### ISSUE TITLE
[Misc/Info] Known Issues

### ISSUE THREAD

**Issue by trickerer** [trickerer/Trinity-Bots#1]
1. ~~Vehicles/Controlled spell cooldowns abuse. Each bot's spellcast triggers global cooldown on every spell of player's currently controlled unit.~~ Fixed in 5.2.67a

2. Dungeons:  
~~* Hyjal Battle:what: Bosses do not give loot if killed by raid full of bots  
Why: You need to do at least 25% damage (625 - 800k) as PLAYER (or pet) damage, it is set within script (instead of player controlled). So raid with players hehe~~ Fixed in 4.16.41a

3. ~~Console DB Errors 'CreatureTextMgr: Could not find TextGroup %u for Creature(%s) GuidLow %u Entry %u. Ignoring'why: Bots are non-pet creatures and being picked up by some scripts. Just ignore it~~ Fixed

4. ~~Level 37. There is a weird bug in TC code which does not allow players to receive creature whisper messages at level 37. This affects all creatures, not just bots~~ Fixed in 4.16.41a

5. If more than 100 bots are spawned in same spot (i. e. by Lua script) players will not be able to approach said spot (GMs too) as they will be kicked due to 'flooding' CMSG_GET_MIRRORIMAGE_DATA packets. See config for workaround and don't do that again. Ref #25

6. "partyX / raidX is not in your party" spam. These messages are typically produced by 'Unit Frames' addons trying to get player info from group members, especially in raid group. For reference:  [GetRaidRosterInfo()](https://wowwiki.fandom.com/wiki/API_GetRaidRosterInfo) (can be and is used for both normal and raid group members)

7. Will add later...

**Comment by KliQUer** [comment]
Hi,

how can i increase "You exceed the max npcbot(1)"?

thanks

**Comment by trickerer** [comment]
It seems like all server-side previously considered unsolvable issues finally were hammered out (or now have a workaround)

Unbelievable

**Comment by biglad** [comment]
did a work around the player% not in party

https://mgawow.online/addons/NoPartySpam.zip
