### ISSUE TITLE
Bots with latest TrinityCore 3.3.5 crash / build impossible

### ISSUE THREAD

**Issue by x92mko** [trickerer/Trinity-Bots#100]
Hi all,

I have pulled the latest trinity core 3.3.5, compiled it and it worked well. 
Then I applied the latest bots patch, unfortunately with errors and errors within the compiling. 
I already have build several servers with bots, all of them worked well but this is strange. Let me show you, I hope you can help :-) thanks for that in advance! 

Error List in Visual Studio:

**E0020**	identifier "p_time" is undefined	game	D:\_SERVER\Entwicklung\TrinityCore\src\server\game\Entities\Player\Player.cpp	6255	
Error	

**C2065**	'p_time': undeclared identifier	game	D:\_SERVER\Entwicklung\TrinityCore\src\server\game\Entities\Player\Player.cpp	6255	

**LNK1181**	cannot open input file '..\game\Release\game.lib'	worldserver	D:\_SERVER\Entwicklung\BUILD\Build 02 (Bots)\src\server\worldserver\LINK	1	
Error (active)	

Code Line 6253 - 6256 tells: 

    //NpcBot mod: Update
    if (_botMgr)
        _botMgr->Update(p_time);
    //end Npcbot

Copied from GitBash:
$ patch -p1 < NPCBots.patch
(Stripping trailing CRs from patch; use --binary to disable.)
patching file README.md
(Stripping trailing CRs from patch; use --binary to disable.)
patching file sql/Bots/1_world_bot_appearance.sql
(Stripping trailing CRs from patch; use --binary to disable.)
patching file sql/Bots/2_world_bot_extras.sql
(Stripping trailing CRs from patch; use --binary to disable.)
patching file sql/Bots/3_world_bots.sql
(Stripping trailing CRs from patch; use --binary to disable.)
patching file sql/Bots/4_world_generate_bot_equips.sql
(Stripping trailing CRs from patch; use --binary to disable.)
patching file sql/Bots/5_world_botgiver.sql
(Stripping trailing CRs from patch; use --binary to disable.)
patching file sql/Bots/characters_bots.sql
(Stripping trailing CRs from patch; use --binary to disable.)
patching file sql/Bots/locales/zhCN/npc_text_locale.sql
(Stripping trailing CRs from patch; use --binary to disable.)
patching file sql/Bots/merge_sqls_characters_unix.sh
(Stripping trailing CRs from patch; use --binary to disable.)
patching file sql/Bots/merge_sqls_characters_windows.bat
(Stripping trailing CRs from patch; use --binary to disable.)
patching file sql/Bots/merge_sqls_world_unix.sh
(Stripping trailing CRs from patch; use --binary to disable.)
patching file sql/Bots/merge_sqls_world_windows.bat
(Stripping trailing CRs from patch; use --binary to disable.)
patching file sql/Bots/updates/characters/2020_05_15_characters_npcbot_NPCBots_4.7.8a-4.7.27a.sql
(Stripping trailing CRs from patch; use --binary to disable.)
patching file sql/Bots/updates/characters/2020_06_21_characters_npcbot_43fceb98.sql
(Stripping trailing CRs from patch; use --binary to disable.)
patching file sql/Bots/updates/characters/2020_10_08_characters_npcbot_NPCBots_4.7.34a-4.7.39a.sql
(Stripping trailing CRs from patch; use --binary to disable.)
patching file sql/Bots/updates/characters/2021_01_04_characters_npcbot.sql
(Stripping trailing CRs from patch; use --binary to disable.)
patching file sql/Bots/updates/characters/2021_01_24_characters_npcbot_stats.sql
(Stripping trailing CRs from patch; use --binary to disable.)
patching file sql/Bots/updates/world/2020_07_08_creature_template_npcbot_extras.sql
(Stripping trailing CRs from patch; use --binary to disable.)
patching file sql/Bots/updates/world/2020_09_25_creature_template.sql
(Stripping trailing CRs from patch; use --binary to disable.)
patching file sql/Bots/updates/world/2020_10_14_creature_classlevelstats.sql
(Stripping trailing CRs from patch; use --binary to disable.)
patching file sql/Bots/updates/world/2020_10_14_creature_template.sql
(Stripping trailing CRs from patch; use --binary to disable.)
patching file sql/Bots/updates/world/2020_10_15_creature_template_npcbot_extras.sql
(Stripping trailing CRs from patch; use --binary to disable.)
patching file sql/Bots/updates/world/2020_11_07_npc_text.sql
(Stripping trailing CRs from patch; use --binary to disable.)
patching file sql/Bots/updates/world/2020_12_11_npc_text.sql
(Stripping trailing CRs from patch; use --binary to disable.)
patching file sql/Bots/updates/world/2021_01_04_npc_text.sql
(Stripping trailing CRs from patch; use --binary to disable.)
patching file sql/Bots/updates/world/2021_01_05_npc_text.sql
(Stripping trailing CRs from patch; use --binary to disable.)
patching file sql/Bots/updates/world/2021_01_08_npc_text.sql
(Stripping trailing CRs from patch; use --binary to disable.)
patching file sql/Bots/updates/world/2021_02_01_npc_text.sql
(Stripping trailing CRs from patch; use --binary to disable.)
patching file sql/Bots/updates/world/2021_03_29_npc_text.sql
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/common/Utilities/EventProcessor.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/database/Database/Implementation/CharacterDatabase.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/database/Database/Implementation/CharacterDatabase.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/AI/CoreAI/UnitAI.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/AI/NpcBots/bot_Events.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/AI/NpcBots/bot_GridNotifiers.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/AI/NpcBots/bot_ai.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/AI/NpcBots/bot_ai.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/AI/NpcBots/bot_archmage_ai.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/AI/NpcBots/bot_bm_ai.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/AI/NpcBots/bot_dark_ranger_ai.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/AI/NpcBots/bot_death_knight_ai.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/AI/NpcBots/bot_dreadlord_ai.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/AI/NpcBots/bot_druid_ai.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/AI/NpcBots/bot_hunter_ai.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/AI/NpcBots/bot_mage_ai.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/AI/NpcBots/bot_paladin_ai.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/AI/NpcBots/bot_priest_ai.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/AI/NpcBots/bot_rogue_ai.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/AI/NpcBots/bot_shaman_ai.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/AI/NpcBots/bot_spellbreaker_ai.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/AI/NpcBots/bot_sphynx_ai.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/AI/NpcBots/bot_warlock_ai.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/AI/NpcBots/bot_warrior_ai.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/AI/NpcBots/botcommands.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/AI/NpcBots/botcommon.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/AI/NpcBots/botdatamgr.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/AI/NpcBots/botdatamgr.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/AI/NpcBots/botdpstracker.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/AI/NpcBots/botdpstracker.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/AI/NpcBots/botdump.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/AI/NpcBots/botdump.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/AI/NpcBots/botgiver.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/AI/NpcBots/botmgr.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/AI/NpcBots/botmgr.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/AI/NpcBots/bpet_ai.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/AI/NpcBots/bpet_ai.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/AI/NpcBots/bpet_archmage.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/AI/NpcBots/bpet_dark_ranger.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/AI/NpcBots/bpet_death_knight.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/AI/NpcBots/bpet_dreadlord.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/AI/NpcBots/bpet_druid.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/AI/NpcBots/bpet_hunter.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/AI/NpcBots/bpet_mage.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/AI/NpcBots/bpet_priest.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/AI/NpcBots/bpet_shaman.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/AI/NpcBots/bpet_warlock.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/Combat/CombatManager.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/Combat/ThreatManager.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/Conditions/ConditionMgr.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/DataStores/DBCStores.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/DataStores/DBCStores.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/DungeonFinding/LFGMgr.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/DungeonFinding/LFGScripts.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/Entities/Creature/Creature.cpp
Hunk #19 succeeded at 3544 (offset 12 lines).
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/Entities/Creature/Creature.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/Entities/Creature/CreatureData.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/Entities/Creature/TemporarySummon.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/Entities/Creature/enuminfo_CreatureData.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/Entities/Object/Object.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/Entities/Player/KillRewarder.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/Entities/Player/Player.cpp
Hunk #1 succeeded at 104 (offset 1 line).
Hunk #2 succeeded at 408 (offset -4 lines).
Hunk #3 succeeded at 448 (offset -4 lines).
Hunk #4 succeeded at 6250 with fuzz 2 (offset 4881 lines).
Hunk #5 FAILED at 1820.
Hunk #6 FAILED at 2011.
Hunk #7 FAILED at 2313.
Hunk #8 FAILED at 2452.
Hunk #9 FAILED at 2533.
Hunk #10 FAILED at 2701.
Hunk #11 FAILED at 4439.
Hunk #12 succeeded at 6843 (offset -5 lines).
Hunk #13 succeeded at 21764 (offset -5 lines).
Hunk #14 succeeded at 22049 (offset -5 lines).
Hunk #15 succeeded at 23916 (offset -5 lines).
7 out of 15 hunks FAILED -- saving rejects to file src/server/game/Entities/Player/Player.cpp.rej
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/Entities/Player/Player.h
Hunk #1 succeeded at 81 (offset 1 line).
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/Entities/Totem/Totem.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/Entities/Unit/StatSystem.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/Entities/Unit/Unit.cpp
Hunk #1 succeeded at 78 (offset 1 line).
Hunk #2 succeeded at 699 (offset 4 lines).
Hunk #3 succeeded at 727 (offset 4 lines).
Hunk #4 succeeded at 1015 (offset 4 lines).
Hunk #5 succeeded at 1089 (offset 4 lines).
Hunk #6 succeeded at 1244 (offset 4 lines).
Hunk #7 succeeded at 1265 (offset 4 lines).
Hunk #8 succeeded at 1561 (offset 4 lines).
Hunk #9 succeeded at 1691 (offset 4 lines).
Hunk #10 succeeded at 1802 (offset 4 lines).
Hunk #11 succeeded at 2220 (offset 4 lines).
Hunk #12 succeeded at 2243 (offset 4 lines).
Hunk #13 succeeded at 2284 (offset 4 lines).
Hunk #14 succeeded at 2659 (offset 4 lines).
Hunk #15 succeeded at 2685 (offset 4 lines).
Hunk #16 succeeded at 2745 (offset 4 lines).
Hunk #17 succeeded at 2779 (offset 4 lines).
Hunk #18 succeeded at 2812 (offset 4 lines).
Hunk #19 succeeded at 2856 (offset 4 lines).
Hunk #20 succeeded at 3967 (offset 4 lines).
Hunk #21 succeeded at 5740 (offset 4 lines).
Hunk #22 succeeded at 5844 (offset 4 lines).
Hunk #23 succeeded at 6450 (offset 12 lines).
Hunk #24 succeeded at 6483 (offset 12 lines).
Hunk #25 succeeded at 6773 (offset 12 lines).
Hunk #26 succeeded at 7111 (offset 12 lines).
Hunk #27 succeeded at 7152 (offset 12 lines).
Hunk #28 succeeded at 7185 (offset 12 lines).
Hunk #29 succeeded at 7416 (offset 12 lines).
Hunk #30 succeeded at 7640 (offset 12 lines).
Hunk #31 succeeded at 7785 (offset 12 lines).
Hunk #32 succeeded at 8192 (offset 12 lines).
Hunk #33 succeeded at 8331 (offset 12 lines).
Hunk #34 succeeded at 8420 (offset 12 lines).
Hunk #35 succeeded at 8677 (offset 12 lines).
Hunk #36 succeeded at 9104 (offset 14 lines).
Hunk #37 succeeded at 9186 (offset 14 lines).
Hunk #38 succeeded at 10361 (offset 7 lines).
Hunk #39 succeeded at 10383 (offset 7 lines).
Hunk #40 succeeded at 10772 (offset 7 lines).
Hunk #41 succeeded at 10927 (offset 7 lines).
Hunk #42 succeeded at 11208 (offset 7 lines).
Hunk #43 succeeded at 11397 (offset 7 lines).
Hunk #44 succeeded at 12190 (offset 1 line).
Hunk #45 succeeded at 12219 (offset 1 line).
Hunk #46 succeeded at 12257 (offset 1 line).
Hunk #47 succeeded at 12280 (offset 1 line).
Hunk #48 succeeded at 12462 (offset 1 line).
Hunk #49 succeeded at 12528 (offset 1 line).
Hunk #50 succeeded at 12787 (offset -10 lines).
Hunk #51 succeeded at 13561 (offset -10 lines).
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/Entities/Unit/Unit.h
Hunk #1 succeeded at 1162 (offset 1 line).
Hunk #2 succeeded at 1709 (offset 9 lines).
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/Entities/Vehicle/Vehicle.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/Globals/ObjectMgr.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/Globals/ObjectMgr.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/Groups/Group.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/Groups/Group.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/Handlers/ItemHandler.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/Handlers/SpellHandler.cpp
Hunk #2 succeeded at 636 (offset 1 line).
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/Maps/Map.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/Maps/MapManager.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/Movement/MotionMaster.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/OutdoorPvP/OutdoorPvP.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/Scripting/ScriptMgr.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/Scripting/ScriptMgr.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/Server/WorldSession.cpp
Hunk #1 succeeded at 55 (offset 1 line).
Hunk #2 succeeded at 482 (offset 4 lines).
Hunk #3 succeeded at 1635 (offset 4 lines).
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/Spells/Auras/SpellAuraEffects.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/Spells/Auras/SpellAuras.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/Spells/Spell.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/Spells/Spell.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/Spells/SpellEffects.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/game/Spells/SpellInfo.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/scripts/Commands/cs_npc.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/scripts/Northrend/Naxxramas/boss_four_horsemen.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/scripts/Spells/spell_dk.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/scripts/Spells/spell_druid.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/scripts/Spells/spell_generic.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/scripts/Spells/spell_hunter.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/scripts/Spells/spell_mage.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/scripts/Spells/spell_paladin.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/scripts/Spells/spell_priest.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/scripts/Spells/spell_rogue.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/scripts/Spells/spell_shaman.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/scripts/Spells/spell_warrior.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/shared/DataStores/DBCStructure.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/shared/DataStores/DBCfmt.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/shared/SharedDefines.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/server/worldserver/worldserver.conf.dist

**Comment by trickerer** [comment]
#99
