### ISSUE TITLE
Help: Changing name of specific bots?

### ISSUE THREAD

**Issue by Sokipok** [trickerer/Trinity-Bots#102]
Hi, I'm trying to change the name of some bots.

When I change their names in creature_template, their names are only changed in the .npcb lookup list and when they perform whispers to me. The names over their heads, in party ui and seemingly everywhere else remain as their original bot names.

I've tried making sure to clear/delete them all before performing the change and resummoning them as well, but no luck.

Can anyone help me out and tell me how to do this? :)
![differentname](https://user-images.githubusercontent.com/45133871/121559019-7b338f80-ca16-11eb-8975-ccf5749e6d63.png)

**Comment by trickerer** [comment]
You need to delete client cache.

**Comment by Sokipok** [comment]
> You need to delete client cache.

Such a simple solution! Thank you :)
