### ISSUE TITLE
Npcbots do not enter BG

### ISSUE THREAD

**Issue by cybrarian** [trickerer/Trinity-Bots#103]
Hi,
First thank you for your module, we really enjoy playing with Npcbots ; they're doing so well !

Here's the issue : the Npcbots do not enter BGs anymore ; i'm so sad because of that ; in the previous version (late november 2020) there was no issue with the Battlegrounds, whatever the level was, a Player with 4 Npcbots could enter all the availlable BGs. Usually it was achieve by clicking the "join party" button, NOT the "join as group" button.

So, as we were happy with the previous version, I've downloaded your last release and compiled it into a fresh server and updated my DB. But now, the Npcbots do not enter BGs anymore :(

My server is :+1: 
 TrinityCore rev. 6cc64c4b2b06+ 2021-06-22 16:42:01 +0200 (npcbots_3.3.5 branch) (Unix, RelWithDebInfo, Static)

My configuration file reads :
NpcBot.Enable.Dungeon       = 1
NpcBot.Enable.Raid          = 1
NpcBot.Enable.BG            = 1
NpcBot.Enable.Arena         = 0
NpcBot.Enable.DungeonFinder = 1

What could go wrong ?

-- Cyb

**Comment by trickerer** [comment]
Works for me regardless of join type

![snap2](https://user-images.githubusercontent.com/1254989/123350997-67e00280-d586-11eb-83a9-fc10bb4595e4.JPG)

**Comment by cybrarian** [comment]
Yes I see, **great** ! Lots of fun ahead, certainly :D  

May I ask the question again ? _What could go wrong_ ?
Is it related to the DB or the server ? Or maybe the Eluna patch ?
Please give me a hint how to fix the issue, or at least, where to investigate.

Thank you ;)

**Comment by cybrarian** [comment]
Hi,

The issue is NOT DB related ; which is good because we've done much work on the world.

I've just done a fresh compilation of your last release without ANY other patch and ... no more issue.
TrinityCore rev. bfbdbd09b52b 2021-06-25 07:09:53 +0700 (npcbots_3.3.5 branch) (Unix, RelWithDebInfo, Static)

Though, Eluna has NOT been installed yet.

![WoWScrnShot_062621_235425](https://user-images.githubusercontent.com/1935236/123526980-e13d3980-d6db-11eb-9945-61ae7380064c.jpg)
