### ISSUE TITLE
LoadGrid throws error

### ISSUE THREAD

**Issue by SimonChenyongxing** [trickerer/Trinity-Bots#105]
I sprawn 35 bots in one place,zhen reboot the server.
server stops at map->LoadGrid(pos_x, pos_y),and throws an error.

**Comment by trickerer** [comment]
Using last TrinityCore - no errors.

> Starting Map System
> Starting NpcBot system...
> \>> Bot appearance data loaded
> \>> Bot race data loaded
> \>> Loaded 79 bot data entries
> \>> Spawned 79 npcbot(s) within 2 grid(s) in 181 ms

Any custom changes?

**Comment by SimonChenyongxing** [comment]
I merge this (http://rochet2.github.io/Transmogrification.html)into the code.  
Do they influence each other?

**Comment by SimonChenyongxing** [comment]
I spawns 5 bots, there is no error. then I spawns 35 bots,gets the error.
I clears characters_npcbot and characters_npcbot_stats,server can start. but it will stop even I spawn one bot.

**Comment by trickerer** [comment]
Yes they do. Post a crash log.

Also, https://github.com/trickerer/Trinity-Bots/issues/101

**Comment by SimonChenyongxing** [comment]
Thanks a lot.
It is resolved.
