### ISSUE TITLE
Update Please 

### ISSUE THREAD

**Issue by iceyman** [trickerer/Trinity-Bots#107]
Could u please update again i have chnaged from windows to linux and patch not working 

patching file src/server/scripts/Northrend/Naxxramas/boss_four_horsemen.cpp
patching file src/server/scripts/Spells/spell_dk.cpp
Hunk #1 FAILED at 397.
Hunk #2 FAILED at 2343.
2 out of 2 hunks FAILED -- saving rejects to file src/server/scripts/Spells/spel                                                                                                                                                             l_dk.cpp.rej
patching file src/server/scripts/Spells/spell_druid.cpp
patching file src/server/scripts/Spells/spell_generic.cpp
patching file src/server/scripts/Spells/spell_hunter.cpp
patching file src/server/scripts/Spells/spell_mage.cpp
Hunk #1 FAILED at 1452.
1 out of 1 hunk FAILED -- saving rejects to file src/server/scripts/Spells/spell                                                                                                                                                             _mage.cpp.rej
patching file src/server/scripts/Spells/spell_paladin.cpp
Hunk #1 FAILED at 169.
Hunk #2 FAILED at 183.
Hunk #3 succeeded at 458 (offset -77 lines).
Hunk #4 succeeded at 1490 (offset -358 lines).
2 out of 4 hunks FAILED -- saving rejects to file src/server/scripts/Spells/spel                                                                                                                                                             l_paladin.cpp.rej
patching file src/server/scripts/Spells/spell_priest.cpp
patching file src/server/scripts/Spells/spell_rogue.cpp
Hunk #1 FAILED at 126.
Hunk #2 FAILED at 137.
Hunk #3 succeeded at 563 (offset -111 lines).
Hunk #4 succeeded at 586 (offset -111 lines).
Hunk #5 FAILED at 845.
Hunk #6 FAILED at 1082.
4 out of 6 hunks FAILED -- saving rejects to file src/server/scripts/Spells/spel                                                                                                                                                             l_rogue.cpp.rej
patching file src/server/scripts/Spells/spell_shaman.cpp
Hunk #4 succeeded at 1872 (offset 1 line).
Hunk #5 succeeded at 1912 (offset 1 line).
patching file src/server/scripts/Spells/spell_warrior.cpp
patching file src/server/shared/DataStores/DBCStructure.h
patching file src/server/shared/DataStores/DBCfmt.h
patching file src/server/shared/SharedDefines.h
patching file src/server/worldserver/worldserver.conf.dist

**Comment by trickerer** [comment]
https://github.com/trickerer/Trinity-Bots/commit/5a6db4f669a7bcd4f96cc26d3a0355058c100672
