### ISSUE TITLE
I got a crash in Energize

### ISSUE THREAD

**Issue by SimonChenyongxing** [trickerer/Trinity-Bots#108]
Here is the info. Do you have some advice to debug it. Or what DB data I need to check?

Call stack:
Address   Frame     Function      SourceFile
00007FF7D1991493  0000003B5B6FB7C0  Spell::EffectTriggerMissileSpell+303  C:\Trinity\src\server\game\Spells\SpellEffects.cpp line 875
00007FF7D19FEFE0  0000003B5B6FB880  ByteBuffer::textlike+400  C:\Trinity\src\server\shared\Packets\ByteBuffer.cpp line 176
00007FF7D19FEB82  0000003B5B6FB910  ByteBuffer::put+F2  C:\Trinity\src\server\shared\Packets\ByteBuffer.cpp line 141
00007FF7D1866F70  0000003B5B6FBAE0  OpcodeTable::ValidateAndSetClientOpcode<void (__cdecl WorldSession::*)(WorldPacket &),&WorldSession::HandleDuelCancelledOpcode>+3A0  C:\Trinity\src\server\game\Server\Protocol\Opcodes.cpp line 92
00007FF7D187022A  0000003B5B6FE740  OpcodeTable::ValidateAndSetClientOpcode<void (__cdecl WorldSession::*)(WorldPacket &),&WorldSession::HandleInspectOpcode>+A  C:\Trinity\src\server\game\Server\Protocol\Opcodes.cpp line 77
00007FF7D1871F02  0000003B5B6FE780  OpcodeTable::ValidateAndSetClientOpcode<void (__cdecl WorldSession::*)(WorldPacket &),&WorldSession::HandleLearnPreviewTalents>+72  C:\Trinity\src\server\game\Server\Protocol\Opcodes.cpp line 80
00007FF7D157E4BB  0000003B5B6FE930  ObjectMgr::LoadGameObjects+10BB  C:\Trinity\src\server\game\Globals\ObjectMgr.cpp line 2471
00007FF7D15019B9  0000003B5B6FEB70  GameObject::SwitchDoorOrButton+9  C:\Trinity\src\server\game\Entities\GameObject\GameObject.cpp line 1459
00007FF7D1303801  0000003B5B6FEBE0  spell_q12735_song_of_cleansing::spell_q12735_song_of_cleansing_SpellScript::`scalar deleting destructor'+11
00007FF7D1302747  0000003B5B6FEF70  spell_q11010_q11102_q11023_aggro_check_aura::spell_q11010_q11102_q11023_aggro_check_aura_AuraScript::`scalar deleting destructor'+17
00007FF7D0E93A29  0000003B5B6FEFF0  AsyncAcceptor::Bind+589  C:\Trinity\src\server\shared\Networking\AsyncAcceptor.h line 99
00007FF7D0EA1A5F  0000003B5B6FF900  boost::system::detail::system_category_default_error_condition_win32+31F  C:\local\boost_1_72_0\boost\system\detail\system_category_win32.hpp line 306
00007FF7D1A8699C  0000003B5B6FF940  <lambda_8a63dc39cafdd455e2561caa0073f65a>::operator()+4BC  C:\Trinity\src\common\Utilities\StartProcess.cpp line 102
00007FFBCD3C7974  0000003B5B6FF970  BaseThreadInitThunk+14
00007FFBCFA4A2F1  0000003B5B6FF9F0  RtlUserThreadStart+21

Local Variables And Parameters

Call stack:
Address   Frame     Function      SourceFile
00007FF7D1991493  0000003B5B6FB7C0  Spell::EffectTriggerMissileSpell+303  C:\Trinity\src\server\game\Spells\SpellEffects.cpp line 875
	Local Spell* this = NULL
	Parameter SpellEffIndex effIndex = 0x3B5B6FB7F8
	Parameter SpellEffIndex effIndex = 0x3B5B6FB980
	Local CastSpellExtraArgs args
		unsigned int TriggerFlags = 0x60172A20
		Item* CastItem = 0x676E6964616F
			Object
				unsigned int m_objectType = 0x676E69646177 <Unable to read memory>
				int m_objectTypeId = 0x676E6964617B <Unable to read memory>
				unsigned int m_updateFlag = 0x676E6964617F <Unable to read memory>
				int* m_int32Values = <Unable to read memory>
				unsigned int* m_uint32Values = <Unable to read memory>
				float* m_floatValues = <Unable to read memory>
				UpdateMask _changesMask = 0x676E6964618F
				unsigned int m_valuesCount = 0x676E6964619F <Unable to read memory>
				unsigned int _fieldNotifyFlags = 0x676E696461A1 <Unable to read memory>
				bool m_objectUpdated = 0x676E696461A3 <Unable to read memory>
				bool m_inWorld = 0x676E696461A4 <Unable to read memory>
				bool m_isNewObject = 0x676E696461A5 <Unable to read memory>
				PackedGuid m_PackGUID = 0x676E696461A7
			Loot loot
				std::vector<LootItem,std::allocator<LootItem> > items = 0x676E696461D7
				std::vector<LootItem,std::allocator<LootItem> > quest_items = 0x676E696461EF
				unsigned int gold = 0x676E69646207 <Unable to read memory>
				unsigned int unlootedCount = 0x676E6964620B <Unable to read memory>
				ObjectGuid roundRobinPlayer = 0x676E6964620F <Unable to read memory>
				ObjectGuid lootOwnerGUID = 0x676E69646217 <Unable to read memory>
				unsigned int loot_type = 0x676E6964621F <Unable to read memory>
				unsigned int maxDuplicates = 0x676E69646220 <Unable to read memory>
				unsigned int containerID = 0x676E69646223 <Unable to read memory>

**Comment by trickerer** [comment]
I don't see anything npcbots related in this crashlog

`spell_q11010_q11102_q11023_aggro_check_aura` is just a small script, looks pretty safe too.
