### ISSUE TITLE
npcb delete crashed

### ISSUE THREAD

**Issue by SimonChenyongxing** [trickerer/Trinity-Bots#109]
When I select one npcbot, and use .npcb delete. I crashes.
I tracked to here: c->GetRespawnPosition(x, y, z) returns random x and y. why,how to fix it?
I have checked the DB, position_x and position_y all are right.
void Map::RemoveFromActive(Creature* c)
{
    RemoveFromActiveHelper(c);

    // also allow unloading spawn grid
    if (!c->IsPet() && c->GetSpawnId())
    {
        float x, y, z;
        c->GetRespawnPosition(x, y, z);
        GridCoord p = Trinity::ComputeGridCoord(x, y);

**Comment by trickerer** [comment]
Can't confirm on last Trinity

Post debug crash log and custom changes, and maybe I'll be able to help you
