### ISSUE TITLE
Request: Raid Icons for DPS and Tanking targeting

### ISSUE THREAD

**Issue by itdevsteve** [trickerer/Trinity-Bots#11]
Just like bot_ai::BuffAndHealGroup() looks at GetHealTargetIconFlags to allow healing outside of the party, would it be possible to do something similar with DPS and Tanking bots?

For example, putting a skull icon on a particular NPC would cause the bots to attack that target.

As a secondary to that particular request, to have a Tank override to that as well.  If the DPS icon was out, then the tank would use that target, since it has the DPS role enabled too.  But if the tank icon was present, then the tank would only care about that icon, ignoring the DPS one.

That would allow fights, such as Bronjahm in "Forge of Souls" (who you have to kill the corrupted soul fragment before it reaches the boss or he heals) to be able to be beaten using just yourself and your NPCbot team.  They won't pull off the boss right now for anything that I can find.  If you move too far, the tank pulls back to you along with the dps and the boss is healed.

I have tried to get something to work, but I don't know the code well enough yet to pull it off.

I don't see this as a big departure from how groups would work in the retail game, and think its fair to apply to the bots as well.

**Comment by itdevsteve** [comment]
https://www.bountysource.com/issues/91733656-request-raid-icons-for-dps-and-tanking-targeting

**Comment by trickerer** [comment]
I can do that.
Keep in mind though, using tank/dps icons in some encounters may actually make them more difficult, like Hodir or something.

**Comment by itdevsteve** [comment]
Yes, i can completely understand that for raids.  I haven't had any good ideas about managing raid sized groups yet, that may be too much to handle with one person.  But I think 5 man dungeons are doable.

**Comment by trickerer** [comment]
Check it out, check config, check README. I added some support for off-tanking, thought that should be pretty cool.

**Comment by itdevsteve** [comment]
Works Beautifully! Thank you so much!  Added an extra tip to the bounty!
