### ISSUE TITLE
Паладин бот не хилит игрока или союзных ботов

### ISSUE THREAD

**Issue by Parkan1986** [trickerer/Trinity-Bots#110]
Суть проблемы такова,имеется в наличии несколько ботов в команде среди которых есть шаман и паладин.
Во время битвы если у ботов падает хп ниже 90% то шаман бот лечит игрока(или ботов) постоянно,когда паладин не лечит никого даже в режиме таланатов Холи и включенном лечении в в группе Role.
Но если сменить паладину на любую другую ветку талантов(не обязательно с холи а если стояла другая типа защиты или ретро),то паладин начинает хилить игрока и союзных ботов как обычно(когда здоровье меньше 90% или 85 %).Проблема появляться вновь если игрок вышел с сервера  и перезашел даже не перезапуская сервер,т.е другие боты хилят,а паладин не хилит совсем до того момента пока ему не сменишь спек талантов на любой другой.

Эта проблема обнаружена была как и на этом сорсе https://github.com/trickerer/TrinityCore-3.3.5-with-NPCBots
так и на другом https://github.com/zaicopx/TrinityCore-Single-Player

**Comment by trickerer** [comment]
Взял паладина и шамана, не вижу ничего подобного. Приведи класс, левел игрока и набор ботов с ролями и талантами

**Comment by Parkan1986** [comment]
Игрок воин, боты-шаман-рестор(роли дпс и хил), паладин-холи( роли дпс и хил), рога-комбат( дпс), хант-бм( дпс ranged). Уровень с 1го и по 15 точно это происходит. Если шаман все время подхиливает в любой ветке при достижении игроком или ботом порога здоровья ниже 85-90, % то паладин начинает хилить только после смены специализации на любую другую.
