### ISSUE TITLE
NPC combat distance ignored

### ISSUE THREAD

**Issue by awesomo582** [trickerer/Trinity-Bots#112]
not sure if im on an old version of the bots, just using a repack, ranged ai don't pursue enemies or run away when enemies get to close

**Comment by awesomo582** [comment]
if it was fixed not sure how to update the bots themselves

**Comment by trickerer** [comment]
There is no way to fix it in a repack as you need to modify source code & rebuild

**Comment by awesomo582** [comment]
So this is the repacks problem?

**Comment by trickerer** [comment]
Yep. Ask its author for an updated version.
