### ISSUE TITLE
command to prioritize follow over attack ?

### ISSUE THREAD

**Issue by Saiska** [trickerer/Trinity-Bots#113]
could it be possible to have some sort of 4th command, a stopfully but follow ?

actually, stopfully ask the bots to also stay, it would be helpful to have a command like "prioritize following me, and don't go attacking during this time, or attack only if you can while following me, like caster with dot/hot or instant cast".  

a "force follow" command of a sort.

example where it's useful: 
heigan the unclean (naxx), the dance would be possible if the bots were to follow the player during the time.
events with aoe on ground which you can see coming, like illidan eye beam or Utgarde pinaacle, the boss which put ice on ground (the bot avoid staying in but can die on the first ticks)
any avoidable damage when you can lead a part of the group when you play dps, but they don't follow because they focus attacking

**Comment by trickerer** [comment]
> stopfully but follow

`npcbot dist 0` does that. Also, stopfully halts all bot's activity while 0 distance only prevents them from attacking anything (they will still use heals and may die if they stop for a big cast)

Now, there is no functionality that would make bots *priotitize* following and only attack with instant spells and such and it probably shouldn't come from a command - a group-wide gossip menu option seems more appropriate, something like 'if player moves only follow at minimum distance and only use instacast abilities to never stop'

**Comment by Saiska** [comment]
Thank you, i will try that on heigan and also the 4 knights, where i searched a way to have a heal to follow me while the rest of the bot focus the 2 other knights

also - i'm very sorry i'm posting this here in issues, else i don't know where to ask - if you don't mind some questions i didn't find any clue in the faq ?
- the bots are using the "use" part in the trinket or it's useless for them ? (even if they use it every time when it's up like some cd)
- in the same vein does the set bonus apply to them ?
- is it me or making me "main tank" via raid tool (when i tank obviously) avoid the pets (hunter pet, also shaman wolfs cd) to taunt my target ? Or it that just coincidence ?

Very big thanks for your work btw, i enjoy a wow in solo i didn't think it was possible, and it's very challenging in its own way to find how to defeat boss with the bots, even if in some boss i had to change some spell in the dbc to remove some things not doable in solo.

**Comment by Saiska** [comment]
follow up. i have tried the dist 0 and it does work, unless i put a dps sign on a target. in this case, they discard the distance and go attacking anyway ?
I tried to split the raid (10) on thaddius, making 4 of the bot at dist 0 and 5 unchanged, hoping the 5 would follow the dps sign while the 4 would follow me; they all 9 jumped on the sign on the other platform.

also, a room for improvement, it comes to me after onyxia, would it be possible to have 3 dps sign instead of one ?
1- the first unchanged, current behavior of the dps sign
2- a dps sign prioritized over the 1st for long range dps
3- the same but for melee

**Comment by trickerer** [comment]
> - the bots are using the "use" part in the trinket or it's useless for them ? (even if they use it every time when it's up like some cd)
> - in the same vein does the set bonus apply to them ?
> - is it me or making me "main tank" via raid tool (when i tank obviously) avoid the pets (hunter pet, also shaman wolfs cd) to taunt my target ? Or it that just coincidence ?

- No, bots cannot use items currently, I tried to systematize item use conditions once but didn't come up with anything good enough.
- Set bonuses do apply, except class spell mods `Increases damage done by Mortal Strike by 5%` and stuff
- Bots respect the MAIN_TANK raid role which is set by `/mt` command, if your addon does the same bots won't try to get every single mob off you, but your off-tanking bots will still try to taunt the boss to try to save you if take too much damage. This applies to all situations and all tanks actually, pets too if they are able to taunt.

> follow up. i have tried the dist 0 and it does work, unless i put a dps sign on a target. in this case, they discard the distance and go attacking anyway ? edit: also just found that if i have a target, they focus it and discard the distance. dist 0 work only if you have no target. Is it the wanted behavior of dist 0 ? It resolve the heigan problem anyway, but for split-the-raid needs it doesn't.
I tried to split the raid (10) on thaddius, making 4 of the bot at dist 0 and 5 unchanged, hoping the 5 would follow the dps sign while the 4 would follow me; they all 9 jumped on the sign on the other platform.

This is exactly how it's supposed to work, which can be used wisely. But no, you can't really split the raid currently, the only way is to station bots in your secondary group one by one in one spot and not attacking anything, only this way your secondary group of bots will find their own target, and even then they need to be relatively close to you to attack in the first place, so use max follow distance.

Distance settings are not individual, they are for whole formation and not even stored in bot_ai class, they are in BotMgr which is member of Player class.


Additional, split DPS markers are possible, yes. You need to always remember which overlaps with which though. For example:

a target immune to physical damage, which means you need mark for ranged dps AND tanking, so the must overlap, otherwise your tank may decide to just chill without trying to even taunt. And if your ranged DPS maker overlaps with melee of general DPS markers by mistake this won't work. Also you trying to attack such target will still make all bots to jump it.

**Comment by Saiska** [comment]
Thanks for all the clarifications.
 
> the only way is to station bots in your secondary group one by one in one spot and not attacking anything
i did use the stay command in this way on some boss, the problem come then the boss trigger when you enter the room or by weird event in which you can't. it's pretty rare you can position bots around the boss without cheating (.gm on) without triggering the fight. But anyway, even on thaddius, or the 4k, i did find a way to win the fight without split, and for the time being i didn't get blocked by this; even if my mind wonder how i will make it at ulduar, the boss where you must split the raid (hodir or thorim ?).

>a target immune to physical damage, which means you need mark for ranged dps AND tanking, so the must overlap, otherwise your tank may decide to just chill without trying to even taunt. And if your ranged DPS maker overlaps with melee of general DPS markers by mistake this won't work. Also you trying to attack such target will still make all bots to jump it.
A fair point. Actually i'm tanking in raid, essentially because you can make up for 90% of the strategies problem if you are tanking (moving the boss, avoiding cleaves for the bot, and so on) so i didn't think about the tanking problem.
As there is only one sign for tanking, i usually off tank if there is the need of 2 tank, so i use the tank sign for the mt and the dps sign if i need a second target to be taken care of, which i will tank. 

Anyway, when i asked for the split i wasn't thinking of the tanking problem, for me the tank should prioritize the tank sign,  then the dps global sign, then the dps melee sign. When i said karazhan, the creatures in question don't need tank anyway. In fact the dps melee sign is somehow useless, just a second sign for long range would be enough, even knowing no tank will go on it.
The dps long range sign, i see it used in most way when you have to focus a target which doesn't need tanking because it's too far (onixia when flying). Because using the general dps sign make the melee wait under her, and not focus the adds. A obvious way to counter this would be to take down the adds and focus onixia; but the adds keep coming so its hard to make any dps on onixia if you can't say to the long range to focus her. Big kudos to the dot from the fire mage and the warlock however.

**Comment by Saiska** [comment]
following up, if you're interested in this kind of infos, if not just delete the msg i ll take the hint.
Again, full 24 bot in raid 25 wotlk, trying to overcome the bot factor with new strats, and at worst the less possible change in spells/encounter script. This time, ulduar. Took me days to clean up to the 4 guardian it on the contrary of naxx.

As i suspected, thorim is not feasible not because you can't split the raid ( i tried with /stay on half the bot) but because thorim doesn't register the bot as player staying in the arena. But as i'm sure youre well aware, a lot of script don't acknowledge the bots as player, and for some boss it's a good thing, as you are to make all the strat be youself (the phase 2 of kelthusad is a good example, as you are the sole target of his spells, you stay far from the raid and manage everything, as the bot don't register the aoe with delay like those on KT and take damage from it and get OS, the best is to stay away from them). So for thorim it was c++ changes to avoid to have to split the raid.

Freya is not feasible either, because of the shrooms. There is this phase where you must go under the shrooms, and the bot obviously don't. again, not found anything else but to remove the spell responsible in the boss script, so the bots are not affected. Like the aoe which damage on delay, it would require the bot to move relativly fast under the shrooms. Not that the "dist 0" trick don't work here, because of the difficulty to move all the bots under a shroom, which has not a very large area, and when in place dps the add; the mechanic take to much time and some other adds have time to pop and it become impossible.

Speaking of the dist 0 trick, which helped me a lot in more than one encounter, the healer taking their sweet time is a problem, especially the one with lot of cast. It's ok for druid or disc priest, but shaman and paladin will die everytime if they have something to heal. (Grobbulus on naxx will see them diying eveytime where the rest of the raid is ok with the dist 0 strat)

For the rest, there is two thing which have come to light which would be great QoL improvements: 
- the capability to stop any aoe by command, to stop the bot from aoe during a fight and focus the dps sign.  Eventually this has to be different for each bot, because you want the tank to aoe and eventually some cac, because they can aoe without breaking their dps on the boss like the casters would (like the mages and their blizzard) - but that's minor, just stoping any aoe would be enough. example on ignis the furnace master, where everybot will aoe at the end of the fight, where you should focus on the boss. Freya too, during the 3 adds, they should monotarget, and during the 10+ add, aoe. but they can't know that, so manually switch the behavior would be th best.
- the same but for any spell in the control category. Freya is a good example where you want to control during the 3 add phase, but absolutely not during the 10+ add phase, and less than absolutly not in the one add phase (the warlock and their bans, so useful during the 3 adds, but just not here).
The capability to change it via dialogue is good, i won't say otherwise, but it has 2 problem: it require you know the name of spells, but mostly it require to make it on every bot. And it's not feasible to switch between some combat where you want aoe/control and some you don't if you're managing more than a group of bots it become tedious. 

Thank you for considering these improvements in a futur iteration

**Comment by Saiska** [comment]
Another ability i had think of since way before, but it became like a matter of life of death (literally, for my character) is the ability to put a sign to NOT dps. Like absolutly not, even if it cost you life, your cycle whatever, don't touch it. CC only.
It's obvious on lady deathwhisper (and a lot of boss which have mc not targetting the bots) at icc when you play cac. You will be MC , and the bots WILL cleave on you like they totally hate you (which you can argue is RP, and i'll agree).
Other special occasion like avoiding killing the princess (last boss lore) in brd for the quest. 
Alas, maybe a brand new sign and mechanic is maybe too much for such a casual use, but maybe if they can check it's not their owner they cleave, it would be great.
