### ISSUE TITLE
npcbot lost

### ISSUE THREAD

**Issue by Keverlac** [trickerer/Trinity-Bots#114]
I left the game with a group that was my npcbot. When I logged back the bot had disappeared from the group. Now I cannot locate it since it is not in its original spawn point. Is there a way to teleport my bot to my position without having it selected? 
This is the third time i have this issue

**Comment by trickerer** [comment]
Try these:

- .go cre id <bot_id>
- .npcb move <bot_id>

If nothing happens that means bot got despawned after death. Which makes them never respawn. I thought I fixed this for good though.

**Comment by Keverlac** [comment]
Indeed, by using the command .go cre id <bot_id> I teleport to the original spawn point of the lost npcbot which is empty :(

**Comment by trickerer** [comment]
Try this query
`SELECT * FROM characters.respawn WHERE spawnId IN (SELECT guid FROM world.creature WHERE id > 70000 AND id <= 71000);`

...and if there is any result
`DELETE FROM characters.respawn WHERE spawnId IN (SELECT guid FROM world.creature WHERE id > 70000 AND id <= 71000);` and restart the server

**Comment by Keverlac** [comment]
Solved! 
Thank you very much for your dedicated work! :)

**Comment by trickerer** [comment]
Glad to see your problem solved.

That's not enough for me though, I still need to track its source. Maybe you could recall what you were doing prior to these occurrences

**Comment by Keverlac** [comment]
I remember i was questing. I move along using .tele when i have to travel far distances.
