### ISSUE TITLE
Metagem "minor speed bonus" make the bot so fast they seem to tp

### ISSUE THREAD

**Issue by Saiska** [trickerer/Trinity-Bots#115]
Equipped a bot with either item 41375 or 41339 (woltk metagem SP+minor speed or AP+minor speed)
And the bot now tp from place to place without animations (i think he's just to fast to display walking/running anim, because attack anim works fine).
Tried to reboot server, dismiss the bot, delete/respawn the bot, but only unequipping the head/and later removing the meta fixed the issue.

**Comment by trickerer** [comment]
I tried it on Dark Ranger and Rogue but can't reproduce that.

Please provide bot name, level and items involved.

**Comment by Saiska** [comment]
Arf, could be a issue on my end, i tried (played?) some things in the core and in the bots code and unknowingly have caused that, sorry to have you waste time.

**Comment by trickerer** [comment]
ok
