### ISSUE TITLE
Question about talents

### ISSUE THREAD

**Issue by awesomo582** [trickerer/Trinity-Bots#116]
using an older version since the repack works, when you pick bot talents there is only spec 1, 2, 3 how can I tell which spec is which in an easy way?

**Comment by trickerer** [comment]
Look at talent trees if you don't have them memoralized

Warrior: Arms Fury Protection
Paladin: Holy Protection Retribution
Rogue: Assassination Combat Subtlety
Hunter: Beastmastery Marksmanship Survival
Priest: Discipline Holy Shadow
DK: Blood Frost Unholy
Shaman: Elemental Enhancement Restoration
Mage: Arcane Fire Frost
Warlock: Affliction Demonology Destruction
Druid: Balance Feral Restoration
