### ISSUE TITLE
Mangle (cat) Debuff on target

### ISSUE THREAD

**Issue by Saiska** [trickerer/Trinity-Bots#117]
I'm trying to correct (correct is a big word) some of the bots dps, because some are where they should (or where i remember they should) whereas some does not what they could.
Note also i didn't update the core and the bots code since somewhere around april, so if somehow it has became tested since, really sorry to make some useless report.

TLDR; Mangle doesn't apply the debuff it should, breaking the cat dps cycle.

So i looked into bot_druid_ai.cpp, in particular line 1071: 

      //Shred
      if (IsSpellReady(SHRED_1, diff) && comboPoints < 4 && energy >= acost(SHRED_1) /* && Rand() < 85*/ &&
          !opponent->HasInArc(float(M_PI), me))
      {
          if (doCast(opponent, GetSpell(SHRED_1)))
              return;
      }
      //Mangle (Cat)
      if (IsSpellReady(MANGLE_CAT_1, diff) && comboPoints < 5 && energy >= acost(MANGLE_CAT_1) &&
          (/*Rand() < 35 ||*/ !opponent->GetAuraEffect(SPELL_AURA_MOD_MECHANIC_DAMAGE_TAKEN_PERCENT, SPELLFAMILY_DRUID, 2312, 1)))
      {
          if (doCast(opponent, GetSpell(MANGLE_CAT_1)))
              return;
      }

(Note that i removed the random part to be sure the problem is not the random)
so normally, a druid cat does more than 50% of his combo on the shred. the two other sources are rake and mangle, but mangle like every each minute.

but i just make a test on patchwork, raid 25, full buff, etc, the druid make this recount detail:
(duration 2minutes 50)
1 Melee 222 - 29.8%
2 Mangle (Cat) 37 - 24.5%
3 Ferocious bite 13 - 15.3%
4 Rip (DoT) 72 - 10.6%
5 Rake (DoT) 28 - 9.5%
6 Shred 9 - 7.6%
7 Rake 10 - 1.5%
(FYI the order should be more like melee, shred, rip, rake, ferocious bite, mangle)
i looked into the aura id, index, they are good, the targeted aura is the one mangle put on the boss; the aura has a one minute duration, so the druid should have at most 3 mangle (cat) on recount, and the rest should be shred. Number indicate it does shred only when the cat is at 4 CP exactly.

So i tested if
GetAuraEffect(SPELL_AURA_MOD_MECHANIC_DAMAGE_TAKEN_PERCENT, SPELLFAMILY_DRUID, 2312, 1)
works, and it alaways return false, i check the spell info its the good aura id, the good display id and index... so i searched why and it seems the mangle debuff is really not put on the target, according to the ui information. Note i created a druid to test fast, and the mangle debuff appear like it should so it occur only on bots. So whether my ui somehow hide the debuff from the bot, or the bot really didn't put the debuff on the target. Either way, the fonction return false every time. 
There should be the mentioned aura on the target: https://wotlkdb.com/?spell=33876 and so the condition for mangle should be false and the druid should shred almost every time, and get 2 combo point instead of the 1 of mangle which will boost his dps immensely.

Note also that rake and rip are mostly where they should without the random, the random is overall too harsh on the druid cat (comparing to other classes), and Ferocious bite is strangely too high, i'm suspecting the druid doesn't maintain a 100% up time on savage roar 5 combo point like it should but i don't have the tools to test it. If i understand the code well, the druid doesn't try to have a Savage roar at 5 combo, it does it as soon as it does not have the buff up and at least a combo point. The correct way would be to make savage roar as soon as the first combo point is made first, then build and maintaining a 5 combo point savage roar during all the fight, because else it become hard to maintain a 5CP Rip all the time too since you need to use your CP too often to maintain SR. Again, i don't count the random to simulate human error. Anyway i'm working on that too and ill post here if i get some interesting result, the main problem here being the main spell misused because of a missing debuff.

I'll continue searching if i can resolve this on my own, but i'm very new to the trinity core so maybe, wishfull thinking, you'll see the problem right away.

**Comment by trickerer** [comment]
The problem was that `GetAuraEffect(AuraType, SpellFamily, spellIcon, effIndex)` only returns true for spells with no spellFamilyFlags. They are supposed to use `GetAuraEffect(AuraType, SpellFamily, flags0, flags1, flags2)` instead.
I wonder how many other such checks are affected... I remember using first function only when checking flags was impossible or ambiguous in results (with SPELLFAMILY_GENERIC) which means... checking every single one of them is... required.

Well anyway,
https://github.com/trickerer/Trinity-Bots/commit/fc98bb96ae0b5a5daa05f47f019f5649dd91047c

(some random lvl 57 naked druid bot DPS)
![kal](https://user-images.githubusercontent.com/1254989/127281665-2079b5f1-e5db-4258-9dc5-1ad0d58b599d.JPG)

**Comment by trickerer** [comment]
https://github.com/trickerer/TrinityCore-3.3.5-with-NPCBots/commit/2210d11cfbe4300db317a1e8f4c2f7270d8c4d9e

**Comment by Saiska** [comment]
warlock AI L755

if (!me->GetAuraEffect(SPELL_AURA_MOD_SPELL_DAMAGE_OF_STAT_PERCENT, SPELLFAMILY_WARLOCK, 0x0, 0x0, 0x0))

if i understood well the 0x0 are the field spell class mask 1,2,3 from spell.dbc

on a side note warlock (any spec, but affli at least should be much higher) dps is weirdly low. They are dead last since the druid got fixed, fighting with the shadow priest and the el sham, but i don't understand why, at least the affli cycle seems ok, the recount show somewhat a acceptable spell damage list, but they are like not even the half of a mage at equivalent ilvl. i know mages are op in wotlk but seems weird through.

**Comment by trickerer** [comment]
The `if (!me->GetAuraEffect(SPELL_AURA_MOD_SPELL_DAMAGE_OF_STAT_PERCENT, SPELLFAMILY_WARLOCK, 208, 0))` check is what's supposed to be there. Checking spell family flags won't work if there aren't any (0x0, 0x0, 0x0).

Warlock is kind of hard to grasp, he relies on bunch of spellmod types unique to the class, and they don't all work for bots I think. And the play style differs greatly for pvp and pve and for each spec. Oh and I have never played warlock really, I've been just using some guides. Warlock used to be much worse. MUCH worse.

**Comment by Saiska** [comment]
My bad. Noted.
I tried to remove the random - and i happened to see the randomness scale with the number of bot which explained in part to me why my druid was so bad at maintaining his debuff, you got me here - but despite a very clean recount where the affli warlock seems to make the perfect cycle, his dps is like a little above the tank, so yes it seems there is things that don't work for the warlock.
Incidentally, i played with the spell_data_bonus table to buff the warlock, and either i was too shy in my up factor or they don't get it, so a question is does the spell bonus factor apply like the character, or there is a trick, like the sets ?
Speaking of the sets bonus... while I'm at it... you said a while ago when i aked if they work that they work unless they are specific spell buff. Did i understand correctly, and does that means almost no set bonus work, and no relic either ? As they are all targeting specific class spells and almost never general starts boost ?

**Comment by trickerer** [comment]
Set bonuses like 'Increases <spell> damage by x / x%' do not work.
Set bonuses like 'Your <spell> critical strikes cause so and so triggered spell' generally work.

The first type of spell bonuses are handled by SpellMod system for Player. The player part is not very complicated, but the code checking different spellmods is spread everywhere, some spellmod check helper functions here and there, just a lot of work. I wanted to come up with something simpler for bots but... didn't - and bots are like this since then. Well, I think this was even before bots could benefit from combat ratings on items so spellmod system wasn't the main concern back then.
