### ISSUE TITLE
Bot leveling to 80 when dismissed

### ISSUE THREAD

**Issue by JamesHoffer** [trickerer/Trinity-Bots#118]
Just did a fresh compile today, was just testing real quick, I made a level 1 character as admin, spawned an NPC Bot (70001), asked him to join, checked out his abilities and such, when I dismissed him, he leveled to 80. Will he stay at 80 now? or will his level fix when I try hiring him again?

**Comment by trickerer** [comment]
Bot level is set to player level upon hiring (or +1...3 for some classes) so don't worry about it.
