### ISSUE TITLE
Paladin heal reset Divine Sacrifice as allowed ability

### ISSUE THREAD

**Issue by Saiska** [trickerer/Trinity-Bots#119]
A paladin heal will re-able Divine sacrifice after i disabled it. I can't pinpoint when, it's not when i change zone, or deconnect/reconnect, somewhere along the way it's the only spell of any bots which doesn't stay disable when put as non-allowed. I'll post if i succeed in finding when.

On a side note, the main problem of Divine Sacrifice is the paladin don't know how to really use it; he will die every time he uses it. Haven't played paladin heal myself so i can only suppose the divine sacrifice must only be used with another damage reduction CD, and not on his own. Just bringing a paladin heal in a encounter where the bots don't ignore the aoe ; the paladin will use divine sacrifice and will take a insane intake of damage and will die every time.
Maybe the AI should either launch another CD if possible, or not use DS at all in raid. (in groups it's ok, it doesn't take much damage in heroic) - i don't know how it is when you don't play solo, but in solo the bot are considered in the player group, so you have a big 25 player group, instead of 5 group of 5. The divine sacrifice is supposed to take the damage of the group (of 5) and not from an entire raid of 25, and so become a burden for the bot.

**Comment by trickerer** [comment]
Divine Sacrifice is supposed to get automatically interrupted; does it not? 

As for re-enabling, there is no auto re-enabling of spells IIRC. Maybe bot just uses the spell regardless of it being disabled?

https://wotlk-twinhead.twinstar.cz/?spell=64205

**Comment by Saiska** [comment]
No it does reenable it without any input on my part. it seems, i'll test that later again because i did not look right after it, but it's after a restart server. No other spells does this from what ive seen, it really look like this one cause a bug.
I didn't see the part where the effect should break, well, it doesn't. Maybe he take too much damage on one tick, dropping his life from 20%+ to 0% in one sweet oblivion. Again i think he take the damage of 24, like i said i suspect he consider every of my bot in my group, so it does not scale well with the spell. But at the time (and it was a long time ago - memory is indeed foggy) that spell wasn't coupled with something like the bubble which void all damage or something like that ?

**Comment by trickerer** [comment]
https://github.com/trickerer/TrinityCore-3.3.5-with-NPCBots/commit/0e33b8961820426d8a634504807a11e09dc8b54c

(not sure if 100% works) https://github.com/trickerer/TrinityCore-3.3.5-with-NPCBots/commit/d282d4b08c2b666abd13de2789f93961c2f3266c

**Comment by Saiska** [comment]
the first is ok !
the second seems ok, but i havent tested it on icc before the patch so maybe the raid itself is not the best way to put it to test. will confirm next time i redo a raid where i was sure the paladin would die insta.
