### ISSUE TITLE
NPCBots for TrinityCore 3.3.5

### ISSUE THREAD

**Issue by VitalyKulin** [trickerer/Trinity-Bots#12]
Привет
Собственно сразу вопрос.
У меня стоят НПЦ Боты из данной раздачи https://spp-forum.de/viewtopic.php?f=18&t=103
Я хотел бы поставить последнюю версию ботов , в которой я так понял можно  менять спек ботам, давать команды "стоять" или "идти" и тд, в более старой версии всё это не работает + может это связано что я играю на русском клиенте? в любом случае можешь пожалуйста объяснить как поставить последних ботов? я видел инструкцию эту ;
NPCBot Mod Installation
NPCBots is a TrinityCore mod (https://github.com/TrinityCore/TrinityCore/), currently only 3.3.5 branch is supported....... и тд но  местами не совсем понимаю что нужно сделать к примеру в этом пункте - (Re)run CMake and (re)build, сам английский понимаю, но тут прост не врубаюсь что именно сделать?? 
Если это возможно объяснить подробней,я был бы рад, и каковы шансы что я сам это поставлю?
ЗЫ: Связывался с создателем Single Player Project`a - David Ori, вот что он сказал -ah sorry but it's not that simple
my bots source is 2 years old and not compatible with the new npcbots patch

**Comment by trickerer** [comment]
> что нужно сделать к примеру в этом пункте - (Re)run CMake and (re)build

Это значит что после установки патча Cmake нужно прогнать ещё раз прежде чем собирать сервер. Если собираешь под виндой то Visual Studio сделает это автоматически но может затупить - придётся переоткрывать проэкт, под линуксом нужно всё делать вручную.

> Follow TrinityCore Installation Guide (https://TrinityCore.info/) to install the server first

Ссылка дана неспроста. Именно там описан базовый алгоритм установки и настройки сервера. Отличие при установке ботов лишь в том, что до Cmake нужно применить патч.

С клиентом функционал ботов вообще не связан, есть лишь некоторые ограничения, присущие кленту. От локализации это не зависит.
