### ISSUE TITLE
Bots and the ICC Buff

### ISSUE THREAD

**Issue by Saiska** [trickerer/Trinity-Bots#120]
... They don't take it. I suppose they don't take the debuff either. 

The buff is given on the event  void 
OnPlayerEnter(Player* player) 
DoCastSpellOnPlayer(player, TeamInInstance == ALLIANCE ? SPELL_STRENGHT_OF_WRYNN : SPELL_HELLSCREAMS_WARSONG);

i suppose bots aren't of the class Player and don't "enter" by the same way.
Any idea how to get around that ? is there a Player->getbots i can iterate ?

**Comment by Saiska** [comment]
tried to add at the same place the spell is cast on player:

      BotMap const* bmap;
      if (player->HaveBot())
      {
            BotMap const* bmap = player->GetBotMgr()->GetBotMap();
            bmap = player->GetBotMgr()->GetBotMap();
            for (BotMap::const_iterator ci = bmap->begin(); ci != bmap->end(); ++ci)
            {
                  if (ci->second  )
                  {
                      player->CastSpell(ci->second, TeamInInstance == ALLIANCE ? SPELL_STRENGHT_OF_WRYNN : SPELL_HELLSCREAMS_WARSONG);
                  } 
            }
      }

ci->second ->CastSpell instead of player->CastSpell crash.
But it doesn't work

**Comment by Saiska** [comment]
damn, i'm happy.
Not the best because you have to modify instance_icecrown_citadel.cpp, but this work inserted after DoCastSpellOnPlayer(player, TeamInInstance == ALLIANCE ? SPELL_STRENGHT_OF_WRYNN : SPELL_HELLSCREAMS_WARSONG);
            
            BotMap const* bmap;
            if (player->HaveBot())
            {
                BotMap const* bmap = player->GetBotMgr()->GetBotMap();
                bmap = player->GetBotMgr()->GetBotMap();
                for (BotMap::const_iterator ci = bmap->begin(); ci != bmap->end(); ++ci)
                {
                    if (ci->second   )
                    {
                        ci->second->SetMap(player->GetMap()); 
                        ci->second->CastSpell(ci->second, TeamInInstance == ALLIANCE ? SPELL_STRENGHT_OF_WRYNN : SPELL_HELLSCREAMS_WARSONG, true);
                    } 
                }
            }

and modifying
       void OnPlayerLeave(Player* player) override
      {
          DoRemoveAurasDueToSpellOnPlayer(player, TeamInInstance == ALLIANCE ? SPELL_STRENGHT_OF_WRYNN : SPELL_HELLSCREAMS_WARSONG, true, true);
      
          BotMap const* bmap;
          if (player->HaveBot())
          {
              BotMap const* bmap = player->GetBotMgr()->GetBotMap();
              bmap = player->GetBotMgr()->GetBotMap();
              for (BotMap::const_iterator ci = bmap->begin(); ci != bmap->end(); ++ci)
              {
                  if (ci->second  )
                  {
                      ci->second->RemoveAurasDueToSpell(TeamInInstance == ALLIANCE ? SPELL_STRENGHT_OF_WRYNN : SPELL_HELLSCREAMS_WARSONG); 
                  }
              }
          }
      }

**Comment by trickerer** [comment]
Unfortunatelly debuff cannot be handled it seems (players only aura)
