### ISSUE TITLE
Heal bot lollygaging

### ISSUE THREAD

**Issue by Saiska** [trickerer/Trinity-Bots#125]
Finally managing an almost P2 on LK... 
You know the fact that the heal continue to try to make the raid full life when you use dist 0 to regroup your raid ?
Well, it is usually a problem, but they somehow manage because the aoe don't kill them too fast so it wasn't a so important problem.
Now you see the transitions on LK ? where he go in the middle and make an aoe frost and you have to go to the edge on the platform to avoid the damage ?
Well, i used the dist 0 here to move the raid fast, but here the heal has no time to cast anything, it kills too fast. So no matter how i try to anticipate, every try, of 4 heal 2 will die assured because they soak in the aoe. So i cheated with a .npcb revive but well, not the most elegant way.
Is there anyway to make the heal prioritize the movement over the healing with dist 0 ?

**Comment by trickerer** [comment]
https://github.com/trickerer/Trinity-Bots/commit/e9c87e7459a43af9b209018d4ad06a8c95d7e470
