### ISSUE TITLE
Build Issues with current TrinityCore

### ISSUE THREAD

**Issue by Psilovybin** [trickerer/Trinity-Bots#126]
`[ 22%] Building CXX object src/server/game/CMakeFiles/game.dir/AI/NpcBots/bot_ai.cpp.o
In file included from /home/wow/TrinityCore/src/server/game/AI/NpcBots/bot_ai.cpp:1:
/home/wow/TrinityCore/src/server/game/AI/NpcBots/bot_ai.h:31:14: error: ‘void bot_ai::DamageTaken(Unit*, uint32&)’ marked ‘override’, but does not override
   31 |         void DamageTaken(Unit* /*attacker*/, uint32& /*damage*/) override { }
      |              ^~~~~~~~~~~
In file included from /home/wow/TrinityCore/src/server/game/AI/NpcBots/bot_ai.cpp:7:
/home/wow/TrinityCore/src/server/game/AI/NpcBots/bpet_ai.h:25:14: error: ‘void bot_pet_ai::DamageTaken(Unit*, uint32&)’ marked ‘override’, but does not override
   25 |         void DamageTaken(Unit* /*attacker*/, uint32& /*damage*/) override { }
      |              ^~~~~~~~~~~
[ 22%] Building CXX object src/server/game/CMakeFiles/game.dir/AI/NpcBots/bot_archmage_ai.cpp.o
In file included from /home/wow/TrinityCore/src/server/game/AI/NpcBots/bot_archmage_ai.cpp:1:
/home/wow/TrinityCore/src/server/game/AI/NpcBots/bot_ai.h:31:14: error: ‘void bot_ai::DamageTaken(Unit*, uint32&)’ marked ‘override’, but does not override
   31 |         void DamageTaken(Unit* /*attacker*/, uint32& /*damage*/) override { }
      |              ^~~~~~~~~~~
/home/wow/TrinityCore/src/server/game/AI/NpcBots/bot_archmage_ai.cpp:251:14: error: ‘void archmage_bot::archmage_botAI::DamageTaken(Unit*, uint32&)’ marked ‘override’, but does not override
  251 |         void DamageTaken(Unit* u, uint32& /*damage*/) override
      |              ^~~~~~~~~~~
[ 22%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Commands/cs_bf.cpp.o
make[2]: *** [src/server/game/CMakeFiles/game.dir/build.make:301: src/server/game/CMakeFiles/game.dir/AI/NpcBots/bot_archmage_ai.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 22%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Commands/cs_cast.cpp.o
make[2]: *** [src/server/game/CMakeFiles/game.dir/build.make:285: src/server/game/CMakeFiles/game.dir/AI/NpcBots/bot_ai.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1105: src/server/game/CMakeFiles/game.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 23%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Commands/cs_character.cpp.o`

added NPCBots.patch as directed and building off working source.

**Comment by Psilovybin** [comment]
I removed the overrides in all the classes with the same error and it seems to be compiling now.  It'll prolly crash the server

**Comment by trickerer** [comment]
`void DamageTaken(Unit* u, uint32& /*damage*/)` signature has changed and I forgot to update the patch. I'll do it tomorrow, thanks.

**Comment by Psilovybin** [comment]
> `void DamageTaken(Unit* u, uint32& /*damage*/)` signature has changed and I forgot to update the patch. I'll do it tomorrow, thanks.

You rock man, thank you.
