### ISSUE TITLE
Lyria (70003) potentially missing text

### ISSUE THREAD

**Issue by TQPS** [trickerer/Trinity-Bots#128]
Each time I take Lyria out, my DBErrors.log file gets a varying number of warnings:

`CreatureTextMgr: Could not find Text for Creature Lyria (Entry 70003, spawnId 213823) in 'creature_text' table. Ignoring.`

Longer dungeon runs generate more entries than shorter runs.

I have not been able to identify what action is causing these.

**Comment by trickerer** [comment]
[Known issue №3](https://github.com/trickerer/Trinity-Bots/issues/1). The message has changed over time it seems.

Bots do not say anything on their own.

**Comment by TQPS** [comment]
I'll ignore.

The strange thing is that it's ONLY Lyria. 
- A 5 man dungeon w/ Lyria - gives only Lyria warnings
- A 10 man UBRS run w/Lyria - gives only Lyria warnings
- A 5 man dungeon w/ No Lyria - no warnings at all

**Comment by trickerer** [comment]
Alright I'll check it out

**Comment by trickerer** [comment]
I tested it with Lyria in UBRS, LBRS and couple other dungeons, double-checking if proper loggers are enabled, even tried to run in Debug mode, but I got not a single such error and not a single breakpoint hit.

I'm not trying to say it never happers, but it seems to either be random, or require some special conditions, which I don't know.

Closing it for now.
