### ISSUE TITLE
Customization issue with Kerra?

### ISSUE THREAD

**Issue by TQPS** [trickerer/Trinity-Bots#129]
Recently added some Night Elves, everyone's fine except for Kerra (70038)

I thought putting a helmet on her would hide the flaw but it doesn't help.

<details>

![image](https://user-images.githubusercontent.com/66294837/130177646-f4bc7d5c-7178-4686-a761-56afd1c5679a.png)

</details>

**Comment by trickerer** [comment]
Try this SQL
```
UPDATE `creature_template_npcbot_extras` SET `race`=10 WHERE `entry`=70038;
```
and restart the server.

Don't forget to clean your client cache.

**Comment by TQPS** [comment]
That fixed it - thank you.

<details>

![image](https://user-images.githubusercontent.com/66294837/130228751-713ed480-7281-4fb7-86fb-2f562807c8ca.png)

</details>
