### ISSUE TITLE
When you the player get charmed, your bots decide to dispell your buffs and mana drain you

### ISSUE THREAD

**Issue by YunataSavior** [trickerer/Trinity-Bots#130]
I was running Slave Pens, and I got charmed. The priest bot in my group thought it was a good idea to pop all my buffs and drain my mana to zero.

That priest was mean :( and shouldn't have done that.

**Comment by trickerer** [comment]
Bots care more about party as a whole, than any of its members in particular (insert communism joke here).
Dispelling controlled friends if only so they do minimum harm, especially in raid encounters.

Maybe it should be restricted to raids and/or heroics or something

**Comment by trickerer** [comment]
Actually, priest bot doesn't have mana burn
