### ISSUE TITLE
Table 'characters.characters_npcbot' doesn't exist

### ISSUE THREAD

**Issue by croutard** [trickerer/Trinity-Bots#131]
Hi all, please forgive me as I'm very ignorant to all of this, I'm able to get a server up and running fine without bots.. However I've had a lot of trouble when trying to add npcbots and I'm getting this error. I've been trying for hours now.. please help! <3

In mysql_stmt_prepare() id: 447, sql: "UPDATE characters_npcbot SET owner = ? WHERE entry = ?"
Table 'characters.characters_npcbot' doesn't exist
In mysql_stmt_prepare() id: 448, sql: "UPDATE characters_npcbot SET owner = ? WHERE owner = ?"
Table 'characters.characters_npcbot' doesn't exist
In mysql_stmt_prepare() id: 449, sql: "UPDATE characters_npcbot SET roles = ? WHERE entry = ?"
Table 'characters.characters_npcbot' doesn't exist
In mysql_stmt_prepare() id: 451, sql: "UPDATE characters_npcbot SET equipMhEx = ?, equipOhEx = ?, equipRhEx = ?, equipHead = ?, equipShoulders = ?, equipChest = ?, equipWaist = ?, equipLegs = ?, equipFeet = ?, equipWrist = ?, equipHands = ?, equipBack = ?, equipBody = ?, equipFinger1 = ?, equipFinger2 = ?, equipTrinket1 = ?, equipTrinket2 = ?, equipNeck = ? WHERE entry = ?"
Table 'characters.characters_npcbot' doesn't exist
In mysql_stmt_prepare() id: 452, sql: "DELETE FROM characters_npcbot WHERE entry = ?"
Table 'characters.characters_npcbot' doesn't exist
In mysql_stmt_prepare() id: 453, sql: "INSERT INTO characters_npcbot (entry, roles, spec, faction) VALUES (?, ?, ?, ?)"
Table 'characters.characters_npcbot' doesn't exist
In mysql_stmt_prepare() id: 454, sql: "UPDATE characters_npcbot SET faction = ? WHERE entry = ?"
Table 'characters.characters_npcbot' doesn't exist
In mysql_stmt_prepare() id: 455, sql: "UPDATE characters_npcbot SET spec = ? WHERE entry = ?"
Table 'characters.characters_npcbot' doesn't exist
In mysql_stmt_prepare() id: 456, sql: "UPDATE characters_npcbot SET spells_disabled = ? WHERE entry = ?"
Table 'characters.characters_npcbot' doesn't exist
In mysql_stmt_prepare() id: 457, sql: "REPLACE INTO characters_npcbot_stats (entry, maxhealth, maxpower, strength, agility, stamina, intellect, spirit, armor, defense, resHoly, resFire, resNature, resFrost, resShadow, resArcane, blockPct, dodgePct, parryPct, critPct, attackPower, spellPower, spellPen, hastePct, hitBonusPct, expertise, armorPenPct) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
Table 'characters.characters_npcbot_stats' doesn't exist

TrinityCore rev. cc36c50fab98 2021-08-27 12:17:09 +0700 (npcbots_3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)
<Ctrl-C> to stop.

 ______                       __
/\__  _\       __          __/\ \__
\/_/\ \/ _ __ /\_\    ___ /\_\ \, _\  __  __
   \ \ \/\`'__\/\ \ /' _ `\/\ \ \ \/ /\ \/\ \
    \ \ \ \ \/ \ \ \/\ \/\ \ \ \ \ \_\ \ \_\ \
     \ \_\ \_\  \ \_\ \_\ \_\ \_\ \__\\/`____ \
      \/_/\/_/   \/_/\/_/\/_/\/_/\/__/ `/___/> \
                                 C O R E  /\___/
http://TrinityCore.org                    \/__/

Using configuration file C:/Build/bin/RelWithDebInfo/worldserver.conf.
Using SSL version: OpenSSL 1.1.1l  24 Aug 2021 (library: OpenSSL 1.1.1l  24 Aug 2021)
Using Boost version: 1.72.0
Updating Auth database...
>> Auth database is up-to-date! Containing 1 new and 91 archived updates.
Updating Character database...
>> Character database is up-to-date! Containing 1 new and 66 archived updates.
Updating World database...
>> World database is up-to-date! Containing 23 new and 5855 archived updates.
Could not prepare statements of the Character database, see log for details.

**Comment by trickerer** [comment]
From Installation Instructions:

> 6. Apply SQL files from /TrinityCore/sql/Bots/ to your DB (files starting with characters_ and world_ go into your characters and world DB respectively):
> ```
> 1_world_bot_appearance.sql
> 2_world_bot_extras.sql
> 3_world_bots.sql
> 4_world_generate_bot_equips.sql
> 5_world_botgiver.sql
> characters_bots.sql
> ```
> 7. Apply SQL update files from /TrinityCore/sql/Bots/updates to your DB

> `Hint: for fresh installation there are also shell scripts available for you to quickly merge all required SQL files into `ALL_chracters.sql` and `ALL_world.sql` to go to `characters` and `world` DB respectively`

Seems like you forgot to do these

**Comment by croutard** [comment]
Thank you for your prompt reply!

I did do these things from the instrutions.. the only thing I can remember not following 'exactly' was merging the worldserver.conf and worldserver.conf.dist files (because I don't know how to merge them lol) so I deleted my worldserver.conf and kept the worldserver.conf.dist but renamed it to worldserver.conf.

I may have applied the SQL update files to my characters and world DB before I put them in the main DB.. maybe that breaks everything?.. 12 hours ago I didn't even know what an SQL file was so I'm super new to all of this.

**Comment by trickerer** [comment]
Ok.

> In mysql_stmt_prepare() id: 447, sql: "UPDATE characters_npcbot SET owner = ? WHERE entry = ?"
> **Table 'characters.characters_npcbot' doesn't exist**

> In mysql_stmt_prepare() id: 457, sql: "REPLACE INTO characters_npcbot_stats (entry, maxhealth, maxpower, strength, agility, stamina, intellect, spirit, armor, defense, resHoly, resFire, resNature, resFrost, resShadow, resArcane, blockPct, dodgePct, parryPct, critPct, attackPower, spellPower, spellPen, hastePct, hitBonusPct, expertise, armorPenPct) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
> **Table 'characters.characters_npcbot_stats' doesn't exist**

These tables weren't created, which means required `characters_*` SQL files weren't executed for `characters` DB. All these files are found in `sql/Bots/` and `sql/Bots/updates/characters/`. Find them and import into `characters` DB one by one.

**Comment by croutard** [comment]
![Capture](https://user-images.githubusercontent.com/89602057/131207625-a8ffe857-4b90-4aab-9250-c8bfa94f88bb.PNG)

**Comment by croutard** [comment]
Okay, I managed to get it down to this


In mysql_stmt_prepare() id: 453, sql: "INSERT INTO characters_npcbot (entry, roles, spec, faction) VALUES (?, ?, ?, ?)"
Unknown column 'spec' in 'field list'
In mysql_stmt_prepare() id: 455, sql: "UPDATE characters_npcbot SET spec = ? WHERE entry = ?"
Unknown column 'spec' in 'field list'
In mysql_stmt_prepare() id: 456, sql: "UPDATE characters_npcbot SET spells_disabled = ? WHERE entry = ?"
Unknown column 'spells_disabled' in 'field list'


Progress!! lol

**Comment by croutard** [comment]
I'm off to bed though! Hopefully in the morning after a strong coffee I'll be able to figure out these last 3 errors with some more of your help. Much appreciated!! <3

**Comment by trickerer** [comment]
You executes sqls in wrong order (or not all of them).

Start again from `characters_bots.sql` and then all the updates from oldest to newest.

**Comment by croutard** [comment]
Do I have to undo what I've already done? Or I can just open HeidiSQL and execute all the sqls in order? I've tried doing it in order but still the same 3 errors.

**Comment by croutard** [comment]
![Capture1](https://user-images.githubusercontent.com/89602057/131223121-64714f63-bb6d-4530-9025-cc07d73f7df3.PNG)

**Comment by croutard** [comment]
I get this error the very first time I try to apply characters_bots.sql then if i run it again it doesn't give the error

**Comment by croutard** [comment]
Okay I've managed to get to this now lol..

Script 'death_knight_bot' exists in the core, but the database does not assign it to any creature.
Script 'druid_bot' exists in the core, but the database does not assign it to any creature.
Script 'hunter_bot' exists in the core, but the database does not assign it to any creature.
Script 'mage_bot' exists in the core, but the database does not assign it to any creature.
Script 'paladin_bot' exists in the core, but the database does not assign it to any creature.
Script 'priest_bot' exists in the core, but the database does not assign it to any creature.
Script 'rogue_bot' exists in the core, but the database does not assign it to any creature.
Script 'shaman_bot' exists in the core, but the database does not assign it to any creature.
Script 'warlock_bot' exists in the core, but the database does not assign it to any creature.
Script 'warrior_bot' exists in the core, but the database does not assign it to any creature.
Script 'blademaster_bot' exists in the core, but the database does not assign it to any creature.
Script 'sphynx_bot' exists in the core, but the database does not assign it to any creature.
Script 'archmage_bot' exists in the core, but the database does not assign it to any creature.
Script 'dreadlord_bot' exists in the core, but the database does not assign it to any creature.
Script 'spellbreaker_bot' exists in the core, but the database does not assign it to any creature.
Script 'dark_ranger_bot' exists in the core, but the database does not assign it to any creature.
Script 'archmage_pet_bot' exists in the core, but the database does not assign it to any creature.
Script 'dark_ranger_pet_bot' exists in the core, but the database does not assign it to any creature.
Script 'dreadlord_pet_bot' exists in the core, but the database does not assign it to any creature.
Script 'hunter_pet_bot' exists in the core, but the database does not assign it to any creature.
Script 'warlock_pet_bot' exists in the core, but the database does not assign it to any creature.
Script 'deathknight_pet_bot' exists in the core, but the database does not assign it to any creature.
Script 'priest_pet_bot' exists in the core, but the database does not assign it to any creature.
Script 'shaman_pet_bot' exists in the core, but the database does not assign it to any creature.
Script 'mage_pet_bot' exists in the core, but the database does not assign it to any creature.
Script 'druid_pet_bot' exists in the core, but the database does not assign it to any creature.
Script 'script_bot_giver' exists in the core, but the database does not assign it to any creature.
Script 'npc_injured_goblin' exists in the core, but the database does not assign it to any creature.
[1146] Table 'world.creature_template_npcbot_appearance' doesn't exist
Your database structure is not up to date. Please make sure you've executed all queries in the sql/updates folders.

**Comment by croutard** [comment]
I'm so dumb.... the whole time I've been 'loading' the sql files and not running them  -_____- got it working now thank you so much!
