### ISSUE TITLE
update maybe 

### ISSUE THREAD

**Issue by iceyman** [trickerer/Trinity-Bots#132]
looks like patching was successful tho

TrinityCore/src/server/game/AI/NpcBots/bot_ai.cpp:15873:32: error: as                                                                                                                                                             signing to 'SpellEffects' from incompatible type 'int'
    sinfo->Effects[1].Effect = 0;
                               ^
TrinityCore/src/server/game/AI/NpcBots/bot_ai.cpp:16149:32: error: as                                                                                                                                                             signing to 'SpellEffects' from incompatible type 'int'
    sinfo->Effects[1].Effect = 0;
                               ^
/TrinityCore/src/server/game/AI/NpcBots/bot_ai.cpp:16279:32: error: as                                                                                                                                                             signing to 'SpellEffects' from incompatible type 'int'
    sinfo->Effects[1].Effect = 0;
                               ^
3 errors generated.
make[2]: *** [src/server/game/CMakeFiles/game.dir/build.make:259: src/server/gam                                                                                                                                                             e/CMakeFiles/game.dir/AI/NpcBots/bot_ai.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1220: src/server/game/CMakeFiles/game.dir/all                                                                                                                                                             ] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by trickerer** [comment]
Yes, I am aware of this. If recent changes to SpellInfo are fully implemented I will update on this weekend.

**Comment by iceyman** [comment]
no worries

**Comment by iceyman** [comment]
![Screenshot_5](https://user-images.githubusercontent.com/5343324/132274184-8f35c6c9-ec91-4017-938e-66b3ed72f16e.jpg)

**Comment by trickerer** [comment]
It wasn't an update.
https://github.com/trickerer/Trinity-Bots/commit/1eb85567b06eceed22f8b7e7bcd266d94c64b090
