### ISSUE TITLE
Potentially unwanted predefined database name in pre-patched repository

### ISSUE THREAD

**Issue by Jinnaix** [trickerer/Trinity-Bots#133]
Dont think that this is intended:

```sql
DROP PROCEDURE IF EXISTS `trinity`.`sp__generate_npcbot_equips`;
```

https://github.com/trickerer/TrinityCore-3.3.5-with-NPCBots/blob/d96d4e665158dead58c0367c78c571b62742a374/sql/Bots/4_world_generate_bot_equips.sql#L159

**Comment by trickerer** [comment]
Thanks for the catch.
https://github.com/trickerer/TrinityCore-3.3.5-with-NPCBots/commit/1a1d3c25081b1c744442db747f84a5d18ab8eb4e
