### ISSUE TITLE
Suggestion for improvement NPC Vendor

### ISSUE THREAD

**Issue by Mr-Deadbeat** [trickerer/Trinity-Bots#134]
would it be possible to change the NPC Vendor to not allow players to hire bots from the opposing faction ?
makes sense sort of since Alliance / Horde dislike each other lore wise ;)

so alliance players get only Alliance bots and Horde get their respective characters

config switchable option or default either would work i guess

would also cause less confusion in pvp for those that have it on their servers

**Comment by trickerer** [comment]
Note that it only affects normal classes
