### ISSUE TITLE
Wrong character race in npcb database

### ISSUE THREAD

**Issue by Mr-Deadbeat** [trickerer/Trinity-Bots#135]
OS: Ubuntu Server 20.04.3

Commit: 594f0bd019c1ba27d86dc738f79e08336b7838f6

70158 Marion states Forsaken but the race it spawns is a Tauren

also would it be possible to recode the npc vendor so you can pick and choose directly from the lists of npc's instead of having to spawn them manually gets hella tedious after a while especially if you have players on a server and you need to spawn bots for each and everyone ;) although the more players you have on a server the less need there is for bots so in the end it evens itself out

lucky me there is only me playing on the server but those that have others friends / family playing they are in for a workflow ;)

so far i have 2 accounts on my server my alliance with 10 characters and horde with 10 so i can pick and choose what i want to play from day to day and all of them have 5 bots each you see where i'm going with this ;)

see this as a quality of life suggestion and if it's feasible to do

**Comment by trickerer** [comment]
Summonable bots were removed in 2014 and aren't coming back.

Spawning bots in packs can be done with id range via simple macro with a loop, you can even spawn all of them (be aware of known issue with bots stacking)

**Comment by trickerer** [comment]
> 70158 Marion states Forsaken but the race it spawns is a Tauren

You're missing `2020_09_25_creature_template.sql` update (or you didn't clean client's cache)

.npc info has to show displayId 1603 (forsaken)

**Comment by Mr-Deadbeat** [comment]
> > 70158 Marion states Forsaken but the race it spawns is a Tauren
> 
> You're missing `2020_09_25_creature_template.sql` update (or you didn't clean client's cache)
> 
> .npc info has to show displayId 1603 (forsaken)

yup it was missing thanks for the heads up no idea how i missed that update though usually make sure i have them all installed lol

double checked with npc info all is good now

just need to figure out a good macro for the spawning of bots the ones i have spawned in world are spread out all over the place just to make sure i don't run into the issue with the stacking problem

anywhoo my issue is solved so going to close this one down thanks again

**Comment by trickerer** [comment]
```
/run local i = 70001; while (i < 71000) do SendChatMessage(".npcb spawn "..i); i=i+1; end
```
This is for all bots.

Here are some notes:
- Every 50 entries are for a class (ex. 70051 - 70100 are paladins), but only for normal classes.
- You won't be able to spawn pets by accident.
