### ISSUE TITLE
Warlock Banishes DPS targets every battle when they can use it

### ISSUE THREAD

**Issue by Mr-Deadbeat** [trickerer/Trinity-Bots#136]
as the title says i have noticed the Warlock bot in party banishes instead of keeping to the dps rules set so once skull is dead
all the bots stand and hit the banished target might it be possible to change him a little bit so he banishes unmarked targets instead if they are in combat with the group so dps marked targets get killed fast

noticed this annoyance when i was fighting Hydromancer Thespia in Steam Vaults marked her adds for quick dps  while i was tanking the boss they got stuck pounding the banished target instead lol so got no support from the bots until i marked the boss instead

**Comment by trickerer** [comment]
Yeah, that's an oversight onmy part

**Comment by trickerer** [comment]
Please test it

**Comment by Mr-Deadbeat** [comment]
ok will do compiling as we speak

**Comment by Mr-Deadbeat** [comment]
it seems to work did a heroic run on Steam vaults and this time they took care of the adds in quick fashion and took care of the boss right after so all is good atm :)

also in the battles before i got to the first boss the warlock took care of extra adds
from the elementals although didn't mark any of them just went with the flow to see what would happen

so i think you solved it can close this issue unless you got something to add to the subject ?

**Comment by trickerer** [comment]
No, it's fine then. Thanks.
