### ISSUE TITLE
Quick question: bot weapon specializations

### ISSUE THREAD

**Issue by Vir27** [trickerer/Trinity-Bots#138]
Hello! Thank you so much for the terrific program.

Combat rogues and arms warriors can specialize swords or axes, etc. Can I look at bots' talent builds somehow?

I have not managed to find which talents are assigned by looking through the files; I did find template_npc_talent in the database but I don't know if that's for npcbots and I am still looking for what the numbers map to.

Or else could you look up for me which weapons are best to give an arms warrior and a combat rogue?

Thank you for your time.

**Comment by trickerer** [comment]
I didn't find a way to represent bot talent tree in some acceptable way. It requires an addon most likely.
Plus bots don't really have player-like talent system. The progression is relatively the same, but actual amount of talent points to spend may range for each bot/spec combination.

Arms warrior bot will automatically use proper weapon specialization for whatever weapon you give him.
Combat rogue will always pick Hack and Slash, and will always get Throwing Specialization as a bonus.

If you want to know what talent exactly are applied to bots you have to look in src/server/game/AI/NpcBots/bot_<CLASS>_ai.cpp files in `void ApplyClassPassives()` method

**Comment by Vir27** [comment]
Thank you, sir!
