### ISSUE TITLE
Worldserver crashing at "Loaded 9 databot entries"

### ISSUE THREAD

**Issue by Vir27** [trickerer/Trinity-Bots#139]
Hi, everything has been working for me on [this](https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-emulator-servers/wow-emu-general-releases/904235-trinitycore-npcbots-repack-update-25-06-2020-a-6.html) repack.

It was working last night, for instance. This morning, I booted the computer and when the worldsever loads, it gets to "Loaded 9 databot entries," hangs, and crashes.

I read through the closed issues threads. My crash is at the same place as [this](https://github.com/trickerer/Trinity-Bots/issues/101). The similar issue relates to transmog, and I have had no apparent issue with running npcbots and transmog for months of playing? I wore previously transmog'd gear yesterday, but otherwise I didn't deal with transmog at all yesterday through multiple game launches. The crash does happen at the same place, though. Unfortunately, I am not familiar with the coding or database work which the poster in that thread was able to do to resolve his issue.

Two observations which may or may not be helpful. One, when I restart the computer, the first time I try to launch WoW [edit: I mean the programs that will enable singleplayer, not the wow.exe itself] the Authserver crashes very quickly. It shows no unusual behavior after the first time. Two, in the MySQL window, I can see lines like,

2021-09-17T15:51:41.523766Z 4 [Note] Aborted connection 4 to db: 'auth' user: 'trinity' host: 'localhost' (Got an error reading communication packets)
2021-09-17T15:51:41.523815Z 5 [Note] Aborted connection 5 to db: 'auth' user: 'trinity' host: 'localhost' (Got an error reading communication packets)
2021-09-17T15:51:41.523846Z 6 [Note] Aborted connection 6 to db: 'characters' user: 'trinity' host: 'localhost' (Got an error reading communication packets)
2021-09-17T15:51:41.524094Z 7 [Note] Aborted connection 7 to db: 'characters' user: 'trinity' host: 'localhost' (Got an error reading communication packets)
2021-09-17T15:51:41.524134Z 8 [Note] Aborted connection 8 to db: 'characters' user: 'trinity' host: 'localhost' (Got an error reading communication packets)
2021-09-17T15:51:41.524179Z 9 [Note] Aborted connection 9 to db: 'world' user: 'trinity' host: 'localhost' (Got an error reading communication packets)
2021-09-17T15:51:41.524217Z 10 [Note] Aborted connection 10 to db: 'world' user: 'trinity' host: 'localhost' (Got an error reading communication packets)

Is there anything I can do? Thanks

**Comment by trickerer** [comment]
Transmog fix is summarized in https://github.com/trickerer/Trinity-Bots/issues/101#issuecomment-854003991

**Comment by Vir27** [comment]
Ok, so you do figure it's the same thing.

Where can I find
src/server/database/Database/Implementation/CharacterDatabase.cpp
?

I haven't found src in heidisql or as a folder.

**Comment by trickerer** [comment]
If your source dirs layout is different look for 'CharacterDatabase.cpp' in all sources

**Comment by Vir27** [comment]
Hi, the fellow who is maintaining my rebuild kindly helped me try this. He said the instructions in that thread are talking about a rebuild? I don't know about rebuilds or Visual Studio. He said he'd try it for me.

Just to repeat, it has been working no problem for quite some time before this morning, and I didn't do anything with transmog yesterday.

He tried it and he said this is what happened

i make the changes and add "stmt->setUInt32(++index, botitem->transmog); // this for transmog"

to

src/server/game/AI/NpcBots/botdatamgr.cpp

like it says but when I try to build I get an error in VS

Severity    Code    Description    Project    Path    File    Line    Suppression State    Tool
Error    C2039    'transmog': is not a member of 'Item'    game    F:\Trinity\TrinityCore-Single-Player\src\server\game\AI\NpcBots    F:\Trinity\TrinityCore-Single-Player\src\server\game\AI\NpcBots\botdatamgr.cpp    363        CL

**Comment by Juggalo187** [comment]
And I think the repack uses eluna transmog script not a patch. https://github.com/ElunaLuaEngine/Scripts/blob/master/Custom/Transmogrifier.lua

**Comment by Vir27** [comment]
Another update. I deleted these transmog values to try to control for whether it could be transmog? Same crash

![image](https://user-images.githubusercontent.com/17092307/133873984-c7307494-2225-48ce-acf1-14e3643abed2.png)

**Comment by trickerer** [comment]
Go to Item.cpp and try to find these rows:
```
            // @tswow-begin (Using Rochet2/Transmog)
            stmt->setUInt32(++index, transmog);
            // @tswow-end
```

Or just search `transmog`

**Comment by Juggalo187** [comment]
src\server\game\Entities\Item\Item.cpp has no Transmog, tswow or Rochet2 in it.

**Comment by trickerer** [comment]
You need to get a crash log then - you may have an entirely different problem. Build in Debug mode.

**Comment by Vir27** [comment]
By trial and error editing the spawned npcbots' entries in HeidiSQL, the extraordinarily kind Juggalo and I narrowed down the problem.

I had 4 bots out on my shaman in AQ40 last night. I hearthed out after running away from the Twin Emperors. It seems the 2 paladins did not get away. The other bots were on MapID 530, Dalaran, but they were still on MapID 531. In our repack, that is indeed AQ40. Changing those 531s to 530 let the worldserver proceed.

Thanks SO MUCH, Juggalo!!

**Comment by Juggalo187** [comment]
Yeah I think vir spawned 2 bots inside Ahn'Qiraj Temple and for some reason it was crashing worldserver. 

I always spawn all 150 bots somewhere on azeroth players shouldn't be able to reach then place hire npc in main cities.

https://www.youtube.com/watch?v=_vAnTUK924g

**Comment by Vir27** [comment]
In case anything of the sort happens to others, I'm pretty sure that how it looks like they spawned in AQ40 is itself the glitch. I have the firmest recollection of spawning those bots in Orgrimmar ages ago and running around with them since then. You can't spawn a bot that is out in the world, so I'd have had to delete them. I'd definitely remember deleting them, respawning them, and reequipping them in the middle of the raid last night.
