### ISSUE TITLE
RDF

### ISSUE THREAD

**Issue by JamesHoffer** [trickerer/Trinity-Bots#14]
I noticed when running RDF with bots, that dungeons are popping up that shouldn't, low level ones. My bots and I are 41 now, and when running RDF, I keep getting Ragefire Chasm, Dead Mines, Gnomergan etc. etc. At this level, I should only be getting the dungeons that you would see if you were to select a dungeon rather then RDF. (Razorfen to Zul'Farak) I'm not sure if somewhere this has gotten broken with the core at some point, or it's something with the bot code or not.

**Comment by trickerer** [comment]
Bot code does not affect dungeon selection. It only allows bots to be treated as players and join the LFG group.
My best guess is that this happens when you gain all the levels in one session due to a small bug in core that does not recheck your dungeon choices. So low-level dungeons are no longer in the list but they are still checked and server honestly selects one of the checked dungeons randomly.

**Comment by JamesHoffer** [comment]
> Bot code does not affect dungeon selection. It only allows bots to be treated as players and join the LFG group.
> My best guess is that this happens when you gain all the levels in one session due to a small bug in core that does not recheck your dungeon choices. So low-level dungeons are no longer in the list but they are still checked and server honestly selects one of the checked dungeons randomly.

Had a feeling it was on the core side, thanks for the input, not too big a deal, usually the satchels are duplicate so many times so using the select a dungeon feature every once in awhile isn't too bad. At least with the bots you don't get a de-buff if you leave group, re-join and reque. Thanks for the quick response. I'm guessing warmane must have fixed it, I don't play on there any more, but I have for the last year or so, and never noticed the bug with RDF, and I had all 10 toons that I strictly ran RDF to level. I'll have to see if there is a ticket at trinity, must be.
