### ISSUE TITLE
Crash on .npcbot delete

### ISSUE THREAD

**Issue by trickerer** [trickerer/Trinity-Bots#140]
Steps to reproduce:
1) .npcb spawn
2) .npcb delete

Don't know what changed that

**Comment by TQPS** [comment]
.mpcbot move also causes a crash

**Comment by Mr-Deadbeat** [comment]
could it be tied to the changes to rbac ? sitting here trying to figure out how to add those bot commands to my accounts
trough the rbac system thus far drawing a blank never fiddled with it before so stuck on how to proceed

just thought that crash might be related to those changes to account rights i'm running the latest build without issues
except for the missing bot commands i'll update if i get the commands to work

i'll do a npcb spawn and delete test at that point

**Comment by Mr-Deadbeat** [comment]
just noticed the 2 new database updates going to add them and then see what happens

**Comment by trickerer** [comment]
Alright, this is a TC issue - crash on deleting active object (tested on fel reaver)
