### ISSUE TITLE
Bot weapon chance on hit proc bug?

### ISSUE THREAD

**Issue by Miritek** [trickerer/Trinity-Bots#144]
First and foremost, thanks for your work Trickerer.

I have tested the following weapons:
1. [Rivenspike](https://wotlkdb.com/?item=13286)
2. [Bashguuder](https://wotlkdb.com/?item=13204)
3. [Annihilator](https://wotlkdb.com/?item=12798)

When using any of the above weapons with the player the chance on hit proc works correctly. When using them on a bot the chance on hit proc effect does not work.

I have tried to use them in the bots main hand, off hand, with weapon enchantments, without weapons enchantments and on different classes. The chance on hit proc effect, [Puncture Armor](https://wotlkdb.com/?spell=17315) & [Armor Shatter](https://wotlkdb.com/?spell=16928) will not activate on target mob.

Thanks in advance,
-Miritek

**Comment by trickerer** [comment]
Can't confirm.

![cap1](https://user-images.githubusercontent.com/1254989/136151982-1ca4b88b-57f9-41c2-84bf-f0b6090e506d.jpg)

What bots version?
Which mobs did you test on?
What about other items with proc effects?

**Comment by Miritek** [comment]
I am using TC 4bed5c828831. Your pre-patched repository.
I was testing on the training dummies in Stormwind.
I will check some other items and try on different mobs.
