### ISSUE TITLE
Raid test on High Warlord Naj'entus

### ISSUE THREAD

**Issue by Mr-Deadbeat** [trickerer/Trinity-Bots#148]
Commit: 4c97f6187e0ee68de1e6b9cb2d1c59b75c6c35d0

just did a test on the first raid boss with a 10 man group of level 80's solo there is an issue if the last human player dies and the boss has his shield up none of the bots ever get spined so his shield is up until he has healed enough shortly after he puts up the shield again and it will result in a wipe after a while

i think it has to do with the way the boss is scripted it checks for "player" targets only and once found spines him no players left
and you can pack it up and just give up ;) so the best solution although not sure if it's possible would be to somehow get the bots recognised as "players" this would solve similar cases with other raid bosses as well

**Comment by trickerer** [comment]
The way it works now is that bots just toss the spines to player so player can use it at the right moment. So it's not only the matter of bots not being recognized as viable targets by boss.
Well maybe bots could pick spines from inventory of dead players or something. There is a risk that bots will use up all available spines when shield is popped but that's a minor thing I guess.

**Comment by Mr-Deadbeat** [comment]
yeah that might also fix the current issue if bots pickup a spine from dead player and uses it on the shield but won't there be a issue with number of spines for example the player dies almost instantly and there is 1 spine in the players corpse
bots can pop the shield once and after that we are back to the same problem ;) not a easy fix for this problem i imagine
and pretty sure there are other bosses with similar issues / similar mechanics

btw merry christmas and a happy new year :)
been busy with other things so have not touched wow for almost a month now time to visit the world shortly though ;)

**Comment by trickerer** [comment]
> btw merry christmas and a happy new year :)

Yeah, you too.

> pretty sure there are other bosses with similar issues / similar mechanics

Well nothing similar comes to my mind, maybe in 4.x.x and above.

As for actual issue, nothing prevents bots from shoving gathered spines into dead player's pockets =). Of course IF bots are targetable by spines in the first place

**Comment by trickerer** [comment]
https://github.com/trickerer/TrinityCore-3.3.5-with-NPCBots/commit/fc1a8bd634b6755ce759149e7afc9d5dfb2a2955
