### ISSUE TITLE
Missing spell casting bar in UI

### ISSUE THREAD

**Issue by qyh214** [trickerer/Trinity-Bots#15]
for example:
bot summon mount, in ui you will see the casting bar(1.5s) ,but in latest this is missing
![20200624105955](https://user-images.githubusercontent.com/3896160/85495570-58457b00-b60d-11ea-9a35-1d1f31a4a018.jpg)

but after 1.5s bot can mount(only missing casting bar in ui)  

It's also a problem with all the spells that need time to sing

**Comment by trickerer** [comment]
This google translation is terrible.
So, after you updated to the lastest version some of your bots stopped casting spells?

Seems like I forgot to include SQL for the spec changes, and forgot to mention the inevitable problems in commit message.

**Comment by trickerer** [comment]
[c9c08a5b](https://github.com/trickerer/Trinity-Bots/commit/c9c08a5be2351bb1bf5f5b766ce9836d5d0dcb2c)

**Comment by qyh214** [comment]
fix title and describe for example:bot summon mount, in ui you will see the casting bar(1.5s) ,but in latest this is missing
![20200624105955](https://user-images.githubusercontent.com/3896160/85495570-58457b00-b60d-11ea-9a35-1d1f31a4a018.jpg)

**Comment by trickerer** [comment]
You cannot see creatures cast mount spells because of spell attribute SPELL_ATTR0_HIDE_IN_COMBAT_LOG. Test this with other creatures.
As for other spells, the problem is in your interface / addons. Try to fix it yourself. Again, test on other creatures. If problem persists, post your TC revision.

**Comment by qyh214** [comment]
not ui/addons issue. no addons and origin client.
maybe the latest tc issuse? I use TC revision is TrinityCore/TrinityCore@dc41aae0427faecef57b831f3a2ed735a9369dd7
not only cast mount spells ,but also all want to "sing" spells,.
other creatures is well.

**Comment by trickerer** [comment]
> all want to "sing" spells,.

Clarify this please.

> not only cast mount spells

Mount spells casted by others have their cast bars hidden by default.

**Comment by qyh214** [comment]
Sorry, English is not a native language, and there are some related professional terms which may be translated differently in different regions.
sing maybe is chant,channeled……
Take an example to describe this problem:
I have a mage bot(id 70332) and spec is Arcane.
use clean client and no addons.
- when I combat with enemies, When bot is casting Blizzard,in ui (Under the head or in group and under the head) you will see "Guided progress bar"(channeled bar)  until e1dc4279eb91c6afd9e734557bb323b9c9d5d82d
- you summon mount,for example horse,you get on the horse,After a short time,your bots also summon mount,summon this action is 1.5 seconds channeled,so you can see the channeled bar under bots head

but now above disappeared,you can't see "Guided progress bar"(channeled bar)  under his head in UI(But it did hurt the enemy) and if you get on the horse after a short time bot is also get on the horse.

and I try:
- right-click the bot and in menu choose manage ablitiy-cast blizzard ,you can see "Guided progress bar"(channeled bar)  under his head in UI.
So I'm not sure if I'm missing something or if there's some recent TC changes occured this issue.

**Comment by qyh214** [comment]
maybe something missing
upgrade to 2be644eb72e72b30e864c1b4c78fb0146804bb78 is well can't reproduce
and only a mistake: 
- bot_warrior_ai uin32->uint32

**Comment by trickerer** [comment]
Thanks for noticing
