### ISSUE TITLE
Improvement - Order Cast command

### ISSUE THREAD

**Issue by jasanhell1** [trickerer/Trinity-Bots#150]
Hi, Trickerer. Can you make the Order Cast command optional that we can choose by bot_name or by class. 

Example:
.npcbot order cast Dannel(bot_name) Charge mytarget, Or
.npcbot order cast Warrior(class) Charge mytarget

both way can be used.

Because we may have same class in the dungeon, we can easier to command the same class doing the same thing at the same time.

**Comment by trickerer** [comment]
Hi.

It's possible, but if you have more than 1 bot of the same class the bot selection itself has to be done at random. And, when argument check is performed, bot name has to take priority over class name I think.

**Comment by jasanhell1** [comment]
> Hi.
> 
> 
> 
> It's possible, but if you have more than 1 bot of the same class the bot selection itself has to be done at random. And, when argument check is performed, bot name has to take priority over class name I think.

True. Bot name should take priority. I think selection random is fine because we may choose different talents for the bots like one warrior is fury and one is protection. Their spells may not be the same. 

Also, we don't need to change our macro if we change NPCBot.
