### ISSUE TITLE
(Question) about patching an update

### ISSUE THREAD

**Issue by x92mko** [trickerer/Trinity-Bots#152]
Sorry this is probably a noob question:

The Trinity Server I am using is still from 27.June.21 and your NPCBots v4.10.7a.
Yes I would like to update the server but I installed additionally transmogvendor, GoMove as well as your bots, so I am getting merge conflicts and that's why I dont update. Anyway..

**To explain my problem:**
I would like to install the latest version of your bots but when I insert the new patch into my trinity folder and run gitbash I don't know what I need to write as a command in order to continue:

$ patch -p1 < NPCBots.patch
(Stripping trailing CRs from patch; use --binary to disable.)
patching file .circleci/config.yml
(Stripping trailing CRs from patch; use --binary to disable.)
patching file README.md
Hunk #1 FAILED at 1.
Hunk #2 FAILED at 19.
Hunk #3 FAILED at 36.
Hunk #4 FAILED at 73.
4 out of 4 hunks FAILED -- saving rejects to file README.md.rej
The next patch would create the file sql/Bots/1_world_bot_appearance.sql,
which already exists!  Assume -R? [n]

I am still learning. Big thanks in advance!

**Comment by trickerer** [comment]
You can't just apply a newer patch if bots are already there.

And if they're not and these errors are all you get then there should be no problem, it's just a README.

On the other hand, if you want a fresh core but preserve your current databases I would suggest you:
1) Get latest [Patched Source](https://github.com/trickerer/TrinityCore-3.3.5-with-NPCBots)
2) Apply all Trinity DB SQL updates (collecting them could be tedious)
3) Apply Bots DB SQL updates
4) Install Transmogvendor and GoMove on top of fresh source as they are much smaller patches and easier to deal with

**Comment by x92mko** [comment]
Alright. Thank you so much!

Let me please ask a last question. Do you thought about bringing random bots into the world, lets say 1000-5000 and let them just level, running around and act as "real" players?

**Comment by x92mko** [comment]
As well as let them joining/open BG's and Arena as a single player.

**Comment by trickerer** [comment]
#147
