### ISSUE TITLE
Apply patch in SQL error

### ISSUE THREAD

**Issue by veselin-ugrinov** [trickerer/Trinity-Bots#153]
Hi the patching and compilation is ok, but when i try to load the SQL's  files from updates/character folder i get error from 2020_06_21_characters_npcbot_43fceb98 that says "table characters.characters_npcbot does not exists" . 
I am getting few warnings too when i try to load some sql's from the updates folder too.
I am runing the latest TrinityCore version.

**Comment by trickerer** [comment]
You probably missed `characters_bots.sql` from `sql/Bots/` folder.

**Comment by veselin-ugrinov** [comment]
Yes, my sql client was bugged it is ok now, thank you!

p.s Those bots are amazing, keep up the good work !!!
