### ISSUE TITLE
Dungeon Finder with Bots not progressing past Role Check

### ISSUE THREAD

**Issue by TQPS** [trickerer/Trinity-Bots#154]
I think 5e2b2fd3f8bd8e1c1d3b4f3b833b9af6890d55dc in TC might have hindered queuing with Bots.

Queuing for a Dungeon now says "Waiting for all players to confirm their roles ..."

The following now displays in chat:

<details>

![image](https://user-images.githubusercontent.com/66294837/147420888-484ac1fa-b357-4f7d-a207-ad858417c482.png)

</details>

**Comment by Parkan1986** [comment]
Потверждаю эот баг.После обновления с ботами стало невозможно зайти в подземелье через поиск.Помогает только мод LFG solo.

**Comment by trickerer** [comment]
https://github.com/trickerer/TrinityCore-3.3.5-with-NPCBots/commit/b604331960a36cdfab14d5eb5000c4d43ce86d62
If everything is fine will push tomorrow

**Comment by TQPS** [comment]
Just built and works perfectly.

<details>

![image](https://user-images.githubusercontent.com/66294837/147709178-c7293da7-2203-45c8-969c-f5daea2cee16.png)

</details>

Great job as always!

Thanks for the awesome continued support you give this project!!
