### ISSUE TITLE
Bots online list 

### ISSUE THREAD

**Issue by veselin-ugrinov** [trickerer/Trinity-Bots#155]
Can bots be enabled so they can be seen in /who list ?

**Comment by trickerer** [comment]
Maybe. But it's not a good idea to mix players in NPCs like that.
Probably an extra .npcbot command is more suitable.

**Comment by trickerer** [comment]
https://github.com/trickerer/TrinityCore-3.3.5-with-NPCBots/commit/1b27fd4ce6e762d273c797c557d4186541421172
If everything is fine will push tomorrow

**Comment by veselin-ugrinov** [comment]
What is the expected end result here ?

**Comment by trickerer** [comment]
Just been waiting for CI to work out correctly
