### ISSUE TITLE
Bot Prizes

### ISSUE THREAD

**Issue by veselin-ugrinov** [trickerer/Trinity-Bots#157]
Hello,
Is it possible the price of hiring a bot to scale depending on the level ?
For example, at level 1-40 bots are free, then from 40-60 - XX gold, 60-80 even more...

**Comment by trickerer** [comment]
Th Readme mentions this briefly. The price IS scaled each 10 levels. Here is the formula:
Say bot base cost is 1000000 (100 gold)
Level 1-9:   base / 5000 (2 silver)
Level 10-19: base / 100 (1 gold)
Level 20-29: base / 20 (5 gold)
Level 30-39: base / 5 (20 gold)
Level 40-80: base * level / 80 (linear, 100 gold at 80)

So - no, not exactly what you want but scaling is there already

**Comment by trickerer** [comment]
Closed as answered
