### ISSUE TITLE
sql update failed

### ISSUE THREAD

**Issue by deadadm1n** [trickerer/Trinity-Bots#159]
im using this as my base: https://github.com/ElunaLuaEngine/ElunaTrinityWotlk

trying to add your patch with clean files and get this error.

https://pastebin.com/baUv9BU2

**Comment by trickerer** [comment]
You are not supposed to apply Bots sqls via automatic updater.
You have to import them manually, base first, then the updates. Check the README:
https://github.com/trickerer/Trinity-Bots#npcbot-mod-installation

**Comment by trickerer** [comment]
Closed due to inactivity
