### ISSUE TITLE
[Feature Request] Option to not return gear when dismissed

### ISSUE THREAD

**Issue by Corgicorgicorgi** [trickerer/Trinity-Bots#164]
Hi again,

Is it going to be difficult to implement the option to not return the gear when the bot is dismissed? Sometimes I'd like to just switch between characters and reuse the same bots.

Tried using the `.npcbot set owner` command on a different character but it says I can't until the bot is dismissed by the current owner, which is kind of expected. So right now my workaround is to update the `owner` column in the `characters_npcbot` table. It works but it's not the prettiest solution. Hoping there would be some native support in the bot menu.

Thank you!

**Comment by trickerer** [comment]
What you want is `.npcbot remove` command. It was already discussed before.
#55

**Comment by Corgicorgicorgi** [comment]
Ah, thank you for that! I should have done a better job at searching previous tickets 😬.
