### ISSUE TITLE
Update README.md to refer to correct TrinityCore commit version

### ISSUE THREAD

**Issue by YunataSavior** [trickerer/Trinity-Bots#17]
Hello,

Pulling the latest from this repo and applying the .patch file to the specified commit ID (dated June 25, 2020), I get a compile error stating that I'm missing "DBStore2.h". This file wasn't added til a few days back, which coincides with a recent publish to the Trinity-Bots repo.

I'm guessing you pulled the latest from TrinityCore and patched NPCBots.patch to that version, but didn't update README.md. Could you please update the README?

**Comment by YunataSavior** [comment]
EDIT: I pulled this commit, and it works!

https://github.com/TrinityCore/TrinityCore/commit/4a4aac61d59c8202166c7bb7065385acc4a11ea7

BTW, thank you so much for developing this; I was looking for something like this for years!!!

**Comment by trickerer** [comment]
There is no "DBStore2.h" file in TrinityCore. There is "DB2Store.h" file but only on master branch.

**Comment by YunataSavior** [comment]
My mistake, I typed the header file name wrong.
