### ISSUE TITLE
Fury warrior weapon display issue

### ISSUE THREAD

**Issue by njikmf** [trickerer/Trinity-Bots#170]
Fury talent can  dual wield two-hand weapon and it displays ok after equipping.

![Capture](https://user-images.githubusercontent.com/96371060/160774668-3abce4f8-1fc6-4c07-ab7c-ce2846a60a4a.PNG)

 but only display one weapon(main hand) if re-loggin or click "update visual".. 
Anyway to fix that?
![2](https://user-images.githubusercontent.com/96371060/160774680-ad64ecbd-4abe-4087-83d9-b5fa9922cb1a.PNG)

**Comment by Mr-Deadbeat** [comment]
i think this is a server core issue seen it happen on a plain server without bots as well
although correct me if i'm wrong :)

and trinitycore has a lot of issues unresolved for decades

**Comment by trickerer** [comment]
I tested it and it doesn't seem to be happening with players. Still, I have to assume this is client issue since I see no problems at all serverside.
A tempfix will make bots update their off-hand when player uses `Manage Equipment` -> `Update Visuals`

**Comment by Parkan1986** [comment]
Я хочу добавить вот кое-что еще.Паладины боты в стандартном снаряжении имеют одноручное оружие и щит.Если паладина экипировать двуручным оружием и затем перзапустить сервер,или перелогиниться дабы бот вернулся на стандартную позицию и потом обратно к игроку,то паладин будет махать двуручным оружием как одноручным.
Если в ДБ в Creature_equip_template убрать у паладинов одноручное оружие и щит и поставить двуручное оружие то баг пропадает.

**Comment by trickerer** [comment]
https://github.com/trickerer/TrinityCore-3.3.5-with-NPCBots/commit/3a800e090e892c26abda53337de309ed8dab76fc
