### ISSUE TITLE
Get 25 errors with VS 2019 please update again

### ISSUE THREAD

**Issue by McCrowley** [trickerer/Trinity-Bots#171]
Hello trickerer, can you update the NpcBots for TrinityCore I get 25 errors with VS 2019

Example:

Error C2039 'GetInterruptMask' is not a member of 'creature'.
"class "Creature"" has no member ""HasReactive"".

Can you please update that? Thank you

always good work thank you

**Comment by McCrowley** [comment]
thank you very much I'm always happy that someone always updates the NpcBots I'm always grateful for the work Thank you

**Comment by trickerer** [comment]
I am aware of recent changes. I looked through the diff briefly but can't see the changes related to Reactives. Whatever. CI is set to sync on Saturdays but I'll see if I can update sooner.
Keep in mind that more changes may follow still.

**Comment by Mr-Deadbeat** [comment]
it fails to patch on ubuntu 20.04 as well so it has something to do with the latest two changes they made to the core
e334fdf3ade7c3df8df9e5730434b67fe1ed019a
and
d611925dc7ab2b3f19c5ee9e0f75b8dfb6de1291

no issues building prior to those 2

**Comment by HolmesLiu** [comment]
TrinityCore/src/server/game/AI/NpcBots/bot_GridNotifiers.h:1082:18: fatal error: too many arguments to function call, expected 1, have 2; did you mean 'Object::HasFlag'?
            !go->HasFlag(GAMEOBJECT_FLAGS, GO_FLAG_IN_USE) &&
                 ^~~~~~~
                 Object::HasFlag
/mnt/e/game/server/TrinityCore/src/server/game/Entities/Object/Object.h:134:14: note: 'Object::HasFlag' declared here
        bool HasFlag(uint16 index, uint32 flag) const;
             ^
[ 21%] Building CXX object src/server/game/CMakeFiles/game.dir/AI/NpcBots/bot_dark_ranger_ai.cpp.o
[ 21%] Building CXX object src/server/game/CMakeFiles/game.dir/AI/NpcBots/bot_death_knight_ai.cpp.o
[ 21%] Building CXX object src/server/game/CMakeFiles/game.dir/AI/NpcBots/bot_dreadlord_ai.cpp.o
In file included from /mnt/e/game/server/TrinityCore/src/server/game/AI/NpcBots/bot_dark_ranger_ai.cpp:2:
/mnt/e/game/server/TrinityCore/src/server/game/AI/NpcBots/bot_GridNotifiers.h:1082:18: fatal error: too many arguments to function call, expected 1, have 2; did you mean 'Object::HasFlag'?
            !go->HasFlag(GAMEOBJECT_FLAGS, GO_FLAG_IN_USE) &&
                 ^~~~~~~
                 Object::HasFlag
/mnt/e/game/server/TrinityCore/src/server/game/Entities/Object/Object.h:134:14: note: 'Object::HasFlag' declared here
        bool HasFlag(uint16 index, uint32 flag) const;
             ^
1 error generated.
make[2]: *** [src/server/game/CMakeFiles/game.dir/build.make:319: src/server/game/CMakeFiles/game.dir/AI/NpcBots/bot_dark_ranger_ai.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
1 error generated.
make[2]: *** [src/server/game/CMakeFiles/game.dir/build.make:274: src/server/game/CMakeFiles/game.dir/AI/NpcBots/bot_ai.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1220: src/server/game/CMakeFiles/game.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
^Cmake[2]: *** [src/server/scripts/CMakeFiles/scripts.dir/build.make:10671: src/server/scripts/CMakeFiles/scripts.dir/depend] Interrupt
make[1]: *** [CMakeFiles/Makefile2:1289: src/server/scripts/CMakeFiles/scripts.dir/all] Interrupt
make: *** [Makefile:130: all] Interrupt

**Comment by trickerer** [comment]
https://github.com/trickerer/Trinity-Bots/commit/a4f70ea23c9a6fd023de4a731e4dc35674d9df34
