### ISSUE TITLE
Database errors when applying SQL files

### ISSUE THREAD

**Issue by PsychoEliteNZ** [trickerer/Trinity-Bots#173]
Hi, Ive been using the pre-patched repository and I managed to get up to the point in which I have to apply the SQL files to my database, and somehow even with a few errors I had managed to get the [_creature_template_npcbot_appearance_](https://i.imgur.com/mldAEC5.png) and [_creature_template_npcbot_extras_](https://i.imgur.com/COnWNpi.png) added.

With _3_world_bots.sql_ file I get the error
![image](https://user-images.githubusercontent.com/5151760/162888407-0439605a-22d0-4a17-9efb-d92829346272.png)

With _4_world_generate_bot_equips.sql_ giving this error
![image](https://user-images.githubusercontent.com/5151760/162888008-df8987d5-07b5-4941-a98b-bd63767a9609.png)

And with _5_world_botgiver.sql_ I get this error
![image](https://user-images.githubusercontent.com/5151760/162887930-1a4801ad-6047-4deb-9b2f-fe6cc1e07184.png)

_characters_bots.sql_ never gave me an error and was successfully added

**Comment by trickerer** [comment]
https://github.com/trickerer/TrinityCore-3.3.5-with-NPCBots/blob/npcbots_3.3.5/sql/Bots/3_world_bots.sql#L413
Clearly `3_world_bots.sql` has table creation query in it.
Warning is fine.
For `spell_school_immune_mask` check your `creature_template` table. You can also check `ObjectMgr.cpp` at `ObjectMgr::LoadCreatureTemplates()` for table columns it reads.
