### ISSUE TITLE
Multiple problems please update again

### ISSUE THREAD

**Issue by McCrowley** [trickerer/Trinity-Bots#174]
Hi can you please update the patch there are many gossip bugs in VS2019 at the moment

here the error

AddGossipItemFor(player, icon, LocalizedNpcText(player, TextForSpec(i)), GOSSIP_SENDER_SPEC_SET, GOSSIP_ACTION_INFO_DEF + i);

Thanks in advance always good work

sorry am not that good for writing a text

**Comment by trickerer** [comment]
https://github.com/trickerer/Trinity-Bots/commit/36f256fd9db9bc83aae12c3bb1220644dc8ca4f3
