### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by McCrowley** [trickerer/Trinity-Bots#175]
Hi,
Question would it be possible to insert the npcbots into Eluna Lua Engine or is that not possible would it be possible to use the patch with Eluna Lua Engine.

https://github.com/ElunaLuaEngine/Eluna

**Comment by trickerer** [comment]
1) No. At least I'm not going to do that
2) I didn't but you can try to patch official TrinityCore+Eluna repository https://github.com/ElunaLuaEngine/ElunaTrinityWotlk
