### ISSUE TITLE
Npc Bot Limit 

### ISSUE THREAD

**Issue by yamouri** [trickerer/Trinity-Bots#176]
Hello,

I'm using your solution in the docker TrinityCore https://github.com/fred-drake/TrinityCoreDocker/tree/3.3.5 
It work well, but it look like a player can have only 1 npc owned by him.

How can I change this player limit ? Is it possible via the gm command line?

Thank you

**Comment by infidelus** [comment]
You need to edit worldserver.conf.  The setting is there:

NpcBot.MaxBots = 0 - 39

**Comment by yamouri** [comment]
Thank you so much for your help
