### ISSUE TITLE
rbac permissions

### ISSUE THREAD

**Issue by Slipy007** [trickerer/Trinity-Bots#179]
Hi,

Am I able to create rbac premissions only for players so they don't have any GM commands to spawn bots etc.? If so how do I go about that? Everything works on the server but only if your a GM.

Thank you,
Slipy007

**Comment by trickerer** [comment]
Here are the default permissions. Adjust them as you wish.
> 196 - admin
> 197 - gm
> 199 - player

![permissions](https://user-images.githubusercontent.com/1254989/171820005-0ea76737-394d-489b-bddb-df4c9d6f0d37.JPG)

**Comment by Slipy007** [comment]
Hi,

Thank you for your help. I really like this idea for TrinityCore 3.3.5a Thank you for creating it.

Slipy007
