### ISSUE TITLE
Shamans don't have "off-hand" equipment option

### ISSUE THREAD

**Issue by NikoSSR** [trickerer/Trinity-Bots#18]
Thank you for your excellent work. 

I'm here to report a minor issue. 

Shamans are able to equip shields and other off-hand items. Currently, Shamans don't have options to equip any off-hand items under talent 1(Elemental ) and talent 3(Restoration), which is considered a bug.

It's really appreciate to fix this issue at any moment. Your Bots are my favorite for wow 3.3.5. Thank u again.

**Comment by trickerer** [comment]
Shaman bots can equip off-hand items but only if their equipped weapon is not a two-hander. This applies to all bots.
There is actually a bug that makes Shaman bots being able to equip off-hand weapons in any spec. This should be fixed.
![shaman_offhand](https://user-images.githubusercontent.com/1254989/86931911-e1f35d80-c162-11ea-91b2-66786ec25b5e.JPG)
