### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by Slipy007** [trickerer/Trinity-Bots#180]
I just wanted the trinitybots owner of this script to know that I love it. I'm very suprised on how much work you put into this. Scaling bots, etc. Thank you for the share. And no bugs or errors on compile or executing .sqls @[trickerer](https://github.com/trickerer)

`Slipy

**Comment by trickerer** [comment]
I started 11 years ago, man. That's one way to learn C++, huh? SQL also.
I'm glad people are enjoying playing with NPCBots, but some work on them is still pending.

All this started with me returning to WoW after some time trying to set up my own private server with bots I once enjoyed, only to find out that bots patch does not apply and even after I'd fix that they won't compile anyway.
Making those bots working again was just a dream back then, but in the end all this hard work yielded me a software engineer position in a big company, so I'd say my time wasn't wasted at all.

**Comment by Slipy007** [comment]
Yea I had no idea how to manage a server 14 years ago. I've learn a lot. I'm now using linux instead of windows desktop. So I know what you mean.

**Comment by Slipy007** [comment]
Closing
