### ISSUE TITLE
Server starting

### ISSUE THREAD

**Issue by Slipy007** [trickerer/Trinity-Bots#181]
Hi,

Do you know why this happens sometimes when trying to start the world? 
I fix it by adding to the database.

https://imgur.com/zlXeAnv

Also when I do 5 man dungeons I crash the server, and only me. Not sure why. I think it's a npcbot spell or something. But I'm sure the spells are wrath spells in database. So I'm not sure. No custom gear or spells on me or npcbots. Doubt it matters but I was doing Ramparts 5 man.

I forget who is who below but pally is tank, protection spec, priest is heal, holy spec, rogue is combat spec, druid is dps spec feral.

I'm using npcbots:

70066

70413

70234

70174

Thank you

**Comment by trickerer** [comment]
Well, as you can see data is loaded. Maybe this is a problem with assertion expression itself. Try using assert with message
> ~~ASSERT(<statement> && <text>);~~
> ASSERT(<statement>, <text>);

**Comment by trickerer** [comment]
I couldn't reproduce either of those crashes, to look into it I need a Debug crash log.

**Comment by Slipy007** [comment]
> I couldn't reproduce either of those crashes, to look into it I need a Debug crash log.

I'll test more. Just weird it only happens in dungeons. But maybe it was my pc. Since everyone else are not having any issues on the server. I have no clue. I just reinstalled windows and I'll test it out and get back to you. Thank you for helping.

**Comment by trickerer** [comment]
Yes you can pull last version of patched repo, or use last version of the patch https://github.com/trickerer/Trinity-Bots/commit/faf36803e13e8c298b7ab92ad15cb8b7e0ea792b

**Comment by trickerer** [comment]
> This was just an update to NPCBots.patch only. Not sql's right? This is what I'm understanding.

That's right

**Comment by Slipy007** [comment]
New NPCBOTS patch works good now. But should I be concerned that it now says upon world start:

so and so wasn't added consider adding it.

I started the world in screen so I only saw it once and couldn't go back. But the world started anyway instead of stopping like before. Nice fix, thank you.

**Comment by trickerer** [comment]
This error means that npcbot entry exists in `characters_npcbot` table but not in `creature` table, meaning that bot will not be spawned.
The only way that I see for this to happen is if npcbot spawn gets erased directly from `creature` table.

To spawn it back you'll have to use `.npc add` command, not `.npcbot spawn`

**Comment by Slipy007** [comment]
> This error means that npcbot entry exists in `characters_npcbot` table but not in `creature` table, meaning that bot will not be spawned. The only way that I see for this to happen is if npcbot spawn gets erased directly from `creature` table.
> 
> To spawn it back you'll have to use `.npc add` command, not `.npcbot spawn`

Ok so if I don't `.npc add` no one can use that bot?

**Comment by trickerer** [comment]
> Ok so if I don't .npc add no one can use that bot?

Of course, it will never be spawned so nobody will see it.
Also, removing that entry from `characters_npcbot` will prevent you from retrieving bot's gear.

**Comment by Slipy007** [comment]
No crashes from me so far. Wonder if it was an addon? Because I did disabled some like xperl. Who knows. oh well.

**Comment by Slipy007** [comment]
Would you have any idea why all of a sudden when the world starts and get's to:

Loading 146 npcbots...

Than I get:
Segmentation fault (core dumped)

I thought I'd ask you first since the world crashes at this point before figuring it out or reinstalling sql backups.

**Comment by trickerer** [comment]
No idea. During worldserver start there is no such output `Loading X npcbots...` and I didn't get any crashes recently despite the fact that I currently working on bot features.
Build in Debug mode and get a crash log.

**Comment by Slipy007** [comment]
> No idea. During worldserver start there is no such output `Loading X npcbots...` and I didn't get any crashes recently despite the fact that I currently working on bot features. Build in Debug mode and get a crash log.

I know it's not your script and it does say loading so and so bots while starting. I've not done anything different lately. How would I get a crashlog?

**Comment by trickerer** [comment]
When core built in Debug mode crashes a verbose log will be placed into `Crashes/` folder
