### ISSUE TITLE
求助：不能运行了

### ISSUE THREAD

**Issue by llucky2022** [trickerer/Trinity-Bots#182]
这次更新后，编译没问题，但是运行wordserver出现：
/home/wow/TrinityCore-3.3.5-with-NPCBots/src/server/database/Database/DatabaseWorkerPool.cpp:73 in DatabaseWorkerPool FATAL ERROR:
Used MariaDB library version (10.3.34 id 100334) does not match the version id used to compile TrinityCore (id 30116). Search on forum for TCE00011.
Segmentation fault (core dumped) 
下面是编译到最后的显示
[ 99%] Building CXX object src/server/worldserver/CMakeFiles/worldserver.dir/TCSoap/TCSoap.cpp.o
[100%] Linking CXX executable worldserver
/usr/bin/ld: ../../../dep/lualib/liblualib.a(loslib.c.o): in function `os_tmpname':
/home/wow/TrinityCore-3.3.5-with-NPCBots/dep/lualib/loslib.c:108: warning: the use of `tmpnam' is dangerous, better use `mkstemp'
[100%] Built target worldserver
Install the project...
-- Install configuration: "RelWithDebInfo"
-- Up-to-date: /home/wow/server/bin/lua_scripts//extensions
-- Up-to-date: /home/wow/server/bin/lua_scripts//extensions/StackTracePlus
-- Installing: /home/wow/server/bin/lua_scripts//extensions/StackTracePlus/LICENSE
-- Installing: /home/wow/server/bin/lua_scripts//extensions/StackTracePlus/StackTracePlus.ext
-- Installing: /home/wow/server/bin/lua_scripts//extensions/StackTracePlus/README.md
-- Installing: /home/wow/server/bin/lua_scripts//extensions/ObjectVariables.ext
-- Installing: /home/wow/server/bin/lua_scripts//extensions/_Misc.ext
-- Installing: /home/wow/server/bin/authserver
-- Set runtime path of "/home/wow/server/bin/authserver" to "/home/wow/server/lib"
-- Installing: /home/wow/server/etc/authserver.conf.dist
-- Installing: /home/wow/server/bin/worldserver
-- Set runtime path of "/home/wow/server/bin/worldserver" to "/home/wow/server/lib"
-- Installing: /home/wow/server/etc/worldserver.conf.dist

**Comment by qyh214** [comment]
If you submit questions on GitHub and the author is not from your native country, you should use English, or one line of your native language and one line of translated English text.

在github上提交问题，且作者并非来自你母语所在国家的，应当使用英语，或者一行你的母语，一行翻译的英语文本

------
你这个错误不属于bot的问题，tc核心对mysql版本的抓取和支持问题，建议在tc里面搜索相关问题，或者提交问题，应该是数据库的版本不符合要求，看下tc的wiki，我这边暂时没时间测试

**Comment by trickerer** [comment]
> Used MariaDB library version (10.3.34 id 100334) does not match the version id used to compile TrinityCore (id 30116). **Search on forum for TCE00011**.

https://community.trinitycore.org/topic/13962-trouble-with-your-trinity-install-starting-login-readme-1st-faqs/?do=findComment&comment=47668

**Comment by llucky2022** [comment]
> If you submit questions on GitHub and the author is not from your native country, you should use English, or one line of your native language and one line of translated English text.
> 
> 在github上提交问题，且作者并非来自你母语所在国家的，应当使用英语，或者一行你的母语，一行翻译的英语文本
> 
> 你这个错误不属于bot的问题，tc核心对mysql版本的抓取和支持问题，建议在tc里面搜索相关问题，或者提交问题，应该是数据库的版本不符合要求，看下tc的wiki，我这边暂时没时间测试

谢谢你的回复，使用git的时间不长，不太知道一些常识。这次应该不是bot的问题，我从tc官网重新clone并编译，也出现这个问题，我的库是mysql5.7，之前的编译环境都没改变，可能是tc更新的原因，对你和作者做出的工作非常感谢。
