### ISSUE TITLE
Bot Tank swimming in air after first walking down into Lava in shadowmoon valley

### ISSUE THREAD

**Issue by Mr-Deadbeat** [trickerer/Trinity-Bots#187]
TCore: b9450bcdd0924ca69b5b2cc675f5c2b558ff9b47
Bots: 4dfa31b8abbf9f6b1cd3ab9800f206876668d6df
OS: Ubuntu 20.04.4

was doing quest Everburning ash with my mage and had my bots out
during one of the fights tank bot "Thran" ran into the lava and he seemed to get stuck there so i used recall
he showed up but after that he has been swimming in air the whole time logged out completely from the game did nothing he is still doing it after i logged back in no idea what might cause this thought i should let you know
if you could figure this one out

got it to stop doing it i think i figured it out if the bots have been using their flying mounts prior and get stuck somewhere and doing recall glitches them out somehow i have noticed they are floating in the air after getting of their flying mounts so something glitchy between transition between flight / ground mode

**Comment by trickerer** [comment]
https://github.com/trickerer/TrinityCore-3.3.5-with-NPCBots/commit/29e063368455407064aa15b3b04cf7f7f93fef15
