### ISSUE TITLE
Bot expiring

### ISSUE THREAD

**Issue by Slipy007** [trickerer/Trinity-Bots#188]
Hi,

I set:

 NpcBot.OwnershipExpireTime
        Description: Maxmum time since last account login (in seconds) before bot ownership
                     is automatically cancelled (at server loading).
       Note:        All items will be refund and mailed back to player.
       Default:     0 - (Disabled)
                    604800 - (7 Days) 86400 - (1 Day) 302400 - (3.5 days)   172800 - (2 days)

NpcBot.OwnershipExpireTime = 172800

The hastags are there, github makes it caps. Sorry but it wouldn't let me make a code box. Are they suppose to still be in characters_npcbot table after that time? I still have over 138 owned npcbots after that time and there's not that many players to own that many. Or do they not expire?

**Comment by trickerer** [comment]
Expiration time is compared against the amount of time passed since owner's last login, not since when bot was hired.
If bots ownership still does not expire that is probably due to bot being owned by a deleted character since that wasn't tested.

**Comment by Slipy007** [comment]
> Expiration time is compared against the amount of time passed since owner's last login, not since when bot was hired. ~If bots ownership still does not expire that is probably due to bot being owned by a deleted character since that wasn't tested.~ Actually when player is deleted all bots are removed from them.

Oh I was hoping it was global expire not time played. Thank you.

**Comment by trickerer** [comment]
The bots' ownership expiration was suggested as a solution to bots staying unhireable forever because they're owned by someowne who doesn't play anymore and things like that.
> What if player doesn't come back to play?

If player does not login in 2 days (in your case) then bots will become free again.

You can free bots manually of course. Here is the query to see bot owner account's last activity if you want to
> SELECT \`last_login\` FROM \`auth.account\` WHERE \`id\` = (SELECT \`account\` FROM \`characters\`.\`characters\` WHERE \`guid\` = (SELECT \`owner\` FROM \`characters\`.\`characters_npcbot\` WHERE \`entry\` = '**\<BOT_ENTRY>**'));

**Comment by Slipy007** [comment]
> The bots' ownership expiration was suggested as a solution to bots staying unhireable forever because they're owned by someowne who doesn't play anymore and things like that.
> 
> > What if player doesn't come back to play?
> 
> If player does not login in 2 days (in your case) then bots will become free again.
> 
> You can free bots manually of course. Here is the query to see bot owner account's last activity if you want to
> 
> > SELECT `last_login` FROM `auth.account` WHERE `id` = (SELECT `account` FROM `characters`.`characters` WHERE `guid` = (SELECT `owner` FROM `characters`.`characters_npcbot` WHERE `entry` = '**<BOT_ENTRY>**'));

Is this suppose to be qued into characters database? Some of the tables don't match with the above code.

**Comment by trickerer** [comment]
That query uses both `auth` and `characters` DBs, assuming that's what they are called on your end. These are the default TDB names.
Well, actually I made a mistake manually escaping the table names.

> SELECT \`last_login\` FROM \`auth\`.\`account\` WHERE \`id\` = (SELECT \`account\` FROM \`characters\`.\`characters\` WHERE \`guid\` = (SELECT \`owner\` FROM \`characters\`.\`characters_npcbot\` WHERE \`entry\` = '<BOT_ENTRY>'));

**Comment by Slipy007** [comment]
Why are there a lot of owners as 0 in characters_npcbot. They dismissed them? Do I have to delete them manually?

**Comment by trickerer** [comment]
Bots being permanent spawns is one key feature of version 4.

You can safely delete free bots if they don't have any gear, otherwise you partially corrupt your `item_instance` table since items bots had will be inaccessible

>DELETE FROM \`world\`.\`creature\` WHERE \`id\` IN (SELECT \`entry\` FROM \`characters\`.\`characters_npcbot\` WHERE \`owner\` = '0' AND \`equipMhEx\` = '0' AND \`equipOhEx\` = '0' AND \`equipRhEx\` = '0' AND \`equipHead\` = '0' AND \`equipShoulders\` = '0' AND \`equipChest\` = '0' AND \`equipWaist\` = '0' AND \`equipLegs\` = '0' AND \`equipFeet\` = '0' AND \`equipWrist\` = '0' AND \`equipHands\` = '0' AND \`equipBack\` = '0' AND \`equipBody\` = '0' AND \`equipFinger1\` = '0' AND \`equipFinger2\` = '0' AND \`equipTrinket1\` = '0' AND \`equipTrinket2\` = '0' AND \`equipNeck\` = '0');

>DELETE FROM \`characters\`.\`characters_npcbot\` WHERE \`owner\` = '0' AND \`equipMhEx\` = '0' AND \`equipOhEx\` = '0' AND \`equipRhEx\` = '0' AND \`equipHead\` = '0' AND \`equipShoulders\` = '0' AND \`equipChest\` = '0' AND \`equipWaist\` = '0' AND \`equipLegs\` = '0' AND \`equipFeet\` = '0' AND \`equipWrist\` = '0' AND \`equipHands\` = '0' AND \`equipBack\` = '0' AND \`equipBody\` = '0' AND \`equipFinger1\` = '0' AND \`equipFinger2\` = '0' AND \`equipTrinket1\` = '0' AND \`equipTrinket2\` = '0' AND \`equipNeck\` = '0';

>SELECT \`entry\` FROM \`characters\`.\`characters_npcbot\` WHERE \`owner\` = '0';

The last query will list remaining free bots which **do** have gear on for some reason. You'll have to delete those ingame with `.npcbot delete`

You can of course delete free bots regardless of their gear status if you really want to, deleting items from `item_instance` in the process, but I'll leave forming such a query to you

**Comment by Slipy007** [comment]
One more question. Once they are hirable again and are sitting in the world can someone else where in the world spawn that npcbot? Or is it not free to spawn because it has no owner but is sitting in the world?

**Comment by trickerer** [comment]
>Once they are hirable again and are sitting in the world can someone else where in the world spawn that npcbot?

You cannot spawn any bot more than once. You can move them with '.npcbot move **\<ENTRY>**', but you use can just use botgiver instead.
I hope you aren't mixing 'spawn' and 'hire' here.

When bot ownership expires, all gear is mailed back to owner. On the other hand, if player is deleted npcbots are freed but all gear stays on them. This is probably not right but that's how it works right now.

**Comment by Slipy007** [comment]
> > Once they are hirable again and are sitting in the world can someone else where in the world spawn that npcbot?
> 
> You cannot spawn any bot more than once. You can move them with '.npcbot move **<ENTRY>**', but you use can just use botgiver instead. I hope you aren't mixing 'spawn' and 'hire' here.
> 
> When bot ownership expires, all gear is mailed back to owner. On the other hand, if player is deleted npcbots are freed but all gear stays on them. This is probably not right but that's how it works right now.

I haven't really messed with them. I'm just trying to learn about them and how certain things work. So if players have questions plus I want to know myself. Mixing spawn with hire?

**Comment by trickerer** [comment]
>Mixing spawn with hire?

>Or is it not free to spawn because it has no owner but is sitting in the world?

Spawning is always free, hiring is never (unless you set hire cost in config to 0)

**Comment by Slipy007** [comment]
> > Mixing spawn with hire?
> 
> > Or is it not free to spawn because it has no owner but is sitting in the world?
> 
> Spawning is always free, hiring is never (unless you set hire cost in config to 0)

Oh no, I make them pay to hire. Just changed prices a bit.

**Comment by Slipy007** [comment]
How does the npcbot vendor work? I spawned her but when you choose any class she says there's none available.
