### ISSUE TITLE
The Battle for Mount Hyjal has no loot after kill the monster

### ISSUE THREAD

**Issue by ClueYang** [trickerer/Trinity-Bots#189]
There has no loot after kill the monster of the instance - “The Battle for Mount Hyjal”

**Comment by Slipy007** [comment]
> There has no loot after kill the monster of the instance - “The Battle for Mount Hyjal”

What's this has to do with the npcbots? If you used npcbots you have to do at least 25% damage yourself in order to get loot drops.

**Comment by trickerer** [comment]
#1.2

**Comment by trickerer** [comment]
Well, this condition can be changed but I always had doubts about doing it.

**Comment by ClueYang** [comment]
Actually I build WOW server with another repository named "[TrinityCore-3.3.5-with-NPCBots]",  and has this bug, So you will fix it, right?

**Comment by trickerer** [comment]
This is the main repository, which has NPCBots issue tracker.
The other is just a development repo and every commit here lists included NPCBots-related commits from [TrinityCore-3.3.5-with-NPCBots](https://github.com/trickerer/TrinityCore-3.3.5-with-NPCBots)

>So you will fix it, right?

Yeah, I think I'll change the condition to include bots' damage, see what happens

**Comment by ClueYang** [comment]
Thanks a lot, Looking forward to your reply again.

**Comment by trickerer** [comment]
https://github.com/trickerer/TrinityCore-3.3.5-with-NPCBots/commit/f7e4b42177dd8ee98c2c064b99597b1b11f1b2aa
