### ISSUE TITLE
Zandine, #70135, a female Draenei Hunter, has female Blood Elf dialogs

### ISSUE THREAD

**Issue by YunataSavior** [trickerer/Trinity-Bots#19]
Title. She should have female Draenei voice lines, not Belf.

How might I manually fix this?

**Comment by trickerer** [comment]
Wrong. Zandine is a blood elf hunter but has race set to 11 (draenei)
`UPDATE creature_template_npcbot_extras SET race=10 WHERE entry=70135;`
