### ISSUE TITLE
Reset NPCbot command walk

### ISSUE THREAD

**Issue by jasanhell1** [trickerer/Trinity-Bots#191]
Hello trckerer,

For the .npcbot command walk, would you please tell me how to reset back the npcbot to run?

It look like the player needs to log out to the world, and log in again and use **.npcbot command follow** to reset. 

If there is no way to reset the walk command, can you modify the .npcbot command follow to reset the walk command?

Thank you.

**Comment by trickerer** [comment]
`.npcbot command walk` toggles walk mode. Just use it again to switch bots back to run mode
