### ISSUE TITLE
Some customized spells are not unused

### ISSUE THREAD

**Issue by trickerer** [trickerer/Trinity-Bots#193]
While making extra classes I was always checking used spells to make sure they aren't used anywhere else in core or DB. But unfortunatelly it seems like I completely forgot about smart scripts. After I got an error from Lady Sevine trying to cast Summon Infernal Servant (Dreadlord spell) I checked smart scripts briefly and found out that some of the spells used by extra bot classes are still used elsewhere, including at least one belonging to raid creature.
Need to review those choices and find replacements.

**Comment by Mr-Deadbeat** [comment]
> While making extra classes I was always checking used spells to make sure they aren't used anywhere else in core or DB. But unfortunatelly it seems like I completely forgot about smart scripts. After I got an error from Lady Sevine trying to cast Summon Infernal Servant (Dreadlord spell) I checked smart scripts briefly and found out that some of the spells used by extra bot classes are still used elsewhere, including at least one belonging to raid creature. Need to review those choices and find replacements.

does this also affect those that are not using the custom classes as well ? just wondering since i have not noticed anything odd / out of the ordinary only 2 of us playing on my server so not a lot of input if you know what i mean ;)

**Comment by trickerer** [comment]
SpellInfo changes are applied regardless of custom classes being used or enabled even. So, yes, this affects everyone. There are not that many spells used in total so most players won't notice a thing, but in worldserver console you may see at some point an error message about some non-bot get denied spell cast due to that spell being used by custom bot class.
