### ISSUE TITLE
ICC Gunship Bug

### ISSUE THREAD

**Issue by Krutok** [trickerer/Trinity-Bots#196]
So today I was at ICC Raids with my NPC bots. And the gunship would usually be the end.

The problem is when I use the cannon all the bots use cannons and suddenly a lot of cannons spawn on the ship simulating what I'm doing. There is no longer a bot on the ship to then attack the mobs on the ship.

Also, the bots have problems with elevators, when I go up or down, they tend to fly with me or accidentally add other groups. I've now set up a portal in the ICC at the gunship that teleports you up to skip it and the bots probably have trouble with that too because they don't teleport to me but stagger through the air or something, like that Summon an order wouldn't be bad so it doesn't matter if in combat or not all bots will teleport to you.

**Comment by trickerer** [comment]
>Also, the bots have problems with elevators, when I go up or down, they tend to fly with me or accidentally add other groups. I've now set up a portal in the ICC at the gunship that teleports you up to skip it and the bots probably have trouble with that too because they don't teleport to me but stagger through the air or something, like that Summon an order wouldn't be bad so it doesn't matter if in combat or not all bots will teleport to you.

Unlike transports, there is no elevator handling in TC (any emulator actually, I think).
Use `.npcbot recall teleport`

>The problem is when I use the cannon all the bots use cannons and suddenly a lot of cannons spawn on the ship simulating what I'm doing. There is no longer a bot on the ship to then attack the mobs on the ship.

Tanks and pure healers (without DPS role) do not use cannons. Maximum bots using cannons is 8 for 10man and 12 for 25man.

**Comment by Krutok** [comment]
But then the fight cannot be managed because the bots do not shoot at the opponents from the other ship, for example.

Example a hunter or magician does not attack the enemy on the other ship so that you cannot win the fight with bots.

The other is if you dismiss a bot it will enrage, that might be a fun feature but you should be able to turn that on or off in the config because if I get 10 bots and dismiss them all they all enrage and without GM ON mode they even attack me and kill me or kill other bots etc.

Therefore please install it as an optional feature, i.e. via Config.
And this buff lasts 5 minutes and if someone else tries to summon the bot they will be killed. As a GM, I can reset the stats in debug mode, but a normal player cannot.

**Comment by trickerer** [comment]
https://github.com/trickerer/TrinityCore-3.3.5-with-NPCBots/commit/4718c0a98b6700fe2f50b4a94ce56a7fab45587c
That's it for enrage.

So, what would you suggest? I personally have no idea how to setup this encounter properly. Bots will not attack archers/mages on their own because these mobs do not `attack` anything, they just cast spells, not targeting anything in particular. You'll need to use ranged DPS icon(s) especially so your melee tank doesn't rush there too. You also need a heal target icon on your ship commander so bots do not slack on those mobs on your ship. And the amount of bots using cannons is the most troubling part, I'm not sure if making a way to configure that for each player is a good idea.

**Comment by Krutok** [comment]
I have now found a temporary solution for myself. I've done it like Blizzard did for the retail servers, so you can do the fight solo, so to speak. I simply increased the damage from the spell and it now has 1 million dps and the fight is over after 1-2 shots.

**Comment by trickerer** [comment]
Couple adjustments may be necessary, but otherwise I consider this completed
