### ISSUE TITLE
Боты, созданные командой '.npcbot createnew', не переносятся командой '.npcbot dump' на другой сервер

### ISSUE THREAD

**Issue by Parkan1986** [trickerer/Trinity-Bots#197]
Проблема такова что команда npcbot dump write записывает   информацию о новых ботах только в таблицы creature,character_npcbots.А вот в таблицу creature_template не добавляет ничего и из-за этого возникают ошибки при запуске сервера по типу таких:
Table `creature` has creature (GUID: 15000224) with non existing creature entry 70800, skipped.
Cannot find creature_template entry for npcbot (id: 70800)!

Т.е созданные админом боты записываються в дамп но невозможно будет их запустить на новом сервере(или переустановленном с нуля сервере)

**Comment by trickerer** [comment]
Проблема, которую решают команды dump, состоит в том, что невозможно сохранить и потом восстановить эти записи с помощью одного лишь SQL. С шаблонами всё проще и надёжней, достаточно задампить записи с entry от 70800 до 70999 из таблиц `creature_template`, `creature_template_npcbot_appearance` и `creature_template_npcbot_extras`, и залить куда требуется.

Есть ещё один способ, ещё более простой и надёжный, при условии отсутствия пустых промежутков между записями в `creature_template` между 70800 и 70999: сохранить аргументы комманды `.npcbot createnew` и потом просто их запустить в правильном порядке на новой БД. Получить их можно с помощью запроса в world:
```SELECT na.entry as '*','.npcbot createnew',na.`name*` as name,ne.class,ne.race,na.gender,na.skin,na.face,na.hair as hairstyle,na.haircolor,na.features FROM creature_template_npcbot_extras ne JOIN creature_template_npcbot_appearance na ON na.entry = ne.entry WHERE na.entry BETWEEN 70800 AND 70999;```

**Comment by trickerer** [comment]
Вывод (Navicat):
```
| *     | .npcbot createnew | name  | class | race | gender | skin | face | hairstyle | haircolor | features |
| 70800 | .npcbot createnew | Turak |    11 |    6 |      0 |    4 |    3 |         5 |         0 |        5 |
```
