### ISSUE TITLE
Possible to back port this to vanilla 1.12.1?

### ISSUE THREAD

**Issue by hggz** [trickerer/Trinity-Bots#200]
Title says it all. Can this be back ported to 1.12.1 easily?

**Comment by trickerer** [comment]
Class AI relies on avalaible spells, how spells and talents work (whole team, not just that bot), and this is just class AI. Core AI... don't even get me started. Oh, and TC doesn't have its own classic, so that should be a different core also?

Can all this revamp be done easily? I don't think so.
