### ISSUE TITLE
Transfer to Azerothcore

### ISSUE THREAD

**Issue by xBarselonx** [trickerer/Trinity-Bots#206]
Здравствуйте, вы можете перенести этих ботов NPC в Azerothcore? (https://github.com/azerothcore/azerothcore-wotlk)

**Comment by trickerer** [comment]
В качестве модуля - нереально, нужны серьёзные изменения в API.
Сам код перенести можно, это задача на несколько дней минимум. На выходных посмотрю.

**Comment by xBarselonx** [comment]
> В качестве модуля - нереально, нужны серьёзные изменения в API.
> Сам код можно перенести, это задача минимум на несколько дней. На выходных посмотрю.

Я так понимаю, это это будет отдельная ветка или как с Тиринитикор боты ввиде патча?

**Comment by trickerer** [comment]
Скорее всего и то, и другое.

**Comment by xBarselonx** [comment]
trickerer, есть продвижение по моему запросу?

**Comment by trickerer** [comment]
Есть, но работы ещё много. За последние пару лет в тринити было многое сделано обратно-несовместимым. Так что придётся искать по изменениям в ботах что нужно откатить. Некоторые вещи прямо придётся обратно переписывать. Как, например, команды.

**Comment by souloi** [comment]
i also need

**Comment by trickerer** [comment]
Репозиторий:
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots

https://github.com/trickerer/Trinity-Bots/commit/40b72c2a8edf4d5099812a6739a0437baed7de73

Патч будет выкладываться здесь:
https://github.com/trickerer/Trinity-Bots/blob/master/AC/NPCBots.patch
