### ISSUE TITLE
Ошибка СМаке

### ISSUE THREAD

**Issue by xBarselonx** [trickerer/Trinity-Bots#211]
Добрый день! Давно не обновлял ветку, сегодня решил обновить. Запусти СМаке получил ошибку. 
![image](https://user-images.githubusercontent.com/99982508/192091926-a8c3fdd7-3d96-4e20-9cbb-4dc5631170b5.png)

**Comment by trickerer** [comment]
Не вижу никаких ошибок на свежем клоне. Из твоего скриншота совершенно не ясно что за ошибку ты получаешь.

![cmake_220924](https://user-images.githubusercontent.com/1254989/192092791-0bbe8094-6675-46fd-9143-368b4ab16f8a.jpg)

**Comment by xBarselonx** [comment]
После нажатия Configure появляется ошибка что на моем скрине.

**Comment by xBarselonx** [comment]
trickerer, мне удалось решить проблему путем переустановки СМаке.
