### ISSUE TITLE
Not Kompatible with last TrinityCore from 2.10

### ISSUE THREAD

**Issue by Krutok** [trickerer/Trinity-Bots#215]
Error at unit.cpp

> patching file src/server/game/Entities/Unit/Unit.cpp
Hunk #4 FAILED at 1036.
Hunk #5 succeeded at 1086 (offset -12 lines).
Hunk #6 succeeded at 1241 (offset -12 lines).
Hunk #7 succeeded at 1262 (offset -12 lines).
Hunk #8 succeeded at 1558 (offset -12 lines).
Hunk #9 succeeded at 1688 (offset -12 lines).
Hunk #10 succeeded at 1799 (offset -12 lines).
Hunk #11 succeeded at 1958 (offset -12 lines).
Hunk #12 succeeded at 2240 (offset -12 lines).
Hunk #13 succeeded at 2263 (offset -12 lines).
Hunk #14 succeeded at 2320 (offset -12 lines).
Hunk #15 succeeded at 2674 (offset -33 lines).
Hunk #16 succeeded at 2700 (offset -33 lines).
Hunk #17 succeeded at 2760 (offset -33 lines).
Hunk #18 succeeded at 2794 (offset -33 lines).
Hunk #19 succeeded at 2827 (offset -33 lines).
Hunk #20 succeeded at 2871 (offset -33 lines).
Hunk #21 succeeded at 3977 (offset -33 lines).
Hunk #22 succeeded at 5227 (offset -33 lines).
Hunk #23 succeeded at 5760 (offset -33 lines).
Hunk #24 succeeded at 5864 (offset -33 lines).
Hunk #25 succeeded at 6476 (offset -33 lines).
Hunk #26 succeeded at 6509 (offset -33 lines).
Hunk #27 succeeded at 6799 (offset -33 lines).
Hunk #28 succeeded at 7137 (offset -33 lines).
Hunk #29 succeeded at 7178 (offset -33 lines).
Hunk #30 succeeded at 7211 (offset -33 lines).
Hunk #31 succeeded at 7441 (offset -33 lines).
Hunk #32 succeeded at 7667 (offset -33 lines).
Hunk #33 succeeded at 7812 (offset -33 lines).
Hunk #34 succeeded at 8255 (offset -33 lines).
Hunk #35 succeeded at 8394 (offset -33 lines).
Hunk #36 succeeded at 8483 (offset -33 lines).
Hunk #37 succeeded at 8739 (offset -33 lines).
Hunk #38 succeeded at 9123 (offset -33 lines).
Hunk #39 succeeded at 9205 (offset -33 lines).
Hunk #40 succeeded at 10396 (offset -33 lines).
Hunk #41 succeeded at 10418 (offset -33 lines).
Hunk #42 succeeded at 10807 (offset -33 lines).
Hunk #43 succeeded at 10962 (offset -33 lines).
Hunk #44 succeeded at 11243 (offset -33 lines).
Hunk #45 succeeded at 11432 (offset -33 lines).
Hunk #46 succeeded at 12240 (offset -33 lines).
Hunk #47 succeeded at 12269 (offset -33 lines).
Hunk #48 succeeded at 12307 (offset -33 lines).
Hunk #49 succeeded at 12330 (offset -33 lines).
Hunk #50 succeeded at 12434 (offset -33 lines).
Hunk #51 succeeded at 12521 (offset -33 lines).
Hunk #52 succeeded at 12587 (offset -33 lines).
Hunk #53 succeeded at 12846 (offset -33 lines).
Hunk #54 succeeded at 13713 (offset -33 lines).
1 out of 54 hunks FAILED -- saving rejects to file src/server/game/Entities/Unit/Unit.cpp.rej
patching file src/server/game/Entities/Unit/Unit.h
Hunk #3 succeeded at 1831 (offset -1 lines).

```
src/server/game/Entities/Unit/Unit.cpp.rej--- src/server/game/Entities/Unit/Unit.cpp
+++ src/server/game/Entities/Unit/Unit.cpp
@@ -1036,6 +1061,18 @@ void Unit::CalculateSpellDamageTaken(SpellNonMeleeDamage* damageInfo, int32 dama
             case SPELL_DAMAGE_CLASS_RANGED:
             case SPELL_DAMAGE_CLASS_MELEE:
             {
+                //NpcBot mod: apply bot damage mods
+                if (GetTypeId() == TYPEID_UNIT && ToCreature()->IsNPCBotOrPet())
+                {
+                    //TODO: rename to ApplyBotDamageMultiplierPhysical
+                    ToCreature()->ApplyBotDamageMultiplierMelee(damage, *damageInfo, spellInfo, attackType, crit);
+                    if (damageSchoolMask & SPELL_SCHOOL_MASK_NORMAL)
+                        damage *= BotMgr::GetBotDamageModPhysical();
+                    else if (damageSchoolMask & SPELL_SCHOOL_MASK_MAGIC)
+                        damage *= BotMgr::GetBotDamageModSpell();
+                }
+                //End NpcBot
+
                 // Physical Damage
                 if (damageSchoolMask & SPELL_SCHOOL_MASK_NORMAL)
                 {

```

**Comment by trickerer** [comment]
Updates from upstream are merged once a week, at saturday morning.

It's a shame a compatibility-breaking change came right after the merge.

**Comment by Krutok** [comment]
But why do you have to download the core every time you use the original TrinityCore when you want to import the new patch? Because the patch -p1 < filename only works once, when a new patch appears, I have to delete the old core, download it again and then patch it.

**Comment by trickerer** [comment]
You don't. There is a patched repository which you only need to synchronize with.
The patch exists only because this is how it all started. Well now it also serves as a centralized issue tracker. Also, patch commits list the exact commits which patch update includes, this is useful sometimes.

**Comment by Mr-Deadbeat** [comment]
> But why do you have to download the core every time you use the original TrinityCore when you want to import the new patch? Because the patch -p1 < filename only works once, when a new patch appears, I have to delete the old core, download it again and then patch it.

actually you don't you can revert the patch git pull core updates and then reapply patch like so 

patch -p1 -R < filename # reverts previous patch
git pull                            # updates core files
patch -p1 < filename     # re-apply patch

this assumes the changes all still work and there are no issues
in this case it would not work until the incompatible changes have been fixed like trickerer mentions

**Comment by Krutok** [comment]
> Updates from upstream are merged once a week, at saturday morning.
> 
> It's a shame a compatibility-breaking change came right after the merge.

as you said it was not updated.
the old patch is still in there. or do you have to wait until 8.10?

**Comment by trickerer** [comment]
https://github.com/trickerer/Trinity-Bots/commit/0a0185ec7478a6714b41aa6d3ab3d943b2e54a42
