### ISSUE TITLE
Копирование существующих ботов

### ISSUE THREAD

**Issue by xBarselonx** [trickerer/Trinity-Bots#216]
Несколько вопросов:
1. Могу скопировать уже имеющихся ботов в базе. Например: в базе world в таблицах creature_template_npcbot_appearance и creature_template_npcbot_extras есть бот орк воин Malosh. Могу я копированием строк в таблицах создать еще одного бота воина с новым ID 70466 (например) и назвать его  Molash?
2. Я правильно понял максимальное количество ботов на сервере 312, т.е. если я один играю то могу создать именно это количество ботов?
3. Не совсем понял процедуру локализации мода NPCBot в твоем мануале
"Все локализуемые строки содержатся в npc_textтаблице. Если вы хотите сделать перевод, вам придется соответствующим образом заполнить npc_text_localeтаблицу ( Text0_0поле)". Можно ли перевести меню сплетен в ПНЦ ботами самому и как?

**Comment by trickerer** [comment]
1. Можешь, но я рекомендую использовать команду `.npcbot createnew`. Потому инструкций по копированию не даю.
2. Нет. Это количество ботов, включённых в чистую установку. Просто каждого бота можно заспавнить лишь раз, так что я добавил эту информацию в инструкцию.
3. Весь локализуемый текст находится в таблице `npc_text` в поле `Text0_0`. Текст ботов это айдишники 70000-71000. Для добавления локализации переведённый текст нужно, с тем же айдишником, записать в таблицу `npc_text_locale` в то же поле, указав в поле `locale` язык (ruRU вроде). Если клиент русскоязычный, сервер его опознает и будет использовать этот - переведённый - текст.

**Comment by xBarselonx** [comment]
> 2\. Нет. Это количество ботов, включённых в чистую установку. Просто каждого бота можно заспавнить лишь раз, так что я добавил эту информацию в инструкцию.

Т.е. в настройке ворлдконфига NpcBot.MaxBots 39 ботов, это значит что я могу создать максимум это количество? Верно?

**Comment by trickerer** [comment]
Нет. Это максимальное количество **нанятых** ботов. Что позволяет создать одному игроку создать полноразмерный рейд (40 с игроком)
Никаких ограничений для спавна, кроме естественных, нет.

**Comment by trickerer** [comment]
> Ты имеешь ввиду НПЦ самого мира WoW (я имею ввиду не твои боты которых ты интегрировал)?

Нет.

> Bots available to spawn: 312

Больше заспавнить невозможно физически (без создания новых). Это и есть естественное ограничение.
