### ISSUE TITLE
Добавление настройки в worldserver.conf

### ISSUE THREAD

**Issue by xBarselonx** [trickerer/Trinity-Bots#217]
Возможно ли добавить в worldserver.conf настройку связанную с созданием бота одетого в наследуемые предметы или без них, т.е. ее включение или отключение?

**Comment by trickerer** [comment]
Конкретней. О каких наследуемых предметах идёт речь? При создании (спавне) бота у него нет никаких предметов.

**Comment by xBarselonx** [comment]
> Конкретней. О каких наследуемых предметах идёт речь? При создании (спавне) бота у него нет никаких предметов.

Например, создаем бота вара и на нем по умолчанию уже одет двуручным топор ( https://base.opiums.eu/?item=42943), плечо (https://base.opiums.eu/?item=42949), грудь (https://base.opiums.eu/?item=48685), кольцо ( https://base.opiums.eu/?item=50255) и 2 трини ( https://base.opiums.eu/?item=42991). Предметы взял не с вовхеда, но суть та же. Также в инвентарь можно добавить все предметы которыми может носить воин и в зависимости от выбранной игроком специализации бота будет их брать из своего инвентаря и их надевать.

**Comment by trickerer** [comment]
У ботов нет сумок и не предвидется. Так что они не могут носить с собой сменные предметы

Что касается начального снаряжения, то боты не создают никаких предметов, даже в слотах инвентаря. Предметы либо получены от игрока, либо существуют только визуально

Чисто теоретически, возможен конфиг в виде
```
NpcBot.RealEquipmentStart.<CLASS> = id1,id2,id3,...,idn
```
после чего предметы с данными ID можно создавать и пытаться одевать в них бота, заменяя таким образом стандартное снаряжение. Такие предметы нельзя будет забрать.

Проблем здесь несколько. Главная из них - бота может нанять игрок любого уровня и на 1 уровне гонять с ботами, одетыми в топ 80

**Comment by xBarselonx** [comment]
[trickerer](https://github.com/trickerer), что касается создание бота с одетыми фамилками это не критично. Просто было интересно в плане реализации на сервере.  В любом случае есть команда .add id предмета)).
