### ISSUE TITLE
Target Marking mask thing??

### ISSUE THREAD

**Issue by conjections** [trickerer/Trinity-Bots#219]
So I saw in the NpcBot settings below that there's an option to HealTargetIconsMask, with other role options. This would be super helpful to me if I could figure out how to do this. But I have no idea how to get there? Is it a command within the game? Or is it in a file somewhere that you have to edit?

**Comment by trickerer** [comment]
No, no. It is actually pretty easy to use.
Just set it to desired value in config. For example, `NpcBot.HealTargetIconsMask=8` (green triangle). Save and `.npcbot reloadconfig` (or restart the server). Right-click and set the icon on a valid assist target.
More info: https://github.com/trickerer/Trinity-Bots#npcbot-config-settings

**Comment by conjections** [comment]
Sorry I'm such a noob lol. Where is the config located? Was it a command? Am I missing an update? If I have to just type exactly that in the text chat, I'll try that when I get home for work. Apologize for my density.

**Comment by trickerer** [comment]
> Where is the config located?

In worldserver.conf in your server folder, where you run your worldserver from
> Was it a command?

No, it's just a config setting. You've mentioned it your first post
> Am I missing an update?

Nope. You just need to be in a group for this to work

**Comment by conjections** [comment]
Thank you my friend. :)
