### ISSUE TITLE
bug build 

### ISSUE THREAD

**Issue by seb91150** [trickerer/Trinity-Bots#22]
hello,
i have a probleme with install afer 

wow@xunb:~/TrinityCore/build$ cmake ../ -DCMAKE_INSTALL_PREFIX=/home/$USER/server -DTOOLS=1 -DWITH_WARNINGS=1
-- Detected 64-bit platform
-- UNIX: Using default configuration directory
-- UNIX: Configuring uninstall target
-- UNIX: Created uninstall target
-- UNIX: Detected compiler: /usr/bin/cc
-- Clang: All warnings enabled
-- Using mysql-config: /usr/bin/mysql_config
-- Found MySQL library: /usr/lib/x86_64-linux-gnu/libmariadb.so
-- Found MySQL headers: /usr/include/mariadb
-- Found MySQL executable: /usr/bin/mysql
-- Found git binary : /usr/bin/git

* TrinityCore revision   : 9fe6756cf26e+ 2020-07-14 23:15:33 +0200 (3.3.5 branch)
* TrinityCore buildtype  : RelWithDebInfo

* Install core to        : /home/wow/server
* Install configs to     : /home/wow/server/etc
* Install configs to     : /home/wow/server/etc

* Build world/auth       : Yes (default)
* Build with scripts     : Yes (static)
* Build map/vmap tools   : Yes (default)
* Build core w/PCH       : Yes (default)
* Build scripts w/PCH    : Yes (default)
* Show all warnings      : Yes
* Use coreside debug     : No  (default)
* Show source tree       : Yes (hierarchical)
* Use GIT revision hash  : Yes (default)

-- Found OpenSSL library: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so
-- Found OpenSSL headers: /usr/include
-- Found Readline library: /usr/lib/x86_64-linux-gnu/libreadline.so
-- Include dir is: /usr/include

* Script configuration (static):
    |
    +- worldserver
    |   +- Battlefield
    |   +- Commands
    |   +- Custom
    |   +- EasternKingdoms
    |   +- Events
    |   +- Kalimdor
    |   +- Northrend
    |   +- OutdoorPvP
    |   +- Outland
    |   +- Pet
    |   +- Spells
    |   +- World
    |

-- Configuring done
-- Generating done
-- Build files have been written to: /home/wow/TrinityCore/build

wow@xunb:~/TrinityCore/build$ make -j 4 install
[  0%] Built target Detour
[  0%] Built target fmt
[  1%] Built target Recast
[  5%] Built target g3dlib
[  5%] Built target sfmt
[  6%] Built target argon2
[  6%] Built target gsoap
[  9%] Built target jemalloc
[ 10%] Built target mpq
[ 10%] Built target revision_data.h
[ 15%] Built target common
[ 16%] Built target vmap4extractor
[ 18%] Built target database
[ 19%] Built target mapextractor
[ 19%] Built target vmap4assembler
[ 20%] Built target mmaps_generator
[ 20%] Built target shared
[ 20%] Built target authserver
[ 20%] Building CXX object src/server/game/CMakeFiles/game.dir/cmake_pch.hxx.pch
[ 20%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Battlefield/BattlefieldWG.cpp.o
[ 20%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Commands/cs_achievement.cpp.o
[ 20%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Commands/cs_arena.cpp.o
In file included from /home/wow/TrinityCore/src/server/scripts/Commands/cs_achievement.cpp:26:
In file included from /home/wow/TrinityCore/src/server/game/Achievements/AchievementMgr.h:23:
/home/wow/TrinityCore/src/server/game/DataStores/DBCStores.h:146:32: fatal error: use of undeclared identifier 'ItemDisplayInfoEntry'
TC_GAME_API extern DBCStorage <ItemDisplayInfoEntry>         sItemDisplayInfoStore;
                               ^
In file included from /home/wow/TrinityCore/src/server/scripts/Battlefield/BattlefieldWG.cpp:23:
In file included from /home/wow/TrinityCore/src/server/game/Achievements/AchievementMgr.h:23:
/home/wow/TrinityCore/src/server/game/DataStores/DBCStores.h:146:32: fatal error: use of undeclared identifier 'ItemDisplayInfoEntry'
TC_GAME_API extern DBCStorage <ItemDisplayInfoEntry>         sItemDisplayInfoStore;
                               ^
1 error generated.
make[2]: *** [src/server/scripts/CMakeFiles/scripts.dir/build.make:139: src/server/scripts/CMakeFiles/scripts.dir/Commands/cs_achievement.cpp.o] Error 1
make[2]: *** Attente des tâches non terminées....
1 error generated.
make[2]: *** [src/server/scripts/CMakeFiles/scripts.dir/build.make:94: src/server/scripts/CMakeFiles/scripts.dir/Battlefield/BattlefieldWG.cpp.o] Error 1
In file included from <built-in>:1:
In file included from /home/wow/TrinityCore/build/src/server/game/CMakeFiles/game.dir/cmake_pch.hxx:5:
In file included from /home/wow/TrinityCore/src/server/game/PrecompiledHeaders/gamePCH.h:21:
/home/wow/TrinityCore/src/server/game/DataStores/DBCStores.h:146:32: fatal error: use of undeclared identifier 'ItemDisplayInfoEntry'
TC_GAME_API extern DBCStorage <ItemDisplayInfoEntry>         sItemDisplayInfoStore;
                               ^
1 error generated.
make[2]: *** [src/server/game/CMakeFiles/game.dir/build.make:64: src/server/game/CMakeFiles/game.dir/cmake_pch.hxx.pch] Error 1
make[1]: *** [CMakeFiles/Makefile2:1241: src/server/game/CMakeFiles/game.dir/all] Error 2
make[1]: *** Attente des tâches non terminées....
make[1]: *** [CMakeFiles/Makefile2:1311: src/server/scripts/CMakeFiles/scripts.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

I am stuck
someone would have an idea
thx 
seb

**Comment by YunataSavior** [comment]
1. You are on the TrinityCore 3.3.5a branch, correct?
2. What commit ID are you using?

**Comment by seb91150** [comment]
1- i have https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130077/Installation+Guide
2- i don't understand what id

**Comment by seb91150** [comment]
I typed these commands
cp ../Trinity-Bots/last/NPCBots.patch ./
patch -p1 < NPCBots.patch
cmake ../ -DCMAKE_INSTALL_PREFIX=/home/$USER/server -DTOOLS=1 -DWITH_WARNINGS=1
make -j 4 install

**Comment by YunataSavior** [comment]
I was referring to the git commit ID of your TrinityCore source code

**Comment by seb91150** [comment]
git clone -b 3.3.5 git://github.com/TrinityCore/TrinityCore.git
--

**Comment by seb91150** [comment]
not master

**Comment by seb91150** [comment]
Commits on Jul 14, 2020

**Comment by YunataSavior** [comment]
Please don't use that commit; try:

https://github.com/TrinityCore/TrinityCore/commit/4a4aac61d59c8202166c7bb7065385acc4a11ea7

**Comment by seb91150** [comment]
okay i test thx

**Comment by seb91150** [comment]
it ok when ./worldserver 
Could not connect to MySQL database at 127.0.0.1: Unknown database 'auth'
Could not connect to MySQL database at 127.0.0.1: Unknown database 'characters'
Could not connect to MySQL database at 127.0.0.1: Unknown database 'world'
In mysql_stmt_prepare() id: 460, sql: "UPDATE characters_npcbot SET owner = ? WHERE entry = ?"
Table 'characters.characters_npcbot' doesn't exist
In mysql_stmt_prepare() id: 461, sql: "UPDATE characters_npcbot SET owner = ? WHERE owner = ?"
Table 'characters.characters_npcbot' doesn't exist
In mysql_stmt_prepare() id: 462, sql: "UPDATE characters_npcbot SET roles = ? WHERE entry = ?"
Table 'characters.characters_npcbot' doesn't exist
In mysql_stmt_prepare() id: 464, sql: "UPDATE characters_npcbot SET equipMhEx = ?, equipOhEx = ?, equipRhEx = ?, equipHead = ?, equipShoulders = ?, equipChest = ?, equipWaist = ?, equipLegs = ?, equipFeet = ?, equipWrist = ?, equipHands = ?, equipBack = ?, equipBody = ?, equipFinger1 = ?, equipFinger2 = ?, equipTrinket1 = ?, equipTrinket2 = ?, equipNeck = ? WHERE entry = ?"
Table 'characters.characters_npcbot' doesn't exist
In mysql_stmt_prepare() id: 465, sql: "DELETE FROM characters_npcbot WHERE entry = ?"
Table 'characters.characters_npcbot' doesn't exist
In mysql_stmt_prepare() id: 466, sql: "INSERT INTO characters_npcbot (entry, roles, spec, faction) VALUES (?, ?, ?, ?)"
Table 'characters.characters_npcbot' doesn't exist
In mysql_stmt_prepare() id: 467, sql: "UPDATE characters_npcbot SET faction = ? WHERE entry = ?"
Table 'characters.characters_npcbot' doesn't exist
In mysql_stmt_prepare() id: 468, sql: "UPDATE characters_npcbot SET spec = ? WHERE entry = ?"
Table 'characters.characters_npcbot' doesn't exist
In mysql_stmt_prepare() id: 460, sql: "UPDATE characters_npcbot SET owner = ? WHERE entry = ?"
Table 'characters.characters_npcbot' doesn't exist
In mysql_stmt_prepare() id: 461, sql: "UPDATE characters_npcbot SET owner = ? WHERE owner = ?"
Table 'characters.characters_npcbot' doesn't exist
In mysql_stmt_prepare() id: 462, sql: "UPDATE characters_npcbot SET roles = ? WHERE entry = ?"
Table 'characters.characters_npcbot' doesn't exist
In mysql_stmt_prepare() id: 464, sql: "UPDATE characters_npcbot SET equipMhEx = ?, equipOhEx = ?, equipRhEx = ?, equipHead = ?, equipShoulders = ?, equipChest = ?, equipWaist = ?, equipLegs = ?, equipFeet = ?, equipWrist = ?, equipHands = ?, equipBack = ?, equipBody = ?, equipFinger1 = ?, equipFinger2 = ?, equipTrinket1 = ?, equipTrinket2 = ?, equipNeck = ? WHERE entry = ?"
Table 'characters.characters_npcbot' doesn't exist
In mysql_stmt_prepare() id: 465, sql: "DELETE FROM characters_npcbot WHERE entry = ?"
Table 'characters.characters_npcbot' doesn't exist
In mysql_stmt_prepare() id: 466, sql: "INSERT INTO characters_npcbot (entry, roles, spec, faction) VALUES (?, ?, ?, ?)"
Table 'characters.characters_npcbot' doesn't exist
In mysql_stmt_prepare() id: 467, sql: "UPDATE characters_npcbot SET faction = ? WHERE entry = ?"
Table 'characters.characters_npcbot' doesn't exist
In mysql_stmt_prepare() id: 468, sql: "UPDATE characters_npcbot SET spec = ? WHERE entry = ?"
Table 'characters.characters_npcbot' doesn't exist

**Comment by seb91150** [comment]
i don' t understand

 Apply SQL files from /TrinityCore/sql/Bots/ to your DB (files starting with characters_ and world_ go into your characters and world DB respectively):

1_world_bot_appearance.sql
2_world_bot_extras.sql
3_world_bots.sql
4_world_generate_bot_equips.sql
5_world_botgiver.sql
characters_bots.sql
Apply SQL update files from /TrinityCore/sql/Bots/updates to your DB
And after that you are ready to go

**Comment by trickerer** [comment]
You forgot to install DB part. SQL files are in your `TrinityCore/sql/Bots` folder

**Comment by seb91150** [comment]
i m sorry i am noobs
How do I do
in my folder i have 
wow@xunb:~/TrinityCore/sql/Bots$ ll
total 164
drwxrwxr-x 3 wow wow   4096 juil. 15 09:40 ./
drwx------ 8 wow wow   4096 juil. 15 09:40 ../
-rw-r--r-- 1 wow wow   9586 juil. 15 09:40 1_world_bot_appearance.sql
-rw-r--r-- 1 wow wow   7828 juil. 15 09:40 2_world_bot_extras.sql
-rw-r--r-- 1 wow wow 117235 juil. 15 09:40 3_world_bots.sql
-rw-r--r-- 1 wow wow   5381 juil. 15 09:40 4_world_generate_bot_equips.sql
-rw-r--r-- 1 wow wow   1629 juil. 15 09:40 5_world_botgiver.sql
-rw-r--r-- 1 wow wow   1417 juil. 15 09:40 characters_bots.sql
drwxrwxr-x 4 wow wow   4096 juil. 15 09:40 update
I didn't put it in there. they appeared

**Comment by seb91150** [comment]
sudo mysql -uroot -p < 1_world_bot_appearance.sql ?

**Comment by seb91150** [comment]
i find with phpmyadmin thx for all
