### ISSUE TITLE
Thaddius won't awaken - Naxxramas

### ISSUE THREAD

**Issue by conjections** [trickerer/Trinity-Bots#223]
I've tried so many different tactics. ".die" on both of them in instant succession. I've tried having two groups of bots split up in the traditional method, ranged on one, melee on the other. The correct setup according to tutorials. I've tried having them killed as soon as they're tagged. Because sometimes that matters from what I've seen. One of the main problems that botches half of my attempts is sometimes one of them will get pulled away from it's coil. But even when they die right where they're standing, even after being engaged, in near instant succession. Thaddius doesn't seem to awaken.

**Comment by trickerer** [comment]
Can't confirm. Tested on both AC and TC. When both guys die from damage simulteniously Thaddius awakens as expected
![thadd](https://user-images.githubusercontent.com/1254989/198816093-edc70898-137b-4abb-b58a-bc3a2e275ece.jpg)
