### ISSUE TITLE
Update to TC Version 9b806c6

### ISSUE THREAD

**Issue by xenonjargarta** [trickerer/Trinity-Bots#23]
Hi everyone,

I try to update NPCBot top latest version. Arround 100Errors

Mainly 
- Change to STD::Chrono:Millseconds
- Change to OPTIONAL
- Renaming (based on DBCStructure)

2 issues are left in Unit.cpp (9115) and bot_ai.cpp

 **SpellShapeshiftFormEntry const* ssEntry = sSpellShapeshiftStore.LookupEntry(form);**

**sSpellShapeshiftStore is not declared.**

So same issue in both files. Maybe someone can give me an advise.
After this I can check for DB updates.

Thx

Zini

**Comment by trickerer** [comment]
sSpellShapeshift**Form**Store.LookupEntry(form);

**Comment by xenonjargarta** [comment]
Thanks trickerer, that helps. 

Now bot classes are compiling. I have to solve some cmake missconfiguration, but I think this is on my side. I will start with test when this is ready.

**Comment by xenonjargarta** [comment]
So good news, 
Code is compiling, server running, bots smashing creatures 👍 

There is one point we should improve before commit

ItemDisplayInfoEntry struct in DBCStructure is not used anymore (uncommented in the currend branch).

On our side we need it for uint32 ID; and char* InventoryIcon;

So 
1. if we use the full struct (today 12 items) we will get a runtime error while we try to load the .DPC  ...

> string (12) expected c++ struct expects (156)

2. If we just activate what we need (2 items) everthing is fine

see here

```
struct ItemDisplayInfoEntry
{
    uint32 ID;                                              // 0
   // char* ModelName[2];                                     // 1-2
   // char* ModelTexture[2];                                  // 3-4
    char* InventoryIcon;                                 // 5-6
   // uint32 GeosetGroup[3];                                  // 7-9
   // uint32 Flags;                                           // 10
   // uint32 SpellVisualID;                                   // 11
   // uint32 GroupSoundIndex;                                 // 12
   // uint32 HelmetGeosetVisID[2];                            // 13-14
   // char* Texture[8];                                       // 15-22
   // int32 ItemVisual;                                       // 23
   // uint32 ParticleColorID;                                 // 24
};
```
Ok aim should be to use the current struct replacing ItemDisplayInfoEntry.

https://github.com/TrinityCore/TrinityCore/commit/c92950b3e1f6366d85d707365a8ad2caddafeecc includes this massive change
on names/structure.

If someone can identify which struct is replacing ItemDisplayInfoEntry, I can try to create patch file more compatible to the current code.

In meantime I will try to update the patch file for the current changes.

Regards Zini

**Comment by trickerer** [comment]
I wonder if compiler complains about this change, but anyway:

You should be able to fix that by replacing in bot_ai.cpp: 'itemDisplayEntry->InventoryIcon' with 'itemDisplayEntry->InventoryIcon**[0]**'

**Comment by xenonjargarta** [comment]
Hi trickerer,

For me the main issue is that we are using a strcut not used by Trinity anymore. But at the moment the code is running.

Not sure if you want to work with pull requests or handling it by your own,

but here is the new patch file to test

[NPCBots.patch.txt](https://github.com/trickerer/Trinity-Bots/files/5012721/NPCBots.patch.txt)

It is compatible and tested for
TrinityCore rev. 10f49793f9a7+ 2020-08-02 21:28:48 +0300 (3.3.5 branch) (Win64, Release, Static) 

I tested it with an existing updated DB and an complete new fresh DB.

As I said mainly 
- Change to STD::Chrono:Millseconds
- Change to OPTIONAL
- Renaming (based on DBCStructure changes)

Would be nice if you can check the patch file, you have more expirience with that.

Regards

Zini

**Comment by trickerer** [comment]
Thanks for your effort. Hope it helps people until I make an update.
Though this is clearly a mistake
```
if (((int)pEnchant->EffectPointsMin) > ((int)me->GetLevel()))
```
should be
```
if (pEnchant->MinLevel > me->GetLevel())
```

**Comment by Parkan1986** [comment]
Есть ли какие-нибудь движение по обновлению патча к текущей версии Тринити?

**Comment by trickerer** [comment]
Думаю через пару дней после [Authserver cleanup phase 5 - removal of sha_pass_hash](https://github.com/TrinityCore/TrinityCore/pull/25156)

**Comment by trickerer** [comment]
[1449f650e5](https://github.com/trickerer/Trinity-Bots/commit/1449f650e509b3aab6e87dfb01897939edc7193f)
