### ISSUE TITLE
NpcBot.Botgiver.FilterRaces = 1 (azerothcore)

### ISSUE THREAD

**Issue by Mr-Deadbeat** [trickerer/Trinity-Bots#236]
OS: Ubuntu 20.04.5
Commit: 70f1e3cb7dfaa698afb401fa461114b2202b4b65

FilterRaces seems to skip Blood elfs they are offered to wrong faction
noticed this just now when i was building a 10 man raid to test UBRS

**Comment by xBarselonx** [comment]
Всем привет! А что эта настройка делает? Если я верно понял, то после команды выбора класса будут предложены только те рассы фракции за которую играет персонаж (например орда, альянс исключается)? У меня она отключена и я играю за орду и при команде .npcbot spawn «id бота» мне предлагаются все рассы (орда+альянс).

**Comment by trickerer** [comment]
@xBarselonx эта настройка только для меню botgiver'а. Она проверяет на соответствие фракцию игрока и фракцию по умолчаюнию для расы бота при добавлении в список доступных для найма ботов.

**Comment by Mr-Deadbeat** [comment]
this issue has been resolved no idea what you guys are talking about so i'll let @trickerer decide if he wants to close this issue

thanks for the fix though much appreciated
