### ISSUE TITLE
Paladin still dissapearing / reappearing

### ISSUE THREAD

**Issue by Mr-Deadbeat** [trickerer/Trinity-Bots#237]
OS Ubuntu 20.04.5
Commit: 467403c0c3493d31762c1fc9b1b2fe1ac7d9107d

Modules:
mod-ah-bot
mod-autobalance (disabled) due to some other issue
mod-eluna
mod-ip-tracker
mod-weekend-xp

Bot having issues is Wilhelm

was doing Dire Maul and paladin bot started vanishing / reappearing over and over tried everything hid the bots unhid them
nothing works

this glitch comes and goes so no idea what might cause it i thought it might be server running short on ram 24gb bumped it up to 32gb still happening running with this much ram for the VM due to having all non instanced maps loaded at startup
roaming monsters and patrols makes for a more fun experience ;)

**Comment by trickerer** [comment]
Dire Maul is huge. When did this happen and where exactly?

**Comment by Mr-Deadbeat** [comment]
> Dire Maul is huge. When did this happen and where exactly?

it happened all over dire maul i was testing out Immol'thar after disabling mod-autobalance and all of a sudden he started vanishing / reappearing it only happens with the paladin none of the other bots seems to be affected also happened outside dire maul while going back to Feathermoon stronghold it seems to fix itself if i logout from the game and login again
quite annoying to say the least ;) it seems to happen after some time i had been playing for hours before he started glitching 
hence i thought it might be ram related really strange this never happened on Trinitycore so something is different for sure

**Comment by Mr-Deadbeat** [comment]
update now the priest in group is having the same symptoms i was running around BRD doing lord incendius
so apparently it's not only paladins behaving like this :( so i would assume it's all bots as of now random who gets it
it's always only 1 bot doing it when it happens

**Comment by zaicopx** [comment]
I also experienced the same thing and it often happens to paladin bots.
For my case, it usually happened after me and npcbot boarded the ship.  After arriving at the destination dock and it happened.
To fix this, you have to restart the server, because if you don't restart the server and just relog, the npcbot will disappear and it won't even appear where it was spawned.

**Comment by Mr-Deadbeat** [comment]
> I also experienced the same thing and it often happens to paladin bots. For my case, it usually happened after me and npcbot boarded the ship. After arriving at the destination dock and it happened. To fix this, you have to restart the server, because if you don't restart the server and just relog, the npcbot will disappear and it won't even appear where it was spawned.

actually i think i might have found the problem causing the issues i ran the server with enGB client data and same client on gaming rig and with that client data it has been one issue after another quest exclamation marks missing / quest hand in markers missing so i started to suspect it might be client related issues so last night i switched to the enUS client and data for the server and so far i have not been able to trigger the vanishing bot issue been playing for hours atm and not a single glitch so the EU version of the game client seems to be at the root of the issues

strange thing is i did not have these issues with trinitycore so maybe they have some code in the core that mitigates the client problems ? either way i'm running things with enUS version of game data for the time being and see if things improve

**Comment by zaicopx** [comment]
Unfortunately I use the enUS client and for azerothcore I get this glitch, while for trinitycore npcbots it runs smoothly.

**Comment by Mr-Deadbeat** [comment]
strange my issues seem to have been solved still no vanishing bots also quest markers / exclamation marks show up as well are you using same data for both server and for the game client ? mods ? i run my server with a limited set of mods
just to avoid issues springing up but some you just can't live without ;)

**Comment by Mr-Deadbeat** [comment]
i have been playing all day now and i have yet to see the glitch appearing so i'm going to mark this down as solved and close the issue
