### ISSUE TITLE
[Azerothcore] nasty npcbots bug on horde side Warlock

### ISSUE THREAD

**Issue by Mr-Deadbeat** [trickerer/Trinity-Bots#239]
OS: Ubuntu 20.04.5
Commit: 018fe830719dfff0983d4581e7728877b3b6618c

Bot: Talionia
id: 70375
guidlow: 115
spec: 26(demonology), faction: 35

when she casts spells her Health zaps down to 1 instantly i was doing the horde quest
Vanquish the betrayers and everytime she cast spells (i presume) she does the above happens
Mobs are Kul tiras sailors

think i found the issue Warlock bot is casting life tap instantly killing herself i checked the combat log when it happened

update:
same thing with Alliance side Warlocks same thing happening there

**Comment by trickerer** [comment]
Heh

**Comment by trickerer** [comment]
There are two problems here: one which affects both TC and AC, but it solves itself at level 15; second one is way more severe and only affects AC.
[Previous attempt at fixing Life Tap health drain](https://github.com/azerothcore/azerothcore-wotlk/pull/4408) sets wrong spell requirements for Life Tap ranks, so warlock bot skips all ranks and goes all the way to rank 8 at level 6, that's why it drains all life.

Here is a tempfix:
```
UPDATE `spell_dbc` SET `MaxLevel`='16',`BaseLevel`='6',`SpellLevel`='6' WHERE (`ID`='1454');
UPDATE `spell_dbc` SET `MaxLevel`='26',`BaseLevel`='16',`SpellLevel`='16' WHERE (`ID`='1455');
UPDATE `spell_dbc` SET `MaxLevel`='36',`BaseLevel`='26',`SpellLevel`='26' WHERE (`ID`='1456');
UPDATE `spell_dbc` SET `MaxLevel`='46',`BaseLevel`='36',`SpellLevel`='36' WHERE (`ID`='11687');
UPDATE `spell_dbc` SET `MaxLevel`='56',`BaseLevel`='46',`SpellLevel`='46' WHERE (`ID`='11688');
UPDATE `spell_dbc` SET `MaxLevel`='68',`BaseLevel`='56',`SpellLevel`='56' WHERE (`ID`='11689');
UPDATE `spell_dbc` SET `MaxLevel`='78',`BaseLevel`='68',`SpellLevel`='68' WHERE (`ID`='27222');
UPDATE `spell_dbc` SET `MaxLevel`='90',`BaseLevel`='80',`SpellLevel`='80' WHERE (`ID`='57946');
```

**Comment by Mr-Deadbeat** [comment]
> There are two problems here: one which affects both TC and AC, but it solves itself at level 15; second one is way more severe and only affects AC. [Previous attempt at fixing Life Tap health drain](https://github.com/azerothcore/azerothcore-wotlk/pull/4408) sets wrong spell requirements for Life Tap ranks, so warlock bot skips all ranks and goes all the way to rank 8 at level 6, that's why it drains all life.
> 
> Here is a tempfix:
> 
> ```
> UPDATE `spell_dbc` SET `MaxLevel`='16',`BaseLevel`='6',`SpellLevel`='6' WHERE (`ID`='1454');
> UPDATE `spell_dbc` SET `MaxLevel`='26',`BaseLevel`='16',`SpellLevel`='16' WHERE (`ID`='1455');
> UPDATE `spell_dbc` SET `MaxLevel`='36',`BaseLevel`='26',`SpellLevel`='26' WHERE (`ID`='1456');
> UPDATE `spell_dbc` SET `MaxLevel`='46',`BaseLevel`='36',`SpellLevel`='36' WHERE (`ID`='11687');
> UPDATE `spell_dbc` SET `MaxLevel`='56',`BaseLevel`='46',`SpellLevel`='46' WHERE (`ID`='11688');
> UPDATE `spell_dbc` SET `MaxLevel`='68',`BaseLevel`='56',`SpellLevel`='56' WHERE (`ID`='11689');
> UPDATE `spell_dbc` SET `MaxLevel`='78',`BaseLevel`='68',`SpellLevel`='68' WHERE (`ID`='27222');
> UPDATE `spell_dbc` SET `MaxLevel`='90',`BaseLevel`='80',`SpellLevel`='80' WHERE (`ID`='57946');
> ```

ok now i know why lol thanks for the explanation i will add that temp fix to the database but it will eventually be overwritten right ? with new database updates so going to create a script i can run if they ever get overwritten with old data
