### ISSUE TITLE
Build error with TC 3.3.5 Sept 6 update

### ISSUE THREAD

**Issue by SlntHntr** [trickerer/Trinity-Bots#24]
Started a new TC build with the latest release from both Sept 6 and 7 with no problems.  CMake runs smooth, finds everything.  VS compiles and builds smooth w/o errors.  Took the fresh setup and wanted to add NPCBots.

LNK1104	cannot open file 'libboost_thread-vc142-mt-x64-1_73.lib'

When I patch in the lastest NPCBots.patch it goes smooth.  CMake finds everything.  But I keep getting the above build error.  Have tried 1.70, 1.71, 1.72, 1.73, and 1.74 boost builds.  Have the environment variable set both System and User.  Have reinstalled CMake, VS 2019, Boost, and about every other option I can think of.  It could be my end and I'm missing something totally obvious but I've not had any problems like this in the past 2-3 years I've been setting up TC servers.

I saw your patch had 2 includes from boost/thread so thought it could be related, my apologies if not and it's just me.  Either way, looking for help or guidance if you've hit a similar issue with NPCBots at any point in time.  I feel I have a good grasp on TC and how to do everything but I've spent the past 2 days being stumped by this one.  I have exhausted the possibilities I can think of and have tried every google result out there.  Renaming boost folders, reinstalling, adding library directories, etc...

Appreciate any feedback, thanks!!  Also...I will continue to beat my head against the wall in order to get NPCBots working :)  The single most fun I've had on WoW private servers without question - your work is wonderful :)

**Comment by trickerer** [comment]
Sorry that you got through all this trouble before posting an issue, but you could actually remove these includes since I just forgot to do it (I build on Debian 10, boost 1.70)

Long story short, I got boost linking error which is strange. I guess TC does not use boost threads anymore, so I used std ones instead, too.

Remove those two boost includes and everything should be fine.

**Comment by trickerer** [comment]
[51acb43379](https://github.com/trickerer/Trinity-Bots/commit/51acb433793e34a7b80350d1ff1fdb2b7e6f63fa)

**Comment by SlntHntr** [comment]
No sorry needed on your end, totally appreciate your insight.  I TOTALLY zoned out on doing that, doh.  I was trying to fix the issue elsewhere and forgot to even try commenting those 2 lines ;)  THANK YOU!!  Rebuilding now, will assume it's working as everything else has gone smooth.
