### ISSUE TITLE
Боты убивают игрока под контролем

### ISSUE THREAD

**Issue by xBarselonx** [trickerer/Trinity-Bots#240]
trickerer, приветствую. У меня ранее был уже вопрос касаемо убийства ботами игрока. Сегодня это повторилось еще раз (2 вайпа на боссе Леди Смертный Шепот). Судя по аддону Skada это в основном было от АОЕ ботов. Скрины ниже. Брали меня боты в таргет или нет, сказать не могу. Возможно ли с этим, что-то сделать?

![WoWScrnShot_110922_230931](https://user-images.githubusercontent.com/99982508/200914295-8718201d-3f5c-4450-86d2-7d051237a5cc.jpg)
![WoWScrnShot_110922_231028](https://user-images.githubusercontent.com/99982508/200914367-2a5c94d6-3bac-4411-b456-60a24ae6a7e1.jpg)

**Comment by trickerer** [comment]
Только что проверить, проходят ли законтрооленные союзники в качестве валидных целей для AOE в алгоритме поиска таковых.

**Comment by xBarselonx** [comment]
> Только что проверить, проходят ли законтрооленные союзники в качестве валидных целей для AOE в алгоритме поиска таковых.

trickerer, не совсем понял твой ответ.

**Comment by trickerer** [comment]
Это я про код. Тебе ничего делать не нужно.

**Comment by trickerer** [comment]
Весь урон в статистике от АоЕ так или иначе. В коде все селекторы имеют проверку целей на валидность, опосредованных целей тоже.

Определение возможности задеть союзника в принципе есть (правда не везде), но данное обстоятельство не является определяющим в вопросе использовать способность или нет.
Также законтроленный союзник может попасть под урон по площади уже после каста, тут определить что урон нанесён союзнику можно, а вот предупредить его нанесение уже нельзя. То есть если 3 вара используют вихрь, и тут игрок оказывается под контролем, в любом случае хотя бы один удар от каждого вара пройдёт; то есть этот опосредованный урон всё равно может убить игрока.

**Comment by Mitradis** [comment]
друида бери, пусть или ресает или в контроль берет чтобы урон не проходил. Тут больше вопрос к самому серверу могут быть т.к. из описания:
Подчиняет выбранного противника на 12 сек. У подчиненного противника повышается урон на 200%, а эффективность исцеления – на 500%.
Работает ли это не знаю.

**Comment by trickerer** [comment]
Пока нет возможности исправить подобное. Появится ли в будущем - не знаю
