### ISSUE TITLE
[Azerothcore] Bots still dissapearing

### ISSUE THREAD

**Issue by Mr-Deadbeat** [trickerer/Trinity-Bots#244]
OS: Ubuntu 20.04.5
Commit: 81b8cada787c1ae7d9860fda9a07b147da1ac354

Druid bot horde side Vanishing / Reappearing

this time it's Druid Bot Harene

have not seen this for some time and now all of a sudden they started doing it again ???

happened in Kalimdor at the border between Mulgor / The Barrens (Camp Taurajo)

also noticed Shaman bot Siln buffs herself with Power Word: Fortitude ??

**Comment by Parkan1986** [comment]
I think such problem occur regardless of places.it just happens randomly.during my leveling try with 2 npcbots in team i got one dissappearing during moving in darnassus.relog and server restart fixed problem

**Comment by Mr-Deadbeat** [comment]
yeah it seems to be a bit random but the strangest thing is it never happened on trinitycore so trying to figure out what is going on

@trickerer on trinitycore you used rbac functions might there be something tied to that with this core azerothcore does not use it at all also when testing now Warlock is Phasing in and out of existance when i use .gm on / .gm off so just wondering if there might be some code affecting their status somehow ? it's getting a bit annoying when bots dissapear in the middle of a fight ;)

also been changing number of vcpu's and ram sizes to see if i can narrow it down to whats causing it one thing i have not tried yet is adding more worker threads if the database connections might be lagging behind on transfers

i have noticed it takes a lot longer for the issue to appear when running the server on only 2 cores "vcpus"

**Comment by trickerer** [comment]
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/0d72c31c1c3638ff8e5cd1602ed5d45313414f2c

**Comment by Mr-Deadbeat** [comment]
> [trickerer/AzerothCore-wotlk-with-NPCBots@0d72c31](https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/0d72c31c1c3638ff8e5cd1602ed5d45313414f2c)
> 
> AC has delayed visibility updates for moving players, that's good to know. The bug is caused by an error in handling creature grid switches for bots: they stay in previous grid despite crossing grid bounds (best example is static transports). This could affect other creatures too, but summoned minions just despawn if they move even medium distance away. So, I can't say for sure if this is bots only bug, but for bots bug is automatically fixed (temporarily) if bot teleports anywhere, with `.npcb reca t` for example.
> 
> The commit above overrides visibility for bots during said visibility updates since bots can't move a grid away from owner without triggering automatic teleport.

ah ok that explains the behaviour the bots have been having i have pulled the last strands of hair on my head trying to figure figure this one out lol i was dead set on a config error in world config or even hardware configuration errors glad to hear it was none of them being the problem ;) building new binaries currently going to test it out shortly

**Comment by Mr-Deadbeat** [comment]
another update the bots do appear but it takes minutes they seem to get yanked across the void instead of being teleported like they normally do when using for example Taxi nodes so they do show up eventually a quick fix is hide them and unhide them and they show up instantly back to testing the instance

**Comment by Mr-Deadbeat** [comment]
> Visibility bug after teleport fix: [trickerer/AzerothCore-wotlk-with-NPCBots@48070ac](https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/48070ac05d727e76e86ad36e3c2b0a68115bc683)

ok i'll test it bots dissapearing fix seems to be working could not trigger them vanishing did 2 instances full runs and they were present the whole time great work :)

**Comment by Mr-Deadbeat** [comment]
after just testing teleporting it's fixed so all the issues seems to be rectified :) great work
i'll close the issue
