### ISSUE TITLE
[Azerothcore] console error

### ISSUE THREAD

**Issue by jasanhell1** [trickerer/Trinity-Bots#245]
Hello, 

Can you take a look at the error in console.

NPCBOT 70170 should be the Rogue NPCBot.

![Rogue](https://user-images.githubusercontent.com/35847663/201500498-b0d62304-6877-4ba4-9060-ffbdf65470a9.jpg)

**Comment by trickerer** [comment]
Can't confirm of freshly spawned bot 70170 after server restart. Also I can't find this spell anywhere in DB or code.

The issue might come from bot's equipment. Try to spawn additional rogue bot and see if second one causes the same issue.
If not, list bot's gear and post the output so I could try to reproduce.

**Comment by jasanhell1** [comment]
Bot 70170
level: 64
roles: DPS only, 
looting: poor, common, uncommon, rare,
gathering: none,
talent: combat,
others: default.

You are right, the issue comes from bot's equipment. No equipment no error in console. 

Here is the equipment. 

![1](https://user-images.githubusercontent.com/35847663/201507920-cbb7cb22-337c-49dd-8f38-2f2d0fcdd5f7.jpg)

**Comment by trickerer** [comment]
Hm. I still don't get the error. Does he have any enchanted pieces?

**Comment by jasanhell1** [comment]
Oh wow, you are genius and legend. Thank you for the advice.

I use AC mod-random-enchants. I think it causes the issue. Probably mod-random-enchants needs to be updated.

I am closing the topic.
