### ISSUE TITLE
[AzerothCore]Боты начинают искать долгие обходные пути когда игрок нападает на мобов в воде

### ISSUE THREAD

**Issue by Parkan1986** [trickerer/Trinity-Bots#246]
Происходит это случайным образом.Бывает такое, если в воде есть противник и игрок нападает на моба,то боты вместо того чтобы зайти за игроком в воду начинают искать обходные пути, убегают далеко и не всегда сразу возвращаются назад.Спасет только команда телепорта ботов к игроку.Так же может быть такое, что игрок когда вышел из воды,а боты еще в воде то они опять начинают убегать от игрока находясь в воде убегают в случайную сторону и долго не возвращаются.Тут опять спасает команда телепорта ботов к игроку.

Такого не происходило на trinitycore.Я такое впервые вижу на AzerothCore.Думал недавний фикс исправит эту проблему,но похоже эта проблема выходит из другой стороны.

Дополню еще один момент.Бывает такое, что боты не кастеры стоят на берегу и не могут зайти в воду чтобы атаковать моба когда игрок зашел в воду и бьет моба в воде.Кастеры бывают подбегают к мобу близко и начинают кастовать.

Список модулей которые использую.
![image](https://user-images.githubusercontent.com/30984138/201976363-d447d3b7-0460-48dc-8264-81ba642fc4d5.png)

**Comment by trickerer** [comment]
Это ошибка mmaps. Происходит со всеми мобами.

https://github.com/azerothcore/azerothcore-wotlk/issues/13551
https://github.com/azerothcore/azerothcore-wotlk/pull/13705

**Comment by Parkan1986** [comment]
Понятно.значит ждать фикса или переделывать mmaps?хотя что то в компилированных файлах я невидел экстрактора для этих дел.в тринитикор такое создается

**Comment by trickerer** [comment]
Нечего переделывать, там же написано что это древний баг.
Экстракторы нужно включить в CMake, как и в тринити.

Кстати, в тринити недавно откатили подобный коммит.
