### ISSUE TITLE
[Azerothcore] The Shattered Halls in Outlands issue

### ISSUE THREAD

**Issue by Mr-Deadbeat** [trickerer/Trinity-Bots#249]
OS: Ubuntu 20.04.5
Commit: 6ed664cb2949931e45549fbe853f7bbf8df1ba58

when you get to Grand Warlock Nethekurse locked gate you need to jump down into the pit to go around to get to the boss room
problem is bots run around and trough the locked gate instead of jumping down with the player so player is all alone with level 70 mobs getting hammered ;)

meanwhile the bots running around bring ALL mobs from boss to everything else down there as well
might there be a way of fixing issues like this so the bots do follow players on jumps instead of taking the long way around ?

on azerothcore the instance is fixed so simply hiding the bots and jumping down wont work like it did on trinitycore

**Comment by trickerer** [comment]
Tested with pet and it does the same, running right through the locked door.
So this is pathing issue and I don't think I will be able to do anything about this issue from bots' side

As for temporary solution... What can I say, time your `.npcb reca t` command right and hope for the best, I guess
