### ISSUE TITLE
[Azerothcore] Gossip menu without spells

### ISSUE THREAD

**Issue by OpexNSK** [trickerer/Trinity-Bots#250]
На тринити сборке проблем не возникало, а в азероткор появилась проблема в ruRU клиенте ("с" и "без" локализации меню ботов). Нет отображения способностей в меню ботов. 
Does anyone have same problem? 
![npcbotmenu](https://user-images.githubusercontent.com/98803279/202887170-acd1387b-d73c-46f0-a9b3-688922bd443c.JPG)

**Comment by trickerer** [comment]
Поставил русскую локализацию. Такой проблемы не обнаружил.

![ruRU](https://user-images.githubusercontent.com/1254989/204119611-7d074780-1955-441f-bb1c-67922a3f97ae.jpg)

Для того чтобы сервер использовал локализацию, нужно:
1. Извлечь ruRU файлы .dbc из клиента (mapextractor-ом, например) и положить папку 'ruRU' в папку 'dbc' в корне сервера
2. Поставить в конфиге русскую локализацию по умолчанию. `DBC.Locale = 8`
3. Собственно, залить русскую локаль ботов в базу world

**Comment by OpexNSK** [comment]
Спасибо за совет, вероятно, что конфликт был с каким-то модулем. Я сделал чистую сборку с новыми базами и всё появилось. Хотелось бы еще уточнить: начальные квесты встречаются без локализации, меню перед квестом и меню сдачи квеста тоже без локализации. Есть ли где то дополнительная локализация баз сервера?

**Comment by trickerer** [comment]
Не имею понятия, извини. Отсутствие локализации квестов это проблемы баз данных. Сам я никакими локализациями не пользуюсь уже лет 10 и даже больше.

**Comment by xBarselonx** [comment]
> 2\. DBC.Locale

Это что для русской локализации теперь карты нужно вытягивать экстрактором из ру клиента или достаточно в настройке DBC.Locale 255 заменить на 8? У них же в мануале (https://www.azerothcore.org/wiki/server-setup) есть ссылка на все карты (https://github.com/wowgaming/client-data/releases), они что разве не походят? АС без ботов с вышеуказанными картами все способности на русском и квесты тоже.

**Comment by trickerer** [comment]
Про карты в моём сообщении ни слова.
> Извлечь ruRU файлы .dbc из клиента

И только.
