### ISSUE TITLE
Feature Request - Bots Count Towards Battleground Queue

### ISSUE THREAD

**Issue by Codewow** [trickerer/Trinity-Bots#251]
Having bots count towards LFG queues is extremely helpful. It would also be great if bots would count towards LFBG as well so the few friends I have can queue up for BGs for the fun of it without still requiring 10 real players on each side or the 20 player requirement for Alterac.

Just tested this out on my server and having 10 bots + 1 player on each side wasn't popping the queue.

**Comment by trickerer** [comment]
https://github.com/trickerer/Trinity-Bots/commit/486aa05bb1079de9a610f9935583b662bedb3e3c

It's not a complete implementation of bot in BGs, so you won't see them in BG players list, but they count towards BG queue players count and BG participants count, preventing BG from ending prematurely from lack of players.

Tested with WG 5p premades on both TC and AC.

**Comment by Codewow** [comment]
I'm running TrinityCore rev 6bf71b07f09e 2022-11-17 npcbots_3.3.5 branch) and queueing with bots in my group on both sides and nothing seems to happen. I have the settings enabled for them to join bgs and arenas. :/
