### ISSUE TITLE
AzerothCore - Unknown Spell

### ISSUE THREAD

**Issue by zaicopx** [trickerer/Trinity-Bots#253]
What is unknown spell 7541 on priest npcbot. I use Azerothcore.
I have tried to delete and create a new priest npcbot and the error still appears on the worldserver console.

![NPCBots error](https://user-images.githubusercontent.com/68382531/203296146-514eb1ba-3f11-43e1-9020-5cfd89ba233b.JPG)

**Comment by trickerer** [comment]
Probably a random enchants bug
https://github.com/trickerer/Trinity-Bots/issues/245

**Comment by zaicopx** [comment]
Oh ok thank for your answer 👍
