### ISSUE TITLE
Question about controlling the bots

### ISSUE THREAD

**Issue by blazersrng** [trickerer/Trinity-Bots#254]
Hey, is there a command to tell bots to stop engaging and move to my location? Maybe I'm dumb and missing it in the documentation. When a raid boss is casting "big aoe attack" I want the bots to stop attacking and move to my location, but 'follow' command doesn't achieve this, they shuffle around and continue attacking the boss. I know of "npcb recall t" command, but it is not ideal, because it teleports them off the grid and back in, resetting the aggro. Is there a better way to do this?

**Comment by trickerer** [comment]
Yep, there is no obvious way to do that.

Normally it is done by using follow distance setting.
You set `.npcbot dist follow` to something relatively small like 20 (or even 0 if you're melee) and stay at the border of that range (18 or so), or, unless you play as a Hunter, just force bots to attack using your melee attack (state, not damage). This distance is exact and does not include model size. When boss is about to cast AoE spell, cancel your attack and move away: bots will break from their target as they are too far away from you now to attack anything. Once the cast is done, engage again.
Be careful with target icons though, as bots will ignore follow distance if they find suitable target by icon and will essentially fixate on that target until it's dead.

**Comment by blazersrng** [comment]
Thank you for the response, I just tried this method and it works fine.
