### ISSUE TITLE
NPCBots: bot text string #70658 is not localized, at least for enUS 

### ISSUE THREAD

**Issue by Riveir** [trickerer/Trinity-Bots#255]
This is on Azerothcore. 
Getting this in my world config menu. In addition my Transmog menu is busted. Any idea what might be going on?
![Screenshot (142)](https://user-images.githubusercontent.com/96812524/203892499-a886a60c-be35-4e46-8de0-19bb388992c3.png)
![Screenshot (146)](https://user-images.githubusercontent.com/96812524/203894422-ef66cc9e-effb-4e2e-87cd-d5e049d32510.png)

**Comment by Riveir** [comment]
Second Sceen different bot.  
![Screenshot (144)](https://user-images.githubusercontent.com/96812524/203893176-f343f0a6-c7a9-448d-b648-37bb4ab0f689.png)

**Comment by trickerer** [comment]
You forgot to apply https://github.com/trickerer/Trinity-Bots/commit/8049150e7fbf0d9edcea71ccf5b05fb656c0e092 SQL updates (1 world DB, 1 characters DB)

**Comment by Riveir** [comment]
> You forgot to apply [8049150](https://github.com/trickerer/Trinity-Bots/commit/8049150e7fbf0d9edcea71ccf5b05fb656c0e092) SQL updates (1 world DB, 1 characters DB)

Sorry to bother by posting this just before I came back and found your response, I re-applied 2022_11_15_00_npc_text and that resolved the issue. I was certain I had originally applied it. Who knows. Thanks.
