### ISSUE TITLE
Paladins don't die

### ISSUE THREAD

**Issue by zbhcn** [trickerer/Trinity-Bots#256]
Paladins don't die when the npcbot is a Paladin.This is a bug.

**Comment by zbhcn** [comment]
and Is there any way to display npcbots in the team framework?

**Comment by trickerer** [comment]
1. Can't confirm, normally dies from damage
![paladin_kill](https://user-images.githubusercontent.com/1254989/204070659-4ca2b859-79e5-42a8-84f0-aeedd588babd.jpg)

2. https://github.com/trickerer/Trinity-Bots#raid-group-frames

**Comment by zbhcn** [comment]
Spell ID 31850 can trigger infinitely, causing the paladin not to die
![image](https://user-images.githubusercontent.com/116956612/204070870-770d8891-953d-48f7-b517-4019591a7b83.png)

**Comment by trickerer** [comment]
TrinityCore or AzerothCore?

**Comment by zbhcn** [comment]
AzerothCore
