### ISSUE TITLE
the npcbots can't play mounted battle in Dungeon - Champion Trial 

### ISSUE THREAD

**Issue by zbhcn** [trickerer/Trinity-Bots#258]
They are not equipped with spears ，how can they do it with mounted battle in Dungeon - Champion Trial ..

it's Azerothcore

**Comment by trickerer** [comment]
Trial of the Champion dungeon is not supported - and will not be any time soon, I fear. That is because I am not returning to working on vehicles if I can't implement a feature on both TC and AC. That being said, on TC TOC5 dungeon is closed (not implemented).

**Comment by zbhcn** [comment]
thank you , What a pity

**Comment by trickerer** [comment]
I completely forgot that ToC5 mounts were fully implemented already. I tested them now on AC and they indeed required a couple fixes.

One bot died during phase 1, so enemies do not try to just focus you, but still feels like they may prioritize your mount over bots'.

Didn't check vehicle stats gain though.
