### ISSUE TITLE
NPCBot and Solo LFG

### ISSUE THREAD

**Issue by zaicopx** [trickerer/Trinity-Bots#26]
Hi, I compile my server using latest npcbot and i add solo lfg and autobalance patch. I got crash when i enter dungeon using Dungeon finder with my npcbot. If I enter dungeon using dungeon finder by myself there is no crash at all. Do you how to fix it??

This Solo Lfg patch.
[SoloLFG Patch](https://drive.google.com/file/d/1Nm9Zjfm38tjVcjaILfyHS8UDCo4vudDQ/view?usp=sharing)

And This Error txt
[Crash WorldServer.exe](https://drive.google.com/file/d/1IROa3F1iCe8X0S5fzOJmDuSXCiLSDdIg/view?usp=sharing)

**Comment by YunataSavior** [comment]
Since you are applying two patches on top of TrinityCore (Trinity-Bots and "SoloLFG Patch"), instead of just one, I'm afraid we cannot help you much unless you know how to compile and run your worldserver in the debugger.

**Comment by trickerer** [comment]
> Do you how to fix it??
> 
I don't how to fix it. I'm not even sure if it's SoloLFG mod that makes server crash with bots - could as well be Autobalance mod.
I may be able to help you if you provide a Debug crash log, but cannot promise.

**Comment by qyh214** [comment]
with https://github.com/TrinityCore/TrinityCoreCustomChanges/tree/3.3.5-lfgsolo
when use LFG and with bots,after loadingscreen finish ,server crash.

**Comment by zaicopx** [comment]
Maybe npcbot not compatible with lfg 🤔
