### ISSUE TITLE
 [AC] [Bug] [Group] Dungeon NAXX‘s boss—Sapphiron，Stuck, don't move, don't attack

### ISSUE THREAD

**Issue by zbhcn** [trickerer/Trinity-Bots#260]
**Description:**

I don't know if it's because of npcbots. In short, the BOSS is stuck and can't move, and the players can't attack it

**AzerothCore:**

**Current behaviour:**

25 pop raid of NAXX，Sapphiron ,it Can't move or attack，I don't know whether it's the Azerothcore or the npcbots

**Comment by trickerer** [comment]
Could be related to hover mechanic. I noticed that if you cast Levitate on bots they cannot move at all, didn't try on other creatures.

**Comment by trickerer** [comment]
Tested on clean https://github.com/azerothcore/azerothcore-wotlk/commit/55957fbb6e24f2fb6df57c92b829ad42498afee0 and the problem still persists

Not a NPCbots issue
