### ISSUE TITLE
[AC] [Bug] Here are some error logs. Please check if they are bugs

### ISSUE THREAD

**Issue by zbhcn** [trickerer/Trinity-Bots#262]
**Description:**

Here are some error logs. Please check if they are bugs.it‘s from 2022/11/28 Updated version

**AzerothCore:**
Starting up Auction House Listing thread...
Race (29) not found in DBC while creating new char for account (ID: 37): wrong DBC files or cheater?
Race (29) not found in DBC while creating new char for account (ID: 37): wrong DBC files or cheater?
Race (29) not found in DBC while creating new char for account (ID: 37): wrong DBC files or cheater?
Race (29) not found in DBC while creating new char for account (ID: 37): wrong DBC files or cheater?
Race (30) not found in DBC while creating new char for account (ID: 37): wrong DBC files or cheater?
Race (28) not found in DBC while creating new char for account (ID: 37): wrong DBC files or cheater?
Race (29) not found in DBC while creating new char for account (ID: 37): wrong DBC files or cheater?
Race (29) not found in DBC while creating new char for account (ID: 37): wrong DBC files or cheater?
Race (29) not found in DBC while creating new char for account (ID: 37): wrong DBC files or cheater?
ERROR: EscortAI (script: npc_azure_invader, creature entry: 30961) attempts to Start while in combat
ERROR: EscortAI (script: npc_azure_invader, creature entry: 30961) attempts to Start while in combat
ERROR: EscortAI (script: npc_azure_invader, creature entry: 30661) attempts to Start while in combat
ERROR: EscortAI (script: npc_azure_stalker, creature entry: 32191) attempts to Start while in combat
ERROR: EscortAI (script: npc_azure_captain, creature entry: 30666) attempts to Start while in combat
ERROR: EscortAI (script: npc_azure_mage_slayer, creature entry: 30664) attempts to Start while in combat
ERROR: EscortAI (script: npc_azure_binder, creature entry: 30918) attempts to Start while in combat
ERROR: EscortAI (script: npc_azure_spellbreaker, creature entry: 30662) attempts to Start while in combat
ERROR: EscortAI (script: npc_azure_invader, creature entry: 30961) attempts to Start while in combat
ERROR: EscortAI (script: npc_azure_mage_slayer, creature entry: 30963) attempts to Start while in combat
ERROR: EscortAI (script: npc_azure_spellbreaker, creature entry: 30962) attempts to Start while in combat
ERROR: EscortAI (script: npc_azure_binder, creature entry: 30663) attempts to Start while in combat
ERROR: EscortAI (script: npc_azure_binder, creature entry: 30663) attempts to Start while in combat
ERROR: EscortAI (script: npc_azure_spellbreaker, creature entry: 30962) attempts to Start while in combat
ERROR: EscortAI (script: npc_azure_spellbreaker, creature entry: 30962) attempts to Start while in combat
ERROR: EscortAI (script: npc_azure_binder, creature entry: 30918) attempts to Start while in combat
ERROR: EscortAI (script: npc_azure_raider, creature entry: 30668) attempts to Start while in combat
ERROR: EscortAI (script: npc_azure_raider, creature entry: 30668) attempts to Start while in combat
ERROR: EscortAI (script: npc_azure_captain, creature entry: 30666) attempts to Start while in combat
ERROR: EscortAI (script: npc_azure_stalker, creature entry: 32191) attempts to Start while in combat
ERROR: EscortAI (script: npc_azure_captain, creature entry: 30666) attempts to Start while in combat
ERROR: EscortAI (script: npc_azure_stalker, creature entry: 32191) attempts to Start while in combat
ERROR: EscortAI (script: npc_azure_binder, creature entry: 30918) attempts to Start while in combat
ERROR: EscortAI (script: npc_azure_invader, creature entry: 30961) attempts to Start while in combat
ERROR: EscortAI (script: npc_azure_spellbreaker, creature entry: 30962) attempts to Start while in combat
ERROR: EscortAI (script: npc_azure_spellbreaker, creature entry: 30962) attempts to Start while in combat

**Comment by trickerer** [comment]
No. Both of these errors are unrelated

First one is malformed C->S packet (character creation) and second one happens all the time in Violet Hold, you can try to do the dungeon without bots and see for yourself

**Comment by zbhcn** [comment]
ok,thanks.That's very kind of you
