### ISSUE TITLE
[AC] [Bug/Crash/Enhance] [botcommands] Command .npcbot recall teleport crash when in the battle.

### ISSUE THREAD

**Issue by jasanhell1** [trickerer/Trinity-Bots#264]
**Description:**

Using .npcbot recall teleport causes console crash when in the battle. 
I understand it is not decided to use .npcbot recall teleport when npcbots are in the battle. Please allow the command to teleport the npcbots when in the battle for both TC and AC.

**TrinityCore or AzerothCore:**
Please do it at both core.

**Current behaviour:**
AC can use the command when the npcbots are in the battle, but the console sometimes will crash. 

>> ASSERTION FAILED

# Location 'C:\azerothcore-wotlk\src\server\game\Entities\Object\Object.h:517'
# Function 'WorldObject::GetMap'
# Condition 'm_currMap'

# Debug info: 'MapID: 580 X: 1488.52 Y: 559.718 Z: 24.2248 O: 2.49112
GUID Full: 0xf1300113010000d4 Type: Creature Entry: 70401  Low: 212 Entry 70401
Name: Turak
AliveState: false UnitMovementFlags: 0 ExtraUnitMovementFlags: 0 Class: 11
AIName:  ScriptName: druid_bot WaypointPath: 0 SpawnId: 3110431'
 
#----------------------------------------------------------------------#

Fault address:  00007FF7E9CD8BD1 01:0000000000057BD1 

Registers:
RAX:00007FF7E9CD6345
RBX:000002A0A7CC7790
RCX:0000000000400000
RDX:0000080000000080
RSI:000000000000E5E6
RDI:00007FF7EB24FF10
R8: 00007FF700000000
R9: 0000000600000000
R10:000016A9B08E877F
R11:000002A0F2D46480
R12:000002A0F2D46480
R13:000002A0A7CC7790
R14:0000000000000000
R15:0000000000000001
CS:RIP:0033:00007FFC9FC4428C
SS:RSP:002B:0000000091EFC7E0  RBP:91EFC959
DS:002B  ES:002B  FS:0053  GS:002B
Flags:00000202

**Expected behaviour:**

1) Reason for doing that. 
Sometimes, we need to defeat the bosses at the same time. (Sathrovarr and Kalecgos) 
we need the npcbots come to the player. 

2) Please also allow the command with selected npcbot or random select npcbot.
example:
.npcbot recall teleport 4 - (random select 4 npcbots teleport to the player)
or 
.npcbot recall teleport - (selected npcbot)
or
better option

**TC / AC rev. hash/commit:** 

AzerothCore rev. fb08f8e905b9+

**Operating system:**
Windows 11

**Comment by trickerer** [comment]
Release crashlog is useless, I need at least a call stack to try to figure out what is happening exactly

**Comment by jasanhell1** [comment]
Hi. Here is the call stack.

Call stack:
Address   Frame     Function      SourceFile
00007FFC9FC4428C  000000DB91EFC8B0  RaiseException+6C
00007FF7EAA75BDD  000000DB91EFC9A0  0001:0000000000DF4BDD 
00007FF7E9CD8BD1  000000DB91EFCAB0  0001:0000000000057BD1 
00007FF7EA552FDB  000000DB91EFCC70  0001:00000000008D1FDB 
00007FF7EA552804  000000DB91EFCDA0  0001:00000000008D1804 
00007FF7EA4A0388  000000DB91EFCE50  0001:000000000081F388 
00007FF7EA2BA9E7  000000DB91EFD020  0001:00000000006399E7 
00007FF7EA2BB432  000000DB91EFD190  0001:000000000063A432 
00007FF7EA2BAFC9  000000DB91EFD2D0  0001:0000000000639FC9 
00007FF7EA43A350  000000DB91EFD330  0001:00000000007B9350 
00007FF7EA439A4B  000000DB91EFD360  0001:00000000007B8A4B 
00007FF7EA9405FE  000000DB91EFD3D0  0001:0000000000CBF5FE 
00007FF7E9DD78BF  000000DB91EFD430  0001:00000000001568BF 
00007FF7EA619CF8  000000DB91EFD630  0001:0000000000998CF8 
00007FF7EA619EE6  000000DB91EFD670  0001:0000000000998EE6 
00007FF7EA265AF1  000000DB91EFD6F0  0001:00000000005E4AF1 
00007FF7EA264DA5  000000DB91EFD830  0001:00000000005E3DA5 
00007FF7EA9BBBFF  000000DB91EFDC10  0001:0000000000D3ABFF 
00007FF7EA31357E  000000DB91EFE740  0001:000000000069257E 
00007FF7EA217ED1  000000DB91EFE800  0001:0000000000596ED1 
00007FF7EA216A01  000000DB91EFEC40  0001:0000000000595A01 
00007FF7E9CB512B  000000DB91EFEC80  0001:000000000003412B 
00007FF7E9CBFB92  000000DB91EFF7E0  0001:000000000003EB92 
00007FF7EAAF062C  000000DB91EFF820  argon2id_verify_ctx+29ECC
00007FFCA1035550  000000DB91EFF850  BaseThreadInitThunk+10
00007FFCA210485B  000000DB91EFF8D0  RtlUserThreadStart+2B

Call stack:
Address   Frame     Function      SourceFile
00007FFCA21A5A54  000000DB91EFA7B0  NtGetContextThread+14
000000000000043C  000000DB91EFA7B8  0000:0000000000000000 
000000000000001D  000000DB91EFA7C0  0000:0000000000000000 
000000DB91EFB840  000000DB91EFA7C8  0000:0000000000000000 
0000000000000001  000000DB91EFA7D0  0000:0000000000000000 
0000000000000434  000000DB91EFA7D8  0000:0000000000000000 

Call stack:
Address   Frame     Function      SourceFile
00007FFCA21A3CA4  000000DB922FFA90  ZwRemoveIoCompletion+14
00007FFC9FC500A3  000000DB922FFAF0  GetQueuedCompletionStatus+53
00007FF7E9CB8A73  000000DB922FFC00  0001:0000000000037A73 
00007FF7E9CBC474  000000DB922FFC80  0001:000000000003B474 
00007FF7E9CA440C  000000DB922FFCC0  0001:000000000002340C 
00007FFC9F766C0C  000000DB922FFCF0  _recalloc+5C
00007FFCA1035550  000000DB922FFD20  BaseThreadInitThunk+10
00007FFCA210485B  000000DB922FFDA0  RtlUserThreadStart+2B

Call stack:
Address   Frame     Function      SourceFile
00007FFCA21A3CA4  000000DB923FFBC0  ZwRemoveIoCompletion+14
00007FFC9FC500A3  000000DB923FFC20  GetQueuedCompletionStatus+53
00007FF7E9CB8A73  000000DB923FFD30  0001:0000000000037A73 
00007FF7E9CBC474  000000DB923FFDB0  0001:000000000003B474 
00007FF7E9CA440C  000000DB923FFDF0  0001:000000000002340C 
00007FFC9F766C0C  000000DB923FFE20  _recalloc+5C
00007FFCA1035550  000000DB923FFE50  BaseThreadInitThunk+10
00007FFCA210485B  000000DB923FFED0  RtlUserThreadStart+2B

Call stack:
Address   Frame     Function      SourceFile
00007FFCA21A76D4  000000DB924FFA60  NtWaitForAlertByThreadId+14
00007FFCA216AAF7  000000DB924FFAE0  RtlSleepConditionVariableSRW+137
00007FFC9FC5BCA9  000000DB924FFB20  SleepConditionVariableSRW+29
00007FFC65CA2959  000000DB924FFB50  ?_Winerror_message@std@@YAKKPEADK@Z+139
00007FFC65CA2BEA  000000DB924FFB80  _Cnd_wait+3A
00007FF7EAA67548  000000DB924FFBB0  0001:0000000000DE6548 
00007FF7E9D3EA1F  000000DB924FFBE0  0001:00000000000BDA1F 
00007FFC9F766C0C  000000DB924FFC10  _recalloc+5C
00007FFCA1035550  000000DB924FFC40  BaseThreadInitThunk+10
00007FFCA210485B  000000DB924FFCC0  RtlUserThreadStart+2B

Call stack:
Address   Frame     Function      SourceFile
00007FFCA21A76D4  000000DB925FFD40  NtWaitForAlertByThreadId+14
00007FFCA216AAF7  000000DB925FFDC0  RtlSleepConditionVariableSRW+137
00007FFC9FC5BCA9  000000DB925FFE00  SleepConditionVariableSRW+29
00007FFC65CA2959  000000DB925FFE30  ?_Winerror_message@std@@YAKKPEADK@Z+139
00007FFC65CA2BEA  000000DB925FFE60  _Cnd_wait+3A
00007FF7EAA67548  000000DB925FFE90  0001:0000000000DE6548 
00007FF7E9D3EA1F  000000DB925FFEC0  0001:00000000000BDA1F 
00007FFC9F766C0C  000000DB925FFEF0  _recalloc+5C
00007FFCA1035550  000000DB925FFF20  BaseThreadInitThunk+10
00007FFCA210485B  000000DB925FFFA0  RtlUserThreadStart+2B

Call stack:
Address   Frame     Function      SourceFile
00007FFCA21A76D4  000000DB926FFA40  NtWaitForAlertByThreadId+14
00007FFCA216AAF7  000000DB926FFAC0  RtlSleepConditionVariableSRW+137
00007FFC9FC5BCA9  000000DB926FFB00  SleepConditionVariableSRW+29
00007FFC65CA2959  000000DB926FFB30  ?_Winerror_message@std@@YAKKPEADK@Z+139
00007FFC65CA2BEA  000000DB926FFB60  _Cnd_wait+3A
00007FF7EAA67548  000000DB926FFB90  0001:0000000000DE6548 
00007FF7E9D3EA1F  000000DB926FFBC0  0001:00000000000BDA1F 
00007FFC9F766C0C  000000DB926FFBF0  _recalloc+5C
00007FFCA1035550  000000DB926FFC20  BaseThreadInitThunk+10
00007FFCA210485B  000000DB926FFCA0  RtlUserThreadStart+2B

Call stack:
Address   Frame     Function      SourceFile
00007FFCA21A3C04  000000DB927FF8B0  ZwWaitForSingleObject+14
00007FFC9FC4254E  000000DB927FF950  WaitForSingleObjectEx+8E
00007FF7E9CBC343  000000DB927FF980  0001:000000000003B343 
00007FF7E9CBD825  000000DB927FF9B0  0001:000000000003C825 
00007FFC9F766C0C  000000DB927FF9E0  _recalloc+5C
00007FFCA1035550  000000DB927FFA10  BaseThreadInitThunk+10
00007FFCA210485B  000000DB927FFA90  RtlUserThreadStart+2B

Call stack:
Address   Frame     Function      SourceFile
00007FFCA21A76D4  000000DB928FF1C0  NtWaitForAlertByThreadId+14
00007FFCA216AAF7  000000DB928FF240  RtlSleepConditionVariableSRW+137
00007FFC9FC5BCA9  000000DB928FF280  SleepConditionVariableSRW+29
00007FFC65CA2959  000000DB928FF2B0  ?_Winerror_message@std@@YAKKPEADK@Z+139
00007FFC65CA2BEA  000000DB928FF2E0  _Cnd_wait+3A
00007FF7E9D49BE2  000000DB928FFA40  0001:00000000000C8BE2 
00007FF7E9D3EA1F  000000DB928FFA70  0001:00000000000BDA1F 
00007FFC9F766C0C  000000DB928FFAA0  _recalloc+5C
00007FFCA1035550  000000DB928FFAD0  BaseThreadInitThunk+10
00007FFCA210485B  000000DB928FFB50  RtlUserThreadStart+2B

Call stack:
Address   Frame     Function      SourceFile
00007FFCA21A76D4  000000DB92BFF680  NtWaitForAlertByThreadId+14
00007FFCA216AAF7  000000DB92BFF700  RtlSleepConditionVariableSRW+137
00007FFC9FC5BCA9  000000DB92BFF740  SleepConditionVariableSRW+29
00007FFC65CA2959  000000DB92BFF770  ?_Winerror_message@std@@YAKKPEADK@Z+139
00007FFC65CA2BEA  000000DB92BFF7A0  _Cnd_wait+3A
00007FF7EA8087E8  000000DB92BFF7D0  0001:0000000000B877E8 
00007FF7E9D3EA1F  000000DB92BFF800  0001:00000000000BDA1F 
00007FFC9F766C0C  000000DB92BFF830  _recalloc+5C
00007FFCA1035550  000000DB92BFF860  BaseThreadInitThunk+10
00007FFCA210485B  000000DB92BFF8E0  RtlUserThreadStart+2B

Call stack:
Address   Frame     Function      SourceFile
00007FFCA21A3C04  000000DB92CFF740  ZwWaitForSingleObject+14
00007FFC9FC4254E  000000DB92CFF7E0  WaitForSingleObjectEx+8E
00007FF7E9CBC343  000000DB92CFF810  0001:000000000003B343 
00007FF7E9CBD825  000000DB92CFF840  0001:000000000003C825 
00007FFC9F766C0C  000000DB92CFF870  _recalloc+5C
00007FFCA1035550  000000DB92CFF8A0  BaseThreadInitThunk+10
00007FFCA210485B  000000DB92CFF920  RtlUserThreadStart+2B

Call stack:
Address   Frame     Function      SourceFile
00007FFCA21A3CA4  000000DB92DFFB90  ZwRemoveIoCompletion+14
00007FFC9FC500A3  000000DB92DFFBF0  GetQueuedCompletionStatus+53
00007FF7E9CB8A73  000000DB92DFFD00  0001:0000000000037A73 
00007FF7E9CBC474  000000DB92DFFD80  0001:000000000003B474 
00007FF7EA244429  000000DB92DFFE80  0001:00000000005C3429 
00007FF7E9D3EA1F  000000DB92DFFEB0  0001:00000000000BDA1F 
00007FFC9F766C0C  000000DB92DFFEE0  _recalloc+5C
00007FFCA1035550  000000DB92DFFF10  BaseThreadInitThunk+10
00007FFCA210485B  000000DB92DFFF90  RtlUserThreadStart+2B

Call stack:
Address   Frame     Function      SourceFile
00007FFCA21A3C44  000000DB92EFF360  NtReadFile+14
00007FFC9FC34FCB  000000DB92EFF3D0  ReadFile+7B
00007FFC9F747859  000000DB92EFF470  _read+209
00007FFC9F7476F2  000000DB92EFF4B0  _read+A2
00007FFC9F747A2A  000000DB92EFF4E0  _fgetc_nolock+AA
00007FFC9F747BFD  000000DB92EFF520  _fgetwc_nolock+FD
00007FFC9F7652D1  000000DB92EFF580  fgetws+81
00007FF7E9CC2735  000000DB92EFF9E0  0001:0000000000041735 
00007FF7E9CA43AB  000000DB92EFFA10  0001:00000000000233AB 
00007FFC9F766C0C  000000DB92EFFA40  _recalloc+5C
00007FFCA1035550  000000DB92EFFA70  BaseThreadInitThunk+10
00007FFCA210485B  000000DB92EFFAF0  RtlUserThreadStart+2B

Call stack:
Address   Frame     Function      SourceFile
00007FFCA21A4204  000000DB92FFFA70  NtDelayExecution+14
00007FFCA215B873  000000DB92FFFAA0  RtlDelayExecution+43
00007FFC9FC4AEA1  000000DB92FFFB20  SleepEx+71
00007FFC65CA2E8C  000000DB92FFFB70  _Thrd_sleep+3C
00007FF7E9CA72D0  000000DB92FFFBD0  0001:00000000000262D0 
00007FF7E9CB027F  000000DB92FFFD90  0001:000000000002F27F 
00007FF7E9CA43AB  000000DB92FFFDC0  0001:00000000000233AB 
00007FFC9F766C0C  000000DB92FFFDF0  _recalloc+5C
00007FFCA1035550  000000DB92FFFE20  BaseThreadInitThunk+10
00007FFCA210485B  000000DB92FFFEA0  RtlUserThreadStart+2B
========================
Local Variables And Parameters

Call stack:
Address   Frame     Function      SourceFile
00007FFC9FC4428C  000000DB91EFC8B0  RaiseException+6C

00007FF7EAA75BDD  000000DB91EFC9A0  0001:0000000000DF4BDD 

00007FF7E9CD8BD1  000000DB91EFCAB0  0001:0000000000057BD1 

00007FF7EA552FDB  000000DB91EFCC70  0001:00000000008D1FDB 

00007FF7EA552804  000000DB91EFCDA0  0001:00000000008D1804 

00007FF7EA4A0388  000000DB91EFCE50  0001:000000000081F388 

00007FF7EA2BA9E7  000000DB91EFD020  0001:00000000006399E7 

00007FF7EA2BB432  000000DB91EFD190  0001:000000000063A432 

00007FF7EA2BAFC9  000000DB91EFD2D0  0001:0000000000639FC9 

00007FF7EA43A350  000000DB91EFD330  0001:00000000007B9350 

00007FF7EA439A4B  000000DB91EFD360  0001:00000000007B8A4B 

00007FF7EA9405FE  000000DB91EFD3D0  0001:0000000000CBF5FE 

00007FF7E9DD78BF  000000DB91EFD430  0001:00000000001568BF 

00007FF7EA619CF8  000000DB91EFD630  0001:0000000000998CF8 

00007FF7EA619EE6  000000DB91EFD670  0001:0000000000998EE6 

00007FF7EA265AF1  000000DB91EFD6F0  0001:00000000005E4AF1 

00007FF7EA264DA5  000000DB91EFD830  0001:00000000005E3DA5 

00007FF7EA9BBBFF  000000DB91EFDC10  0001:0000000000D3ABFF 

00007FF7EA31357E  000000DB91EFE740  0001:000000000069257E 

00007FF7EA217ED1  000000DB91EFE800  0001:0000000000596ED1 

00007FF7EA216A01  000000DB91EFEC40  0001:0000000000595A01 

00007FF7E9CB512B  000000DB91EFEC80  0001:000000000003412B 

00007FF7E9CBFB92  000000DB91EFF7E0  0001:000000000003EB92 

00007FF7EAAF062C  000000DB91EFF820  argon2id_verify_ctx+29ECC

00007FFCA1035550  000000DB91EFF850  BaseThreadInitThunk+10

00007FFCA210485B  000000DB91EFF8D0  RtlUserThreadStart+2B


Call stack:
Address   Frame     Function      SourceFile
00007FFCA21A5A54  000000DB91EFA7B0  NtGetContextThread+14

0000000000000404  000000DB91EFA7B8  0000:0000000000000000 

000000000000001D  000000DB91EFA7C0  0000:0000000000000000 

000000DB91EFB840  000000DB91EFA7C8  0000:0000000000000000 

0000000000000001  000000DB91EFA7D0  0000:0000000000000000 

0000000000000414  000000DB91EFA7D8  0000:0000000000000000 

0000000000000001  000000DB91EFA7E0  0000:0000000000000000 

00007FF7E9CCB28D  000000DB91EFAD10  0001:000000000004A28D 

00007FF7E9CC9561  000000DB91EFB3A0  0001:0000000000048561 

00007FF7E9CCA714  000000DB91EFB6A0  0001:0000000000049714 

00007FFC9FD45D81  000000DB91EFB7C0  UnhandledExceptionFilter+1F1

00007FFCA21AABAC  000000DB91EFB800  memset+2EC

00007FFCA2193B36  000000DB91EFB870  __C_specific_handler+96

00007FFCA21A8B1F  000000DB91EFB8A0  __chkstk+12F

00007FFCA2135B9A  000000DB91EFBFF0  RtlRestoreContext+8AA

00007FFCA2132E63  000000DB91EFC7D0  RtlRaiseException+163

00007FFC9FC4428C  000000DB91EFC8B0  RaiseException+6C

00007FF7EAA75BDD  000000DB91EFC9A0  0001:0000000000DF4BDD 

00007FF7E9CD8BD1  000000DB91EFCAB0  0001:0000000000057BD1 

00007FF7EA552FDB  000000DB91EFCC70  0001:00000000008D1FDB 

00007FF7EA552804  000000DB91EFCDA0  0001:00000000008D1804 

00007FF7EA4A0388  000000DB91EFCE50  0001:000000000081F388 

00007FF7EA2BA9E7  000000DB91EFD020  0001:00000000006399E7 

00007FF7EA2BB432  000000DB91EFD190  0001:000000000063A432 

00007FF7EA2BAFC9  000000DB91EFD2D0  0001:0000000000639FC9 

00007FF7EA43A350  000000DB91EFD330  0001:00000000007B9350 

00007FF7EA439A4B  000000DB91EFD360  0001:00000000007B8A4B 

00007FF7EA9405FE  000000DB91EFD3D0  0001:0000000000CBF5FE 

00007FF7E9DD78BF  000000DB91EFD430  0001:00000000001568BF 

00007FF7EA619CF8  000000DB91EFD630  0001:0000000000998CF8 

00007FF7EA619EE6  000000DB91EFD670  0001:0000000000998EE6 

00007FF7EA265AF1  000000DB91EFD6F0  0001:00000000005E4AF1 

00007FF7EA264DA5  000000DB91EFD830  0001:00000000005E3DA5 

00007FF7EA9BBBFF  000000DB91EFDC10  0001:0000000000D3ABFF 

00007FF7EA31357E  000000DB91EFE740  0001:000000000069257E 

00007FF7EA217ED1  000000DB91EFE800  0001:0000000000596ED1 

00007FF7EA216A01  000000DB91EFEC40  0001:0000000000595A01 

00007FF7E9CB512B  000000DB91EFEC80  0001:000000000003412B 

00007FF7E9CBFB92  000000DB91EFF7E0  0001:000000000003EB92 

00007FF7EAAF062C  000000DB91EFF820  argon2id_verify_ctx+29ECC

00007FFCA1035550  000000DB91EFF850  BaseThreadInitThunk+10

00007FFCA210485B  000000DB91EFF8D0  RtlUserThreadStart+2B


Call stack:
Address   Frame     Function      SourceFile
00007FFCA21A3CA4  000000DB922FFA90  ZwRemoveIoCompletion+14

00007FFC9FC500A3  000000DB922FFAF0  GetQueuedCompletionStatus+53

00007FF7E9CB8A73  000000DB922FFC00  0001:0000000000037A73 

00007FF7E9CBC474  000000DB922FFC80  0001:000000000003B474 

00007FF7E9CA440C  000000DB922FFCC0  0001:000000000002340C 

00007FFC9F766C0C  000000DB922FFCF0  _recalloc+5C

00007FFCA1035550  000000DB922FFD20  BaseThreadInitThunk+10

00007FFCA210485B  000000DB922FFDA0  RtlUserThreadStart+2B


Call stack:
Address   Frame     Function      SourceFile
00007FFCA21A3CA4  000000DB923FFBC0  ZwRemoveIoCompletion+14

00007FFC9FC500A3  000000DB923FFC20  GetQueuedCompletionStatus+53

00007FF7E9CB8A73  000000DB923FFD30  0001:0000000000037A73 

00007FF7E9CBC474  000000DB923FFDB0  0001:000000000003B474 

00007FF7E9CA440C  000000DB923FFDF0  0001:000000000002340C 

00007FFC9F766C0C  000000DB923FFE20  _recalloc+5C

00007FFCA1035550  000000DB923FFE50  BaseThreadInitThunk+10

00007FFCA210485B  000000DB923FFED0  RtlUserThreadStart+2B


Call stack:
Address   Frame     Function      SourceFile
00007FFCA21A76D4  000000DB924FFA60  NtWaitForAlertByThreadId+14

00007FFCA216AAF7  000000DB924FFAE0  RtlSleepConditionVariableSRW+137

00007FFC9FC5BCA9  000000DB924FFB20  SleepConditionVariableSRW+29

00007FFC65CA2959  000000DB924FFB50  ?_Winerror_message@std@@YAKKPEADK@Z+139

00007FFC65CA2BEA  000000DB924FFB80  _Cnd_wait+3A

00007FF7EAA67548  000000DB924FFBB0  0001:0000000000DE6548 

00007FF7E9D3EA1F  000000DB924FFBE0  0001:00000000000BDA1F 

00007FFC9F766C0C  000000DB924FFC10  _recalloc+5C

00007FFCA1035550  000000DB924FFC40  BaseThreadInitThunk+10

00007FFCA210485B  000000DB924FFCC0  RtlUserThreadStart+2B


Call stack:
Address   Frame     Function      SourceFile
00007FFCA21A76D4  000000DB925FFD40  NtWaitForAlertByThreadId+14

00007FFCA216AAF7  000000DB925FFDC0  RtlSleepConditionVariableSRW+137

00007FFC9FC5BCA9  000000DB925FFE00  SleepConditionVariableSRW+29

00007FFC65CA2959  000000DB925FFE30  ?_Winerror_message@std@@YAKKPEADK@Z+139

00007FFC65CA2BEA  000000DB925FFE60  _Cnd_wait+3A

00007FF7EAA67548  000000DB925FFE90  0001:0000000000DE6548 

00007FF7E9D3EA1F  000000DB925FFEC0  0001:00000000000BDA1F 

00007FFC9F766C0C  000000DB925FFEF0  _recalloc+5C

00007FFCA1035550  000000DB925FFF20  BaseThreadInitThunk+10

00007FFCA210485B  000000DB925FFFA0  RtlUserThreadStart+2B


Call stack:
Address   Frame     Function      SourceFile
00007FFCA21A76D4  000000DB926FFA40  NtWaitForAlertByThreadId+14

00007FFCA216AAF7  000000DB926FFAC0  RtlSleepConditionVariableSRW+137

00007FFC9FC5BCA9  000000DB926FFB00  SleepConditionVariableSRW+29

00007FFC65CA2959  000000DB926FFB30  ?_Winerror_message@std@@YAKKPEADK@Z+139

00007FFC65CA2BEA  000000DB926FFB60  _Cnd_wait+3A

00007FF7EAA67548  000000DB926FFB90  0001:0000000000DE6548 

00007FF7E9D3EA1F  000000DB926FFBC0  0001:00000000000BDA1F 

00007FFC9F766C0C  000000DB926FFBF0  _recalloc+5C

00007FFCA1035550  000000DB926FFC20  BaseThreadInitThunk+10

00007FFCA210485B  000000DB926FFCA0  RtlUserThreadStart+2B


Call stack:
Address   Frame     Function      SourceFile
00007FFCA21A3C04  000000DB927FF8B0  ZwWaitForSingleObject+14

00007FFC9FC4254E  000000DB927FF950  WaitForSingleObjectEx+8E

00007FF7E9CBC343  000000DB927FF980  0001:000000000003B343 

00007FF7E9CBD825  000000DB927FF9B0  0001:000000000003C825 

00007FFC9F766C0C  000000DB927FF9E0  _recalloc+5C

00007FFCA1035550  000000DB927FFA10  BaseThreadInitThunk+10

00007FFCA210485B  000000DB927FFA90  RtlUserThreadStart+2B


Call stack:
Address   Frame     Function      SourceFile
00007FFCA21A76D4  000000DB928FF1C0  NtWaitForAlertByThreadId+14

00007FFCA216AAF7  000000DB928FF240  RtlSleepConditionVariableSRW+137

00007FFC9FC5BCA9  000000DB928FF280  SleepConditionVariableSRW+29

00007FFC65CA2959  000000DB928FF2B0  ?_Winerror_message@std@@YAKKPEADK@Z+139

00007FFC65CA2BEA  000000DB928FF2E0  _Cnd_wait+3A

00007FF7E9D49BE2  000000DB928FFA40  0001:00000000000C8BE2 

00007FF7E9D3EA1F  000000DB928FFA70  0001:00000000000BDA1F 

00007FFC9F766C0C  000000DB928FFAA0  _recalloc+5C

00007FFCA1035550  000000DB928FFAD0  BaseThreadInitThunk+10

00007FFCA210485B  000000DB928FFB50  RtlUserThreadStart+2B


Call stack:
Address   Frame     Function      SourceFile
00007FFCA21A76D4  000000DB92BFF680  NtWaitForAlertByThreadId+14

00007FFCA216AAF7  000000DB92BFF700  RtlSleepConditionVariableSRW+137

00007FFC9FC5BCA9  000000DB92BFF740  SleepConditionVariableSRW+29

00007FFC65CA2959  000000DB92BFF770  ?_Winerror_message@std@@YAKKPEADK@Z+139

00007FFC65CA2BEA  000000DB92BFF7A0  _Cnd_wait+3A

00007FF7EA8087E8  000000DB92BFF7D0  0001:0000000000B877E8 

00007FF7E9D3EA1F  000000DB92BFF800  0001:00000000000BDA1F 

00007FFC9F766C0C  000000DB92BFF830  _recalloc+5C

00007FFCA1035550  000000DB92BFF860  BaseThreadInitThunk+10

00007FFCA210485B  000000DB92BFF8E0  RtlUserThreadStart+2B


Call stack:
Address   Frame     Function      SourceFile
00007FFCA21A3C04  000000DB92CFF740  ZwWaitForSingleObject+14

00007FFC9FC4254E  000000DB92CFF7E0  WaitForSingleObjectEx+8E

00007FF7E9CBC343  000000DB92CFF810  0001:000000000003B343 

00007FF7E9CBD825  000000DB92CFF840  0001:000000000003C825 

00007FFC9F766C0C  000000DB92CFF870  _recalloc+5C

00007FFCA1035550  000000DB92CFF8A0  BaseThreadInitThunk+10

00007FFCA210485B  000000DB92CFF920  RtlUserThreadStart+2B


Call stack:
Address   Frame     Function      SourceFile
00007FFCA21A3CA4  000000DB92DFFB90  ZwRemoveIoCompletion+14

00007FFC9FC500A3  000000DB92DFFBF0  GetQueuedCompletionStatus+53

00007FF7E9CB8A73  000000DB92DFFD00  0001:0000000000037A73 

00007FF7E9CBC474  000000DB92DFFD80  0001:000000000003B474 

00007FF7EA244429  000000DB92DFFE80  0001:00000000005C3429 

00007FF7E9D3EA1F  000000DB92DFFEB0  0001:00000000000BDA1F 

00007FFC9F766C0C  000000DB92DFFEE0  _recalloc+5C

00007FFCA1035550  000000DB92DFFF10  BaseThreadInitThunk+10

00007FFCA210485B  000000DB92DFFF90  RtlUserThreadStart+2B


Call stack:
Address   Frame     Function      SourceFile
00007FFCA21A3C44  000000DB92EFF360  NtReadFile+14

00007FFC9FC34FCB  000000DB92EFF3D0  ReadFile+7B

00007FFC9F747859  000000DB92EFF470  _read+209

00007FFC9F7476F2  000000DB92EFF4B0  _read+A2

00007FFC9F747A2A  000000DB92EFF4E0  _fgetc_nolock+AA

00007FFC9F747BFD  000000DB92EFF520  _fgetwc_nolock+FD

00007FFC9F7652D1  000000DB92EFF580  fgetws+81

00007FF7E9CC2735  000000DB92EFF9E0  0001:0000000000041735 

00007FF7E9CA43AB  000000DB92EFFA10  0001:00000000000233AB 

00007FFC9F766C0C  000000DB92EFFA40  _recalloc+5C

00007FFCA1035550  000000DB92EFFA70  BaseThreadInitThunk+10

00007FFCA210485B  000000DB92EFFAF0  RtlUserThreadStart+2B


Call stack:
Address   Frame     Function      SourceFile
00007FFCA21A4204  000000DB92FFFA70  NtDelayExecution+14

00007FFCA215B873  000000DB92FFFAA0  RtlDelayExecution+43

00007FFC9FC4AEA1  000000DB92FFFB20  SleepEx+71

00007FFC65CA2E8C  000000DB92FFFB70  _Thrd_sleep+3C

00007FF7E9CA72D0  000000DB92FFFBD0  0001:00000000000262D0 

00007FF7E9CB027F  000000DB92FFFD90  0001:000000000002F27F 

00007FF7E9CA43AB  000000DB92FFFDC0  0001:00000000000233AB 

00007FFC9F766C0C  000000DB92FFFDF0  _recalloc+5C

00007FFCA1035550  000000DB92FFFE20  BaseThreadInitThunk+10

00007FFCA210485B  000000DB92FFFEA0  RtlUserThreadStart+2B

**Comment by trickerer** [comment]
Release crashlog is **useless**. As well as its callstack. It doesn't show anything

**Comment by jasanhell1** [comment]
I am so sorry. I did not use Debug mode to test the game. I will build the new version this weekend and reproduce the call stack in Debug mode and send it here.

**Comment by trickerer** [comment]
3+ weeks without proper report, closing as stalled
