### ISSUE TITLE
[AC] [Bug] [DB] Cant populating DB

### ISSUE THREAD

**Issue by Mitradis** [trickerer/Trinity-Bots#267]
AC have auto DB population and update system, and this system not work if DBs have some data, but when auto system try populating DBs he say "not found tables npcbots", its a hopeless situation... dbimport.exe from AC need empty DBs, but he cant correct finish work because no npcbot table found.

**Comment by Mitradis** [comment]
В общем суть в том что в процессе инициализации ДБ что dbimport что worldserver натыкаются на какие-то команды в хард коде, пытаясь выполнить их при отсутствии таблиц в базе.

**Comment by Mitradis** [comment]
>> Applying update "2022_11_21_13.sql" '344A7D2'...
>> Applying update "2022_11_21_14.sql" 'E1BED2B'...
>> Applying update "2022_11_21_15.sql" '9BA28D5'...
>> Applying update "2022_11_21_16.sql" '658F564'...
>> Applying update "2022_11_21_17.sql" 'D47ADB2'...
>> Applying update "2022_11_21_18.sql" 'D3B524B'...
>> Applying update "2022_11_21_19.sql" '7FB5F0C'...
>> Applied 266 queries. Containing 0 new and 3160 archived updates.
 
In mysql_stmt_prepare() id: 455, sql: "UPDATE characters_npcbot SET owner = ? WHERE entry = ?"
Table 'acore_characters.characters_npcbot' doesn't exist
In mysql_stmt_prepare() id: 456, sql: "UPDATE characters_npcbot SET owner = ? WHERE owner = ?"
Table 'acore_characters.characters_npcbot' doesn't exist
In mysql_stmt_prepare() id: 457, sql: "UPDATE characters_npcbot SET roles = ? WHERE entry = ?"
Table 'acore_characters.characters_npcbot' doesn't exist
In mysql_stmt_prepare() id: 459, sql: "UPDATE characters_npcbot SET equipMhEx = ?, equipOhEx = ?, equipRhEx = ?, equipHead = ?, equipShoulders = ?, equipChest = ?, equipWaist = ?, equipLegs = ?, equipFeet = ?, equipWrist = ?, equipHands = ?, equipBack = ?, equipBody = ?, equipFinger1 = ?, equipFinger2 = ?, equipTrinket1 = ?, equipTrinket2 = ?, equipNeck = ? WHERE entry = ?"
Table 'acore_characters.characters_npcbot' doesn't exist
In mysql_stmt_prepare() id: 460, sql: "DELETE FROM characters_npcbot WHERE entry = ?"
Table 'acore_characters.characters_npcbot' doesn't exist
In mysql_stmt_prepare() id: 461, sql: "INSERT INTO characters_npcbot (entry, roles, spec, faction) VALUES (?, ?, ?, ?)"
Table 'acore_characters.characters_npcbot' doesn't exist
In mysql_stmt_prepare() id: 462, sql: "UPDATE characters_npcbot SET faction = ? WHERE entry = ?"
Table 'acore_characters.characters_npcbot' doesn't exist
In mysql_stmt_prepare() id: 463, sql: "UPDATE characters_npcbot SET spec = ? WHERE entry = ?"
Table 'acore_characters.characters_npcbot' doesn't exist
In mysql_stmt_prepare() id: 464, sql: "UPDATE characters_npcbot SET spells_disabled = ? WHERE entry = ?"
Table 'acore_characters.characters_npcbot' doesn't exist
In mysql_stmt_prepare() id: 465, sql: "REPLACE INTO characters_npcbot_stats (entry, maxhealth, maxpower, strength, agility, stamina, intellect, spirit, armor, defense, resHoly, resFire, resNature, resFrost, resShadow, resArcane, blockPct, dodgePct, parryPct, critPct, attackPower, spellPower, spellPen, hastePct, hitBonusPct, expertise, armorPenPct) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
Table 'acore_characters.characters_npcbot_stats' doesn't exist
In mysql_stmt_prepare() id: 466, sql: "REPLACE INTO characters_npcbot_transmog (entry, slot, item_id, fake_id) VALUES (?, ?, ?, ?)"
Table 'acore_characters.characters_npcbot_transmog' doesn't exist
In mysql_stmt_prepare() id: 467, sql: "DELETE FROM characters_npcbot_transmog WHERE entry = ?"
Table 'acore_characters.characters_npcbot_transmog' doesn't exist
In mysql_stmt_prepare() id: 468, sql: "DELETE FROM characters_npcbot_transmog WHERE entry IN (SELECT entry FROM characters_npcbot WHERE owner = ?)"
Table 'acore_characters.characters_npcbot_transmog' doesn't exist
In mysql_stmt_prepare() id: 469, sql: "REPLACE INTO characters_npcbot_group_member (guid, entry, memberFlags, subgroup, roles) VALUES(?, ?, ?, ?, ?)"
Table 'acore_characters.characters_npcbot_group_member' doesn't exist
In mysql_stmt_prepare() id: 470, sql: "DELETE FROM characters_npcbot_group_member WHERE entry = ? AND guid = ?"
Table 'acore_characters.characters_npcbot_group_member' doesn't exist
In mysql_stmt_prepare() id: 471, sql: "UPDATE characters_npcbot_group_member SET memberFlags = ? WHERE entry = ?"
Table 'acore_characters.characters_npcbot_group_member' doesn't exist
Closing down DatabasePool 'acore_characters'.
Asynchronous connections on DatabasePool 'acore_characters' terminated. Proceeding with synchronous connections.
All connections on DatabasePool 'acore_characters' closed.
Could not prepare statements of the Character database, see log for details.
Closing down DatabasePool 'acore_world'.
Asynchronous connections on DatabasePool 'acore_world' terminated. Proceeding with synchronous connections.
All connections on DatabasePool 'acore_world' closed.
Closing down DatabasePool 'acore_characters'.
Asynchronous connections on DatabasePool 'acore_characters' terminated. Proceeding with synchronous connections.
All connections on DatabasePool 'acore_characters' closed.
Closing down DatabasePool 'acore_auth'.
Asynchronous connections on DatabasePool 'acore_auth' terminated. Proceeding with synchronous connections.
All connections on DatabasePool 'acore_auth' closed.

**Comment by Mitradis** [comment]
Непонятна правильная последовательность заполнения ДБ.

**Comment by trickerer** [comment]
Похоже нужна отдельная папка в SQL 'create', где будут файлы только для создания таблиц для ботов.
Ну или добавить в родной AC скрипт создания пустой БД.

**Comment by loveofmaria** [comment]
i  got the issues too.

many table don't exist.

**Comment by EvilCalf** [comment]
![image](https://user-images.githubusercontent.com/35754619/205428160-55ee41ea-4f8b-4385-8191-a4dc2e27b61e.png)

**Comment by Mitradis** [comment]
Там еще нюанс в том, что если в базе есть пустые таблицы то автозаполнение базы не происходит. Т.е. сервер по ошибке считает что типа она не пустая а значит таблицы есть. Вот тут и получается какойто бермудский треугольник, невозможно заранее создать таблицы и невозможно автозаполнить их.

**Comment by trickerer** [comment]
В основном репозитории ращзмещение SQL файлов не изменится. Новые апдейты (АС) будут помещены в:
(In main repo SQL files placement won't change. New updates (AC) will be put into:)
- [Trinity-Bots/tree/master/AC/SQL/updates/.../](https://github.com/trickerer/Trinity-Bots/tree/master/AC/SQL/updates)
- [AzerothCore-wotlk-with-NPCBots/data/sql/custom/.../](https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/tree/npcbots_3.3.5/data/sql/custom)
