### ISSUE TITLE
[AC] [Crash][Serious BUG]worldserver.exe crash while If death does not immediately release the soul on the gunship of ICC( third BOSS)

### ISSUE THREAD

**Issue by zbhcn** [trickerer/Trinity-Bots#268]
worldserver.exe crash while If death does not immediately release the soul on the gunship of ICC( third BOSS)

There is no official bug in azerothcore, so I guess it is probably caused by the death of the npcbot

sorry,my english is poor，I wish you will understand.this bug always exists

**Comment by zbhcn** [comment]
I have tested for many times in two different situations:

1. Without npcbots, even if you die without releasing your soul, the body will be moved to the entrance by the system without causing downtime.

2. With the robots, if you die and the soul is not released within 3 seconds, the body will be shut down in the process of system displacement.

I'm sure it's npcbot's problem, not AZ's core problem

**Comment by littlehelper1987** [comment]
+1
can confirm this. If you die or killed the Boss, Server Crashs. 
You cant loot and the Ship is gone. This issue is only with NPCBots.
