### ISSUE TITLE
Patch fails to apply on TrinityCore 335.20091

### ISSUE THREAD

**Issue by LEO33SoFo** [trickerer/Trinity-Bots#27]
Tested with https://github.com/TrinityCore/TrinityCore/commit/9d959123e68020a83c780f53a967b3589cb70786, I got:
```
error: patch failed: src/server/game/Globals/ObjectMgr.h:1489
error: src/server/game/Globals/ObjectMgr.h: patch does not apply
```

**Comment by SneakyV** [comment]
I get the following error while compiling:


```
[ 17%] Building CXX object src/server/game/CMakeFiles/game.dir/AI/NpcBots/bot_ai.cpp.o
In file included from /home/wowserver/TrinityBotCore/src/server/game/AI/NpcBots/bot_ai.cpp:1:
/home/wowserver/TrinityBotCore/src/server/game/AI/NpcBots/bot_ai.h:42:42: error: only virtual member functions can be marked 'override'
        bool GossipHello(Player* player) override;
                                         ^~~~~~~~
/home/wowserver/TrinityBotCore/src/server/game/AI/NpcBots/bot_ai.h:43:79: error: only virtual member functions can be marked 'override'
        bool GossipSelect(Player* player, uint32 menuId, uint32 gossipListId) override;
                                                                              ^~~~~~~~
/home/wowserver/TrinityBotCore/src/server/game/AI/NpcBots/bot_ai.h:44:101: error: only virtual member functions can be marked 'override'
        bool GossipSelectCode(Player* player, uint32 menuId, uint32 gossipListId, char const* code) override;
                                                                                                    ^~~~~~~~
In file included from /home/wowserver/TrinityBotCore/src/server/game/AI/NpcBots/bot_ai.cpp:7:
/home/wowserver/TrinityBotCore/src/server/game/AI/NpcBots/bpet_ai.h:21:14: warning: 'AttackStart' overrides a member function but is not marked 'override'
      [-Winconsistent-missing-override]
        void AttackStart(Unit* u);
             ^
/home/wowserver/TrinityBotCore/src/server/game/AI/CoreAI/UnitAI.h:141:22: note: overridden virtual function is here
        virtual void AttackStart(Unit* /*target*/);
                     ^
/home/wowserver/TrinityBotCore/src/server/game/AI/NpcBots/bot_ai.cpp:5124:62: warning: multi-character character constant [-Wmultichar]
                message1 << "Willst Du " << me->GetName() << ' locken?';
                                                             ^
/home/wowserver/TrinityBotCore/src/server/game/AI/NpcBots/bot_ai.cpp:5124:62: warning: character constant too long for its type
/home/wowserver/TrinityBotCore/src/server/game/AI/NpcBots/bot_ai.cpp:5129:65: warning: multi-character character constant [-Wmultichar]
                message1 << "Möchtest Du " << me->GetName() << ' anheuern ?';
                                                               ^
/home/wowserver/TrinityBotCore/src/server/game/AI/NpcBots/bot_ai.cpp:5129:65: warning: character constant too long for its type
/home/wowserver/TrinityBotCore/src/server/game/AI/NpcBots/bot_ai.cpp:7090:4: error: invalid preprocessing directive
 # Gelöscht
   ^
5 warnings and 4 errors generated.
make[2]: *** [src/server/game/CMakeFiles/game.dir/build.make:246: src/server/game/CMakeFiles/game.dir/AI/NpcBots/bot_ai.cpp.o] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:1367: src/server/game/CMakeFiles/game.dir/all] Fehler 2
make: *** [Makefile:130: all] Fehler 2

```

**Comment by trickerer** [comment]
The update which was supposed to happen today is delayed due to [this error](https://github.com/TrinityCore/TrinityCore/commit/14fa6c3a725f617e02af74eea95f5074b9095704#comments)

**Comment by 328950225** [comment]
> 编译时出现以下错误：
> 
> ```
> [ 17%] Building CXX object src/server/game/CMakeFiles/game.dir/AI/NpcBots/bot_ai.cpp.o
> In file included from /home/wowserver/TrinityBotCore/src/server/game/AI/NpcBots/bot_ai.cpp:1:
> /home/wowserver/TrinityBotCore/src/server/game/AI/NpcBots/bot_ai.h:42:42: error: only virtual member functions can be marked 'override'
>         bool GossipHello(Player* player) override;
>                                          ^~~~~~~~
> /home/wowserver/TrinityBotCore/src/server/game/AI/NpcBots/bot_ai.h:43:79: error: only virtual member functions can be marked 'override'
>         bool GossipSelect(Player* player, uint32 menuId, uint32 gossipListId) override;
>                                                                               ^~~~~~~~
> /home/wowserver/TrinityBotCore/src/server/game/AI/NpcBots/bot_ai.h:44:101: error: only virtual member functions can be marked 'override'
>         bool GossipSelectCode(Player* player, uint32 menuId, uint32 gossipListId, char const* code) override;
>                                                                                                     ^~~~~~~~
> In file included from /home/wowserver/TrinityBotCore/src/server/game/AI/NpcBots/bot_ai.cpp:7:
> /home/wowserver/TrinityBotCore/src/server/game/AI/NpcBots/bpet_ai.h:21:14: warning: 'AttackStart' overrides a member function but is not marked 'override'
>       [-Winconsistent-missing-override]
>         void AttackStart(Unit* u);
>              ^
> /home/wowserver/TrinityBotCore/src/server/game/AI/CoreAI/UnitAI.h:141:22: note: overridden virtual function is here
>         virtual void AttackStart(Unit* /*target*/);
>                      ^
> ```

Follow my steps:
first :
in NPCBots.patch 
1,replace OnGossipHello OnGossipSelect OnGossipSelectCode to other names like nOnGossipHello nOnGossipSelect nOnGossipSelectCode
2,replace GossipHello  GossipSelect GossipSelectCode to OnGossipHello OnGossipSelect OnGossipSelectCode
save.
After solving the location of the patch line, I tested that the latest version of the patch for ElunaTrinityWotlk~TrinityCore can be used.
Of course, you can also use the files I have modified
[NpcBots_edited.zip](https://github.com/trickerer/Trinity-Bots/files/5361243/NpcBots_edited.zip)
