### ISSUE TITLE
 [AC] [Bug] [NPCBOTS] NpcBots All empty

### ISSUE THREAD

**Issue by loveofmaria** [trickerer/Trinity-Bots#272]
**Description:**

.npcbot add xxx  -> output in the dialog is NULL

or

.npc add 70000 <bots hire>

all bots menu is [ ]

**Comment by trickerer** [comment]
Seems like a localization problem.

What is client locale?
What is server dbc's locale?
What is `DBC.Locale` in worldserver.conf?

**Comment by loveofmaria** [comment]
i think the locale is zhCN.

i imported a sql file in locales - zhCN folder

**Comment by trickerer** [comment]
Maybe @396842276 or @souloi could give you a hint faster than me getting the locale files and testing

**Comment by loveofmaria** [comment]
Thanks for your help.
i'll have a try with their hints.
