### ISSUE TITLE
Can you explain how to use the new command .npcbot sendto?

### ISSUE THREAD

**Issue by jasanhell1** [trickerer/Trinity-Bots#274]
I just built the new core. 

Can you please give an explaination how to use the new command .npcbot sendto?

If you can give an example, that will be great.

I appreciate it.

**Comment by Mr-Deadbeat** [comment]
it's fairly simple create a macro for example with the name Bots Sendto inside the macro type /p .npcbot sendto

add some blue smoke flares to your inventory with .additem 23770

when you want to send them somewhere use a blue smoke flare and throw it somewhere and the bots will run to that location

usually only need to use this feature when there is a problem with pathing in the game for example inside The Shattered Halls in Hellfire peninsula where you need to jump down into the pit to reach the boss Netherkurse

hope this will get you going :)

**Comment by trickerer** [comment]
https://github.com/trickerer/Trinity-Bots/commit/107405447e29c61cc5d942418d6e3db84372f11e#commitcomment-91538332
https://github.com/trickerer/Trinity-Bots/issues/266#issuecomment-1334736461

Here are two video examples.

**Comment by jasanhell1** [comment]
Thank you for the explanation. 

I am just wondering. Is that necessary and possible to enchant the command (sendto). 

Example:
.npcbot sendto warrior (all the warriors will go to position)
.npcbot sendto tank (all the tank will go to the position)
.npcbot sendto priest
.npcbot sendto warrior, priest, mage, druid, rogue (all the warrior, priest, mage, druid, and rogue will go the position)
.npcbot sendto name1, name2, name3, name4

The reason is we can send 5 npcbots to the position, hold it and attacking the boss.
Then we can use another command **.npcbot recall teleport**, recall the others npcbots to other dimension. 
We can defeat the boss like kalecgos and sathrovarr at the same time.

**Comment by trickerer** [comment]
Currently commands don't support names (except .npcb order cast) or name/class sets like this. It's selected/all/none(show help).
Somewhat related: https://github.com/trickerer/Trinity-Bots/discussions/271

Currently how you do this is write a macro
```
/target <name1>
.npcb ...
/target <name2>
.npcb ...
```
You may want to end it with `/target player` or add `/targetlasttarget` after each block to retain target.

And yes - you can `.npcb send` several bots one after another before actually sending them

**Comment by jasanhell1** [comment]
> And yes - you can `.npcb send` several bots one after another before actually sending them

Thank you so much for furture explaination. That's great that we can send serveral bots one after another.

> Somewhat related: https://github.com/trickerer/Trinity-Bots/discussions/271
True. 
I am thinking the difficult bosses to defeat are:

TempleOfAhnQiraj: cthun and twin emperors
SunwellPlateau: kalecgos and sathrovarr
Ulduar: algalon the observer and Yogg-Saron

They require either defeat the boss at the same time or other dimension. 
If we can set a **specific npcbots group** for one, and the other group will follow with the player (including other dimension), it is possible that player can defeat these kinds of bosses normally.
