### ISSUE TITLE
AC ICC Gunship 

### ISSUE THREAD

**Issue by littlehelper1987** [trickerer/Trinity-Bots#275]
If u use the Cannon on the Ship, all Bots went in a Cannon :) It's funny but probably not intentional :))

![WoWScrnShot_120622_134633](https://user-images.githubusercontent.com/76127576/205918107-1571179a-802d-4076-a7e3-b6a6afd83080.jpg)

**Comment by trickerer** [comment]
There is no vehicle strat for bots for this boss yet, so most bots will spawn cannons along with you for possible quick draw.
I don't remember the exact limit but almost all dps bots will do that save for pure healers and tanks on both 10man and 25man.

**Comment by trickerer** [comment]
To imlpement individual vehicle choices without checking master's vehicle requires general behavior modes implementation, which opens possibilities for free bots in world, BG bots and other fun stuff, but that's unpredictably time-consuming by itself so such a revamp may not happen, ever.
