### ISSUE TITLE
[TC] WTF with rotation? 

### ISSUE THREAD

**Issue by darhanger** [trickerer/Trinity-Bots#276]
**Description:**

Its possible somehow check bots rotation and change it? Its bit cancer on almost all...

**Comment by trickerer** [comment]
Bots don't use perfect rotation anywhere, it's kind of semi-random. It depends on talents tree and roles. Arms warrior will do pvp-ish rotation, unless he is tanking, fire mages do Frostfire Bolt based pve rotation, etc.
If you think some bot need an improvement in their actions, some ability they don't use or some abilities sequence you expect to see doesn't happen - describe it, if you think some bots behave stupidly is pve - tell me about it.

**Comment by trickerer** [comment]
If there is anything else to report on this front, please open a separate issue
