### ISSUE TITLE
Can I remove all bots that have been summoned but no one has hired them

### ISSUE THREAD

**Issue by EvilCalf** [trickerer/Trinity-Bots#277]
Someone on my server called a bunch of bots, but they didn't hire them

Thanks a lot.

**Comment by trickerer** [comment]
Hm. Not yet. QoL stuff for non-small servers isn't there.
Need a new command for that. Or maybe a set of sqls, one for characters, one for world.

**Comment by EvilCalf** [comment]
> Hm. Not yet. QoL stuff for non-small servers isn't there. Need a new command for that. Or maybe a set of sqls, one for characters, one for world.

thanks.A player's spawned bot. Can other players spawn or summon to their side

**Comment by trickerer** [comment]
`.npcbot spawn` requires permission 70004 which is by default linked to gm and admin accounts (TC). On AC this command requires SEC_GAMEMASTER directly.
