### ISSUE TITLE
Chat Spam when bots in group

### ISSUE THREAD

**Issue by Booser** [trickerer/Trinity-Bots#28]
On our server there is a lot of chat spamming when at least one bot is in any group. It says "Party x gehört nicht zu eurer Gruppe" in german. It reads like "Party x does not belong to your group" where x is any number between 2 and 4 or so. It is coming in group one player one bot. And even more when our group of 3 is filled with 2 bots.

We could not see what type of events possibly trigger these messages. It seems they are coming out of the client itself.

We are using Version NPCBots v4.7.34a with the code from TrinityCore revision: 68a4085427 like given on the start page.

**Comment by Parkan1986** [comment]
Так же есть момегт, когда игрок один и он делает рейд из ботов то в чат идут сообщения про raid1 is not part of raid( или что то такое) , причем это сообщение дублируется под каждого бота типа raid1, raid2 и тд и появляется при каждом телепортировании либо смерти бота в бою. 

Впринципе ничего критического, но глаза мозолит.

**Comment by trickerer** [comment]
This happens when addons are trying to query player info from group members.
In most cases Unit Frames addons are doing this - resolving this problem requires client editing.
Probably need to add this to known issues as well.

I am personally don't get too many of these errors (using XPerl + HealBot)

**Comment by Booser** [comment]
Oh, then maybe I find a way to filter some of the status calls out when a Bot is part of the group.

**Comment by trickerer** [comment]
Added to known issues

**Comment by AreChen** [comment]
Encountered the same issue, in the latest components, there is a large amount of similar information in both battlefield and 5-player team, ZH_CN client.

**Comment by DEV7163** [comment]
This is an annoying issue.
If it can't be resolved server-side, what about creating an addon that greps the message and suppresses it?

Edit: Well, I just did it:

STFU.lua
```
local blockedPatterns = {
    "is not in your party"
}

local function ChatFilter(self, event, msg, ...)
    if not msg then return false end
    
    local messageLower = msg:lower()
    for _, pattern in ipairs(blockedPatterns) do
        if string.find(messageLower, pattern, 1, true) then
            return true
        end
    end
    return false
end

ChatFrame_AddMessageEventFilter("CHAT_MSG_SYSTEM", ChatFilter)
ChatFrame_AddMessageEventFilter("CHAT_MSG_CHANNEL", ChatFilter)
ChatFrame_AddMessageEventFilter("CHAT_MSG_SAY", ChatFilter)
ChatFrame_AddMessageEventFilter("CHAT_MSG_YELL", ChatFilter)
ChatFrame_AddMessageEventFilter("CHAT_MSG_WHISPER", ChatFilter)
```

STFU.toc
```
## Interface: 30300
## Title: STFU
## Notes: Or else
STFU.lua
```
