### ISSUE TITLE
Hope to find the bot that nobody uses

### ISSUE THREAD

**Issue by EvilCalf** [trickerer/Trinity-Bots#283]
.npcb lookup 
This command can view robots in all templates,but not free.
Players must try the bot one by one. To find the bot is not hired

**Comment by trickerer** [comment]
Right now you can check if bot is spawned only by using `.npcbot spawned` command which will list spawned bots in sorted order and their statuses

**Comment by EvilCalf** [comment]
> Right now you can check if bot is spawned only by using `.npcbot spawned` command which will list spawned bots in sorted order and their statuses

Can i delete the spawned bot by sql, so that anyone else can spawn them

**Comment by trickerer** [comment]
> Can i delete the spawned bot by sql, so that anyone else can spawn them

You've already asked this question
#277 
And I have to wonder why would you give permission to spawn bots to anyone except GMs.

**Comment by EvilCalf** [comment]
> 

yes , i konw. Sorry,i know dont have a command.But i still want to use sql to do this.
i give permission to spawn bots to anyone.

**Comment by EvilCalf** [comment]
Maybe can add the deletion of the specified ID.

Thanks a lot!Please forgive my frequent questions.
