### ISSUE TITLE
[AC] [QUESTION]

### ISSUE THREAD

**Issue by zbhcn** [trickerer/Trinity-Bots#284]
Look this :

![image](https://user-images.githubusercontent.com/116956612/206667969-6c65f753-5bbe-4b24-9c02-38a306da0275.png)

what's wrong?

**Comment by trickerer** [comment]
https://wotlkdb.com/?spell=57345

Try and see if it's related to bots at all

**Comment by zbhcn** [comment]
I found the source code, which looks like this: 
pa
F:\AzerothCore-wotlk-with-NPCBots\src\server\game\Entities\Unit\Unit.cpp
File Path：
SpellInfo const * triggerEntry=sSpellMgr ->GetSpellInfo (trigger_spell_id);

code:

if (!triggerEntry)

{

// Don't cast unknown spell

LOG_ ERROR("entities.unit", "Unit::HandleProcTriggerSpell: Spell {} (effIndex: {}) has unknown TriggerSpell {}. Unhandled custom case?", auraSpellInfo->Id, triggeredByAura->GetEffIndex(), trigger_ spell_ id);

return false;

}

**Comment by trickerer** [comment]
Try it in-game on a player using that trinket. If you get the same error in console then this is AC bug and not related to bots

**Comment by zbhcn** [comment]
Wait a minute. I'll test it right away

**Comment by zbhcn** [comment]
i have try it in-game on a player using that trinket.Its effect can be triggered normally
