### ISSUE TITLE
[AC] [Bug] warlock‘s spell-Life Tap isn't display

### ISSUE THREAD

**Issue by zbhcn** [trickerer/Trinity-Bots#286]
![image](https://user-images.githubusercontent.com/116956612/206828289-ec47bd44-b9d7-4726-930b-fdbf6fc425c3.png)
look this, i test it ,it's Life Tap
and this skill - Metamorphosis is also not displayed

By the way, can npcbots use inscriptions?

**Comment by trickerer** [comment]
1.
> look this, i test it ,it's Life Tap

The problem is that this spell (all ranks) is added to `spell_dbc` table. You need to localize it there (maybe setting translations to NULL will also work)

2.
Metamorphosis is not implemented (and is not coming soon)
