### ISSUE TITLE
Server downtime

### ISSUE THREAD

**Issue by HolmesLiu** [trickerer/Trinity-Bots#287]
After the new azerothcore patch is compiled, bot administrators cannot recruit bot，Click npc administrator to recruit npc, and the server will be disconnected

Patch version NPCBots v5.2.55a.

**Comment by trickerer** [comment]
Can't confirm, I can recruit bot through normal gossip and botgiver. Plus, there were no related changes recently.

Provide a debug crashlog if you want me to look into it.
