### ISSUE TITLE
[AC]bot missing

### ISSUE THREAD

**Issue by EvilCalf** [trickerer/Trinity-Bots#288]
bot_ai::SetBotOwner(): Theridran's master 我是渣渣辉 (GUID Full: 0x0000000000000073 Type: Player Low: 115) is found but bot failed to set owner (fatal)! Unbinding bot temporarily (until server restart)...

player login in the game,and the bot lost

**Comment by EvilCalf** [comment]
bot_ai::SetBotOwner(): Valda's master 巅峰 (GUID Full: 0x0000000000000075 Type: Player Low: 117) is found but bot failed to set owner (fatal)! Unbinding bot temporarily (until server restart)...
bot_ai::SetBotOwner(): Isabella's master 巅峰 (GUID Full: 0x0000000000000075 Type: Player Low: 117) is found but bot failed to set owner (fatal)! Unbinding bot temporarily (until server restart)...
bot_ai::SetBotOwner(): Ker's master 巅峰 (GUID Full: 0x0000000000000075 Type: Player Low: 117) is found but bot failed to set owner (fatal)! Unbinding bot temporarily (until server restart)...

always....

**Comment by trickerer** [comment]
This happens in 3 cases:
1. Bot system is disabled but bot still has owner.
2. Maximum bots has been reduced in config.
3. Maximum class bots has been reduced in config.

in 2 and 3 player can no longer use this many bots but still is an owner for all of them. Not all bots will be added to player, that's it.

**Comment by EvilCalf** [comment]
Thank you very much

**Comment by EvilCalf** [comment]
Every time the above bot disappears, restart the server to recover. But I can't restart the server for every player。
Is it possible to solve this problem
Thanks a lot.

**Comment by trickerer** [comment]
You have to either revert your worldconfig changes of maximum bots or just ignore the errors - they will go away eventually, when bot ownership expires or player dismisses some of their bots.
You can also reset bot's owner in-game in GM mode using debug gossip menu.

**Comment by EvilCalf** [comment]
When I started from the server, I set the maximum number to 4.Most cases are normal. A few players find that the bot will disappear after logging in.By use npcb info,also show the bot missing.But my characters_npc in database still have the data about the bot which they owned.And after restarting the server ,the bots will appear.

**Comment by EvilCalf** [comment]
After the player is online, he found that the robot disappeared, while there still has data in the database. Players can still hire robots to make the data in the database exceed the set maximum value.According to the feedback of players during this period, it seems that the disappearance of robots is related to accidental offline

![8$WT$MG K@}GH 33F@RQ$_W](https://user-images.githubusercontent.com/35754619/208674754-8c59aabc-f984-44fb-bb5e-7ee30b58cb35.png)

**Comment by trickerer** [comment]
So are you saying the problem is that players can hire bots regardless of config limits?

And you did not give `.npcbot add` command permission to players, did you?

**Comment by EvilCalf** [comment]
> So are you saying the problem is that players can hire bots regardless of config limits?
> 
> And you did not give `.npcbot add` command permission to players, did you?

I did not give `.npcbot add` command permission to players.
They just use gossip menu to hire.
Once they disconnected from server accidentally,sometimes the bot will lost. But at the moment, the data in database did not disapper.It's just that the bot disappeared when they were online. When they use  `.npcbot info`, they also find the bot number is decrease. And they can hire new bot, even if the count of the bot in database has reach the max num.

**Comment by EvilCalf** [comment]
> So are you saying the problem is that players can hire bots regardless of config limits?
> 
> And you did not give `.npcbot add` command permission to players, did you?

I did not give `.npcbot add` command permission to players.
They just use gossip menu to hire.
Once they disconnected from server accidentally,sometimes the bot will lost. But at the moment, the data in database did not disapper.It's just that the bot disappeared when they were online. When they use  `.npcbot info`, they also find the bot number is decrease. And they can hire new bot, even if the count of the bot in database has reach the max num.

**Comment by EvilCalf** [comment]
> So are you saying the problem is that players can hire bots regardless of config limits?
> 
> And you did not give `.npcbot add` command permission to players, did you?

Yes, players can hire bots regardless of config limits, when the bot missing occurs.

**Comment by trickerer** [comment]
https://github.com/trickerer/Trinity-Bots/commit/ee67b680a345ff4315a238bad059bf06813145ff

**Comment by EvilCalf** [comment]
I'm sorry.But bot missing is still happen.
`npcb info`shows player have no NPCbots!
But database still have,and can use `npcb move` to move.
When i chat to the bot ,shows they have been hired by the players.

**Comment by EvilCalf** [comment]
> [ee67b68](https://github.com/trickerer/Trinity-Bots/commit/ee67b680a345ff4315a238bad059bf06813145ff)

I'm sorry.But bot missing is still happen.
npcb infoshows player have no NPCbots!
But database still have,and can use npcb move to move.
When i chat to the bot ,shows they have been hired by the players.

**Comment by trickerer** [comment]
This means you screwed up your bots installation and there are entries in `charaters_npcbot` table of bots not existing in `creature` table. Players own the bots but they don't exist in world.

Your best way of fixing this is to spawn those bots and `.npcbot delete` them while in-game so you don't have dangling item_instance entries in DB of items not owned by anyone.
