### ISSUE TITLE
[AC] [Crash] worldserver crash

### ISSUE THREAD

**Issue by blazersrng** [trickerer/Trinity-Bots#289]
Hi, can you take a look what is the cause?

https://gist.github.com/blazersrng/735cac1a43fe119b6c8072f04e82b7d5

AzerothCore rev. f8948253dd38+ 2022-12-10 13:20:16 +0700 (npcbots_3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)
OS Windows 7

**Comment by trickerer** [comment]
Provide a link to your Individual Player Progression mod source please

**Comment by trickerer** [comment]
This spell is item-based from the looks of it. The caster unit is NULL but that UnitScript doesn't check it. You'd better report this is the mod' issue tracker. Just a null pointer dereference.
