### ISSUE TITLE
Server crash when doing trial of crusader

### ISSUE THREAD

**Issue by Ryu1254** [trickerer/Trinity-Bots#29]
Hi, When I do the first boss of trial of crusader with NPCBot mod, after kill the Gormok the Impaler. the Dreadscale start entering to the room. boom, the server crash.

I try to recompile from the trinitycore 3.3.5 without any mod, the fight is working as expect. 

any idea what cause the crash?
I attached the debug and the dump, hope this can help.

I try VS2019 16.7.2 with boost 1.72 and 1.74 both, version game me the same result.

[454d86c4e7e8+_worldserver.exe_[8-10_23-18-37].zip](https://github.com/trickerer/Trinity-Bots/files/5352418/454d86c4e7e8%2B_worldserver.exe_.8-10_23-18-37.zip)

**Comment by trickerer** [comment]
Seems like NULL attacker got dereferenced at Unit.cpp:1674. Well, that's my mistake.

Here is a quick fix:
```
-     if (attacker->GetTypeId() == TYPEID_UNIT && attacker->ToCreature()->IsNPCBot())
+     if (attacker && attacker->GetTypeId() == TYPEID_UNIT && attacker->ToCreature()->IsNPCBot())
```

**Comment by Ryu1254** [comment]
ohhh cool. i'll give a try and let you know the outcome.
Thanks for the quick respond.

**Comment by Ryu1254** [comment]
confirmed, the fix is working as expected.
I am able complete the ToC with with bots.
Thank you very much.
