### ISSUE TITLE
 [AC] [Crash] Message 'TOTAL_AURAS must be at least %u

### ISSUE THREAD

**Issue by askvod** [trickerer/Trinity-Bots#293]
AzerothCore:**

Loading SpellInfo Store...
#----------------------------------------------------------------------#

>> ASSERTION FAILED

# Location 'F:\azerothcore-wotlk\src\server\game\Spells\SpellMgr.cpp:2718'
# Function 'SpellMgr::LoadSpellInfoStore'
# Condition 'spellEffectInfo.ApplyAuraName < TOTAL_AURAS'
# Message 'TOTAL_AURAS must be at least %u'

#----------------------------------------------------------------------#

**Comment by trickerer** [comment]
What makes you think this is related to NPCBots?
