### ISSUE TITLE
[AC]`Table `command` 

### ISSUE THREAD

**Issue by zaicopx** [trickerer/Trinity-Bots#296]
I got this on worldserver.exe after build ur latest AC
`Table `command` contains data for non-existant command 'npcbot spawned'. Skipped.`

**Comment by Parkan1986** [comment]
Да хочу потвердить.Такая же ошибка стала вылезать после добавления новых комманд,пару дней назад.

**Comment by trickerer** [comment]
https://github.com/trickerer/Trinity-Bots/commit/2f8da602357ac1355bc3174c0167702fe5807153

**Comment by Parkan1986** [comment]
Странные дела,что после перекомпиляции экзешников и обновления базы эта ошибка опять появляется.

**Comment by trickerer** [comment]
Упс.
https://github.com/trickerer/Trinity-Bots/commit/48690054cecf42f29b2949c8bc8f87d8a86695c5
Не надо ничего перекомпилировать
