### ISSUE TITLE
[AC] [Bug] [Spell] NPCBots' Area of Effect spells will hurt NPC

### ISSUE THREAD

**Issue by AlvinZhu** [trickerer/Trinity-Bots#297]
**Description:**

NPCBots' Area of Effect spells will hurt NPC, then NPCs will attack NPCBots, and NPCBots will kill NPC.

AzerothCore

**Current behaviour:**

NPCBots' Area of Effect spells will hurt NPC(the player can't hart)

**Expected behaviour:**

NPCBots' Area of Effect spells will **not** hurt NPC(the player can't hart)

**Steps to reproduce the problem:**

1. spawn and add 4 NPCBots with ID: 70038, 70065, 700320, 700356
2. try to complete the Quest( ID 9752 ) in Zangarmarsh
3. the NPC (ID 17969) will be killed by NPCBots after NPCBots use Area of Effect spells.

AzerothCore rev. 01740cbf9061 2022-12-21 14:30:43 +0800 (main branch) (Unix, Release, Static) (authserver)
**Operating system:** Linux

**Comment by trickerer** [comment]
Caused by #295
