### ISSUE TITLE
npcbot revive should also give player

### ISSUE THREAD

**Issue by qyh214** [trickerer/Trinity-Bots#3]
you give player use .npcbot kill. but I seems they can not revive by themself? maybe .npcbot revive command should also give player use.

sometimes npcbot maybe in combat,player will use .npcbot kill to fix this issue.

**Comment by trickerer** [comment]
Bots do revive by themselves, but it takes some time (1 minute for controlled and 3 minutes for free bots)  
`.npcbot revive` command exists but only available to gm and admin accounts
