### ISSUE TITLE
'can't find file to patch at input 1808' and other lines

### ISSUE THREAD

**Issue by Tameiki** [trickerer/Trinity-Bots#30]
Hello,

I'm trying to use this patch, but after some "patching file sql/...", I have this error "can't find file to patch at input 1808" then asking for a "File to patch:". I already tried tu manually download the .sql file and give it to the "File to patch" prompt, it doesn't work.

If I skip it, the same error occurs with other "input".

Any idea please ?

![image](https://user-images.githubusercontent.com/17551010/95680786-4c8dbc80-0bdc-11eb-9743-160033186389.png)

**Comment by trickerer** [comment]
Make sure you're using patch for the last version and not 2013 one.

**Comment by Tameiki** [comment]
Re downloaded the right patch, still the same error.

**Comment by trickerer** [comment]
Files aren't found where they should be. Are you sure you are in the right folder?
