### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by saliven1970** [trickerer/Trinity-Bots#300]
server/game/AI/NpcBots/lib/bottraits.h

must:

#ifndef BOT_TRAITS_H
#define BOT_TRAITS_H

#include "botcommon.h"

#include "Creature.h"
#include "SpellAuraEffects.h"
#include "Log.h"

I add  #include "Log.h"
Otherwise, it will go wrong.
 TC_LOG_ERROR("entities.player", "bot_ai::CanAffectVictimSchools(): trying to check invalid spell school, first: %u", uint32(results.at(0).first));

**Comment by trickerer** [comment]
Happens. Non-PCH build is not being tested unfortunately.
https://github.com/trickerer/TrinityCore-3.3.5-with-NPCBots/commit/44cfa2d496b9eeed1d19bad90f4e69ba02502b4e
