### ISSUE TITLE
[AC] [Crash] Npcbot Owner Expire

### ISSUE THREAD

**Issue by drachai** [trickerer/Trinity-Bots#302]
Firs spawn the bot then restart the server and server crash.

Report

>> ASSERTION FAILED

# Location 'C:\Game\AzerothCore-Builder-2022\Source\AzerothCore\src\server\game\AI\NpcBots\bot_ai.cpp:438'
# Function 'bot_ai::CheckOwnerExpiry'
# Condition 'npcBotData'
# Message 'bot_ai::CheckOwnerExpiry(): data not found!'

# Debug info: 'Me: MapID: 0 X: -1832.71 Y: -4187.02 Z: 3.7198 O: 1.77343
GUID Full: 0xf13001117e00000f Type: Creature Entry: 70014  Low: 15 Entry 70014
Name: Krang
AliveState: true UnitMovementFlags: 0 ExtraUnitMovementFlags: 0 Class: 1
AIName:  ScriptName: warrior_bot WaypointPath: 0 SpawnId: 3110633'

**Comment by trickerer** [comment]
Provide NPCBots version or patched repo revision.
Attach worldserver startup log.

**Comment by drachai** [comment]
[Server.log](https://github.com/trickerer/Trinity-Bots/files/10307388/Server.log)

Build your last repo

The server can not start directly closed

end of server.log

ASSERTION FAILED

Location 'C:\Game\AzerothCore-Builder-2022\Source\AzerothCore\src\server\game\AI\NpcBots\bot_ai.cpp:438'
Function 'bot_ai::CheckOwnerExpiry'
Condition 'npcBotData'
Message 'bot_ai::CheckOwnerExpiry(): data not found!'
Debug info: 'Me: MapID: 0 X: -1832.71 Y: -4187.02 Z: 3.7198 O: 1.77343
GUID Full: 0xf13001117e00000f Type: Creature Entry: 70014 Low: 15 Entry 70014
Name: Krang
AliveState: true UnitMovementFlags: 0 ExtraUnitMovementFlags: 0 Class: 1
AIName: ScriptName: warrior_bot WaypointPath: 0 SpawnId: 3110633'

**Comment by drachai** [comment]
and this is the crash report
[unknown_2612.exe_[26-12_11-26-58].txt](https://github.com/trickerer/Trinity-Bots/files/10307414/unknown_2612.exe_.26-12_11-26-58.txt)

**Comment by drachai** [comment]
This is the crash report

[unknown_2612.exe_[27-12_12-55-59].txt](https://github.com/trickerer/Trinity-Bots/files/10307420/unknown_2612.exe_.27-12_12-55-59.txt)

**Comment by trickerer** [comment]
1.
> Build your last repo

This can't be true unless you have some code modifications in bot_ai.cpp.
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/blob/npcbots_3.3.5/src/server/game/AI/NpcBots/bot_ai.cpp Line 438 is

```
 CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_SEL_NPCBOT_EQUIP_BY_ITEM_INSTANCE);
```
And the assertion is at line 412

2. Release crash log is useless, also it isn't needed here.

As for solution here:
Try and see if bot 70014 exists in your `characters_npcbot` table, and if not, feel free to add it there with `roles = 4`

I see you have 74 bot entries in `characters_npcbot`. Did you delete one manually?

**Comment by drachai** [comment]
Ah i take build 6 days ago. I'll rebuild and try. 

Yes when i saw the first erro i delete some id's on characters_npcbot table

**Comment by trickerer** [comment]
You shouldn't delete anything from `characters_npcbot` table manually.

Now you have to either add them all back or delete them from `creature` table also

**Comment by drachai** [comment]
I added the deleted table now ws crash on starting. I'll build debug and update crash report
[Server.log](https://github.com/trickerer/Trinity-Bots/files/10308379/Server.log)

**Comment by drachai** [comment]
debug crash report
[debug.exe_[27-12_16-33-24].txt](https://github.com/trickerer/Trinity-Bots/files/10308409/debug.exe_.27-12_16-33-24.txt)

**Comment by trickerer** [comment]
I'm not sure why but your debug build doesn't contain debug symbols. It's impossible to know where the error is happening.

Do you get an error in the console?

**Comment by drachai** [comment]
No i dont get error on console. on the console

 

> Starting Map System
>  
> > Config: Missing property NpcBot.Mult.HP in all config files, at least the .dist file must contain: "NpcBot.Mult.HP = 1.000000"
> > Config: Missing option NpcBot.Transmog.Enable, add "NpcBot.Transmog.Enable = 0"
> > Config: Missing option NpcBot.Transmog.MixArmorClasses, add "NpcBot.Transmog.MixArmorClasses = 0"
> > Config: Missing option NpcBot.Transmog.MixWeaponClasses, add "NpcBot.Transmog.MixWeaponClasses = 0"
> > Config: Missing option NpcBot.Transmog.MixWeaponInventoryTypes, add "NpcBot.Transmog.MixWeaponInventoryTypes = 0"
> > Config: Missing option NpcBot.Transmog.UseEquipmentSlots, add "NpcBot.Transmog.UseEquipmentSlots = 0"
> Re-Loading Spell Proc conditions...
> >> Loaded 0 Spell Proc Conditions And Data. DB table `spell_proc` Is Empty.
>  
> Starting NpcBot system...
> >> Bot appearance data loaded
> >> Bot race data loaded
> >> Bots transmog data is not loaded. Table `characters_npcbot_transmog` is empty!
> >> Loaded 118 bot data entries


than it's closed

**Comment by trickerer** [comment]
In this case I don't think I will be able to help you, unless you manage to generate a proper debug crashlog.
Worst case: you'll have to debug it yourself or reinstall the bots

**Comment by drachai** [comment]
I've debugged build a few more times, but the server log is always the same.How can i reinstall Npcbot?

**Comment by trickerer** [comment]
characters: `DELETE FROM characters_npcbot;`
world: `DELETE FROM creature WHERE id1 BETWEEN 70001 AND 71000 AND id1 != 70100;`

**Comment by drachai** [comment]
Thanks for help, after reinstall server start
