### ISSUE TITLE
[AC] [Bug] [Core] GM command not dedicated to GM

### ISSUE THREAD

**Issue by iOITer** [trickerer/Trinity-Bots#306]
**Description:**

Anyone can use GM dedicated commands regardless account seurity level 

**AzerothCore:**

**Current behaviour:**

Any account (level 0~3)  can use GM dedicated commands such as ".npcb spawn, .npcb delete".

**Expected behaviour:**

Only GM with account security level 3 should be able to use GM dedicated commands.

**Steps to reproduce the problem:**

1. build  
2. run
3. test with a account with level 0 using .npcb spawn 70001 successfully

**TC / AC rev. hash/commit:** 

AzerothCore rev. 80e22ec30128 2022-12-24 12:51:03 +0700 (npcbots_3.3.5 branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon)

**Operating system:** Ubuntu 22.04

**Comment by trickerer** [comment]
https://github.com/trickerer/Trinity-Bots/commit/20c8c2892feaca0689a896e69de79c36410b7d74

**Comment by EvilCalf** [comment]
> [20c8c28](https://github.com/trickerer/Trinity-Bots/commit/20c8c2892feaca0689a896e69de79c36410b7d74)

emmm，this update make all the command delete from comand talbes.So that someone except GM cant use this...The security level could have been adjusted for control

**Comment by trickerer** [comment]
There are only a couple commands you may want to adjust security level for. You can add them yourself if you need to. The list was incomplete anyway.

**Comment by iOITer** [comment]
Thanks for the reply. I have found them in the database and just manually changed them.
