### ISSUE TITLE
[AC] [Bug] [Core] NpcBot.MaxBots = 39 You exceed max npcbots 1

### ISSUE THREAD

**Issue by Greyisttot** [trickerer/Trinity-Bots#309]
AzerothCore rev. 8b0bd347e15c+ 2022-12-29 10:05:50 +0700 (npcbots_3.3.5 branch) (Win64, Release, Static) (worldserver-daemon) ready...

I tested a maximum of 39 and 4 respectively, and both suggested that a maximum of 1 can only be recruited.

**Comment by trickerer** [comment]
Can't confirm. It seems like the config you're modifying is not the one used by your worldserver. Check Server.log for missing config param errors.

Hiring 5 bots with `NpcBot.MaxBots = 4`
![exceed](https://user-images.githubusercontent.com/1254989/210034687-a2abba59-225e-4296-b9ba-c7ce3b2a339d.jpg)

**Comment by Greyisttot** [comment]
> 无法确认。您正在修改的配置似乎不是您的世界服务器使用的配置。检查 Server.log 是否缺少配置参数错误。
> 
> 雇用 5 个机器人`NpcBot.MaxBots = 4` ![超出](https://user-images.githubusercontent.com/1254989/210034687-a2abba59-225e-4296-b9ba-c7ce3b2a339d.jpg)

Thank you, I have solved this problem, it should be caused by the worldserver.conf.dist configuration file not being updated
