### ISSUE TITLE
Add about npcbot color in group

### ISSUE THREAD

**Issue by 328950225** [trickerer/Trinity-Bots#31]
1.
src\server\shared\SharedDefines.h
..........
// valid classes for creature_template.unit_class
enum UnitClass
{
    UNIT_CLASS_WARRIOR                  = 1,
    UNIT_CLASS_PALADIN                  = 2,
    UNIT_CLASS_ROGUE                    = 4,
    UNIT_CLASS_MAGE                     = 8,
//npc bot start
    UNIT_CLASS_HUNTER = 3,
    UNIT_CLASS_PRIEST = 5,
    UNIT_CLASS_DEATH_KNIGHT = 6,
    UNIT_CLASS_SHAMAN = 7,
    UNIT_CLASS_WARLOCK = 9,
    UNIT_CLASS_DRUID = 11
    
};

//#define CLASSMASK_ALL_CREATURES ((1<<(UNIT_CLASS_WARRIOR-1)) | (1<<(UNIT_CLASS_PALADIN-1)) | (1<<(UNIT_CLASS_ROGUE-1)) | (1<<(UNIT_CLASS_MAGE-1)))
#define CLASSMASK_ALL_CREATURES ((1<<(UNIT_CLASS_WARRIOR-1)) | (1<<(UNIT_CLASS_HUNTER-1)) | (1<<(UNIT_CLASS_PRIEST-1)) | (1<<(UNIT_CLASS_DEATH_KNIGHT-1)) | (1<<(UNIT_CLASS_SHAMAN-1)) | (1<<(UNIT_CLASS_WARLOCK-1)) | (1<<(UNIT_CLASS_DRUID-1))| (1<<(UNIT_CLASS_PALADIN-1)) | (1<<(UNIT_CLASS_ROGUE-1)) | (1<<(UNIT_CLASS_MAGE-1)))
//npc bot end
.......................

2.on "creature_template" table
set your npcbot "unit_class" to the class ID, 
like this "UPDATE `creature_template` SET `unit_class`='6' WHERE (`entry`='70457')"

3,on "creature_classlevelstats" table
add the lost stats and level for the class  ,like this:
INSERT INTO `creature_classlevelstats` (`level`, `class`, `basehp0`, `basehp1`, `basehp2`, `basemana`, `basearmor`, `attackpower`, `rangedattackpower`, `damage_base`, `damage_exp1`, `damage_exp2`, `comment`) VALUES ('60', '11', '2442', '3984', '3984', '2434', '3748', '238', '24', '31.3842', '55', '55', '');
INSERT INTO `creature_classlevelstats` (`level`, `class`, `basehp0`, `basehp1`, `basehp2`, `basemana`, `basearmor`, `attackpower`, `rangedattackpower`, `damage_base`, `damage_exp1`, `damage_exp2`, `comment`) VALUES ('60', '6', '3052', '4979', '4979', '0', '3750', '252', '26', '33.9625', '53.4755', '53.4755', '');
Write the missing class ID in the class field
all class Level 1 to 80  need to write in.

Enjoy!

Please add this feature.

![QQ五笔截图未命名](https://user-images.githubusercontent.com/33200258/95858669-00837900-0d90-11eb-83b9-47681d6f1257.png)

**Comment by Parkan1986** [comment]
If this will work, it would be awesome.

**Comment by trickerer** [comment]
Thanks, I didn't believe this could work.

**Comment by qyh214** [comment]
seems well and cool!

**Comment by 328950225** [comment]
> Thanks, I didn't believe this could work.

[color _group_patch.zip](https://github.com/trickerer/Trinity-Bots/files/5377164/color._group_patch.zip)
This is the patch，Just need to recompile shared.dll after import patch.
![menghuanfg31](https://user-images.githubusercontent.com/33200258/95972795-74338d80-0e45-11eb-9776-f62033161676.jpg)
This is the result picture

**Comment by 328950225** [comment]
> Thanks, I didn't believe this could work.
[color _group_patch.zip](https://github.com/trickerer/Trinity-Bots/files/5377232/color._group_patch.zip)
This is the modified patch。
![QQ五笔截图未命名](https://user-images.githubusercontent.com/33200258/95973242-f91ea700-0e45-11eb-9269-0dccac147eeb.jpg)

**Comment by Parkan1986** [comment]
Tested.Working fine on current trinitycore for npcbots

**Comment by xtracripper** [comment]
I got horrible lag on my server after running the 2013/SQL/updates/world/2020_10_14_creature_classlevelstats.sql updates
Not sure if it's just my code version. But I ran below update to get better dummy values which fixed the lag:
```
UPDATE world.creature_classlevelstats ccls
INNER JOIN world.creature_classlevelstats ccls2 ON ccls2.level = ccls.level
SET
ccls.basehp0 = ccls2.basehp0,
ccls.basehp1 = ccls2.basehp1,
ccls.basehp2 = ccls2.basehp2,
ccls.basemana = ccls2.basemana,
ccls.basearmor = ccls2.basearmor,
ccls.attackpower = ccls2.attackpower,
ccls.rangedattackpower = ccls2.rangedattackpower,
ccls.damage_base = ccls2.damage_base,
ccls.damage_exp1 = ccls2.damage_exp1,
ccls.damage_exp2 = ccls2.damage_exp2
WHERE ccls.class in (3, 5, 6, 7, 9, 11)
AND ccls2.class = 1;
```
