### ISSUE TITLE
[AC] [Build Error] Autobalance

### ISSUE THREAD

**Issue by zaicopx** [trickerer/Trinity-Bots#311]
I got this error when finished build your latest AC + your Autobalance module

`15>E:\Compile Server\Projects\zaicopx-AzerothCore\AzerothCore-wotlk-with-NPCBots\modules\mod-autobalance\src\AutoBalance.cpp(454,10): error C3668: 'AutoBalance_UnitScript::ModifyPeriodicDamageAurasTick': method with override specifier 'override' did not override any base class methods`

`15>E:\Compile Server\Projects\zaicopx-AzerothCore\AzerothCore-wotlk-with-NPCBots\modules\mod-autobalance\src\AutoBalance.cpp(454,10): error C4263: 'void AutoBalance_UnitScript::ModifyPeriodicDamageAurasTick(Unit *,Unit *,uint32 &)': member function does not override any base class virtual member function`

`15>E:\Compile Server\Projects\zaicopx-AzerothCore\AzerothCore-wotlk-with-NPCBots\modules\mod-autobalance\src\AutoBalance.cpp(499,1): error C4264: 'void UnitScript::ModifyPeriodicDamageAurasTick(Unit *,Unit *,uint32 &,const SpellInfo *)': no override available for virtual member function from base 'UnitScript'; function is hidden`

`15>E:\Compile Server\Projects\zaicopx-AzerothCore\AzerothCore-wotlk-with-NPCBots\src\server\game\Scripting\ScriptMgr.h(427,18): message : see declaration of 'UnitScript::ModifyPeriodicDamageAurasTick'`

`15>E:\Compile Server\Projects\zaicopx-AzerothCore\AzerothCore-wotlk-with-NPCBots\src\server\game\Scripting\ScriptMgr.h(413,7): message : see declaration of 'UnitScript'`

**Comment by trickerer** [comment]
https://github.com/trickerer/mod-autobalance/commit/229de39f3923a356405176ae7ad9b025f470ec15
