### ISSUE TITLE
[AC] [Bug] [Spell] instance Slave Pens Bot AOE affects neutral NPC's resulting in aggro

### ISSUE THREAD

**Issue by Mr-Deadbeat** [trickerer/Trinity-Bots#312]
**Description:**

Naturalist Bite aggroes when fighting naga with bots their AOE seems to affect neutral NPC's
which results in him hitting the bots trying to kill them

**TrinityCore or AzerothCore:**

AzerothCore

**Current behaviour:**

when you speak to naturalist bite to let him out of the cage it spawns a group of naga which attacks the party
resulting in above described issue

**Expected behaviour:**

Naturalist bite should not attack the party when battling the naga

**Steps to reproduce the problem:**

fight your way to last boss in slave pens Quagmirran up on the left side in a cage you find Naturalist Bite
after freeing him he will bestow a buff to the party to more easily fight the last boss

**TC / AC rev. hash/commit:** 

AzerothCore rev. 089d5d92ad13 2022-12-31 08:49:16 +0700 (npcbots_3.3.5 branch) (Unix, Release, Static)

**Operating system:** CHANGEME OS

Ubuntu 20.04.6

**Comment by trickerer** [comment]
Related: #297

**Comment by trickerer** [comment]
Can't confirm. After Bite attacks spawned nagas and goes into AoE area (Consecration) he doesn't get damaged and doesn't aggro on the bots, properly returns to his spot.

**Comment by Mr-Deadbeat** [comment]
strange for me it happens every time and not only with Naturalist bite but other npc's as well during server bootup i have no db errors or nothing ? could this be due to db corruption by any chance ? i have noticed some small anomalies like shattered sun npc's in shattrath invisible standing in the center area only their weapons visible what could be causing this ? is there anyway of checking if the DB is intact during boot ? and having the correct data ?

i did activate the worldserver.conf options for database cleanup when i setup the server been using the same settings on trinitycore as well and never noticed these anomalies before until yesterday

**Comment by trickerer** [comment]
This can't be a DB related issue
You could check if you're able to reproduce #297 with your party. If yes then it would mean the fix wasn't comlete

**Comment by Mr-Deadbeat** [comment]
yeah i have the same thing happen to me as well on #297 and it's all AOE effects from bots paladin takes aggro and so does the hunter since he uses volley a lot on bigger groups of mobs paladin uses consecrate on all fights he is retribution specced

**Comment by Mr-Deadbeat** [comment]
atm it looks like the issue is resolved did a recompile from fresh clone and restarted all the hardware and added more ram as well to the VM and this time Naturalist Bite behaved can't test the #297 issue though since i have completed that quest already but i will keep it in mind when i get there with my other characters i will let this issue be active for the time being going to test the instance again after instance reset which will happen later did it in heroic mode since i'm grinding gear for raiding

**Comment by Mr-Deadbeat** [comment]
not been able to test again due to my gaming system having a fit new gpu causing me grief so waiting for a response from
Sapphire about a gpu bios i'll test the issue once i get the card fixed

**Comment by Mr-Deadbeat** [comment]
just tested it and it's still happening first Naturalist Bite was standing in the cage after i spoke to him and the naga's spawned during that fight he did not attack

went to speak to him again to get the buff and got the same "alright i'll let you out" and a new group of nagas attacked this time he came out from the cage but attacked warrior right after nagas feared the whole group

starting to think it's the event that is bugged Naturalist bite was green to me so could not attack him but he did attack the warrior bot so not sure what to think weird as hell also the slave NPC's they attack the bots as well but those are forced by the nagas if memory serves me right on those i use distance 0 to recall the bots once the nagas are dead but sometimes they kill the occasional slave worker these are Yellow colored so neutral

**Comment by Mr-Deadbeat** [comment]
sorry for leaving this hanging have had other issues to deal with so forgot this entirely going to run another test run after dinner and then close this issue must be a edge case affecting only me if it's still there did build new binaries today

**Comment by Mr-Deadbeat** [comment]
this time the naturalist bite behaved not as expected though but he did not attack the bots also he never came out of the cage until he got feared once he returned to the fight he did not engage the bots so i would call it sorted for the time being
also he gave me the buff once i spoke to him so i would call that a win ;) closing this issue
