### ISSUE TITLE
[TC] [Bug] [Group/Spell/Core] Restro Shaman Bots don't use earthshield on tanks in 5 man groups.

### ISSUE THREAD

**Issue by Codewow** [trickerer/Trinity-Bots#314]
Shamans will only earthshield the main tank in a raid group and doesn't use it in 5 man groups.

**TrinityCore or AzerothCore:** 

TrinityCore

**Current behaviour:**

 Shaman doesn't apply spell

**Expected behaviour:**

Shamans add earth shield to player tanks. 

**Steps to reproduce the problem:**

1. Join a group with a resto shaman bot and other bots to queue for a dungeon (level 80 to make sure bot has the ability)
2. Notice shaman doesn't apply earth shield if main tank is a player.

**TC / AC rev. hash/commit:** 

TrinityCore rev. d05d3cf1ff06 2022-12-28 16:44:45 +0700 (npcbots_3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

**Operating system:** 

Windows 10

**Comment by trickerer** [comment]
Unfortunatelly there is no way to fix this for normal non-lfg group, which sucks if you wish to tank through a dungeon normally

**Comment by Codewow** [comment]
> Unfortunatelly there is no way to fix this for normal non-lfg group, which sucks if you wish to tank through a dungeon normally

Would a potential workaround be to check if any bots in the group are marked to tank/offtank, if not default to giving the player the tank flag regardless of class? That way they can actually use the spell even if it's not on the most effective target of the 5 man group? Then in raids either a bot tank or a player marked as main tank would get the shield instead.

**Comment by trickerer** [comment]
For that it needs to be extracted from BuffTarget() to a separate function.
