### ISSUE TITLE
[TC] [AC] [Enhancement] [Core] NPCBOT hired bots parked location

### ISSUE THREAD

**Issue by Logandros** [trickerer/Trinity-Bots#315]
**Description:**

Gearing / owning bots

I like the idea of keeping the same bots, gearing them and using NPCBOTS in a more personal manner. I'd love to see their parked location expanded upon. I understand ownership versus spawn points, however would it be possible to make a change to the code or use an additional DB entry to keep the bots that are owned at a location? The idea behind this is, as I'm working on gearing some of my bots and having a more personal experience with them, as my group size grows, it becomes an obstacle to other players when I hearth or teleport to a new location, specifically a confined Inn and my army of hired bots zone in with me. They will stay at the hearth location because I have them commanded to stay and do nothing but the inn then becomes very crowded and it makes it difficult for other players to interact with Inn NPCs. The only way around this as I understand it is to use .npc remove so that they retain their gear but players do not have access to that feature as it is a GM command as I understand it. I would just love to see this are expanded upon if possible, I think it would make for a better end user ownership of their hires.

**TrinityCore or AzerothCore:**
Both

**Current behaviour:**

An army of hired bots that are not being can over crowd a location upon hearthing or being summoned, ported.

If this is a crash, post the crashlog (upload to https://gist.github.com/).

**Expected behaviour:**

Be able to set a parked location for hired bots that do not follow you when you hearth, teleport, or receive a summons.

**Steps to reproduce the problem:**

1. Hire a bunch of bots for use
2. Ask them to stay and do nothing
3. Hearth, teleport, or accept a summons

**TC / AC rev. hash/commit:** 

TrinityCore rev. 734fd9d5b3f9+ 2022-12-06 01:16:04 +0000 (master branch) (Win64, Release, Static) (worldserver-daemon) ready...

**Operating system:** Windows 11

**Comment by Logandros** [comment]
This sounds perfect but I can't figure out the syntax. I've tried .npcbot unbind and it doesn't seem like a valid command. When was this implemented? I used NPCBots.patch back on 12/24 and I have been manually patching since. Did I overlook a patch?

I've tried it every possible way so I think I just missed a commit (going back to look now starting from 12/24).

**Comment by trickerer** [comment]
Maybe you just overlook the syntax since it's under `command` subcommand, this isn't exactly convenient.
- `.npcbot command unbind [TARGET | NAME]`
- `.npcbot command rebind [TARGET | NAME]`

**Comment by Logandros** [comment]
After about 15 minutes of going through code I went back and reread, I was missing command! This works perfectly, excellent feature that I just overlooked, thank you as always! I'm just glad I didn't miss any merges, I try to keep up nightly so I would have been annoyed if I forgot to import an sql  ... cheers!

**Comment by EvilCalf** [comment]
> 
‘.npcbot command rebind [TARGET | NAME]’
i used ‘.npcbot command rebind [Stacy]’
![image](https://user-images.githubusercontent.com/35754619/211520477-c684b011-56a4-457e-a9ba-398f0703f9f0.png)

![image](https://user-images.githubusercontent.com/35754619/211520195-aabe19fe-c698-4d67-9cfa-1b607100e54a.png)

**Comment by trickerer** [comment]
@EvilCalf
Square brackets mean this argument is optional. Names are case-insensitive. I need a way to reproduce the issue - in a separate issue. Maybe you had an error show up on the first time you tried to re-bind the bot?

**Comment by EvilCalf** [comment]
> @EvilCalf Square brackets mean this argument is optional. Names are case-insensitive. I need a way to reproduce the issue - in a separate issue. Maybe you had an error show up on the first time you tried to re-bind the bot?

Yes, i know this argument is optional. So i use name, because i cant find the npcbot.I always restart the server to solve the unbound bot.

**Comment by Logandros** [comment]
Also I believe you need to have yourself targeted when using rebind with the [name] argument iirc.

**Comment by Logandros** [comment]
> 

I was incorrect, you do not need to target yourself to use the rebind command with [name], not sure why you are having errors
