### ISSUE TITLE
.server info message spam.

### ISSUE THREAD

**Issue by NetherstormX** [trickerer/Trinity-Bots#316]
I see this message in below while playing every few minutes in chat. "TrinityCore rev. 1e1de84cd097 + 2022-10-21 21:40:59 +0000 (npcbots_3.3.5 branch) (Unix, RelWithDebInfo, Static) "   Looks like ".server info" command message. 

![Screenshot](https://i.ibb.co/LSdpHY7/Screenshot-2022-12-31-133651.png)
https://ibb.co/ZdzT7GD

Is there a way to stop it or increase the time so it spams less?
i couldn't find anything related to this .conf files.

**Comment by trickerer** [comment]
No idea. This isn't `.server info` command output. The only related conf option is `Server.LoginInfo` but it doesn't cause this issue.
What custom changes do you have?

**Comment by NetherstormX** [comment]
Hmmm. I don't think i have any custom configurations except some number tweaks made on drop rates and stuff and activated Raid for npcbots.
Here's the worldserver.conf
[worldserver.txt](https://github.com/trickerer/Trinity-Bots/files/10377679/worldserver.txt)

And also with ".server info" i get that output ingame, also tried it in worldserver cli.
https://ibb.co/Fb9z8WB

For server installation i used the pre-patched repository that is linked in the manual and followed that guide. I didn't install any custom scripts or anything else.

**Comment by NetherstormX** [comment]
Hmmm. I don't think i have any custom configurations except some number tweaks made on drop rates and stuff and activated Raid for npcbots.
Here's the worldserver.conf
[worldserver.txt](https://github.com/trickerer/Trinity-Bots/files/10377741/worldserver.txt)


And also with ".server info" i get that output ingame, also tried it in worldserver cli.
https://ibb.co/Fb9z8WB

For server installation i used the pre-patched repository that is linked in the manual and followed that guide. I didn't install any custom scripts or anything else.

**Comment by trickerer** [comment]
> nd also with ".server info" i get that output ingame, also tried it in worldserver cli.

`.server info` shows number of online players and other info, the spam you get does not.

> Hmmm. I don't think i have any custom configurations except some number tweaks made on drop rates and stuff and activated Raid for npcbots.

I mean core modifications. Your revision clearly states TrinityCore "1e1de84cd097_**+**_" which means there is some extra stuff. The referred commit is [here](https://github.com/trickerer/TrinityCore-3.3.5-with-NPCBots/commit/1e1de84cd097)

If you're not sure you can search whole `src` folder for string `GetFullVersion()` and post those occasions here. For example:
```
CharacterHandler.cpp:L774
World.cpp:L2114
```

**Comment by htc16** [comment]
Are you using trinity admin addon? Because it does it automatically and directly in the addon.

**Comment by trickerer** [comment]
> Here is the string search output:
> ```
> ...
> ```

Hm, nothing special there

> I didn't do any core modifications, i just followed the guide and used a pre-patched core which is referenced in the manual.

If there were no core modifications revision would be `1e1de84cd097`, not `1e1de84cd097+`. Try `git status` or open your repository in Git Extensions to see what is going on.

**Comment by NetherstormX** [comment]
> Are you using trinity admin addon? Because it does it automatically and directly in the addon.

Thank you very much, this was the spamming problem. I never thought that the addon could be doing that.

**Comment by NetherstormX** [comment]
> > Here is the string search output:
> > ```
> > ...
> > ```
> 
> Hm, nothing special there
> 
> > I didn't do any core modifications, i just followed the guide and used a pre-patched core which is referenced in the manual.
> 
> If there were no core modifications revision would be `1e1de84cd097`, not `1e1de84cd097+`. Try `git status` or open your repository in Git Extensions to see what is going on.

@trickerer 
Resolved. The spamming problem i caused by TrinityAdmin Clientside addon thnx to @htc16.
Still don't know why the .server info shows that as server information but it looks another problem with the revision that i use. Will try to investigate it further.

Thanks for all your help and support. Your Awesome!.
