### ISSUE TITLE
[AC][TC][Feature Request] Return to Last Sendto

### ISSUE THREAD

**Issue by Day36512** [trickerer/Trinity-Bots#318]
Hey Trickerer,

I was wondering if perhaps it would be possible to implement a feature where you can have bots return to the last sendto location. This would be very useful on fights where alternating stacking and spreading is necessary, or if you are having bots move to two main locations for two different phases and would like a simple macro to execute such movements. Not sure how difficult this would be to implement and if it would require a cache system of previous saved locaitons, but if it isn't too much trouble I would love this as a feature.

**Comment by Day36512** [comment]
Very cool and extremely quick. Man I hope I can be that quick some day. 

I made a short video testing it out and had a couple thoughts: https://youtu.be/EhLcbFVQX0s

**Comment by Day36512** [comment]
Sorry, last comment for the night. I used C'thun as an example in my video. I forgot that it's unlikely the boss targets bots with his lightning, making it a bit of a moot point. Still, great feature. Would love if they could move back to the smokeflares but not sure what sort of work that would involve.

**Comment by trickerer** [comment]
There are two ways to go about this problem.

One is to only use `.npcbot sendto` command once. When bots assume positions order them to follow. This way `.npcbot sendto last` will move bots to their initial statonery position. But in this scenario every `.npcbot sendto last` command must be followed by `.npcbot command follow` so their last position is always the same.

Another way is to add two new commands like this:
- `.npcbot sendto point <NUMBER> <NAMES...>`
- `.npcbot sendto point set <NUMBER> <NAMES...>`

This will allow to set (multiple if needed) station points to be used later on.

**Comment by trickerer** [comment]
https://github.com/trickerer/Trinity-Bots/commit/7f72b86e2bf61e549a7b4e30d292ab8fa9c484e4

**Comment by Day36512** [comment]
Always better results than anticipated. Thanks again Trickerer. Works fantastically.
