### ISSUE TITLE
[AC]look this error stats

### ISSUE THREAD

**Issue by zbhcn** [trickerer/Trinity-Bots#325]
![image](https://user-images.githubusercontent.com/116956612/212701136-624cb287-4ca5-48e7-b917-fa5bba428e74.png)
This is the January 16th version，there is no problem with The version on January 11

This error message appears when the user login

**Comment by trickerer** [comment]
Why do you think this is related to NPCBots? Have you tried to reproduce it on clean core?

**Comment by zbhcn** [comment]
> 
哈哈，你居然会用中文回复啊。牛逼。是受不了机器人翻译的折磨了吗？
好的，我马上试试你的建议。

**Comment by zbhcn** [comment]
You are right. The problem disappeared after I recompiled. Thank you very much. Please delete my post.
