### ISSUE TITLE
[TC] [Bug] [Core] Missing Bots After Dropping/Recreating World Database

### ISSUE THREAD

**Issue by infidelus** [trickerer/Trinity-Bots#326]
**Description:**

I recently had to drop the world database as advised by the TC devs to fix an issue.  Every time I now build TC I get errors when I start worldserver telling me the bots I've spawned don't exist in the creatures table.

**TrinityCore:**

**Current behaviour:**

Spawned bots missing when logging in to WotLK

**Expected behaviour:**

Bots should load when I login

**Steps to reproduce the problem:**

1. Git pull the latest version of TC, cd to TC directory and grab the NPCBots.patch (wget https://raw.githubusercontent.com/trickerer/Trinity-Bots/master/NPCBots.patch)

2. apply the patch
> patch -p1 < NPCBots.patch

Then continue with the build:

> mkdir build && cd build
> cmake ../ -DCMAKE_INSTALL_PREFIX=/home/$USER/server
> make -j $(nproc) install

4. Grab the latest TC release and save it to the server/bin folder

4. From the TrinityCore/sql/Bots folder run merge_sqls_world_unix.sh to get the world sql files and apply them to the world database

5. Start worldserver.  Just before the server finishes loading, the following is shown in the terminal:

> Cannot spawn npcbot Kerra (id: 70038), not found in `creature` table!
> Cannot spawn npcbot Oninath (id: 70134), not found in `creature` table!
> Cannot spawn npcbot Arena (id: 70231), not found in `creature` table!
> Cannot spawn npcbot Aldrae (id: 70234), not found in `creature` table!
> Cannot spawn npcbot Haromm (id: 70251), not found in `creature` table!
> Cannot spawn npcbot Talionia (id: 70375), not found in `creature` table!

**TC / AC rev. hash/commit:** 

TrinityCore rev. 80884e32ef6e+ 2023-01-16 11:10:56 +0000 (3.3.5 branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon)

**Operating system:** Ubuntu 22.04

**Comment by trickerer** [comment]
By dropping world DB you deleted all non-default spawns in the world, including all bots you previously spawned. You can't do that and expect a big mod like this to continue to work as if nothing happened.

You should've made a backup before **dropping an entire database**.
But since you didn't, you have only 4 options:
1. Try to re-spawn those bots in new locations using `.npc add` command (probably won't work)
2. Copy existing records in `creature` table with `id` value changed to creature entries of those missing bots (70038 and so on) and then use `.npcbot move` to move them to desired locations
3. If none of the bots had any gear try `.npcbot delete` options from the console
4. As a last resort: empty `characters_npcbot` table. This will create dangling `item_instance` records

**Comment by infidelus** [comment]
Thanks for the reply.  I was under the impression (clearly incorrectly) that the world database was basically static and the auth and characters databases held any and all changes.

>You should've made a backup before dropping an entire database.
>But since you didn't, you have only 4 options:

As it happens I did make a backup before dropping it so have been able to restore it, but the world database is corrupted and causing problems with quests & duplicate spawns, hence the advice from the TC team to drop it and create a fresh DB with the latest release.

I am not an SQL expert unfortunately, but if you have a template query I can use to apply to one, I'm sure I can run it for the rest of the bots.

**Comment by trickerer** [comment]
Allright.
There is no template query to automatically restore `creature` table records so you have to do it manually.
Basically all you need to do after you apply back all of NPCBots `world` SQLs is to look at your backed up `creature` table and restore records with `id`s 70001-71000, from what you've shown there aren't many of them so this should be fairly easy to do.
Or you can just copy existing records and paste them with some different `guid` and one of the missing `id`s and then move bots to their original locations (option 2). If your SQL app doesn't support paste with modifications you can typically paste to a text editor, modify what you need and copy a modified line

**Comment by trickerer** [comment]
Here. You can try with this query. You still need to move bots afterwards. Use `.npcbot list` to see spawned bots
```
INSERT INTO world.creature (id, position_x, position_y, position_z) (SELECT entry,-9056,152,3.159 FROM characters.characters_npcbot WHERE entry NOT IN (SELECT id FROM world.creature));

```

**Comment by infidelus** [comment]
Thanks again.  I tried dropping the world database again this afternoon and doing a fresh TrinityCore pull and my bots are all there, without me having to do anything.  I'm starting to doubt that I dropped the database now so will have another go tomorrow and see what happens and try your SQL query if necessary.

**Comment by infidelus** [comment]
OK, I (definitely) dropped the world DB today and pulled the latest git and after applying all the updates and running your INSERT query the bots are all there again.  Thanks for the help, much appreciated.
