### ISSUE TITLE
[AC] [Bug] [Sendto] Holy Paladin Prioritizing Casting, Ignores Sendto

### ISSUE THREAD

**Issue by Day36512** [trickerer/Trinity-Bots#329]
**Description:**

Tested with a Holy Paladin,but may apply to other casters/healers. Using Sendto location while they were mid cast fails to prioritize the sendto function. Bot does not execute sendto command midway or after finished casting.

**Expected behaviour:**

Healer should cancel current action and move to specified location or finish casting and move after, not ignore command entirely.

**Steps to Reproduce**

Get smacked a lot by a mob, have a paladin healing you. Target said bot and use sendto via the following macro while they're mid cast (you'll need white smoke flares):
.npcbot sendto
/use white smoke flare

OS Windows

**Comment by trickerer** [comment]
On TC this works no problem. Hm.

The only thing comes to mind I can do without making it much different from TC version is to interrupt current spell being cast.

**Comment by Day36512** [comment]
I'm good with whatever you could manage. There's a big benefit to just interrupting the cast in critical situations.
