### ISSUE TITLE
[Suggest] Compiled version

### ISSUE THREAD

**Issue by Mitradis** [trickerer/Trinity-Bots#330]
Есть возможность выкладывать хотя бы раз в месяц в раздел Релизы гита готовые скомпилированные версии? Это расширило охват пользователей. Не все хотят ставить кучу всякого (для них) хлама только ради того чтобы скомпилирвоать сервер. Ну вот мне например совсем не нужны 20 лишних гб студии для этого. Хотя побегать я люблю. Пока пользуюсь готовыми репаками с других форумов и сайтов, хотя там много ненужного хлама. Как по мне серверу нужны только боты, все прочее уже ломает игру.

**Comment by trickerer** [comment]
Для TC можно скачивать экзешники из результатов автосборки appveyor (artifacts). [Например](https://ci.appveyor.com/project/trickerer/trinitycore-3-3-5-with-npcbots/builds/46007802/artifacts).

С AC пока проблема. Когда-нибудь настрою.

Репаков не будет.

**Comment by trickerer** [comment]
Добавил автобилд для АС. [Здесь](https://ci.appveyor.com/project/trickerer/azerothcore-npcbots)

**Comment by trickerer** [comment]
Ещё кое-что: https://github.com/trickerer/Trinity-Bots/issues/208
