### ISSUE TITLE
Can't compile the server with autobalance mod

### ISSUE THREAD

**Issue by deadcorpseeater** [trickerer/Trinity-Bots#331]
Не могу скомпилировать сервер с модом автобаланс.

Серьезность	Код	Описание	Проект	Файл	Строка	Состояние подавления
Ошибка	C3668	AutoBalance_UnitScript::ModifyPeriodicDamageAurasTick: метод со спецификатором переопределения "override" не переопределяет какие-либо методы базового класса	modules	D:\ACNPCBOTS\modules\mod-autobalance\src\AutoBalance.cpp	454	
Ошибка	C4263	void AutoBalance_UnitScript::ModifyPeriodicDamageAurasTick(Unit *,Unit *,uint32 &): функция-член не переопределяет ни одной виртуальной функции-члена базового класса	modules	D:\ACNPCBOTS\modules\mod-autobalance\src\AutoBalance.cpp	454	
Ошибка	C4264	void UnitScript::ModifyPeriodicDamageAurasTick(Unit *,Unit *,uint32 &,const SpellInfo *): нет доступного переопределения для виртуальной функции-члена из базового класса "UnitScript"; функция скрыта	modules	D:\ACNPCBOTS\modules\mod-autobalance\src\AutoBalance.cpp	498	
Ошибка	C3668	AutoBalance_UnitScript::ModifySpellDamageTaken: метод со спецификатором переопределения "override" не переопределяет какие-либо методы базового класса	modules	D:\ACNPCBOTS\modules\mod-autobalance\src\AutoBalance.cpp	459	
Ошибка	C4263	void AutoBalance_UnitScript::ModifySpellDamageTaken(Unit *,Unit *,int32 &): функция-член не переопределяет ни одной виртуальной функции-члена базового класса	modules	D:\ACNPCBOTS\modules\mod-autobalance\src\AutoBalance.cpp	459	
Ошибка	C4264	void UnitScript::ModifySpellDamageTaken(Unit *,Unit *,int32 &,const SpellInfo *): нет доступного переопределения для виртуальной функции-члена из базового класса "UnitScript"; функция скрыта	modules	D:\ACNPCBOTS\modules\mod-autobalance\src\AutoBalance.cpp	498	
Ошибка	C3668	AutoBalance_UnitScript::ModifyHealRecieved: метод со спецификатором переопределения "override" не переопределяет какие-либо методы базового класса	modules	D:\ACNPCBOTS\modules\mod-autobalance\src\AutoBalance.cpp	469	
Ошибка	LNK1181	не удается открыть входной файл "..\..\..\modules\RelWithDebInfo\modules.lib"	worldserver	D:\Build\src\server\apps\LINK	1	

Все делал по АК вики, оригинальный ак с их модами компилится без проблем.

Изначальное название папки с модом было:
![image](https://user-images.githubusercontent.com/123157768/213965292-a8e4eba5-349a-4cba-b0a7-89cbb4a41e08.png)

Изменил на это:
![image](https://user-images.githubusercontent.com/123157768/213965336-639c44cf-1ac8-4a2b-919f-808d04badca6.png)

**Comment by trickerer** [comment]
Изменения в этих методах - недавние. Какая ревизия AC используется? Попробуй самую последнюю.

Для справки история изменений релевантного файла: https://github.com/azerothcore/azerothcore-wotlk/commits/master/src/server/game/Scripting/ScriptMgr.h

**Comment by deadcorpseeater** [comment]
> Изменения в этих методах - недавние. Какая ревизия AC используется? Попробуй самую последнюю.
> 
> Для справки история изменений релевантного файла: https://github.com/azerothcore/azerothcore-wotlk/commits/master/src/server/game/Scripting/ScriptMgr.h

вот эту я брал https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots

**Comment by trickerer** [comment]
Ты использовал старую версию автобаланса (от 10 Октября). Скорее всего потому что загрузил мастер ветку. Поскольку этот мод только для ботов, обновляется только ветка для ботов (она же является веткой по умолчанию для этого репозитория)

```
git clone -b npcbots_3.3.5 https://github.com/trickerer/mod-autobalance.git
```

**Comment by deadcorpseeater** [comment]
> Ты использовал старую версию автобаланса (от 10 Октября). Скорее всего потому что загрузил мастер ветку. Поскольку этот мод только для ботов, обновляется только ветка для ботов (она же является веткой по умолчанию для этого репозитория)
> 
> ```
> git clone -b npcbots_3.3.5 https://github.com/trickerer/mod-autobalance.git
> ```

слушай, а что здесь использовать, чтобы подобную команду ввести? а то когда вики читаешь, подобных вариантов нет
![image](https://user-images.githubusercontent.com/123157768/214066490-cfee5a44-b4d1-4ccc-bb49-74fb79e84b07.png)

**Comment by deadcorpseeater** [comment]
> Ты использовал старую версию автобаланса (от 10 Октября). Скорее всего потому что загрузил мастер ветку. Поскольку этот мод только для ботов, обновляется только ветка для ботов (она же является веткой по умолчанию для этого репозитория)
> 
> ```
> git clone -b npcbots_3.3.5 https://github.com/trickerer/mod-autobalance.git
> ```

то есть по сути я должен поставить твой мод поверх оригинального или как?

**Comment by trickerer** [comment]
> то есть по сути я должен поставить твой мод поверх оригинального или как?

Никак нет.

Заходишь в ту папку, где у тебя лежат модули,
![folder](https://user-images.githubusercontent.com/1254989/214198867-66b59e00-66c6-459f-9828-ee6184f781e5.png)
удаляешь старый `mod-autobalance`, затем правый клик -> `Git Bash Here`. Туда и вводишь команду на клонирование.
В принципе можно и просто загрузить модуль в архиве (или что там вики предалагает), просто нужно использовать ветку ботов. Текущая последняя ревизия там - https://github.com/trickerer/mod-autobalance/commit/3f49f299fc5375a7a918fda95d5e68511cf079e7

**Comment by Logandros** [comment]
I noticed an issues with this as well. Although it compiles. If you have unbound bots, it seems you need to debug, reset them in order to get them back and you will need to do this each time the server restarts. I don't know if this is a GM only issue because I do see this spammed upon login:
Not available in GM mode (multiple times)

Normally upon server restart, all owned bots will rebind. This does not happen when compiling with autobalnce, instead the bots are listed as owned but you get an error message. 'Must target your unbound npcbot. I wonder if autobalance is the partial cause in this users issue as well listed [here](https://github.com/trickerer/Trinity-Bots/issues/324) just a thought trickerer.

**Comment by Logandros** [comment]
I might be mistaken, it may not be an issue with autobalance, it may be another module. Testing now...

**Comment by Logandros** [comment]
Nope, somehow I turned on GM mode, I'm not even sure how I did that. Turning it fixed everything ... odd.

**Comment by trickerer** [comment]
@Logandros
This issue is not about an in-game problem.

As for rebind - could you please post a list of modules (possible culprits) in #324?

Also, bots do not unbind from or re-bind to owner at logout/login. Unbind is a bot state managed through commands only.

**Comment by Logandros** [comment]
Sorry, I may not have been clear, my issue was I had GM Mode set to ON. As soon as I set it to off, all my bots worked as expected. If you have all your bots unbind, after a server restart they will bind. This was not happening, I thought it was a module but it was because I had GM Mode on.

**Comment by deadcorpseeater** [comment]
> > то есть по сути я должен поставить твой мод поверх оригинального или как?
> 
> Никак нет.
> 
> Заходишь в ту папку, где у тебя лежат модули, ![folder](https://user-images.githubusercontent.com/1254989/214198867-66b59e00-66c6-459f-9828-ee6184f781e5.png) удаляешь старый `mod-autobalance`, затем правый клик -> `Git Bash Here`. Туда и вводишь команду на клонирование. В принципе можно и просто загрузить модуль в архиве (или что там вики предалагает), просто нужно использовать ветку ботов. Текущая последняя ревизия там - [trickerer/mod-autobalance@3f49f29](https://github.com/trickerer/mod-autobalance/commit/3f49f299fc5375a7a918fda95d5e68511cf079e7)

пардон, что исчезал на столь долгий срок. а что такое ветка вообще? ну вот чайник я в этом))

итак подытожим, я просто удаляю оригинальный модуль автобота, затем в папку модулей клонирую твой модуль, верно? просто ситуация была такая, что я твой модуль скачал, а у папки название странное - оригинальные с сайта азероткора называются мод-название-мастер, а у тебя мод-название-числовое_значение, которое мне непонятно. его нужно удалять, чтобы осталось только мод-название, или оставлять все как есть?

ЗЫ - сменил комп, сейчас с нуля все буду качать и компилить.
еще есть один оффтоп вопрос, на который, я думаю, не смогу найти ответ, но надеюсь, что ты найдешь время ответить - если я все удачно скомпилирую, то могу я папку с ревизией кинуть на другой комп, чтобы использовать сервер? мне же достаточно будет на том компе просто майэсквель поставить и туда базу вкачать через ворлдсерер.ехе? просто дело в том, что я по большей части в АСсоло играю на своем ноуте на работе в свободное время, а он древнючий, что капец. не думаю, что он в состоянии нормально все скомпилировать и не умереть (или напортачить), а репаки вот на нем нормально идут.

**Comment by trickerer** [comment]
Оригинальный модуль ты скачал сам. Два одинаковых модуля поставить нельзя, логично?

Как я уже говорил, в папке с модулям ПКМ->Git Bash Here. Комманда для клонирования: `git clone -b npcbots_3.3.5 https://github.com/trickerer/mod-autobalance.git`
Папка модуля должна именоваться `mod-autobalance` - по аналогии с другими.

Перенести на другую машину можно при условии сохранения структуры папок (зависит от конфига), а также наличия необходимых сервисов и библиотек. Про сервер БД ты уже сам ответил, от себя добавлю что нужно не забыть вместе с экзешниками сервера перенести .dll файлы libmysql, libssl и libcrypto

**Comment by deadcorpseeater** [comment]
> Оригинальный модуль ты скачал сам. Два одинаковых модуля поставить нельзя, логично?
> 
> Как я уже говорил, в папке с модулям ПКМ->Git Bash Here. Комманда для клонирования: `git clone -b npcbots_3.3.5 https://github.com/trickerer/mod-autobalance.git` Папка модуля должна именоваться `mod-autobalance` - по аналогии с другими.
> 
> Перенести на другую машину можно при условии сохранения структуры папок (зависит от конфига), а также наличия необходимых сервисов и библиотек. Про сервер БД ты уже сам ответил, от себя добавлю что нужно не забыть вместе с экзешниками сервера перенести .dll файлы libmysql, libssl и libcrypto

логично. просто поскольку я не разобрался с тем, как устроен гит, что такое бранчи и форки, у меня очень расплывчатое представление о том, как это работает. я представлял, что твой репозиторий ставится поверх основного модуля и заменяет уже существующие файл плюс добавляет новые.

можно узнать зачем в этой команде -b? смотрю, через гит баш все быстрее делается, думаю, так удобнее было бы клонировать репозитории

**Comment by deadcorpseeater** [comment]
почему? 

[1146] Table 'acore_world.custom_quest_xp' doesn't exist
Your database structure is not up to date. Please make sure you've executed all queries in the sql/updates folders.
[1146] Table 'acore_world.custom_quest_xp' doesn't exist
Your database structure is not up to date. Please make sure you've executed all queries in the sql/updates folders.

**Comment by trickerer** [comment]
> почему?

Никакого отношения к автобалансу или ботам эти ошибки не имеют. Смотри другие свои модули.
