### ISSUE TITLE
[AC] [Crash] [Core] Missing something on coversion

### ISSUE THREAD

**Issue by Logandros** [trickerer/Trinity-Bots#332]
**Description:**

I was hoping you could help although I'm sure this is outside the realm of support. I tried to bring my data over from TrinityCore to AzerothCore and everything went pretty well with one exception. I forgot I have 1 custom bot that I made and I cannot remember all the areas in the DB that I need to grab her data from. It looks like I'm missing a section when world tries to spawn her. Before I delete her I was hoping for some advice

**TrinityCore and AzerothCore:**

**Current behaviour:**

World crashes on load due to missing sql data
```
Starting NpcBot system...
>> Bot spellInfo overrides generated for 44 spells
>> Bot appearance data loaded
>> Bot race data loaded
>> Bot transmog data loaded
>> Loaded 38 bot data entries
```

https://gist.github.com/Logandros/086ebeea649fa6e95e5cfc351dfd8351

**Expected behaviour:**

Should be able to load the custom bot that I created

**Steps to reproduce the problem:**

1. Start world server

**TC / AC rev. hash/commit:** 

AzerothCore rev. 79b8aa97b688+ 2023-01-23 19:01:04 +0000 (master branch) (Win64, Release, Static) (worldserver-daemon)

**Operating system:** Windows [11]

**Comment by trickerer** [comment]
https://github.com/trickerer/Trinity-Bots/blob/master/README.md#database

You need to transfer data from world DB tables, except `npc_text` and `creature_template_outfits`

**Comment by Logandros** [comment]
Thank you, `creature_equip_template` was the one I missed
