### ISSUE TITLE
[AC] [Crash] [Core] server crash

### ISSUE THREAD

**Issue by EvilCalf** [trickerer/Trinity-Bots#333]
[gdb.txt](https://github.com/trickerer/Trinity-Bots/files/10491351/gdb.txt)

**Comment by trickerer** [comment]
What bots were used besides druid?
Also, are you using RelWithDebInfo build? Half of the locals are optimized out.

**Comment by EvilCalf** [comment]
I am using RelWithDebInfo build.
![image](https://user-images.githubusercontent.com/35754619/214493890-9c1287b5-f918-44c8-9e8f-1568f8351665.png)
And my gdb.conf as follows:
`set logging on
set debug timestamp
run -c ../etc/worldserver.conf
bt
bt full
info thread
thread apply all backtrace full`
I start the world server by using `gdb -x gdb.conf --batch ./worldserver`

I dont know why occured so much optimized out.

Thank you for helping me for many times.

**Comment by trickerer** [comment]
> I am using RelWithDebInfo build.

You missed my main question.
> What bots were used besides druid?

This time RelWithDebInfo crashlog isn't enough. I have no idea how to reproduce this one
