### ISSUE TITLE
[enhancement] Unbind ignore combat state

### ISSUE THREAD

**Issue by Logandros** [trickerer/Trinity-Bots#334]
**Description:**

You might want to consider adding this. I noticed that if I unbind a bot while in combat, they will persist. I was using a training dummy and hit unbind. Because the bot is in combat it will keep attacking. The only way to stop the bot is to rebind, get out of combat then you can unbind. Maybe a change would be better that unbind will also cancel combat? Just a suggestion.

**TrinityCore or AzerothCore:**

**Current behaviour:**

Bot stays in combat after unbind. They will get very tired and hungry!  :)
If this is a crash, post the crashlog (upload to https://gist.github.com/).

**Expected behaviour:**

Not expected, suggested. Bot should unbind and return to spawn point and ignore combat state.

**Steps to reproduce the problem:**

1. attack a training dummy with a bot
2. unbind bot
3. watch them fight for eternity
**TC / AC rev. hash/commit:** 

AzerothCore rev. 3d631a3e57fc 2023-01-28 06:18:17 -0500 (master branch) (Win64, Release, Static) (worldserver-daemon)

**Operating system:** Windows 10

**Comment by Logandros** [comment]
Just curious, when you update via patch, do you just reapply the .patch file on top of previous patch? I've never used patch before until AzerothCore.

TY

**Comment by trickerer** [comment]
No you can't just apply any patch on top of its previous version

Best way to update via patch is to use `git reset --hard` to revision before patch, then apply new patch. The disadvantage of re-applying a patch is that you'll have to re-build everything

**Comment by Logandros** [comment]
Not sure how that would work with AC since I've done many updates over the last few weeks. I will just manually patch using diff like I've always done with TC. Have you ever considered making NPCBots to use the AC module system? As always thanks for your work and thank you for adding this enhancement.

**Comment by trickerer** [comment]
Just like playerbots "module" - this mod **requires** core patching. To convert it to a module dozens of new hooks would be needed - hooks that only bots will use. And even after that, adding some new feature will be a nightmare.

**Comment by Logandros** [comment]
Understood, makes sense.
