### ISSUE TITLE
 [Suggest]  Error when applying sql files

### ISSUE THREAD

**Issue by vmornf** [trickerer/Trinity-Bots#337]
Hi,

Could you explain how to "Apply SQL files from /TrinityCore/sql/Bots/"? I have tried to source the all sql files but I'm getting some errors.

I might be doing it wrong though. Could you explain the commands needed from Step 6 and 7? I have compiled TrinityCore with the patch already.

Cheers.

**Comment by trickerer** [comment]
There aren't any commands to SQL files needed. All you need to do is to apply SQL files one by one to its DB. Files starting with 'characters' go to `characters` DB, etc. First - the 6 files listed in step 6, then all files from `updates` subfolders. If you get any errors while doing this or at server start post them here.

![exec](https://user-images.githubusercontent.com/1254989/215372325-dc5effb8-b376-4a44-a7d4-d6a8d2565d54.jpg)

**Comment by vmornf** [comment]
> 

Okay - but that should be the same as doing something like:
mysql -u root -p
use characters;
And then sourcing all sql files in the order you described:
source "characters...sql"

Do I need to apply Trinitycores database file beforehand, or do I apply it afterwards?
https://github.com/TrinityCore/TrinityCore/releases


I will try it with a fresh install today, but I have received some error yesterday about some table missing or similar.

Thank you for the awesome work btw!

**Comment by trickerer** [comment]
> Do I need to apply Trinitycores database file beforehand, or do I apply it afterwards?

Afterwards of course, as with any other mod. TDB always goes first.
Also important that you apply only DB updates after initial TDB load, world DB contains bot spawn locations which will be lost if you load TDB on top after you spawn your bots.

**Comment by vmornf** [comment]
> 

When I try to apply TDB first, I get this error:

Updating World database...
>> World database is up-to-date! Containing 0 new and 6340 archived updates.
In mysql_stmt_prepare() id: 447, sql: "UPDATE characters_npcbot SET owner = ? WHERE entry = ?"
Table 'characters.characters_npcbot' doesn't exist
In mysql_stmt_prepare() id: 448, sql: "UPDATE characters_npcbot SET owner = ? WHERE owner = ?"
Table 'characters.characters_npcbot' doesn't exist
In mysql_stmt_prepare() id: 449, sql: "UPDATE characters_npcbot SET roles = ? WHERE entry = ?"
Table 'characters.characters_npcbot' doesn't exist
In mysql_stmt_prepare() id: 451, sql: "UPDATE characters_npcbot SET equipMhEx = ?, equipOhEx = ?, equipRhEx = ?, equipHead = ?, equipShoulders = ?, equipChest = ?, equipWaist = ?, equipLegs = ?, equipFeet = ?, equipWrist = ?, equipHands = ?, equipBack = ?, equipBody = ?, equipFinger1 = ?, equipFinger2 = ?,
equipTrinket1 = ?, equipTrinket2 = ?, equipNeck = ? WHERE entry = ?"
Table 'characters.characters_npcbot' doesn't exist
In mysql_stmt_prepare() id: 452, sql: "DELETE FROM characters_npcbot WHERE enTable 'characters.characters_npcbot_transmog' doesn't exist
In mysql_stmt_prepare() id: 460, sql: "DELETE FROM characters_npcbot_transmog WHERE entry IN (SELECT entry FROM characters_npcbot WHERE owner = ?)"
Table 'characters.characters_npcbot_transmog' doesn't exist
In mysql_stmt_prepare() id: 461, sql: "INSERT INTO characters_npcbot_group_member (guid, entry, memberFlags, subgroup, roles) VALUES(?, ?, ?, ?, ?)"
Table 'characters.characters_npcbot_group_member' doesn't exist
In mysql_stmt_prepare() id: 462, sql: "DELETE FROM characters_npcbot_group_member WHERE entry = ?"
Table 'characters.characters_npcbot_group_member' doesn't exist
In mysql_stmt_prepare() id: 463, sql: "UPDATE characters_npcbot_group_member
SET memberFlags = ? WHERE entry = ?"
Table 'characters.characters_npcbot_group_member' doesn't exist
Could not prepare statements of the Character database, see log for details.

**Comment by vmornf** [comment]
> That's because you can't start the worldserver with bots patch applied without applying bots SQLs to DBs. Errors displayed here show that `characters` DB does not have bots 'characters' SQLs applied

Thanks! I got it to work now :)
