### ISSUE TITLE
[AC] [Crash] [Core] AC update requires NPCBot Changes

### ISSUE THREAD

**Issue by Logandros** [trickerer/Trinity-Bots#338]
**Description:**

https://github.com/azerothcore/azerothcore-wotlk/commit/bf30c66ba48cede909a98cb132959c979c032b3b

AC changed recently `(Unit* /*summoner*/) {}` to `(WorldObject* /*summoner*/) {}`

_I believe_ NPCBots may need to be updated accordingly.

AzerothCore:**

**Current behaviour:**

```
5>D:\azerothcore\src\server\game\AI\NpcBots\bpet_ai.h(36,14): error C3668: 'bot_pet_ai::IsSummonedBy': method with override specifier 'override' did not override any base class methods (compiling source file D:\BUILD STUFF\repos\azerothcore\src\server\game\AI\NpcBots\bpet_hunter.cpp)
5>D:\azerothcore\src\server\game\AI\NpcBots\bpet_ai.h(36,14): error C4263: 'void bot_pet_ai::IsSummonedBy(Unit *)': member function does not override any base class virtual member function (compiling source file D:\BUILD STUFF\repos\azerothcore\src\server\game\AI\NpcBots\bpet_hunter.cpp)
5>D:\azerothcore\src\server\game\AI\NpcBots\bpet_ai.h(174,1): error C4264: 'void CreatureAI::IsSummonedBy(WorldObject *)': no override available for virtual member function from base 'CreatureAI'; function is hidden (compiling source file D:\BUILD STUFF\repos\azerothcore\src\server\game\AI\NpcBots\bpet_hunter.cpp)
3>boss_high_interrogator_gerstahn.cpp
5>D:\azerothcore\src\server\game\AI\CreatureAI.h(129,18): message : see declaration of 'CreatureAI::IsSummonedBy' (compiling source file D:\BUILD STUFF\repos\azerothcore\src\server\game\AI\NpcBots\bpet_hunter.cpp)
5>D:\azerothcore\src\server\game\AI\CreatureAI.h(69,7): message : see declaration of 'CreatureAI' (compiling source file D:\BUILD STUFF\repos\azerothcore\src\server\game\AI\NpcBots\bpet_hunter.cpp)
```

**Expected behaviour:**

Should be able to compile

**Steps to reproduce the problem:**

1. AC, with NPCBots.patch and latest commit

**TC / AC rev. hash/commit:** 

CHANGEME Copy the first line of the `worldserver` or `authserver` startup.
For example: TrinityCore rev. 0000000000 2000-01-09 11:31:41 +0100 (my branch) (Win64, Debug, Static) (worldserver)

**Operating system:** Windows 11

**Comment by zhaoxuan** [comment]
I had the same issue.

**Comment by Logandros** [comment]
I believe the simple fix would be:

```
src\server\game\AI\NpcBots\bpet_ai.cpp

2094 - void bot_pet_ai::IsSummonedBy(Unit* summoner)
2094 + void bot_pet_ai::IsSummonedBy(WorldObject* summoner)

src\server\game\AI\NpcBots\bpet_ai.h

35 - void IsSummonedBy(Unit* summoner) override;
35 + void IsSummonedBy(WorldObject* summoner) override;
```

Unofficial but tested and working in-game

**Comment by zhaoxuan** [comment]
> I believe the simple fix would be:
> 
> ```
> src\server\game\AI\NpcBots\bpet_ai.cpp
> 
> 2094 - void bot_pet_ai::IsSummonedBy(Unit* summoner)
> 2094 + void bot_pet_ai::IsSummonedBy(WorldObject* summoner)
> 
> src\server\game\AI\NpcBots\bpet_ai.h
> 
> 35 - void IsSummonedBy(Unit* summoner) override;
> 35 + void IsSummonedBy(WorldObject* summoner) override;
> ```
> 
> Unofficial but tested and working in-game

Thanks, it worked

**Comment by Logandros** [comment]
This fix may not be correct. Server crashed when entering combat with bots in party.

Tested inside and outside of instance, server crash as soon as combat starts.

https://gist.github.com/Logandros/1b891d6775ebd01f38e6e167d69c5d47

**Comment by Logandros** [comment]
However this is after I applied recent commits:

https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/c030bbec0d2f3cadc28ea2aa2c7c4d6b6cfe06b8
and
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/aef919d90f1d846eab80bb7c7dd7586b66b5e614

**Comment by Logandros** [comment]
@trickerer  let me know if you need me to build a debug release and provide you with a crash log to troubleshoot the issue. I'm not certain if the fix I'm using to temporarily build caused this or your latest commits. I would have to revert to test. I do not think there was a combat crash prior to c030bbe and aef919d being merged.

**Comment by Logandros** [comment]
RelWDebug

https://gist.github.com/Logandros/296d3a5a82678811c154720abf09a28c

**Comment by Logandros** [comment]
Here is another interesting find, this crash does not occur when using a character that does not have a pet (Druid). I tried it with an NPCBot that does not have a pet (Rogue) and an NPCBot that has a pet (Hunter) and no crash. The crash seems to be isolated to using a combination of a character with a pet (Hunter) and any NPCbot.

**Comment by trickerer** [comment]
> RelWDebug
>
> https://gist.github.com/Logandros/296d3a5a82678811c154720abf09a28c

This crash is caused by https://github.com/azerothcore/azerothcore-wotlk/commit/44226e4754b0ac8e741f00fdebdf894c599baac5
Target of shapeshift spell effect is assumed to be player always which is a mistake. Probably can be reproduced by using `.cast b 5487 t` on any creature.

Try removing druid from bot party (unbind)

**Comment by Logandros** [comment]
Unbind Druid prevented crash. However I was not able to reproduce by using `.cast b 5487 t`
The creature successfully turned to bear form and was able to melee in combat.

**Comment by trickerer** [comment]
Sorry, didn't look close enough, the assumption that target is player is based on a condition if target class is druid. NPCBots use player classes (for in-game class names&colors display).

**Comment by Logandros** [comment]
> Sorry, didn't look close enough, the assumption that target is player is based on a condition if target class is druid. NPCBots use player classes (for in-game class names&colors display).

Got it, let me know if there is anything else I can do to help troubleshoot and resolve this. For now, we just not using Druids in our party / raids.
