### ISSUE TITLE
Valithria Dreamwalker - Bot not heal until 100% HP to the dragon

### ISSUE THREAD

**Issue by Ryu1254** [trickerer/Trinity-Bots#34]
Yesterday, for the first time, I run ICC 10 mans with 9 bot.
at Valithria Dreamwalkter fight, I set Valithria with healing mark (Triangle)
the bots doing a pretty good job on healing to the dragon. but stop casting any healing on it at around 11M/12M HP.

any idea what make the the bot stop cast heal??

Thanks.

**Comment by trickerer** [comment]
Looks like there is a condition 'expected health below 95%' to do any healing - from the time of implemenation of health prediction healing system. Looks like this needs to be changed for explicit (pointed) targets.

**Comment by Ryu1254** [comment]
I applied the new npcbot patch, and test Valithria Dreamwalker again. still not heal to 100% the dragon..
Is this line cause the issues?
if (xppct >= 95 && hp >= 25 && !IsPointedHealTarget(target))

I'll change it to 100 instead of 95 see what it's does. and keep you post.

**Comment by trickerer** [comment]
I forgot something it seems

**Comment by Ryu1254** [comment]
test result.. even i change it to
if (xppct >= 100 && hp >= 25 && !IsPointedHealTarget(target))
still does not work.. i notice something.. in my group composition, i have a druid healer. when reaching around 10946k / 12000k HP. the casting skill for healing keep failing.
unfortunally, there is no crash.. so i cannot provide any log..

**Comment by trickerer** [comment]
[ea8fe2c3a1](https://github.com/trickerer/Trinity-Bots/commit/ea8fe2c3a114b1ef98c60e43f81818d77278c3e8)
Apply this manually and it should work

**Comment by Ryu1254** [comment]
nop.. still not heal to 100%..

**Comment by Ryu1254** [comment]
you going to hate me :)
I try the new patch.. same thing.. the bot heal until 10942k /12000k.  I see the bot is casting spell to heal the dragon. but never complete the casting.. it's keep resetting the current cast.. this behavior occur only near the end..

if I use a real player to complete the 1000k hp left, then I can complete the fight. but it must be a real player to do the last 1000k hp..

**Comment by Ryu1254** [comment]
Check the video, see the behavior what it does. hope it help.

[bot healing fail.zip](https://github.com/trickerer/Trinity-Bots/files/5432148/bot.healing.fail.zip)

**Comment by trickerer** [comment]
meh, I don't even need a video to know what I missed, again.
Don't worry, I've been dealing with issues way worse than this.

I think this is the last of them:
bot_ai.cpp:11326
```
-                 info->HasEffect(SPELL_EFFECT_HEAL) && GetHealthPCT(target) > 90)
+                info->HasEffect(SPELL_EFFECT_HEAL) && GetHealthPCT(target) > 90 && !IsPointedHealTarget(target))
```

**Comment by Ryu1254** [comment]
you did it!!!! it's work.. 
I did a test and I am able to complete the Valithria Dreamwalker 10 man. with 9 bots.
Thanks you very much for taking time to fix stuff. really appreciate. I think, we never thank you enough for your good work on this NPCbot and for keeping it up to date.

Good job again.
