### ISSUE TITLE
[TC] [AC] [Enhancement] [Core] Bind Bots by account

### ISSUE THREAD

**Issue by Logandros** [trickerer/Trinity-Bots#342]
**Description:**

How hard would it be to allow bots to be bound by account rather than character?

**TrinityCore or AzerothCore:**

**Current behaviour:**

Currently bots are character bind only.

**Expected behaviour:**

This would be a great way to retain and minimize the amount of bots each account would use. It would also allow the account to retain and upgrade bot gear account-wide.

**Steps to reproduce the problem:**

This is a feature / enhancement request.

**TC / AC rev. hash/commit:** 

N/A

**Operating system:** Windows 10

**Comment by trickerer** [comment]
Not until there is an option to bind all items by account
#299

**Comment by Logandros** [comment]
I see, this is a core limitation. I will close the issue.
