### ISSUE TITLE
[AC] [enhancement] [Group] number of bot in raid

### ISSUE THREAD

**Issue by EvilCalf** [trickerer/Trinity-Bots#344]
Now the bot can directly enter the dungeon without forming a team
In this way, the number of people entering the dungeon will exceed the upper limit

**Comment by trickerer** [comment]
Config params `NpcBot.Limit.Dungeon` and `NpcBot.Limit.Raid` exist just for that. Bots not in group can enter dungeons only if set to 0 (default is 1)
