### ISSUE TITLE
 [AC] [Bug] AC: 04 Feb 2023, 83b828f5d6 authserver.exe and worldserver.exe both Unable to boot normally

### ISSUE THREAD

**Issue by zbhcn** [trickerer/Trinity-Bots#345]
No log file generated，Without any error warning, the window closes automatically，help me please
I didn't change any settings in the authserver.conf and worldserver.conf files
I haven't changed any database. I can start it with the previous program

**Comment by trickerer** [comment]
Windows version works fine. Try to launch from outer console and get the output.

**Comment by zbhcn** [comment]
thanks , I found the reason. It no longer load authserver.conf.dist, can only load authserver.conf
