### ISSUE TITLE
 [AC] [Bug] [Core] not find localized in database

### ISSUE THREAD

**Issue by kr521** [trickerer/Trinity-Bots#346]
**Description:**
Thank you for you work.

i have some error for npcbot database on AzerothCore with newest master code. please help me .

I tried to upgrade the database manually, but didn't fix it.

OS: ubuntu 22.04

![wow-1](https://user-images.githubusercontent.com/3262751/216829860-ed9f372e-5172-4efe-b2cc-a603cd614c18.png)

![wow-2](https://user-images.githubusercontent.com/3262751/216829867-fd0efe2d-aee9-44d8-99a5-6f0617616ecc.png)

![wow-3](https://user-images.githubusercontent.com/3262751/216829875-55e8d7fd-d319-480c-a2b7-88f58cfb10e5.png)

**Comment by trickerer** [comment]
Can't reproduce with ruRU locale (the only one I have at hand). I also can't find any recent changes in the core affecting localization process.

Make sure:
1) worldserver is using the right DB (check config)
2) `npc_text` table  (not `npc_text_locale` in this case) contains original english text strings

**Comment by kr521** [comment]
Thank you for your answer

1. I have recheck the worldserver config file. database config is correct and i have try to reset the dbc.locale to 255 but not fix .
2. I didn't delete any table in database，in the previous version is normal，I was only update git and repatch and rebuild code . 
3.  Tonight I will rebuild the npcbot database and try again.  if can fix the problem i will close this issue.
