### ISSUE TITLE
[AC] [Bug]  После последнего обновления консоль сервера стала выдавать ошибку.

### ISSUE THREAD

**Issue by Parkan1986** [trickerer/Trinity-Bots#349]
При использовании бота паладинов а так же во время загрузки сервера консоль стала выдавать такие ошибки:
CastSpell: unknown spell 7614 by caster GUID Full: 0xf1300111ac000002 Type: Creature Entry: 70060  Low: 2
CastSpell: unknown spell 7614 by caster GUID Full: 0xf1300111ad0008d6 Type: Creature Entry: 70061  Low: 2262

Такого спелла в игре нет.При чем это случается на паладинах.

**Comment by trickerer** [comment]
https://github.com/trickerer/Trinity-Bots/issues/253
https://github.com/trickerer/Trinity-Bots/issues/245

**Comment by Parkan1986** [comment]
Ну да тут получается я использую просто другую версию random enchants. https://github.com/AnchyDev/StatBooster
Я еще не компилировал текущую версию Ваших исходников с сегодняшними исправлениями,но ошибка из консоли пропала хотя на боте я предметы не успел поменять.Значит какой то энчант гадит в консоль.узнать бы какой именно.
