### ISSUE TITLE
feature suggest:Lease period of robot

### ISSUE THREAD

**Issue by qyh214** [trickerer/Trinity-Bots#35]
although we can add a lot of bots in the world,but it is should a limit.
we can design a system-- Validity period of robot
for example,when you buy a bot and you should use him/her,If you offline for more than 30 days,your bots will be released.
all items will mailed to you.

**Comment by xtracripper** [comment]
I did this with a stored procedure. Had to add a column in characters table which updates with current timestamp when characters login. As there was only a logout timestamp.

Character offline >2 days, start to bleed bots 1 per nightly server restart. When a bot bleeds away, mail all items he had. Paladin and druid bots seem to be in high demand.

When people play alts in particular, their bots will need to bleed away when they stop playing the alt.

**Comment by trickerer** [comment]
Please take note that ownership expires based on **account** inactivity period.
