### ISSUE TITLE
Priest bots stop wanding

### ISSUE THREAD

**Issue by westernoutlaw** [trickerer/Trinity-Bots#351]
Hello. I ran into an issue when priest bots stop using wands all of a sudden and I can't find a way to fix it once it happens to a bot.
When a bot first spawned it works just like it should, and then at some point they stop using and just stand there between casting. I tried reloading bot config, removing the bot, deleting, respawning, re-hiring, re-equipping different wands, everything. Nothing works except creating a brand new bot. Would you happen to know what could cause something like that? I'm using one of the latest builds on Azerothcore.

**Comment by trickerer** [comment]
Can't reproduce.
Maybe this is a visual bug? Have you tried with priest only to see if damage passes?
If it isn't I'll need bot level, stats, roles, wand item id and disabled spells if any. And area/target creature where this was encountered.

**Comment by westernoutlaw** [comment]
Nope, not a visual... That's the thing, it happens randomly to any bot, with any wand, with any mob
Well if it's not a mod bug guess it's a problem with my setup, nevermind then
