### ISSUE TITLE
[AC] баг с отображение здоровья у ботов

### ISSUE THREAD

**Issue by xBarselonx** [trickerer/Trinity-Bots#352]
Вчера заметил один момент при экипировки ботов фамильным снаряжением. При подключении сервера и входа в игру за персонажа у ботов одетых в фамилки высокий показатель здоровья. Например на 15 уровне у моего перса около 600+- единиц здоровья, а у ботов в районе 3000. После того как я сниму всю фамильную экипировку и одену обратно на ботов показатель их здоровья относительно выравнивается с показателем моего персонажа. В качестве фамилок использую стандартные предметы из дополнения 3.3.5а. Если нужны будут скрины, скину позже.  
С чем это может быть связано?

**Comment by trickerer** [comment]
"Фамильное"... я даже не сразу понял что это.

Похоже, уровень для скалирования выбирается неверно, либо алгоритм другой. Возможно опечатка.

**Comment by xBarselonx** [comment]
Под фамилками я имел ввиду наследуемые предметы ( броня, оружие и трини). Это связано с самим модом или исходниками от АС?

**Comment by trickerer** [comment]
Я никакой проблемы не вижу. Попробуй отключить модули, одеть бота в свежесозданный шмот

![heirloom](https://user-images.githubusercontent.com/1254989/218235494-6f074b42-4ce9-4101-acde-ab08a6d68b8b.jpg)

**Comment by xBarselonx** [comment]
Со здоровьем ничего не изменилось. До меня только что начинает доходить, что события с изменением здоровья начались после того как я решил создавать свои (дополнительные) наследуемые предметы (шапка, шея, плащ и т.д., т.е. полный комплект), чтоб меньше заморачиваться на шмоте для ботов. В качестве проги я использовал ---> [Keira3](https://github.com/azerothcore/Keira3), а за основу брал какую-то из фамилок (точно не помню) путем копирования и изменения стат и назначения. В итоге я создал 31 предмет в безе world, таблица item_template. Поэтому думаю тему нужно закрывать. 

trickerer, пару вопросов:
1. как думаешь удаление созданных предметов вернет все обратно, как думаешь (в плане решение моего вопроса)? 
2. удалить в таблице item_template созданные предметы и только, я надеюсь они нигде больше не записались в базе?

**Comment by trickerer** [comment]
> trickerer, пару вопросов:
> 1. как думаешь удаление созданных предметов вернет все обратно, как думаешь (в плане решение моего вопроса)?
> 2. удалить в таблице item_template созданные предметы и только, я надеюсь они нигде больше не записались в базе?

1. Если это единственный источник проблем, то вернёт.
2. Прежде чем удалять из таблицы `item_template` необходимо изъять все эти предметы у игроков и ботов. И не забудь после проверить их наличие в `item_instance`.

**Comment by xBarselonx** [comment]
> > trickerer, пару вопросов:
> > 
> > 1. как думаешь удаление созданных предметов вернет все обратно, как думаешь (в плане решение моего вопроса)?
> > 2. удалить в таблице item_template созданные предметы и только, я надеюсь они нигде больше не записались в базе?
> 
> 1. Если это единственный источник проблем, то вернёт.
> 2. Прежде чем удалять из таблицы `item_template` необходимо изъять все эти предметы у игроков и ботов. И не забудь после проверить их наличие в `item_instance`.

Поковыряться, посмотрю что получится.

**Comment by xBarselonx** [comment]
> 2\. И не забудь после проверить их наличие в `item_instance`.

в `item_instance` база char в разделе или графе itemEntry есть повторяющиеся entry (может это так и должно быть). Ты про эти говорил которые нужно проверить при удалении данных о наследуемых предметах в таблице `item_template`. Напомню, что наследуемые предметы я создавал с 90000.

таблица `item_instance`. Отбор по созданным наследуемым предметам.
![image](https://user-images.githubusercontent.com/99982508/220702590-ed9a461e-0e5c-4e60-b6de-d7d1b82fe2e2.png)

таблица `item_template`. Отбор по созданным наследуемым предметам. Все созданные предметы есть в базе и сняты со всех ботов и уничтожены в игре. Как ты говорил.
![image](https://user-images.githubusercontent.com/99982508/220702864-b728a3b2-0195-4129-ac5e-ee937d8de94d.png)


Я верно понимаю, что мне нужно удалить строки начиная с 90000 в указанных таблицах на скринах выше? Меня немного смутило, что графа в `item_template` называется guid, а в `item_instance` itemEntry - это ведь одно и тоже?
