### ISSUE TITLE
[AC] [Bug] [Core] Compile Error

### ISSUE THREAD

**Issue by EvilCalf** [trickerer/Trinity-Bots#353]
[036d23d](https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/036d23dc4bcf1947dd93b81020b7ab6054f4c191)\

[ 22%] Building CXX object src/server/game/CMakeFiles/game.dir/AI/NpcBots/bot_ai.cpp.o
In file included from /root/AzerothCore-wotlk-with-NPCBots/src/server/game/AI/NpcBots/bot_ai.cpp:1:
/root/AzerothCore-wotlk-with-NPCBots/src/server/game/AI/NpcBots/bot_ai.h:106:14: warning: 'CanRespawn' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
        bool CanRespawn() { return IAmFree(); }
             ^
/root/AzerothCore-wotlk-with-NPCBots/src/server/game/AI/CreatureAI.h:113:18: note: overridden virtual function is here
    virtual bool CanRespawn() { return true; }
                 ^
In file included from /root/AzerothCore-wotlk-with-NPCBots/src/server/game/AI/NpcBots/bot_ai.cpp:5:
/root/AzerothCore-wotlk-with-NPCBots/src/server/game/AI/NpcBots/botmgr.h:17:6: fatal error: enumeration previously declared with nonfixed underlying type
enum CurrentSpellTypes : uint8;
     ^
/root/AzerothCore-wotlk-with-NPCBots/src/server/game/Entities/Unit/Unit.h:984:6: note: previous declaration is here
enum CurrentSpellTypes
     ^
1 warning and 1 error generated.
make[2]: *** [src/server/game/CMakeFiles/game.dir/build.make:244: src/server/game/CMakeFiles/game.dir/AI/NpcBots/bot_ai.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1225: src/server/game/CMakeFiles/game.dir/all] Error 2

**Comment by trickerer** [comment]
oops
