### ISSUE TITLE
[AC] [Crash] [Core] look at this

### ISSUE THREAD

**Issue by runchance** [trickerer/Trinity-Bots#355]
https://github.com/azerothcore/azerothcore-wotlk/commit/bd6034e1a9f5ba18dff1261edaea4494727412a2

**Comment by trickerer** [comment]
This will have to wait until saturday when I merge. Plus I expect additional patch breaking commits to follow.

**Comment by Logandros** [comment]
As an FYI, temp solution you can use a simple **search** `EnterCombat` and **replace with** `JustEngagedWith` within`\azerothcore\src\server\game\AI\NpcBots` 

This will at least get you to compile and everything seems to work. I'm sure Trickerer may want to clean that up and there may be more to it so **I would make a backup** and replace it later when he's able to get to it. But if you don't want to wait until then, this temporary solution is a workaround. I've tested it and so has Revision - noisiver.
