### ISSUE TITLE
 [AC] 在使用AzerothCore-wotlk-with-NPCBots 时加入了azerothcore的 mod-eluna 模块，但是在编译时报错

### ISSUE THREAD

**Issue by kasting** [trickerer/Trinity-Bots#356]
[AC] 在使用AzerothCore-wotlk-with-NPCBots 时加入了azerothcore的 mod-eluna 模块，但是在编译时报错
各模块和程序都已经更新到最新

**Comment by kasting** [comment]
> [AC] 在使用AzerothCore-wotlk-with-NPCBots 时加入了azerothcore的 mod-eluna 模块，但是在编译时报错 各模块和程序都已经更新到最新
AzerothCore-wotlk-with-NPCBots 单独编译时是成功的
在目录modules里加入 mod-eluna 模块后在生成解决方案时
![微信图片_20230216061550](https://user-images.githubusercontent.com/83107774/219192211-31911fa0-8de1-48e8-98c5-901500672ced.png)
导致编译worldserver失败

**Comment by trickerer** [comment]
I'm glad you figured out the solution to the original issue.

The compilation errors you get are just due to recent AC changes. AzerothCore-wotlk-with-NPCBots repository gets updates every saturday.
#355

**Comment by kasting** [comment]
非常感谢！
我会持续关注更新！

**Comment by kasting** [comment]
加油！我会持续关注更新！
