### ISSUE TITLE
[AC] Не могу зайти в игру. 

### ISSUE THREAD

**Issue by xBarselonx** [trickerer/Trinity-Bots#359]
После последних обновлений не заходит в игру. При выборе персонажа полоса загрузки доходит до конца и дальше может продолжаться до бесконечности. До обновления все было норм. Ошибок и предупреждений при компиляции и дальнейшего запуска сервера не было.

**Comment by trickerer** [comment]
Попробовал на нескольких персонажах. Не вижу ничего такого, да и не было в ботах таких серьёзных изменений. Укажи ревизию.

**Comment by xBarselonx** [comment]
Я писал АС и они дали ответ https://github.com/azerothcore/azerothcore-wotlk/issues/15134. Сказали, это уже исправлено нужно обноситься.

**Comment by trickerer** [comment]
Ясно.

**Comment by xBarselonx** [comment]
Я так понимаю, тебе нужно будет объединить обновления АС, с учетом исправленной проблемы?

**Comment by trickerer** [comment]
Да. Так как баг и исправление появились после субботы нужно скачать последние обновления **оттуда**.

**Comment by xBarselonx** [comment]
Что именно скачать? Файл исправления в который вносили изменения или что? Никогда этого не делал.

**Comment by trickerer** [comment]
Я имею ввиду `git pull` & `merge`

**Comment by xBarselonx** [comment]
так слияние нужно делать: https://github.com/xBarselonx/AC-wotlk-NPCBots/commits/npcbots_3.3.5 ? Я сделал на копии твоего репо попоробовал.

**Comment by trickerer** [comment]
Слияние из ориганального репозитория, ведь исправления (как и баг) добавили только там.
Если получается сложно, можно просто накатить фикс вручную, там же всего несколько строк.

**Comment by xBarselonx** [comment]
Вручную, то здесь https://github.com/azerothcore/azerothcore-wotlk/commit/abedfe245f176fd421a91301d97ba89a73251ab6. Верно? Но только в файлах из твоего репо.

**Comment by trickerer** [comment]
Верно.
В файлах твоего локального репо. Путь один и тот же а проблемы только у тебя.

**Comment by xBarselonx** [comment]
Ок. Спасибо.

**Comment by Day36512** [comment]
I'm actually experiencing this same issue. Good to know what the issue was. Thank you.

**Comment by xBarselonx** [comment]
trickerer, это для тебя трудоемко делать слияние в случае если у АС что-то пойдет не так (как в данной проблеме не пускает зайти в игру). Таких случаев единицы. По крайней мере за год пользования твоей разработкой я не сталкивался с подобным. Видимо кто-то тоже обновляется с ошибкой и приходится либо неделю ждать или углубляться в источник проблемы который не четко ясен ввиду отсутствия профессиональных навыков. Но я лично (возможно и еще кто-то) простой обыватель и я знаю как установить сервер и базы и без проблем запустить его. 
Можно попросить тебя в следующий раз (если случится подобный случай) обновлять свой репо с исправленной ошибкой?

**Comment by trickerer** [comment]
Если бы в первом же сообщении ты указал ревизию (шаблон требует этого не просто так), из разницы между репозиториями проблему можно было бы обнаружить сразу, как и необходимость срочного обновления.
А так я вынужден гадать в чём дело, тем более что у меня этой проблемы нет. Подобные проблемы могут возникнуть от чего угодно, а ребусов мне уже хватило от наших китайских друзей.
В данном случае тоже придётся обновляться, а то завалят репортами этой хрени, как это обычно бывает.

**Comment by xBarselonx** [comment]
Ок. Я тебя понял.  Если буду подобные случаи в будущем, сначала разберусь откуда и где она возникла и возможно ли на моей уровне ее решить. В противном случае обращусь к тебе с вопросом. Предлагаю закончить эту тему. Я так понял, ты уже сделал слияние?
