### ISSUE TITLE
Adding a bot in Stormwind creates random Festive Mug item

### ISSUE THREAD

**Issue by TQPS** [trickerer/Trinity-Bots#36]
Refreshed bots server with clean build and SQL DB - no problem.
Added bots and played for a while - no problem.

Came back to bank and noticed a `Festive Mug` hovering in the air just near The Gilded Rose.

Couldn't remove it - was bugging me - the only thing I did was add bots (not even a GM ON) and ran Deadmines.

Put in a fresh DB and put in a single Bot - shutdown server, shutdown SQL, started everything up and there it was.

Something is adding this item after you add your first bot.

https://classic.wowhead.com/object=180905/festive-mug

Edit: Tested adding 3 different bots in 3 different locations 1 per attempt. All 3 attempts, regardless of their locations generated that item in the exact same place - each time shutting down server and restoring a clean DB.

Bots tested were:
.npcbot spawn 70003
.npcbot spawn 70201
.npcbot spawn 70060
.npcbot spawn 70153

All of them resulted in the mug spawning after a full server shutdown / restart

Currently using clean 3.3.5a - no bots - and no mug spawns are present - only when adding first bot.

<details>

![image](https://user-images.githubusercontent.com/66294837/97098256-e2424500-16ce-11eb-9da8-0738119ad570.png)

</details>

**Comment by TQPS** [comment]
**Testing:**
`.npcbot spawn 70003` to Aerie Peak (Hinterlands) - Hearthed to Stormwind - no Festive Cup
Shutdown world, auth and MySQL - startup - login - no Festive Cup!!! Perfect!

Deleted data DIR and restored clean DB and ran npcbot SQLs

**Testing:**
`.npcbot spawn 70201` outside Gilded Rose (Stormwind) - no Festive Cup (You have to shutdown)
Shutdown world, auth and MySQL - startup - login - Festive Cup had spawned!!

Deleted data DIR and restored clean DB and ran npcbot SQLs

**Testing:**
`.npcbot spawn 70153` outside Everyday Merchandaise (Stormwind) - no Festive Cup (You have to shutdown)
Shutdown world, auth and MySQL - startup - login - Festive Cup had spawned over at the Gilded Rose!!

**Additional testing:**
So you can loot the cup like a normal object and it gives you the empty mug and disappears - but it comes back after a while.

If you loot the cup and log out and do a full shutdown and startup - it respawns!

So something is creating an additional spawn right?

**Comment by trickerer** [comment]
This could be a bug with how grids are loaded for active objects.
What I can say for certain is:

1. Nothing within bots mod is spawning any gameobjects besides temporary ones spawned by spell (Mage, Warlock).
2. Hidden Festive Mugs are all over the place within cities, tied to game events. Most of them are for brewfest I think.

You need to check your 'gameobjects' table for new entries. If there are none, this bug is not a big thing.

**Comment by TQPS** [comment]
Do you have any bots spawned in Stormwind? Does the item spawn outside your Gilded Rose? This is a clean TDB_ and I dont run any mods or tweaks - just wanted to give the bots a try.

**Comment by trickerer** [comment]
I tested it and no mug spawned, but this wasn't a clean setup. As I said, there are several invisible mugs hovering in the air near Gilded Rose, use `lookup object 180905`, `go gameobject` and `gameobject near` if you want to check them by yourself

**Comment by TQPS** [comment]
Any idea why they are only showing up after I add a bot?

**Comment by trickerer** [comment]
As I already said: this could be a bug with how grids are loaded for active objects.
When server loads all grids containing bots are forcefully loaded (as they would for players). Something like 'first gameobject in the grid changes its phasemask to 0xFF for some reason' is my only guess right now. Finding the exact reason may require alot of debugging

**Comment by TQPS** [comment]
Ok, thanks for the explanation. 

If it's not the bots I'll close this.
