### ISSUE TITLE
[Enhancement] Unbind all command

### ISSUE THREAD

**Issue by bkmangx1** [trickerer/Trinity-Bots#366]
Right now, if you control large number of bots and want to dismiss temporarily, you have to execute unbind command on every single bot either by name or targeting them individually. I think this command could could be improved by adding a mass unbind option, either by targeting yourself (like remove command works) or by extra parameter. Let me know what you think.

**Comment by trickerer** [comment]
For starters, you can unbind bots using a list of names: `.npcb unbind name1 name2 name3 ... nameN`. It sometimes is easier when you have a macro for such unbind so you have those names saved somewhere
Secondly, there is a `.npcb hide` / `.npcb unhide` commands which do essentially what you want, the only difference is that bots don't return anywhere and just stay out of world

**Comment by trickerer** [comment]
Uh, it seems like you can't use names list with unbind command after all. Mistook it for how `.npcbot sendto` command works.
I'm going to expand bind commands functionality asap.
