### ISSUE TITLE
[AC] [Bug/Crash] Server process crash

### ISSUE THREAD

**Issue by kasting** [trickerer/Trinity-Bots#369]
Check the log display
bot_ai::doCast(): Keryn (bot class 4) tried to cast spell 48638 on a dead target 明鳞龙鳗

How should I deal with such a breakdown

**Comment by trickerer** [comment]
You don't need to deal with it. What you need to do is fill the issue template and provide a crashlog so I can fix the crash

https://github.com/trickerer/Trinity-Bots/blob/master/.github/ISSUE_TEMPLATE/issue_template.md
