### ISSUE TITLE
Npcbot name

### ISSUE THREAD

**Issue by zaicopx** [trickerer/Trinity-Bots#37]
Is there a way to get rid of the npcbot name?  like <.paladin bot.> <.player minion.> under npcbot name

**Comment by trickerer** [comment]
As for bot type do this:

```
UPDATE creature_template SET subname = NULL WHERE entry IN (SELECT entry FROM creature_template_npcbot_extras WHERE class IN (1,2,3,4,5,6,7,8,9,11,12,13,14,15,16,17));
```

As for minion status, same rules as with pets. You cannot remove it without breaking owner-minion base mechanics.

**Comment by zaicopx** [comment]
Thanks. If you already had npcbot, you must be deleted your npcbot first
