### ISSUE TITLE
[TC] Compile warning with last Trinitycore

### ISSUE THREAD

**Issue by Krutok** [trickerer/Trinity-Bots#372]
[ 19%] Building CXX object src/server/game/CMakeFiles/game.dir/AI/NpcBots/bot_archmage_ai.cpp.o
/var/www/vhosts/myserver/TrinityCore/src/server/game/AI/NpcBots/bot_ai.cpp:5607:21: warning: unannotated fall-through between switch labels [-Wimplicit-fallthrough]
                    case BOT_ITEM_USE_SPELL_TARGET_NONE:
                    ^
/var/www/vhosts/myserver/TrinityCore/src/server/game/AI/NpcBots/bot_ai.cpp:5607:21: note: insert 'break;' to avoid fall-through
                    case BOT_ITEM_USE_SPELL_TARGET_NONE:
                    ^
                    break;

Compile under Debian 11
TrinityCore rev. 92b7c98c018c+ 2023-02-25 21:12:28 +0100 (3.3.5 branch) (Unix, RelWithDebInfo, Static)

**Comment by trickerer** [comment]
Thanks. Strangely enough CI didn't trigger on that at all
