### ISSUE TITLE
Feature Requests: Glyph system + able to purchase any Tier gear for bot with token

### ISSUE THREAD

**Issue by Ryu1254** [trickerer/Trinity-Bots#38]
NPCBot is cool and fun to play with. I love them. I did most almost all raid exclusively with bot only. only certain fight that require special player mechanism.. that i cheat with GM. but other then that, i play normal with bot.
so that been said, it would be cool if we can have Glyph system for bot.
also, currently you can only buy Tier gear for your own class, how can we buy Tier gear that are not our class?
That's not an npcbot enhancement. but more a question of how to remove class tier vendor restriction, any idea?

**Comment by trickerer** [comment]
ItemHandler.cpp::653 comment out this allowable classes check. Some items are restricted by conditions but I hope they don't affect class tiers.

Glyphs. Right now all the the glyphs I could implement are used automatically according to level. Most of the glyphs affecting class effectiveness are tied to spec's key spells so I see no problem leaving them as is. I'd like to implement the rest of them but that's not a high priority.

**Comment by Ryu1254** [comment]
Im happy with the current setup. But Its doesn't hurt asking for improvements. 

And i’ll try the trick in the itemhandler. Thanks

**Comment by Ryu1254** [comment]
Here the test result.
by disable the line 653 and 654 in the ItemHandler.cpp , i am able to see all tier gear for all class. that would be very useful to buy Tier gear for bots.
thanks

**Comment by Ryu1254** [comment]
I got this error when I compile the patch v4.9.1a

![v4 9 1a compile error](https://user-images.githubusercontent.com/72590132/101811908-ad584900-3ae8-11eb-8cd8-630b72f561a4.jpg)

**Comment by trickerer** [comment]
I'll recheck it but I'm sure TemporarySummon.cpp wasn't changed

**Comment by Ryu1254** [comment]
Ok i found the issues with the error message.. when i apply the patch.. there are some left over script from the previous patch.. for  some reason.. it does not clean it.. I re-apply the patch.. and i can compile now..
except.. when i go to a gear vendor.. i see the gear that are not my class, but i cannot buy them. it's said Item not found.

I try to do a reset from trinitycore and reapply the npcbot again. will let you know.

**Comment by Ryu1254** [comment]
1) confirmed. after resetting the trinitycore to Trinitycore repository 3.3.5 and reapply the npcbot patch.. no error during compile.
2) i try to purchase a class gear for a bot. I see the gear but unable to purchase it. I got error: Item not found.

**Comment by Ryu1254** [comment]
cool.. it's work perfectly for the gear purchase.. when the bot class present, i can buy the Tier gear.
if I dismissed the bot, I don't see the gear for that class as well. this is perfect..

Thanks you very much.. that would make life easier if you want to gear bot with frost emblem or upgrade with Tier gear drop from ICC 25..

**Comment by trickerer** [comment]
Have to cancel that, Glyphs are going to stay as presets, just like talents.
