### ISSUE TITLE
[AC] [Bug] Bot Giver 'Lagretta' lists wandering bots

### ISSUE THREAD

**Issue by Boxhead78** [trickerer/Trinity-Bots#382]
Bot Giver 'Lagretta' offers to recruits wandering NPC-Bots which she shouldn't. When trying to recruit a wandering NPC-Bot with the bot giver she only responds with 'The bot is busy at the moment'.

**Comment by Parkan1986** [comment]
У меня случай был наоборот я смог нанять бота через нпс и он был 30го уровня со шмотом.Но я не смог через диалог отвязать его от игрока,только через гм команду npcbot remove бот получил 80ый уровень и улетел в неизвестном направлении

**Comment by trickerer** [comment]
https://github.com/trickerer/Trinity-Bots/commit/babf73e5594f555198c340fb37800843ee790f48

**Comment by Boxhead78** [comment]
> [babf73e](https://github.com/trickerer/Trinity-Bots/commit/babf73e5594f555198c340fb37800843ee790f48)

I recompiled with the latest commits and it seems like Lagretta still wants to give me wandering bots. Could you please confirm if it's fixed for you and it's something on my side?

**Comment by trickerer** [comment]
Nope. Check both AC and TC. Botgiver only offers static free bots
