### ISSUE TITLE
[AC] [Crash] can't use

### ISSUE THREAD

**Issue by zhuyaozi** [trickerer/Trinity-Bots#384]
sorry I have some problem building
here is what i did:
cd azerothcore/modules
git clone https://github.com/trickerer/Trinity-Bots.git
cd azerothcore
git apply modules/Trinity-Bot/AC/NPCBots.patch

run all the 6 *.sql scripts

and when i start  ./worldserver 
it report some errors like:
Script named 'archmage_bot' is assigned in the database, but has no code!
Script named 'archmage_pet_bot' is assigned in the database, but has no code!
Script named 'blademaster_bot' is assigned in the database, but has no code!
Script named 'dark_ranger_bot' is assigned in the database, but has no code!
Script named 'dark_ranger_pet_bot' is assigned in the database, but has no code!
Script named 'death_knight_bot' is assigned in the database, but has no code!
Script named 'deathknight_pet_bot' is assigned in the database, but has no code!
Script named 'dreadlord_bot' is assigned in the database, but has no code!
Script named 'dreadlord_pet_bot' is assigned in the database, but has no code!
Script named 'druid_bot' is assigned in the database, but has no code!
Script named 'druid_pet_bot' is assigned in the database, but has no code!
Script named 'hunter_bot' is assigned in the database, but has no code!
Script named 'hunter_pet_bot' is assigned in the database, but has no code!
Script named 'mage_bot' is assigned in the database, but has no code!
Script named 'mage_pet_bot' is assigned in the database, but has no code!
Script named 'paladin_bot' is assigned in the database, but has no code!
Script named 'priest_bot' is assigned in the database, but has no code!
Script named 'priest_pet_bot' is assigned in the database, but has no code!
Script named 'rogue_bot' is assigned in the database, but has no code!
Script named 'script_bot_giver' is assigned in the database, but has no code!
Script named 'shaman_bot' is assigned in the database, but has no code!
Script named 'shaman_pet_bot' is assigned in the database, but has no code!
Script named 'spellbreaker_bot' is assigned in the database, but has no code!
Script named 'sphynx_bot' is assigned in the database, but has no code!
Script named 'warlock_bot' is assigned in the database, but has no code!
Script named 'warlock_pet_bot' is assigned in the database, but has no code!
Script named 'warrior_bot' is assigned in the database, but has no code! 
 
i have no idea ,am i using it in a wrong way？

really appreciate your help!

**Comment by trickerer** [comment]
You have to re-build the server for applied patch to take effect

**Comment by zhuyaozi** [comment]
actually, I have rebuild ,rm all things in "build",and cmake ***,and make,and make install   😥

**Comment by trickerer** [comment]
The errors you get indicate that core you're running was built without bots code

**Comment by zhuyaozi** [comment]
so i don't know ... am i using the wrong method?
in azerothcore "git apply modules/Trinity-Bot/AC/NPCBots.patch"

**Comment by zhuyaozi** [comment]
here is the report when i run "git apply modules/Trinity-Bot/AC/NPCBots.patch"

[root@0b70a5fba2de azerothcore]# git apply modules/Trinity-Bots/AC/NPCBots.patch 
modules/Trinity-Bots/AC/NPCBots.patch:1462: trailing whitespace.
('70541', 'ruRU', 'Снять бафф', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
modules/Trinity-Bots/AC/NPCBots.patch:2320: trailing whitespace.
-- 
modules/Trinity-Bots/AC/NPCBots.patch:2359: trailing whitespace.
-- 
modules/Trinity-Bots/AC/NPCBots.patch:2379: trailing whitespace.
-- 
modules/Trinity-Bots/AC/NPCBots.patch:2421: trailing whitespace.
-- 
error: appveyor.yml: already exists in working directory
error: data/sql/Bots/locales/esES/npc_text_locale.sql: already exists in working directory
error: data/sql/Bots/locales/esMX/npc_text_locale.sql: already exists in working directory
error: data/sql/Bots/locales/ruRU/npc_text_locale.sql: already exists in working directory
error: data/sql/Bots/locales/zhCN/npc_text_locale.sql: already exists in working directory
error: data/sql/Bots/locales/zhTW/npc_text_locale.sql: already exists in working directory
error: data/sql/base/db_characters/characters_npcbot.sql: already exists in working directory
error: data/sql/base/db_characters/characters_npcbot_group_member.sql: already exists in working directory
error: data/sql/base/db_characters/characters_npcbot_stats.sql: already exists in working directory
error: data/sql/base/db_characters/characters_npcbot_transmog.sql: already exists in working directory
error: data/sql/base/db_world/creature_template_npcbot_appearance.sql: already exists in working directory
error: data/sql/base/db_world/creature_template_npcbot_extras.sql: already exists in working directory
error: data/sql/base/db_world/creature_template_outfits.sql: already exists in working directory
error: data/sql/custom/db_world/0000-00-00_npcbot_01_creature_template.sql: already exists in working directory
error: data/sql/custom/db_world/0000-00-00_npcbot_02_creature_equip_template.sql: already exists in working directory
error: data/sql/custom/db_world/0000-00-00_npcbot_03_npc_text.sql: already exists in working directory
error: data/sql/custom/db_world/0000-00-00_npcbot_04_creature_classlevelstats.sql: already exists in working directory
error: data/sql/custom/db_world/0000-00-00_npcbot_05_command.sql: already exists in working directory
error: data/sql/custom/db_world/2022_12_08_00_npc_text.sql: already exists in working directory
error: data/sql/custom/db_world/2022_12_17_00_command.sql: already exists in working directory
error: data/sql/custom/db_world/2022_12_17_01_command.sql: already exists in working directory
error: data/sql/custom/db_world/2022_12_23_00_command.sql: already exists in working directory
error: data/sql/custom/db_world/2022_12_29_00_command.sql: already exists in working directory
error: data/sql/custom/db_world/2023_01_02_00_npc_text.sql: already exists in working directory
error: npcbots_prepatch.log: already exists in working directory

**Comment by trickerer** [comment]
Do you have .cpp files in your src/server/game/AI/NpcBots/ folder?

If not, use git reset --hard and to apply patch use `patch -p1 < NPCBots.patch` instead

If you're sure you compiled core with bots, then check revision of core you run and compare it to your git head, see if it's different

**Comment by zhuyaozi** [comment]
THANK YOU!!! IT WORKS!
