### ISSUE TITLE
TOC-5 Bots mount but I mount and immediately dismount.

### ISSUE THREAD

**Issue by jdubs187** [trickerer/Trinity-Bots#389]
As the title says.
When I click to mount a wolf in TOC5 the bots all mount up properly but then I immediately dismount.
Any consecutive attempts to mount reproduces the same issue.

I know the TOC and Occulus discussions have happened alot in the past.
Haven't seen this issue posted.

AzerothCore rev. b938c1d427f5

**Comment by trickerer** [comment]
Not entirely sure what's going on with AC vehicle (and mounting in general) code, need to investigate.
Related: #388

**Comment by jdubs187** [comment]
@trickerer you can smack me for this. 

This bug was happening because I forgot to equip a lance. /facepalm
But that encounter doesn't work properly for me.
All the enemies only attack me and it's over in about 3 seconds lol
