### ISSUE TITLE
[AC] Не работает команда npcbot co rebind 

### ISSUE THREAD

**Issue by xBarselonx** [trickerer/Trinity-Bots#392]
Убрал ботов командой на макросе
MACRO 16777229 "Прогнать на врем" INV_Misc_QuestionMark
.npcbot co unbind wu
.npcbot co unbind shalannius
.npcbot co unbind kaerbrus
.npcbot co unbind kelv

Но обратно командой на макросе они не появляются
MACRO 16777230 "Вернуть бота все" INV_Misc_QuestionMark
.npcbot co rebind wu
.npcbot co rebind shalannius
.npcbot co rebind kaerbrus
.npcbot co rebind kelv

**Comment by menevia16a** [comment]
This is happening on TrinityCore as well. Only when unbinding all of them I think.
