### ISSUE TITLE
Bots can't enter 20-player dungeons

### ISSUE THREAD

**Issue by yj1118** [trickerer/Trinity-Bots#393]
Thanks to the author for his contribution.There is a problem here: After the robot starts a team, it cannot enter a large dungeon, can it be solved? Thanks

**Comment by trickerer** [comment]
Check bot config parameters in your `worldserver.conf`:
1. `NpcBot.Enable.Raid`
2. `NpcBot.Limit.Raid`

Read the description and set those accordingly to your needs

**Comment by yj1118** [comment]
> 2\. NpcBot.Limit.Raid

thank you very much!
