### ISSUE TITLE
[AC] [Bug] [Core] После последнего обновления сервер не запускается и пишет кучу ошибок.

### ISSUE THREAD

**Issue by Parkan1986** [trickerer/Trinity-Bots#397]
![image](https://user-images.githubusercontent.com/30984138/226700262-5ec252ad-aae0-4aaa-adab-b28e9f077707.png)

Эти логи идут бесконечно.Это при включении странствующих ботов,если их выключить то все нормально.Все Sql задействованы

Проверил на свеже созданном сервере происходит такая же проблема.

**Comment by Mitradis** [comment]
у меня все нормально собирается и работает, тоже АС.

**Comment by Parkan1986** [comment]
Заметил что если включены не стандартные ботыи выставлено больше чем 250 ботов ошибки идут бесконечно,если поставить 250 ботов,то сервер ругается только на ДК ботов и потом запускается

**Comment by Mitradis** [comment]
кол-во не должно превышать общее число ботом минус установленных статиков.

**Comment by Parkan1986** [comment]
это я знаю просто до обновы не было таких ошибок причем ошибки были постоянно одинаковые и шли бесконечно.

**Comment by Mitradis** [comment]
патч требует фикса под последнею версию АС. После изменений https://github.com/azerothcore/azerothcore-wotlk/commit/80ac0c958db4dd964c1d22ec29b7ec45f1078dac

**Comment by Parkan1986** [comment]
ну так я использую текущие исходники.никакие другие.
