### ISSUE TITLE
[TC] [AC] Bot not identify as players

### ISSUE THREAD

**Issue by Mitradis** [trickerer/Trinity-Bots#398]
Server and client not identified bots as player. It could be attributed to addons, as if they not correctly identified targets (as i originally thought). But today I noticed bot not have names above head as it have player (with my game settings where disabled names for NPCs). It proves what client identified bots as npc. It's not an addon problem. Strangely, bot pets are identified as players pets.
![WoWScrnShot_032123_211248](https://user-images.githubusercontent.com/21084600/226704531-5948b693-abea-413d-8de0-a4b9b07e7609.jpg)

**Comment by Mitradis** [comment]
можно задать как m_objectTypeId = TYPEID_PLAYER; но тогда через ->GetTypeId() сломается весь мод. Как я оыбчно пишу в таких случаях - корни проблем лежат в изначально ошибочной архитектуре кода.

**Comment by trickerer** [comment]
I assume bot pets are identified as "name's Pet" by client using two factors: being a CREATURE_TYPE_BEAST and being controlled - having owner guid, charmer guid or creator_guid != 0. Druid bots also qualify as pets by client's standards based on creature type being overriden with beast type.

The problem with client identifying bots as NPCs probably cannot be solved without client modification. Client does not use any type_id field or whatever, the classification is based on object guid structure, its high part to be exact. But even if high part is somehow replaced everywhere with player one AND client is okay with that, this will also break basic interactions like gossip menus, voices and probably visuals - client **needs** to know they are NPCs to accept those mechanics built especially for them.
