### ISSUE TITLE
Servers

### ISSUE THREAD

**Issue by oldmagic** [trickerer/Trinity-Bots#4]
This is not an issue but as i don't know of any other sites involving these Bots, yeah..

Is there anyone using these Bots on a public server?

Or is there even a website for these Bots? Or a sub reddit or what have you?

**Comment by trickerer** [comment]
#2 
Well I have an idea how to allow players to hire bots without seeking them out, but it will still require spawning bots, how about that?

**Comment by oldmagic** [comment]
Go for it :)

**Comment by trickerer** [comment]
[6f8f5af9d](https://github.com/trickerer/Trinity-Bots/commit/6f8f5af9d440dcbea9d1441cc43ae51455598360)
