### ISSUE TITLE
Crash often tonight

### ISSUE THREAD

**Issue by yj1118** [trickerer/Trinity-Bots#405]
[ce0e429928f4_worldserver.exe_[24-3_0-20-47].txt](https://github.com/trickerer/Trinity-Bots/files/11053298/ce0e429928f4_worldserver.exe_.24-3_0-20-47.txt)
[ce0e429928f4_worldserver.exe_[24-3_0-19-2].txt](https://github.com/trickerer/Trinity-Bots/files/11053300/ce0e429928f4_worldserver.exe_.24-3_0-19-2.txt)
[ce0e429928f4_worldserver.exe_[23-3_23-25-23].txt](https://github.com/trickerer/Trinity-Bots/files/11053301/ce0e429928f4_worldserver.exe_.23-3_23-25-23.txt)

**Comment by trickerer** [comment]
Don't duplicate issues please. #403

**Comment by yj1118** [comment]
> 请不要重复问题。#403


ok sorry to bother you
