### ISSUE TITLE
Start the server and report an error

### ISSUE THREAD

**Issue by yj1118** [trickerer/Trinity-Bots#406]
![image](https://user-images.githubusercontent.com/25011361/227326328-06a75673-984c-40d0-b21e-6247d484cfb8.png)
How to solve this problem?

**Comment by trickerer** [comment]
Your core is not up-to-date to your DB. Re-build starting from CMake.

This is NPCBots mod issue tracker, not AC/TC tracker or forum. Please report only NPCBots related issues and fill the template next time.

**Comment by yj1118** [comment]
> Your core is not up-to-date to your DB. Re-build starting from CMake.
> 
> This is NPCBots mod issue tracker, not AC/TC tracker or forum. Please report only NPCBots related issues and fill the template next time.

Thanks for reminding
