### ISSUE TITLE
[AC] [Bug/Crash] 

### ISSUE THREAD

**Issue by kasting** [trickerer/Trinity-Bots#407]
AzerothCore rev. 487f25f2e002 2023-03-25 08:03:47 +0700 (npcbots_3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)
I have successfully compiled the project and added the Eluna module
However, after running for a period of time, the worldserver.exe process will shut down for no reason.
I'm recompiling it in debug mode
Where can I find the crash record when the process is shut down

**Comment by kasting** [comment]
AzerothCore rev. 487f25f2e002 2023-03-25 08:03:47 +0700 (npcbots_3.3.5 branch) (Win64, Debug, Static) (worldserver-daemon)
<Ctrl-C> to stop.

   █████╗ ███████╗███████╗██████╗  ██████╗ ████████╗██╗  ██╗
  ██╔══██╗╚══███╔╝██╔════╝██╔══██╗██╔═══██╗╚══██╔══╝██║  ██║
  ███████║  ███╔╝ █████╗  ██████╔╝██║   ██║   ██║   ███████║
  ██╔══██║ ███╔╝  ██╔══╝  ██╔══██╗██║   ██║   ██║   ██╔══██║
  ██║  ██║███████╗███████╗██║  ██║╚██████╔╝   ██║   ██║  ██║
  ╚═╝  ╚═╝╚══════╝╚══════╝╚═╝  ╚═╝ ╚═════╝    ╚═╝   ╚═╝  ╚═╝
                                 ██████╗ ██████╗ ██████╗ ███████╗
                                ██╔════╝██╔═══██╗██╔══██╗██╔════╝
                                ██║     ██║   ██║██████╔╝█████╗
                                ██║     ██║   ██║██╔══██╗██╔══╝
                                ╚██████╗╚██████╔╝██║  ██║███████╗
                                 ╚═════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

     AzerothCore 3.3.5a  -  www.azerothcore.org

> Using configuration file       configs/worldserver.conf
> Using SSL version:             OpenSSL 1.1.1s  1 Nov 2022 (library: OpenSSL 1.1.1s  1 Nov 2022)
> Using Boost version:           1.81.0
 
Daemon PID: 11720

Process priority class set to HIGH
 
Loading Modules Configuration...
 
Using modules configuration:
> mod_LuaEngine.conf
> mod-zone-difficulty.conf.dist

**Comment by kasting** [comment]
[http://[kasting.tpddns.cn:888/487f25f2e002_worldserver.exe_[25-3_22-33-28].txt](http://kasting.tpddns.cn:888/487f25f2e002_worldserver.exe_[25-3_22-33-28].txt)](url)

**Comment by trickerer** [comment]
Please use gist.github.com to upload crashlogs, do not link third-party sources

**Comment by kasting** [comment]
![微信图片_20230223020008](https://user-images.githubusercontent.com/83107774/228135607-3f8b5dba-fb8d-4563-a2a7-ec276a588a18.png)
This morning the process crashed unexpectedly again, this time even the executive program disappeared. There was no crash log.

**Comment by trickerer** [comment]
No additional code could cause that, seems like antivirus intervention. Malware could be involved, too.

**Comment by kasting** [comment]
Looks like my firewall shut it down. But why the threat was detected. Should I whitelist the program?!
![111](https://user-images.githubusercontent.com/83107774/228439672-55583d70-2e1f-4125-bcdc-62707a401e8a.jpg)

**Comment by trickerer** [comment]
Normally whitelisting server exes isn't required. I suggest you scan your system first. Then, if nothing suspicious is found, you can blame your malware protection software and whitelist worldserver.exe.
