### ISSUE TITLE
[AC] [DBErrors]  DBErrors.log

### ISSUE THREAD

**Issue by saliven1970** [trickerer/Trinity-Bots#408]
**Description:**
DBErrors.log

**AzerothCore:**

**Current behaviour:**

Warning: GetData<m> on LONGLONG field .MAX(setguid) (.) at index 0.
SmartAIMgr: entryorguid -138893 source_type 0 id 1003 action_type 223 is using an action with no unused params specified in SmartAIMgr::CheckUnusedActionParams(), please report this.
SmartAIMgr: entryorguid -138879 source_type 0 id 1003 action_type 223 is using an action with no unused params specified in SmartAIMgr::CheckUnusedActionParams(), please report this.
SmartAIMgr: entryorguid -138869 source_type 0 id 1003 action_type 223 is using an action with no unused params specified in SmartAIMgr::CheckUnusedActionParams(), please report this.
SmartAIMgr: entryorguid -138820 source_type 0 id 1003 action_type 223 is using an action with no unused params specified in SmartAIMgr::CheckUnusedActionParams(), please report this.
SmartAIMgr: entryorguid 18497 source_type 0 id 6 action_type 41 is using a target 204 with no unused params specified in SmartAIMgr::CheckUnusedTargetParams(), please report this.

**Expected behaviour:**

**Steps to reproduce the problem:**

**TC / AC rev. hash/commit:** 

AzerothCore rev. 487f25f2e002 2023-03-25 08:03:47 +0700 (master branch)

**Operating system:**
Linux CentOS

**Comment by trickerer** [comment]
Why do you think this is related to NPCBots? They don't use SmartAI, not do bots repos have master branch

**Comment by saliven1970** [comment]
OK,This is AzerothCore error
