### ISSUE TITLE
Feature: Vehicles

### ISSUE THREAD

**Issue by xtracripper** [trickerer/Trinity-Bots#41]
Possible to make bots use mounts in dungeons?

Proposed:
Occulus: Bots mount same drake type as player, use drake spells when in combat. Dismount when player dismounts.
ToC: Bots mount horses, use shields, and use damage spells intelligently when in combat. Force dismount by dungeon script when joust phase is done.

**Comment by trickerer** [comment]
Sorry but this title is misleading

**Comment by Mr-Deadbeat** [comment]
all bots using same mount as player in Occulus would not work since all of the drakes you can choose have a different purpose one of them heals others dish out damage or can take damage so would not work sorry to say unless you can assign a drake for every bot also i have a feeling it would mean a lot of code just to make the bots use all the different functions the drakes have or i could be wrong not a coder ;)

**Comment by xtracripper** [comment]
Depends on how many bots you have. 5 bronze is a valid strategy. If you have 3 players and 2 bots, it would be helpful even if the bots just randomly hit buttons on a bronze drake too. That would cast the freeze spell from all bots pretty early and players could use their freeze spell later in the fight. The way it is currently, the bots are just 100% useless in the vehicle fights. So randomly hitting buttons would be better than nothing.

**Comment by xtracripper** [comment]
Just a note that fixing the drakes would also be useful for the daily quest "Aces High" (https://wotlk-twinhead.twinstar.cz/?quest=13413)

Fixing the horses/wolves would also be useful for the daily quest "Battle Before The Citadel" (https://wotlk-twinhead.twinstar.cz/?quest=13861) and "The Grand Melee" (https://wotlk-twinhead.twinstar.cz/?quest=13665)

**Comment by trickerer** [comment]
So far bots can enter and exit vehicles, but not change seats.
I managed to integrate vehicles into exisiting movement system, at least out of combat. This may be not enough though as some vehicles may need something like custom formation as part of the tactic, like Ulduar demolishers as they can eat attacks of each other.
Bots also already can cast same spells as player if controlling identical vehicles (including player attack dest targeting).
Stats scaling works too.

Not sure if I should just force bots to use same vehicle type as player and chain spell casts or to code some sort of generic AI plus tactics for special cases. Sound like quite an undertaking.

**Comment by xtracripper** [comment]
Ideally there would be a custom case for each type of vehicle which controls movement, and what attacks to use when. And for example in EoE, a role-based system would be good. A healer spec bot would use the drake healing spells, but a dps spec bot would use the drake dps spells. But that's an ideal state.

I would suggest you start with a basic state, get a good baseline functionality going. And then release that functionality and close this feature. Open a new feature specifically for the more ideal state. That way you can delay working on the ideal state until later if there is a more valuable issue or feature to work on. You could even put a checklist in a new feature and work on just one boss at a time in whatever order makes the most sense.

I think making the bots enter identical vehicles as the player and cast identical spells is a massive step forward for the bots overall. Compared with them standing there and staring at enemies now, it's night and day. Take a couple examples: in Oculus your drake's attacks basically get multiplied by 5, finishing the fight 5x faster. In ToC your basic melee attacks get multiplied by 5, finishing the fight 5x faster.

**Comment by trickerer** [comment]
**This is not finished**.

Notes:

- Players can't use Flame Shield (bots can)
- Life Burst heal does not stack with combo points. I can tempfix that but it has to be fixed properly on core level.
- EoE tested (success) but with some leeway (10 man).

**Comment by trickerer** [comment]
Any additional vehicle types have to be requested separately. Ulduar is kind of paused at the moment, going to prioritize other things now.

**Comment by xtracripper** [comment]
@trickerer
I have working ToC, made a couple small tweaks and now it's working great!
Oculus seems to work pretty good too, did a full run.
