### ISSUE TITLE
compile issue

### ISSUE THREAD

**Issue by wing-zacharias** [trickerer/Trinity-Bots#411]
Does this project only compile by msvc toolset? it looks like it won't compile on linux.

**Comment by Mr-Deadbeat** [comment]
it works under linux but the patch has not been merged with the latest changes from master so use @trickerers fork in the meantime you can find it at https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots

**Comment by wing-zacharias** [comment]
lol,thanks
