### ISSUE TITLE
[AC] [Enhancement] Turn it into a module for convenience/maintainability

### ISSUE THREAD

**Issue by 55Honey** [trickerer/Trinity-Bots#413]
**Description:**

Turn it into a module.

**AzerothCore:**
Unfortunalety opening issues is disabled [here](https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots), so I took it to this repo.

**Current behaviour:**
Currently players need to follow a specific guide and apply a core-patch to be able to use the npc bots.

**Expected behaviour:**

AC allows to add modules by just cloning them into a subfolder of the local source. There are no further steps required than re-running cmake/compiling, if all features of the module system are used. Even SQL including updates is handled by the core.

AC maintainers (wink, here is one) happily fork modules into the AC org and give the author full access.

There are various resources available...
- to create modules: https://www.azerothcore.org/wiki/create-a-module
- to PR potentially required hooks: https://www.azerothcore.org/wiki/hooks-script

I'll happily clarify any questions about the module system.

**Steps to reproduce the problem:**
n/a

**TC / AC rev. hash/commit:** 
n/a

**Operating system:** CHANGEME OS
n/a

**Comment by trickerer** [comment]
The short answer is: it's impossible.

Just like playerbots, a mod of this scale requires low-level code edits. Core developers will never be adding a new hook for every single piece of code I may need to inject.

https://github.com/azerothcore/azerothcore-wotlk/discussions/3936

**Comment by 55Honey** [comment]
Thanks for the reply!
I'm sad to hear it's too much work to convert it.
Either way, thanks for maintaining the branch, it seems that a lot of players enjoy it.
