### ISSUE TITLE
vehicle/dragons do not work correctly on Azorothcore but work perfectly on Trinitycore

### ISSUE THREAD

**Issue by 11hodgecal** [trickerer/Trinity-Bots#415]
Description:
This may be an issue with azorothcore itself as i know the player character is unable to stay on the warg in trial of the champion. but the only dungeon i have tested is the oculus but the bots will only stay on the dragons for up to 10 seconds when in trinitycore they dismount when you tell them to. which will also make eoe (EYE of Eternity) unplayable and various other aspects of other dungeons/raids unplayable.

Current behaviour:
NPC bots wont stay on vehicals ore beasts in azorothcore but will stay on the vehicles on trinitycore.

Expected behaviour:
NPC bots should stay on mount till you invoke the npcbot vehicle eject command. (similar functionality to the trinitycore version)

Steps to reproduce the problem:
n/a

TC / AC rev. hash/commit:
Your 3.3.5 AC fork

Operating system: CHANGEME OS
n/a

**Comment by trickerer** [comment]
The last time I checked player couldn't even fly using those drakes. Did that change?

**Comment by 11hodgecal** [comment]
The player character can stay on the dragon in the oculus now. Just the bots stay on the dragon for a small amount of time and exits them. I also tested trial of the champion which the player cant stay on the warg/horse. Ill test eye of eternity later but im assuming it will show the same results as the oculus.

**Comment by trickerer** [comment]
I'm talking about Oculus vehicles not being able to fly at all.

As for ToC5, you just need to have the lance equipped.

**Comment by 11hodgecal** [comment]
You can fly as well as the bots are able to fly they just eject from the mount after a very short no more then ten second period.

**Comment by trickerer** [comment]
Seems like it was indeed fixed. Well, good.
I'll push the fix to main repo soon.

https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/0ca8fe578fdc7c592b55d9f39698585cb2f417ab

**Comment by 11hodgecal** [comment]
The drakes work in eye of eternity and TOC5 horses/wargs work as well. ill close the issue as it is know fixed.
