### ISSUE TITLE
 [AC] Delay Attack Still not Functional

### ISSUE THREAD

**Issue by Day36512** [trickerer/Trinity-Bots#417]
Hey Trickerer!

Sorry to bug you again about this but doesn't seem like the delay commit worked. Bots are still attacking immediately. Thanks :)

**Comment by trickerer** [comment]
I have to admit I didn't test it thoroughly, so yeah.
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/304651efdf112141778473e3ac7cb34822cb163f

**Comment by Day36512** [comment]
Thanks man. Appreciate you tons.
