### ISSUE TITLE
Intermittent lag on server startup

### ISSUE THREAD

**Issue by xtracripper** [trickerer/Trinity-Bots#42]
Restarting several times fixes it.

Took 3 performance profile recordings in visual studio during the lag.
And took another 3 performance profile recordings in visual studio after I did restarts to fix the lag.

**BEFORE restarts (during lag)**
![image](https://user-images.githubusercontent.com/72840507/98885350-7b0aeb80-2457-11eb-8655-4ee4b435456f.png)
![image](https://user-images.githubusercontent.com/72840507/98885393-9118ac00-2457-11eb-9ba3-d081bfae8b74.png)
![image](https://user-images.githubusercontent.com/72840507/98885460-ac83b700-2457-11eb-8653-bd87e6a860e8.png)

**AFTER restarts (no more lag)**
![image](https://user-images.githubusercontent.com/72840507/98885476-ba393c80-2457-11eb-93f2-f0b411e56af1.png)
![image](https://user-images.githubusercontent.com/72840507/98885502-c58c6800-2457-11eb-814e-40500a2b3cb0.png)
![image](https://user-images.githubusercontent.com/72840507/98885527-d2a95700-2457-11eb-82b4-0011dd109f7d.png)

**Comment by trickerer** [comment]
How many bots do you have spawned?
How close to each other?
For how long the lag lasts?

**Comment by xtracripper** [comment]
it says this is the hottest block (by far) in every x_class_ai.cpp file:
```
if (!GlobalUpdate(diff))
  return;
```

I have 282 bots spawned total (all the regular classes).
14 of them are currently owned. (70021, 70034, 70051, 70053, 70227, 70230, 70233, 70265, 70311, 70324, 70351, 70355, 70356 and 70405)

None of the bots are much closer than 10 yards to each other, and there's no megacluster.

The lag lasts indefinitely until I restart multiple times (lag affects startup and never ceases).
I don't know what makes it start happening, but the way I restart my server is to force-kill the process id and then start again.
It doesn't always lag, maybe 10% of restarts or so, the problem comes.

**Comment by xtracripper** [comment]
![image](https://user-images.githubusercontent.com/72840507/98887511-b7d8e180-245b-11eb-8cce-5864c84b43e0.png)

The mage "global update" area was the hottest in my 3 "lag" samples.
bot_mage_ai.cpp (line 338) alone ate up 21.10% of the total worldserver cpu usage

**Comment by xtracripper** [comment]
Here's that same area, for the non-lagging sample. Both samples are approximately 60 seconds.

![image](https://user-images.githubusercontent.com/72840507/98888381-852fe880-245d-11eb-93b6-3afa4b7353d1.png)

Why is it hit 12877 times in the lagging sample, but only 2703 times in the non-lagging sample?

**Comment by trickerer** [comment]
I can't locate the source of lag by just looking at the code, so I'll have try to recreate your stuation and see what I can see.

**Comment by xtracripper** [comment]
It's churning on this for-loop when it's lagging, not sure why:

```
inline float bot_ai::_getTotalBotStat(uint8 stat) const
{
    int32 value = 0;
    for (uint8 slot = BOT_SLOT_MAINHAND; slot != BOT_INVENTORY_SIZE; ++slot)
        value += static_cast<BotStat>(_stats[slot])[stat];
```

**Comment by xtracripper** [comment]
I fixed the churning by eliminating the for-loop.
Not sure if it will help the sporadic lag issue at all.

I just duplicated every "_stats[slot][statType]" line in bot_ai.cpp like this example:
```
_stats[slot][statType] += val;
_statSum[statType] += val;
```

I defined _statSum in bot_ai.h like this:
`int32 _statSum[MAX_BOT_ITEM_MOD];`

Then I changed this:
```
int32 value = 0;
    for (uint8 slot = BOT_SLOT_MAINHAND; slot != BOT_INVENTORY_SIZE; ++slot)
        value += static_cast<BotStat>(_stats[slot])[stat];
```

To this:
```
    int32 const value = _statSum[stat];
    //for (uint8 slot = BOT_SLOT_MAINHAND; slot != BOT_INVENTORY_SIZE; ++slot)
    //    value += static_cast<BotStat>(_stats[slot])[stat];
```

MASSIVE cpu savings right there.

**Comment by trickerer** [comment]
Using hash_map container for constantly accessed stats was pretty stupid then, huh? Only if I could remember when and why I did this.

**Comment by xtracripper** [comment]
The profiler drove me to attack this specific part of the code.
I even added TC_LOG_ERROR() outputs and watched the glorious nonstop scroll in the console for several minutes.

**Comment by xtracripper** [comment]
But as for why the update(diff) functions were being called ~4.5-5x more than normal during lag scenario, I don't know.
But if the diff functions get overly called again, the bot stats total shouldn't be the main CPU hog anymore...

**Comment by xtracripper** [comment]
Have not had this issue since fixing the code mentioned above.
