### ISSUE TITLE
 [AC] [Bug] Frequently Bots Stop Attacking

### ISSUE THREAD

**Issue by Day36512** [trickerer/Trinity-Bots#421]
It's hard for me to pin down the issue precisely but it seems newly hired bots or just bots in general are not continuing to attack after some time. Starting in the human zone and hiring a mage bot, the mage attacked once before stopping altogether. Used a .die command. Issue persisted. There's other instances that are similar posted on discord.

EDIT: It also seems that ungrouped bots that the player owns might not be assisting.

**Comment by trickerer** [comment]
Negative on the ungrouped bots, at least no additional problems.

The problem you see is ranged spellcasters unable to properly participate in combat on lower levels.
Mage can't use Fireball / Frostbolt if rolled Arcane spec at init, but Arcane Missiles is level 8.
Another problem is that Druid can't do much as Feral on levels 1-19 until Cat Form is unlocked.
For other Warlock / Shaman I didn't notice anything wrong both in-game and in code.

https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/3296d5cd65b225f396667cd07f7022d39e939b30

**Comment by Day36512** [comment]
Thanks man.

**Comment by trickerer** [comment]
Related: #388 (see comments). Considering this resolved for now
