### ISSUE TITLE
[TC]  [Crash] [Group/Spell/Core] Crash when leave group in Dungeon with npcbots

### ISSUE THREAD

**Issue by zzyyll2** [trickerer/Trinity-Bots#422]
latest code
steps:
1. invite some npcbots to create a group
2. join a dungeon
3. leave group

crash at:
bot_ai.h
void SetTeleportFinishEvent(TeleportFinishEvent* tfevent) { ASSERT(!teleFinishEvent); teleFinishEvent = tfevent; }

i found teleFinishEvent has been called twice, then ASSERT crashed. 

SetTeleportFinishEvent been called by BotMgr::_teleportBot

**Comment by trickerer** [comment]
Can't confirm. I can create a group with bots, enter a dungeon (both normal and LFG) and leave party while in dungeon without crashing the server.

This crash was fixed in https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/ebeb716cc1cd83cfcbcbaaf3f332102b5b6bf147 (31 Mar)

**Comment by zzyyll2** [comment]
Thanks, I found  the bugfix and pulled it, i will test this night.

**Comment by trickerer** [comment]
So you lied about the latest source then?
> latest code

**Comment by zzyyll2** [comment]
My fault，i forgot to pull code，that time my latest code is 25 Mar, commit id: 5477d7bc02aecae4ba2c4992bbd675b5d0a1c61a

**Comment by zzyyll2** [comment]
Good job，it's ok, thanks.
