### ISSUE TITLE
[Suggestion] A command which lists the gear score of every bot in your party.

### ISSUE THREAD

**Issue by 11hodgecal** [trickerer/Trinity-Bots#423]
At the moment it is difficult to track the bots gear progress whould it be possible to do the suggestion ubove or allow being able to inspect the bots inventory to see there gearscore althogh i do know this may be impossible as the game sees them as npcs not players.

this will help with quickly being able to prioritize which bots will receive gear.

https://www.reddit.com/r/classicwow/comments/y7gs8g/how_is_gearscore_calculated/

**Comment by trickerer** [comment]
The link you provided only contains speculations and no actual formulas.
In fact, gear score calculation is kind of complicated. I couldn't find any C++ code doing that and GearScore addon code makes me slap my face. All I have right now is a primitive weighted bonus calculation for working with auto-equip options (not real gear score) and I don't like the idea of writing the whole thing from scratch just for a single application.
GearScore addon works with links, but still - it's not very good when you need to check 18 items per bot.

**Comment by xBarselonx** [comment]
trickerer, возможно ли добавить случайное снаряжение ботов которые вызывает игрок и использует их. Я имею ввиду, на battleground, боты экипированы, может ли эта экипировка применяться и к ботам которых нанимает игрок?
