### ISSUE TITLE
[AC] Bot Abort with BG Que

### ISSUE THREAD

**Issue by Day36512** [trickerer/Trinity-Bots#425]
Hey I was solo queing at bot level 19 and 29. It took 5 minutes to finally get any world server information but all I got was this:

BotBattlegroundEnterEvent: Aborting bot 282302 bg 2!
BotBattlegroundEnterEvent: Aborting bot 282296 bg 2!
BotBattlegroundEnterEvent: Aborting bot 282297 bg 2!
BotBattlegroundEnterEvent: Aborting bot 282298 bg 2!
BotBattlegroundEnterEvent: Aborting bot 282293 bg 2!
BotBattlegroundEnterEvent: Aborting bot 282291 bg 2!
BotBattlegroundEnterEvent: Aborting bot 282288 bg 2!
BotBattlegroundEnterEvent: Aborting bot 282287 bg 2!
BotBattlegroundEnterEvent: Aborting bot 282295 bg 2!
BotBattlegroundEnterEvent: Aborting bot 282300 bg 2!
BotBattlegroundEnterEvent: Aborting bot 282299 bg 2!
BotBattlegroundEnterEvent: Aborting bot 282301 bg 2!
BotBattlegroundEnterEvent: Aborting bot 282294 bg 2!
BotBattlegroundEnterEvent: Aborting bot 282290 bg 2!
BotBattlegroundEnterEvent: Aborting bot 282289 bg 2!
BotBattlegroundEnterEvent: Aborting bot 282292 bg 2!

**Comment by Day36512** [comment]
I think it ended up being interference with another mod

**Comment by trickerer** [comment]
The bots in queue lifetime history is not etirely clear yet, required some more work; I have a feeling that it differs between cores, too.
But basically bots start trying to enter BG shortly after players enters a qeueue. Player has 60 seconds to accept the invitation, plus 2 minutes before the match starts. Within 3 minutes all bots shall try to enter BG at least once.
There are only 3 reasons for bots to abort the BG entering event: either timed out (3 minutes passed), player logged out, or BG is already full (other players connected).
Bots will not be generated at all if BG debugging is enabled.

I had a strange bug where BG bot generation wouldn't work sometimes when trying to join as group. I have a report about the same problem with non-grouped attempts.

More work is requried on this front, but at least we have a start.

**Comment by Day36512** [comment]
Yeah I think it's a fantastic start. The issue ended up being a Cross Faction Battleground Mod that I removed. Works like a charm now.
