### ISSUE TITLE
[AC] [Feature Request] [Core] Wandering Bots Travel Speed Configuration Setting

### ISSUE THREAD

**Issue by archer-gh** [trickerer/Trinity-Bots#428]
**Description:**

This is a question to confirm whether it is by design that wandering bots seem to have a default travel speed faster than the human player?  

With my private server set on PvP mode, if I encounter any wandering bots in the wild at low levels (where I don't have access to mounts or other speed modification tools) and I do not wish to engage in a fight, the speed differential makes it impossible to run away if the wandering bot notices my character and engages me.  I can attempt to run, but eventually the bot will catch up and if they are higher level or I am ill equipped, it is certain death.

** AzerothCore:**

**Current behaviour:**

Wandering NPCbots will engage and pursue the player as expected.  If the player runs away the wandering bots will pursue, which is expected and also great.  However, the bots seem to be running faster than the player and no matter how far I run the bot(s) will eventually catch up making it impossible for the player to avoid the confrontation.

**Expected behaviour:**

Not expecting anything.  Just wanting to know if this was by design, and if so, is there a way to configure around it.

**Steps to reproduce the problem:**

1. See a wandering bot.  Let the bot notice the player character (e.g. get targeted)
2. Run away.

**TC / AC rev. hash/commit:** 

AzerothCore rev. 84988debe2fc 2023-04-12 16:01:16 +0700 (npcbots_3.3.5 branch) (Unix, RelWithDebInfo, Static)

**Operating system:**

Ubuntu Server 22.04 LTS

**Comment by archer-gh** [comment]
I suppose one issue I can think of is that the speed differential affects hunter kiting tactics in PvP, as bots would close separation distance faster than expected.

**Comment by trickerer** [comment]
The problem of bot movement speed is double-edged.

Normally, movement is point-based. In this mode server-controlled units move up to 99% of the time depending on performance and config. For bots this value is a tiny bit lower.
Combat movement is spline-based for melee bots (chase movement). This movement basically never stops.
Normal spawned static bots have base movement speed at 110% (of player base speed). Wandering bots have their speed reduced to 105%.
Then there are talens like Fleet Footed or Pursuit of Justice unlocked at level 35 or so.
Another thing is generated boots on wandering bots may have minor run speed increase.

So, player having Minor Speed kind of boots enchant will be faster than most wandering bots, but there is no chance to run away from some Rogues or Paladin (they are all Retri), probably Feral Druid, too. I can of course set their speed to 100% flat but I'm not sure that will change much - server controlled chasers will cut corners perfectly. And even reducing speed below 100% won't solve everything.

The config setting is probably the most appropriate way of managing this.

P.S.
Wandering bots will search for targets at about 45 yards and drop chased target at 60 yards.

**Comment by archer-gh** [comment]
You mention a configuration setting is the most appropriate way of managing this.  Is there an existing configuration in the worldserver.conf file that I've overlooked?

**Comment by trickerer** [comment]
No, sorry if that way misleading. I was speaking of a potential feature.

**Comment by archer-gh** [comment]
Thanks Trickerer.  I will change the title of this issue ticket to reflect a feature request.

**Comment by archer-gh** [comment]
Thanks for implementing this so quickly!  Since the data in the creature_template database has not changed (travelspeed = 1.10) and according to your statement above that wandering bots have speed reduced to 105% by default, in order to have wandering bot travel speed match human character at 100% speed, would the proper thing to do be set the NpcBot.Mult.Wanderer.Speed setting to 0.95?  Or should it be 0.90?

**Comment by trickerer** [comment]
No, wandering bots' speed multiplier get completely overriden with this value, so it's just `1.0` for 100% player speed.
