### ISSUE TITLE
Bot Pets won't follow after using command

### ISSUE THREAD

**Issue by kalamus** [trickerer/Trinity-Bots#43]
Bot pets seem to get stuck on "stay" after issuing "**.npcbot command stopfully**".
"**.npcbot command follow**" makes all my bots follow but the pets are stuck on "stay"

I have to **.npcb hide** and **.npcb show** to get new pets once this happens to fix it.

**Comment by Mr-Deadbeat** [comment]
this seems to happen on stay command now at least on my server didn't have any issues before that i can remember
but now all bots pets get stuck after issuing stay command once i get moving again the pets stay behind
are there differences in the code between windowns / linux that might cause this ?

OS Ubuntu 20.04 server
TC Commit: c2a0b78a051ea3301d8769b2c11fae00e14fe095
TC Bots: 2c6b08d5147b67a2bf8d659a59db9288c9f8a1d3
