### ISSUE TITLE
[TC] [AC] [Bug] Wandering bot's bonus bumped too fast

### ISSUE THREAD

**Issue by kbetmp001** [trickerer/Trinity-Bots#430]
**Description:**
the wandering bot's kill bonus goes to around 6g after level 50, way too fast 

**TrinityCore and AzerothCore**

**Current behaviour:**  
bonus goes to around 6g - 8g on level 50+ bot, significant bump compared to level 40+ (around 1-2g)

**Expected behaviour:**
Actually the level and income are not equality flat, bonuses should not be increased by equivalent proportion.

**Steps to reproduce the problem:**

1. find any wandering bot, kill and loot

**TC / AC rev. hash/commit:** 
AzerothCore rev. aac0149be517+ 2023-04-15 13:38:01 +0700 (npcbots_3.3.5 branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon)

**Operating system:** linux mint 21

my idea:
```
float maxgold = 50000;
    auto level = me->GetLevel();
    float basegold = maxgold/20*2/45 * (level>45?45:level);
    if (level>45)
        basegold += maxgold/20*4/15 * ((level>60?60:level)-45);
    if (level>60)
        basegold += maxgold/20*5/10 * ((level>70?70:level)-60);
    if (level>70)
        basegold += maxgold/20*9/10 * ((level>80?80:level)-70);
    float gold = (
        basegold/2 + ((_killsCount>5?5:_killsCount) * basegold/10)
        - ((_deathsCount>9?9:_deathsCount) * basegold/10)
    );
    if (gold < 0) gold = basegold/10;
    loot.gold = uint32(gold);
```
expected result
```
1 : 0.01g
2 : 0.02g
3 : 0.03g
4 : 0.04g
5 : 0.06g
6 : 0.07g
7 : 0.08g
8 : 0.09g
9 : 0.10g
10 : 0.11g
11 : 0.12g
12 : 0.13g
13 : 0.14g
14 : 0.16g
15 : 0.17g
16 : 0.18g
17 : 0.19g
18 : 0.20g
19 : 0.21g
20 : 0.22g
21 : 0.23g
22 : 0.24g
23 : 0.26g
24 : 0.27g
25 : 0.28g
26 : 0.29g
27 : 0.30g
28 : 0.31g
29 : 0.32g
30 : 0.33g
31 : 0.34g
32 : 0.36g
33 : 0.37g
34 : 0.38g
35 : 0.39g
36 : 0.40g
37 : 0.41g
38 : 0.42g
39 : 0.43g
40 : 0.44g
41 : 0.46g
42 : 0.47g
43 : 0.48g
44 : 0.49g
45 : 0.50g
46 : 0.57g
47 : 0.63g
48 : 0.70g
49 : 0.77g
50 : 0.83g
51 : 0.90g
52 : 0.97g
53 : 1.03g
54 : 1.10g
55 : 1.17g
56 : 1.23g
57 : 1.30g
58 : 1.37g
59 : 1.43g
60 : 1.50g
61 : 1.63g
62 : 1.75g
63 : 1.88g
64 : 2.00g
65 : 2.13g
66 : 2.25g
67 : 2.38g
68 : 2.50g
69 : 2.63g
70 : 2.75g
71 : 2.98g
72 : 3.20g
73 : 3.42g
74 : 3.65g
75 : 3.88g
76 : 4.10g
77 : 4.33g
78 : 4.55g
79 : 4.78g
80 : 5.00g
```

it should be great if we can adjust the bonus and drop rate in config file

**Comment by trickerer** [comment]
Just don't forget that there is a set of config options to adjust open world wandering bots' powers. They aren't supposed to be an easy kill since they may drop items, rares too (thankfully there are no high levels)
