### ISSUE TITLE
[AC] Assertoin Failed for New DBCs

### ISSUE THREAD

**Issue by Day36512** [trickerer/Trinity-Bots#431]
Been getting a new Assertion failed message that has happened 2/3rds the time after updating creaturedisplayinfo.dbc, creaturemodeldata.dbc and creaturedisplayinfoextra.dbc. This is likely a non-issue for most people but figured it might be good to have
![Capture](https://user-images.githubusercontent.com/118951051/232377712-93526c49-0c50-41c0-92f6-ccb55116b318.JPG)

**Comment by trickerer** [comment]
This issue wasn't caused by DBCs.
You have entries in `creature_template_npcbot_extras` for creature(s) not in `creature_template`.

Seems like I need to add some validation finally.
