### ISSUE TITLE
[TC] [Crash] [Core] DeadLord WanderingBots waypoint Crash 

### ISSUE THREAD

**Issue by leelf00** [trickerer/Trinity-Bots#433]
**Description:**

DeadLord WanderingBots waypoint Crash 

TrinityCore

**Current behaviour:**

CHANGEME Tell us what happens.
If this is a crash, post the crashlog (upload to https://gist.github.com/).

**Expected behaviour:**

Server Crash

**Steps to reproduce the problem:**
/home/pkgs/TrinityCore-3.3.5-with-NPCBots/src/server/game/AI/NpcBots/bot_ai.cpp:16909 in Evade ASSERTION FAILED:
  pos.m_positionZ > INVALID_HEIGHT
Me: MapID: 0 Map name: 'EasternKingdoms' X: 2479.47 Y: -4178.93 Z: 63.8777 O: 4.68532
GUID Full: 0xf1300121ae0006ae Type: Creature Entry: 74158  Low: 1710 Entry 74158
Name: Lotthicus
IsAIEnabled: true DeathState: 0 UnitMovementFlags: 2097152 ExtraUnitMovementFlags: 0 Class: 9
MoveSpline
spline Id: 44621647
flags:  Done CanSwim
time passed: 7763
total  time: 7763
spline point Id: 8
path  point  Id: 8
mode: Linear
points count: 11
point 0 : (2489.82, -4151.26, 50.2562)
point 1 : (2488.83, -4151.14, 50.2562)
point 2 : (2486.5, -4154.39, 50.748)
point 3 : (2484.16, -4157.63, 51.155)
point 4 : (2481.83, -4160.88, 51.0718)
point 5 : (2479.49, -4164.13, 51.3028)
point 6 : (2477.16, -4167.38, 53.1523)
point 7 : (2478.36, -4171.19, 55.5016)
point 8 : (2479.57, -4175, 59.1282)
point 9 : (2479.47, -4178.93, 63.8777)
point 10 : (2479.47, -4178.93, 63.8777)
GetCharmedGUID(): GUID Full: 0x0000000000000000 Type: None Low: 0
GetCharmerGUID(): GUID Full: 0x0000000000000000 Type: None Low: 0
No vehicle kit
GetGameClientMovingMe(): NULL
m_Controlled size: 0
AIName:  ScriptName: dreadlord_bot WaypointPath: 0 SpawnId: 0
Segmentation fault

**TC / AC rev. hash/commit:** 

TrinityCore rev. d6838fce4b7b 2023-04-16 10:10:46 +0700 (npcbots_3.3.5 branch) (Unix, Release, Static) 

**Operating system:** 
Ubuntu 22.04

**Comment by trickerer** [comment]
How many wandering bots do you use? And how long does it take to cause a crash at average?

**Comment by leelf00** [comment]
I set "NpcBot.WanderingBots.Continents.Count = 200" in worldserver.conf.Crash occuerd about 24-48 hours after server startup.
