### ISSUE TITLE
[AC][TC] [Bug] [Interface] Bots Are Incorrectly Identified as Enemy Guardians

### ISSUE THREAD

**Issue by archer-gh** [trickerer/Trinity-Bots#434]
**Description:**

Hired NPCbots appear to be identified as enemy guardians when attempting to show or hide their names.

**AzerothCore**

**Current behaviour:**

Names of any player characters, mobs, NPCbots, pets, etc., are configured via the WoW client options under Interface -> Names
When attempting to toggle on or off the names of NPCbots that have been hired, the option box that results in their names being hidden or shown is Guardians, under Enemy Players.

This does not affect wandering bots, which are correctly identified simply as NPCs.

**Expected behaviour:**

NPCBots could be considered Guardians, but it seems wrong that they are identified as Enemy Player Guardians instead of Friendly Player Guardians.

**Steps to reproduce the problem:**

1. As an Alliance character (I haven't tested Horde yet), hire an NPCBot, of the same faction for simplicity's sake. 
2. Open the game interface options.
3. Navigate to Names
4. Check the radio box under Enemy Players, Guardians to see the names disappear or appear on top of the hired NPCBot's head. 

**TC / AC rev. hash/commit:** 

AzerothCore rev. aac0149be517 2023-04-15 13:38:01 +0700 (npcbots_3.3.5 branch) (Unix, RelWithDebInfo, Static)
(this is a couple commits behind the most recent, but this bug has been present for many commits, at least a few months now)

**Operating system:**

Ubuntu Server 22.04 LTS

**Comment by trickerer** [comment]
Yeah, very strange actually, especially considering that under Nameplates section they're classified correctly as friendly guardians.

**Comment by trickerer** [comment]
On TC this happens as well, in and out of party, so problem must be in ownership indication markers client receives, like owner guid.
