### ISSUE TITLE
[TC] [] [Visual UI Bug] Visual UI Compatibility Issue with Transmog Patch

### ISSUE THREAD

**Issue by Lexaraj** [trickerer/Trinity-Bots#438]
First off, please bear with me. This is the first issue I've reported on Github so, if this is not relevant to this patch or if I have reported this incorrectly, please let me know.

I've run into a small visual issue when using NPC Bots alongside rochet2's Transmog Patch where the inventory icons of the gear that is given to the NPC Bot show as blank in both the chat log and in the gossip frame. After opening the Transmog Gossip frame, it will take those Icons from the Transmog frame and apply them to the previously blank icons, in an unaligned, out of chatbox, way. 

Below is what the icons look like before speaking to the Transmog vendor:
![NPC Bot 1](https://user-images.githubusercontent.com/103298090/234672903-bcd6f431-9e7a-499c-8c5f-e44bc0de77b7.jpg)
![NPC Bot 2](https://user-images.githubusercontent.com/103298090/234672934-dff1d67a-81f3-4496-a002-fa93e329f569.jpg)

This is what the current Transmog Gossip Frame looks like.
![NPC Bot 3](https://user-images.githubusercontent.com/103298090/234673077-8597d5fb-44a2-4efa-969f-52b5f04daf0e.jpg)

Now, after opening the Transmog Gossip Frame, this is what happens when asking the NPC Bot to show their gear. In the upper left you can see the Transmog Gossip Frame Icons. They appear linked to the chat frame inventory icons, as they scroll up and down when the chat scrolls.
![NPC Bot 4](https://user-images.githubusercontent.com/103298090/234673388-e6cee0f3-378f-48c7-bc3d-43a17cfe187d.jpg)

I believe this is linked directly or partly to the 'InventoryIcon' section of 'DBCStructure.h'. When applying the Transmog Patch to the TrinityCore-3.3.5-With-NPC-Bots source, this section has a conflict. When patching, I kept the incoming changes to that area from the Transmog patch, which also looks identical to the base TrinityCore 3.3.5. This is how it looks: https://gist.github.com/Lexaraj/54277bd06e1dba188ee04832ae904f5f

However, I decided to recompile and leave everything the way it was except for that part, and kept the original code in that section to that of the TrinityCore-3.3.5-With-NPC-Bots. This is how it looks: https://gist.github.com/Lexaraj/16e6847289ac288dbfea1ea506c7b7ab

After recompiling with that, the issue essentially swapped, with the chat and gossip frame icons being present and correct for the NPC Bots but now the Gossip Frame for the Transmogrifier was incorrect.
![Transmog 2](https://user-images.githubusercontent.com/103298090/234676532-29689f31-6d85-4daa-96d4-6a157ffabf4f.jpg)
![Transmog 3](https://user-images.githubusercontent.com/103298090/234676546-4bc7f95e-54f6-485b-a64b-a8adc56e8553.jpg)

I am unsure if I may have just merged incorrectly or if this simply a hard incompatibility between these two aspects of each patch. Also, I am not even 100% sure it's related specificly to the Transmog Patch or if it's simply the method of how they icons are pulled to the Gossip frame.

As I said, apologies if this is not how issues are usually reported. Please let me know if I need to include more info, or if this is even the proper place to report such an issue. Thank you!

**Comment by trickerer** [comment]
This is an incompatibility issue. The difference between transmog's version and the original version of `ItemDisplayInfoEntry`'s `InventoryIcon` field is too big. Original is a `char*` but transmog patch changes that to `char**` and processes it as such, breaking bot code.

Here is what you could try:
Keep the Rochet's version of `ItemDisplayInfoEntry`. In bot_ai.cpp go to `bot_ai::_AddItemLink()` method and look for `itemDisplayEntry->InventoryIcon` - this is the only occurence in code. Change it to `itemDisplayEntry->InventoryIcon[0]`.

**Comment by Lexaraj** [comment]
That worked perfectly. 

After recompiling with rochet2's version of 'DBCStructure' and changing `itemDisplayEntry->InventoryIcon` to `itemDisplayEntry->InventoryIcon` in 'bot_ai.cpp', both UI elements are functioning as they would if using each standalone.

Thank you very much for the support with this, very appreciated!

**Comment by trickerer** [comment]
You're welcome
