### ISSUE TITLE
Ask for instructions on flags and links in the creature_template_npcbot_wander_nodes table

### ISSUE THREAD

**Issue by Greyisttot** [trickerer/Trinity-Bots#441]
I want to be able to customize their refresh point

**Comment by trickerer** [comment]
Working with wander points using just DB is inconvenient.

While in-game in GM mode use `.npcb wp sp` to spawn wander points in current map. Then the other wp commands can be used on spawned npcs.

`.npcb wp link` to list links.
`.npcb wp info` to get WP info.
`.npcb wp move` to move WP to your location.
Check other commands yourself.
Be careful - one wrong command used may ruin selected wp and all of its links and you'll have to fix them (or re-import WPs to DB, restart the server and start from scratch)

Flags you can find in code (I assume TC) in [botwanderful.h](https://github.com/trickerer/TrinityCore-3.3.5-with-NPCBots/blob/npcbots_3.3.5/src/server/game/AI/NpcBots/botwanderful.h#L18). They aren't listed separately in wp info though so it could be difficult to work with it at start.

What you see in DB in links field is a list of space separated wp ids that this wp is linked to (note that it can be a one-way link). Don't get scared by the format `2316:0 2317:0 ` - trailing space is nothing, the `:0` part is unused currently, in future it may become a chance/weight for next wp selection.

**Comment by Greyisttot** [comment]
Thank you very much for your detailed answer
