### ISSUE TITLE
[AC] [Bug] [Core] NPCBot "Valgar" is casting Shadow Bolt as a Level 23 Paladin

### ISSUE THREAD

**Issue by RedMageofRed** [trickerer/Trinity-Bots#443]
Hello! Thank you so much for your continued work on the bots; it's so great to be able to encounter them in the world and play in battlegrounds with them. I'd like to report an issue I found while I was playing. If this is already known, I apologize in advance.

**Description:**

NPCBot 77886 "Valgar" at level 23 is casting Shadow Bolt during battle, even though he is a Paladin. I have tried to replicate this with other Paladin bots, but they don't seem to be casting it like Valgar does, maybe because Valgar was specifically level 23?

![WoWScrnShot_043023_185119](https://user-images.githubusercontent.com/50994703/235382384-75aba90a-1b96-44a1-b7b7-8de51d545877.jpg)

**AzerothCore:**

**Current behaviour:**

When engaging the Valgar bot out in the world, he will eventually cast Shadow Bolt during the encounter (at level 23).

**Expected behaviour:**

Valgar (or any Paladin bot) should not be casting Shadow Bolt.

**Steps to reproduce the problem:**

1. Log in as a Horde character with wandering bots enabled (and probably a good number to ensure Valgar spawns)
2. .npcbot go 77886
3. Fight Valgar a while
4. He should eventually try casting Shadow Bolt, maybe when he's lower on health? It might also only happen if he's around level 23.

**TC / AC rev. hash/commit:** 

AzerothCore rev. 0dbcf427fb6f 2023-04-26 11:50:06 +0700 (AzerothCore branch) (Win64, Release, Static) (worldserver-daemon)
NPCBots v5.3.161a

**Operating system:** Windows 10 Pro

**Comment by trickerer** [comment]
This spell is probably given to him by some deprecated item. Try to list his gear - you can talk to him in GM mode.

**Comment by RedMageofRed** [comment]
I'm sorry, I didn't think I could talk to the wandering bots in GM mode like the normal spawned bots. I've already reset the server since then. I'll try going around to any non-Warlock bot around level 23 and checking their gear and spell lists to see if I can find anything. 

This isn't related and it's a very minor issue, but while checking this, I did notice that some bots had two copies of unique items equipped:

![WoWScrnShot_050123_081151](https://user-images.githubusercontent.com/50994703/235456259-d6b4cd6a-39ab-45ad-97e3-5ad32dbcee58.jpg)

![WoWScrnShot_050123_081622](https://user-images.githubusercontent.com/50994703/235456756-78495ee7-9a27-4cac-b1e5-94bd4e2a6060.jpg)

**Comment by trickerer** [comment]
Yeah, bots don't check item unique-ness. They never did.

As for original issue - it is too late to check now, You'll have very hard time trying to encounter such a bot again. But if you do, feel free to re-open this issue.
