### ISSUE TITLE
[TC] [Crash] [Core] Crash after select character with npcbot

### ISSUE THREAD

**Issue by leelf00** [trickerer/Trinity-Bots#446]
**Description:**

CHANGEME Description of the problem or issue here.

**TrinityCore or AzerothCore:**
TrinityCore 

**Current behaviour:**

CHANGEME Tell us what happens.
If this is a crash, post the crashlog (upload to https://gist.github.com/).

**Expected behaviour:**

CHANGEME Tell us what should happen instead.

**Steps to reproduce the problem:**
TrinityCore rev. 722795c7930d 2023-05-04 12:08:47 +0700 (npcbots_3.3.5 branch) (Unix, Release, Static) (worldserver-daemon) ready...
TC>
/home/pkgs/TrinityCore-3.3.5-with-NPCBots/src/server/game/AI/NpcBots/botmgr.cpp:1238 in AddBot ASSERTION FAILED:
  bot->IsNPCBot()

**TC / AC rev. hash/commit:** 
TrinityCore rev. 722795c7930d 2023-05-04 12:08:47 +0700 (npcbots_3.3.5 branch) (Unix, Release, Static) (worldserver-daemon) 

**Operating system:** Ubuntu 22.04

**Comment by trickerer** [comment]
Post a debug crashlog, sir. I'm not solving riddles here.

**Comment by leelf00** [comment]
I will try reapply SQL files.Thanks.
