### ISSUE TITLE
[AC] [Bug] Issues when applying patch

### ISSUE THREAD

**Issue by Falladis** [trickerer/Trinity-Bots#453]
Hi there, tried to apply the patch and got this output in the terminal.

```NPCBots.patch:1530: trailing whitespace.
('70541', 'ruRU', 'Снять бафф', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),		
NPCBots.patch:2388: trailing whitespace.
-- 
NPCBots.patch:2427: trailing whitespace.
-- 
NPCBots.patch:2447: trailing whitespace.
-- 
NPCBots.patch:2489: trailing whitespace.
-- 
error: patch failed: src/server/game/Entities/Player/KillRewarder.cpp:165
error: src/server/game/Entities/Player/KillRewarder.cpp: patch does not apply```

**Comment by trickerer** [comment]
Patches are generated from existing AC/TC forks with bots.

If patch doesn't apply - provide core revision.

**Comment by heathertoni** [comment]
I've been trying to apply the patch here as well, same issue as the original poster, if you need the core revision, here it is

fd6941de7c7e+ (AzerothCore)

**Comment by trickerer** [comment]
This revision is from a month ago. You have to either use latest supported AC revision (see README) or use older patch version which will apply to your older AC version.

<details><summary>prepatch log</summary>
<p>

trickerer@trickerer-PGE MINGW64 /e/AppServ
$ git clone --depth 2000 -b master https://github.com/azerothcore/azerothcore-wotlk ac_temp
Cloning into 'ac_temp'...
remote: Enumerating objects: 26922, done.
remote: Counting objects: 100% (26922/26922), done.
remote: Compressing objects: 100% (11062/11062), done.
remote: Total 26922 (delta 16880), reused 23546 (delta 15158), pack-reused 0
Receiving objects: 100% (26922/26922), 251.27 MiB | 2.31 MiB/s, done.
Resolving deltas: 100% (16880/16880), done.
Updating files: 100% (7246/7246), done.

trickerer@trickerer-PGE MINGW64 /e/AppServ
$ git clone --depth 200 -b master https://github.com/trickerer/trinity-bots bots_temp
Cloning into 'bots_temp'...
remote: Enumerating objects: 1287, done.
remote: Counting objects: 100% (1287/1287), done.
remote: Compressing objects: 100% (493/493), done.
remote: Total 1287 (delta 849), reused 1193 (delta 774), pack-reused 0
Receiving objects: 100% (1287/1287), 9.01 MiB | 2.32 MiB/s, done.
Resolving deltas: 100% (849/849), done.

trickerer@trickerer-PGE MINGW64 /e/AppServ
$ cd bots_temp/

trickerer@trickerer-PGE MINGW64 /e/AppServ/bots_temp (master)
$ git reset --hard 84fae76419
HEAD is now at 84fae76 NPCBots: Update README

trickerer@trickerer-PGE MINGW64 /e/AppServ/bots_temp (master)
$ cd ../ac_temp/

trickerer@trickerer-PGE MINGW64 /e/AppServ/ac_temp (master)
$ git reset --hard fd6941de7c7e
Updating files: 100% (1206/1206), done.
HEAD is now at fd6941de fix(Core/SmartAI): Prevent MOVE_TO_POS from creating large distances between target (#15899)

trickerer@trickerer-PGE MINGW64 /e/AppServ/ac_temp (master)
$ cp ../bots_temp/AC/NPCBots.patch .

trickerer@trickerer-PGE MINGW64 /e/AppServ/ac_temp (master)
$ patch -p1 < NPCBots.patch
patching file .github/README.md
patching file .gitignore
patching file appveyor.yml
patching file data/sql/Bots/locales/esES/npc_text_locale.sql
patching file data/sql/Bots/locales/esMX/npc_text_locale.sql
patching file data/sql/Bots/locales/ruRU/npc_text_locale.sql
patching file data/sql/Bots/locales/zhCN/npc_text_locale.sql
patching file data/sql/Bots/locales/zhTW/npc_text_locale.sql
patching file data/sql/base/db_characters/characters_npcbot.sql
patching file data/sql/base/db_characters/characters_npcbot_group_member.sql
patching file data/sql/base/db_characters/characters_npcbot_stats.sql
patching file data/sql/base/db_characters/characters_npcbot_transmog.sql
patching file data/sql/base/db_world/creature_template_npcbot_appearance.sql
patching file data/sql/base/db_world/creature_template_npcbot_extras.sql
patching file data/sql/base/db_world/creature_template_outfits.sql
patching file data/sql/custom/db_world/0000-00-00_npcbot_01_creature_template.sql
patching file data/sql/custom/db_world/0000-00-00_npcbot_02_creature_equip_template.sql
patching file data/sql/custom/db_world/0000-00-00_npcbot_03_npc_text.sql
patching file data/sql/custom/db_world/0000-00-00_npcbot_04_creature_classlevelstats.sql
patching file data/sql/custom/db_world/0000-00-00_npcbot_05_command.sql
patching file data/sql/custom/db_world/2022_12_08_00_npc_text.sql
patching file data/sql/custom/db_world/2022_12_17_00_command.sql
patching file data/sql/custom/db_world/2022_12_17_01_command.sql
patching file data/sql/custom/db_world/2022_12_23_00_command.sql
patching file data/sql/custom/db_world/2022_12_29_00_command.sql
patching file data/sql/custom/db_world/2023_01_02_00_npc_text.sql
patching file data/sql/custom/db_world/2023_03_12_00_creature_template_npcbot_wander_nodes.sql
patching file data/sql/custom/db_world/2023_03_14_00_creature_wander_nodes.sql
patching file data/sql/custom/db_world/2023_03_21_00_creature_template_npcbot_wander_nodes.sql
patching file data/sql/custom/db_world/2023_03_22_00_creature_template.sql
patching file data/sql/custom/db_world/2023_04_04_00_creature_template_npcbot_wander_nodes.sql
patching file data/sql/custom/db_world/2023_04_11_00_creature_template_npcbot_wander_nodes.sql
patching file npcbots_prepatch.log
patching file src/common/Common.h
patching file src/common/Utilities/EventProcessor.h
patching file src/server/apps/worldserver/worldserver.conf.dist
patching file src/server/database/Database/Implementation/CharacterDatabase.cpp
patching file src/server/database/Database/Implementation/CharacterDatabase.h
patching file src/server/game/AI/CoreAI/UnitAI.h
patching file src/server/game/AI/CreatureAI.h
patching file src/server/game/AI/NpcBots/bot_Events.h
patching file src/server/game/AI/NpcBots/bot_GridNotifiers.h
patching file src/server/game/AI/NpcBots/bot_ai.cpp
patching file src/server/game/AI/NpcBots/bot_ai.h
patching file src/server/game/AI/NpcBots/bot_archmage_ai.cpp
patching file src/server/game/AI/NpcBots/bot_bm_ai.cpp
patching file src/server/game/AI/NpcBots/bot_dark_ranger_ai.cpp
patching file src/server/game/AI/NpcBots/bot_death_knight_ai.cpp
patching file src/server/game/AI/NpcBots/bot_dreadlord_ai.cpp
patching file src/server/game/AI/NpcBots/bot_druid_ai.cpp
patching file src/server/game/AI/NpcBots/bot_hunter_ai.cpp
patching file src/server/game/AI/NpcBots/bot_mage_ai.cpp
patching file src/server/game/AI/NpcBots/bot_necromancer_ai.cpp
patching file src/server/game/AI/NpcBots/bot_paladin_ai.cpp
patching file src/server/game/AI/NpcBots/bot_priest_ai.cpp
patching file src/server/game/AI/NpcBots/bot_rogue_ai.cpp
patching file src/server/game/AI/NpcBots/bot_sea_witch_ai.cpp
patching file src/server/game/AI/NpcBots/bot_shaman_ai.cpp
patching file src/server/game/AI/NpcBots/bot_spellbreaker_ai.cpp
patching file src/server/game/AI/NpcBots/bot_sphynx_ai.cpp
patching file src/server/game/AI/NpcBots/bot_warlock_ai.cpp
patching file src/server/game/AI/NpcBots/bot_warrior_ai.cpp
patching file src/server/game/AI/NpcBots/botcommands.cpp
patching file src/server/game/AI/NpcBots/botcommon.h
patching file src/server/game/AI/NpcBots/botdatamgr.cpp
patching file src/server/game/AI/NpcBots/botdatamgr.h
patching file src/server/game/AI/NpcBots/botdpstracker.cpp
patching file src/server/game/AI/NpcBots/botdpstracker.h
patching file src/server/game/AI/NpcBots/botdump.cpp
patching file src/server/game/AI/NpcBots/botdump.h
patching file src/server/game/AI/NpcBots/botgiver.cpp
patching file src/server/game/AI/NpcBots/botgossip.h
patching file src/server/game/AI/NpcBots/botmgr.cpp
patching file src/server/game/AI/NpcBots/botmgr.h
patching file src/server/game/AI/NpcBots/botspell.cpp
patching file src/server/game/AI/NpcBots/botspell.h
patching file src/server/game/AI/NpcBots/bottext.h
patching file src/server/game/AI/NpcBots/botwanderful.cpp
patching file src/server/game/AI/NpcBots/botwanderful.h
patching file src/server/game/AI/NpcBots/bpet_ai.cpp
patching file src/server/game/AI/NpcBots/bpet_ai.h
patching file src/server/game/AI/NpcBots/bpet_archmage.cpp
patching file src/server/game/AI/NpcBots/bpet_dark_ranger.cpp
patching file src/server/game/AI/NpcBots/bpet_death_knight.cpp
patching file src/server/game/AI/NpcBots/bpet_dreadlord.cpp
patching file src/server/game/AI/NpcBots/bpet_druid.cpp
patching file src/server/game/AI/NpcBots/bpet_hunter.cpp
patching file src/server/game/AI/NpcBots/bpet_mage.cpp
patching file src/server/game/AI/NpcBots/bpet_necromancer.cpp
patching file src/server/game/AI/NpcBots/bpet_priest.cpp
patching file src/server/game/AI/NpcBots/bpet_sea_witch.cpp
patching file src/server/game/AI/NpcBots/bpet_shaman.cpp
patching file src/server/game/AI/NpcBots/bpet_warlock.cpp
patching file src/server/game/AI/NpcBots/lib/bottraits.h
patching file src/server/game/AI/SmartScripts/SmartScript.cpp
patching file src/server/game/Battlegrounds/Battleground.cpp
patching file src/server/game/Battlegrounds/Battleground.h
patching file src/server/game/Battlegrounds/BattlegroundMgr.h
patching file src/server/game/Battlegrounds/BattlegroundQueue.cpp
patching file src/server/game/Battlegrounds/BattlegroundQueue.h
patching file src/server/game/Battlegrounds/Zones/BattlegroundWS.cpp
patching file src/server/game/Battlegrounds/Zones/BattlegroundWS.h
patching file src/server/game/Conditions/ConditionMgr.cpp
patching file src/server/game/DungeonFinding/LFGMgr.cpp
patching file src/server/game/DungeonFinding/LFGScripts.cpp
patching file src/server/game/Entities/Creature/Creature.cpp
patching file src/server/game/Entities/Creature/Creature.h
patching file src/server/game/Entities/Creature/CreatureData.h
patching file src/server/game/Entities/Creature/GossipDef.h
patching file src/server/game/Entities/Creature/TemporarySummon.cpp
patching file src/server/game/Entities/Creature/enuminfo_CreatureData.cpp
patching file src/server/game/Entities/Item/Item.h
patching file src/server/game/Entities/Object/Object.cpp
patching file src/server/game/Entities/Object/Object.h
patching file src/server/game/Entities/Player/KillRewarder.cpp
patching file src/server/game/Entities/Player/Player.cpp
patching file src/server/game/Entities/Player/Player.h
patching file src/server/game/Entities/Player/PlayerUpdates.cpp
patching file src/server/game/Entities/Totem/Totem.cpp
patching file src/server/game/Entities/Transport/Transport.cpp
patching file src/server/game/Entities/Unit/StatSystem.cpp
patching file src/server/game/Entities/Unit/Unit.cpp
patching file src/server/game/Entities/Unit/Unit.h
patching file src/server/game/Entities/Vehicle/Vehicle.cpp
patching file src/server/game/Entities/Vehicle/Vehicle.h
patching file src/server/game/Globals/ObjectMgr.cpp
patching file src/server/game/Globals/ObjectMgr.h
patching file src/server/game/Grids/Notifiers/GridNotifiers.cpp
patching file src/server/game/Grids/Notifiers/GridNotifiers.h
patching file src/server/game/Groups/Group.cpp
patching file src/server/game/Groups/Group.h
patching file src/server/game/Groups/GroupMgr.cpp
patching file src/server/game/Handlers/BattleGroundHandler.cpp
patching file src/server/game/Handlers/ItemHandler.cpp
patching file src/server/game/Handlers/SpellHandler.cpp
patching file src/server/game/Instances/InstanceScript.cpp
Hunk #2 succeeded at 617 (offset 17 lines).
Hunk #3 succeeded at 638 (offset 17 lines).
patching file src/server/game/Instances/InstanceScript.h
patching file src/server/game/Maps/Map.cpp
patching file src/server/game/Maps/MapMgr.cpp
patching file src/server/game/Movement/MotionMaster.cpp
patching file src/server/game/Movement/MovementGenerators/PointMovementGenerator.cpp
patching file src/server/game/OutdoorPvP/OutdoorPvP.cpp
patching file src/server/game/Scripting/ScriptMgr.cpp
patching file src/server/game/Scripting/ScriptMgr.h
patching file src/server/game/Server/WorldSession.cpp
patching file src/server/game/Spells/Auras/SpellAuraEffects.cpp
patching file src/server/game/Spells/Auras/SpellAuras.cpp
patching file src/server/game/Spells/Spell.cpp
patching file src/server/game/Spells/Spell.h
patching file src/server/game/Spells/SpellEffects.cpp
patching file src/server/game/Spells/SpellInfo.cpp
patching file src/server/game/Spells/SpellInfo.h
patching file src/server/game/Spells/SpellInfoCorrections.cpp
patching file src/server/scripts/Commands/cs_npc.cpp
patching file src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjalAI.cpp
patching file src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal_trash.cpp
patching file src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_viscidus.cpp
patching file src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/boss_grand_champions.cpp
Hunk #1 succeeded at 207 (offset 5 lines).
patching file src/server/scripts/Northrend/IcecrownCitadel/boss_icecrown_gunship_battle.cpp
patching file src/server/scripts/Northrend/Naxxramas/boss_four_horsemen.cpp
patching file src/server/scripts/Northrend/Nexus/Oculus/oculus.cpp
patching file src/server/scripts/Pet/pet_mage.cpp
patching file src/server/scripts/Spells/spell_dk.cpp
Hunk #1 succeeded at 501 (offset 5 lines).
Hunk #2 succeeded at 877 (offset 5 lines).
Hunk #3 succeeded at 2131 (offset 52 lines).
patching file src/server/scripts/Spells/spell_druid.cpp
patching file src/server/scripts/Spells/spell_generic.cpp
patching file src/server/scripts/Spells/spell_hunter.cpp
patching file src/server/scripts/Spells/spell_mage.cpp
patching file src/server/scripts/Spells/spell_paladin.cpp
patching file src/server/scripts/Spells/spell_priest.cpp
patching file src/server/scripts/Spells/spell_rogue.cpp
patching file src/server/scripts/Spells/spell_shaman.cpp
patching file src/server/shared/DataStores/DBCStructure.h
patching file src/server/shared/DataStores/DBCfmt.h
patching file src/server/shared/SharedDefines.h

trickerer@trickerer-PGE MINGW64 /e/AppServ/ac_temp (master)
$


</p>
</details>
