### ISSUE TITLE
[TC][AC][Feature Request] Ongoing gold cost for Bots

### ISSUE THREAD

**Issue by Borgio22** [trickerer/Trinity-Bots#454]
Absolutely love the bot system developed here for my own family server but I realised it reminded me of the Mercenary system from Everquest.

In that system there was a cost to initally hire the bot, but also an ongoing hourly gold cost the bots would deduct from you to keep "adventuring".  I think that would be amazing if it could be added as an optional thing, although im not too sure how feasible it is.

The cost was less than the initial hiring cost but id imagine using the same scaling code as for initial hire, but as a separate entry in the config would be great.

Again, thanks for this mod, its made small manning raids with a few friends so much fun!

**Comment by trickerer** [comment]
I don't think this is going to be a thing.

That's a lot of work for miscellaneous feature, plus have ownership management which allows players to skip periodic triggers like this.
And if it's implemented as a 'bots get their share of looted money'  thing or 'dropped gold scaling with number of bots' (like XP scaling) - that seems boring and strays too far from the original idea.

Sorry.
