### ISSUE TITLE
Bot's Faction value

### ISSUE THREAD

**Issue by 396842276** [trickerer/Trinity-Bots#46]
I'm wondering if we can change the faction values in creature_template table from 35 to diffrent values seperately.
according to [https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130081/FactionTemplate](url)

1-PLAYER, Human
2-PLAYER, Orc
3-PLAYER, Dwarf
4-PLAYER, Night Elf
5-PLAYER, Undead
6-PLAYER, Tauren
115-PLAYER, Gnome
116-PLAYER, Troll
1610-PLAYER, Blood Elf
1629-PLAYER, Draenei

So that horde player won't be able to hire any ally bot, and bots can fight each other from two sides,
and can be be affected by boss's spell?

**Comment by 328950225** [comment]
if use the plyerbot mod to npcbot .That's also great.

**Comment by Ryu1254** [comment]
I try it before the Bot Service Creature patch. you could change the faction 35 to anything else, the bot you spawn in the world will be friendly or hostile or neutral depend on what you set. but i am not sure with the Bot Services creation will take account of the faction restriction or not

**Comment by 396842276** [comment]
@Ryu1254 Thanks for replying, I'll try it out.

**Comment by trickerer** [comment]
1) Bots are already hostile to each other but not immediately (14, 1801, 1802 for monster, horde and alliance respectively). In a big enough group of spawned bots of different factions, a single wrong spellcast will turn into carnage (warlocks like to do that)

2) Bots are designed to be hireable even if hostile which is an improvement in my opinion

3) What bossfights would benefit from that? I don't know of any where faction value is used

4) Faction value in creature_template table is irrelevant. Faction is stored in characters_npcbot table and is set at bot creation/loading

**Comment by 396842276** [comment]
First of all, thanks for replying this, and sorry for my bad English.
1.When we played alone, some boss's spell that should be cast on players randomly, and it will only target the character which we controled, bots won't be affected by most of that spells as your pet. That makes some fights become harder(or easier? lol, Maexxna's Web Spray for example).I want to know if bots can be changed to take those spells for us.
2. I'd like to share a zhCN verson of npc_text, I translated it myself. Only shaman's Manage roles.../heal need some change. 
[npc_text_locale.txt](https://github.com/trickerer/Trinity-Bots/files/5670655/npc_text_locale.txt)

**Comment by trickerer** [comment]
I see. Unfortunately, boss scripts do not check unit's faction to determine if it is player or not. Some spells may only target players, so bots are unaffected by them - this is a complex problem with no simple solution

Thanks for the translation. I appreciate help with someting I could never do myself

**Comment by 396842276** [comment]
emm... thanks for detailed explain

So is it possible to make bots do things when bot is within a specific distance of some object/unit.
things like this: 
 >flee from certain groundspell(objects like the little hellfire maybe?) 
 >attack certain target like LK's Valkyrie and Saurfang's Blood Beast etc.
If the thought is workable, I think it will need to save the certain object/unit's ID into a DB table?

**Comment by Ryu1254** [comment]
the way I play is using the icon target..(heal, tank, dps)
for example: attack certain target like LK's Valkyrie and Saurfang's Blood Beast etc.
I set Saurfang with skull (tank target)
when the fight start, every bot will attach saurfang. when adds spawn, I set the add with the Star (DPS target), then all bot will attack the adds except the tank.  it's not automatically, but it's good enough to do that fight without any problem. 

the only problem with bot stand in fire, is they follow the player.. if you move far enough, they will move with you.. it's not optimal.

**Comment by trickerer** [comment]
> flee from certain groundspell(objects like the little hellfire maybe?)

https://github.com/trickerer/Trinity-Bots/commit/f4f66672a5f0837d647b249da7229b8e43d7c7db

**Comment by Ryu1254** [comment]
> > flee from certain groundspell(objects like the little hellfire maybe?)
> 
> [f4f6667](https://github.com/trickerer/Trinity-Bots/commit/f4f66672a5f0837d647b249da7229b8e43d7c7db)

I tested in ICC10 normal: ..Marrowgar fight and Lady deathwhisper working good. they don't stay in fire
ICC25H... they try very very hard.. but end up burn in fire anyway.. too much fire to handle.. 

but other boss like Rotface or Putricide, they don't move from slim puddle.
I also try in TOC 10H... the first boss, Gormok the Impaler, they put lot of fire.. bot dont move at all..
I guess not all skill are not mark as AOE damage skill so but don't recognize to move.

**Comment by trickerer** [comment]
Not all aoe spells come from aoe cast effects. Scripts often use invisible npc spawns which periodically cast those aoe spells and there is no generic way of finding them, they have to be added manually. I was testing on Janalai fight (Zul'Aman) which is pretty much as tight as it can get.
