### ISSUE TITLE
[TC] [Bug] [Core] No XP in battlegrounds with bots

### ISSUE THREAD

**Issue by biglad** [trickerer/Trinity-Bots#468]
no XP rewards in BGs

https://wowpedia.fandom.com/wiki/Experience_point#:~:text=Players%20will%20now%20be%20awarded,(honorable%20kills%20not%20included).

[32ef070](https://github.com/trickerer/TrinityCore-3.3.5-with-NPCBots/commit/32ef070f06152268450302f4e06a93cd7abf94d9)

**Nix/Win**

**Comment by trickerer** [comment]
I disabled XP for killing BG bots intentionally. You're not supposed to get XP for honorable kills in BG. There is probably a config option to override this but I'm not sure.

If you mean BG objectives then provide an example. I clearly remember returning WSG flag dropped by bot giving experience.

**Comment by trickerer** [comment]
Feel free to re-open this issue if and when you're ready to elaborate further. Closing for now.
