### ISSUE TITLE
 [AC]BotDataMgr::UnregisterBot: bot 70552 (Mirror Image (Blademaster)) not found!

### ISSUE THREAD

**Issue by lemonmomomo** [trickerer/Trinity-Bots#469]
hi，trickerer
I have encountered a problem!Discovered when shutting down worldserver.
prompt：BotDataMgr::UnregisterBot: bot 70552 (Mirror Image (Blademaster)) not found!
Bot70552 cannot be hired

I cannot see my added bot70552 on the service bot70000 in the game, but bot70551 does not have this issue.
I used translation tools to translate, please forgive me.

**Comment by trickerer** [comment]
Blademaster is disabled by default because his Mirror Image will crash your server. Please don't use him.

As for bot 70552 - this is a special unit, a BM's summon which you're not even supposed to be able to spawn.

**Comment by lemonmomomo** [comment]
。。。I just crashed when I was playing the game.
Now I understand. Thank you for your reply.
