### ISSUE TITLE
Enhancement - Bot Warlock Affliction improvement

### ISSUE THREAD

**Issue by Ryu1254** [trickerer/Trinity-Bots#47]
Hello, 

it's quite a while I played with the Warlock bots comparing affliction and destruction talent, I start gear up the bot with some ICC 10/25 gear. but I notice the warlock in affliction do not much skill in affliction skill and the DPS is very poor, In recount addon I see the bot cast incinerate, corruption, immolate, shadow bolt.. but no Haunt , unstable Affliction or curse of Agony.. if I block some skill that I don't want the bot use.. like incinerate, corruption or immolate hoping the bot use other skill.. niet... I see only Corruption and Shadow bolt spamming only. Would be nice if affliction spec can do more dps

![warlock affliction](https://user-images.githubusercontent.com/72590132/101267604-78cf4080-3728-11eb-8ae1-3e3d9a897998.png)
![warlock affliction with skill block](https://user-images.githubusercontent.com/72590132/101267605-7bca3100-3728-11eb-830a-8daee368bb6a.png)

**Comment by trickerer** [comment]
Affliction is the same story as mage Arcane spec. Not only I have no experience with it, but also the rotation relies on mechanics spread all over the source code.

**Comment by Ryu1254** [comment]
It doesn't has to be perfect. here what I found on google about affliction rotation.

"Life Tap → Shadow Bolt → Haunt → Unstable Affliction → Corruption → Curse of Agony
Replace Shadow Bolt with Drain Soul when target HP is less than 25%
Don’t reapply DoTs earlier than needed. Spells like Corruption and Drain Soul remember the stats you have the moment you’ve cast them (even if the buffs wear off during the spell) – use that to maximise your damage."

yeah about arcane mage too. I notice, it just doing frost bolt and auto attack.. But I did not add another enhancement for that yet :) 


hey.. but I do have something to share, if you interest.. about bot gear tracking
I play a lot with your bot and I love it. I do ICC 10/25 Raid with bot.. gear them, gem and enchanting them like a real player.. 
but at certain point, you loose track of what bot has what gear, and is it gemmed / enchanted  etc...
So I create this SQL view, to be add in the Character BD.. and with some imagination.. I use excel to connect to this view and put conditional formatting with color to easy view..
[BOT equipment.txt](https://github.com/trickerer/Trinity-Bots/files/5670146/BOT.equipment.txt)

it the lease I can contribute in any way.. im not a C++ Coder. but i do quite good with SQL..

**Comment by trickerer** [comment]
Awesome

**Comment by trickerer** [comment]
It took some doing to get Glyph of Life Tap to work, but I think the spec is good enough now. Didn't test its DPS, but I think it's still lower than in Destruction. Anyway, I'll push it tomorrow so you can see for yourself.

**Comment by 396842276** [comment]
> So I create this SQL view, to be add in the Character BD.. and with some imagination.. I use excel to connect to this view and put conditional formatting with color to easy view..
> [BOT equipment.txt](https://github.com/trickerer/Trinity-Bots/files/5670146/BOT.equipment.txt)

@Ryu1254 

thanks for sharing this, but I don't understand how to "use excel to connect to this view and put conditional formatting with color to easy view..."

I changed the BOT equipment.txt where the table name is wotlk_xxx to fit my tables and create the SQL view use Navicat.
then what should I do with excel?

**Comment by Ryu1254** [comment]
> It took some doing to get Glyph of Life Tap to work, but I think the spec is good enough now. Didn't test its DPS, but I think it's still lower than in Destruction. Anyway, I'll push it tomorrow so you can see for yourself.

Cool.. i'll test it out. and let you know.

**Comment by Ryu1254** [comment]
this is a little bit off topic. but I make it short.
1 - you need to connect your Excel to mysql Server using the odbc connection. here a how to do it.
     https://helpdeskgeek.com/office-tips/excel-to-mysql/
2 - when it ask you what table / view you want to use. choose the view you created in Mysql
3 - use this SQL query statement 
      Select *
      from [your view in mysql]
4 - then you should see all the data in Excel.

I attach my excel sheet that i use as exemple. I delete the mysql connector reference for security purpose. but you should be able to use this excel to connect to your data source.

[NPCBot Gear tracking.xlsx](https://github.com/trickerer/Trinity-Bots/files/5674473/NPCBot.Gear.tracking.xlsx)

it's not perfect as view, but it's good enough to quick pick/choose the gear for bot when doing dungeon/raid.

hope this help.
