### ISSUE TITLE
Compatibility for Master Build

### ISSUE THREAD

**Issue by StonedCookieGaming** [trickerer/Trinity-Bots#472]
Hey would it be possible to add compatibility for bots in the Dragonflight build?

**Comment by trickerer** [comment]
I'll be straight: I'm not going to port this project to any version beyound 3.x.x.

But if you're asking if it's at all possible - then yes, everything is possible if you have the source code. As far as I know master branch isn't radically different, but adding all the new spells, class ai revamp and adjustments for new/changed game mechanics... My estimate is 50-80 hours of work to do it correctly for a competent programmer (the patch is almost 90k lines currently, probably 80k without SQLs).
