### ISSUE TITLE
[TC] [AC] [Request] [NPCBots: Wanderer] Possibility in config to choose how many wanderer bots are spawned for each level bracket

### ISSUE THREAD

**Issue by Boxhead78** [trickerer/Trinity-Bots#473]
Would be awesome if we could choose for which level bracket Wanderer-NPCBots spawn. Example:
Level 1-10: 20%
Level 11-20: 0%
Level 21-30: 10%
Level 31-40: 5%
Level 41-50: 5%
Level 51-60: 20%
Level 61-70: 20%
Level 61-80: 20%

This would mean that 20% of NpcBot.WanderingBots.Continents.Count would spawn at waypoints ranging from 1-10, none would spawn at waypoints ranging from 11-20 and so on.

I'm currently using waypoints for Outland and Northrend created by RussianRanger and noticed a lot more bots are spawning between level 60-80 than level 1-59. I assume it's due to the sheer amount of waypoints placed in Outland and Northrend.

**Comment by Russianranger** [comment]
Just to add flavor here - I only put about 4 to 6 "spawn" nodes per zone - typically 1-2 in the appropriate settlement locations. Obviously across 7 zones in Outlands and 9 zones in Northrend - can come out to 64-96 nodes to spawn in general. Will take a look at the flags today but if its not possible to weight the spawns based on level - I can shave back a few spawns in the settlements and set them back to 0 on the flags, which may help with any imbalance in the spawning algorithm. There were a couple settlements that I put two spawn nodes in.

**Comment by trickerer** [comment]
Yeah... selected node is random so level depends on spawn node levels frequency.
This is a long-needed change.

**Comment by trickerer** [comment]
https://github.com/trickerer/Trinity-Bots/commit/6a0eaff2106b4a25de87c56541eb8169428aeb89
