### ISSUE TITLE
[AC] [Patch] Patch Error

### ISSUE THREAD

**Issue by Onshare** [trickerer/Trinity-Bots#474]
AC last submit(https://github.com/azerothcore/azerothcore-wotlk/commit/d525949316f2e1bbe8b93b8de1a8bc4c861221cb ) failed patch。
conflict at ： src/server/game/Entities/Creature/CreatureData.h

**Comment by trickerer** [comment]
typo in commit message

**Comment by zhouchen1113** [comment]
> typo in commit message

thanks for paying attention this patch bug. 
But it seems like the problem has always existed.
conflict at 
error: patch failed: src/server/game/Entities/Creature/CreatureData.h:80

**Comment by lemonmomomo** [comment]
Hunk #1 FAILED at 80.
1 out of 2 hunks FAILED -- saving rejects to file src/server/game/Entities/Creature/CreatureData.h.rej
