### ISSUE TITLE
[AC] [Bug/Crash]

### ISSUE THREAD

**Issue by DykeRz** [trickerer/Trinity-Bots#476]
**Description:**
When worldserver.exe going to "Wandering bots spawn" its stucking and closing

Clean installation AC crashing worldserver.exe when start

**AzerothCore:**

**Current behaviour:**

Crashlog
(https://gist.github.com/DykeRz/3f99363ebb3fb59be400f4d78e91e54d)

**Expected behaviour:**

Corrently start worldserver.exe

**Steps to reproduce the problem:**

start worldserver.exe

**AC rev. hash/commit:** 

AzerothCore rev. a0e2a5156f36 2023-06-02 15:54:46 +0700 (npcbots_3.3.5 branch) (Win64, Debug, Static)

**Operating system:**
Windows 10 Pro

**Comment by trickerer** [comment]
Did you change `NpcBot.WanderingBots.Continents.Levels`? If yes, try default settings; do not try to set last two brackets - there are no nodes for that level range.

**Comment by trickerer** [comment]
Thanks for your report, it would be a shame to find it out myself tomorrow morning.
