### ISSUE TITLE
can't add mod-eluna

### ISSUE THREAD

**Issue by qiuyu123456** [trickerer/Trinity-Bots#477]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK2019	无法解析的外部符号 "void __cdecl Addmod_eluna_masterScripts(void)" (?Addmod_eluna_masterScripts@@YAXXZ)，函数 "void __cdecl AddModulesScripts(void)" (?AddModulesScripts@@YAXXZ) 中引用了该符号	worldserver	C:\fs\tmp\wow source code\azerothcore-wotlk-master\build\src\server\apps\modules.lib(ModulesLoader.obj)	1

**Comment by trickerer** [comment]
Tell me how is this related to bots? This is just an eluna linking error. Clean project, re-run CMake and re-build. If problem persists, ask at eluna issue tracker.

**Comment by qiuyu123456** [comment]
> 
Sorry, yes, I found out this is an issue with Eluna
