### ISSUE TITLE
.npc move not working with npcbots

### ISSUE THREAD

**Issue by opicron** [trickerer/Trinity-Bots#48]
Thank you for your effort on making Bots working with TrinityCore. Much appreciated! I am *really* enjoying solo play with bots and dungeon with friends and bots 👍 

When I dont delete my bots they remain ingame. Which is perfect-- however unfortunately I am a bit stupid and sometimes forget where I spawned them initially.

I tried to .npc move [id] the bot to my location. Unfortunately this does not work anymore, as the GUID is not the ID. What does work is: .lookup creature [name] I can find them again and spawn to their position. 

I think the documentation should be adjusted. Or the command adjusted to get the GUID from an lookup.

Wonderful work, thanks again. I'd gladly donate for your spend time if you have a link somewhere.

**Comment by 396842276** [comment]
Just try to add a npcbot giver (.npc spawn 70000) then you can hire all the bots and no need to know where they are.

**Comment by trickerer** [comment]
Thanks for your kind words, and for this note. I like to see that people enjoy results of my silly coding here.

If you want to donate use [my paypal link](https://paypal.me/trickerer), if it works for you.
