### ISSUE TITLE
[Question] Intense Cold keeps stacking on bots

### ISSUE THREAD

**Issue by Selence-Liuis** [trickerer/Trinity-Bots#482]
Hi,

I want npcbots to be treated as player when choosing spell targets by bosses, so I did some custom modification based on [AzerothCore-wotlk-with-NPCBots](https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots).
more precisely, I modified **[src/server/game/AI/CoreAI/UnitAI.h](https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/blob/npcbots_3.3.5/src/server/game/AI/CoreAI/UnitAI.h)**, replaced all related
`target->GetTypeId() != TYPEID_PLAYER`  to `!(target->IsPlayer() || target->IsNPCBot())`

at first it works fine, not until I run into *Keristrasza* at **The Nexus**.
its spell [Intense Cold](https://www.wowhead.com/spell=48094/intense-cold) just keep stacking on bots, and any bots movement can not remove the stack as expected, while this skill works fine for player.

Any ideas how I can fix this? many thanks.

**Comment by trickerer** [comment]
Checked the code and tested it in-game.
Your changes are irrelevant, this is just a bug (seems like an old one, too). `Unit::RemoveAurasWithInterruptFlags()`, with flag 8 (`AURA_INTERRUP_FLAG_MOVE`) is never called for creatures. Intense Cold is only removed automatically when Keristrasza dies and spell 48094 is removed from her.

Requires a serious core fix.

**Comment by Selence-Liuis** [comment]
> 

thanks, i'll issue a bug at ac.
