### ISSUE TITLE
[enhancement]Can bots only spawned when one player enter the map, so save our cpu and memory

### ISSUE THREAD

**Issue by zzyyll2** [trickerer/Trinity-Bots#484]
Now bots will be spawned to any maps on startup,  can we set to spawn bots only when one player enter the map, despawn when no player in the map, so save our cpu and memory and reduce carbon dioxide emissions[smile].

**Comment by trickerer** [comment]
Wandering bots you mean? It's not possible without serious adjustments to map system. Wandering bots don't have creature spawn data for map to use when grid is loaded. So, once grid is unloaded all creatures get despawned, and if wandering bot gets despawned - it's gone forever (until server restart).

If you don't have hardware capabilities to keep player-accessible grids loaded then you'd better wait 'till per-map setting are added - config setting(s) to only spawn wandering bots on selected maps, supposed to reduce the load for solo servers by 40% compared to current state. Or just reduce their numbers.

Anothing thing to note: AFAIK AC still didn't reimplement grids unload so all grids visited by active objects stay loaded forever, implies you're actually supposed to have hardware good enough to keep up with it (whatever is the number of unique grids players may visit within X hours).

**Comment by zzyyll2** [comment]
Thanks for the info, I thought the map would unload when no players were on it.
It's fun to watch wandering bots fight monsters, or kill them, or be killed by them, but it's pointless when no player interact with them, so i thought they should be despawned when on player on the map, and then system would unload the map from memory.

**Comment by zzyyll2** [comment]
I found a configuration item in worldserver.conf
#
#    GridUnload
#        Description: Unload grids to save memory. Can be disabled if enough memory is available
#                     to speed up moving players to new grids.
#        Default:     1 - (enable, Unload grids)
#                     0 - (disable, Do not unload grids)

GridUnload = 1

it means unload map when no player on it?

**Comment by trickerer** [comment]
Yes. It that a recent AC change or you're looking is TC worldserver.conf?

**Comment by zzyyll2** [comment]
I am using TC，thanks
