### ISSUE TITLE
[AC] [Bug] [Spell] spell70157 cannot automatically disappear

### ISSUE THREAD

**Issue by moncat2005** [trickerer/Trinity-Bots#488]
Npcbots to be unable to move,when player and npcbots hit spell 70157(SPELL_ICE_TOMB_DAMAGE) in the Battle of Sindragosa(ICC).
The DEBUFF(70157) has always existed, cannot automatically disappear.
Even if it is no longer in the dungeon(ICC),causing npcbots to be unable to move.
Please consider fix this problem,THX.
![debuff-70157](https://github.com/trickerer/Trinity-Bots/assets/34859687/eea7a9c7-c327-4735-a37d-1ef9bc96eb10)

**Comment by trickerer** [comment]
Looks like you have changes that allow player-only spells (SPELL_ATTR3_ONLY_TARGET_PLAYERS) to be cast on bots.

Use `.npcbot kill` for workaround.

**Comment by moncat2005** [comment]
I have not changed the npcbots code, and currently this 70157 skill is also valid for npcbots. 
After leaving the dungeon, this DEBUFF remains attached and still valid. 
Npcbot cannot be moved until the world server is restarted.
