### ISSUE TITLE
.npcbot delete not working if owner not dismissed bot and gear equiped

### ISSUE THREAD

**Issue by opicron** [trickerer/Trinity-Bots#49]
I am having troubles trying to delete an npc bot which is not dismissed by its owner and has gear equipped.

Tried all the commands I could find but I am missing something.

- How can I take control of the bot as GM admin when not dismissed.
- How can I have bot unequip his equiment if I am not owner.

**Comment by trickerer** [comment]
There is no way currently to just delete bot with gear equipped

If bot is currently following its owner you can use '.npcbots remove' command
If bot owner is absent: while in GM mode use gossip menu <Debug>->Reset owner

On free bot use '.npcbot add' command, after that you can dismiss it.

**Comment by opicron** [comment]
Mhm I tried your suggestions:
Npcbot remove results in “you must select player or controlled npcbot”
Npcbot add results in “you must select uncontrolled npcbot”

If I speak with the npcbot I can only hire him. Which leads to the unequip issue. Or is there another gossip menu?

**Comment by opicron** [comment]
Fixed this particular bot by lowering the timeout of bot owner last login to one hour.

**Comment by trickerer** [comment]
I want to add the ability to delete bot with gear for convenience sake
