### ISSUE TITLE
[TC] [AC] [Feature] [Core] Sorting of items in Bot Gear Bank

### ISSUE THREAD

**Issue by Mr-Deadbeat** [trickerer/Trinity-Bots#491]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

hey @trickerer would it be possible to code a sorting algorithm into the bot gear bank so all items of the same name get listed one after the other will make it much easier to sort trough all the gear amassed noticed this today i sorted all the gear yesterday and today when i checked the gear bank they were mixed again so did not know if i had that particular gear already or how many my eyesight is not the best in the world so have a hard time seeing things clearly "old age creeping up on me" ;)

also as a positive note to the gear bank feature no more crap cluttering my bank lol was a pain in the past ;)
thanks again for adding this

### TrinityCore or AzerothCore

Both

### Core rev. hash/commit

Azerothcore rev. 240d2928f1fd+ 2023-06-05 02:45:16 +0000 (master branch) (Unix, Release, Static)

### Operating system

win10 client / server ubuntu 20.04.6

**Comment by trickerer** [comment]
I'll do that, but it'll work only for withdrawal menu. Deposit menu will stay sorted by bag slots.
