### ISSUE TITLE
Hunk # FAILED and can't find file to patch

### ISSUE THREAD

**Issue by Retro1995** [trickerer/Trinity-Bots#492]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

While i try use patch command i have very many errors like
can't find file to patch at input line
Hunk # FAILED at
How can I remember this has never happened half a year ago. 

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

6b846df6a36e4ce72e9c26313d14aae70bad33e5

**Comment by trickerer** [comment]
The patch gets updated every saturday, which is about 12 hours from now.

**Comment by Retro1995** [comment]
I'm talking about errors, this is normal? And what should I choose when the patch ask me about Y\N?

**Comment by Retro1995** [comment]
I can't figure out if the patch was applied correctly or not.

**Comment by Mitradis** [comment]
Ty. You prepatched version have this errors too https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/blob/npcbots_3.3.5/npcbots_prepatch.log#L303 that why i am ask.

**Comment by Retro1995** [comment]
Ty. You prepatched version have this errors too https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/blob/npcbots_3.3.5/npcbots_prepatch.log#L303 that why i am ask.

**Comment by trickerer** [comment]
That's just an old file I forgot for some reason. Prepatched repositories don't get reset-and-patched every time they update. Instead, they receive direct code updates and then patches are created using `git diff-tree`.
Also, prepatched repo has build status badge in README and in last commit status https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots#readme. That how you know it will build without errors. You only need to build it, patch becomes irrelevant if you use prepatched repo.
