### ISSUE TITLE
NPCBots sometimes have outdated health in raid frames

### ISSUE THREAD

**Issue by xtul9** [trickerer/Trinity-Bots#493]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

I didn't yet discover when it happens, but sometimes the display of bot's health can get stuck in one place. It's only visual, the real HP is as expected.

For example, in a BG, a bot can respawn, but its health is stuck on 0. If I click on it, I can see its real hit points in unit frame.

This also occurs in dungeons. It seems to happen randomly, current HP doesn't seem to matter.

/reload remedies this for a moment, but the issue happens again eventually. In my experience it took around 20 minutes of playing to occur at first, then it occurred all the time.

If it matters, I use ElvUI from here: https://github.com/ElvUI-WotLK/ElvUI

### Expected behaviour

Bot hit points in raid frames should be the same as actual bot hit points. It should update as before the fixes related to displaying bots in BG raid frames and leaderboards (before [this commit](https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/6106b918e1))

### Steps to reproduce the problem

1) Queue for BG or DF with a full party of bots
2) Play for ~20 minutes (that was in my case). I recommend playing as a healer, makes it more visible
3) Notice hit points getting stuck on raid frames

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. 400d73c9b938+ 2023-06-09 17:09:22 +0700 (AzerothCore branch) (Win64, RelWithDebInfo, Static)

### Operating system

Windows 10

**Comment by trickerer** [comment]
Probably could be solved by implementing player-like updates to out of range members.
But it requires storing and manging Group in bot_ai. Hm.

**Comment by xtul9** [comment]
Just in case - the bug also occurs when the bot is within range. My tank bot died while I was healing it because I was sure its HP was ~85%.
