### ISSUE TITLE
[AC] [Bug] [Spell] ICC: Gunshipbattle Cannon Spell "Cannon-Blast" cooldown resets after NPCBots outside of cannon use ability

### ISSUE THREAD

**Issue by Boxhead78** [trickerer/Trinity-Bots#494]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Cooldown of Spell "Cannon-Blast" of one of the cannons (tested with alliance side) resets after a NPC-Bot uses a class-ability which results into infinite cooldown.

Also happens for other spells of vehicles like when you encounter Malygos.

### Expected behaviour

Cannon-Blast cooldown should only be 1 second even if a NPCBot uses an ability.

### Steps to reproduce the problem

1) Start ICC Gunshipbattle
2) Go into one of the cannons
3) Make sure not all bots are in cannons
4) See cooldown resetting without using ability

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. fcfa7f049c50 2023-06-10 08:53:38 +0200 (npcbots_3.3.5 branch) (Win64, Release, Static) (authserver)

**Comment by trickerer** [comment]
Basically this is a side effect of bots having owner guid. This simplifies a ton of things for bots in core but when player has some unit charmed (like vehicle) any spell cast by owner unit triggers global CD on client's side.
Need to test pets/guardians with charmed creatures. This could be a base core issue, or even a 3.3.5 client's problem.
There was an attempt to remedy this by switching to creator guid but that caused different problems so it was reverted.
