### ISSUE TITLE
 [AC] [Crash] Can't get in BG

### ISSUE THREAD

**Issue by lemonmomomo** [trickerer/Trinity-Bots#497]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

ASSERTION FAILED appears when I click Join BG，The worldsever Crash.

### Expected behaviour

I should be able to get into BG.
crashlog was sent
[crash.txt](https://github.com/trickerer/Trinity-Bots/files/11712988/crash.txt)

### Crashlog

It was a crash indeed.

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

Revision: AzerothCore rev. 0fb492828510+ 2023-06-09 18:44:53 -0300 (master branch) (Win64, RelWithDebInfo, Static) Date 11:6:2023. Time 1:15 

### Operating system

win10

**Comment by lemonmomomo** [comment]
BG minimum number of people is set to 0
[crash2.txt](https://github.com/trickerer/Trinity-Bots/files/11712999/crash2.txt)

**Comment by trickerer** [comment]
What is your config setting for `NPCBots.WanderingBots.BG.TargetTeamPlayersCount.AB`?

**Comment by lemonmomomo** [comment]
Default: 
![无标题](https://github.com/trickerer/Trinity-Bots/assets/122801033/d3de14a0-c1eb-4aa3-a059-772c7e8a60fa)
[worldserver.txt](https://github.com/trickerer/Trinity-Bots/files/11713796/worldserver.txt)

**Comment by trickerer** [comment]
> BG minimum number of people is set to 0

What is the maximum number set?

**Comment by trickerer** [comment]
I don't get any crashes if I just set minimum number of players to 0 in `battleground_template`.
How many bots do you preserve for BGs? (total bots minus spawned and wandering)

**Comment by lemonmomomo** [comment]
hello，trickerer&nbsp;
Ah, so it is!
I think I've done something very embarrassing!I'll NpcBot.WanderingBots.Continents.Count=200.
Your patient explanation let me know this logical relationship!
There are no crashes after leaving enough npc bots!
Thank you very much！
