### ISSUE TITLE
Pet label

### ISSUE THREAD

**Issue by Retro1995** [trickerer/Trinity-Bots#498]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

I noticed in last updates you update bots packages and now bots in bg party correctly displayed by addons as player. Can you make same with all bots? So that they are perceived by addons as players always. This is important, because you need to see target class on bg, if bot have pet flag addons not show class color and other options for battle.

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

last

**Comment by trickerer** [comment]
What addon do you have in mind?
I'm using X-Perl. Removing ownership and player-controlled flag doesn't change anything. Also causes this https://github.com/trickerer/Trinity-Bots/issues/434.
![WoWScrnShot_061123_100915](https://github.com/trickerer/Trinity-Bots/assets/1254989/197eff58-ff7c-428b-b37b-f048573e5472)
![WoWScrnShot_061123_101532](https://github.com/trickerer/Trinity-Bots/assets/1254989/8a66deb6-c27d-4c71-93a9-42a59d13446f)

**Comment by Retro1995** [comment]
if  selected friendly bot from your team its okey
![image](https://github.com/trickerer/Trinity-Bots/assets/136082219/9d3a4d2f-dadf-4fec-b6c0-eb8df72ce0ef)
but if selected enemy bot from opposing side he displayed as pet without class color
![image](https://github.com/trickerer/Trinity-Bots/assets/136082219/6d02535d-9eb2-4e8f-96b1-a7a68fb9fa4e)
same situation with placed bots in the world
![image](https://github.com/trickerer/Trinity-Bots/assets/136082219/a2be7f21-e946-4d84-846b-c7867f91dc95)

**Comment by Retro1995** [comment]
'Removing ownership and player-controlled flag' you try clear game Cache folder? Always need delete this folder.

**Comment by Retro1995** [comment]
'Removing ownership and player-controlled flag doesn't change anything' - sets in packages?

**Comment by trickerer** [comment]
> 'Removing ownership and player-controlled flag doesn't change anything' - sets in packages?

What sets and what packages are you talking about?
Owner guid and 'player-controlled' flag are the only things that make bots different from neutral creatures (make bots related to player).

**Comment by Retro1995** [comment]
add TYPEID_PLAYER?

**Comment by trickerer** [comment]
You can't add typeID exactly, it's set in C++ class constructor. Setting an object to wrong typeID will break everything. Might as well rewrite the whole player-related code base if you do that.

Now,
Removing player-control attributes I mentioned earlier only makes bot names appear in white instead of purple, unless they're in party. At the same time, regardless of these changes, their class is displayed as normal, maybe you're using a different addon version? Mine is 3.0.9 r366 which I've never updated.

![WoWScrnShot_061123_185657](https://github.com/trickerer/Trinity-Bots/assets/1254989/0889a5ed-cb0b-43a6-b562-bda437a8c598)

**Comment by Mitradis** [comment]
as you can see on you picture nickname not have class color for druid. Color for pets, minions etc.

**Comment by Retro1995** [comment]
3.1.0
As you can see on you picture nickname not have class color for druids (brown).

**Comment by trickerer** [comment]
Just checked it.
3.0.9 is the last release version for WotLK. So your argument is invalid.
https://www.curseforge.com/wow/addons/xperl/files

**Comment by Retro1995** [comment]
But you have still have pets colors nickname.

**Comment by trickerer** [comment]
First of all, player-controlled name color is irrelevant to addon version, it depends on unit flags. I stated this before - a result of testing, but you must've missed it.
> Removing player-control attributes I mentioned earlier only makes bot names appear in white instead of purple, unless they're in party.

Secondly, X-Perl 3.1.0 shows bots as pets which is incorrect, while version 3.0.9 displays actual player class.
Wowace says that version 3.1 beta 1 is for version 3.3.5 while other 3.1 iterations are for 4.0.6.
Both Curseforge and WoWAddons say that version 3.1 beta 1 is for 4.x.x.
And my argument that 3.0.9 is the last release version for WotLK still stands, this version is supposed to be the most reliable by definition.

But the main point is that nothing makes addons see bots as players, unless they are in group in which case it's assumed always. There are ways for addons to use WoW API to determine unit as creature and not player. I don't see how this problem could be fixed, I don't know of any unit frames addon which displays unit names in class color always regardless of it being player of creature.
