### ISSUE TITLE
[AC] [Feature]convert the default class (enGB) text to local language

### ISSUE THREAD

**Issue by moncat2005** [trickerer/Trinity-Bots#499]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Please consider enhancing the display function of NPCBOTS: convert the default class (enGB) text of the currently listed NPCBOTs to local language display (like zhCN).

### TrinityCore or AzerothCore

AzerothCore

**Comment by trickerer** [comment]
Localization system is already implemented. Locales are located in `SQL/locales/` folder. They become outdated over time of course, feel free to contribute an update.
