### ISSUE TITLE
NPCBot refactor for commit "Core/AI: refactor SpellHit and SpellHitTarget."

### ISSUE THREAD

**Issue by danthespal** [trickerer/Trinity-Bots#5]
Refactor for TrinityCore 3.3.5 [commit ](https://github.com/TrinityCore/TrinityCore/commit/e3b232fe0e5c21a87d3fe71813e9d750259823f1)

[NPCBot_patch.txt](https://github.com/trickerer/Trinity-Bots/files/4760807/NPCBot_patch.txt)

I tested and it's working I hope I did good :D

Congrats for keeping update :D

**Comment by trickerer** [comment]
More of TC team shinenigans. Thanks for pointing out.
_"Update required"_ - noted.
