### ISSUE TITLE
Added .npc add 70000 no npcbots for hire

### ISSUE THREAD

**Issue by opicron** [trickerer/Trinity-Bots#50]
I added an .npc add 7000 botgiver. All available classes have the number 1 (except Blademasters:2, Destroyers:5, Arch: 2, Dreadlords: 5, Spellbreakers: 2, DarkRangers:5).

However, whichever option I select the text "Seems like there is nobody available right now". Even when I manually spawn an random npcbot.

It is my installation or could there be an issue?

Sorry for the trouble :).

**Comment by opicron** [comment]
I can make an account on my server which is publicly accessible if you wish, to see for yourself?

**Comment by opicron** [comment]
Closed-- I am wrong, it DOES work just as it should.

**Comment by wachuwamekil** [comment]
@opicron, what did you do to solve this issue, I'm having the problem atm on my server.

**Comment by wachuwamekil** [comment]
Never mind I didn’t realize you had to spawn the bits first before they could e hired via the NPC.

**Comment by xlla** [comment]
HI, I have encounter this issue too, the npcbot giver seems does not automatically spawn the npcbots. should I manual spawn the npcbot all all class before hire one from npcbot giver?

**Comment by trickerer** [comment]
@xlla Spawning bots first IS required, botgiver is an auxillary feature

**Comment by xlla** [comment]
@trickerer , I want provide npcbots for normal players , the botgiver is a good solution for this scenario.

**Comment by leafstrat** [comment]
> anyone can explain how do I remove Lagretta after added? need it so much! tks in advance!

In case anyone else is wondering (couldn't find any references besides this issue).

# How to remove Lagretta - Bots for hire

1. Go near her and run:
`.npc near` 

OUTPUT:
>XXXXXXXX - [Lagretta ...]

This is the actual ID for this entity after being spawned in, it's not actually 70000.

2. Delete her:
`.npc delete XXXXXXXX`
