### ISSUE TITLE
Upload you addon

### ISSUE THREAD

**Issue by Retro1995** [trickerer/Trinity-Bots#500]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

https://github.com/trickerer/Trinity-Bots/issues/498#issuecomment-1586179393
i am download all versions xperl and have same behaviour with all versions.
![image](https://github.com/trickerer/Trinity-Bots/assets/136082219/1bbc5954-4e54-4a5d-8165-bd55fea6461e)

I cant get like you
![image](https://github.com/trickerer/Trinity-Bots/assets/136082219/cf595f4c-b5f7-43c4-a535-86a4171fd0c3)

Can you upload you addon?

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

last

**Comment by trickerer** [comment]
My version is just a standard 3.0.9 X-Perl.
Did you try to check both `Target -> Target Class` and `Text` next to it?

**Comment by Retro1995** [comment]
Lua function UnitIsPlayer(unit) always return false on bots. **Do nothing until then.**

**Comment by Mitradis** [comment]
Just add in XPerl.lua in function XPerl_SetUnitNameColor(self, unit)
`if (UnitIsPlayer(unit) or not UnitIsVisible(unit) or (UnitPlayerControlled(unit) and UnitCreatureType(unit) == "Humanoid" and UnitClassification(unit) == "normal")) then`

in XPerl_Target.lua in local function XPerl_Target_UpdateClassification(self)
`if (targetclassification == "normal" and UnitPlayerControlled(partyid) and not UnitCreatureType(partyid) == "Humanoid") then`

in XPerl_Target.lua in local function XPerl_Target_UpdateType(self)
`if (UnitIsPlayer(partyid) or not UnitPlayerControlled(partyid) or (UnitCreatureType(partyid) == "Humanoid" and UnitClassification(partyid) == "normal")) then`

**Comment by Retro1995** [comment]
it works but it looks weird...

**Comment by Mitradis** [comment]
Это только создает еще большие проблемы по опредению и не исправляет цвет ника. К счастью есть еще порядка 5 приемов, я не буду публиковать их, а то назло только закрываешь эти приемы.

**Comment by Retro1995** [comment]
here was some fixes for Xperl, not it not work.
