### ISSUE TITLE
[AC] [Question/Feature] [Core] BG with 80 lvl bots

### ISSUE THREAD

**Issue by DykeRz** [trickerer/Trinity-Bots#504]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Hello, i set wandering bots to 138, got 80 lvl char and reg BG, but bots dont reg BG with me, how to play BG VS bots at 80 lvl? they dont reg BG at 80 lvl :(

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

5542548

### Operating system

debian 11

**Comment by trickerer** [comment]
First of all, this is not a question of request. Or did you think you're not supposed to queue into BGs at level 80 with bots?

Second. Can't confirm. I set wandering bots count to 138 and can and start BG at level 80 normally.

What BG are you trying to queue in?
What is the number of spawed bots in world?
Does console show any errors where you click 'Join Battle'?

**Comment by DykeRz** [comment]
> First of all, this is not a question of request. Or did you think you're not supposed to queue into BGs at level 80 with bots?
> 
> Second. Can't confirm. I set wandering bots count to 138 and can and start BG at level 80 normally.
> 
> What BG are you trying to queue in? What is the number of spawed bots in world? Does console show any errors where you click 'Join Battle'?

When entering a command .npcb list sp so far has 315 bots in total, but I have 138 installed in the config because there are no more bots, you need to create even more in creature_template, on the island of GM I have spawned about 50 bots for players

When registering any BG at 80 lvl, shows 1/20 - 1/16 registrations

**Comment by trickerer** [comment]
> When entering a command .npcb list sp so far has 315 bots in total, but I have 138 installed in the config because there are no more bots, you need to create even more in creature_template, on the island of GM I have spawned about 50 bots for players

If `.npcb list sp` shows 315 bots that's total number of bots in world. If there are 138 wandering bots then the remaining 177 bots are normal statically spawned bots.
The bots which get created for BG are temporarily taken from **free unspawned** bots, not wandering bots or static bots. If you don't have any unused bots then there will be no BG for you.

**Comment by DykeRz** [comment]
> > When entering a command .npcb list sp so far has 315 bots in total, but I have 138 installed in the config because there are no more bots, you need to create even more in creature_template, on the island of GM I have spawned about 50 bots for players
> 
> If `.npcb list sp` shows 315 bots that's total number of bots in world. If there are 138 wandering bots then the remaining 177 bots are normal statically spawned bots. The bots which get created for BG are temporarily taken from **free unspawned** bots, not wandering bots or static bots. If you don't have any unused bots then there will be no BG for you.

ok,got it, but how i can set all non spawned bots 80 lvl?

**Comment by DykeRz** [comment]
> Unused bots don't have level to speak of, so there is nothing to set. Besides, you don't need to. Bots match your level bracket automatically. If you queue as level 80 all bots will be level 80 as well.

ok, and the last question, how to make sure that these 80 lvl bots for BG are equipped exclusively in a gear I have defined, for example, A7?

**Comment by trickerer** [comment]
There is no way, their equipment is random currently. For 80 level it's composed of items with required level 76-80, from greens to epics.

**Comment by DykeRz** [comment]
> There is no way, their equipment is random currently. For 80 level it's composed of items with required level 76-80, from greens to epics.

does it depend on my equipment?

**Comment by trickerer** [comment]
Nope. Their equipment only depends on the level they spawn at.
