### ISSUE TITLE
[AC] [Bug/Crash] [Group/Spell/Core] ISSUE_TITLE

### ISSUE THREAD

**Issue by damangguomoniqi** [trickerer/Trinity-Bots#505]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

hello，Players can't for robots to release Intervene and Misdirection

### Steps to reproduce the problem

1.spell=34477/misdirection /The hunter     
2.spell=3411/intervene/A warrior

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

AzerothCore rev. a432316dec6a+ 2023-06-11 17:16:02 +0000 (master branch) (Win64, Release, Static) (worldserver-daemon) <Ctrl-C> to stop.

### Operating system

win 10

**Comment by trickerer** [comment]
Although server allows that (bots can use those on player), client doesn't allow casting spells that require ally target on non-players not controlled by the character. So it's impossible to fix it by conventional means.

I've expected that one day I'll need to implement commands to allow using such spells on bots.

**Comment by trickerer** [comment]
Re-check the Readme to learn how to use new commands
