### ISSUE TITLE
Excuse me, how to control the robot to follow and not attack?

### ISSUE THREAD

**Issue by lmzml** [trickerer/Trinity-Bots#506]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Excuse me, how to control the robot to follow and not attack? Thanks!

### TrinityCore or AzerothCore

AzerothCore

### Operating system

Win10

**Comment by trickerer** [comment]
Use either gossip or `.npcbot distance 0` command. Setting follow distance to zero will make your bots only attack when you point a target with your melee attack.

**Comment by lmzml** [comment]
Is this also effective in combat？

**Comment by trickerer** [comment]
Yes.
The command can be useful even mid bossfight to stop all dps.

**Comment by lmzml** [comment]
Can it be like `.npcbot command stopfully`，follow only and do not engage in any hateful behavior,Thank you.

**Comment by trickerer** [comment]
Yeah, there is no way to tell bots when they're allowed to heal and when they aren't. The only way to preven bots from doing anything while moving is to use `.npcbot sendto` command, but that's a kind of advanced technique. Check Readme for its usage if you want to try it.

**Comment by lmzml** [comment]
Can you add this feature? Follow but don't do anything?This feature should be very commonly used.Thank you again.

**Comment by lmzml** [comment]
For example, when fighting monsters, the robot's position can be adjusted.

**Comment by trickerer** [comment]
Check Readme for help on new commands.

**Comment by lmzml** [comment]
牛！！！
