### ISSUE TITLE
Solocraft not work

### ISSUE THREAD

**Issue by Retro1995** [trickerer/Trinity-Bots#507]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

After https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/165dfb416be3ac5acc4182219a8cece0485550cc Solocraft not affected on bots HP, can you revert this PR?

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

last

**Comment by trickerer** [comment]
That commit fixes client side issues and its follow-up fix cooldown conflicts. No, that commit won't be reverted. Ask solocraft maintainer(s) to add support for npcbots if you really need it.

BTW, why would you need solocraft if you use bots and vice versa?

**Comment by zaicopx** [comment]
Just use trickerer autobalance module for npcbot 👍
