### ISSUE TITLE
NPCBots unable to cast spells on neutral targets

### ISSUE THREAD

**Issue by gigormo** [trickerer/Trinity-Bots#508]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Bots seem to cast the first spell but are unable to cast further, the same issue does not occur on aggressive creatures. 
The issue seems to affect only ranged bots, the bots move to position as if they will cast and seem to attempt to. 
Looping due to neutral status perhaps

### Expected behaviour

Bots should continue to cast spells and fight at range

### Steps to reproduce the problem

Spawn NPCBots,
Travel/teleport to Westfall,
Kill goretusk creatures

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. 453975420de8 2023-06-14 15:20:40 -0500 (npcbots_3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

### Operating system

Windows 11

**Comment by trickerer** [comment]
Confirmed.
Since player control markers removal this crap is going to pop up in the most unexpected places, for some time anyways.
