### ISSUE TITLE
How do you fight a npcbot?

### ISSUE THREAD

**Issue by lemonmomomo** [trickerer/Trinity-Bots#509]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

I don't know how to fight a robot. I ordered a fight, but it didn't work, okay? Don't know why?

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. c676a8283768+ 2023-06-13 08:10:35 -0300 (master branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

### Operating system

win10 x64

**Comment by trickerer** [comment]
You can't duel with a creature, you can't trade with a creature, etc. That's it. You only see those options because client assumes unit in party to be a player.

**Comment by lemonmomomo** [comment]
@trickerer 
Thank you for your patience, but I think it's a bit of a shame because dueling is an interesting feature and I hope to add it in future updates. Thank you very much.
I'm going to close this topic for now.

**Comment by lixiaoquan** [comment]
> @trickerer Thank you for your patience, but I think it's a bit of a shame because dueling is an interesting feature and I hope to add it in future updates. Thank you very much. I'm going to close this topic for now.
Hi @lemonmomomo ,

Have you found any feasible solution to dual with a bot? It there any other bot mod solution which can do that?

Thanks
