### ISSUE TITLE
Enhancement : Fire mage skill rotation improvement

### ISSUE THREAD

**Issue by Ryu1254** [trickerer/Trinity-Bots#51]
Hello

For bot fire mage, I didn't see the bot use Scorch at all or using the molten Armor. this may end with weak dps even with high end gear. I have 0 skill in coding C++, but I take a chance to modify the bot_mage_ai.cpp to add the scorch..
but no success. maybe you can help with this.
[bot_mage_ai.txt](https://github.com/trickerer/Trinity-Bots/files/5684254/bot_mage_ai.txt)

I also, notice the fire mage bot do the living bombe randomly.. not consistence with a specific rotation..

For the rotation for fire mage, if that can help to improve the DPS for Fire mage.

Rotation
Scorch → Living Bomb →  spam Fireball or Frostfire Bolt → Pyroblast

Scorch – every 30 seconds
Living Bomb – every 12 seconds after the explosion
Pyroblast – after every Hot Streak proc.

**Comment by trickerer** [comment]
You'll have to disable both Frost Armor and Ice Armor in order to force Molten Armor outside of instances, otherwise bot will assume more defensive strat.

[3abb6c6a8e](https://github.com/trickerer/Trinity-Bots/commit/3abb6c6a8eb65825121ab852c5e7d093cef2d9c6)

**Comment by Ryu1254** [comment]
This is perfect.. I test it again by disable the frost and ice armor.  I see my fire mage bot increate DPS by a lot with the new scorch implement.
Thank for the improvement.
