### ISSUE TITLE
[AC] [Bug] [Core] Can't compile clean core

### ISSUE THREAD

**Issue by DykeRz** [trickerer/Trinity-Bots#513]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

compile dont done correctly, 2 errors

### Expected behaviour

/usr/bin/ld: ../scripts/libscripts.a(ScriptLoader.cpp.o): input "AddScripts()":
/home/source/AzerothCore-wotlk-with-NPCBots/build/src/server/scripts/gen_scriptloader/static/ScriptLoader.cpp:68: incomplete link to "AddCustomScripts()"
clang: error: the linker command failed with exit code 1 (use -v to see the call)
make[2]: *** [src/server/apps/CMakeFiles/worldserver.dir/build.make:193: src/server/apps/worldserver] Error 1
make[1]: *** [CMakeFiles/Makefile2:1038: src/server/apps/CMakeFiles/worldserver.dir/all] Oibka 2
make: *** [Makefile:136: all] Error 2

### Steps to reproduce the problem

pull clean source
pull 3 modules into source folder ../modules - mod-solo-lfg, mod-ah-bot,mod-autobalance
try to compile

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

10b8853

### Operating system

debian 11

**Comment by trickerer** [comment]
10b8853 build status is here: https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/10b88531f393722fd43f52859e64f945bdc27b7b

So, you added bunch of modules and it doesn't build. Why do you think this is a NPCBots issue?

**Comment by DykeRz** [comment]
> 10b8853 build status is here: [trickerer/AzerothCore-wotlk-with-NPCBots@10b8853](https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/10b88531f393722fd43f52859e64f945bdc27b7b)
> 
> So, you added bunch of modules and it doesn't build. Why do you think this is a NPCBots issue?

ok, im sorry about my issue, i resolved it - 

this happened due to the fact that i did not compile core and pulled modules at once, so that there would be no error, you must first pull core, then compile clean core, then only pull modules to modules folder and compile core again

I hope this message will be an experience for other users and that they would not make mistakes like me, sorry :)

**Comment by DykeRz** [comment]
i compilled clean core, then, pulled modules and recompile core again and its working now ok :) do not pull modules into core before first compile
