### ISSUE TITLE
Bots not have interrupt cast on take damage

### ISSUE THREAD

**Issue by Retro1995** [trickerer/Trinity-Bots#517]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

About this report https://github.com/trickerer/Trinity-Bots/issues/510
Bots buff 1h Fortitude buff (72590) and this spell NOT standard and here you are wrong say about bots use default spells, THIS SPELL NOT DEFAULT. Standard Fortitude = 30min.
And two: LAST means LAST. I just dont want copy this big heash. i rebuild server every day or 2 maximum.

**QUESTION:**
Bots not have interrupt cast on take damage? Cast time not increases on take damage?

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

last

**Comment by Retro1995** [comment]
rogue run in stealth

**Comment by Retro1995** [comment]
No adding delay on take damage while casting creates big problems with healers and other casters.

**Comment by trickerer** [comment]
> Bots buff 1h Fortitude buff (72590) and this spell NOT standard and here you are wrong say about bots use default spells, THIS SPELL NOT DEFAULT. Standard Fortitude = 30min.

Bots increase the duration of all buffs to 1 hour, it's strange that you didn't notice that seeing other classes buffs. Even more strange that you didn't notice that fortitude spells have different names: 72590 is 'Fortitude' while Priest spell is 'Power Word: Fortitude'. If you prefer to just disregard all that and blindly believe your version I suggenst you use `.list auras` command to check aura spell ids.
> Rogues run in stealth - one more bug notice

I know it's hard to provide a screenshot or video of such a bug. Still, I don't think it's true and here is why: Stealth applies movement speed decrease aura, even considering the fact that bots move faster than player, Stealth also applies a visual 'sneak' state which changes movement animation. So this is probably just a visual bug or (maybe) a side effect of using Sprint with it. If you still think it's a valid issue, try to provide a screenshot or video of it, or at least a detailed explanation how and where you were able to reproduce it.
> Bots not have interrupt cast on take damage? Cast time not increases on take damage?

Like any other creature, bots do not suffer spellcast pushback on damage, there are also no creature flags that would enable that. Long time ago I decided to not fiddle with it and now there are no checks for that in bots code that would account for such a possibility.

And the last thing
> LAST means LAST. I just dont want copy this big heash. i rebuild server every day or 2 maximum.

I'm sorry, you probably don't have any idea what issue solving process looks like, but I'll explain. Nobody cares how often you build, this is unimportant. An issue may stay open for months, and developers need to know which version is guaranteed to have this defect, this applies to any project. If you refuse to understand why it's important and instead prefer to think that required field is not required really, please save my time and don't open an issue at all.
