### ISSUE TITLE
warlock has no spell to do

### ISSUE THREAD

**Issue by 328950225** [trickerer/Trinity-Bots#52]
if bot <lv64 will cant cast shadowbolt

use fix
`
            //Main: Shadow Bolt, Incinerate, Searing Pain (tank), checking destruction range
            if (dist < CalcSpellMaxRange(SHADOW_BOLT_1))
            {
                uint32 boltinerate =
                    me->GetLevel()<=64?SHADOW_BOLT_1:GetSpell(INCINERATE_1)&&
                    IsTank() && GetSpell(SEARING_PAIN_1) ? SEARING_PAIN_1 :
                    GetSpell(SHADOW_BOLT_1) && GetSpec() == BOT_SPEC_WARLOCK_AFFLICTION ? SHADOW_BOLT_1 :
                    GetSpell(INCINERATE_1) && opponent->HasAuraState(AURA_STATE_CONFLAGRATE) ?
                    //opponent->GetAuraEffect(SPELL_AURA_PERIODIC_DAMAGE, SPELLFAMILY_WARLOCK, 0x4, 0x0, 0x0) &&
                    //opponent->GetAuraEffect(SPELL_AURA_MOD_ATTACKER_SPELL_CRIT_CHANCE, SPELLFAMILY_WARLOCK, 213, 0) &&
                    //(me->GetMap()->IsRaid() || !me->HasAura(SHADOW_TRANCE_BUFF)) ?
                    INCINERATE_1 : 0;
`
or

`
            //Main: Shadow Bolt, Incinerate, Searing Pain (tank), checking destruction range
            if (dist < CalcSpellMaxRange(SHADOW_BOLT_1))
            {
                uint32 boltinerate =
                    IsTank() && GetSpell(SEARING_PAIN_1) ? SEARING_PAIN_1 :
                    GetSpell(SHADOW_BOLT_1) && GetSpec() == BOT_SPEC_WARLOCK_AFFLICTION ? SHADOW_BOLT_1 :
                    GetSpell(INCINERATE_1) && opponent->HasAuraState(AURA_STATE_CONFLAGRATE) ?
                    //opponent->GetAuraEffect(SPELL_AURA_PERIODIC_DAMAGE, SPELLFAMILY_WARLOCK, 0x4, 0x0, 0x0) &&
                    //opponent->GetAuraEffect(SPELL_AURA_MOD_ATTACKER_SPELL_CRIT_CHANCE, SPELLFAMILY_WARLOCK, 213, 0) &&
                    //(me->GetMap()->IsRaid() || !me->HasAura(SHADOW_TRANCE_BUFF)) ?
                    INCINERATE_1 :SHADOW_BOLT_1 ;
`
There has other bug, soul link Only  the demon Warlock can use it.  not all spec .

**Comment by trickerer** [comment]
Cannot confirm Soul Link part.

[3abb6c6a8e](https://github.com/trickerer/Trinity-Bots/commit/3abb6c6a8eb65825121ab852c5e7d093cef2d9c6)
