### ISSUE TITLE
Possible convert (Creature)mypet to (Pet)mypet?

### ISSUE THREAD

**Issue by Retro1995** [trickerer/Trinity-Bots#521]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Possible convert (Creature)mypet to (Pet)mypet? I mean convert bots pet to TRUE pets. This need for fix some interface detect problem, like names, nameplates etc:
![image](https://github.com/trickerer/Trinity-Bots/assets/136082219/2fc7dda6-ed05-489d-b15f-6c5397ece99d)

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

fb4b95ba9686cba489f4a5a26def9ae971639d54

**Comment by trickerer** [comment]
Currently bot pets have owner guid set to bot and UNIT_FLAG_PLAYER_CONTROLLED set also, I'm not sure if setting other guid values will make bot pets be recognized by client as player pets. I'll try but if it fails I'll have to assume that's not possible

**Comment by trickerer** [comment]
No luck. Nothing I could find works. Seems like client checks if unit's resulting owner/summoner/creator is a player. Even units summoned by spells that would normally count as pets when cast by players still count as just units when spell is cast by bots.
That's a shame, but seems like this isn't feasable.
