### ISSUE TITLE
[AC] [Question] [Core] Bots and module autobalance

### ISSUE THREAD

**Issue by DykeRz** [trickerer/Trinity-Bots#522]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

how to remove the impact of the autobalance module on the npc bot? The fact is that the bot is not healing or is healing for only 100-150 HP in combat in dungeons at 80 lvl

Visual cast is doing, but healing 0-150

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

aed3118

### Operating system

debian 11

**Comment by DykeRz** [comment]
and second question, is it possible to make bots appear in the online list?

**Comment by trickerer** [comment]
Use autobalance with npcbots support: https://github.com/trickerer/mod-autobalance

**Comment by trickerer** [comment]
> and second question, is it possible to make bots appear in the online list?

Not currently. And I don't plan to add this feature.

**Comment by DykeRz** [comment]
> Use autobalance with npcbots support: https://github.com/trickerer/mod-autobalance

BUG: remote-curl.c:1494: The entire rpc->buf should be larger than LARGE_PACKET_MAX
fatal: expected flush after ref listing

When pulling

**Comment by DykeRz** [comment]
> > Use autobalance with npcbots support: https://github.com/trickerer/mod-autobalance
> 
> BUG: remote-curl.c:1494: The entire rpc->buf should be larger than LARGE_PACKET_MAX fatal: expected flush after ref listing
> 
> When pulling

resolved by   git config --global http.postBuffer 524288000

thank you :)
