### ISSUE TITLE
[AC] [Bug] [Core] Error compile cneal source

### ISSUE THREAD

**Issue by DykeRz** [trickerer/Trinity-Bots#523]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

pulled clean source and try to compile it without any changes and modules
just pull and compile with 

cmake ../ -DCMAKE_INSTALL_PREFIX=/home/serv -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_C_COMPILER=/usr/bin/clang-11 -DCMAKE_CXX_COMPILER=/usr/bin/clang++-11 -DWITH_WARNINGS=1 -DTOOLS_BUILD=all -DSCRIPTS=static -DMODULES=static

Error at 100%

/usr/bin/ld: ../scripts/libscripts.a(ScriptLoader.cpp.o): input "AddScripts()":
/home/source/AzerothCore/build/src/server/scripts/gen_scriptloader/static/ScriptLoader.cpp:68: incomplete link to "AddCustomScripts()"
clang: error: the linker command failed with exit code 1 (use -v to see the call)
make[2]:  [src/server/apps/CMakeFiles/worldserver.dir/build.make:193: src/server/apps/worldserver] Error 1
make[1]:  [CMakeFiles/Makefile2:1020: src/server/apps/CMakeFiles/worldserver.dir/all] error 2
make: *** [Makefile:136: all] Error 2

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

7795412

### Operating system

debian 11

**Comment by trickerer** [comment]
Here, I added clang CI builds. Try after https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/c31b84563035fe86b88c6afe9b8711c0c444f85a

**Comment by trickerer** [comment]
Well, you can see the build status.
In most cases, when you get linking errors you just need to re-run CMake

**Comment by DykeRz** [comment]
> Well, you can see the build status. In most cases, when you get linking errors you just need to re-run CMake

Hm, i was rerun cmake every time when compiling, i pulled this commit 40 min ago,so rerun cmake = still errors

**Comment by DykeRz** [comment]
![Screenshot_2023-06-20-13-44-24-241_com sonelli juicessh](https://github.com/trickerer/Trinity-Bots/assets/35741241/5dcad6d9-1dda-4f33-acdc-1520e2725d31)

**Comment by DykeRz** [comment]
![Screenshot_2023-06-20-13-42-06-214_com sonelli juicessh](https://github.com/trickerer/Trinity-Bots/assets/35741241/53f2f229-5ae8-402a-8ef2-1da9db5133a7)

This up, rerun cmake,then make install -j2, error at 100% i rebooted my debian, its dont help me

**Comment by DykeRz** [comment]
![Uploading Screenshot_2023-06-20-13-44-24-241_com.sonelli.juicessh.jpg…]()

**Comment by DykeRz** [comment]
![Uploading Screenshot_2023-06-20-13-44-24-241_com.sonelli.juicessh.jpg…]()

**Comment by DykeRz** [comment]
![Uploading Screenshot_2023-06-20-13-44-24-241_com.sonelli.juicessh.jpg…]()

**Comment by DykeRz** [comment]
What i do:

Pull source
Cd /home/source
Mkdir build
Cd build
cmake ../ -DCMAKE_INSTALL_PREFIX=/home/serv -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_C_COMPILER=/usr/bin/clang-11 -DCMAKE_CXX_COMPILER=/usr/bin/clang++-11 -DWITH_WARNINGS=1 -DTOOLS_BUILD=all -DSCRIPTS=static -DMODULES=static
Make install -j2

**Comment by trickerer** [comment]
Unfortunately github workflow doesn't provide any Debian images. Clang build works fine on Ubuntu 20.04, check the logs for working parameters.
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/actions/runs/5322285403/jobs/9638528103
```
* Build applications              : Yes (all)
* Build tools                     : No
* Build with scripts              : Yes (static)
* Build with modules              : Yes (static)
* Build unit tests                : Yes
* Build core w/PCH                : No
* Build scripts w/PCH             : No
* Show all warnings               : Yes
* Use coreside debug              : No  (default)
* Use unix gperftools             : No  (default)
* Use GIT revision hash           : Yes (default)
* Enable vmap DisableMgr checks   : Yes (default)
* Show source tree                : No (For UNIX default)
```

If it doesn't help you either, then you may have some problem on your end. Try to build clean AzerothCore without bots.
