### ISSUE TITLE
[TC] [AC] [Bug/Crash] [Group/Spell/Core] ISSUE_TITLE

### ISSUE THREAD

**Issue by ddk2001** [trickerer/Trinity-Bots#524]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Bot skills don't display names

### Expected behaviour

Some skills that manage the available skills do not display names。
![@KN~~4F M 3QN(%U3~O9Z D](https://github.com/trickerer/Trinity-Bots/assets/29648605/ff1250f0-88d0-41d3-9bde-1a3f5c4bd360)

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

AC: 19 Jun 2023, 7795412531

**Comment by trickerer** [comment]
Make sure you have proper locale dbc files in your server's `dbc/` folder, for example:
```
SERVER_ROOT/
  ...
  dbc/
    zhCN/
      Achievement.dbc            <-- zhCN files
      Achievement_Category.dbc   <-- zhCN files
      ...
    Achievement.dbc             <-- enUS files
    Achievement_Category.dbc    <-- enUS files
    ...
  ...
  worldserver.exe
  ...
```

**Comment by ddk2001** [comment]
These DBCs are not missing, I tried to re-extract the DBC。

**Comment by trickerer** [comment]
Try changing `DBC.Locale` in worldserver.conf.
Check what locale is set in you client's `Config.wtf`

**Comment by ddk2001** [comment]
set DBC.Locale =4  ， Config.wtf ： SET locale "zhCN" 。But it still doesn't work, I'm going to re-git and recompile。

**Comment by ddk2001** [comment]
[trickerer] ：Can Autobalance update it at the same time?

**Comment by moncat2005** [comment]
![image](https://github.com/trickerer/Trinity-Bots/assets/34859687/2ee09f4f-0474-4898-8929-aa81a5065e6a)
Looks like the NPCBOTS skill list is fine.
