### ISSUE TITLE
[TC] [AC] [Bug/Crash] [Group/Spell/Core] ISSUE_TITLE

### ISSUE THREAD

**Issue by demm500** [trickerer/Trinity-Bots#525]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

I apologize in advance for my poor English, as I write through a translator.

I noticed one oddity, if you give bots a thing that increases the speed of spells, and not melee, then bots also increase the speed of melee.

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore

### Operating system

Win7

**Comment by trickerer** [comment]
Bots ignore haste type and convert it into universal haste.
What is the item/spell in question?

**Comment by trickerer** [comment]
Feel free to re-open this issue if and when you're ready to elaborate further.
