### ISSUE TITLE
[AC] [Question/Feature] [Group] Formation of opposing factions

### ISSUE THREAD

**Issue by Onshare** [trickerer/Trinity-Bots#526]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Hi, I have a little suggestion. If players from opposing factions form teams, can robots avoid attacking each other?

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

none

### Operating system

centos

**Comment by trickerer** [comment]
You mean `AllowTwoSide.Interaction.Group`? Please give a more detailed description.

**Comment by trickerer** [comment]
Ok, here are the rules for bots when `AllowTwoSide.Interaction.Group` is enabled:
- NPCBots out of group owned by previously hostile player who is now in group will show up as hostile at client, not attackable but not automatically assistable either
- When such bots get added to group they will still appear as hostile until values update is forced by either teleporting somewhere or using `.npcbot recall teleport` command. Only then they will appear af friendly and assistable

I'll push the fix today
