### ISSUE TITLE
[AC] [Bug] [Spell] Prayer of Mending can't target bots anymore

### ISSUE THREAD

**Issue by Selence-Liuis** [trickerer/Trinity-Bots#527]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Prayer of Mending cannot target bots

### Expected behaviour

Prayer of Mending should able to choose bot as spell target

### Steps to reproduce the problem

1. learn spell Prayer of Mending
2. spawn a bot
3. invite bot to team
4. target bot and use Prayer of Mending

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

 AzerothCore rev. 29ab75366f17 2023-06-20 14:35:34 +0800 (npcbots_3.3.5 branch)

### Operating system

Ubuntu 22.04

**Comment by trickerer** [comment]
You can't use player-only spells on NPCBots directly anymore. Use `.npcbot use spell Prayer of Mending` command to work around it. Create a macro. Check Readme for command syntax.
