### ISSUE TITLE
[TC] [AC] [Bug/Crash] [Group/Spell/Core] Battgrounds missing characters

### ISSUE THREAD

**Issue by Conan1996-2** [trickerer/Trinity-Bots#528]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Set the following in worldserver.conf:
- NpcBot.WanderingBots.BG.TargetTeamPlayersCount.WS = 10
- NpcBot.WanderingBots.BG.TargetTeamPlayersCount.AB = 15

Create an Alliance Team and end up with one less then the opposite team, eg:
Alliance in WG has 9, Horde has 10
Alliance in AB has 14, Horde has 15

Looking at worldserver: output is:
BotBattlegroundEnterEvent: Aborting bot 71319 bg 2
BotBattlegroundEnterEvent: Aborting bot 71337 bg 3

### Expected behaviour

Battlegrounds WG and AB both should have the number of individuals you post in the worldserver.conf file.

### Steps to reproduce the problem

See above

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

0fb492828510+ 2023-06-09 18:44:53 -0300 (master branch) (Unix, RelWithDebInfo, Static) (authserver)

### Operating system

Ubuntu

**Comment by trickerer** [comment]
This isn't a bug. Bots start to leave queue if you don't join the BG before match starts.

**Comment by Conan1996-2** [comment]
But I'm in the BG waiting for it to start with the 1 minute timer and then 30 second notifications. I'm definitely in the BG waiting.
________________________________

**Comment by trickerer** [comment]
Don't worry I already saw it's a different kind of thing, now it's fixed

**Comment by Conan1996-2** [comment]
Thank you, recompiling now.

Any estimate on any new BG's adding to the mix?
________________________________

**Comment by trickerer** [comment]
AV is slowly coming. It'll take more than just WPs to make it good.

**Comment by Conan1996-2** [comment]
Perfect, I can't wait to try it out when you finish. I honestly thought you were going to do EOTS, because its a combination of both WG and AB and you already have that code done.
________________________________
