### ISSUE TITLE
Free bots with opposite faction can res player corpse

### ISSUE THREAD

**Issue by Retro1995** [trickerer/Trinity-Bots#529]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Free bots with opposite faction (enemy to player) can res player corpse. It looks strange. But if i add check here https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/blob/npcbots_3.3.5/src/server/game/AI/NpcBots/bot_ai.cpp#LL1656C10-L1656C10 on IsFriendlyTo server crash.

And another question about CPU load: party with 4 npcbots + 1 player can load CPU up to 15%. On BG with 10\\10 it can reach 18%. Did not check but what will happen if a battle occurs 40\\40.  I think this to big given that clear server can endure 5k player.

And one more question: bot return all equipped items after dismissed, it is possible save their gear?

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

535d7d84edac4b533510b9b9d933e11aa1cea1bf

**Comment by Retro1995** [comment]
DK in group REuse HORN OF WINTER every ~30sec, each time when he do something. But this spell have cooldown 10min.

**Comment by trickerer** [comment]
> DK in group REuse HORN OF WINTER every ~30sec, each time when he do something. But this spell have cooldown 10min. He does it all the time even if its not required. Sometimes he does it even non combat state, just in moving.

Intended. Cooldown is 30 sec. 10 min is spell duration.
> And another question about CPU load: party with 4 npcbots + 1 player can load CPU up to 15%. On BG with 10\10 it can reach 18%. Did not check but what will happen if a battle occurs 40\40. I think this to big given that clear server can endure 5k player.

Main server load comes from grids loaded, not bots themselves. From feedback I get slowdown starts when people try to create 8k+ wandering NPCBots. If you'll get a slowdown and want me to profile server performance I'll need exact server setup which you can't describe in just a few sentences.

> And one more question: bot return all equipped items after dismissed, it is possible save their gear?

This was discussed numerous times.
#164
