### ISSUE TITLE
bot_mage_ai fix

### ISSUE THREAD

**Issue by 328950225** [trickerer/Trinity-Bots#53]
just tested on <lv74 npcbot
fix Fire Blast never cast it out 
```
            //Fire Blast (do not waste mana in raids)火焰冲击
            if (IsSpellReady(FIRE_BLAST_1, diff) 
                && dist < CalcSpellMaxRange(FIRE_BLAST_1) 
                && Rand() < (30 + 40*fbCasted + 80*(!opponent->IsFrozen() 
                && !opponent->HasUnitState(UNIT_STATE_STUNNED) )))
            {
                if (doCast(opponent, GetSpell(FIRE_BLAST_1)))
                    return;
            }
```
fix FROSTFIREBOLT (FROSTFIRE_BOLT_1 : FIREBALL_1)  on " || !GetSpell(ARCANE_BLAST_1)"=true  always cast it. Because it always =true
```
            //中文：霜火之箭英文：Frostfire Bolt
            if (IsSpellReady(FROSTFIREBOLT, diff) && _spec == BOT_SPEC_MAGE_FIRE && !GetSpell(ARCANE_BLAST_1) &&
                dist < CalcSpellMaxRange(FROSTFIREBOLT))
            {
                if (doCast(opponent, GetSpell(FROSTFIREBOLT)))
                    return;
            }
```

1. fix FROSTFIRE_BOLT_1 only >74 can use
2. add Mage_Armor_1                        = 6117,
3. fix ARMOR :ICEARMOR/MOLTENARMOR/mageARMOR cast with spec
```           
            //ARMOR 护甲buff中文：熔岩护甲英文：Molten Armor
            bool isArca = _spec == BOT_SPEC_MAGE_ARCANE;
            bool isFire = _spec == BOT_SPEC_MAGE_FIRE;
            bool isFros = _spec == BOT_SPEC_MAGE_FROST;
            uint32 ICEARMOR = GetSpell(ICE_ARMOR_1) ? GetSpell(ICE_ARMOR_1) : GetSpell(FROST_ARMOR_1);//冰霜
	    uint32 MOLTENARMOR = GetSpell(MOLTEN_ARMOR_1) ? GetSpell(MOLTEN_ARMOR_1) : ICEARMOR;//火焰
            uint32 mageARMOR = GetSpell(Mage_Armor_1) ? GetSpell(Mage_Armor_1):ICEARMOR;//奥术
            uint32 ARMOR = isFros ? ICEARMOR : isArca?mageARMOR:isFire?MOLTENARMOR:ICEARMOR;
            if (ARMOR && !me->HasAura(ARMOR))
            {
                if (doCast(me, ARMOR))
                    return;
            }
```

[bot_mage_ai.txt](https://github.com/trickerer/Trinity-Bots/files/5687265/bot_mage_ai.txt)

**Comment by trickerer** [comment]
> fix Fire Blast never cast it out

can't confirm

> fix FROSTFIREBOLT (FROSTFIRE_BOLT_1 : FIREBALL_1) on " || !GetSpell(ARCANE_BLAST_1)"=true always cast it. Because it always =true

wrong, Arcane Blast may be disabled, and since it is an essential part of the rotation, bot need to use something if he has any damaging spells at all.

1. Frostfire Bolt **is** a lvl 74 spell, I see no point in your statement.
2, 3. Mage Armor is used so rarily that I never cared to add it. Armor spell type is chosen based not on spec, but on its purpose. In dungeon you want maximum damage output, while in open world bots will prefer more defensive approach, unless forced of course.
