### ISSUE TITLE
[TC] [AC] [Bug/Crash] [Group/Spell/Core] Server gone if i have a item 32729 and share to npcbot

### ISSUE THREAD

**Issue by zhimingbb** [trickerer/Trinity-Bots#531]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Server gone if i have a item 32729 and share to npcbot
bug video  https://veed.io/view/b5212c82-aafd-44b1-8be8-3cab998c59a3

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

azerothcore

### Operating system

ubuntu

**Comment by trickerer** [comment]
Wrong description. Videos shows you click bot gear bank menu and server crashes. Item id is irrelevant.

You didn't provide an AC revision hash.

Can't confirm on https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/0b48c723b5058b84c5c17af41a9292c9daf44b5b. Build in Debug mode and post a crashlog.

**Comment by zhimingbb** [comment]
server crash when i chat npcbot to show equimentment available if i have item 32729 in my bag

**Comment by trickerer** [comment]
I tried that also and it doesn't crash for me. Without a crashlog I won't be able to help you.

**Comment by zhimingbb** [comment]
where is the crash log?

**Comment by trickerer** [comment]
https://www.azerothcore.org/wiki/how-to-restart-and-debug

**Comment by moncat2005** [comment]
@zhimingbb  需要你用编译的DEBUG版worldserver来运行，然后提供宕机后的DUMP日志信息，我手头Linux版还没实现DEBUG。

I have also verified this issue many times. 
First, using a GM account, execute the .add 32729 command. 
There is 32729 item (NPC equip 32729) in the bagpack. 
Click on the gear bank of the hired NPCBOT - deposit menu, and the worldserver crashes immediately.

**Comment by trickerer** [comment]
https://github.com/trickerer/Trinity-Bots/issues/531#issuecomment-1600662573

https://github.com/trickerer/Trinity-Bots/assets/1254989/a88ef2df-6a1e-468e-9c71-e60b697609e2

**Comment by zhimingbb** [comment]
this is linux server version? win server no problem,but linux server down

**Comment by zhimingbb** [comment]
Ubuntu Ubuntu 20.04 LTS

**Comment by Conan1996-2** [comment]
Ubuntu 22.04.2LTS version here, when I follow the above steps, my server does not crash but I also do not see anything other than BACK in the characters window.

**Comment by moncat2005** [comment]
Ubuntu 18.04
I tried to turn on coredump and generate a file (core. world. XXXX. lz4) during the playback crash operation mentioned above, but this file is too large. The LZ4 format is 602M, and the 7Z compression still has 214M, while the fully decompressed file is 2G. I don't know how to open and view this file.

**Comment by trickerer** [comment]
> This way you will have both the restarter and GDB pre-configured to create a gdb.txt (crashdump) file when the core crashes

Didn't you get `gdb.txt` file? It should be enough.

**Comment by trickerer** [comment]
> I got crash gdb.txt
> [gdb.txt](https://github.com/trickerer/Trinity-Bots/files/11871420/gdb.txt).

What is the revision you built it on?
