### ISSUE TITLE
[AC] [Bug] [Core] Bots reaction to skull mark

### ISSUE THREAD

**Issue by DykeRz** [trickerer/Trinity-Bots#534]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

bots react badly to the skull mark, Marrowguar spike and the ice prisons of Sindragosa, bots do not attack them when the skull is marked, bots also freeze after the Lich King Harvest spell

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

8d1a436

### Operating system

Debian 11

**Comment by trickerer** [comment]
Bots target Bone Spikes and Ice Prison automatically, it is hardcoded.
