### ISSUE TITLE
[AC] [Bug] [BG] AV some bugs

### ISSUE THREAD

**Issue by Retro1995** [trickerer/Trinity-Bots#535]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Thank you very much for adding this wonderful battlefield! I found some bugs:
bots not using mounts at start and later and just run on big distance;
all horde bots going in Mine at start because they start fighting with Cobalts.

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

ec5000692db19206360bd2ff5ca66d73a95e5478

**Comment by Retro1995** [comment]
Who use Tentacle???)))

**Comment by Retro1995** [comment]
![image](https://github.com/trickerer/Trinity-Bots/assets/136082219/9fe365cb-717a-433b-ac8e-c2f1206a13af)

**Comment by Retro1995** [comment]
Horde attack FROSTWOLF

**Comment by Retro1995** [comment]
after battle bots return back to previous waypoint

**Comment by trickerer** [comment]
> Who use Tentacle???)))

https://wotlk.evowow.com/?item=46312

**Comment by trickerer** [comment]
> after battle bots return back to previous waypoint

They go to **current** waypoint they passed by due to combat.

> all horde bots going in Mine at start because they start fighting with Cobalts

> Horde attack FROSTWOLF alliance RAM

Blah. As long as they meet up at the center and not somewhere else I'm okay with it. I don't see any of this giving any team an advantage, at all
