### ISSUE TITLE
 [AC] Shaman doesn't learn healing stream totem

### ISSUE THREAD

**Issue by crispinknox** [trickerer/Trinity-Bots#536]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Shaman NPCBOT does not learn healing stream totem.
Not sure if other bots don't learn quest spells
azerothcore + npcbot fresh server not repack

### Expected behaviour

Shaman should learn healing stream totem at 20

### Crashlog

n/a

### Steps to reproduce the problem

spawn bot and hire at level over 20

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. 5a4998d1dc1b 2023-06-21 18:45:32 +0700 (npcbots_3.3.5 branch) (Win64, RelWithDebInfo, Static) (authserver)

### Operating system

win 11

**Comment by trickerer** [comment]
Shaman bots don't have it because it's useless in absolutely most situations.
