### ISSUE TITLE
NPCBOT Learn Spell

### ISSUE THREAD

**Issue by crispinknox** [trickerer/Trinity-Bots#537]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Would it be possible to add the ability to teach the npcbot a spell via a gm command?

I know some cores have the ability petlearn, so something similar

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. 5a4998d1dc1b 2023-06-21 18:45:32 +0700 (npcbots_3.3.5 branch) (Win64, RelWithDebInfo, Static) (authserver)

### Operating system

win 11

**Comment by trickerer** [comment]
Bots only learn hardcoded class spells. If they don't have some class spell it means it isn't implemented.
Bots don't use spells at random so there is no way to add anything custom to their rotation other then modifying the code. And their spells aren't saved anywhere, available spells depend on level and talent spec.
Such a feature is completely out of score of this project. Bots aren't pets, custom classes is the only real 'custom' thing that makes this project different from 'player-like mercenaries'.
