### ISSUE TITLE
[TC] [Bug] [Spell] The Mage Bot is not channeling the Blizzard spell.

### ISSUE THREAD

**Issue by MokaCube** [trickerer/Trinity-Bots#539]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

The Mage Bot casts the Blizzard spell, but it immediately interrupts the channeling after approximately 1 second. It continues this behavior repeatedly until it runs out of mana.

### Expected behaviour

The Mage Bot should maintain the channeling of the Blizzard spell until it completes casting.

### Crashlog

N/A

### Steps to reproduce the problem

1) The Mage bot encounters a group of enemies.
2) The Mage Bot begins casting Blizzard.
3) The Mage Bot prematurely ends the channeling of Blizzard spell.
4) It repeats the above behavior.

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

TrinityCore rev. 2eb778ae635f+ 2023-06-21 12:16:01 +0200 (3.3.5 branch)

### Operating system

Arch linux

**Comment by Retro1995** [comment]
and DK not use GAP
