### ISSUE TITLE
[AC] [Crash] [Core] Server crashing when start Alterac BG with bots

### ISSUE THREAD

**Issue by DykeRz** [trickerer/Trinity-Bots#542]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Start alterac BG with bots
at start server will crash

You start BG,going with bots to fight,server will lag and crushes the core, debag points to my alterations mailhandler.cpp - I added 10 lines there, but I deleted them and left a file as the standard, anyway crash logs point to mailhandler I don't understand why, because I have already deleted the code from there

Maybe there really is a problem with bots on Alterac

Стартуешь БГ,бежишь с ботами в бой, всё зависает и крашит ядро, дебаг указывает на мои переделки mailhandler.cpp - я там 10 строк добавил, но я и их удалил и оставил как стандарт должен быть файл, всё равно краш логи указывают на mailhandler не понимаю почему, ведь я код оттуда уже удалил

Может быть действительно проблема в ботах на Альтераке

### Crashlog

https://gist.github.com/DykeRz/b7dc3a4ebd10c6a22b615a40c8c108de

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

000056a

### Operating system

debian 11

**Comment by Mitradis** [comment]
ничего не крашит, смотри свои правки.

**Comment by DykeRz** [comment]
> ничего не крашит, смотри свои правки в других местах. Многократно запускал и перезапускал. Выходил с начала и тут же запускал снова - все стабильно. У меня тоже множество правок под себя (в них нет исправлений trickerer, я к тому что я ничего не прячу, просто там то, что ты все равно не внедришь). Кстати было бы неплохо организовать чтото типа обмена патчами, типа отдельная тема, но при условии сохранения их работоспособности, а не блокировки, потому что это основная проблема публичной публикации.

Хм,ну у меня есть правки в cs_server.cpp и в boss_sindragosa.cpp,но я там просто поменял надписи с англ на рус,вывод текста и всё в принципе,я не пойму почему мой гдб указывает на мои старые правки в мэйлхэндлер, у тебя есть корректный рестартер с гдб дебагом? Поделись пожалуйста,что бы я мог разобраться

**Comment by Mitradis** [comment]
Я не такой прошаренный cpp программист чтобы использовать такие вещи)) У меня довольно простой подход, есть отлаженная система быстрой сборки и быстрой свежей сборки БД. Если чтото вылетает или где-то проблемы я просто откатываю поэтапно патч и смотрю результат. Говоришь если идти со своими ботами? щас првоерю.

**Comment by Mitradis** [comment]
Да, крашит.

**Comment by DykeRz** [comment]
> Да, крашит. Крашит если взять СВОИХ ботов на бг.

Да,если с собой бота берешь

**Comment by DykeRz** [comment]
> Я не такой прошаренный cpp программист чтобы использовать такие вещи)) У меня довольно простой подход, есть отлаженная система быстрой сборки и быстрой свежей сборки БД. Если чтото вылетает или где-то проблемы я просто откатываю поэтапно патч и смотрю результат. Говоришь если идти со своими ботами? щас првоерю.

Понял,жалко) но если что,можем скооперироваться в разработке,вот мой дискорд https://discord.gg/_dyker

**Comment by DykeRz** [comment]
Ė

> Ну так что это не твои правки, а логи все ерунда, они могут что угодно показывать. Это конкретный баг и главное, что определена причина действий.

Ну вот,да, баг не во мне) хотя почему мой гбд указывает на краш мои правки не понятно,из давно уже нет,такое ощущение,что он из запомнил и теперь только их и спамит мне,а новые не выдаёт

**Comment by Mitradis** [comment]
Я написал в дискорд, а у Trinity-Bots есть дискорд еще? Просто нигде не указан.

**Comment by DykeRz** [comment]
> Я написал в дискорд, а у Trinity-Bots есть дискорд еще? Просто нигде не указан.

Мне ничего не пришло,скинь свой Дискорд или где ты сидишь. Вот кстати Тринити Борис или Азерот Борис я тоже не нашел Дискорд,хотя очень хотелось бы

**Comment by Mitradis** [comment]
На альтераке орда и альянс атакуют нейтральных мобов.
Ханты не используют трапы.
Боты на маунте в воде двигаются с такой же скоростью.

Это что заметил.
