### ISSUE TITLE
[AC] [Bug] [Core] Bots always behind the player

### ISSUE THREAD

**Issue by Retro1995** [trickerer/Trinity-Bots#547]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Bots always behind the player, cant attack!

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

6c1754e170c8e104ee5eaa14b95201ad0ab81c77

**Comment by trickerer** [comment]
> Bots always behind the player, cant attack!

I'm not solving riddles here. Provide a full description of the problem. Word it in a way that noone would need to ask any additional questions.

**Comment by Retro1995** [comment]
in battle with bot - bot always behind me

**Comment by Russianranger** [comment]
What class is the bot?
What role does the bot have? Tank? DPS? Ranged? Heal?
You're not being specific. If you have time to submit an issue, you have time to detail it out.

**Comment by Retro1995** [comment]
I wont write anymore

**Comment by trickerer** [comment]
I think I understand now.
So, melee bots always try to go behind their attacked player (like in normal PvP) and the problem is that they do it constantly when targeting a unit not attacking the bot in turn.

**Comment by Mitradis** [comment]
На это потребовалось 2 дня. Какое быстрое перестроение нейронных цепочек!
