### ISSUE TITLE
[AC] [Core] On the issue of high CPU usage display in the Azerothcore worldserver program

### ISSUE THREAD

**Issue by moncat2005** [trickerer/Trinity-Bots#549]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Suddenly, I found that the compiled worldserver program with the latest npcbots feature code has a CPU usage rate of over 90% after startup.

I tested and recompiled the worldserver program without NPCBOTS function code, and the system showed a CPU usage rate of 40%.

I haven't paid attention to the CPU resource usage issue of Azerothserver for a long time, and I feel abnormal about this usage rate. Remember that in the past, the occupancy rate of worldserver after startup was usually below 20%

Ubuntu 18.04 8core Vcpu 10G memory

AzerothCore rev. c424a0953b5a+2023-06-24 00:56:56+0000

### Steps to reproduce the problem

![cpu95](https://github.com/trickerer/Trinity-Bots/assets/34859687/fc88bce4-a757-4205-a97a-4edf87d3d98c)

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. c424a0953b5a+2023-06-24 00:56:56+0000

### Operating system

  Ubuntu 18.04

**Comment by trickerer** [comment]
> Suddenly, I found that the compiled worldserver program with the latest npcbots feature code has a CPU usage rate of over 90% after startup.

What revision was the previous one for you?
> AzerothCore rev. **c424a0953b5a+** 2023-06-24 00:56:56+0000

This revision points to AC commit not merged into bots. Are you using a patch?
If so, what is the patch version? What was the previous version where you didn't have this problem?
Otherwise, what are the custom changes?

What is the setup and state of your server during this? Particularly, how many players do you have online? How many bots are spawned in how many grids? Is that a Debug or Release build?

**Comment by moncat2005** [comment]
That's right, I used the official version of azerothcore source code from June 24th, 
and then downloaded and executed the AC PATCH of npcbots before compiling it. 
The screenshot shows that the worldserver program has just been started, 
and even the authserver has not been started, so no players have logged in.
Then execute the TOP or HTOP command to check the CPU usage of the worldserver program on the Ubuntu system.

Now I seem to have discovered the cause of the problem.
The problem originates from the configuration parameters in the worldserverconf file.
After adjusting the following configuration parameters, the problem has been improved.
#    MinWorldUpdateTime
#        Description: Minimum time (milliseconds) between world update ticks (for mostly idle servers).
#        Default:     1 - (0.001 second)
MinWorldUpdateTime = 1  change to 10

#    MapUpdateInterval
#        Description: Time (milliseconds) for map update interval.
#        Default:     10 - (0.01 second)
MapUpdateInterval = 10 change to 100
![cpu37](https://github.com/trickerer/Trinity-Bots/assets/34859687/c0e6d41f-e03a-4147-8f27-9cf41c763883)
