### ISSUE TITLE
[TC] [AC] [Question/Feature] [Group/Spell/Core] Implement stuck timer?

### ISSUE THREAD

**Issue by philocalist3** [trickerer/Trinity-Bots#550]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Hi!

I've noticed that wandering bots (open world) can get stuck if encountering a bugged mob / attacking targets that can't be attacked - for example this one in Shadowmoon valley: https://www.wowhead.com/wotlk/npc=21416/lakaan

Lakaan can't be attacked until the surrounding totems are killed.

I was wondering if it would be possible to implement a "stuck timer" that perhaps checks if the wandering bot hasn't reached a new wander node for X amount of time? So, if the bot hasn't reached a new node in 1 hour for example, it would be forcibly teleported to a new node / graveyard.

Thanks!

### TrinityCore or AzerothCore

Both

**Comment by trickerer** [comment]
Such check already exists, but it checks the number of tries it took the bot to reach current point, this counter resets in combat.
The approach used for unkillable creatures is different and was added to handle creatures like training dummies or Blasted Lands servants. Maybe units having full immunity with infinite duration are better be added there (like these Shadowmoon Valley corruptors).

**Comment by philocalist3** [comment]
What is that check called?
I'm not sure that it works if the bot is in combat and the creature is lagging (evading or reseting during combat). Then the bot will be stuck fighting that creature.

**Comment by trickerer** [comment]
They are both inlined. First one is in `bot_ai::Evade()` method, look for `_evadeCount`. Second one is in `bot_ai::CanBotAttack()` - a switch by creature ID, some creatures have taken damage adjusted by scripts but `DamageTaken()` method can have side effects and can't be a proper way to check the ability to damage the target, plus it isn't the only one.
