### ISSUE TITLE
[TC] [AC] [Question/Feature] [Group/Spell/Core] ISSUE_TITLE

### ISSUE THREAD

**Issue by Machalote** [trickerer/Trinity-Bots#552]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Can you remove specific spells from the bots? (I mean select the spell I want to disable)

### TrinityCore or AzerothCore

TrinityCore

**Comment by Russianranger** [comment]
Yes. Check the readme, under the "Manage Abilities" section. You can enable/disable spells that way via the gossip menu.

**Comment by Machalote** [comment]
> Yes. Check the readme, under the "Manage Abilities" section. You can enable/disable spells that way via the gossip menu.

Thank you so much!
