### ISSUE TITLE
[AC] [Bug] [Spell] Rogues cast Blind on totems (tremor)

### ISSUE THREAD

**Issue by ghost** [trickerer/Trinity-Bots#554]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Rogues cast Blind on totems (tremor). And they are all the time behind the back of the player, cant cast spell on him.

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

648d6dfa1a11181f4b14c3a961e42a8c76203154

**Comment by trickerer** [comment]
First part should be fixed by https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/8eef51ca0fa2f6b89db8bd251dd0aba7394dde8f
