### ISSUE TITLE
[AC] [Bug] [Core] CanApplyResilience

### ISSUE THREAD

**Issue by Tula20** [trickerer/Trinity-Bots#555]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

CanApplyResilience() some times not confirms what unit Bot or BotPet. You see this if add check bools with out to log message to Unit.cpp and start fighting with bot:
![image](https://github.com/trickerer/Trinity-Bots/assets/138192835/509234f1-b9e8-44be-9b6b-cd6fca054b49)
![image](https://github.com/trickerer/Trinity-Bots/assets/138192835/9ded8208-17a2-4624-a215-40e0bb1a019e)
you can see this:
![image](https://github.com/trickerer/Trinity-Bots/assets/138192835/67bac369-0cc1-4da1-af04-5e335b49de34)

this fixed by add:
m_applyResilience = false || (ToCreature() && ToCreature()->IsNPCBotOrPet());
m_applyResilience = (!IsVehicle() && owner.IsPlayer()) || (ToCreature() && ToCreature()->IsNPCBotOrPet());

and remove IsNPCBotOrPet from:
bool Unit::CanApplyResilience() const
{
    return m_applyResilience;
}

**BUT this leaves a big question** if IsNPCBotOrPet() cant correctly work in CanApplyResilience() when this
virtual bool IsNPCBot() const { return false; }
virtual bool IsNPCBotPet() const { return false; }
virtual bool IsNPCBotOrPet() const { return false; }
can do potential errors in other cases in Unit.cpp

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

NWM

**Comment by Tula20** [comment]
And why you mass use IsNPCBotOrPet? Why noy use bool variable? Why in EACH cast you call IsNPCBotOrPet? This is not good

**Comment by trickerer** [comment]
Can't confirm on version 5.4.103a. I've replicated the checks you show here but didn't receive any errors while attacking / being attacked by rogue bot, I tried putting a breakpoint at log instruction in case something is wrong with my logging settings but it wasn't hit either. I suspect you're missing some SQL update so bots aren't recognized, or maybe you've imported additional bots from third-party SQL file(s) which weren't updated.

**Comment by trickerer** [comment]
> And why you mass use IsNPCBotOrPet? Why not use bool variable? Why in EACH cast you call IsNPCBotOrPet? This is not good and not professional.

That's to make it accessible from the very `Object` class. Just like `IsPlayer()` method and the like, which is used all over the place too. I was asked for this change, too.

Also just a reminder, most of NPCBots code was written 10-12 years ago when I was still learning C++, I'm not redesigning the whole project to make it look more professional, that's 80,000 lines of code at least, no way.

**Comment by Tula20** [comment]
Quantity does not mean quality, you can write a million lines of code, but in the end, in the game, for player, it will be indistinguishable from a regular NPC.
But exactly what is the point in this case why need EACH time call IsNPCBotOrPet in CanApplyResilience()? Is there a very important reason for this? Who asked you? Microsoft?

**Comment by Tula20** [comment]
Fresh rebuid
![image](https://github.com/trickerer/Trinity-Bots/assets/138192835/690bf06d-ef27-4e37-99b9-06ce2214bbca)

**Comment by Tula20** [comment]
Quantity does not mean quality, you can write a million lines of code, but in the end, in the game, for player, it will be indistinguishable from a regular NPC.

But exactly what is the point in this case why need EACH time call IsNPCBotOrPet in CanApplyResilience() FOR EACH SPELL CAST? Is there a very important reason for this? Who asked you? Microsoft? Competitors? Enemies?
This is just this particular example, there are many such examples.

**Comment by Tula20** [comment]
Sory some bug with DB.

**Comment by trickerer** [comment]
> Quantity does not mean quality, you can write a million lines of code, but in the end, in the game, for player, it will be indistinguishable from a regular NPC.

I'm not talking about quantity nor quality. It's about the time it would take, a major redesign is required to really improve the system. Seriously, do you have the time to do a redesign of project of this scale? Yeah, me neither.

> But exactly what is the point in this case why need EACH time call IsNPCBotOrPet in CanApplyResilience() FOR EACH SPELL CAST? Is there a very important reason for this? Who asked you? Microsoft?
This is just this particular example, there are many such examples.

Easy, buddy. Relax. I'm well aware this isn't the **most** effective solution. Also, why don't ask AC developers about the reasons to call `CanApplyResilience()` 'FOR EACH SPELL CAST' in the first place.
In the end the CPU time is what matters the most. `IsNPCBotOrPet()` method is extremely lightweight and even without optimization will be translated into about 5-10 ASM instructions. Profiling AC performance shows that the majority of CPU time goes to movement, line of sight, height calculations and aura updates.

Please, do not try to unwind this off-topic further and try to elaborate on current bugreport instead. If you have any particular suggestions - make a pull request in respective repository, or open a new 'feature request' issue.
