### ISSUE TITLE
[AC] [Bug] Discovered a delay/lag in NPCBOTS following player's movement.

### ISSUE THREAD

**Issue by moncat2005** [trickerer/Trinity-Bots#557]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

When NPCBots follow players on horseback or walking, 
they often stop at a certain place (such as within Stormwind City) 
and then suddenly quickly return to the player's side in about 10 seconds.
The player network latency less than 10ms.
![npcbots-move-delay](https://github.com/trickerer/Trinity-Bots/assets/34859687/ee521865-13a6-41d4-be26-113a0e03b16d)

### Steps to reproduce the problem

Find an open space.
Let NPCBOTS follow the player's character.
Operate Q&E to control the player's horizontal movement, stop, and return.
After about 4-5 times, it will be discovered that NPCBOTS has stopped based on the previous walk,
No longer following players immediately, players can walk more than 50 yards without being followed.
At this point, the player chooses a following distance of 30 yards for NPCBOTS，and the network delay is less than 10ms.

After about 10 seconds, NPCBOTS will suddenly accelerate and follow the player（highspeed）.

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. 648d6dfa1a11 2023-06-29 11:40:41 +0700 (npcbots_3.3.5 branch) (Unix, RelWithDebInfo, Static) 

### Operating system

Ubuntu 18.04

**Comment by trickerer** [comment]
To have a chance to reproduce this I may need your `Visibility.Notify.Period.OnContinents` and `MapUpdateInterval` values.

**Comment by moncat2005** [comment]
Where is the parameter 'Visibility. Notify. Period. OnContinents'?
MapUpdateInterval = 20

When NPCBOTS follows normally, there is no problem at all and it is very smooth.
In fact, this may seem more like a network delay, but both the latency displayed by the client and the external PING value of the server itself seem normal.
I even started to doubt if my virtual machine system was malfunctioning.

**Comment by moncat2005** [comment]
I'm very sorry for wasting your energy and time.

After repeated experiments, I have found the problem: the host system of the VM I am using is abnormal.
Although 8-core VCPU is allocated, there is actually an issue with CPU resource allocation and usage. 
The latency/lag performance in the game is actually caused by insufficient worldserver computation.

After restarting the host system of the VM, the game performance has returned to normal.

Now, I will adjust MapUpdateInterval = 20 to 100, which is also very normal.
