### ISSUE TITLE
[AC] [Question] [Core] How to create new NPCBots?

### ISSUE THREAD

**Issue by DykeRz** [trickerer/Trinity-Bots#558]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

i created new NPCBot in creature_template table with entry = 182773

but now in world,when i put .npcb spawn 182773 it says me: No class/race data for bot 182773

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

c73673c

### Operating system

debian 11

**Comment by Russianranger** [comment]
See this discussion. You are only adding one table, your need to add it to 4 different tables.

https://github.com/trickerer/Trinity-Bots/discussions/540#discussioncomment-6276120

**Comment by lemonmomomo** [comment]
It's better to just use the command. Check out readme

createnew <_NAME_> <_CLASS_> _RACE_ _GENDER_ _SKIN_ _FACE_ _HEARSTYLE_ _HAIRCOLOR_ _FEATURES_ _SOUNDSET_ -- (Admin command) allows you to create new NPCBots for players to use. Creature ids 70800+ are used for that.
NAME = name of created NPCBot. Note that first letter will always be in Upper Case, name_containing_spaces_must_be_underscored
CLASS = this refers to NPCBot class. Use .npcbot lookup comand to list all available classes
RACE = you have to provide a race for your new NPCbot unless you are creating a NPCBot of one of the special classes for whose race is predefined as well as other details
1: Human
2: Orc
3: Dwarf
4: Night Elf
5: Undead
6: Tauren
7: Gnome
8: Troll
10: Blood Elf
11: Draenei
GENDER = same as RACE, for normal classes you have to select one
0: Male
1: Female
SKIN, FACE, HEARSTYLE, HAIRCOLOR, FEATURES = appearance details, 0 and up. Different race/gender combinations have different constraints for visuals, use .npcbot createnew ranges to see them
SOUNDSET = NPC voice variant for bot to use. There are 3 variants for each race, by default the choice is random
Example Usage:
.npcbot createnew Selendris 2 10 1 6 4 3 2 4 (creates a female redhead Blood Elf mage npcbot)
.npcb cre Selendris 2 10 1 6 4 3 2 4 (creates a female redhead Blood Elf mage npcbot)
.npcb createnew ranges (prints visuals constraints for all races)

**Comment by DykeRz** [comment]
> See this discussion. You are only adding one table, your need to add it to 4 different tables.
> 
> [#540 (comment)](https://github.com/trickerer/Trinity-Bots/discussions/540#discussioncomment-6276120)

Thank you very much! :)
