### ISSUE TITLE
[TC]  [Bug] Error when start worldserver

### ISSUE THREAD

**Issue by 1plus-1** [trickerer/Trinity-Bots#559]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Hi ,
I cloned the TrinityCore-3.3.5-with-NPCBots repo on Apr(around 15th) and build up the server. Everything was running as expected. I spawned 9 bots in the map.
Lately I did a git pull to updated to the latest code. After built and installed the new binaries, I got below error when starting the world server.

> Starting Map System
Starting NpcBot system...
>> Bot spellInfo overrides generated for 53 spells
>> Bot spell proc overrides generated for 1 spells
Bot entry 70266 has appearance data but doesn't exist in `creature_template` table! Skipped.
>> Bot appearance data loaded
>> Bot race data loaded
>> Bots transmog data is not loaded. Table `characters_npcbot_transmog` is empty!
>> Loaded 9 bot data entries
>> Spawned 9 npcbot(s) within 1 grid(s) in 39 ms
Setting up wander map...
No valid Alliance spawn node for at least level 55 on map 530! Spawning wandering bots is impossible! Aborting.
No valid Alliance spawn node for at least level 55 on map 571! Spawning wandering bots is impossible! Aborting.
No valid Horde spawn node for at least level 55 on map 530! Spawning wandering bots is impossible! Aborting.
No valid Horde spawn node for at least level 55 on map 571! Spawning wandering bots is impossible! Aborting.
No valid Neutral spawn node for at least level 60 on non-continent map 489.
No valid Neutral spawn node for at least level 60 on map 530! Spawning wandering bots is impossible! Aborting.
No valid Neutral spawn node for at least level 60 on map 571! Spawning wandering bots is impossible! Aborting.
/home/nick/TrinityCore-3.3.5-with-NPCBots/src/server/game/AI/NpcBots/botdatamgr.cpp:1178 in LoadWanderMap ABORTED.
Segmentation fault (core dumped)

Will be appreciated if any advice.

NickZL 

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

c3f6771dd1ecb76b9cbafcb3aa3e0616793343d3

### Operating system

Ubuntu 22.04

**Comment by trickerer** [comment]
You forgot to import SQL updates. For TC you have to do it manually. Base path to those files is `/sql/Bots/updates/`

**Comment by 1plus-1** [comment]
It fixed the problem... thanks

**Comment by 1plus-1** [comment]
BTW, thanks for the greate work of all the development and maintenance...it's like back to the old days...
