### ISSUE TITLE
Feature request:Npcbots+Autobalance feature

### ISSUE THREAD

**Issue by Parkan1986** [trickerer/Trinity-Bots#56]
Добрый день Trickerer.Вопрос такой:
Есть очень интересная модификация этого автора https://github.com/aleigood/TrinityCore-Autobalance которая неплохо работает на текущей ревизии тринитикор и с ботами.Но у этой модификации есть свои недостатки,которые я незнаю  возможно ли будет Вам решить.
Дело в том что автор мода хоть и выложил версию для тринитикор которую он портировал с азероткор,но его мод не патчиться (т.е невозможно добавить на сорсы тринитикор,пришлось добавлять вручную и уже делать патч-файл самому,файл который ставиться на текущую ревизию приложу к сообщению),а так же есть еще кое-какие недостатки к примеру:
1.Чат команды перестали работать(они работали до ревизии тринитикор от 1 ноября,начиная с ревизии 1 ноября команды пришлось закоментить т.к из-за этого не компилировался сервер)
2.Сложность рейдов\подземелий  автоматически не увеличивается при добавлении ботов в пати(хотя по принципу как с игроками сложность к примеру повышается когда по умолчанию стоит AutoBalance.playerCountDifficultyOffset = 0 и при добавлении игрока оно меняется на AutoBalance.playerCountDifficultyOffset = 1.Да и изменение параметра AutoBalance.playerCountDifficultyOffset = 1 выше 4,ничего не меняет.
3.К сожалению у мода скалирование по уровню и статам у мобов работает только в подземельях,а вот в открытом мире к сожалению не работает(хотя для одиночной игры этого ой как не хватает.)Такая особенность была замечена только в репаке базированному на азероткор https://www.ac-web.org/forums/showthread.php?232758-AzerothCore-AzerothCore-wotlk-Solo-Friendly-Repack-with-Eluna этого автора.
К сожалению человек больше не работает на обновлениями и делиться наработками он не желает.
4.Если в  Creature_template у нпс ботов стоит minLevel и maxlevel 80,то нпсботы в подземельях не наносят урона вообще и как будто все время промахиваются.Исправить это недоразумение помогло лишь установка минимального и максимального уровня у нпсботов и их петов на 1.

Из всего выше перечисленного у меня есть такие вопросы:
1.Возможно ли к Вашему моду добавить те же самые функции автобаланса,но с доополнительными исправлениями по типу чтобы работали команды этих функций
2.Возможность включить скалирование мобов по игроку в открытом мире либо сделать альтернативные настройки по принципу автобаланс мода.

[0003-Add-AutoBalance.zip](https://github.com/trickerer/Trinity-Bots/files/5735219/0003-Add-AutoBalance.zip)

**Comment by trickerer** [comment]
Добавлять автобаланс к ботам не годится, это два взаимонезависимых мода с разными задачами. Тем более в таком виде функции автобаланса распространить на ботов наравне с игроками не получится, нужны немалые дополнения функционала. Лучше всего было бы его наполовину переписать, избавить от тяжёлых костылей (особенно влияющих на производительность) и выпустить как отдельную версию мода, совместимую с ботами.

Скалировать мобов в открытом мире ничего не мешает, вопрос только по какому принципу, ведь вокруг игроков теоретически может быть больше чем у моба здоровья, опять же мобов очень много ну и так далее.

Исправить команды просто. Нужно лишь привести таблицы комманд к текущему шаблону.

Добавить using namespace Trinity::ChatCommands;
`std::vector <ChatCommand>` -> `ChatCommandTable`
```
{"setoffset", SEC_GAMEMASTER, true, &HandleABSetOffsetCommand,
"Sets the global Player Difficulty Offset for instances. Example:
 (You + offset(1) = 2 player difficulty)."},
```
привести к
```
{"setoffset", HandleABSetOffsetCommand, rbac::RBACPermissions(197), Console::Yes},
```
ну и корень `{"vas", ABCommandTable},`

Возможно имеет смысл сравнить с версией для тринити на их форуме, хотя там тоже давным-давно нет обновлений.

**Comment by Parkan1986** [comment]
> Скалировать мобов в открытом мире ничего не мешает, вопрос только по какому принципу, ведь вокруг игроков теоретически может быть больше чем у моба здоровья, опять же мобов очень много ну и так далее.

Тогда как примерно это можно сделать чтобы скалирование в открытом мире работало?



> Исправить команды просто. Нужно лишь привести таблицы комманд к текущему шаблону.

Где именно и как это все добавить?

**Comment by trickerer** [comment]
> Тогда как примерно это можно сделать чтобы скалирование в открытом мире работало?

Пока не знаю, я его даже установить ещё не пытался, не то что пытаться вылавливать косяки.

> Где именно и как это все добавить?
```
+//    std::vector <ChatCommand> GetCommands() const {
+//        static std::vector <ChatCommand> ABCommandTable =
+//                {
+//                        {"setoffset", SEC_GAMEMASTER, true, &HandleABSetOffsetCommand,     "Sets the global Player Difficulty Offset for instances. Example: (You + offset(1) = 2 player difficulty)."},
+//                        {"getoffset", SEC_GAMEMASTER, true, &HandleABGetOffsetCommand,     "Shows current global player offset value"},
+//                        {"checkmap",  SEC_GAMEMASTER, true, &HandleABCheckMapCommand,      "Run a check for current map/instance, it can help in case you're testing autobalance with GM."},
+//                        {"mapstat",   SEC_GAMEMASTER, true, &HandleABMapStatsCommand,      "Shows current autobalance information for this map-"},
+//                       {"crstat",    SEC_GAMEMASTER, true, &HandleABCreatureStatsCommand, "Shows current autobalance information for selected creature."},
+//               };
+//
+//        static std::vector <ChatCommand> commandTable =
+//                {
+//                        {"vas", SEC_GAMEMASTER, false, NULL, "", ABCommandTable},
+//                };
```
Здесь. И не добавить а конвертировать. Как - пример я дал

> Ну тут больше по принципу что играет 1-2 человека на сервере в разных местах и каждый качаеться как хочет.Но чтобы уровень мобов и их статы всегда были равны игроку.Эдакий автолевелинг как в скайриме.

Ну тогда нужно просто хукать Creature::SelectLevel и выставлять статы на основе количества игроков в радиусе 120-150 или типа того. Но опять-таки эти статы нужно обновлять со временем, скажем, каждые 3 секудны, ведь количество игроков вокруг может меняться, а хук сработает лишь раз. В сингле всё проще.

Наткнулся
https://www.ac-web.org/forums/showthread.php?238222-Want-To-Sell-Script-Services&p=2392204&viewfull=1#post2392204

**Comment by Parkan1986** [comment]
Похоже его автобаланс тоже не скалирует мобов в открытом мире. Я там спросил человека, но ответа пока не поступало. Да и хрен его знает сколько стоить это будет. Все таки у меня не баксы, а рубли. Тяжело будет расплачиватся

**Comment by trickerer** [comment]
6к? Я бы тоже столько не дал.

Числу к десятому попробую что-нибудь сделать.

**Comment by Parkan1986** [comment]
Спасибо.

**Comment by trickerer** [comment]
Выдался свободный вечер. Пока вывод не очень, но всё работает. С одним ботом вот так

![scr0](https://user-images.githubusercontent.com/1254989/103192965-47075f00-490d-11eb-9ee2-185d1ea7d512.JPG)
![scr1](https://user-images.githubusercontent.com/1254989/103192980-51295d80-490d-11eb-9530-ea183c1c8353.jpg)

**Comment by Parkan1986** [comment]
Интересненько. А почему вывод не очень?

**Comment by trickerer** [comment]
Анонс изменения сложности недостаточно детален, и происходит не всегда. Информация о текущей зоне как-то обновляется до телепорта. В результате на выводе всякая дичь. Так и на скрине пишет игроков 5 (1+4), изменения после появления бота нет

**Comment by Parkan1986** [comment]
Т.е player diffuculty asset не менятся от колва ботов, только вручную в конфиге?

**Comment by trickerer** [comment]
Меняется, но не пишется

Игрок + бот

Проверку на ботов и взаимную интеграцию модов я уже запилил

Как я уже сказал, всё работает, но если просто играть то ничего не понятно

**Comment by Parkan1986** [comment]
О, это уже интересненько.

**Comment by trickerer** [comment]
> П. С я там пару дней назад сообщение на почту отправил Вам. Вы его получили?

Да
