### ISSUE TITLE
[TC] [AC] [Question/Feature] [Group/Spell/Core] How can I adjust the npcbot exp reduction formula?

### ISSUE THREAD

**Issue by Seads512** [trickerer/Trinity-Bots#562]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

I see you can adjust the exp reduction per bot in the config files, but I was wanting to change when the exp reduction begins from hiring the second bot to hiring your first bot. How could I go about doing this?

### TrinityCore or AzerothCore

AzerothCore

**Comment by trickerer** [comment]
The formula itself is hardcoded, config only adjusts a single parameter in it.

If you want to adjust the formula in code go to KillRewarder.cpp line 181 and change
```
uint32 ratePct = std::max<int32>(100 - ((player->GetNpcBotsCount() - 1) * xp_reduction), 10);
```
to
```
uint32 ratePct = std::max<int32>(100 - (player->GetNpcBotsCount() * xp_reduction), 10);
```
Alternatively, an additional config param could be added which would allow to set bot number for above formula to take effect starting from.
