### ISSUE TITLE
[AC] [Bug] [Core] Vmap data ICC

### ISSUE THREAD

**Issue by DykeRz** [trickerer/Trinity-Bots#565]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Hello, i extracted all data from clean client, worldserver starting, but in ICC dont have vmaps data in game, idk why

i placed data folder at authserver and worldserver and set datadir to = ./data

players fall down at Lich King place :( but other maps working ok

 https://ibb.co/SxTcW5B

https://ibb.co/xLkHxTX

https://ibb.co/5hv32vJ

#
#    DataDir
#        Description: Data directory setting.
#        Important:   DataDir needs to be quoted, as the string might contain space characters.
#        Example:     "@prefix@\home\youruser\azerothcore\data"
#        Default:     "."

DataDir = "./data"

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

c73673c

### Operating system

debian 11

**Comment by trickerer** [comment]
How is this related to NPCBots?
