### ISSUE TITLE
[AC] [Feature] [Core] npcbot use my potions and consumables, they don't decrease.

### ISSUE THREAD

**Issue by lemonmomomo** [trickerer/Trinity-Bots#569]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Yes， I found that when I let npcbot use my potions and consumables, they don't decrease, but I'm not sure if it's all!
I think whoever uses the potions and consumables in their backpack should cut back!

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. 43f46dc5eb0c+ 2023-06-24 23:31:18 +0000 (master branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

### Operating system

win10 x64

**Comment by trickerer** [comment]
When you give consumable to bot the item doesn't get removed, that's intended. The reason is that bot auras don't get saved (as they do for pets) and don't get retained when bots is removed even temporarily. So you may just waste the item - this may become a much bigger problem.

**Comment by lemonmomomo** [comment]
that's intended？Okay, I have no doubts.
I can't write code, but I understand it.
Thank you for answering my question.

**Comment by feng380** [comment]
I found the same problem, but it has little impact on the server, and the gain status is not outrageous
