### ISSUE TITLE
GetMap ASSERTION FAILED

### ISSUE THREAD

**Issue by littlehelper1987** [trickerer/Trinity-Bots#57]
Hello,

Server Crashes: 

Revision: TrinityCore rev. 73b68bea937d 2020-12-12 19:51:38 +0100 (3.3.5 branch) (Win64, Release, Static)
Date 27:12:2020. Time 15:9 
//=====================================================
*** Hardware ***
Processor: Intel(R) Xeon(R) CPU E3-1275 V2 @ 3.50GHz
Number Of Processors: 8
Physical Memory: 33483920 KB (Available: 29476680 KB)
Commit Charge Limit: 38464656 KB

*** Operation System ***
Windows Server 2016 Standard (Version 10.0, Build 17763)

//=====================================================
Exception code: C0000420 Ein Assertionsfehler ist aufgetreten.

Assertion message: 
F:\MeinServer\Trinity\src\server\game\Entities\Object\Object.h:399 in WorldObject::GetMap ASSERTION FAILED:
  m_currMap
MapID: 533 Map name: 'Naxxramas' X: 2935.04 Y: -3506.85 Z: 297.628 O: 0.6674
GUID Full: 0xf130011174000108 Type: Creature Entry: 70004  Low: 264 Entry 70004
Name: Ander
IsAIEnabled: true DeathState: 0 UnitMovementFlags: 0 ExtraUnitMovementFlags: 0 Class: 1
 MoveSpline
spline Id: 1920156
flags:  Done

time passed: 0
total  time: 0
spline point Id: 1
path  point  Id: 2
mode: Linear
points count: 0

AIName:  ScriptName: warrior_bot WaypointPath: 0 SpawnId: 15000321

Fault address:  00007FF62812ACD9 01:00000000004F9CD9 F:\MeinServer\Build\bin\Release\worldserver.exe

Registers:
RAX:000000DCDE3FED70
RBX:0000021743BCC470
RCX:0000000000000002
RDX:00007FF8DC4C53C5
RSI:0000000000000000
RDI:000000DCDE3FF620
R8: 0000000000000019
R9: 0000000000000001
R10:000000000000000A
R11:00007FF6289D4680
R12:0000000000000019
R13:0000000000000000
R14:7FFFFFFFFFFFFFFF
R15:000000010000005E
CS:RIP:0033:00007FF8DC5E96C9
SS:RSP:002B:00000000DE3FF420  RBP:DE3FF591
DS:002B  ES:002B  FS:0053  GS:002B
Flags:00000206

Call stack:
Address   Frame     Function      SourceFile
00007FF8DC5E96C9  000000DCDE3FF4F0  RaiseException+69
00007FF6287C6196  000000DCDE3FF5E0  0001:0000000000B95196 F:\MeinServer\Build\bin\Release\worldserver.exe
00007FF62812ACD9  000000DCDE3FF660  0001:00000000004F9CD9 F:\MeinServer\Build\bin\Release\worldserver.exe
00007FF6281656B7  000000DCDE3FF7D0  0001:00000000005346B7 F:\MeinServer\Build\bin\Release\worldserver.exe
00007FF62814C077  000000DCDE3FF810  0001:000000000051B077 F:\MeinServer\Build\bin\Release\worldserver.exe
00007FF62814BCB5  000000DCDE3FF840  0001:000000000051ACB5 F:\MeinServer\Build\bin\Release\worldserver.exe
00007FF628687320  000000DCDE3FF870  0001:0000000000A56320 F:\MeinServer\Build\bin\Release\worldserver.exe
00007FF6283546EF  000000DCDE3FF960  0001:00000000007236EF F:\MeinServer\Build\bin\Release\worldserver.exe
00007FF62835423B  000000DCDE3FF9A0  0001:000000000072323B F:\MeinServer\Build\bin\Release\worldserver.exe
00007FF6285C3901  000000DCDE3FF9D0  0001:0000000000992901 F:\MeinServer\Build\bin\Release\worldserver.exe
00007FF6285C3C5F  000000DCDE3FFA00  0001:0000000000992C5F F:\MeinServer\Build\bin\Release\worldserver.exe
00007FF6285C43A2  000000DCDE3FFA50  0001:00000000009933A2 F:\MeinServer\Build\bin\Release\worldserver.exe
00007FF62811FA3F  000000DCDE3FFA80  0001:00000000004EEA3F F:\MeinServer\Build\bin\Release\worldserver.exe
00007FF8DC4D268A  000000DCDE3FFAB0  _o_exp+5A
00007FF8DFC47974  000000DCDE3FFAE0  BaseThreadInitThunk+14
00007FF8E010A0B1  000000DCDE3FFB60  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FF8E0152A94  000000DCDD78EB60  ZwWaitForAlertByThreadId+14
00007FF8E01083D9  000000DCDD78EBD0  RtlSleepConditionVariableSRW+109
00007FF8DC5CF44D  000000DCDD78EC10  SleepConditionVariableSRW+2D
00007FF8C414BF3D  000000DCDD78EC50  __crtSetThreadpoolWait+3D
00007FF8C4122798  000000DCDD78EC80  ?_Winerror_message@std@@YAKKPEADK@Z+178
00007FF8C4122A4A  000000DCDD78ECB0  _Cnd_wait+3A
00007FF6285C492F  000000DCDD78ECF0  0001:000000000099392F F:\MeinServer\Build\bin\Release\worldserver.exe
00007FF6281009DE  000000DCDD78ED20  0001:00000000004CF9DE F:\MeinServer\Build\bin\Release\worldserver.exe
00007FF6280F10F0  000000DCDD78F0B0  0001:00000000004C00F0 F:\MeinServer\Build\bin\Release\worldserver.exe
00007FF627C93B09  000000DCDD78F130  0001:0000000000062B09 F:\MeinServer\Build\bin\Release\worldserver.exe
00007FF627CA1B3F  000000DCDD78FA40  0001:0000000000070B3F F:\MeinServer\Build\bin\Release\worldserver.exe
00007FF6288507CC  000000DCDD78FA80  argon2id_verify_ctx+5774C
00007FF8DFC47974  000000DCDD78FAB0  BaseThreadInitThunk+14
00007FF8E010A0B1  000000DCDD78FB30  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FF8E014F2A4  000000DCDDDFF660  NtRemoveIoCompletion+14
00007FF8DC5CBBE3  000000DCDDDFF6C0  GetQueuedCompletionStatus+53
00007FF627C985C3  000000DCDDDFF7A0  0001:00000000000675C3 F:\MeinServer\Build\bin\Release\worldserver.exe
00007FF627C9D11F  000000DCDDDFF800  0001:000000000006C11F F:\MeinServer\Build\bin\Release\worldserver.exe
00007FF627C7BC2C  000000DCDDDFF840  0001:000000000004AC2C F:\MeinServer\Build\bin\Release\worldserver.exe
00007FF8DC4D268A  000000DCDDDFF870  _o_exp+5A
00007FF8DFC47974  000000DCDDDFF8A0  BaseThreadInitThunk+14
00007FF8E010A0B1  000000DCDDDFF920  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FF8E014F2A4  000000DCDDEFF970  NtRemoveIoCompletion+14
00007FF8DC5CBBE3  000000DCDDEFF9D0  GetQueuedCompletionStatus+53
00007FF627C985C3  000000DCDDEFFAB0  0001:00000000000675C3 F:\MeinServer\Build\bin\Release\worldserver.exe
00007FF627C9D11F  000000DCDDEFFB10  0001:000000000006C11F F:\MeinServer\Build\bin\Release\worldserver.exe
00007FF627C7BC2C  000000DCDDEFFB50  0001:000000000004AC2C F:\MeinServer\Build\bin\Release\worldserver.exe
00007FF8DC4D268A  000000DCDDEFFB80  _o_exp+5A
00007FF8DFC47974  000000DCDDEFFBB0  BaseThreadInitThunk+14
00007FF8E010A0B1  000000DCDDEFFC30  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FF8E0152A94  000000DCDDFFF850  ZwWaitForAlertByThreadId+14
00007FF8E01083D9  000000DCDDFFF8C0  RtlSleepConditionVariableSRW+109
00007FF8DC5CF44D  000000DCDDFFF900  SleepConditionVariableSRW+2D
00007FF8C414BF3D  000000DCDDFFF940  __crtSetThreadpoolWait+3D
00007FF8C4122798  000000DCDDFFF970  ?_Winerror_message@std@@YAKKPEADK@Z+178
00007FF8C4122A4A  000000DCDDFFF9A0  _Cnd_wait+3A
00007FF6287B5E27  000000DCDDFFF9D0  0001:0000000000B84E27 F:\MeinServer\Build\bin\Release\worldserver.exe
00007FF62811FA3F  000000DCDDFFFA00  0001:00000000004EEA3F F:\MeinServer\Build\bin\Release\worldserver.exe
00007FF8DC4D268A  000000DCDDFFFA30  _o_exp+5A
00007FF8DFC47974  000000DCDDFFFA60  BaseThreadInitThunk+14
00007FF8E010A0B1  000000DCDDFFFAE0  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FF8E0152A94  000000DCDE0FF6C0  ZwWaitForAlertByThreadId+14
00007FF8E01083D9  000000DCDE0FF730  RtlSleepConditionVariableSRW+109
00007FF8DC5CF44D  000000DCDE0FF770  SleepConditionVariableSRW+2D
00007FF8C414BF3D  000000DCDE0FF7B0  __crtSetThreadpoolWait+3D
00007FF8C4122798  000000DCDE0FF7E0  ?_Winerror_message@std@@YAKKPEADK@Z+178
00007FF8C4122A4A  000000DCDE0FF810  _Cnd_wait+3A
00007FF6287B5E27  000000DCDE0FF840  0001:0000000000B84E27 F:\MeinServer\Build\bin\Release\worldserver.exe
00007FF62811FA3F  000000DCDE0FF870  0001:00000000004EEA3F F:\MeinServer\Build\bin\Release\worldserver.exe
00007FF8DC4D268A  000000DCDE0FF8A0  _o_exp+5A
00007FF8DFC47974  000000DCDE0FF8D0  BaseThreadInitThunk+14
00007FF8E010A0B1  000000DCDE0FF950  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FF8E0152A94  000000DCDE1FF660  ZwWaitForAlertByThreadId+14
00007FF8E01083D9  000000DCDE1FF6D0  RtlSleepConditionVariableSRW+109
00007FF8DC5CF44D  000000DCDE1FF710  SleepConditionVariableSRW+2D
00007FF8C414BF3D  000000DCDE1FF750  __crtSetThreadpoolWait+3D
00007FF8C4122798  000000DCDE1FF780  ?_Winerror_message@std@@YAKKPEADK@Z+178
00007FF8C4122A4A  000000DCDE1FF7B0  _Cnd_wait+3A
00007FF6287B5E27  000000DCDE1FF7E0  0001:0000000000B84E27 F:\MeinServer\Build\bin\Release\worldserver.exe
00007FF62811FA3F  000000DCDE1FF810  0001:00000000004EEA3F F:\MeinServer\Build\bin\Release\worldserver.exe
00007FF8DC4D268A  000000DCDE1FF840  _o_exp+5A
00007FF8DFC47974  000000DCDE1FF870  BaseThreadInitThunk+14
00007FF8E010A0B1  000000DCDE1FF8F0  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FF8E014F204  000000DCDE2FFAA0  ZwWaitForSingleObject+14
00007FF8DC5E8973  000000DCDE2FFB40  WaitForSingleObjectEx+93
00007FF627C9D003  000000DCDE2FFB70  0001:000000000006C003 F:\MeinServer\Build\bin\Release\worldserver.exe
00007FF627C9F3F5  000000DCDE2FFBA0  0001:000000000006E3F5 F:\MeinServer\Build\bin\Release\worldserver.exe
00007FF8DC4D268A  000000DCDE2FFBD0  _o_exp+5A
00007FF8DFC47974  000000DCDE2FFC00  BaseThreadInitThunk+14
00007FF8E010A0B1  000000DCDE2FFC80  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FF8E014F204  000000DCDE4FF790  ZwWaitForSingleObject+14
00007FF8DC5E8973  000000DCDE4FF830  WaitForSingleObjectEx+93
00007FF627C9D003  000000DCDE4FF860  0001:000000000006C003 F:\MeinServer\Build\bin\Release\worldserver.exe
00007FF627C9F3F5  000000DCDE4FF890  0001:000000000006E3F5 F:\MeinServer\Build\bin\Release\worldserver.exe
00007FF8DC4D268A  000000DCDE4FF8C0  _o_exp+5A
00007FF8DFC47974  000000DCDE4FF8F0  BaseThreadInitThunk+14
00007FF8E010A0B1  000000DCDE4FF970  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FF8E014F2A4  000000DCDE5FF840  NtRemoveIoCompletion+14
00007FF8DC5CBBE3  000000DCDE5FF8A0  GetQueuedCompletionStatus+53
00007FF627C985C3  000000DCDE5FF980  0001:00000000000675C3 F:\MeinServer\Build\bin\Release\worldserver.exe
00007FF627C9D11F  000000DCDE5FF9E0  0001:000000000006C11F F:\MeinServer\Build\bin\Release\worldserver.exe
00007FF628121CD3  000000DCDE5FFAB0  0001:00000000004F0CD3 F:\MeinServer\Build\bin\Release\worldserver.exe
00007FF62811FA3F  000000DCDE5FFAE0  0001:00000000004EEA3F F:\MeinServer\Build\bin\Release\worldserver.exe
00007FF8DC4D268A  000000DCDE5FFB10  _o_exp+5A
00007FF8DFC47974  000000DCDE5FFB40  BaseThreadInitThunk+14
00007FF8E010A0B1  000000DCDE5FFBC0  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FF8E014F244  000000DCDE6FF350  NtReadFile+14
00007FF8DC5CF6F7  000000DCDE6FF3D0  ReadFile+77
00007FF8DC4C58F1  000000DCDE6FF470  _fileno+1A1
00007FF8DC4C5A32  000000DCDE6FF4B0  _read+A2
00007FF8DC4C567C  000000DCDE6FF4E0  _isatty+CC
00007FF8DC5212BE  000000DCDE6FF520  _fgetwc_nolock+FE
00007FF8DC521130  000000DCDE6FF580  getc+1A0
00007FF627CA1FE6  000000DCDE6FF940  0001:0000000000070FE6 F:\MeinServer\Build\bin\Release\worldserver.exe
00007FF627C7BBCB  000000DCDE6FF970  0001:000000000004ABCB F:\MeinServer\Build\bin\Release\worldserver.exe
00007FF8DC4D268A  000000DCDE6FF9A0  _o_exp+5A
00007FF8DFC47974  000000DCDE6FF9D0  BaseThreadInitThunk+14
00007FF8E010A0B1  000000DCDE6FFA50  RtlUserThreadStart+21
========================
Local Variables And Parameters

Call stack:
Address   Frame     Function      SourceFile
00007FF8DC5E96C9  000000DCDE3FF4F0  RaiseException+69

00007FF6287C6196  000000DCDE3FF5E0  0001:0000000000B95196 F:\MeinServer\Build\bin\Release\worldserver.exe

00007FF62812ACD9  000000DCDE3FF660  0001:00000000004F9CD9 F:\MeinServer\Build\bin\Release\worldserver.exe

00007FF6281656B7  000000DCDE3FF7D0  0001:00000000005346B7 F:\MeinServer\Build\bin\Release\worldserver.exe

00007FF62814C077  000000DCDE3FF810  0001:000000000051B077 F:\MeinServer\Build\bin\Release\worldserver.exe

00007FF62814BCB5  000000DCDE3FF840  0001:000000000051ACB5 F:\MeinServer\Build\bin\Release\worldserver.exe

00007FF628687320  000000DCDE3FF870  0001:0000000000A56320 F:\MeinServer\Build\bin\Release\worldserver.exe

00007FF6283546EF  000000DCDE3FF960  0001:00000000007236EF F:\MeinServer\Build\bin\Release\worldserver.exe

00007FF62835423B  000000DCDE3FF9A0  0001:000000000072323B F:\MeinServer\Build\bin\Release\worldserver.exe

00007FF6285C3901  000000DCDE3FF9D0  0001:0000000000992901 F:\MeinServer\Build\bin\Release\worldserver.exe

00007FF6285C3C5F  000000DCDE3FFA00  0001:0000000000992C5F F:\MeinServer\Build\bin\Release\worldserver.exe

00007FF6285C43A2  000000DCDE3FFA50  0001:00000000009933A2 F:\MeinServer\Build\bin\Release\worldserver.exe

00007FF62811FA3F  000000DCDE3FFA80  0001:00000000004EEA3F F:\MeinServer\Build\bin\Release\worldserver.exe

00007FF8DC4D268A  000000DCDE3FFAB0  _o_exp+5A

00007FF8DFC47974  000000DCDE3FFAE0  BaseThreadInitThunk+14

00007FF8E010A0B1  000000DCDE3FFB60  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FF8E0152A94  000000DCDD78EB60  ZwWaitForAlertByThreadId+14

00007FF8E01083D9  000000DCDD78EBD0  RtlSleepConditionVariableSRW+109

00007FF8DC5CF44D  000000DCDD78EC10  SleepConditionVariableSRW+2D

00007FF8C414BF3D  000000DCDD78EC50  __crtSetThreadpoolWait+3D

00007FF8C4122798  000000DCDD78EC80  ?_Winerror_message@std@@YAKKPEADK@Z+178

00007FF8C4122A4A  000000DCDD78ECB0  _Cnd_wait+3A

00007FF6285C492F  000000DCDD78ECF0  0001:000000000099392F F:\MeinServer\Build\bin\Release\worldserver.exe

00007FF6281009DE  000000DCDD78ED20  0001:00000000004CF9DE F:\MeinServer\Build\bin\Release\worldserver.exe

00007FF6280F10F0  000000DCDD78F0B0  0001:00000000004C00F0 F:\MeinServer\Build\bin\Release\worldserver.exe

00007FF627C93B09  000000DCDD78F130  0001:0000000000062B09 F:\MeinServer\Build\bin\Release\worldserver.exe

00007FF627CA1B3F  000000DCDD78FA40  0001:0000000000070B3F F:\MeinServer\Build\bin\Release\worldserver.exe

00007FF6288507CC  000000DCDD78FA80  argon2id_verify_ctx+5774C

00007FF8DFC47974  000000DCDD78FAB0  BaseThreadInitThunk+14

00007FF8E010A0B1  000000DCDD78FB30  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FF8E014F2A4  000000DCDDDFF660  NtRemoveIoCompletion+14

00007FF8DC5CBBE3  000000DCDDDFF6C0  GetQueuedCompletionStatus+53

00007FF627C985C3  000000DCDDDFF7A0  0001:00000000000675C3 F:\MeinServer\Build\bin\Release\worldserver.exe

00007FF627C9D11F  000000DCDDDFF800  0001:000000000006C11F F:\MeinServer\Build\bin\Release\worldserver.exe

00007FF627C7BC2C  000000DCDDDFF840  0001:000000000004AC2C F:\MeinServer\Build\bin\Release\worldserver.exe

00007FF8DC4D268A  000000DCDDDFF870  _o_exp+5A

00007FF8DFC47974  000000DCDDDFF8A0  BaseThreadInitThunk+14

00007FF8E010A0B1  000000DCDDDFF920  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FF8E014F2A4  000000DCDDEFF970  NtRemoveIoCompletion+14

00007FF8DC5CBBE3  000000DCDDEFF9D0  GetQueuedCompletionStatus+53

00007FF627C985C3  000000DCDDEFFAB0  0001:00000000000675C3 F:\MeinServer\Build\bin\Release\worldserver.exe

00007FF627C9D11F  000000DCDDEFFB10  0001:000000000006C11F F:\MeinServer\Build\bin\Release\worldserver.exe

00007FF627C7BC2C  000000DCDDEFFB50  0001:000000000004AC2C F:\MeinServer\Build\bin\Release\worldserver.exe

00007FF8DC4D268A  000000DCDDEFFB80  _o_exp+5A

00007FF8DFC47974  000000DCDDEFFBB0  BaseThreadInitThunk+14

00007FF8E010A0B1  000000DCDDEFFC30  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FF8E0152A94  000000DCDDFFF850  ZwWaitForAlertByThreadId+14

00007FF8E01083D9  000000DCDDFFF8C0  RtlSleepConditionVariableSRW+109

00007FF8DC5CF44D  000000DCDDFFF900  SleepConditionVariableSRW+2D

00007FF8C414BF3D  000000DCDDFFF940  __crtSetThreadpoolWait+3D

00007FF8C4122798  000000DCDDFFF970  ?_Winerror_message@std@@YAKKPEADK@Z+178

00007FF8C4122A4A  000000DCDDFFF9A0  _Cnd_wait+3A

00007FF6287B5E27  000000DCDDFFF9D0  0001:0000000000B84E27 F:\MeinServer\Build\bin\Release\worldserver.exe

00007FF62811FA3F  000000DCDDFFFA00  0001:00000000004EEA3F F:\MeinServer\Build\bin\Release\worldserver.exe

00007FF8DC4D268A  000000DCDDFFFA30  _o_exp+5A

00007FF8DFC47974  000000DCDDFFFA60  BaseThreadInitThunk+14

00007FF8E010A0B1  000000DCDDFFFAE0  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FF8E0152A94  000000DCDE0FF6C0  ZwWaitForAlertByThreadId+14

00007FF8E01083D9  000000DCDE0FF730  RtlSleepConditionVariableSRW+109

00007FF8DC5CF44D  000000DCDE0FF770  SleepConditionVariableSRW+2D

00007FF8C414BF3D  000000DCDE0FF7B0  __crtSetThreadpoolWait+3D

00007FF8C4122798  000000DCDE0FF7E0  ?_Winerror_message@std@@YAKKPEADK@Z+178

00007FF8C4122A4A  000000DCDE0FF810  _Cnd_wait+3A

00007FF6287B5E27  000000DCDE0FF840  0001:0000000000B84E27 F:\MeinServer\Build\bin\Release\worldserver.exe

00007FF62811FA3F  000000DCDE0FF870  0001:00000000004EEA3F F:\MeinServer\Build\bin\Release\worldserver.exe

00007FF8DC4D268A  000000DCDE0FF8A0  _o_exp+5A

00007FF8DFC47974  000000DCDE0FF8D0  BaseThreadInitThunk+14

00007FF8E010A0B1  000000DCDE0FF950  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FF8E0152A94  000000DCDE1FF660  ZwWaitForAlertByThreadId+14

00007FF8E01083D9  000000DCDE1FF6D0  RtlSleepConditionVariableSRW+109

00007FF8DC5CF44D  000000DCDE1FF710  SleepConditionVariableSRW+2D

00007FF8C414BF3D  000000DCDE1FF750  __crtSetThreadpoolWait+3D

00007FF8C4122798  000000DCDE1FF780  ?_Winerror_message@std@@YAKKPEADK@Z+178

00007FF8C4122A4A  000000DCDE1FF7B0  _Cnd_wait+3A

00007FF6287B5E27  000000DCDE1FF7E0  0001:0000000000B84E27 F:\MeinServer\Build\bin\Release\worldserver.exe

00007FF62811FA3F  000000DCDE1FF810  0001:00000000004EEA3F F:\MeinServer\Build\bin\Release\worldserver.exe

00007FF8DC4D268A  000000DCDE1FF840  _o_exp+5A

00007FF8DFC47974  000000DCDE1FF870  BaseThreadInitThunk+14

00007FF8E010A0B1  000000DCDE1FF8F0  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FF8E014F204  000000DCDE2FFAA0  ZwWaitForSingleObject+14

00007FF8DC5E8973  000000DCDE2FFB40  WaitForSingleObjectEx+93

00007FF627C9D003  000000DCDE2FFB70  0001:000000000006C003 F:\MeinServer\Build\bin\Release\worldserver.exe

00007FF627C9F3F5  000000DCDE2FFBA0  0001:000000000006E3F5 F:\MeinServer\Build\bin\Release\worldserver.exe

00007FF8DC4D268A  000000DCDE2FFBD0  _o_exp+5A

00007FF8DFC47974  000000DCDE2FFC00  BaseThreadInitThunk+14

00007FF8E010A0B1  000000DCDE2FFC80  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FF8E014F204  000000DCDE4FF790  ZwWaitForSingleObject+14

00007FF8DC5E8973  000000DCDE4FF830  WaitForSingleObjectEx+93

00007FF627C9D003  000000DCDE4FF860  0001:000000000006C003 F:\MeinServer\Build\bin\Release\worldserver.exe

00007FF627C9F3F5  000000DCDE4FF890  0001:000000000006E3F5 F:\MeinServer\Build\bin\Release\worldserver.exe

00007FF8DC4D268A  000000DCDE4FF8C0  _o_exp+5A

00007FF8DFC47974  000000DCDE4FF8F0  BaseThreadInitThunk+14

00007FF8E010A0B1  000000DCDE4FF970  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FF8E014F2A4  000000DCDE5FF840  NtRemoveIoCompletion+14

00007FF8DC5CBBE3  000000DCDE5FF8A0  GetQueuedCompletionStatus+53

00007FF627C985C3  000000DCDE5FF980  0001:00000000000675C3 F:\MeinServer\Build\bin\Release\worldserver.exe

00007FF627C9D11F  000000DCDE5FF9E0  0001:000000000006C11F F:\MeinServer\Build\bin\Release\worldserver.exe

00007FF628121CD3  000000DCDE5FFAB0  0001:00000000004F0CD3 F:\MeinServer\Build\bin\Release\worldserver.exe

00007FF62811FA3F  000000DCDE5FFAE0  0001:00000000004EEA3F F:\MeinServer\Build\bin\Release\worldserver.exe

00007FF8DC4D268A  000000DCDE5FFB10  _o_exp+5A

00007FF8DFC47974  000000DCDE5FFB40  BaseThreadInitThunk+14

00007FF8E010A0B1  000000DCDE5FFBC0  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FF8E014F244  000000DCDE6FF350  NtReadFile+14

00007FF8DC5CF6F7  000000DCDE6FF3D0  ReadFile+77

00007FF8DC4C58F1  000000DCDE6FF470  _fileno+1A1

00007FF8DC4C5A32  000000DCDE6FF4B0  _read+A2

00007FF8DC4C567C  000000DCDE6FF4E0  _isatty+CC

00007FF8DC5212BE  000000DCDE6FF520  _fgetwc_nolock+FE

00007FF8DC521130  000000DCDE6FF580  getc+1A0

00007FF627CA1FE6  000000DCDE6FF940  0001:0000000000070FE6 F:\MeinServer\Build\bin\Release\worldserver.exe

00007FF627C7BBCB  000000DCDE6FF970  0001:000000000004ABCB F:\MeinServer\Build\bin\Release\worldserver.exe

00007FF8DC4D268A  000000DCDE6FF9A0  _o_exp+5A

00007FF8DFC47974  000000DCDE6FF9D0  BaseThreadInitThunk+14

00007FF8E010A0B1  000000DCDE6FFA50  RtlUserThreadStart+21

go in/out instances, random crashes. If u need more Information, tell me :) 
Thank you.

**Comment by trickerer** [comment]
Try to set in config MapUpdate.Threads = 1

There is a problem with teleportation of creatures between maps, it's yet to be solved.

**Comment by littlehelper1987** [comment]
Hey trickerer,

thank you for ur Support. Unfortunately, this option was already set :/.

**Comment by trickerer** [comment]
Just for reference most recent issue like this #39

**Comment by trickerer** [comment]
73b68bea937d is not a TrinityCore revision, are you using custom modifications?

**Comment by trickerer** [comment]
Assuming invalid
