### ISSUE TITLE
[AC] [Bug] [Core] Reversed (or previously applied) patch detected!

### ISSUE THREAD

**Issue by lmzml** [trickerer/Trinity-Bots#570]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

I am using this project：AzerothCore-wotlk-with-NPCBots
When I use the _patch - p1 < NPCBots.patch_ command，display this：
![微信截图_20230712153526](https://github.com/trickerer/Trinity-Bots/assets/97717237/12100a8e-f6da-41ff-bebd-6f179485ea20)
How should I operate？

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. unknown 1970-01-01 00:00:00 +0000 (Archived branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon) ready...

**Comment by trickerer** [comment]
You're using pre-patched repository and trying to patch it over again.
Don't do that. Just run CMake & build.

**Comment by lmzml** [comment]
Thanks!!!
