### ISSUE TITLE
If project AzerothCore-wotlk-with-NPCBots is used, do you still need to execute additional SQL in project Trinity-Bots?

### ISSUE THREAD

**Issue by lmzml** [trickerer/Trinity-Bots#571]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

If project AzerothCore-wotlk-with-NPCBots is used, do you still need to execute additional SQL in project Trinity-Bots?

### TrinityCore or AzerothCore

AzerothCore

**Comment by trickerer** [comment]
No, AC executes all required SQL files automatically if `Updates.EnableDatabases` is set to 7 in worldserver.conf (all DBs, default)

The only SQL file you may want to execute additionally is your localization of bots if it exists. Locales are located is `SQL/locales/`

**Comment by trickerer** [comment]
The patch creates all required SQL files when applied, so answer is the same.

Just in case you're interested bot SQLs are located in `data/sql/custom/`

**Comment by trickerer** [comment]
Yes, unless DB auto updates are disabled. Also, if you apply all the SQLs yourself it won't break anything.
Sorry Readme isn't updated for AC, as you can see the path so SQL files is different between two cores, this was made so AC autoupdater could find them.

**Comment by lmzml** [comment]
I have previously executed SQL for AC, but due to a foreign key error in the database table.
![微信截图_20230712223725](https://github.com/trickerer/Trinity-Bots/assets/97717237/f5415e2f-d04b-47c2-b0ca-099b5659d96b)
This database table must be deleted for successful execution.
Can you delete the foreign key settings for this database?

**Comment by trickerer** [comment]
I can't.
The sql files are supposed to automatically executed in order that makes `characters_npcbot` table to be created first so there is no conflict. And even if not, foreign key checks are disabled at this point of execution.
What is the error you get?

**Comment by lmzml** [comment]
![微信截图_20230712231553](https://github.com/trickerer/Trinity-Bots/assets/97717237/33b835df-8d76-495a-b45c-6e61c54556cd)

**Comment by vurtne** [comment]
My problem is that after killing the BOSS in all instances, the server reports an error, indicating that it is indeed a Mapid
