### ISSUE TITLE
[AC] [Bug/Crash] instant crash when que for bg

### ISSUE THREAD

**Issue by Griptor** [trickerer/Trinity-Bots#572]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

As soon as I que for a bg i get an instant crash :(
This has been happing on my level 80 for some time which didn't worry me a couple of weeks ago.  Around the time AB got added.

using modules

dungeonrespawn
mod-account-achivements
mod-accountbound
mod-ah-bot
mod-autobalance
mod-learn-spells
mod-random-enchants
mod-skip-dk-starting-area
mod-solocraft
mod-solo-lfg
mod-transmog

### Expected behaviour

Thought it was only on level 80 but now I'm level 13 and as soon as I queue it freezes and the crash log gets created instantly. 

Go to wsg, av or ab

### Crashlog

attached

### Steps to reproduce the problem

Start server
Log in
Que for bg
Crash

[c42befe118b7+_worldserver.exe_[13-7_21-4-46].txt](https://github.com/trickerer/Trinity-Bots/files/12039092/c42befe118b7%2B_worldserver.exe_.13-7_21-4-46.txt)

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AC with npc bots latest 13/7/2023

### Operating system

win 11

**Comment by trickerer** [comment]
You're using original autobalance without npcbots support. Original autobalance crashes the server when BG map is created.
See here: https://github.com/trickerer/Trinity-Bots/issues/546

**Comment by Griptor** [comment]
Ooh! That's awesome man thanx ill do that today 😀 I didn't think autobalance would interfere with bgs lol who knew
