### ISSUE TITLE
[AC] [Crash] [Core] Crashes caused by insufficient wandering bot

### ISSUE THREAD

**Issue by WildBlizzard** [trickerer/Trinity-Bots#573]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

core crash

### Expected behaviour

not crash

### Crashlog

<script src="https://gist.github.com/WildBlizzard/cc736676f15848ce56295a49dff9db4b.js"></script>

### Steps to reproduce the problem

1. Enabled NpcBot.WanderingBots.Continents.Count = 50
2. Enabled NpcBot.Enable.BG            = 1
3. Spawned some bots in game(I created some bots, about 40+)
4. ReStarted worldserver.
5. Crashed.

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

c42befe118b739fbe11594caab0eb5f10ed7c6f6

### Operating system

CentOS7.9

**Comment by hkbbdx** [comment]
me too

**Comment by trickerer** [comment]
Asserion message says it all. It's that either most of the classes are disabled or too many bots are spawned.
If and when you're able to provide all the related info feel free to reopen this issue (enabled bot classes config listing, number of `characters_npcbot` table entries)
