### ISSUE TITLE
[AC] [Bug] [Core] Somitimes bosses dont drop anything

### ISSUE THREAD

**Issue by DykeRz** [trickerer/Trinity-Bots#575]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Sorry to ask a question here, but i can't find the answer anywhere, the fact is that sometimes on my server bosses don't give a drop randomly, you can kill Lord in ICC and get drop, then you kill Lady and she dont drop anything, then you kill another bosses and get drop, coming to Lich King, kill him and he dont drop anything. This problem in all dungeons, some random bosses dont drop anything

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

864e405

### Operating system

debian 11

**Comment by trickerer** [comment]
1) Do you have any additional changes in Unit.cpp (Unit::DealDamage)?

2) Some module or script could interfere with that. For example, some autobalance-like mod could reduce boss' max hp by 50% (or more), at the same time required damage to receive the reward is unchanged. This way, depending on original max hp being even or odd, you may be unable to deal enough damage to get loot.

**Comment by DykeRz** [comment]
> 1. Do you have any additional changes in Unit.cpp (Unit::DealDamage)?
> 2. Some module or script could interfere with that. For example, some autobalance-like mod could reduce boss' max hp by 50% (or more), at the same time required damage to receive the reward is unchanged. This way, depending on original max hp being even or odd, you may be unable to deal enough damage to get loot.

1. No

2. it seems to be true that players do not deal enough damage to get loot, and where is this amount of damage regulated? or do i need to change autobalance somehow?

**Comment by trickerer** [comment]
You can't do any of that through mod config I don't think, you'll have to ask your mod's developer.

**Comment by DykeRz** [comment]
> You can't do any of that through mod config I don't think, you'll have to ask your mod's developer.

im using this mod, your  :)

https://github.com/trickerer/mod-autobalance

maybe i must modify unit.cpp?

**Comment by DykeRz** [comment]
and i'm using your core with bots, last commit

**Comment by trickerer** [comment]
What are your non-default settings for autobalance? And how many bots were you using?

**Comment by DykeRz** [comment]
> What are your non-default settings for autobalance? And how many bots were you using?

this is my settings conf autobalance

### 5-player dungeons
AutoBalance.InflectionPoint=0.5
AutoBalance.InflectionPoint.CurveFloor=0.0
AutoBalance.InflectionPoint.CurveCeiling=1.0
AutoBalance.InflectionPoint.BossModifier=1.0

### 5-player heroic dungeons
AutoBalance.InflectionPointHeroic=0.5
AutoBalance.InflectionPointHeroic.CurveFloor=0.0
AutoBalance.InflectionPointHeroic.CurveCeiling=1.0
AutoBalance.InflectionPointHeroic.BossModifier=1.0

### Default for all raids
AutoBalance.InflectionPointRaid=0.55
AutoBalance.InflectionPointRaid.CurveFloor=0.0
AutoBalance.InflectionPointRaid.CurveCeiling=1.0
AutoBalance.InflectionPointRaid.BossModifier=1.0

### Default for all heroic raids
AutoBalance.InflectionPointRaidHeroic=0.53
AutoBalance.InflectionPointRaidHeroic.CurveFloor=0.0
AutoBalance.InflectionPointRaidHeroic.CurveCeiling=1.0
AutoBalance.InflectionPointRaidHeroic.BossModifier=1.5

AutoBalance.InflectionPoint.PerInstance="564 0.35 0.0 1.0, 534 0.35 0.0 1.0, 548 0.35 0.0 1.0, 568 0.35 0.0 1.0, 532 0.35 0.0 1.0, 550 0.35 0.0 1.0, 565 0.35 0.0 1.0, 544 0.35 0.0 1.0, 580 0.35 0.0 1.0"

AutoBalance.RewardScaling.XP = 0

AutoBalance.RewardScaling.Money = 0

this lines what i changed

**Comment by DykeRz** [comment]
i using 1 bot + 1 player = 2

1 bot for 1 player

**Comment by DykeRz** [comment]
I want to players can going dungeons only with 1 bot and successfully done dungeons with 1 bot

**Comment by DykeRz** [comment]
something is wrong with autobalance, when i turn it off, loot is always there, when i turn it on, there is no loot from bosses

**Comment by DykeRz** [comment]
I will donate for resolving its problem

**Comment by trickerer** [comment]
I tested whole dungeon twice with autobalance enabled in group of 1 player + 1 bot and each time I was getting loot from every boss. Most damage was done by the bot.

Autobalance code contains a call to `ResetPlayerDamageReq()` when hp is adjusted so something must have interfered in your case that prevented boss from hitting loot condition. I see 2 possible reasons:
1) No damage done to boss by player after last HP adjust.
2) Most of damage done to boss didn't count as player damage.

If there are no more players on the server and no bots entered or left the map before boss kill to cause autobalance stats update 1st possibility can be struck out.
So probably your bot didn't count as NPCBot.
You may want to use a debugger. Set a breakpoint at about Unit.cpp:L1125 (look for `LowerPlayerDamageReq`) with `attacker != nullptr && attacker->m_uint32Values[3] > 70000` condition and let bot attack something. If `damagedByPlayer` value is false then therer is something wrong with your DB setup regarding to bots as they count as typical uncontrolled creatures.

**Comment by danieldfischer** [comment]
To add some anecdotal evidence I've seen this occur on a server (AzerothCore-wotlk-with-NPCBots] + the forked mod-autobalance) while running dungeons solo, no players or NPCBots.

Looking at the base mod-autobalance repo there was a commit in August that fixed not getting credit for loot. https://github.com/azerothcore/mod-autobalance/pull/145.

That issue was caused by the player leveling up while in the dungeon. Now I can't say for sure this was my issue but I will update the server and test. If it continues to occur I'll spin up a fresh server with minimal mods to see if I can narrow down the issue / rule it out as NPCBot specific.
