### ISSUE TITLE
[AC] [Bug] [Core] Solocraft

### ISSUE THREAD

**Issue by DykeRz** [trickerer/Trinity-Bots#576]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Your Solocraft module dont work for ICC

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

864e405

### Operating system

debian 11

**Comment by DykeRz** [comment]
I will donate for resolving it, or for resolve autobalance looting bosses :) если что я рус

**Comment by trickerer** [comment]
https://github.com/trickerer/mod-solocraft/commit/4e940d69f0e95ee5a33bf36020b07a8b7b4b689e
