### ISSUE TITLE
[TC] Patching Error with last TrinityCore / invisible bots

### ISSUE THREAD

**Issue by Krutok** [trickerer/Trinity-Bots#577]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

The patch cannot be applied with the last TC Core. I get the error message as shown in the screenshot.

![Screenshot 2023-07-22 152423](https://github.com/trickerer/Trinity-Bots/assets/47283866/66bdede8-1d59-4ed6-b109-c9016f547969)

But as I can see the last botpatch is 3 weeks old, so it doesn't surprise me that it doesn't work.

Furthermore, my bots are all invisible. They buff me when I'm close, but I can't see them, only their pets
![Screenshot 2023-07-22 153034](https://github.com/trickerer/Trinity-Bots/assets/47283866/442d8961-9046-4a4b-9822-131f4cd6fa14)

I have now entered the part that was not patched manually and am testing it.
An update of the Rev version will be submitted later. The one I've posted now is from the last TC patch

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

TrinityCore rev. 2eb778ae635f+ 2023-06-21

### Operating system

Debian 11

**Comment by trickerer** [comment]
You didn't apply bot SQL updates so they aren't recognized as bots by the server and they don't send appearance info.

**Comment by Krutok** [comment]
> You didn't apply bot SQL updates so they aren't recognized as bots by the server and they don't send appearance info.

I've always updated all SQL files because when I start the world server I don't get an error message either, so I don't know which SQL files should be missing

**Comment by Krutok** [comment]
My bots remain invisible.
When I try to add new bots, my server crashes.

https://gist.github.com/Krutok/ba24df14fe12a587f9d1fd1d03185671

TrinityCore rev. f9033a5dbd55+ 2023-07-19 13:45:17 +0200 (3.3.5 branch) (Unix, RelWithDebInfo, Static)

**Comment by Krutok** [comment]
Therefore I have now installed the patch from 2.6.23 on the previous core. and now the bots are working again. Since I remove all patches I was able to reproduce the point in time when the bots stopped working, namely with the 06/14/23 patch my bots became invisible. So it must be related to the patch.

I also don't know which sql file I forgot. Unfortunately, there is no documentation as to which SQL files you need to import.

**Comment by trickerer** [comment]
It's either `2023_04_28_00_creature_template.sql` or  `2023_06_03_00_creature_template.sql` (or both). They are in your sql/Bots/updates/world/ folder
Simply saying you have to apply new sql files since last update, but in fact all bot SQLs for `world` DB can be re-applied safely (if you don't have custom created bots)

**Comment by Krutok** [comment]
Ok the bots now work with the last patch from 14.6.23. But they no longer work with the latest one available here, as it is no longer compatible with the current TC version.

**Comment by trickerer** [comment]
https://github.com/trickerer/Trinity-Bots/commit/73fd176d05cb9610e862220a5a219b0f874f584a
