### ISSUE TITLE
Enhancement - Auto-loot system

### ISSUE THREAD

**Issue by Ryu1254** [trickerer/Trinity-Bots#58]
Since bot are very useful doing dungeon, raid, quest etc...
when doing old raid to farm rep, item etc and there are a lot of mob to loot. with bot in the way.. it a bit in the way sometime.
if would be nice if we can have bot do auto-loot for us or some sort of autoloot system :)

What do you think?

here what i found, something already exist, but no group loot. probably you can improve it to implement with bot or on the side that accept group loot. 
[autoloot.txt](https://github.com/trickerer/Trinity-Bots/files/5756476/autoloot.txt)

**Comment by trickerer** [comment]
> here what i found, something already exist, but no group loot. probably you can improve it to implement with bot or on the side that accept group loot.
autoloot.txt

What an ugly hack.

Autoloot can be done without much trouble through roles. I have a doubt though regarding unwanted loot types. Just can't say how much detailed the filter has to be.

**Comment by Ryu1254** [comment]
I can imagine that could be very complicate, but what if we go with quality group of item ??
like --> autoloot quality
All
common
rare
epic

Quest item are automatically loot regardless.
is that sound more feasible?

**Comment by trickerer** [comment]
Filter by quality is fine.

What if several players are in the same group? Bound on pickup loot will be a problem if bots are allowed to collect loot freely

**Comment by Ryu1254** [comment]
In 1 player with only bot. all loot should go to player.
In group with other play. The bot should loot only what the creature loot assign to the player.
For Bind on pickup item, the popup for need/greed should display.
We don’t want bot loot  thing that are not assign to us.

**Comment by Ryu1254** [comment]
I made a visio flow, hope this can help for logic decision.

![auto loot logic](https://user-images.githubusercontent.com/72590132/103433039-231b7600-4bb8-11eb-9e24-888bfcaf3694.png)

**Comment by trickerer** [comment]
testing gittube

https://user-images.githubusercontent.com/1254989/103623602-e6aa9a00-4f6a-11eb-8eac-8dbb21842e95.mp4

**Comment by Parkan1986** [comment]
Прикольно. Удобно

**Comment by trickerer** [comment]
I didn't make bots actually go to each corpse, so they just force pop nearby lootable corpses. Loot methods work, but situations with 2+ players are not tested.

**Comment by Ryu1254** [comment]
Excellent, your are the best.
I'm compiling it now and will test it once it done.

**Comment by Ryu1254** [comment]
WOW... this new autoloot feature is super cool.
I did test the solo bot loot: working as intended
group loot with another player with different threshold : working as intended
group with by pass loot option: working as intended
i also test different item quality: working as intended.

Man you rock!!!! I wish I could do cool stuff like this, you make me jealous of your skill :)
