### ISSUE TITLE
[AC] [Bug] [Spell] Priest's Prayer of Mending cannot be cast on the target.

### ISSUE THREAD

**Issue by saliven1970** [trickerer/Trinity-Bots#586]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

When another character is set as the target character, the Priest's Prayer of Mending cannot be cast on the target, but when the target is cancelled or the target is himself, it can be cast on himself.

### Expected behaviour

Priest's Prayer of Mending should be able to be cast on other characters.

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

Azeroth Core, Versions will appear after June 2023, and versions before May will be fine.

### Operating system

ubuntu 22.04

**Comment by saliven1970** [comment]
Other characters are NpcBots at present,so I will test the situation in real characters again.

**Comment by saliven1970** [comment]
I test the situation in real characters,Add a real character to the team,and it can work well.

**Comment by saliven1970** [comment]
Once again, I found a problem, such as knight's power blessing and king's blessing. As long as it is a big BUFF for team members at one time, it can't be cast, but a small BUFF for a single member can.And this priest's skill also needs to judge team members, and can only be cast by one person.

**Comment by trickerer** [comment]
https://github.com/trickerer/Trinity-Bots#npcbot-commands

You cannot use abilities, which can only target players, on bots. You have to use `.npcbot useonbot spell` command (`.npcb use s`). Make a macro. Target(s) selection should work normally (Prayer of Mending should jump from / to bots, Greater Blessings should include bots on selected target's class, etc.)
