### ISSUE TITLE
Enhancement - Bot giver also give some details of the bot

### ISSUE THREAD

**Issue by Ryu1254** [trickerer/Trinity-Bots#59]
When interact with the Bot Giver, is it possible to also display the race, and gender of the bot to hire?

**Comment by trickerer** [comment]
Yes, but this info may not fit into a single row. Yes, I am keeping track of such things. Using a bold font though.

**Comment by xtracripper** [comment]
You could abbreviate.
Ex: Wu [A][Hu] or just Wu [Hu]

Alliance [A], Horde [H]
HUman [HU], NightElf [NE], DRaenei [DR], DWarf [DW], GNome [GN]
ORc [OR], TRoll [TR], TAuren [TA], UNdead [UN], Blood Elf [BE]

**Comment by Ryu1254** [comment]
Abbreviation is ok too. 

as long as we have something like this in the name.

![image](https://user-images.githubusercontent.com/72590132/103559897-e8019700-4e84-11eb-83e0-12c4bfc82c48.png)

**Comment by trickerer** [comment]
I have this working already, so no worries. It will be pushed within 24 hours

**Comment by Ryu1254** [comment]
beautiful, now I can pick an choose what bot I want.. hehe hate to see a big fat torrent female in a group..
