### ISSUE TITLE
[TC] [AC] [Question] [Commands] `.npcbot delete id` not working

### ISSUE THREAD

**Issue by oblisgr** [trickerer/Trinity-Bots#592]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

i m trying to delete an npcbot by using .npcbot delete id 70840 but when i restart the server it appears again.
why this happening?

### TrinityCore or AzerothCore

TrinityCore

**Comment by trickerer** [comment]
This could happen because bot was not in the same map where it was spawned. It's a TC-only bug. It was fixed for `.npcb delete` command but not for `.npcb delete id`
