### ISSUE TITLE
[TC] [AC] [Question] [Group/Spell/Core] can bots use meeting stone?

### ISSUE THREAD

**Issue by canbingzt** [trickerer/Trinity-Bots#593]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

can bots use meeting stone?

### TrinityCore or AzerothCore

TrinityCore

**Comment by Russianranger** [comment]
Negative- They cannot use meeting stone currently.
