### ISSUE TITLE
[AC] [Bug] Unable to create archmage robot!

### ISSUE THREAD

**Issue by lmzml** [trickerer/Trinity-Bots#597]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

When I try to create an Archmage robot using the following command
.npcbot createnew testname 14
An error was returned
![微信截图_20230809223721](https://github.com/trickerer/Trinity-Bots/assets/97717237/fa506631-00c3-4327-a7b3-628b85832c6c)

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. unknown 1970-01-01 00:00:00 +0000 (Archived branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon) ready...

### Operating system

Ubuntu 22.04

**Comment by trickerer** [comment]
Yes, Archmage can change appearance, so you have to provide values for those parameters.
Default values can be fetched by executing following query in your world DB:
`SELECT * FROM creature_template_npcbot_appearance WHERE entry = 70555;`
