### ISSUE TITLE
[TC] [AC] [Question] [Group] More autonomous tank bots?

### ISSUE THREAD

**Issue by Boxhead78** [trickerer/Trinity-Bots#599]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Right now from my experience in dungeons, Tank-Bots mostly target the foe which the master is targeting/attacking, except for taunts and other take-aggro related abilities which the tank will cast on enemies where the Tank-Bot doesn't have aggro on.

Is it possible to make the tanks choose their current target a bit more independetly from their master so that they priorize to target enemies which have aggro on either the player or other NPCBots in the group?

### TrinityCore or AzerothCore

Both

**Comment by trickerer** [comment]
Owned bots can't have their attack target selected independently from master, only targets for abilities can be selected depending on current situation, this includes taunts (30 yds is more than enough I think). And bots don't have any idea what tanking position is best for the encounter except for trying to make sure nobody attacks from behind.
While you obviously can't attack more than one target at once, you can force target selection for your bots based on roles, using group target icons. Look for `NpcBot.TankTargetIconMask` in `worldserver.conf`.
You can also use `.npcbot send` command to force bot's (tanking) position.

Also, tanks use distant taunts on targets not just which they don't have aggro on, but ones attacking non-tanks or to save some other tank at death's door.

**Comment by Boxhead78** [comment]
Thank you for explaining 😃
