### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by oldmagic** [trickerer/Trinity-Bots#6]
/home/wow/TrinityCore/src/server/game/AI/NpcBots/bot_ai.cpp:1:10: fatal error: bot_ai.h: No such file or directory
    1 | #include "bot_ai.h"

Not sure if i have done something wrong here, but simply applyed the patch and this came out.

**Comment by itdevsteve** [comment]
Verified perfectly working "last" patch this morning on personal server, using a fresh TC 3.3.5 f2f4fc921e clone.

Make sure to do a new clone, patch, and then compile.  You can try to run "make clean" to see if that fixes the issue if the patch command ran properly.

**Comment by oldmagic** [comment]
Ah yeah, did do that now and it compiles!
