### ISSUE TITLE
Feature Request: Backup similar to pdump but for bots

### ISSUE THREAD

**Issue by cherbert** [trickerer/Trinity-Bots#60]
Would be really nice to have a command like pdump but backs up all our owned bots, their appearance and their equipment. So we can then restore them to a new fresh build.

Sometimes a lot of effort is put into bot placement in the world, their appearance and the items they are equipped with. I know how to do all this manually and I am doing it but a command line option to dump it all to a file would be really convenient and potentially very useful for a lot of players.

**Comment by zaicopx** [comment]
Yes, this is also what I expected

**Comment by trickerer** [comment]
@cherbert what exactly do you mean by efforts put into bot appearance? What data in which tables?

**Comment by cherbert** [comment]
I mean we put a lot of effort into equipping our bots with armor and weapons etc... It would be nice to backup the bots we have spawned into the world and for the backup to also contain their equipped items so as to be able to restore this data to a fresh new build easily.

**Comment by trickerer** [comment]
@cherbert well I didn't thumb up anything, but it's unimportant.

Why it is closed? Well because it got implemented, don't you see? 54c6a5e

**Comment by cherbert** [comment]
Oh god, so sorry. And thank you so much!
