### ISSUE TITLE
Can NPCBOT be set to hire by profession without any quantity restrictions[TC] [AC] [Bug/Crash] [Group/Spell/Core] ISSUE_TITLE

### ISSUE THREAD

**Issue by songjunst** [trickerer/Trinity-Bots#600]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Can NPCBOT be set to hire by profession without any quantity restrictions,

Adding BPCBOT to the database is a laborious task.

### Expected behaviour

Can NPCBOT be set to hire by profession without any quantity restrictions,

Adding BPCBOT to the database is a laborious task.

### Steps to reproduce the problem

Can NPCBOT be set to hire by profession without any quantity restrictions,

Adding BPCBOT to the database is a laborious task.

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

worldserver

### Operating system

win10

**Comment by trickerer** [comment]
Sorry, but I don't understand a thing you're saying. Could you please put it more wordy so your message is understood based on context?

**Comment by trickerer** [comment]
A month without answer. Closing.
