### ISSUE TITLE
[TC] [AC] [Question/Feature] [Group] Suggestions for optimizing NPCBOTS members when entering a 5-person dungeon in RAID

### ISSUE THREAD

**Issue by moncat2005** [trickerer/Trinity-Bots#602]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

When the player enters a 5-person dungeon in RAID team, the NPCBOTS members entering appear to be random.

Usually, the ideal goal for entering a 5-person dungeon member is the 5-person group where the player is located.

If the group members of the player are insufficient, then consider whether to randomly add members from the RAID team.

Please take some time to consider whether this mode can be optimized .

Thank you!

### TrinityCore or AzerothCore

Both

### Core rev. hash/commit

AzerothCore rev. 4699f0429a86 2023-08-13 19:17:15 +0700 (npcbots_3.3.5 branch) (Unix, RelWithDebInfo, Static)

### Operating system

Ubuntu 18.04

**Comment by hkbbdx** [comment]
very good  me need too
