### ISSUE TITLE
[TC] [Bug] [Core] Cmake build failed.

### ISSUE THREAD

**Issue by MokaCube** [trickerer/Trinity-Bots#613]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

I tried to build but got an error.

I built using the most recent commit (1bea4aa) from the 3.3.5 branch of the TrinityCore project and confirmed that it builds fine without the NPCBot patch.

The build crashed with the following message.
```bash
....
[ 75%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/World/chat_log.cpp.o
[ 75%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/World/duel_reset.cpp.o
[ 75%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/World/go_scripts.cpp.o
[ 75%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/World/item_scripts.cpp.o
[ 75%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/World/npc_guard.cpp.o
[ 76%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/World/npc_innkeeper.cpp.o
[ 76%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/World/npc_professions.cpp.o
[ 76%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/World/npcs_special.cpp.o
[ 76%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/World/world_script_loader.cpp.o
[ 76%] Linking CXX static library libscripts.a
[ 76%] Built target scripts
make: *** [Makefile:136: all] Error 2
```

Thank you.

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

commit 71d0a5307db0f3de65fb8fdf56e71b9f5dbab088

### Operating system

Ubuntu 22.04

**Comment by trickerer** [comment]
Please upload your full build log so I can see what errors you get.

I noticed MSVC CI build failing because of C++20 warnings being interpreted as errors but not GCC one, still could be relevant.

**Comment by MokaCube** [comment]
Hello,

Here is the build log.

[build.log](https://github.com/trickerer/Trinity-Bots/files/12414232/build.log)

Thank you.
