### ISSUE TITLE
[AC] [Crash] a crash in GenerateBattlegroundBots

### ISSUE THREAD

**Issue by Blandyoung** [trickerer/Trinity-Bots#614]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

The crash occurred the moment of leaving the battlefield after the end of the battle

but there are more than ten players playing together here

perhaps other issues triggered the crash

the first breakpoint at botdatamgr.cpp

I guess that problem may be.

1.Division by Zero: If either `needed_bots_count_a` or `needed_bots_count_h` is zero, it will lead to a division by zero error.

2. Type Conversion Error: If `MINUTE` is a large value and `needed_bots_count_a` and `needed_bots_count_h` are relatively small, it might result in a very large value after type conversion, potentially overflowing the `uint32` type.

3.Issues with `needed_bots_count_a` and `needed_bots_count_h` Values: The values of these variables might not be properly initialized or calculated, resulting in incorrect computation.

But my abilities cannot be repaired

### Crashlog

https://gist.github.com/Blandyoung/edc5f24877fa27b48926d437e2b356b4

### Steps to reproduce the problem

I am not sure about the steps to reproduce, but it‘s appeared at the moment I left the battlefield

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore 2023-2-27

### Operating system

winserver2019

**Comment by trickerer** [comment]
Seems like case 1 to me.

I see you're using pretty old AC version. Although it shouldn't matter for this particular issue, it's impossible to determine what version of NPCBots patch is used. Most recent one has its botdatamgr.cpp line 1490 pointing to an assertion, but issue is a division by zero and I want to be sure I'm looking in the right place.
Please state patch version.

**Comment by Blandyoung** [comment]
Sorry, the core I used is relatively old because I made a lot of personalized adjustments to the source code.

The npcbot code that I manually merged around August 7, 2023
