### ISSUE TITLE
[TC] [Crash] [Core] Crash when queuing for BGs

### ISSUE THREAD

**Issue by TQPS** [trickerer/Trinity-Bots#615]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

World server crashes when you queue for a BG.
* For context, I am queuing solo

### Expected behaviour

Previously, queue works as intended and match populates with random bots.

### Crashlog

https://gist.github.com/TQPS/73bafa185b36d86eb37173dcdf04fd7d

### Steps to reproduce the problem

1) Queue for a BG (AB or WGS)
2) World Server crash message appears in few moments on server
3) This line is added to the DBerrors.log file:
```
[1064] You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '%u' at line 1
Error while parsing SQL. Core fix required.
```

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

TrinityCore rev. 3d1c10f24203 2023-08-23 20:05:26 +1000 (npcbots_3.3.5 branch) (Win64, RelWithDebInfo, Static)

### Operating system

Win10

**Comment by trickerer** [comment]
You're likely using an executable stripped on debug symbols because crashlog doesn't contain any info.
Make a proper crashlog.

**Comment by TQPS** [comment]
Gist updated with full log.

Server.log last lines before crash on startup now is:
```
Starting NpcBot system...
>> Bot spellInfo overrides generated for 53 spells
>> Bot spell proc overrides generated for 1 spells
>> Bot appearance data loaded
>> Bot race data loaded
>> Bots transmog data is not loaded. Table `characters_npcbot_transmog` is empty!
>> Loaded 1 bot data entries
```

**Comment by trickerer** [comment]
Looks like I forgot to adjust string formatting in DB queries.

Try after https://github.com/trickerer/TrinityCore-3.3.5-with-NPCBots/commit/a7abceed8964465157f5bc809df740d7cd615146

**Comment by TQPS** [comment]
Thank you! This fix has resolved the issue. No crash. No dberrors and BG's are queuable again.

Much appreciate the quick turnaround.

You can close this as completed.
