### ISSUE TITLE
[AC] [Bug] Autobalance doesn't count bots

### ISSUE THREAD

**Issue by Wishmaster117** [trickerer/Trinity-Bots#618]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

When i go to raid with the bots Autobalance doesn't count bots so the raid is scalled to 1 instead off 5.

### Expected behaviour

N/A

### Crashlog

N/A

### Steps to reproduce the problem

Make a group of 4 bots
Enter raid

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. da30653363b8+ 2023-08-23 11:59:02 +0700 (npcbots_3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

### Operating system

Windows 10

**Comment by trickerer** [comment]
https://github.com/trickerer/mod-autobalance/commit/b995e3bdee7751b66cbcbf503b6b66e66e7d615c
