### ISSUE TITLE
[TC&AC] [Question/Feature] [Group/Spell/Core] Gender change command?

### ISSUE THREAD

**Issue by leopku** [trickerer/Trinity-Bots#619]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

First of all, big thanks for this awesome project.

As so many players wants female bot but there were too many male bots like Elf.

Hope there are a command to change gender of a bot.  Specially from male to female. :）

Thanks again.

### TrinityCore or AzerothCore

Both

### Core rev. hash/commit

da30653363b8103fde6b9d643e280d61b520ecaf

### Operating system

Ubuntu 22.04 + Docker

**Comment by trickerer** [comment]
Changing bot's gender is as straightforward as it seems.
Need to find a model matching opposite gender by voice type (if possible), 3 different voice types per gender per race.
Need to confirm if current appearance details are valid for new gender, if not - randomize within new bounds.
Such changes will only take effect after server restart.
Also, it's possible that visual changes will only be available after client cache renewal, not 100% on that.

**Comment by trickerer** [comment]
I think I'm not doing this. Anyone in need of more female bots will have to go with geneating new bots approach as per #668.

**Comment by leopku** [comment]
@trickerer got it. Thanks.
