### ISSUE TITLE
[TC] Compilewarning @Battaleground file

### ISSUE THREAD

**Issue by Krutok** [trickerer/Trinity-Bots#620]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

There is currently a compile error in the Battleground and BattlegroundAV file.
These are not compatible with the latest TrinityCore version.
Example:

![Screenshot 2023-09-01 101530](https://github.com/trickerer/Trinity-Bots/assets/47283866/9bc3afd4-0a5a-4480-9e8f-a97474a26327)

OriginalCode from TC: https://github.com/TrinityCore/TrinityCore/blob/74bfc3862197c0b4f1f4d91215b05ab514a81696/src/server/game/Battlegrounds/Zones/BattlegroundAB.cpp#L467

NPCbotFork: https://github.com/trickerer/TrinityCore-3.3.5-with-NPCBots/blob/a7abceed8964465157f5bc809df740d7cd615146/src/server/game/Battlegrounds/Zones/BattlegroundAB.cpp#L605

Either an error crept in or not yet synchronized with the current TC repo

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

TrinityCore rev. c3d6e61e4419+ 2023-09-01 09:37:30 +0200 (npcbots_3.3.5 branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon)

### Operating system

Debian 11

**Comment by trickerer** [comment]
https://github.com/trickerer/Trinity-Bots/commit/cd415a1302ee9b9f6e9406b63a8f4ad8fb3c0872
https://github.com/trickerer/TrinityCore-3.3.5-with-NPCBots/commit/6825a29f2e
