### ISSUE TITLE
[TC] [Bug] [Core] It crash and display 1064 error when NpcBot.WanderingBots.Continents.Count != 0

### ISSUE THREAD

**Issue by renlong567** [trickerer/Trinity-Bots#621]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

if set NpcBot.WanderingBots.Continents.Count = 0,it's OK and anything is fine.
But when I set NpcBot.WanderingBots.Continents.Count = xxx,xxx means anything greater than 0,it always crash and display "[1064] You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '%u' at line 1
Error while parsing SQL. Core fix required."

### Crashlog

https://gist.github.com/renlong567/897bb3bcdfac4af803fad148bf37cd56

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

TrinityCore rev. 79e2f77d4403+ 2023-09-01 12:15:17 +0200 (3.3.5 branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon)

### Operating system

Ubuntu 22.04

**Comment by trickerer** [comment]
> https://gist.github.com/renlong567/897bb3bcdfac4af803fad148bf37cd56

This is server startup log, not crashlog

I see you use a patch, post the patch version used. GDB backtrace may be unnecessary here.

Related:
https://github.com/trickerer/Trinity-Bots/issues/615
https://github.com/trickerer/TrinityCore-3.3.5-with-NPCBots/commit/a7abceed8964465157f5bc809df740d7cd615146

**Comment by infidelus** [comment]
Interesting.  I started getting this error too when I tried to upgrade a week ago or so.  I'm not sure when it started but I have a backup image of my server from the start of August where everything is fine, but anything I try to build now causes this crash.  I do have WanderingBots set to a non-zero number also though hadn't attributed it to that and am just running the older instance for now.

For info I'm only using TC and TrinityBots.

Working build: TrinityCore rev. f9033a5dbd55+ 2023-07-19 13:45:17 +0200 (3.3.5 branch) (Unix, RelWithDebInfo, Static).

**Comment by renlong567** [comment]
> > https://gist.github.com/renlong567/897bb3bcdfac4af803fad148bf37cd56
> 
> This is server startup log, not crashlog
> 
> I see you use a patch, post the patch version used. GDB backtrace may be unnecessary here.
> 
> Related: #615 [trickerer/TrinityCore-3.3.5-with-NPCBots@a7abcee](https://github.com/trickerer/TrinityCore-3.3.5-with-NPCBots/commit/a7abceed8964465157f5bc809df740d7cd615146)

Hi,first of all,thanks for your response.
Three days ago,I cloned this patch with this command "git clone --depth 1 https://github.com/trickerer/Trinity-Bots.git".so the patch version should be the lastest.
By the way,there are no problems with the old version from two months ago.

**Comment by trickerer** [comment]
I actually forgot to update the patch after #615 fix, pretty sure it's supposed to fix this one as well. Try it.
https://github.com/trickerer/Trinity-Bots/commit/4f5504dc573c2755c8b18a1c8b44e8530ed87e55

**Comment by infidelus** [comment]
That looks to have fixed it.  Built and running with this version, though I think one of the bots is now being bullied:

> Wandering bot Drothum id 72562 class 18 level 31 KILLED botpet Skeleton id 70580 class 1 level 31 on their way to DesolaceN19!
> Wandering bot Drothum id 72562 class 18 level 31 KILLED botpet Skeleton id 70580 class 1 level 31 on their way to DesolaceN19!
> Wandering bot Drothum id 72562 class 18 level 31 KILLED botpet Skeleton id 70580 class 1 level 31 on their way to DesolaceN19!
> Wandering bot Drothum id 72562 class 18 level 31 KILLED botpet Skeleton id 70580 class 1 level 31 on their way to DesolaceN19!
> Wandering bot Drothum id 72562 class 18 level 31 KILLED botpet Skeleton id 70580 class 1 level 31 on their way to DesolaceN19!
> Wandering bot Arak-arahm id 72567 class 20 level 16 WAS KILLED BY creature Mountaineer Flint id 1279 class 1 level 30 on their way to Algaz Station!
> Wandering bot Drothum id 72562 class 18 level 31 KILLED botpet Skeleton id 70580 class 1 level 31 on their way to DesolaceN19!
> Wandering bot Drothum id 72562 class 18 level 31 KILLED botpet Skeleton id 70580 class 1 level 31 on their way to DesolaceN19!
> Wandering bot Drothum id 72562 class 18 level 31 KILLED botpet Skeleton id 70580 class 1 level 31 on their way to DesolaceN5!
> Wandering bot Drothum id 72562 class 18 level 31 KILLED botpet Skeleton id 70580 class 1 level 31 on their way to DesolaceN5!
> Wandering bot Drothum id 72562 class 18 level 31 KILLED botpet Skeleton id 70580 class 1 level 31 on their way to DesolaceN4!
:smiley:

**Comment by trickerer** [comment]
Nah, this happens all the time - bots don't have any conception of mercifulness or cruelty, that's just how they roll.
