### ISSUE TITLE
[AC] [Bug/Crash] [Group] Can't enter instance after worldserver crash

### ISSUE THREAD

**Issue by Conan1996-2** [trickerer/Trinity-Bots#624]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Found bug. When worldserver crashes and you are in a group and in a dungeon, you are unable to join a dungeon once worldserver is back up. You have to leave the group, then recreate the group.

In worldserver, it says: this when you fail to enter a dungeon:
"Wrong dungeon type 0 for dungeon 0"

### Expected behaviour

You should be able to que for a dungeon and enter.

### Steps to reproduce the problem

1) Have NPCbot group, in a random dungeon.
2) worldserver crashes after a little while in dungeon (different issue - likely to many spawned wandering bots for 8gb - 500 bots)
3) startup worldserver
4) log in and see you still have a group
5) try to queue for a random dungeon (The Dungeon Finder eye is not on the minimap to verify I'm not still in dungeon)

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. 092c2b9957c5+ 2023-08-23 17:05:10 +0000 (master branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon) ready...

### Operating system

Ubuntu 22.04.3 LTS

**Comment by trickerer** [comment]
The crash is irrelevant, you always have to re-assemble bot group in order to queue in another LFG dungeon - a different issue

**Comment by Conan1996-2** [comment]
So, you are correct. In order for it to work after a crash, you would have to LEAVE the group once you log in (You log in with a complete group), and then recreate the group.
