### ISSUE TITLE
[TC] [Bug] [Core/MMaps] "Could not load MMAP"

### ISSUE THREAD

**Issue by TS-BAH** [trickerer/Trinity-Bots#626]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

"I have created 3,000 robots in the tables 'creature_template_npcbot_appearance,' 'creature_template_npcbot_extras,' and 'creature_template.' I have also generated equipment using '4_world_generate_bot_equips.sql.' In the configuration, I have enabled 2,000 roaming robots and also enabled BG robots. Now, I occasionally encounter the following error, and I'm not sure if I missed any steps."

### Expected behaviour

Could not load MMAP name:诺森德, id:571, x:32, y:32 (mmap rep.: x:32, y:32)
Could not load MMAP name:诺森德, id:571, x:31, y:32 (mmap rep.: x:31, y:32)
Could not load MMAP name:诺森德, id:571, x:31, y:31 (mmap rep.: x:31, y:31)
Could not load MMAP name:诺森德, id:571, x:32, y:31 (mmap rep.: x:32, y:31)
Could not load MMAP name:诺森德, id:571, x:32, y:32 (mmap rep.: x:32, y:32)
Could not load MMAP name:诺森德, id:571, x:31, y:32 (mmap rep.: x:31, y:32)
Could not load MMAP name:诺森德, id:571, x:32, y:31 (mmap rep.: x:32, y:31)
Could not load MMAP name:诺森德, id:571, x:31, y:31 (mmap rep.: x:31, y:31)
Could not load MMAP name:东部王国, id:0, x:13, y:28 (mmap rep.: x:13, y:28)
Could not load MMAP name:东部王国, id:0, x:18, y:36 (mmap rep.: x:18, y:36)
Could not load MMAP name:诺森德, id:571, x:32, y:32 (mmap rep.: x:32, y:32)
Could not load MMAP name:诺森德, id:571, x:31, y:32 (mmap rep.: x:31, y:32)
Could not load MMAP name:外域, id:530, x:42, y:25 (mmap rep.: x:42, y:25)
Could not load MMAP name:诺森德, id:571, x:31, y:31 (mmap rep.: x:31, y:31)
Could not load MMAP name:诺森德, id:571, x:32, y:31 (mmap rep.: x:32, y:31)
Could not load MMAP name:诺森德, id:571, x:32, y:32 (mmap rep.: x:32, y:32)
Could not load MMAP name:诺森德, id:571, x:31, y:32 (mmap rep.: x:31, y:32)
Could not load MMAP name:东部王国, id:0, x:18, y:36 (mmap rep.: x:18, y:36)
Could not load MMAP name:外域, id:530, x:42, y:25 (mmap rep.: x:42, y:25)
Could not load MMAP name:诺森德, id:571, x:31, y:31 (mmap rep.: x:31, y:31)
Could not load MMAP name:诺森德, id:571, x:32, y:32 (mmap rep.: x:32, y:32)
Could not load MMAP name:诺森德, id:571, x:31, y:32 (mmap rep.: x:31, y:32)
Could not load MMAP name:东部王国, id:0, x:18, y:36 (mmap rep.: x:18, y:36)
Could not load MMAP name:诺森德, id:571, x:32, y:31 (mmap rep.: x:32, y:31)
Could not load MMAP name:诺森德, id:571, x:32, y:32 (mmap rep.: x:32, y:32)
Could not load MMAP name:诺森德, id:571, x:31, y:32 (mmap rep.: x:31, y:32)
MoveSplineInitArgs::Validate: expression 'velocity >= 0.001f' failed for MapID: 1 Map name: '卡利姆多' X: -6813.83 Y: 744.165 Z: 48.3409 O: 2.85889
GUID Full: 0xf130003b5000da93 Type: Creature Entry: 15184  Low: 55955 Entry 15184
Name: Cenarion Hold Infantry
IsAIEnabled: true DeathState: 0 UnitMovementFlags: 0 ExtraUnitMovementFlags: 0 Class: 1
MoveSpline
spline Id: 8666213
flags:  Done CanSwim Final_Angle
facing  angle: 2.85889
time passed: 1
total  time: 1
spline point Id: 1
path  point  Id: 1
mode: Linear
points count: 4
point 0 : (-6812.87, 743.886, 48.3409)
point 1 : (-6813.83, 744.165, 48.3409)
point 2 : (-6813.83, 744.165, 48.3409)
point 3 : (-6813.83, 744.165, 48.3409)
GetCharmedGUID(): GUID Full: 0x0000000000000000 Type: None Low: 0
GetCharmerGUID(): GUID Full: 0x0000000000000000 Type: None Low: 0
No vehicle kit
GetGameClientMovingMe(): NULL
m_Controlled size: 0
AIName: SmartAI ScriptName:  WaypointPath: 428960 SpawnId: 42896

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

TrinityCore rev. 56c9c993006b 2023-08-30 00:00:03 +0800 (npcbots_3.3.5 branch) (Win64, Release, Static) (worldserver-daemon)

**Comment by trickerer** [comment]
You didn't miss any steps.

Looks like bots walk into grids for which mmaps weren't generated. Second error is completely irrelevant and happens at random with many creatures.

Did you generate mmaps yourself or get them from elsewhere?

**Comment by TS-BAH** [comment]
"Additionally, the entry IDs for the custom NPC bots I created start from 170001. Does this have any relevance?"

**Comment by trickerer** [comment]
> "Additionally, the entry IDs for the custom NPC bots I created start from 170001. Does this have any relevance?"

Nope

**Comment by trickerer** [comment]
Couldn't reproduce.
If it's doesn't brak anything then just ignore those errors, otherwise you may reopen this issue
