### ISSUE TITLE
[AC] [Bug] [Core] AV logic issue causes bots to get stuck in an area

### ISSUE THREAD

**Issue by EllieSca** [trickerer/Trinity-Bots#627]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

![image](https://github.com/trickerer/Trinity-Bots/assets/92201409/b053304d-8eea-4464-a940-4ee0cb0ed839)
If AV ends up in a state where horde team is respawning inside alliance base without having captured icewing/stoneheart bunkers bots get stuck. Eventually got resolved when alliance attempted capture of frostwolf towers but bots ended up being stuck for a solid 10 minutes before that happened.

### Expected behaviour

Bots should either attempt boss if there's enough of them in the area or run back to assault icewing/stoneheart bunkers.

### Steps to reproduce the problem

1. Be on a losing AV side as horde, no objectives secured
2. Backdoor alliance base while bots clashing in front of horde base
3. Successfully capture graveyard
4. Capture of towers causes alliance team to run all the way back
5. Horde bots are now fighting closer to the middle field and respawning inside alliance base as all other graveyards are contested/alliance controlled
6. Successfully burn towers and watch horde bots getting stuck

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. 280822cb8350+ 2023-08-29 00:24:41 +0200 (master branch) (Unix, RelWithDebInfo, Static)

### Operating system

Debian

**Comment by Day36512** [comment]
Same thing happens if a tower gets skipped and your group is at the final GY.

**Comment by trickerer** [comment]
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/f1c9391acc0fe79373fbb129f2c50ab2f357283a
