### ISSUE TITLE
server crash after patch bot to v4.9.21a

### ISSUE THREAD

**Issue by Ryu1254** [trickerer/Trinity-Bots#63]
Hello

after patching to npcbot 4.9.21a with trinitycore version https://github.com/TrinityCore/TrinityCore/commit/28d470c50ef6ea72d7609375856e5da005df19ae

I try Occulus H. and i got crash almost every pull..

Here the log file. hope this can help.
[server crash in occulus H.zip](https://github.com/trickerer/Trinity-Bots/files/5825086/server.crash.in.occulus.H.zip)

**Comment by trickerer** [comment]
This is not a 3.3.5 branch commit. Please provide valid info next time
