### ISSUE TITLE
[AC] [Bug] Errors since latest update

### ISSUE THREAD

**Issue by Wishmaster117** [trickerer/Trinity-Bots#631]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Hi,
Since latest update i have this errors when starting world server:
SmartScript::ProcessAction: SMART_ACTION_TALK: EntryOrGuid 28994 SourceType 0 EventType 10 TargetType 7 using non-existent Text id 0 for talker 29494, ignored.
SmartScript::ProcessAction: SMART_ACTION_TALK: EntryOrGuid 29523 SourceType 0 EventType 10 TargetType 7 using non-existent Text id 0 for talker 35500, ignored.
SmartScript::ProcessAction: SMART_ACTION_TALK: EntryOrGuid 28989 SourceType 0 EventType 10 TargetType 7 using non-existent Text id 0 for talker 29493, ignored.

SmartScript::ProcessAction: SMART_ACTION_TALK: EntryOrGuid 28721 SourceType 0 EventType 10 TargetType 7 using non-existent Text id 0 for talker 28701, ignored.
SmartScript::ProcessAction: SMART_ACTION_TALK: EntryOrGuid 28725 SourceType 0 EventType 10 TargetType 7 using non-existent Text id 0 for talker 28703, ignored.
SmartScript::ProcessAction: SMART_ACTION_TALK: EntryOrGuid 28726 SourceType 0 EventType 10 TargetType 7 using non-existent Text id 0 for talker 28699, ignored.

### Expected behaviour

Correct this errors

### Steps to reproduce the problem

Start world server

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

AzerothCore rev. aef631e354b2+ 2023-09-16 07:29:09 +0700 (npcbots_3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

### Operating system

Win 10

**Comment by trickerer** [comment]
Hi.

NPCBots don't use SmartAI for anything, nor do I see any bot ids in the messages (70001+). What makes you think these errors are relevant to bots?

**Comment by Wishmaster117** [comment]
Because befor pulling the latest update i don't have any errors, and after i have this one.
You think that's a module conflict between the last update os npcbot?

**Comment by Wishmaster117** [comment]
Nevermind, you're right, this is not relevant to bots, but i don't understand why i have it since the last bot updates anyway, if someone have the same problem, il solved it with this update:

UPDATE `smart_scripts` SET `event_param5` = 1, `action_param3` = 1 WHERE `source_type` = 0 AND `entryorguid` IN (28994,29523,28989,28721,28725,28726);

**Comment by Wishmaster117** [comment]
I close the issue, sorry.
