### ISSUE TITLE
[TC] [AC] [Bug/Crash] [Group/Spell/Core] Bots Don't Enter Raids

### ISSUE THREAD

**Issue by craigdbarber** [trickerer/Trinity-Bots#633]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Bots do not enter raid instance after character enters. I've tried multiple times attempting to enter Naxx10, with none of my owned and in-raid bots entering the instance.

I've attempted to use `.npcbot recall teleport` which doesn't work. 
I've also attempted to use `.npcbot move <botId>` which also doesn't work.

The bots do enter 5-man dungeons, just not raids.

### Expected behaviour

For the bots to teleport into the raid instance upon my character entering.

### Steps to reproduce the problem

1) Create a 10-man raid full of 9 owned npcbot spawns.
2) Enter Naxx10
3) Notice no bots enter the instance.

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

TrinityCore rev. afc050980cd6+ 2023-09-19 22:08:56 -0400

### Operating system

Ubuntu 22.04

**Comment by trickerer** [comment]
This is controlled by `NpcBot.Enable.Raid` config param. Check your worldserver.conf

**Comment by craigdbarber** [comment]
> This is controlled by `NpcBot.Enable.Raid` config param. Check your worldserver.conf

That was the issue. Thanks very much :)
