### ISSUE TITLE
[TC] [AC] [Question/Feature] [Group/Spell/Core] Split Group Fights

### ISSUE THREAD

**Issue by craigdbarber** [trickerer/Trinity-Bots#634]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Hello,

I'm curious to hear what others have figured out re: managing bots positioning on split group fights, eg: Thaddius, 4 horsemen, etc. Going with the Thaddius example, I haven't figured out a way to get my bots to split into two groups for Fuegen and Heigan. I can use the TargetIconMask to get my OT and Melee to focus on Heigan for example, but I can't figure out how to get them to position him next to his tesla coil.

Have others figured out a way to configure physical positioning of bots like this on fights? 

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

TrinityCore rev. afc050980cd6+ 2023-09-19 22:08:56 -0400

### Operating system

Ubuntu 22.04

**Comment by Day36512** [comment]
Ah sorry forgot you also need to use the addon to extend macros:
https://felbite.com/addon/3407-ncbiggermacros/
