### ISSUE TITLE
[TC] [Question/Feature] how to make wander bots actively attack players in sight?

### ISSUE THREAD

**Issue by SouthMemory** [trickerer/Trinity-Bots#637]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Hello, I spawned many wander bots, it's good。

But I want them to actively attack players in attack range, I just don't know how.

can you please explain a bit or tell me where I can set this

### TrinityCore or AzerothCore

TrinityCore

**Comment by trickerer** [comment]
Wandering bots attack units of opposite faction automatically. Wandering bots of extra classes are hostile to everyone.

Bots you manually spawn aren't wandering bots, they are just normal npcbots for players to hire.
To make normal npcbots hostile to Alliance / Horde / Everyone you have to set up their faction using `.npcbot set faction` command. Invoke it for additional help or check Readme. But only bots hostile to everyone will actively attack, so you'll need `.npcbot set faction m`.

**Comment by SouthMemory** [comment]
about the wanderer, The faction is already 14, the bot is attakable to me, but it just do not actively attack me
![图片](https://github.com/trickerer/Trinity-Bots/assets/28387896/49eecea2-3e7f-495d-8c17-c45946e5584d)

**Comment by trickerer** [comment]
Okay, maybe they don't attack players for some reason. Do they go around killing creeps?

**Comment by SouthMemory** [comment]
yes, the kills mob and gurads, but the just ignore me

**Comment by SouthMemory** [comment]
https://youtu.be/dryMO6QtNzk

the video is here, you can check it

thank you very much!

**Comment by trickerer** [comment]
Well it's hardcoded then and I just didn't remember they're set to not attack players. Maybe changing `NpcBot.PvP` config param to 1 makes them attack players too, if not - then it's impossible to configure currently.

**Comment by SouthMemory** [comment]
NpcBot.PvP is already set to 1, and player is pvp enabled.
you can give a try
@trickerer

**Comment by SouthMemory** [comment]
@trickerer 
I solved this problem by removing function MoveInLineOfSight and AttackStart from bot_ai.h and bot_ai.cpp.
These two functions are implemnted with empty body intentionally.
Now the wandering bots attacks players actively.

**Comment by StraysFromPath** [comment]
> @trickerer I solved this problem by removing function MoveInLineOfSight and AttackStart from bot_ai.h and bot_ai.cpp. These two functions are implemnted with empty body intentionally. Now the wandering bots attacks players actively.

To clarify did you mark this as closed/completed because you found a fix we apply ourselves or because you pushed the fix to the module and it is fixed for everyone?

**Comment by alexyang-sea** [comment]
> I solved this problem by removing function MoveInLineOfSight and AttackStart from bot_ai.h and bot_ai.cpp.
> These two functions are implemnted with empty body intentionally.
> Now the wandering bots attacks players actively.

Can NPCBOTS roam the wilds now too?
