### ISSUE TITLE
[TC] [AC] [Question] [Core] where does CreatureTemplateContainer _botsWanderCreatureTemplates get filled?

### ISSUE THREAD

**Issue by SouthMemory** [trickerer/Trinity-Bots#640]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

AzerothCore, botdatamgr.cpp, line 51:
`CreatureTemplateContainer _botsWanderCreatureTemplates;`

I searched everywhere, but did not find where this variable get itself filled, akward,  get myself very confused

I only find where it's used

can you please point this out for me? very grateful! @trickerer 

### TrinityCore or AzerothCore

AzerothCore

**Comment by trickerer** [comment]
It's in `bool WanderingBotsGenerator::GenerateWanderingBotToSpawn(...)` of course.
```
CreatureTemplate& bot_template = _botsWanderCreatureTemplates[next_bot_id];
```
makes an insertion, that's how `std::unordered_map`'s `operator[]` works - if key doesn't exist it gets created and value default-initialized (that's why default constructor is required for the container).

**Comment by SouthMemory** [comment]
I managed to spawn npc bots based on creatures, it's quite funy
[the video is here](https://www.youtube.com/watch?v=ctp9R8Mhpus)
