### ISSUE TITLE
[AC] [Question] [Spell] As a healing profession, paladins are always very close to tanks。

### ISSUE THREAD

**Issue by lmzml** [trickerer/Trinity-Bots#641]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

As a healing profession, paladins are always very close to tanks. When a priest acts as a healer, it is a normal range. Excuse me, is this a bug? How to solve the problem of paladins always being close to tanks as a healing profession?

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. unknown 1970-01-01 00:00:00 +0000 (Archived branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon) ready...

### Operating system

Ubuntu 22.04

**Comment by trickerer** [comment]
Each class has its own normal ranged attack distance. For paladins this is range of Judgement spell, which is pretty short. If it bothers you and you want your paladins to stay farther behind (and not use Judgement) force your bots' ranged attack distance through their gossip menu or using `.npcb dist a <value>` command.

**Comment by lmzml** [comment]
I tried to adjust the attack range to maximum, but it didn't seem to work, and the healing paladin was still closely following the tank.

**Comment by trickerer** [comment]
First of all, bots don't follow one another. While having attack target they only check their attack range, melee bots follow it in melee, ranged bots use either fixed attack distance, long attack distance or short attack distance. The thing is, short and long attack distance may differ between classes, but fixed one is set for all ranged bots.
Are you sure your paladin is ranged but still uses different attack range than other ranged bots and the distance you set through command?

**Comment by lmzml** [comment]
![微信截图_20230930203205](https://github.com/trickerer/Trinity-Bots/assets/97717237/273b07d3-fe09-4eca-95f9-1fda25b6c5fa)
![微信截图_20230930203232](https://github.com/trickerer/Trinity-Bots/assets/97717237/19e5dbcd-f031-46b0-87e0-99485edb9c5f)
![微信截图_20230930203317](https://github.com/trickerer/Trinity-Bots/assets/97717237/eabcf616-82be-43bb-9e7c-086c78626746)
![微信截图_20230930203359](https://github.com/trickerer/Trinity-Bots/assets/97717237/d9ae2fd2-efa0-4c22-a3da-d852351dcdfa)

**Comment by trickerer** [comment]
Sorry, I can't read chinese. All I can figure out is that you use 'long range' attack distance and not exact one like I told you.
Again, you need to set somewhat large exact attack distance and make sure your paladin bot has Ranged role assigned.

**Comment by lmzml** [comment]
Sorry, I understand what you mean. It is necessary to set an accurate remote attack distance, and cannot use 'short' or 'long'. Thank you very much for your answer. It has taken up your time.
