### ISSUE TITLE
[AC] [Crash] [Core] When BG Config enabled, and player queue the server crashed

### ISSUE THREAD

**Issue by jakatangkir** [trickerer/Trinity-Bots#644]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Worldserver get crashed when the config of npcbot battleground being enabled.
Current config:
`NpcBot.WanderingBots.BG.Enable = 1

NpcBot.WanderingBots.BG.CapLevel = 0`
The error were:
`Exception code: C0000005 ACCESS_VIOLATION
Fault address:  00007FF70A18087C 01:000000000006F87C D:\RepackNew\compli\worldserver.exe`

Please notice too, i tried to update within the lastest patch right now and the version changed to:
`AzerothCore rev. unknown 1970-01-01 00:00:00 +0000 (Archived branch) (Win64, Release, Static) (worldserver-daemon)`

### Expected behaviour

It should not be crashed and the battleground we're queued.

### Crashlog

https://gist.github.com/jakatangkir/72bcd8d4a41e0f51227a416210f249e9

### Steps to reproduce the problem

1) Join in with level 70
2) queue for BG
3) wait for a minute / second
4) server crashed

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. 4699f0429a86+ 2023-08-13 19:17:15 +0700 (npcbots_3.3.5 branch) (Win64, Release, Static)

### Operating system

Win10 and Win Server 2012

**Comment by trickerer** [comment]
Release crashlog misses debug symbols therefore is useless. Post a debug crashlog please. And a link to repository and commit you've updated to.

**Comment by jakatangkir** [comment]
Hello here is the debug compiled crash, did i make this right?
https://gist.github.com/jakatangkir/5c4e9f66a6b5140c1b94b6ced482e0f4
as for the update, i fresh installed it via https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots about hours before this issue posted, because i thought it will perform fix if i do fresh installation.

On installing, i do download the zip from https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots
Then doing the CMake (x64), then compile it via VS 2022 (Debug)
Thank you

**Comment by trickerer** [comment]
This crash is caused by Autobalance module. There is a bug there which causes a crash in BG maps due to wrong type cast.

Use Autobalance with NPCBots support: https://github.com/trickerer/mod-autobalance. Make sure you use `.npcbots_3.3.5` branch.

**Comment by jakatangkir** [comment]
ah i see, its support the lastest update on each dungeon and raid.
thank you for the fix and info, my bad for didnot knowing there is a standalone mod-autobalance for bots pack.
