### ISSUE TITLE
[AC] [Question] [Core] how to change the movement type of wandering bots to RANDOM_MOTION_TYPE?

### ISSUE THREAD

**Issue by SouthMemory** [trickerer/Trinity-Bots#645]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Hello
I managed to replace mobs with wandering bots, they now work well.
They would get on horses and move every where and fight each other, which is quite interesting.

[video is here](https://www.youtube.com/watch?v=ctp9R8Mhpus)

The problem is that I want to change the movement type of wandering bots to RANDOM_MOTION_TYPE, making the bot wandering around it's spawn location
I tried a few places to change ,But it would crash the service, error is like:
`
Exception code: C0000005 ACCESS_VIOLATION
Fault address:  00007FF7FBC15C25 01:0000000000EA4C25 C:\acore_build_creaturebots\bin\RelWithDebInfo\worldserver.exe

Call stack:
Address   Frame     Function      SourceFile
00007FF7FBC15C25  000000552EAFF370  RandomMovementGenerator<Creature>::_setRandomLocation+4A5  C:\AzerothCore-wotlk-with-CreatureBots\src\server\game\Movement\MovementGenerators\RandomMovementGenerator.cpp line 112
00007FF7FBC14DDD  000000552EAFF3A0  RandomMovementGenerator<Creature>::DoUpdate+8D  C:\AzerothCore-wotlk-with-CreatureBots\src\server\game\Movement\MovementGenerators\RandomMovementGenerator.cpp line 301
00007FF7FB7A2DC8  000000552EAFF4C0  MotionMaster::UpdateMotion+58  C:\AzerothCore-wotlk-with-CreatureBots\src\server\game\Movement\MotionMaster.cpp line 113
00007FF7FB4D5A77  000000552EAFF530  Unit::Update+537  C:\AzerothCore-wotlk-with-CreatureBots\src\server\game\Entities\Unit\Unit.cpp line 572
00007FF7FB7FC2D4  000000552EAFF770  Player::Update+114  C:\AzerothCore-wotlk-with-CreatureBots\src\server\game\Entities\Player\PlayerUpdates.cpp line 84
00007FF7FB7513EA  000000552EAFF9F0  Map::Update+12A  C:\AzerothCore-wotlk-with-CreatureBots\src\server\game\Maps\Map.cpp line 766
00007FF7FBB46762  000000552EAFFA30  MapUpdateRequest::call+32  C:\AzerothCore-wotlk-with-CreatureBots\src\server\game\Maps\MapUpdater.cpp line 45
00007FF7FBB4625C  000000552EAFFA60  MapUpdater::WorkerThread+DC  C:\AzerothCore-wotlk-with-CreatureBots\src\server\game\Maps\MapUpdater.cpp line 158
00007FF7FBB45C5F  000000552EAFFA90  std::thread::_Invoke<std::tuple<void (__cdecl MapUpdater::*)(void),MapUpdater *>,0,1>+F  C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include\thread line 56
00007FFB484B1BB2  000000552EAFFAC0  _configthreadlocale+92
00007FFB49E47344  000000552EAFFAF0  BaseThreadInitThunk+14
00007FFB4AE026B1  000000552EAFFB70  RtlUserThreadStart+21
`

I figured that this is a problem beyond my capability.
so can you please give some advice?

### TrinityCore or AzerothCore

AzerothCore

**Comment by trickerer** [comment]
I have no idea what you changed so there is no way to know what the issue is.
Bots' movement decisions are made inside AI, MovementHandler is only used for execution.

P.S. Why the heck did you open a second issue for that?

**Comment by SouthMemory** [comment]
I closed the original issue, opened this one because I thought it was a new question

**Comment by SouthMemory** [comment]
> I have no idea what you changed so there is no way to know what the issue is. Bots' movement decisions are made inside AI, MovementHandler is only used for execution.
> 
> P.S. Why the heck did you open a second issue for that?

well,  the question is exactly the same as :

> "what would you do if you want to change the movement type of wandering bots to RANDOM_MOTION_TYPE?"



the bots used to replace mobs is the same as wandering bots.

**Comment by trickerer** [comment]
> well, the question is exactly the same as :
> > "what would you do if you want to change the movement type of wandering bots to RANDOM_MOTION_TYPE?"

> the bots used to replace mobs is the same as wandering bots.

I've already answered that. You have to change bots' movement inside AI. Check my last post in the original issue.

**Comment by SouthMemory** [comment]
It's just too complicated and diffcult form me

**Comment by SouthMemory** [comment]
Thank you so much! @trickerer
I followed your advice, did something under if (nextNode == _travel_node_cur), and it worked.
So grateful!
