### ISSUE TITLE
[AC] [Crash] [Core] Grid Related Crashes since Update

### ISSUE THREAD

**Issue by Day3651** [trickerer/Trinity-Bots#646]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

1. Server has map related crashes since update to Grids. Callstacks have been fairly consistent. The following attached log was from just letting the server run on its own for awhile.

2. The following errors have been occuring for player's npcbots while moving maps

**Active creature GUID Full: 0xf13001117300005b Type: Creature Entry: 70003  Low: 91 added to grid[24, 6] but spawn grid[15, 33] was not loaded.
Active creature GUID Full: 0xf13001117300005b Type: Creature Entry: 70003  Low: 91 removed from grid[24, 6] but spawn grid[15, 33] was not loaded.**

2 does not seem to be the direct cause of said crashes however. The crash logs below are without any player characters logging in.

[Crashes.zip](https://github.com/trickerer/Trinity-Bots/files/12794037/Crashes.zip)

### Expected behaviour

Server should not be crashing periodically.

### Crashlog

Please see attached

### Steps to reproduce the problem

Simply allow the server to run for a short period of time. Tested using 1k-4k bots.

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. cb973c78f9d1+ 2023-10-01 17:31:03 -0600 (npcbots_3.3.5 branch) 

### Operating system

Win 10

**Comment by trickerer** [comment]
Grid system was finally ported from TC, but code supporting bots isn't there yet, I have to see what's missing.

**Comment by Day3651** [comment]
Is there any progress on this issue? Issue persists for me on most recent update.

**Comment by Day36512** [comment]
> Was there any progress on this issue? Issue persists for me on most recent update. Just want to make sure this isn't a "me" issue.

There's been two commits attempting to fix the issue, though neither are added yet to trickerer's fork. However crashes of this kind still happen.

https://github.com/azerothcore/azerothcore-wotlk/commit/60e27511c530b0949fee361a89d3eb9d9f9125af
https://github.com/azerothcore/azerothcore-wotlk/pull/17569

I've made some modifications to WorldObject::GetSightRange and WorldObject::CanSeeOrDetect in Object.cpp by importing TC's methods and it seems promising so far, but the original AC versions have more checks. At least this way i'll know what exactly is the core issue.

Hopefully this gives people a hint at least.

**Comment by skelUA** [comment]
Crashes is still exist on last rev :(
