### ISSUE TITLE
[AC] [Bug] [Spell]   Robot accessory trigger spell has no cooldown time (CD), repeat trigger.

### ISSUE THREAD

**Issue by Liuccysdgg** [trickerer/Trinity-Bots#647]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Robot accessory trigger spell has no cooldown time (CD), repeat trigger.
Normal casting of Spell is normal, only trinkets trigger Spell

### Expected behaviour

The casting spells of the robot's accessories should be the same as those of the player, with a cooldown time

### Crashlog

Not

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

worldserver

### Operating system

Win2016

**Comment by trickerer** [comment]
- Missing hash / commit
- What is the trinket / spell in question?

**Comment by Liuccysdgg** [comment]
Hello, I just tested passive triggering effects such as accessories and weapons, which will result in repeated triggering without a cooldown time. The accessory I assembled has ID: 47464, and the spell ID triggered by the accessory is 67773. I have placed a demonstration motion picture below

![1](https://github.com/trickerer/Trinity-Bots/assets/27082607/bead8906-d74f-4e74-bbf0-4bef5cb19231)

**Comment by songjunst** [comment]
I also encounter this problem, as long as there is a trigger effect on a ring or accessory, there will be a non CD trigger effect, causing the melee output data to be particularly large, such as accessories and rings in ICC.
