### ISSUE TITLE
[TC] [AC] [Question/Feature] [Group/Spell/Core] ISSUE_TITLE

### ISSUE THREAD

**Issue by alexpec1** [trickerer/Trinity-Bots#648]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Only GM access can summon NPCBots, is this how the system is set up? Why not allow regular accounts to hire NPCBots as well?

### TrinityCore or AzerothCore

AzerothCore

**Comment by trickerer** [comment]
Because spawning and hiring are two different things.
Spawning bots is a part of server setup and management - it may affect server stability and performance in the long run.
Hiring is a part of gameplay. Players can hire spawned bots through gossip menu or botgiver npc.
And this is how the system is set up (by default).

**Comment by alexpec1** [comment]
So how do normal players hire bots? You can't generate bots with normal access now, so you can't hire them, right?

**Comment by Day36512** [comment]
No. You hire them from the npc with an id of 70000, ie the hirebot.

**Comment by trickerer** [comment]
> So how do normal players hire bots? You can't generate bots with normal access now, so you can't hire them, right?

To spawn bots you'll need admin account. To hire a bot you just talk to them or to botgiver npc (if you spawn them first, npc id 70000)

**Comment by alexpec1** [comment]
So my understanding is that you have to have GM access to spawn a bot first, and then you can hire through the generated bot. Is that correct? So there is no way for a regular account to hire a bot?If I can't hire bots on a regular account, I won't be able to get through a lot of copies.。

**Comment by trickerer** [comment]
As I said before, spawning bots is a part of server management. Regular accounts shouldn't be able to manage the server.
To **hire** a bot you don't need any additional permissions, only to spawn them. In other words, you cannot populate world with bots without gm account, but once bots are spawned anyone can hire them.

**Comment by alexpec1** [comment]
Thank you for your patience, I understand.
