### ISSUE TITLE
[AC] [Bug] [Core] Incorrect bot name displayed

### ISSUE THREAD

**Issue by matgskinner** [trickerer/Trinity-Bots#649]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

When creating new bots, an incorrect name is displayed on name plate (name above character's head) and in party/raid HUD. However, correct name is displayed in `Social` menu's `Raid` tab (see screenshot). The name should be "Riven" with ID 70821, but showing "Vaelen" from ID 70453. 

Other observations: 
- The correct name shows up in database `acore_world.creature_template` table and `acore_world.creature_template_npcbot_appearance` table (see screenshot).
- The name displayed is of another pre-made bot with a different entry ID. The issue began at bot ID 70820. Custom bots with IDs between 70800-70819 display correctly. 
- When running bot commands, the correct name is displayed in the chat window (see screenshot). 
- The normal `<[Class]_Bot>` is missing from the roll-over info panel. 

![NPCbots name bug](https://github.com/trickerer/Trinity-Bots/assets/147221646/1fa2cdf1-95db-4eaa-a3fe-c24012c50846)
![NPCbots DB](https://github.com/trickerer/Trinity-Bots/assets/147221646/0073c588-bf37-44dc-ab83-ee33e6bf9651)

### Expected behaviour

Correct name is displayed on name plate and party/raid HUD. 

### Steps to reproduce the problem

1. Create a custom bot using `.npcb createnew ...` command.
2. Restart server
3. Spawn bot using `.npcb spawn [ID]` (note: only happing for bot IDs above 70820)
4. Bot is spawned with incorrect name (has name of another pre-made bot). 

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. unknown 1970-01-01 00:00:00 +0000 (Archived branch) (Win64, RelWithDebInfo, Static) (authserver)

### Operating system

Win10

**Comment by trickerer** [comment]
It's just a client cache intersection.
When client registers a creature it caches some of its attributes, including name / subname. In your case it's wandering bot's name for sure.

Quit the game and clear you client's cache folder. Server restart isn't required.

**Comment by matgskinner** [comment]
That fixed it. Thank you!
