### ISSUE TITLE
[AC] [Question] [Core] Needs help on debugging for core stuck but no exception thrown

### ISSUE THREAD

**Issue by SouthMemory** [trickerer/Trinity-Bots#650]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Hi, Needs some help again.
I encountered a  core stuck problem and spent many days, but still no clue. 

Description:
- I replaced some mobs with bots, set script to warrior_bot
- I log in the game, everything is normal, bots fighting each other
- Then after some time, the core would get stuck, no response at all, either from the client or the terminal
- Especially when my player enters afk mode, seems the core get stuck more often.
- No log, No Exception, No crashes
- ctrl+c in terminal does can not cancel the server

My code is here: [AzerothCore-wotlk-with-CreatureBots](https://github.com/SouthMemory/AzerothCore-wotlk-with-CreatureBots.git)

My problem is that I totally don't know what to do, because no info about what's happening at all.
Can you give some clue or guess about what could be the problem,  from your developing experience?

### TrinityCore or AzerothCore

AzerothCore

**Comment by trickerer** [comment]
Just build in Debug mode and attach to worldserver process once it's started to catch any errors thrown or hangs.

Usually when core get stuck completely it's either an infinite loop or a problem in exception report generation in which case core may also never fully crash. General reasons for infinte loop are a logic error inside iteration conditions or out-of-bound access.

Sometimes exception report generation on Windows takes a long time (like 10 minutes), but that's probably not your case.

**Comment by SouthMemory** [comment]
Thanks, I shall try it out!

**Comment by SouthMemory** [comment]
"attach to worldserver process once it's started to catch any errors thrown or hangs."
what does this mean?
Any tools shall be used here? 
Or just watch the terminal?

**Comment by trickerer** [comment]
Here is the manual:
- Windows (VS2022): https://learn.microsoft.com/en-us/visualstudio/debugger/attach-to-running-processes-with-the-visual-studio-debugger?view=vs-2022
- Linux (GDB): https://www.azerothcore.org/wiki/how-to-restart-and-debug (scroll down to 'manual way')

**Comment by SouthMemory** [comment]
thanks so much!

**Comment by SouthMemory** [comment]
I still don't know where the problem is,  something is wrong when map updates

**Comment by SouthMemory** [comment]
I tried to change many codes, but can not eliminate the "access violation"
Finally, I had to use try...catch... to prevent app from crash
