### ISSUE TITLE
[TC][Bug/Crash] Worldserver crashes when i load npc's.

### ISSUE THREAD

**Issue by pederbp** [trickerer/Trinity-Bots#651]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

It happend when i was about  to pull a boss in trial of the crusader. Now i cant load the worldserver with the npc's enabled/works fine when npc is disabled. Stops at ">> Loaded 23 bot data entries" (See crashlog link.)

### Crashlog

https://gist.github.com/pederbp/bd3c87ea701cb1b0c709c466510b66e9#file-504fcfb2fdd0-_worldserver-exe_-8-10_15-26-55-txt

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

Revision: TrinityCore rev. 504fcfb2fdd0+ 2022-09-23 09:42:26 -0500 (3.3.5 branch) (Win64, Release, Static)

### Operating system

Win 11

**Comment by trickerer** [comment]
- `504fcfb2fdd0` is not a known TC revision
- Release crashlog doesn't contain debug symbols therefore is useless, upload a Debug crashlog please
- In your crashlog path to the exe suggests you're using some kind of repack which somewhat lowers the chances I will be able to help here
