### ISSUE TITLE
[TC] [AC] [Bug/Crash] [Group/Spell/Core] Error on Console & Sometime Crash After BG

### ISSUE THREAD

**Issue by jakatangkir** [trickerer/Trinity-Bots#653]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Worldserver crashes everytime player finished doing BGs with NPC Bot (Wandering BG enabled)

In other hand, the worldserver console also informing this error:
`Active creature GUID Full .... Type Creature Entry: 70255 Low: 491 added to grid[28,41] but spawn grid[38,25] was not loaded`.
Just in case it also effect it?

And one thing, i use the lastest version of NPCBot pre-installed in Azeroth Core and the version of the Azeroth core is unknown.
Thank you

### Expected behaviour

I think it should not crash after players doing BG? I dunno maybe AC did not recognized the NPC Bot and resulting in Assertion Failed? See the crash log i include

### Crashlog

https://gist.github.com/jakatangkir/0689893d14212be46ce7a9fe7780d19c

### Steps to reproduce the problem

1) Get 1 or 2 NPCBot with your side
2) Dont form a party with them yet
3) Queue For BG
4) Win / Lose the BG Match
5) Finished BG and clicling leave
6) Server Crash / Not Responding

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. 4699f0429a86+ 2023-08-13 19:17:15 +0700 (npcbots_3.3.5 branch) (Win64, Release, Static)

### Operating system

Win 11 and Win Server 2019

**Comment by trickerer** [comment]
Same as #646.
Looks like grid was unloaded but not pre-loaded again when bot entered it.

**Comment by jakatangkir** [comment]
So as the best for now to fix this is by reverting to previous AC version right?

**Comment by trickerer** [comment]
Right. I would do just that if I were you.

**Comment by jakatangkir** [comment]
any recomendation on the previous AC version? i tried my oldest non compiled it is kinda crashing because the missmatch of database version

**Comment by trickerer** [comment]
> any recomendation on the previous AC version? i tried my oldest non compiled it is kinda crashing because the missmatch of database version

Try a partial revert then.
You'll need to revert this commit: https://github.com/azerothcore/azerothcore-wotlk/commit/2779833768bbe9967006d6d16888dace05b4bcb6. If your current branch is already past https://github.com/azerothcore/azerothcore-wotlk/commit/90b16ca065a4881b94438575502c2441f435d53b then you'll have to **revert that one first**.

**Comment by trickerer** [comment]
https://github.com/trickerer/Trinity-Bots/commit/5da5b7193a8f79587e9db44b5a589d45278162e6
