### ISSUE TITLE
[TC] [Bug] [Spell] Warlock bots are not using Soulstones in dungeons.

### ISSUE THREAD

**Issue by MokaCubrew** [trickerer/Trinity-Bots#658]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

The Warlock bot won't use Soulstones on me in an instance dungeon; it only does so when the dungeon is over and I return to the field. It doesn't seem to be a cooldown issue, as it ignores me from the time I enter the dungeon until the end.

### Expected behaviour

Warlock bots should be able to use Soulstones in dungeons without ignoring players.

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

TrinityCore rev. 6b9899e907a8+ 2023-09-17 01:07:49 +0200 (3.3.5 branch)

### Operating system

Ubuntu 22.04

**Comment by trickerer** [comment]
https://github.com/trickerer/Trinity-Bots/commit/cd415a1302ee9b9f6e9406b63a8f4ad8fb3c0872
https://github.com/trickerer/TrinityCore-3.3.5-with-NPCBots/commit/6825a29f2e
