### ISSUE TITLE
[AC] [Question] [Core] VisitNearbyCellsOf of NPCBot slows down the server a lot

### ISSUE THREAD

**Issue by SouthMemory** [trickerer/Trinity-Bots#659]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Hello, dear sir

After I replaced most monsters with npcbots, I found the server became very slow
Finally I found it's the following code from Map.cpp:

>     // non-player active objects, increasing iterator in the loop in case of object removal
    for (m_activeNonPlayersIter = m_activeNonPlayers.begin(); m_activeNonPlayersIter != m_activeNonPlayers.end();)
    {
        WorldObject* obj = *m_activeNonPlayersIter;
        ++m_activeNonPlayersIter;

        if (!obj || !obj->IsInWorld())
            continue;

        VisitNearbyCellsOf(obj, grid_object_update, world_object_update, grid_large_object_update, world_large_object_update);
    }

I tried to comment the code out and run the server again, the speed get normal, and the world seems normal too.
But I knew there must be something wrong if I just comment the code out.

what if I just skip the "VisitNearbyCellsOf" line if obj is NPCBot?

### TrinityCore or AzerothCore

AzerothCore

**Comment by trickerer** [comment]
That would prevent all bots' activities (block Object::Update() call) except for ones having player (or other non-bot active object) nearby. Which in your case could be ok if you plan to only use bots to replace mobs with.

**Comment by SouthMemory** [comment]
what do you mean by "prevent all bots' activities"?
does bots here refers to normal npcbots or wandering bots?
would mines,herbs,or other non npcbot monsters's activity get affected?

**Comment by trickerer** [comment]
Update() call is a root of a call tree for any unit or gameobject - auras, spells, movement, target selection, attack, death, respawn. Everything starts from Update() call. `VisitNearbyCellsOf()` visitor calls Update for objects around active object (within grid) - player, bot, etc. ex. Fel Reaver is an active object. All non-active objects without nearby active objects to update them are always idle, so if you set visitor to not be triggered by bots you make bots be no different than other mobs in that regard, though this may have nasty side effects like frozen cooldowns.
Also, when grid is unloaded (when there are no active objects in grid) all those non-active objects get deleted from memory, but bots won't be since they are active. Those loaded grids with no players nearby will just stay 'frozen in time' until some player arrives.

**Comment by SouthMemory** [comment]
Thanks a lot, @trickerer , for your understanding of wow and generous knowledge sharing.
Seems setting visitor to not be triggered by bots is good enough for now. 
Because I just want them to act like mobs but have equipments and can combat like real player, which your code have achieved.

**Comment by SouthMemory** [comment]
There are some problems, just as you mentioned:

- I kill some mob
- I log out 
- the mob will not respawn

well, It sees like I still have some work to do!

**Comment by SouthMemory** [comment]
There's still one thing I dont' understand
with the original mob creature and creature replaced with npcbots by me , the times  `VisitNearbyCellsOf` get called should not change, because number of active nonplayers did not change.
How come it became so slow when creature was replaced with npcbots?

**Comment by trickerer** [comment]
> There are some problems, just as you mentioned:
> 
>     * I kill some mob
> 
>     * I log out
> 
>     * the mob will not respawn
> 
> 
> well, It sees like I still have some work to do!

Well, that's wrong. Not calling VisitNearbyCellsOf() on bots doesn't change **how** non-active mobs are handled.
When player logs in grid at their location gets loaded into memory, creating mobs that have their spawn positions within said grid. If mob was dead, server checks if its respawn timer has passed already, and if so - re-spawns that mob.

**Comment by SouthMemory** [comment]
> There's still one thing I dont' understand with the original mob creature and creature replaced with npcbots by me , the times `VisitNearbyCellsOf` get called should not change, because number of active nonplayers did not change. How come it became so slow when creature was replaced with npcbots?

Seems it's because all npcbots are set as active and keep updating all the time.
maybe I should try adjust the active state accordingly.
