### ISSUE TITLE
Core fails to build

### ISSUE THREAD

**Issue by Mr-Deadbeat** [trickerer/Trinity-Bots#66]
OS: Ubuntu Server 20.04.1

TC Commit: 4c0a8ad3b3f9960fa15504cf32a84218807ac9d5
Bots: 29dcd96d6bbc69176d270cff6def77978416ead4

at end of compile it has 2 fatal errors

**Comment by Ryu1254** [comment]
i update my TC to the same commit as yours and apply the latest NPCBot patch..
here what I found how to fix the bot_ai.cpp

line 14845:
    sinfo->AttributesEx &= ~SPELL_ATTR1_UNK11;
Change it to 
    sinfo->AttributesEx &= ~SPELL_ATTR1_DONT_REFRESH_DURATION_ON_RECAST;

Line 15166:
    sinfo->AttributesEx4 |= SPELL_ATTR4_UNK21; //party aura
change it to:
    sinfo->AttributesEx4 |= SPELL_ATTR4_DONT_REMOVE_IN_ARENA; //party aura

line 15317: 
    sinfo->AttributesEx4 |= SPELL_ATTR4_UNK21; //party aura
Change it to
    sinfo->AttributesEx4 |= SPELL_ATTR4_DONT_REMOVE_IN_ARENA; //party aura

I am able to compile without error.

**Comment by trickerer** [comment]
https://github.com/trickerer/Trinity-Bots/commit/dfdd43ca5554ec26ddbcc8105f7bb518b1705f60
