### ISSUE TITLE
[TC] [AC] [Question] What is the purpose of this parameter `NpcBot.XpReduction.Amount`?

### ISSUE THREAD

**Issue by GesiIvy128** [trickerer/Trinity-Bots#663]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

"I'm really confused about what role `NpcBot.XpReduction.Amount` plays in the configuration file."

-#    NpcBot.XpReduction.Amount
-#    NpcBot.XpReduction.StartingNumber
-#        Description: XP percent penalty for each bot used starting with <StartingNumber>.
-#        Example:     3 bots, reduction is 20, start is 2: ((3-(2-1))*20) = 40%, 60% exp gained.
-#        Note:        Maximum overall xp reduction is 90%.
-#        Default:     0 - (NpcBot.XpReduction.Amount)
-#                     2 - (NpcBot.XpReduction.StartingNumber)

NpcBot.XpReduction.Amount         = 0
NpcBot.XpReduction.StartingNumber = 2

### TrinityCore or AzerothCore

Both

**Comment by trickerer** [comment]
`NpcBot.XpReduction.Amount` is XP reduction percentage. Each bot hired will reduce XP gain by this percentage, say 15%. Assuming `NpcBot.XpReduction.StartingNumber` is 1:
- 1 bot: 85% xp gained
- 2 bots: 70% xp gained
- 3 bots: 55% xp gained

If `NpcBot.XpReduction.StartingNumber` is set to 3:
- 1 bot: 100% xp gained
- 2 bots: 100% xp gained
- 3 bots: 85% xp gained
- and so on

**Comment by GesiIvy128** [comment]
> `NpcBot.XpReduction.Amount` is XP reduction percentage. Each bot hired will reduce XP gain by this percentage, say 15%. Assuming `NpcBot.XpReduction.StartingNumber` is 1:
> 
> * 1 bot: 85% xp gained
> * 2 bots: 70% xp gained
> * 3 bots: 55% xp gained
> 
> If `NpcBot.XpReduction.StartingNumber` is set to 3:
> 
> * 1 bot: 100% xp gained
> * 2 bots: 100% xp gained
> * 3 bots: 85% xp gained
> * and so on

Thank you! So, should I set it (`NpcBot.XpReduction.Amount`) to 15, right?

**Comment by trickerer** [comment]
> Thank you! So, should I set it (`NpcBot.XpReduction.Amount`) to 15, right?

To make this whole XP reduction thing work you mean? You have to set it to some non-zero value to enable it, pick value yourself - this is your server after all. The formula is right there.
