### ISSUE TITLE
 [AC] [Bug] [Group/Spell/Core]BUG about Icecrown citadel Sindragosa

### ISSUE THREAD

**Issue by moncat2005** [trickerer/Trinity-Bots#664]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

When Sindragosa launches an Ice Tomb attack, the player is frozen and the NPC is unable to rescue them. 
After the NPCBots freeze, players break them to save, but the NPC's Ice Tomb debuff still exists, and other NPCBOTS cannot save the hit NPCBots.
Only when the player leads the npcbots away from the dungeon can the npcbotsIce Tomb debuff be clear up.

### Expected behaviour

Hope it can be fixed:

1. fix Npcbots can break players' ice graves and cancel their ice tomb debuff.
2. Npcbots can break the ice tomb in Npcbots and cancel the ice tomb debuff for Npcbots companions

thanks！

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. 29af6cc88662+

### Operating system

Ubuntu 18.04

**Comment by hkbbdx** [comment]
I also hope this BUG can be solved, thank you!

**Comment by moncat2005** [comment]
I currently have a temporary limit on the 70157 skill, which is configured in the database disable table to have no effect on the creature.
INSERT INTO `acore_world`.`disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) VALUES ('0', '70157', '2', '', '', 'disable for npcbots');
