### ISSUE TITLE
WaypointMovementGenerator::LoadPath: creature Dustbelcher Wyrmhunter (GUID Full: 0xf130000a9c001089 Type: Creature Entry: 2716  Low: 4233) doesn't have waypoint path id: 0

### ISSUE THREAD

**Issue by kipless** [trickerer/Trinity-Bots#670]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

启动后worldserver会显示WaypointMovementGenerator::LoadPath: creature Dustbelcher Wyrmhunter (GUID Full: 0xf130000a9c001089 Type: Creature Entry: 2716  Low: 4233) doesn't have waypoint path id: 0  该怎么解决！

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. de00b639b324 2023-10-22 07:59:05 +0700 (npcbots_3.3.5 branch) (Win64, RelWithDebInfo, Static) (authserver)

### Operating system

win10

**Comment by trickerer** [comment]
This error has nothing to do with bots, reproducible on clean core
