### ISSUE TITLE
[AC] [Bug/Crash] Crash with warlock bot

### ISSUE THREAD

**Issue by sokie** [trickerer/Trinity-Bots#672]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

The worldserver crashes while playing in a dungeon with 2 bots.
Crash seems related to the warlock bot.
Crash happens when the other bot is dead ( might be due to warlock trying to cast on the dead bot? )

### Crashlog

https://gist.github.com/sokie/abcf58f74258025eadcfa4546b5010a6

### Steps to reproduce the problem

1) Join a dungeon with 2 bots, one is a warlock the other is a warrior
2) Warrior dies
3) If you engage in another fight, the worldserver will crash

?) If you wait for warrior to res, crash doesn't happen and you can play fine

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

de00b639b3247098cf809ac038b227181443fa06

### Operating system

Win10

**Comment by trickerer** [comment]
Do you remember warlock bot level?

**Comment by sokie** [comment]
> Do you remember warlock bot level?

I was 15 or 16, warlock was showing '??' afaik oddly enough
