### ISSUE TITLE
[AC] Fresh AC, build error

### ISSUE THREAD

**Issue by philldogger** [trickerer/Trinity-Bots#674]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

New AC master only project.  Installed NPCbots.patch with git-bash successfully.  Cmake was successful.  Build triggered the following errors: (trying to only post error messages)

23>bot_necromancer_ai.cpp
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_GridNotifiers.h(1206,40): error C2662: 'DeathState Unit::getDeathState(void)': cannot convert 'this' pointer from 'const Creature' to 'Unit &' (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_ai.cpp)
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_GridNotifiers.h(1206,37): message : Conversion loses qualifiers (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_ai.cpp)
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\Entities\Unit\Unit.h(1850,16): message : see declaration of 'Unit::getDeathState' (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_ai.cpp)
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_GridNotifiers.h(1206,40): message : while trying to match the argument list '()' (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_ai.cpp)
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_GridNotifiers.h(1206,61): error C2065: 'CORPSE': undeclared identifier (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_ai.cpp)
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_GridNotifiers.h(1262,47): error C2662: 'DeathState Unit::getDeathState(void)': cannot convert 'this' pointer from 'const Creature' to 'Unit &' (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_ai.cpp)
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_GridNotifiers.h(1262,44): message : Conversion loses qualifiers (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_ai.cpp)
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\Entities\Unit\Unit.h(1850,16): message : see declaration of 'Unit::getDeathState' (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_ai.cpp)
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_GridNotifiers.h(1262,47): message : while trying to match the argument list '()' (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_ai.cpp)
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_GridNotifiers.h(1262,68): error C2065: 'CORPSE': undeclared identifier (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_ai.cpp)
21>cs_inventory.cpp
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_GridNotifiers.h(1206,40): error C2662: 'DeathState Unit::getDeathState(void)': cannot convert 'this' pointer from 'const Creature' to 'Unit &' (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_dark_ranger_ai.cpp)
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_GridNotifiers.h(1206,37): message : Conversion loses qualifiers (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_dark_ranger_ai.cpp)
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\Entities\Unit\Unit.h(1850,16): message : see declaration of 'Unit::getDeathState' (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_dark_ranger_ai.cpp)
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_GridNotifiers.h(1206,40): message : while trying to match the argument list '()' (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_dark_ranger_ai.cpp)
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_GridNotifiers.h(1206,61): error C2065: 'CORPSE': undeclared identifier (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_dark_ranger_ai.cpp)
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_GridNotifiers.h(1262,47): error C2662: 'DeathState Unit::getDeathState(void)': cannot convert 'this' pointer from 'const Creature' to 'Unit &' (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_dark_ranger_ai.cpp)
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_GridNotifiers.h(1262,44): message : Conversion loses qualifiers (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_dark_ranger_ai.cpp)
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\Entities\Unit\Unit.h(1850,16): message : see declaration of 'Unit::getDeathState' (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_dark_ranger_ai.cpp)
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_GridNotifiers.h(1262,47): message : while trying to match the argument list '()' (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_dark_ranger_ai.cpp)
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_GridNotifiers.h(1262,68): error C2065: 'CORPSE': undeclared identifier (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_dark_ranger_ai.cpp)

23>bot_sphynx_ai.cpp
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_GridNotifiers.h(1206,40): error C2662: 'DeathState Unit::getDeathState(void)': cannot convert 'this' pointer from 'const Creature' to 'Unit &' (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_necromancer_ai.cpp)
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_GridNotifiers.h(1206,37): message : Conversion loses qualifiers (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_necromancer_ai.cpp)
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\Entities\Unit\Unit.h(1850,16): message : see declaration of 'Unit::getDeathState' (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_necromancer_ai.cpp)
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_GridNotifiers.h(1206,40): message : while trying to match the argument list '()' (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_necromancer_ai.cpp)
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_GridNotifiers.h(1206,61): error C2065: 'CORPSE': undeclared identifier (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_necromancer_ai.cpp)
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_GridNotifiers.h(1262,47): error C2662: 'DeathState Unit::getDeathState(void)': cannot convert 'this' pointer from 'const Creature' to 'Unit &' (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_necromancer_ai.cpp)
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_GridNotifiers.h(1262,44): message : Conversion loses qualifiers (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_necromancer_ai.cpp)
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\Entities\Unit\Unit.h(1850,16): message : see declaration of 'Unit::getDeathState' (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_necromancer_ai.cpp)
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_GridNotifiers.h(1262,47): message : while trying to match the argument list '()' (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_necromancer_ai.cpp)
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_GridNotifiers.h(1262,68): error C2065: 'CORPSE': undeclared identifier (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_necromancer_ai.cpp)
21>cs_modify.cpp
23>bot_warlock_ai.cpp
21>cs_npc.cpp
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_GridNotifiers.h(1206,40): error C2662: 'DeathState Unit::getDeathState(void)': cannot convert 'this' pointer from 'const Creature' to 'Unit &' (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_spellbreaker_ai.cpp)
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_GridNotifiers.h(1206,37): message : Conversion loses qualifiers (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_spellbreaker_ai.cpp)
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\Entities\Unit\Unit.h(1850,16): message : see declaration of 'Unit::getDeathState' (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_spellbreaker_ai.cpp)
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_GridNotifiers.h(1206,40): message : while trying to match the argument list '()' (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_spellbreaker_ai.cpp)
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_GridNotifiers.h(1206,61): error C2065: 'CORPSE': undeclared identifier (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_spellbreaker_ai.cpp)
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_GridNotifiers.h(1262,47): error C2662: 'DeathState Unit::getDeathState(void)': cannot convert 'this' pointer from 'const Creature' to 'Unit &' (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_spellbreaker_ai.cpp)
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_GridNotifiers.h(1262,44): message : Conversion loses qualifiers (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_spellbreaker_ai.cpp)
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\Entities\Unit\Unit.h(1850,16): message : see declaration of 'Unit::getDeathState' (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_spellbreaker_ai.cpp)
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_GridNotifiers.h(1262,47): message : while trying to match the argument list '()' (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_spellbreaker_ai.cpp)
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_GridNotifiers.h(1262,68): error C2065: 'CORPSE': undeclared identifier (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_spellbreaker_ai.cpp)
21>cs_pet.cpp
23>bot_warrior_ai.cpp
23>botcommands.cpp
21>cs_player.cpp
23>botdatamgr.cpp
21>cs_player_settings.cpp
23>botdpstracker.cpp
21>cs_quest.cpp
21>cs_reload.cpp
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_GridNotifiers.h(1206,40): error C2662: 'DeathState Unit::getDeathState(void)': cannot convert 'this' pointer from 'const Creature' to 'Unit &' (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_sphynx_ai.cpp)
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_GridNotifiers.h(1206,37): message : Conversion loses qualifiers (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_sphynx_ai.cpp)
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\Entities\Unit\Unit.h(1850,16): message : see declaration of 'Unit::getDeathState' (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_sphynx_ai.cpp)
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_GridNotifiers.h(1206,40): message : while trying to match the argument list '()' (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_sphynx_ai.cpp)
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_GridNotifiers.h(1206,61): error C2065: 'CORPSE': undeclared identifier (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_sphynx_ai.cpp)
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_GridNotifiers.h(1262,47): error C2662: 'DeathState Unit::getDeathState(void)': cannot convert 'this' pointer from 'const Creature' to 'Unit &' (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_sphynx_ai.cpp)
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_GridNotifiers.h(1262,44): message : Conversion loses qualifiers (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_sphynx_ai.cpp)
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\Entities\Unit\Unit.h(1850,16): message : see declaration of 'Unit::getDeathState' (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_sphynx_ai.cpp)
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_GridNotifiers.h(1262,47): message : while trying to match the argument list '()' (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_sphynx_ai.cpp)
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_GridNotifiers.h(1262,68): error C2065: 'CORPSE': undeclared identifier (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_sphynx_ai.cpp)
23>botdump.cpp
23>botgearscore.cpp
23>botgiver.cpp
23>botmgr.cpp
23>botspell.cpp
21>cs_reset.cpp
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_GridNotifiers.h(1206,40): error C2662: 'DeathState Unit::getDeathState(void)': cannot convert 'this' pointer from 'const Creature' to 'Unit &' (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_sea_witch_ai.cpp)
21>cs_script_loader.cpp
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_GridNotifiers.h(1206,37): message : Conversion loses qualifiers (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_sea_witch_ai.cpp)
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\Entities\Unit\Unit.h(1850,16): message : see declaration of 'Unit::getDeathState' (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_sea_witch_ai.cpp)
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_GridNotifiers.h(1206,40): message : while trying to match the argument list '()' (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_sea_witch_ai.cpp)
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_GridNotifiers.h(1206,61): error C2065: 'CORPSE': undeclared identifier (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_sea_witch_ai.cpp)
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_GridNotifiers.h(1262,47): error C2662: 'DeathState Unit::getDeathState(void)': cannot convert 'this' pointer from 'const Creature' to 'Unit &' (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_sea_witch_ai.cpp)
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_GridNotifiers.h(1262,44): message : Conversion loses qualifiers (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_sea_witch_ai.cpp)
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\Entities\Unit\Unit.h(1850,16): message : see declaration of 'Unit::getDeathState' (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_sea_witch_ai.cpp)
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_GridNotifiers.h(1262,47): message : while trying to match the argument list '()' (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_sea_witch_ai.cpp)
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_GridNotifiers.h(1262,68): error C2065: 'CORPSE': undeclared identifier (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_sea_witch_ai.cpp)
23>botwanderful.cpp

23>bpet_mage.cpp
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\botmgr.cpp(1116,24): error C2065: 'ALIVE': undeclared identifier
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_GridNotifiers.h(1206,40): error C2662: 'DeathState Unit::getDeathState(void)': cannot convert 'this' pointer from 'const Creature' to 'Unit &' (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bpet_ai.cpp)
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_GridNotifiers.h(1206,37): message : Conversion loses qualifiers (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bpet_ai.cpp)
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\Entities\Unit\Unit.h(1850,16): message : see declaration of 'Unit::getDeathState' (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bpet_ai.cpp)
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_GridNotifiers.h(1206,40): message : while trying to match the argument list '()' (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bpet_ai.cpp)
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_GridNotifiers.h(1206,61): error C2065: 'CORPSE': undeclared identifier (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bpet_ai.cpp)
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_GridNotifiers.h(1262,47): error C2662: 'DeathState Unit::getDeathState(void)': cannot convert 'this' pointer from 'const Creature' to 'Unit &' (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bpet_ai.cpp)
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_GridNotifiers.h(1262,44): message : Conversion loses qualifiers (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bpet_ai.cpp)
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\Entities\Unit\Unit.h(1850,16): message : see declaration of 'Unit::getDeathState' (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bpet_ai.cpp)
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_GridNotifiers.h(1262,47): message : while trying to match the argument list '()' (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bpet_ai.cpp)
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bot_GridNotifiers.h(1262,68): error C2065: 'CORPSE': undeclared identifier (compiling source file C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\bpet_ai.cpp)
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\AI\NpcBots\botmgr.cpp(1940,28): error C2065: 'JUST_DIED': undeclared identifier
21>zone_ironforge.cpp

21>boss_lady_deathwhisper.cpp
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\Entities\Creature\Creature.cpp(3986,20): error C2065: 'ALIVE': undeclared identifier
23>C:\Azerothcore_Repo\azerothcore-wotlk\src\server\game\Entities\Creature\Creature.cpp(4008,31): error C2065: 'ALIVE': undeclared identifier
23>UpdateFieldFlags.cpp

25>LINK : fatal error LNK1181: cannot open input file '..\game\RelWithDebInfo\game.lib'
25>Done building project "worldserver.vcxproj" -- FAILED.
26>------ Build started: Project: ALL_BUILD, Configuration: RelWithDebInfo x64 ------
26>Building Custom Rule C:/Azerothcore_Repo/azerothcore-wotlk/CMakeLists.txt
========== Build: 24 succeeded, 2 failed, 0 up-to-date, 0 skipped ==========

### Expected behaviour

Build with no errors

### Steps to reproduce the problem

Build

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. f757e93da5cd 2023-10-28 10:54:03 +0200 (master branch) (Win64, RelWithDebInfo, Static)

### Operating system

Win11

**Comment by moncat2005** [comment]
I also found errors related to npcbots when compiling under Linux (use AzrothCore 52d37a9+).
The issue should be related to commit f757e93
![npcbots-make-error](https://github.com/trickerer/Trinity-Bots/assets/34859687/6e4a199b-b3e1-4eb0-8a4a-e265ce1a9720)
