### ISSUE TITLE
[AC] [Question/Feature] [Mod-autobalance] update of npcbots compatible version to latest revision for fixes regarding summoned creatures

### ISSUE THREAD

**Issue by icemansparks** [trickerer/Trinity-Bots#676]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

The latest version of mod-autobalance fixes issues with summoned creatures inside dungeons (which were not properly scaled at all times before).

It would be great if the NPCbots compatible branch here https://github.com/trickerer/mod-autobalance could be updated to include the lastest fixes from the main project.

### TrinityCore or AzerothCore

 AzerothCore

### Core rev. hash/commit

[_No response_](https://github.com/azerothcore/mod-autobalance/commit/a20143dde5f6e1dd992f537f45be3b03dceaee76)

### Operating system

Win 11 x64

**Comment by philldogger** [comment]
Bump

**Comment by trickerer** [comment]
@philldogger this is not a forum, no need to bump here. I'll update autobalance when I'm able to.

**Comment by philldogger** [comment]
Thanks Trickerer... appreciate your work.

**Comment by trickerer** [comment]
https://github.com/trickerer/mod-autobalance/commit/b995e3bdee7751b66cbcbf503b6b66e66e7d615c
