### ISSUE TITLE
[TC] [AC] [Question] Bots in LUA?

### ISSUE THREAD

**Issue by GesiIvy128** [trickerer/Trinity-Bots#679]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

I would like to write a Lua script that gives me money when a robot in the team kills a guard. Should I consider the robots as players or NPCs in this case? Or, can I use `player:IsInGroup()` in Lua for the robots?
Thanks.

### TrinityCore or AzerothCore

TrinityCore

**Comment by trickerer** [comment]
It's rare to see someone use Lua engine with TrinityCore. Do you use some Eluna fork?

I can say for sure that `player:IsInGroup()` won't work with bots, you'll need something like `group:IsMember()`. Sorry, I don't use any Lua engine, but if you provide a link to the repository I think I will be able to give you a better advice.
