### ISSUE TITLE
Question: Where does NPCBOT stat store?

### ISSUE THREAD

**Issue by Ryu1254** [trickerer/Trinity-Bots#68]
Do you know where are the stats store for bots??
like their HP, mana, Attack power , dodge , parry etc...

on the table characters_npcbot, i see only equipment , class etc.. but not their combat stat..

I'm trying to make an SQL query to see what are my bot stats, like does they have enough hit rating, expertise, armor pen etc.

Thanks.

**Comment by Ryu1254** [comment]
There is a table call character_stats, that auto popuplate with the config PlayerSave.Stats.MinLevel = 1
do we have something similar to that table but for bot?

**Comment by trickerer** [comment]
Well, bot stats are not saved for external use in DB currently.

 > I'm trying to make an SQL query to see what are my bot stats, like does they have enough hit rating, expertise, armor pen etc.

`chracter_stats` doesn't provide any info on hit, expertise or armor pen. I'm saying this because I'm not sure if I will be able to provide info on these stats in full either.

**Comment by Ryu1254** [comment]
Yeah you right.. the table chracter_stats does not provide those stat, but they provide the effect of the stat, like the dodgePct, parryPct..

I just wondering, when you use a GM account and talk to a bot, doing "Debug List Stat" i guess, it's a dynamic function that gathering all those info right?
you think there is way to dump those info into a table? even gear info.. there will be a hell of column..

**Comment by trickerer** [comment]
If you noticed, when you use /bonk on a bot, stats listed often have a '+' or '-' prefix. It is because those stats are relative and only a average bonus is shown, like '+ x% chance to hit', which kind of understandable as you see it the same way in character stats window.

But saving stat in DB as a bonus seems unconvenient. I don't know, I never used those, maybe it's fine

**Comment by Ryu1254** [comment]
it's for consultation only, not necessary need to be live data..
like the chracter_stats, it's update on player logoff.
if we can have the something for bot_stats table to be update when logoff for example..If that feasible..
