### ISSUE TITLE
[AC] [Question] [Group/Spell/Core] How to debug bots

### ISSUE THREAD

**Issue by sokie** [trickerer/Trinity-Bots#680]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

I might have messed up something with bots.
They follow,equip items and auto attack just fine but they never use any spells.
Hunters do only auto-attack, Priest never heals even when set to correct spec.
How can I debug their actions to see what's up?

### TrinityCore or AzerothCore

AzerothCore

**Comment by trickerer** [comment]
Check this comment: https://github.com/trickerer/Trinity-Bots/issues/650#issuecomment-1751915116
Once you set up your IDE and core for debugging make a breakpoint in bot's class ai attack method to see what gets executed and what doesn't.
