### ISSUE TITLE
[TC] [AC] [Question/Feature]  Choose hunter's pet?

### ISSUE THREAD

**Issue by GesiIvy128** [trickerer/Trinity-Bots#683]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Can I choose which specific hunter pet to summon? Right now, all hunters (by default) only summon wolves.

### TrinityCore or AzerothCore

TrinityCore

**Comment by trickerer** [comment]
Hunter's pet is selectable through gossip menu. You cannot choose the exact type, only spec. There are just too many to fit on a single page.
Wolf is a typical raid pet due to its abilities increasing DPS the most, except for Beast Mastery hunters who have more options.
