### ISSUE TITLE
[TC] Compile Error with latest TC Version. Problem with latest TC Commit (Core/Spells: Make SpellEffectInfo not copyable)

### ISSUE THREAD

**Issue by Krutok** [trickerer/Trinity-Bots#685]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

I loaded the last TC update and am now getting a compilation error

![Screenshot 2023-11-08 162753](https://github.com/trickerer/Trinity-Bots/assets/47283866/06dfc860-6a70-40e1-a9f2-55774335844b)

### Steps to reproduce the problem

Update to the last TC Version and you got this Compile Error

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/dd1847bd8ff36618500ead2b734cb0e087905066

### Operating system

Debian 11

**Comment by PaienNate** [comment]
Revert "Core/Spells: Make SpellEffectInfo not copyable" commit in latest TrinityCore, it breaks this mod.

**Comment by PaienNate** [comment]
> @PaienNate
> 
> > Revert "Core/Spells: Make SpellEffectInfo not copyable" commit in latest TrinityCore, it breaks this mod.
> 
> I've already merged it with my fork and can't delete it once I've merged it

You can try use git to revert its change. Or, just use two files in https://github.com/trickerer/TrinityCore-3.3.5-with-NPCBots/tree/npcbots_3.3.5/src/server/game/Spells (File name as I remember: SpellInfo.cpp,SpellInfo.h)
(Maybe you should see its difference, it delete some function, and I turn it back)
I'm not good at using git, so I can't give you more help...

**Comment by Kazodan** [comment]
the problem with reverting  this tc commit, is sadly the core become instable and will lead to multiple spell related crashes without a proper fix :/

**Comment by PaienNate** [comment]
> the problem with reverting this tc commit, is sadly the core become instable and will lead to multiple spell related crashes without a proper fix :/

(Translate by ChatGPT:)

"Currently, there isn't a better way for me, and it does indeed result in an unstable TC. In theory, the method of retrieval should be rewritten to accommodate the changes in TC, but I'm not proficient in C++. Hopefully someone can quickly figure out the fix. In principle, TC must have made specific alterations elsewhere to ensure accurate retrieval; I'm just unaware of those changes."

**Comment by trickerer** [comment]
https://github.com/trickerer/Trinity-Bots/commit/5da5b7193a8f79587e9db44b5a589d45278162e6
