### ISSUE TITLE
[AC] [Question] [Core] Disabling extra classes for wandering bots, and easy creature_template creation.

### ISSUE THREAD

**Issue by SlowLogicBoy** [trickerer/Trinity-Bots#687]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Thank you for this great mod, our game became way more fun with this mod then any private wotlk server.

1. Is there an easy way (without deleting `creature_template` and other table records) to disable extra classes for wandering bots?

I have disabled (and did not spawn) hirable bots with extra classes, but I also don't want custom classes for wandering bots :)

2. Are there any tools that would allow easier creation for more wandering bots in `creature_template` table (and other tables)?

### TrinityCore or AzerothCore

AzerothCore

### Operating system

Debian 12

**Comment by trickerer** [comment]
1. Disabling bot classes in general should disable those classess for wandering bots generation as well (this reduces max wandering bots count).
2. I didn't create any tools for batching new bots creation. Good news is that wow repack community already provides SQLs with thousands of new bots, the only problem I see is bot names. Discord link: https://discord.gg/m72xntKa

**Comment by SlowLogicBoy** [comment]
> 1. Disabling bot classes in general should disable those classess for wandering bots generation as well (this reduces max wandering bots count).

Ah I haven't tested wandering bots after I disabled those classes, sorry for this :)

> 2. I didn't create any tools for batching new bots creation. Good news is that wow repack community already provides SQLs with thousands of new bots, the only problem I see is bot names. Discord link: https://discord.gg/m72xntKa

Thank you, I'll see maybe I will be able to do something about names, like script to rename them.
