### ISSUE TITLE
[TC] [AC] [Question/Feature] [Group/Spell/Core] Newbie

### ISSUE THREAD

**Issue by Tntdruid** [trickerer/Trinity-Bots#689]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Hello,

Is there a quick newbie guide how to apply the patch to AC?

Thanks.

### TrinityCore or AzerothCore

AzerothCore

**Comment by trickerer** [comment]
Here is how you install bots to a fresh server (if you have no database set up yet). Refer to AC installation guide for required software.
1. Open console at destination base folder. Ex. if your core folder has to be `D:\server\AzerothCore` then your base folder is `D:\server`
2. `git clone https://github.com/azerothcore/azerothcore-wotlk.git`
3. `git reset --hard da30653363` (last supported revision)
4. Copy `AC/NPCBots.patch` to your AzerothCore folder
5. `patch -p1 < NPCBots.patch`
6. Run CMake and build (refer to AC installation guide)
7. Rename worldserver.conf.dist to worldserver.conf and configure server to your liking
8. Run the server and it will create your DBs including NPCBots ones
9. Create an admin account (gm level 3)
10. See commands section of Readme and spawn bots

**Comment by trickerer** [comment]
If you need to apply patch to existing server than just use [Installation](https://github.com/trickerer/Trinity-Bots#npcbot-mod-installation) section of Readme: steps 2, 3, 4 and 5. Enable automatic updates in config (enabled by default) and skip steps 6 and 7.

**Comment by Tntdruid** [comment]
@trickerer Thanks for the help.
