### ISSUE TITLE
Vehicul bug - dungeon that are not implement bug pretty bad.

### ISSUE THREAD

**Issue by Ryu1254** [trickerer/Trinity-Bots#69]
I know the vehicule mechanism are not implement for all raid except Occulus and EOE. 
Some raid are buggy pretty bad and not feasible with bot anymore. 

for example ICC: 
1st bug : gunboat fight: if the person who bring multiple bot, when enter use the cannon, all bot transform into cannon.. it could be an advantage or could be a problem. when all bot turn into cannon, no one kill adds spawn on the boat anymore. this lead to wipe.. also, when we manage to finish the boat fight, we are stuck in combat, cannot loot the boat unless we kill ourself.
2nd bug in ICC:
When fighting Putricide, if i bring 5 bot and control the big abomination, then all my bot are transform into abomination..so that lead to a wipe.. because, there are no tank , dps or healer anymore.

Is there any way, to prevent this from happening? 
like if the vehicule is not implement for a specific dungeon, do not apply bot vehicule??

I know there is a lot to implement..

**Comment by trickerer** [comment]
Man, I didn't even touched ICC in my vehicles testing... And I thought gunship battle doesn't even work at all.

Right now you can only use `.npcbot vehicle eject` command to dismount bots from vehicles - selected or all of them.

**Comment by Ryu1254** [comment]
No problem at all.. this is we call unexpected behavior..

I think. the moment you mount a vehicle. it's something general that trigger a mount..
Just think about that, I did not test naxxramas instructor razuvious, i dont know what will happen yet.. my guess, when i control the orb, all the bot will try to control it too.. that would be a mess heheh.

Yes, i'll try .npcbot vehicle eject next time..

**Comment by Ryu1254** [comment]
Ok confirm. naxxramas instructor razuvious is working fine. no bot vehicle interfered.

**Comment by trickerer** [comment]
Good, less work for me. Thanks

**Comment by Ryu1254** [comment]
after playing since.. i kind like this bug, I can do ICC boat guntlet alone with bot.. otherwise, it's nearly impossible to do it.
with the command ".npcbot vehicle eject", it work pretty well in putricide fight or any fight that you don't require bot to be in an vehicle. I think we can leave as is.
