### ISSUE TITLE
[TC] [AC] [Bug/Crash] [Group/Spell/Core] ISSUE_TITLE

### ISSUE THREAD

**Issue by aaronruhe** [trickerer/Trinity-Bots#690]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

The server is working great. I just can't talk to the extra NPC's like the archmage, dark ranger etc.

### Expected behaviour

I should get the gossip chat like with 'normal' bots?

### Crashlog

N/A

### Steps to reproduce the problem

1) I lookup the bot (.npcbot lookup ...)
2) I spawn the bot (.npcbot spawn ...)

Then I can't talk to it.

I tried it with add and then talk, but no luck.

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

AzerothCore rev. b45a3fcac97b 2023-08-13 22:38:53 +0700 (AzerothCore branch) (Win64, Release, Static) (worldserver-daemon)

### Operating system

Win11

**Comment by trickerer** [comment]
Check your config and enable extra classes you want, look for
- `NpcBot.Classes.<Class>.Enable`

**Comment by aaronruhe** [comment]
THanks for the advice!

I did the following:
1) 
![Screenshot 2023-11-18 123431](https://github.com/trickerer/Trinity-Bots/assets/18396824/ea46c25a-4143-4dc5-b346-edfad4605a3b)
2) restarted everything (sql, auth and server via the 'start server' action)
3) Lookup, spawn

I still cant talk to them

**Comment by aaronruhe** [comment]
It works. I had a config and configs folder and 2 server files? Anyway, thanks for your help!

**Comment by aaronruhe** [comment]
Fixed by changing NpcBot.Classes.<Class>.Enable

**Comment by trickerer** [comment]
If you don't want to risk crashing your server then disable Blademaster as per default settings

**Comment by aaronruhe** [comment]
Hi thank you i will! Maybe I need to start another thread, but I'll try here. :)

I keep getting the message: One or more party members do not meet the requirements for the chosen dungeon.

I went into stratholme just fine. Some time later I tried again and I got the message. Yesterday I was in Scholomance, and now I get the same message. If I disband party it works again. Shutting down the world / auth doesn't work. Also resetting instances doesn't work (maybe cause it's a dungeon).

Do you have any ideas?

**Comment by trickerer** [comment]
Yes, I'm well aware. That's a bug with easy workaround. The problem is in how LFG works for bots, not sure what happens exactly.

**Comment by aaronruhe** [comment]
It's fine. I'm really happy with the server thanks so much!

**Comment by aaronruhe** [comment]
Maybe one more thing. :P Can I use glyphs on bots? I'd like the water elemental to be a permanent summon. 

Is there another channel or anything like that to ask these question? I am aware that this isn't the right way...

**Comment by trickerer** [comment]
Bots already use all glyphs I cared to implement (gained same way as spells). Glyph of water elemental was removed at some point and I don't remember why :see_no_evil:
If you really want it you can modify elemental duration in bpet_mage.cpp to a great enough value (from default 45 sec).

**Comment by trickerer** [comment]
In general, if you need a place to ask questions then you could open a discussion or find me in discord by same name as my github profile

**Comment by aaronruhe** [comment]
You're awesome thank you. Ill add you on Discord :)
