### ISSUE TITLE
[AC] [Feature] [Spell] why npc bot's damge so high, 2 to 3 times than it should be

### ISSUE THREAD

**Issue by SouthMemory** [trickerer/Trinity-Bots#692]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

npcbpts' damage are strangely high, 2 to 3 times than it should be
warrior bot, equipped, with attack power like 3500, hit me with melee attack damge around 2000 (no critical）, while my character can only hit around 1000 on the bot or other creature
It can be seen from the screen I uploaded ![screenshot of damage](https://github.com/trickerer/Trinity-Bots/assets/28387896/40a4c24b-600e-42d9-ae32-6a003aa0f40b)
I did not change the rate of damge in configs.
I just wonder, why?

### TrinityCore or AzerothCore

AzerothCore

**Comment by trickerer** [comment]
NPCs have base damage and base attack power. For NPCBot creature templates it's like 2-6 base damage and 0 base attack power, while other npcs have those set based on sniffs. All this additional damage is also affected further by bot talents.
This is probably it.

**Comment by SouthMemory** [comment]
It seems the following code is not working for npcbots
`        // Calculate armor reduction
        if (IsDamageReducedByArmor((SpellSchoolMask)(damageInfo->damages[i].damageSchoolMask)))
        {
            damageInfo->damages[i].damage = Unit::CalcArmorReducedDamage(this, damageInfo->target, damage, nullptr, 0, damageInfo->attackType);
            damageInfo->cleanDamage += damage - damageInfo->damages[i].damage;
        }
        else
        {
            damageInfo->damages[i].damage = damage;
        }`

I added some log:
ERROR [entities.unit] Bot Dwarfwarrior melee damage before mod: 2107
ERROR [entities.unit] Bot Dwarfwarrior melee damage after armor reduced: 2107

**Comment by SouthMemory** [comment]
these two values are too high (a death-knight bot as an example):
UNIT_FIELD_MINDAMAGE: 4020.95
UNIT_FIELD_MAXDAMAGE: 5553.43

**Comment by trickerer** [comment]
What ends up in unit fields is the result, not the reason.

This also looks almost like you're trying to pretend this is a problem of original bots and not your personal project.

Read my previous comment again and try to adjust creature's template damage / ap to see if it makes the difference.

**Comment by SouthMemory** [comment]
It truned out it's the following code which caused the damge to be too high (StatSystem.cpp)
`    float baseValue        = GetModifierValue(unitMod, BASE_VALUE) + (attackPower / 14.0f) * variance;
    float basePct          = GetModifierValue(unitMod, BASE_PCT) * attackSpeedMulti;
    //float baseValue        = GetModifierValue(unitMod, BASE_VALUE) + (attackPower / 14.0f) * variance * attackSpeedMulti;
    //float basePct          = GetModifierValue(unitMod, BASE_PCT);`

**Comment by SouthMemory** [comment]
uncomment those two lines downstairs solved this damage problem.
As This may not be a problem in other situations, I'll close this issue.
