### ISSUE TITLE
[AC] [Bug] [Group/Core] Mana users lose their power pool in instances and do not recover it until restart

### ISSUE THREAD

**Issue by archipoeta** [trickerer/Trinity-Bots#693]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

When bots with powerType = Mana teleport into an instance their mana pool is wiped out, and does not recover. It doesn't go 0% it simply disappears, and then they no longer can do anything related to mana at all even outside said instance: until server restart. (Assumingly because that's when the power pool gets reloaded from the characters_npcbots_stats table or what have ya.)

Tested this about 20-30 different variations, happens on stockades and deadmines, mage, priest, shaman, druid - all have this happen, both from random dungeon LFG and from just literally zoning into the instance.

There is a chance I've mucked something up because the patch for this mod into AC core needed some slight manual intervention.
But any ideas or pointers would be super helpful! :)

TIA. <3

### Expected behaviour

Mana users should definitely keep their power pool in instances.

### Crashlog

N/A

### Steps to reproduce the problem

1) Load up AC `12ff3e0c` and patch in this mod
2) Grab a mana user bot and group with them
3) Enter an instance dungeon by walking in or by RDF LFG (need 4 bots)
4) Notice the mana user has lost its power pool :(

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. 12ff3e0c6776+ 2023-11-05 10:24:20 +0000 (master branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon)

### Operating system

Debian 12.2

**Comment by trickerer** [comment]
Probably some recent AC change broke it.

Try using troubleshooting gossip menu (`Pull yourself together`) -> `Fix power type` as a tempfix.

**Comment by archipoeta** [comment]
That unfortunately did not have any noticeable outcome.
As a GM character I checked Debug > List Stats and the "total mana" was 0.
I went ahead and did a Reset Stats but it remained total mana = 0.

Appreciate your help!

**Comment by archipoeta** [comment]
100% this ^^^

**Comment by archipoeta** [comment]
This might be an important clue--

On entering instance [dungeon]:
`Active creature GUID Full: 0xf13001125a0000a5 Type: Creature Entry: 70234  Low: 165 added to grid[15, 33] but spawn grid[32, 32] was not loaded.`

On exiting instance:
`Active creature GUID Full: 0xf13001125a0000a5 Type: Creature Entry: 70234  Low: 165 removed from grid[15, 33] but spawn grid[32, 32] was not loaded.`

And the power pool is gone until server restart. 🤔

**Comment by archipoeta** [comment]
Ok, this was actually a conflict with the autobalance mod (eventhough that mod was disabled).
Those error messages about the spawn grid appear to be red herrings.

Hope this helps anyone else.
