### ISSUE TITLE
 [AC] [Bug/Crash] Гуляющие боты-друиды балансеры не превращаються в медведя или кошку во время боя

### ISSUE THREAD

**Issue by Parkan1986** [trickerer/Trinity-Bots#694]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Гуляющие боты-друиды у которых спек стоит баланс(28) во время боя у них установлены роли дпс+дальник.Но когда к ним подбегает моб то друид  немного отбегает от моба, а потом стоит и никуда не убегает и пытается превратиться в кошку(медведя),но не превращается и стоит тратит ману в пустую.Его бьют, а он не отбивается практически. Замечаю такое довольно часто. Незаметил  такого поведения друидов во время боя с игроком,только с мобами.Другие спеки друидов работают нормально.

### Expected behaviour

Боты друиды должны превращаться в кошку\медведя когда их моб загонят в угол во время боя.

### Steps to reproduce the problem

1.Найти гуляющего бота-друида балансера и проследить за его поведением
2.Увидеть результат его битв.

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

de00b639b3247098cf809ac038b227181443fa06

### Operating system

Win10

**Comment by Mitradis** [comment]
@Parkan1986 я случайно не с вами связывался по дискорду и скидывал кастомные патчи? Не могу найти человека которому все скидывал.

**Comment by Parkan1986** [comment]
> @Parkan1986 я случайно не с вами связывался по дискорду и скидывал кастомные патчи? Не могу найти человека которому все скидывал.

О каких патчах идет речь?

Добавлю свои наблюдения.Друиды у которых стоит поведение Ranged и стоит ветка Баланс до 40го уровня во время боя не сильно далеко отбегают от мобов а потом бьют либо милишными атаками и кое-когда магие но и тратят ману на попытку превращения в совуха т.к на 40 уровне и выше я встречал друдиов с таким же поведением но они превращались в совуха и спокойно отбивались магией и атаками когда мобы их били в ближнем диапазоне.

**Comment by trickerer** [comment]
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/bfbab63cf68e2a8fd3dc0e37ee287fbfba5bcd42

Та же фигня была и против игроков, просто у игрока поведение чуть поразнообразнее

**Comment by Parkan1986** [comment]
> [trickerer/AzerothCore-wotlk-with-NPCBots@bfbab63](https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/bfbab63cf68e2a8fd3dc0e37ee287fbfba5bcd42)
> 
> Та же фигня была и против игроков, просто у игрока поведение чуть поразнообразнее

ой как хорошо.будем проверять.
