### ISSUE TITLE
[AC] [Bug] Бот не использует летающего/наземного маунта

### ISSUE THREAD

**Issue by xBarselonx** [trickerer/Trinity-Bots#696]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Когда бот случайно агрит летающего/наземного моба он спешивается и вступает с ним в бой. Игрок в это время не находится в режиме боя. После окончания боя наблюдается сбой/баг который связан с тем, что бот отказывается садиться на летающего/наземного маунта для дальнейшего следования за игроком. В место этого  (в случае летающего маунта) бот начинает бежать по земле за игроком (игрок в это время на летающем маунте) и агрит всех мобом на своем пути. Как вариант использовалась команда телепорта ботов, но это помогает только на один раз, т.к. при последующем спешивании игрока бот опять отказывается использовать маунта. 

### Expected behaviour

После того как бот отстал по причине боя в мобом и одержал над ним победу он должен использовать маунта (летающий/наземный) и догнать игрока. 
Как вариант было бы не плохо, чтоб мобы не агрились на ботов игрока когда они находятся на маунтах и сами боты не атаковали мобов которые атакуют игрока когда он находится на маунте. Как только игрок спешился с летающего или наземного маунта только тогда бот начинает вступать в бой. 

### Steps to reproduce the problem

1. Сесть на маунта с ботом в пати
2. Пролететь с ботом в зоне агра моба
3. Дождаться когда моб сагрится на бота. 

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

Последний релиз от 22.10.2023

### Operating system

Windows 10

**Comment by Parkan1986** [comment]
У меня такое тоже часто происходило лечилось тем что я дожидался когда боты выйдут из боя и просто сам слез\залез на маунта опять и они возвращаються тоже на маунта

**Comment by trickerer** [comment]
Не могу воспроизвести.
Дожно быть это просто баг системы угрозы с зависанием юнита в режиме битвы.

https://github.com/trickerer/Trinity-Bots/assets/1254989/73c5b353-6a41-42f1-be60-13d810531946
