### ISSUE TITLE
[AC] [Bug] [Core] [1054] Unknown column 'MapID' in 'field list'

### ISSUE THREAD

**Issue by vurtne** [trickerer/Trinity-Bots#698]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

[1054] Unknown column 'MapID' in 'field list'
Your database structure is not up to date. Please make sure you've executed all queries in the sql/updates folders.
Caught signal 6
Segmentation fault (core dumped)

### Expected behaviour

[1054] Unknown column 'MapID' in 'field list'

### Crashlog

[1054] Unknown column 'MapID' in 'field list' Your database structure is not up to date. Please make sure you've executed all queries in the sql/updates folders. Caught signal 6 Segmentation fault (core dumped)

### Steps to reproduce the problem

Saving reports for 1 players.
Saving reports for 1 players.
Saving reports for 1 players.
Saving reports for 1 players.
Command: npcb loo 13 1 [Player: 大臭 (GUID Full: 0x0000000000000015 Type: Player Low: 21) (Account: 3) X: -4925.0234 Y: -958.2457 Z: 501.51328 Map: 0 (Eastern Kingdoms) Area: 1537 (Ironforge) Zone: 1537 (Ironforge) Selected: Shikrik (GUID Full: 0xf130011271000119 Type: Creature Entry: 70257  Low: 281)]
Command: npcb loo 15 1 [Player: 大臭 (GUID Full: 0x0000000000000015 Type: Player Low: 21) (Account: 3) X: -4925.0234 Y: -958.2457 Z: 501.51328 Map: 0 (Eastern Kingdoms) Area: 1537 (Ironforge) Zone: 1537 (Ironforge) Selected: Shikrik (GUID Full: 0xf130011271000119 Type: Creature Entry: 70257  Low: 281)]
Command: npcb sp 70555 [Player: 大臭 (GUID Full: 0x0000000000000015 Type: Player Low: 21) (Account: 3) X: -4925.0234 Y: -958.2457 Z: 501.51328 Map: 0 (Eastern Kingdoms) Area: 1537 (Ironforge) Zone: 1537 (Ironforge) Selected: Shikrik (GUID Full: 0xf130011271000119 Type: Creature Entry: 70257  Low: 281)]
Command: npcb sp 70558 [Player: 大臭 (GUID Full: 0x0000000000000015 Type: Player Low: 21) (Account: 3) X: -4925.7266 Y: -948.5967 Z: 501.56412 Map: 0 (Eastern Kingdoms) Area: 1537 (Ironforge) Zone: 1537 (Ironforge) Selected: Detrae (GUID Full: 0xf13001139b000e46 Type: Creature Entry: 70555  Low: 3654)]
Saving reports for 1 players.
Command: npcb add [Player: 大臭 (GUID Full: 0x0000000000000015 Type: Player Low: 21) (Account: 3) X: -4922.2676 Y: -947.81055 Z: 501.54892 Map: 0 (Eastern Kingdoms) Area: 1537 (Ironforge) Zone: 1537 (Ironforge) Selected: Fearoth (GUID Full: 0xf13001139e000e49 Type: Creature Entry: 70558  Low: 3657)]
Command: npcb add [Player: 大臭 (GUID Full: 0x0000000000000015 Type: Player Low: 21) (Account: 3) X: -4922.2676 Y: -947.81055 Z: 501.54892 Map: 0 (Eastern Kingdoms) Area: 1537 (Ironforge) Zone: 1537 (Ironforge) Selected: Detrae (GUID Full: 0xf13001139b000e46 Type: Creature Entry: 70555  Low: 3654)]
Saving reports for 1 players.
Command: aura 22888 [Player: 大臭 (GUID Full: 0x0000000000000015 Type: Player Low: 21) (Account: 3) X: 1090.9915 Y: -506.10162 Z: -104.21558 Map: 409 (Molten Core) Area: 2717 (Molten Core) Zone: 2717 (Molten Core) Selected: Detrae (GUID Full: 0xf13001139b000e46 Type: Creature Entry: 70555  Low: 3654)]
Command: aura 22988 [Player: 大臭 (GUID Full: 0x0000000000000015 Type: Player Low: 21) (Account: 3) X: 1090.9915 Y: -506.10162 Z: -104.21558 Map: 409 (Molten Core) Area: 2717 (Molten Core) Zone: 2717 (Molten Core) Selected: Detrae (GUID Full: 0xf13001139b000e46 Type: Creature Entry: 70555  Low: 3654)]
Command: aura 22818 [Player: 大臭 (GUID Full: 0x0000000000000015 Type: Player Low: 21) (Account: 3) X: 1090.9915 Y: -506.10162 Z: -104.21558 Map: 409 (Molten Core) Area: 2717 (Molten Core) Zone: 2717 (Molten Core) Selected: Detrae (GUID Full: 0xf13001139b000e46 Type: Creature Entry: 70555  Low: 3654)]
Command: aura 25059 [Player: 大臭 (GUID Full: 0x0000000000000015 Type: Player Low: 21) (Account: 3) X: 1090.9915 Y: -506.10162 Z: -104.21558 Map: 409 (Molten Core) Area: 2717 (Molten Core) Zone: 2717 (Molten Core) Selected: Detrae (GUID Full: 0xf13001139b000e46 Type: Creature Entry: 70555  Low: 3654)]
Command: aura 58054 [Player: 大臭 (GUID Full: 0x0000000000000015 Type: Player Low: 21) (Account: 3) X: 1090.9915 Y: -506.10162 Z: -104.21558 Map: 409 (Molten Core) Area: 2717 (Molten Core) Zone: 2717 (Molten Core) Selected: Detrae (GUID Full: 0xf13001139b000e46 Type: Creature Entry: 70555  Low: 3654)]
Command: aura 58921 [Player: 大臭 (GUID Full: 0x0000000000000015 Type: Player Low: 21) (Account: 3) X: 1090.9915 Y: -506.10162 Z: -104.21558 Map: 409 (Molten Core) Area: 2717 (Molten Core) Zone: 2717 (Molten Core) Selected: Detrae (GUID Full: 0xf13001139b000e46 Type: Creature Entry: 70555  Low: 3654)]
Command: aura 42735 [Player: 大臭 (GUID Full: 0x0000000000000015 Type: Player Low: 21) (Account: 3) X: 1090.9915 Y: -506.10162 Z: -104.21558 Map: 409 (Molten Core) Area: 2717 (Molten Core) Zone: 2717 (Molten Core) Selected: Detrae (GUID Full: 0xf13001139b000e46 Type: Creature Entry: 70555  Low: 3654)]
Command: aura 53758 [Player: 大臭 (GUID Full: 0x0000000000000015 Type: Player Low: 21) (Account: 3) X: 1090.9915 Y: -506.10162 Z: -104.21558 Map: 409 (Molten Core) Area: 2717 (Molten Core) Zone: 2717 (Molten Core) Selected: Detrae (GUID Full: 0xf13001139b000e46 Type: Creature Entry: 70555  Low: 3654)]
Command: aura 53749 [Player: 大臭 (GUID Full: 0x0000000000000015 Type: Player Low: 21) (Account: 3) X: 1090.9915 Y: -506.10162 Z: -104.21558 Map: 409 (Molten Core) Area: 2717 (Molten Core) Zone: 2717 (Molten Core) Selected: Detrae (GUID Full: 0xf13001139b000e46 Type: Creature Entry: 70555  Low: 3654)]
Command: aura 53748 [Player: 大臭 (GUID Full: 0x0000000000000015 Type: Player Low: 21) (Account: 3) X: 1090.9915 Y: -506.10162 Z: -104.21558 Map: 409 (Molten Core) Area: 2717 (Molten Core) Zone: 2717 (Molten Core) Selected: Detrae (GUID Full: 0xf13001139b000e46 Type: Creature Entry: 70555  Low: 3654)]
Command: aura 53760 [Player: 大臭 (GUID Full: 0x0000000000000015 Type: Player Low: 21) (Account: 3) X: 1090.9915 Y: -506.10162 Z: -104.21558 Map: 409 (Molten Core) Area: 2717 (Molten Core) Zone: 2717 (Molten Core) Selected: Detrae (GUID Full: 0xf13001139b000e46 Type: Creature Entry: 70555  Low: 3654)]
Command: aura 57623 [Player: 大臭 (GUID Full: 0x0000000000000015 Type: Player Low: 21) (Account: 3) X: 1090.9915 Y: -506.10162 Z: -104.21558 Map: 409 (Molten Core) Area: 2717 (Molten Core) Zone: 2717 (Molten Core) Selected: Detrae (GUID Full: 0xf13001139b000e46 Type: Creature Entry: 70555  Low: 3654)]
Command: aura 57371 [Player: 大臭 (GUID Full: 0x0000000000000015 Type: Player Low: 21) (Account: 3) X: 1090.9915 Y: -506.10162 Z: -104.21558 Map: 409 (Molten Core) Area: 2717 (Molten Core) Zone: 2717 (Molten Core) Selected: Detrae (GUID Full: 0xf13001139b000e46 Type: Creature Entry: 70555  Low: 3654)]
Command: aura 48469 [Player: 大臭 (GUID Full: 0x0000000000000015 Type: Player Low: 21) (Account: 3) X: 1090.9915 Y: -506.10162 Z: -104.21558 Map: 409 (Molten Core) Area: 2717 (Molten Core) Zone: 2717 (Molten Core) Selected: Detrae (GUID Full: 0xf13001139b000e46 Type: Creature Entry: 70555  Low: 3654)]
Command: aura 24425 [Player: 大臭 (GUID Full: 0x0000000000000015 Type: Player Low: 21) (Account: 3) X: 1090.9915 Y: -506.10162 Z: -104.21558 Map: 409 (Molten Core) Area: 2717 (Molten Core) Zone: 2717 (Molten Core) Selected: Detrae (GUID Full: 0xf13001139b000e46 Type: Creature Entry: 70555  Low: 3654)]
Command: aura 16609 [Player: 大臭 (GUID Full: 0x0000000000000015 Type: Player Low: 21) (Account: 3) X: 1090.9915 Y: -506.10162 Z: -104.21558 Map: 409 (Molten Core) Area: 2717 (Molten Core) Zone: 2717 (Molten Core) Selected: Detrae (GUID Full: 0xf13001139b000e46 Type: Creature Entry: 70555  Low: 3654)]
Command: aura 22817 [Player: 大臭 (GUID Full: 0x0000000000000015 Type: Player Low: 21) (Account: 3) X: 1090.9915 Y: -506.10162 Z: -104.21558 Map: 409 (Molten Core) Area: 2717 (Molten Core) Zone: 2717 (Molten Core) Selected: Detrae (GUID Full: 0xf13001139b000e46 Type: Creature Entry: 70555  Low: 3654)]
Command: aura 15366 [Player: 大臭 (GUID Full: 0x0000000000000015 Type: Player Low: 21) (Account: 3) X: 1090.9915 Y: -506.10162 Z: -104.21558 Map: 409 (Molten Core) Area: 2717 (Molten Core) Zone: 2717 (Molten Core) Selected: Detrae (GUID Full: 0xf13001139b000e46 Type: Creature Entry: 70555  Low: 3654)]
Command: aura 19506 [Player: 大臭 (GUID Full: 0x0000000000000015 Type: Player Low: 21) (Account: 3) X: 1090.9915 Y: -506.10162 Z: -104.21558 Map: 409 (Molten Core) Area: 2717 (Molten Core) Zone: 2717 (Molten Core) Selected: Detrae (GUID Full: 0xf13001139b000e46 Type: Creature Entry: 70555  Low: 3654)]
Command: aura 22888 [Player: 大臭 (GUID Full: 0x0000000000000015 Type: Player Low: 21) (Account: 3) X: 1090.9915 Y: -506.10162 Z: -104.21558 Map: 409 (Molten Core) Area: 2717 (Molten Core) Zone: 2717 (Molten Core) Selected: 大臭 (GUID Full: 0x0000000000000015 Type: Player Low: 21)]
Command: aura 22988 [Player: 大臭 (GUID Full: 0x0000000000000015 Type: Player Low: 21) (Account: 3) X: 1090.9915 Y: -506.10162 Z: -104.21558 Map: 409 (Molten Core) Area: 2717 (Molten Core) Zone: 2717 (Molten Core) Selected: 大臭 (GUID Full: 0x0000000000000015 Type: Player Low: 21)]
Command: aura 22818 [Player: 大臭 (GUID Full: 0x0000000000000015 Type: Player Low: 21) (Account: 3) X: 1090.9915 Y: -506.10162 Z: -104.21558 Map: 409 (Molten Core) Area: 2717 (Molten Core) Zone: 2717 (Molten Core) Selected: 大臭 (GUID Full: 0x0000000000000015 Type: Player Low: 21)]
Command: aura 25059 [Player: 大臭 (GUID Full: 0x0000000000000015 Type: Player Low: 21) (Account: 3) X: 1090.9915 Y: -506.10162 Z: -104.21558 Map: 409 (Molten Core) Area: 2717 (Molten Core) Zone: 2717 (Molten Core) Selected: 大臭 (GUID Full: 0x0000000000000015 Type: Player Low: 21)]
Command: aura 58054 [Player: 大臭 (GUID Full: 0x0000000000000015 Type: Player Low: 21) (Account: 3) X: 1090.9915 Y: -506.10162 Z: -104.21558 Map: 409 (Molten Core) Area: 2717 (Molten Core) Zone: 2717 (Molten Core) Selected: 大臭 (GUID Full: 0x0000000000000015 Type: Player Low: 21)]
Command: aura 58921 [Player: 大臭 (GUID Full: 0x0000000000000015 Type: Player Low: 21) (Account: 3) X: 1090.9915 Y: -506.10162 Z: -104.21558 Map: 409 (Molten Core) Area: 2717 (Molten Core) Zone: 2717 (Molten Core) Selected: 大臭 (GUID Full: 0x0000000000000015 Type: Player Low: 21)]
Command: aura 42735 [Player: 大臭 (GUID Full: 0x0000000000000015 Type: Player Low: 21) (Account: 3) X: 1090.9915 Y: -506.10162 Z: -104.21558 Map: 409 (Molten Core) Area: 2717 (Molten Core) Zone: 2717 (Molten Core) Selected: 大臭 (GUID Full: 0x0000000000000015 Type: Player Low: 21)]
Command: aura 53758 [Player: 大臭 (GUID Full: 0x0000000000000015 Type: Player Low: 21) (Account: 3) X: 1090.9915 Y: -506.10162 Z: -104.21558 Map: 409 (Molten Core) Area: 2717 (Molten Core) Zone: 2717 (Molten Core) Selected: 大臭 (GUID Full: 0x0000000000000015 Type: Player Low: 21)]
Command: aura 53749 [Player: 大臭 (GUID Full: 0x0000000000000015 Type: Player Low: 21) (Account: 3) X: 1090.9915 Y: -506.10162 Z: -104.21558 Map: 409 (Molten Core) Area: 2717 (Molten Core) Zone: 2717 (Molten Core) Selected: 大臭 (GUID Full: 0x0000000000000015 Type: Player Low: 21)]
Command: aura 53748 [Player: 大臭 (GUID Full: 0x0000000000000015 Type: Player Low: 21) (Account: 3) X: 1090.9915 Y: -506.10162 Z: -104.21558 Map: 409 (Molten Core) Area: 2717 (Molten Core) Zone: 2717 (Molten Core) Selected: 大臭 (GUID Full: 0x0000000000000015 Type: Player Low: 21)]
Command: aura 53760 [Player: 大臭 (GUID Full: 0x0000000000000015 Type: Player Low: 21) (Account: 3) X: 1090.9915 Y: -506.10162 Z: -104.21558 Map: 409 (Molten Core) Area: 2717 (Molten Core) Zone: 2717 (Molten Core) Selected: 大臭 (GUID Full: 0x0000000000000015 Type: Player Low: 21)]
Command: aura 57623 [Player: 大臭 (GUID Full: 0x0000000000000015 Type: Player Low: 21) (Account: 3) X: 1090.9915 Y: -506.10162 Z: -104.21558 Map: 409 (Molten Core) Area: 2717 (Molten Core) Zone: 2717 (Molten Core) Selected: 大臭 (GUID Full: 0x0000000000000015 Type: Player Low: 21)]
Command: aura 57371 [Player: 大臭 (GUID Full: 0x0000000000000015 Type: Player Low: 21) (Account: 3) X: 1090.9915 Y: -506.10162 Z: -104.21558 Map: 409 (Molten Core) Area: 2717 (Molten Core) Zone: 2717 (Molten Core) Selected: 大臭 (GUID Full: 0x0000000000000015 Type: Player Low: 21)]
Command: aura 48469 [Player: 大臭 (GUID Full: 0x0000000000000015 Type: Player Low: 21) (Account: 3) X: 1090.9915 Y: -506.10162 Z: -104.21558 Map: 409 (Molten Core) Area: 2717 (Molten Core) Zone: 2717 (Molten Core) Selected: 大臭 (GUID Full: 0x0000000000000015 Type: Player Low: 21)]
Command: aura 24425 [Player: 大臭 (GUID Full: 0x0000000000000015 Type: Player Low: 21) (Account: 3) X: 1090.9915 Y: -506.10162 Z: -104.21558 Map: 409 (Molten Core) Area: 2717 (Molten Core) Zone: 2717 (Molten Core) Selected: 大臭 (GUID Full: 0x0000000000000015 Type: Player Low: 21)]
Command: aura 16609 [Player: 大臭 (GUID Full: 0x0000000000000015 Type: Player Low: 21) (Account: 3) X: 1090.9915 Y: -506.10162 Z: -104.21558 Map: 409 (Molten Core) Area: 2717 (Molten Core) Zone: 2717 (Molten Core) Selected: 大臭 (GUID Full: 0x0000000000000015 Type: Player Low: 21)]
Command: aura 22817 [Player: 大臭 (GUID Full: 0x0000000000000015 Type: Player Low: 21) (Account: 3) X: 1090.9915 Y: -506.10162 Z: -104.21558 Map: 409 (Molten Core) Area: 2717 (Molten Core) Zone: 2717 (Molten Core) Selected: 大臭 (GUID Full: 0x0000000000000015 Type: Player Low: 21)]
Command: aura 15366 [Player: 大臭 (GUID Full: 0x0000000000000015 Type: Player Low: 21) (Account: 3) X: 1090.9915 Y: -506.10162 Z: -104.21558 Map: 409 (Molten Core) Area: 2717 (Molten Core) Zone: 2717 (Molten Core) Selected: 大臭 (GUID Full: 0x0000000000000015 Type: Player Low: 21)]
Command: aura 19506 [Player: 大臭 (GUID Full: 0x0000000000000015 Type: Player Low: 21) (Account: 3) X: 1090.9915 Y: -506.10162 Z: -104.21558 Map: 409 (Molten Core) Area: 2717 (Molten Core) Zone: 2717 (Molten Core) Selected: 大臭 (GUID Full: 0x0000000000000015 Type: Player Low: 21)]
Saving reports for 1 players.
Saving reports for 1 players.
Ping MySQL to keep connection alive
Saving reports for 1 players.
Saving reports for 1 players.
[1054] Unknown column 'MapID' in 'field list'
Your database structure is not up to date. Please make sure you've executed all queries in the sql/updates folders.
Caught signal 6
Segmentation fault (core dumped)

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. de00b639b324+ 2023-10-22 07:59:05 +0700 (npcbots_3.3.5 branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon)

### Operating system

Ubuntu22.04

**Comment by vurtne** [comment]
The problem is: After killing the boss in the replica, the server reports an error, indicating that it is indeed a Mapid

**Comment by trickerer** [comment]
Build in debug mode and post a crashlog. The issue is probably in one of the modules (if you use them).

**Comment by vurtne** [comment]
Thank you, teacher. It's been a long time since there was an update and it's been stuck on October 22nd。

**Comment by trickerer** [comment]
https://github.com/trickerer/Trinity-Bots/commit/5da5b7193a8f79587e9db44b5a589d45278162e6
