### ISSUE TITLE
[AC] [Bug] [dump load] Error "unknown table `characters_npcbot`" when loading dump file 

### ISSUE THREAD

**Issue by robertocsjr** [trickerer/Trinity-Bots#699]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Whenever I try to load a sql file with npcbot dump load <file> command, I get a "unknown table `characters_npcbot`" error.

> npcbot dump load bots_dump.sql
>  at line 4: unknown table `characters_npcbot`
> File data integrity check failed!

In my db, the table exists and is empty

> mysql> select * from acore_characters.characters_npcbot;
> Empty set (0.00 sec)

[bots_dump.zip](https://github.com/trickerer/Trinity-Bots/files/13547894/bots_dump.zip)

### Steps to reproduce the problem

1) Create dump using npcbot dump write <filename> on previous server
2) Copy file to new server Bin folder
3) Execute npcbot dump load <filename> on new server
4) Error ocurs

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. de00b639b324+ 2023-10-22 07:59:05 +0700 (npcbots_3.3.5 branch) (Unix, Release, Static)

### Operating system

Ubuntu 22.4 64 bits

**Comment by trickerer** [comment]
Try to change line endings to Unix format before importing.

I don't imagine it being a difference in `std::string` `substr()` method implementation which is being used to extract table name from the line.

**Comment by robertocsjr** [comment]
That was it, I changed the file type to unix using :

`awk '{ sub("\r$", ""); print }' bot_dump> bot_dump_unix`

And it worked.
Thank you very much!
