### ISSUE TITLE
DB errros

### ISSUE THREAD

**Issue by oldmagic** [trickerer/Trinity-Bots#7]
ScriptName 'warrior_bot' exists in database, but no core script found!
ScriptName 'spellbreaker_bot' exists in database, but no core script found!
ScriptName 'sphynx_bot' exists in database, but no core script found!
ScriptName 'warlock_bot' exists in database, but no core script found!
ScriptName 'rogue_bot' exists in database, but no core script found!
ScriptName 'paladin_bot' exists in database, but no core script found!
ScriptName 'shaman_bot' exists in database, but no core script found!
ScriptName 'warlock_pet_bot' exists in database, but no core script found!
ScriptName 'shaman_pet_bot' exists in database, but no core script found!
ScriptName 'mage_bot' exists in database, but no core script found!
ScriptName 'hunter_pet_bot' exists in database, but no core script found!
ScriptName 'hunter_bot' exists in database, but no core script found!
ScriptName 'druid_pet_bot' exists in database, but no core script found!
ScriptName 'druid_bot' exists in database, but no core script found!
ScriptName 'dreadlord_pet_bot' exists in database, but no core script found!
ScriptName 'dreadlord_bot' exists in database, but no core script found!
ScriptName 'death_knight_bot' exists in database, but no core script found!
ScriptName 'dark_ranger_pet_bot' exists in database, but no core script found!
ScriptName 'priest_pet_bot' exists in database, but no core script found!
ScriptName 'mage_pet_bot' exists in database, but no core script found!
ScriptName 'deathknight_pet_bot' exists in database, but no core script found!
ScriptName 'dark_ranger_bot' exists in database, but no core script found!
ScriptName 'priest_bot' exists in database, but no core script found!
ScriptName 'blademaster_bot' exists in database, but no core script found!
ScriptName 'archmage_pet_bot' exists in database, but no core script found!
ScriptName 'archmage_bot' exists in database, but no core script found!

Is this normal?

**Comment by itdevsteve** [comment]
Did you run all 6 SQL scripts?

**Comment by oldmagic** [comment]
Yes i have!

https://pastebin.com/guB1iNFu

**Comment by itdevsteve** [comment]
Not sure where you are getting those issues, I don't see them on server startup nor do I see any kind of log file with them in it.

**Comment by ROBERTCABRERA** [comment]
Apply SQL update files from /TrinityCore/sql/Bots/updates to your DB

**Comment by itdevsteve** [comment]
Just one last piece, it looks like the database is seeing your entries, but the server code is not.  Did you run a "make install" to the right destination folder after the "make" ran?

You should be setting your server directory with your cmake command, for example:

```
cmake ../ -DCMAKE_INSTALL_PREFIX=/home/trinity/server
```

So that when it installs, it installs the binaries in the correct place.

**Comment by oldmagic** [comment]
Yes i did :)

**Comment by trickerer** [comment]
Patch did not apply or you forgot to re-run CMake it seems.

**Comment by oldmagic** [comment]
I'll do a totalt doover and see what happens!
