### ISSUE TITLE
Feature Request when using Auto-Equip

### ISSUE THREAD

**Issue by cherbert** [trickerer/Trinity-Bots#70]
I don't even know if this is possible but I'll ask... I'm going to assume it's a frontend client issue so I wonder if a custom Addon is what is needed.

When you are talking to an NPC and you select Manage Equipment -> Auto Equip is it possible for you to show a pop-up of the item stat box when the mouse rolls over the item much like it does when you roll over items in the chat box?

I have found it's such a pain in the arse to compare items you have in your inventory against items equipped by your bot and trying to ascertain if you have better gear over what they already have. If you could examine the stats for items by rolling over the list that Auto-Equip generates this would make things so much easier that having to go through looking for them all in your bags.

**Comment by trickerer** [comment]
Unfortunately, client can't show tooltips for gossip menu fields. You need an addon that will hook mouse hover over gossip menu or right click or something.

The only thing I can do is to send those item links in chat with whisper message, but then they clutter you chat and are partially blocked with the same gossip menu. I just can't see any really good way of going about this.

**Comment by cherbert** [comment]
How about sending them to the Loot/Trade chat window?

**Comment by trickerer** [comment]
Implemented functionality requires to be supported by standard client. Separate chat windows in 3.3.5 are only available via addons.
