### ISSUE TITLE
[TC] [AC] [Bug] [Core] Autobalance For NPC Bots issue

### ISSUE THREAD

**Issue by jakatangkir** [trickerer/Trinity-Bots#700]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Autobalance is used for balancing dungeons & raids, the current behaviour was:

Raid bosses, dungeon bosses, elite creatures that included within the autobalance that has mana will be automatically being out of mana after a player logging in.

Note: I was using lastest version of https://github.com/trickerer/mod-autobalance

### Expected behaviour

The mob should not lose all mana while a random player join within encounter of a mob or bosses

### Crashlog

N/A

### Steps to reproduce the problem

1. A Player Doing Raid Bosses / Dungeon Boss (In Encounter Status)
2. The mobs has mana
3. A random player logging in within the world
4. Target's Mana is moddified to 0, ex: 0/341K (So Out of mana)

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. 4699f0429a86+ 2023-08-13 19:17:15 +0700 (npcbots_3.3.5 branch) (Win64, Release, Static)

### Operating system

Win Server 2019

**Comment by trickerer** [comment]
After original repo big update merge it seems to be fixed
