### ISSUE TITLE
[TC] [AC] [Question/Feature] [Group/Spell/Core] Does Dungeon Finder work?

### ISSUE THREAD

**Issue by nugsforthugs** [trickerer/Trinity-Bots#702]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Been looking all over the internet and decided to stop in for the official response, does Dungeon Finder work? I try to queue and nothing happens, obviously works fine with a group I make but it doesn't generate random bot groups it seems.

Is this a bug? I have it enabled in the WS config for Dungeonfinder = 1 but not seeing any random bots queueing,

Thanks!

### TrinityCore or AzerothCore

AzerothCore

**Comment by trickerer** [comment]
No, there is no random npcbots generation for Dungeon Finder.

**Comment by nugsforthugs** [comment]
> No, there is no random npcbots generation for Dungeon Finder.

Thank you for replying, was driving me nuts trying to figure it out.

**Comment by icemansparks** [comment]
using soloLFG mod and manually spawned / hired bots, this works just fine :)

**Comment by blinkysc** [comment]
> using soloLFG mod and manually spawned / hired bots, this works just fine :)

Didn't work for me =/ mine shows cannot spawn bots in instances
