### ISSUE TITLE
[AC] [Question/Feature] [Core] Is it possible to have NPCbots match player level when joining BGs (or possibly all time)?

### ISSUE THREAD

**Issue by icemansparks** [trickerer/Trinity-Bots#704]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Playing battlegrounds is much more fun when you do not encounter bots 7-9 levels higher than yourself. The issue is generally caused by blizzards bracket system.
A possible solution using NPCBots would be to have the bots (same side and opposite side) all match the player level upon entering the Battleground.
Would this be possible?

### TrinityCore or AzerothCore

AzerothCore

**Comment by trickerer** [comment]
This may only be an optional feature - bots matching level of the first player (triggering bots' generation).

NPCBots project's main target is small servers (not single player or medium+), so more than one player is expected to join BG / raid / etc., and it may be still (dis)advantageous for additional BG players if such feature is enabled by default. Also, if there is only one player then real disadvantage exists only for that player - BG teams will remain pretty much balanced level-wise, at average; that's how I see it as a developer of course.

**Comment by icemansparks** [comment]
Thanks for the response, i definitely can relate to the developer viewpoint as well. As you guessed, my usecase would be solo or small group play were it would not affect many other players badly - but you are absolutely right that it would cause problems for servers with players of a wider variety of levels.
It would still be great, if it will be an optional feature at some point. 👍
