### ISSUE TITLE
Feature request:Improve Auto-equip options

### ISSUE THREAD

**Issue by Parkan1986** [trickerer/Trinity-Bots#71]
Суть запроса такова:
В режиме диалога с нпсботом функция auto-equip в данный момент выбирает предметы по уровню предмета(когда раньше было еще то что влияло еще и качество предмета,но это довольно часто приводило к круговороту вещей в этом режиме,что сбивало с толку).
Сейчас у меня есть еще одно предложение как еще лучше можно реализовать работу данной функции:
Сделать выбор предметов по сумме полезных характеристик предмета(при этом брать только бонусные параметры типа сила,ловкость и тд,не смотреть в сторону урона у оружия и показателя брони у одежды).К примеру одев бота в какой-нибудь тир2 и потом пойдя делать квесты в аутленд,многие вещи которые заметно слабее,но выше уровнем предмета чем шмотки тир2,довольно часто можно ошибиться и одеть нпсботу предмет явно хуже одетого.
По возможности вывести в файл конфигурации режим работы auto-equip где было бы на выбор либо по уровню предмета,либо по сумме полезных характеристик,ну либо еще какой-нибудь другой вариант работы этой функции.

**Comment by trickerer** [comment]
If you want to suggest your own stats weights you can look up the stats in botcommon.h::L966-L1023
