### ISSUE TITLE
[TC] [AC] [Bug/Crash] [Group/Spell/Core] Druid Tank won't use Feral Charge

### ISSUE THREAD

**Issue by IDUnknownSoldier** [trickerer/Trinity-Bots#717]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Hired Druid bot set to "feral" talents, does not use "Feral Charge"

### Expected behaviour

Druid bot set to "feral" talents should use or have "feral charge" available to cast.

### Steps to reproduce the problem

1) Hire Druid Bot
2) Set Talents to "Feral"
3) xp or quest until level 10 (druid unlock for feral charge)
4) Confirm NPCbot is level 10.   
Have druid role set to Tank/DPS

Druid will not use "feral charge"

### TrinityCore or AzerothCore

Both

### Core rev. hash/commit

AzerothCore rev. a8c1768722c7+ 2023-12-23 18:05:24 -0700 (npcbots_3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

**Comment by Grimfeather** [comment]
Feral charge requires level 20. not 10.
