### ISSUE TITLE
[AC] [Bug] Roaming Bot Decay over Time

### ISSUE THREAD

**Issue by StraysFromPath** [trickerer/Trinity-Bots#718]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

When I launch the server there are random bots running everywhere (intended behaviour: good).

If the server stays up for more than 2-3 days the bots slowly start to disappear.

After 6-7 days there are zero roaming bots to be found.

### Expected behaviour

Bots should be similar regardless of server uptime.

### Steps to reproduce the problem

Enable wandering bots.

Leave a server up for a long duration.

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

10th december azerothcore 

### Operating system

win10

**Comment by trickerer** [comment]
Wandering bots shouldn't get despawned or anything like that. If you don't see them they have to congregate somewhere. Use `.npcbot list spawned` to check bots' locations. I think bots eventually just get to level up enough to leave low-level zones and later mid-level zones as well

**Comment by StraysFromPath** [comment]
> Wandering bots shouldn't get despawned or anything like that. If you don't see them they have to congregate somewhere. Use `.npcbot list spawned` to check bots' locations. I think bots eventually just get to level up enough to leave low-level zones and later mid-level zones as well

You're 100% right. I checked and after 6 days of uptime every bot hit my server's level cap (60).

I have in the config this setting: 

#
#    NpcBot.WanderingBots.Continents.Levels
#        Description: Percentage of wandering bots to spawn per level bracket:
#                     0-9, 10-19, 20,29, ... , 70-79, 80+.
#        Note:        Total percentage must be exactly 100.
#        Note2:       Classes with minimum level requirement may ignore this parameter.
#        Default:     25,15,15,10,5,10,20,0,0

NpcBot.WanderingBots.Continents.Levels = 20,25,25,25,5,0,0,0,0

But based on the current distribution after time it is now:

0,0,0,0,0,100,0,0,0

Could we add functionality to ensure that there's always a certain distribution of bots as determined by this config setting?

Something that just resets a bot back to its "starting level" when it hits max?

or maybe even an option to disable bot XP gain entirely might be the easiest implementation option for this?

**Comment by trickerer** [comment]
> or maybe even an option to disable bot XP gain entirely might be the easiest implementation option for this?

Yes this one is the easiest

**Comment by Parkan1986** [comment]
> > or maybe even an option to disable bot XP gain entirely might be the easiest implementation option for this?
> 
> Yes this one is the easiest

А как на счет добавить возможность менять скорость их прокачки от типа  от 1.0 до 20.0 ?Например не все игроки будут держать сервак неделю аптайма.А перезагружают его раз день в два или в течении дня по несколько раз.Я бы наоборот ставил значения по умолчанию а потом смотрел как боты развиваются в течении игровой сессии.Ну или до периода пока сервак не выключиться или не перезагрузят его.

**Comment by trickerer** [comment]
> > > or maybe even an option to disable bot XP gain entirely might be the easiest implementation option for this?
> > 
> > 
> > Yes this one is the easiest
> 
> А как на счет добавить возможность менять скорость их прокачки от типа от 1.0 до 20.0 ?Например не все игроки будут держать сервак неделю аптайма.А перезагружают его раз день в два или в течении дня по несколько раз.Я бы наоборот ставил значения по умолчанию а потом смотрел как боты развиваются в течении игровой сессии.Ну или до периода пока сервак не выключиться или не перезагрузят его.

Тогда уж от 0.0

**Comment by Parkan1986** [comment]
> > > > or maybe even an option to disable bot XP gain entirely might be the easiest implementation option for this?
> > > 
> > > 
> > > Yes this one is the easiest
> > 
> > 
> > А как на счет добавить возможность менять скорость их прокачки от типа от 1.0 до 20.0 ?Например не все игроки будут держать сервак неделю аптайма.А перезагружают его раз день в два или в течении дня по несколько раз.Я бы наоборот ставил значения по умолчанию а потом смотрел как боты развиваются в течении игровой сессии.Ну или до периода пока сервак не выключиться или не перезагрузят его.
> 
> Тогда уж от 0.0

Тоже верно.
