### ISSUE TITLE
Enhancement - Rogue Assassination improvement

### ISSUE THREAD

**Issue by Ryu1254** [trickerer/Trinity-Bots#72]
Rogue in general is very good for raiding
but I notice something for Rogue Assassination spec, they don't use Envenom skill??
I don't see that skill in any ability control..

can you implement it?
here what I found for rogue assassination spec:

1. You need to keep up your Hunger For Blood (HFB) all the time(8% dps increase).
2. Keep up the Slice and Dice (SND). This part is easy because every time you cast Envenom your SND gets instantly back to maximum buff time which means you only need to apply this buff once at the start and never use it again when you're in combat. This awesome thing comes from your talent tree called as Cut to the Chase .
3. Try to time your Envenom . Don't spam it. Use this only when the last one runs out. Use Envenom only with 4 or 5 combo points.

**Comment by trickerer** [comment]
Does this require instant poison priority (at least for one hand)? Not sure about PvE vs PvP here.

**Comment by Ryu1254** [comment]
yes, it does require poison,
Main hand – 1.8 with Instant Poison IX. 
Offhand – 1.4 with Deadly Poison IX
