### ISSUE TITLE
[TC] [AC] [Question/Feature] [Group/Spell/Core] TrinityCore Retail Branch support

### ISSUE THREAD

**Issue by Aztec2012** [trickerer/Trinity-Bots#720]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Is any chance to adding support for TrinityCore Retail Branch? I know that the similar system works on Legion in SPP project.

### TrinityCore or AzerothCore

TrinityCore

**Comment by trickerer** [comment]
#472
#361
