### ISSUE TITLE
[AC] [Feature] [Core] Bots not giving XP on kill with the option Battleground.GiveXPForKills enabled.

### ISSUE THREAD

**Issue by Twiggstar** [trickerer/Trinity-Bots#721]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

As said in the title. I understand it's because they aren't considered as a player. The original feature is working correctly for players. It would be a great to have it at least as a feature for bots as well.

**Additional context**
With addition to no XP given as the bots are not considered real players. Their bars aren't colored to the class with the option "Class color on nameplates" turned on. There has to be some way to trick the server to think they are visually players. Or what class they display.

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

38fc22da375a20861b9ea8a85d9789c3df183ab7

### Operating system

Win10

**Comment by whipowill** [comment]
I can confirm this issue.  Also on AzerothCore.

I had to turn on NPC Names in my interface to see friend/foe distinction, and when clicking on an NPC it won't tell me their class, rather it presents their name as their class.
