### ISSUE TITLE
[TC] [Crash] [Core] Core crashing sometimes

### ISSUE THREAD

**Issue by DykeRz** [trickerer/Trinity-Bots#722]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Core crashing sometimes

### Crashlog

https://gist.github.com/DykeRz/480299b534d105bd234cdda07887095c

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

last

### Operating system

debian 11

**Comment by trickerer** [comment]
You're using tons of custom content, crash happened in custom created map 1116 "Draenor" which is for some reason considered being BG.

You're lucky I have similar report elsewhere, otherwise this would've been rejected.

**Comment by DykeRz** [comment]
any fixes?

**Comment by trickerer** [comment]
You may try a tempfix. At botmgr.cpp line 984 add an additional check:
```c++
else if (currMap->IsBattleground())
```
to
```c++
else if (currMap->IsBattleground() && _owner->GetBattleground())
```
you can do the same for line 986

**Comment by DykeRz** [comment]
ok thank you

**Comment by DykeRz** [comment]
again crash

https://gist.github.com/DykeRz/0e486c5821b4c2af742771690d80209f

**Comment by trickerer** [comment]
That's a completely different crash without anything even vaguely bot-related, all it says is core crashed in some instance map at transport update with one passenger which seems to have its pointer invalidated.
