### ISSUE TITLE
[AC] [Question] [Core] Install Question RE characters DB

### ISSUE THREAD

**Issue by whipowill** [trickerer/Trinity-Bots#723]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Question has to do with installing from your AzerothCore fork.  I already have characters, so I am erasing the world DB only.  

After I install your fork, it errors out bc it can't find the npc transmog table.  I am thinking this is bc on world boot, the characters db already exists, so it doesn't run those migrations.  Which migrations might I need to run manually, so I can preserve my existing characters?

Another possibility is that the schema of your forked AzerothCore database is different than the current AzerothCore database, which would make preserving existing characters even more difficult.

### TrinityCore or AzerothCore

AzerothCore

### Operating system

Ubuntu

**Comment by trickerer** [comment]
Yes indeed, it is expected that bots will be installed along with fresh DB.
To update characters DB with bots tables manually you need to run all 4 'npcbot' SQL files from `/data/sql/base/db_characters/` folder. You can't miss them, their names all start with `characters_npcbot_`.
If you run into errors with world DB bot tables let me know.

**Comment by whipowill** [comment]
This worked perfectly, thank you.
