### ISSUE TITLE
[AC] [Question] [Core] Question About Gear Selection in BG

### ISSUE THREAD

**Issue by whipowill** [trickerer/Trinity-Bots#726]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Question about gear selection in BG.  The bots seems to be very OP and I'm wondering if it's due to them equipping TBC gear on my server which is set to vanilla only with max level of 60.  If that is the case, how might I solve?  Is there a way to remove expansion gear from the database?

### TrinityCore or AzerothCore

AzerothCore

**Comment by trickerer** [comment]
The easiest way to balance bots is to set multipliers for their stats in config.
There is a `creature_template_npcbot_disabled_items` table but making a list of TBC gear is such a hassle.
Also https://github.com/trickerer/Trinity-Bots/issues/692

**Comment by whipowill** [comment]
I assume the multiplier config vars stack with each other?  Referring to these:

```
NpcBot.Mult.Damage.Physical
NpcBot.Mult.Damage.Spell
NpcBot.Mult.Healing
NpcBot.Mult.HP
...
NpcBot.Mult.Damage.Levels
```

So ``Physical`` might nuke their dmg by 50%, and then ``Levels`` could nuke it by another 50%, resulting in a total 75% cut in dmg (for example).

Thank you for taking the time to address these questions.
