### ISSUE TITLE
[AC] [Feature Request] Better Class Distribution for BG Bots

### ISSUE THREAD

**Issue by StraysFromPath** [trickerer/Trinity-Bots#728]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

I've been enjoying BG bots a lot but they have a habit of doing something like this: 

![image](https://github.com/trickerer/Trinity-Bots/assets/119371540/6a1bfa52-ff26-435c-89f5-c78931261bfb)

Where my team is 5 priests and 2 warriors.

Other comps I've had were -

9 druids.

6 hunts and 1 shaman.

4 mages, 4 warlocks, 1 paladin.

35 rogues in alterac valley on the enemy side.

It'd be nice if the BG bots were soft capped at no more than 2-3(?) of the same class for WSG, and no more than 3-5(?) of the same class for others BGs.

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

jan 1st commit acore

### Operating system

win10

**Comment by trickerer** [comment]
The situation you describe isn't impossible on a live server, right? I do not cherish the idea of complicating BG bots generation even more than it is right now, so BG bot class balance is unlikely to happen.
What you must understand though is besides RNG BG team composition strongly depends on class availability
- spawned bots (including wandering) can't join BGs
- total number of bots available per class is very unbalanced. There is a ton of Rogues / Hunters / Warriors / Priests, but not so many DKs / Warlocks / Shamans. I'm yet to scratch my head on that one

**Comment by Parkan1986** [comment]
Кстати хотел тоже создать похожу тему по Бг с ботами.И бывали ситуации где например на моей стороне было что то роде 9 пристов,10 хантеров,10 воинов и остальное маги.т.е максимум было 4 класса ботов.Даже при использований дополнений по увеличению кол-ва доступного пула ботов до 11 тысяч и при использовании гуляющих ботов где то около 8-9 тысяч(плюс 320 засапавненных ботов)неучтенного кол-ва должно же нормально хватать для равномерного распределения ботов на БГ.Возможно ли задать какой-то конфиг с тиле распределения ботов для БГ?

**Comment by StraysFromPath** [comment]
> The situation you describe isn't impossible on a live server, right? I do not cherish the idea of complicating BG bots generation even more than it is right now, so BG bot class balance is unlikely to happen. What you must understand though is besides RNG BG team composition strongly depends on class availability
> 
>     * spawned bots (including wandering) can't join BGs
> 
>     * total number of bots available per class is very unbalanced. There is a ton of Rogues / Hunters / Warriors / Priests, but not so many DKs / Warlocks / Shamans. I'm yet to scratch my head on that one

Ty for the reply. I am loving this module to death.

It's not impossible for a live server to have weird games like 9 rogues in WSG but I'd guess that 85-90% of live server games have mixed balanced classes.

I'd guess that 25-30% of trinity bots games have mixed balanced classes. Last night I had an alterac valley with 26 priests and 11 warriors.

Even if it chose at complete random it would be more likely to produce better games.

Maybe it is possibly related to class_ID as the most prevelant classes are;

Warrior (ID1)
Paladin (ID2)
Hunter (ID4)
Rogue (ID8)
Priest (ID16)

with almost zero

DK (ID32)
Shaman (ID64)
Mage (ID128)
Warlock (ID256)
Druid (ID1024) - I have personally never seen a druid in a bg and me and my friends have run about 100 games.

If they're joining in ChrClassID order it could explain the distribution?

It doesn't have to be perfect even if it's a little hackfixy.

Maybe a workaround like let us run a commant or use the in-game votekick/report afk feature to remove excess bots from the BG and the bots will replenish/join with new bots? That way you can votekick the extras.

**Comment by StraysFromPath** [comment]
![image](https://github.com/trickerer/Trinity-Bots/assets/119371540/876f9904-f487-4456-82d3-5a1a332dd700)

 17 priests ;-;

**Comment by Day36512** [comment]
If players have added additional wandering bots to their database, upwards of like 3k, distribution goes out the window. 1.5k is about the sweet spot to have even class distribution.

**Comment by trickerer** [comment]
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/8d85657ea484bc168b4e85a9949ddf6e845b3fc0
From what I've researched it looks like actual RNG algorithm is kinda flawed when it comes to generating multiple random numbers on a same tick and/or for smaller ranges (in our case 1...21 or so) so instead I decided to change the bot pick randomization approach. I see no difference in-game but maybe you will.

**Comment by trickerer** [comment]
https://github.com/trickerer/Trinity-Bots/commit/dd5e5cf59b39d8254edbf1417a5166251eaa9547
