### ISSUE TITLE
[AC] [Question/Feature] [Core] Prioritize NoDPSTargetIcons for CC

### ISSUE THREAD

**Issue by SuzumiK** [trickerer/Trinity-Bots#729]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Hi there, and thanks for all your work!

I wondered whether it would be possible to have bots prioritize targets market with a NoDPS icon for crowd control spells. I noticed at Garr that warlocks would banish unmarked targets although I had two Firesworn explicitly marked as No DPS. I imagine this would also come in handy in heroic dungeons.

Thanks!

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

azerothcore-wotlk-with-npcbots 38fc22da375a20861b9ea8a85d9789c3df183ab7 merged into azerothcore-master

### Operating system

Win10

**Comment by trickerer** [comment]
Sure, it could be done. But it will only be a soft priority, I'm not making bots ignore all other valid targets if prioritized unit is out of range or something, as for single-target spells when some other target is already affected... we'll see (polymorph, banish, etc.)
