### ISSUE TITLE
[Development / Poll] Repository Conversion

### ISSUE THREAD

**Issue by trickerer** [trickerer/Trinity-Bots#73]
Currently this repository only contains patches / sql files.

To improve development and contribution experience this repository is probably better to be converted to normal source.

The plan is:

- [ ] Drop 2013 version
- [ ] Move patch and sqls to downloads / releases
- [ ] Upload a certain patched TrinityCore revision and go from there

This change may be dicussed for 2 months from now and is planned to be pushed in bulk around 31 March 2021.

I presume most of you don't have anything against these, so I want you to leave a comment if you are **against** any of the proposed changes.

**Comment by Parkan1986** [comment]
Значит ли это что тем кому интересно развитие Вашего мода смогут использовать мод как уже встроенного в сорсы тринитикор, так и отдельно как было в прошлом использовать патчи на установку на свои сорсы тринитикор? 

Поправьте меня, если я не верно понял.

**Comment by trickerer** [comment]
> Значит ли это что тем кому интересно развитие Вашего мода смогут использовать мод как уже встроенного в сорсы тринитикор, так и отдельно как было в прошлом использовать патчи на установку на свои сорсы тринитикор?
> 
> Поправьте меня, если я не верно понял.

Всё верно

**Comment by Parkan1986** [comment]
Тогда идея хорошая.Я только ЗА.

**Comment by Mr-Deadbeat** [comment]
only a bit curious how will it affect lets say i want to combine the bots with a newer revision of the core code ?
previously i've been patching per instructions is that changing with your proposal ? or are things going to be done in a similar fashion ? my coding knowledge is severely limited to a little bit of C ;)

**Comment by trickerer** [comment]
> only a bit curious how will it affect lets say i want to combine the bots with a newer revision of the core code ?
> previously i've been patching per instructions is that changing with your proposal ? or are things going to be done in a similar fashion ? my coding knowledge is severely limited to a little bit of C ;)

The difference is that you'll need to get lastest patch from releases and not from repo files

**Comment by Ryu1254** [comment]
I don't have any issues. using the NPCBot.patch file to patch.. or using a release..
I'm good with it.

**Comment by qyh214** [comment]
I think that's a good change for developer open pr and also easy to upgrade  with tc.(e.g:use auto mirror with ci)
I don't know how to use patch at present. for example 3 months ago I use 4.8.0 patch, now is 4.9.x and I update by comparing the differences between the two commit files without directly using the patch file.(maybe have other solutions?)
so I very much agree with the objective of this issue and look forward to its implementation as soon as possible!!!

**Comment by trickerer** [comment]
A minor change of plans it seems. I could not resolve all the issues I came upon when importing TC git history into this repo (corrupted commits unaccepted by github without simple resolutions).

For now https://github.com/trickerer/TrinityCore-3.3.5-with-NPCBots will serve as a pre-patched repo cross-linking to this one, without issue tracker (all issues have to collected in one place, which is this repo).
