### ISSUE TITLE
[Github/Suggestion] [Bug] Example in module description is wrong? + create new bot enhancement suggestion

### ISSUE THREAD

**Issue by StraysFromPath** [trickerer/Trinity-Bots#731]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

![image](https://github.com/trickerer/Trinity-Bots/assets/119371540/6cc3e359-3910-44b8-9945-6b817719ef4d)

This says it makes a blood elf mage but if 

createnew <_NAME_> <_CLASS_> _RACE_ _GENDER_ _SKIN_ _FACE_ _HEARSTYLE_ _HAIRCOLOR_ _FEATURES_ _SOUNDSET_

then 

![image](https://github.com/trickerer/Trinity-Bots/assets/119371540/0249099f-4d7d-4bcd-954e-6af75aa130bb)

based on the class list it's making a paladin

p.s:  i'd love it if we can create an npcbot using just name, class, and race and it autofills the hair/eyes/face/etc with semi random numbers that fit the criteria

### Expected behaviour

walkthrough should have correct/accurate info

### TrinityCore or AzerothCore

Both

### Core rev. hash/commit

n/a

### Operating system

n/a

**Comment by trickerer** [comment]
Yeah, I probably filled the numbers with paladin values initially but then decided to make it a mage instead, changes the string but not the number. Thanks for the reminder.
