### ISSUE TITLE
[AC] [Question/] [Core] Consumeable did not deducted on Player Item when giving it to bots, is it mean that way? or any configuration to enable the deduction?

### ISSUE THREAD

**Issue by jakatangkir** [trickerer/Trinity-Bots#732]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

While giving any consumeable like potions foods flask etc to the bot, the item on player's bag did not deducted. Is there any configuration to enable the deduction? or maybe it is must be added some function to the core? thank you

### TrinityCore or AzerothCore

AzerothCore

**Comment by trickerer** [comment]
No, this can't be enabled yet.
Search the tracker before posting an issue please.
#64
#569

**Comment by jakatangkir** [comment]
i see, thank you.
also am so sorry, i tried to type `Consumable` in the search bar it did not result in anything before.

**Comment by trickerer** [comment]
For me searching for `consumable` results in 2 closed issues (now 3 ofc)

**Comment by jakatangkir** [comment]
might be my typo then, been experiencing typos so much lately xD
