### ISSUE TITLE
[AC] [Group/Spell/Core] Assassination Rogue offhand weapon not proccing poison. Combat offhand procs poison on occasion.

### ISSUE THREAD

**Issue by Zaedon33** [trickerer/Trinity-Bots#734]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Assassination Rogue offhand weapon does not proc poison.

### Expected behaviour

Assassination Rogue offhand weapon procs poison applied to offhand weapon.

### Steps to reproduce the problem

Hire Rogue. Set talent to assassination. Attack target dummy or other target.

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. a8c1768722c7+ 2023-12-23 18:05:24 -0700 (npcbots_3.3.5 branch) (Win64, RelWithDebInfo, Static)

### Operating system

Win11

**Comment by trickerer** [comment]
Huh. I never even cared to test it this thoroughly. But somebody cares^^

**Comment by Zaedon33** [comment]
> Huh. I never even cared to test it this thoroughly. But somebody cares^^

It's not care vs not care.  Rogue dps is extremely low rendering them mostly useless. I simply replaced the rogues in my raid. Just wanted to give you a heads up.

**Comment by trickerer** [comment]
Can't confirm no off-hand poison procs, although chance is much lower in Subtlety spec (as it should be). Bot item enchantment proc code isn't messed up either. On the other hand I've noticed Eviscerate consuming Deadly Poison stacks as if it was Envenom. Maybe that was it.

<details><summary>Details</summary>
<p>

![WoWScrnShot_031724_112447](https://github.com/trickerer/Trinity-Bots/assets/1254989/fb13f6a8-bfb8-48ff-b008-dcba688b66c2)
![WoWScrnShot_031724_112536](https://github.com/trickerer/Trinity-Bots/assets/1254989/f2c6c78d-5cf1-444a-8987-881907401997)
![WoWScrnShot_031724_112938](https://github.com/trickerer/Trinity-Bots/assets/1254989/3afea84d-5a4a-4885-9946-279170e85339)

</p>
</details>

https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/c866c602bb161827f005a5bb779e9ba985500529
