### ISSUE TITLE
[AC] [Bug] [Group] any caster-bot looses mana bar and lvl

### ISSUE THREAD

**Issue by Chamuel123** [trickerer/Trinity-Bots#735]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

when I hire a caster or healer, invite to a group and go to a dungeon through the dungeon finder - the bot looses the mana-bar and lvl and is not casting any spells. the only thing the bot is doing is melee-attacks.

![2024-02-03 22_44_39-World of Warcraft](https://github.com/trickerer/Trinity-Bots/assets/143427299/3a286b05-4f25-4f7f-a67b-a70eb39eb8ca)

![2024-02-03 22_46_07-World of Warcraft](https://github.com/trickerer/Trinity-Bots/assets/143427299/a39db57c-b5fa-4060-ac7d-38265d89a9db)

![2024-02-03 22_46_45-World of Warcraft](https://github.com/trickerer/Trinity-Bots/assets/143427299/e865cd98-d95d-48b1-a9fa-cb220bb226d6)

after leaving the dungeon the bot still has no mana-bar and lvl anymore

### Expected behaviour

caster-bots should keep the mana-bar and lvl

### Steps to reproduce the problem

1) hire any caster bot
2) make group
3) go to dungeon finder and list for a dungeon

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. 46062dd070a8 2024-01-20 20:35:59 +0700 (npcbots_3.3.5 branch) (Win64, RelWithDebInfo, Static) (authserver)

### Operating system

Win 10

**Comment by SuzumiK** [comment]
This is (probably) a conflict with the Autobalance module.
If you want to use Autobalance, use this fork instead: https://github.com/trickerer/mod-autobalance

**Comment by Chamuel123** [comment]
> This is (probably) a conflict with the Autobalance module. If you want to use Autobalance, use this fork instead: https://github.com/trickerer/mod-autobalance

yes, i'm using the Autobalance mod. Thank you I will give it a try right now.

**Comment by Chamuel123** [comment]
![2024-02-04 15_59_59-World of Warcraft](https://github.com/trickerer/Trinity-Bots/assets/143427299/37f9bd76-7d24-406b-9f88-86301bddecd7)
The problem was the mod-autobalance. Now everything works fine. Thank you again!
