### ISSUE TITLE
Heroic Azjol-Nerub Bots dissapear mid fight

### ISSUE THREAD

**Issue by Mr-Deadbeat** [trickerer/Trinity-Bots#74]
TC Commit: 0dee695f3bf1e7eea8082f84e1c552c03a137dab
Bots: f4f66672a5f0837d647b249da7229b8e43d7c7db

tried to defeat Hadronox for about 6 times and no matter what i did range changes or what not the bots just vanished and i was standing there alone with the boss and wiped every time until i just gave up on him and rushed past and jumped down
not sure if they just fall trough the webbing in the fight did not see if they did but noticed they just dissapeared all of them

my guess is they fall trough and try to get back so Hadronox is pretty much impossible to defeat atm or you have to be lucky as hell and all the stars align just right

all the other bosses i had no issues what so ever

**Comment by trickerer** [comment]
I tested Hadronox fight/event 3 times and noticed bot and other craetures occasionally fall through the web floor there. I'd like to fix that but it's a TrinityCore maps issue - creatures may sometimes fall through thin surfaces.

The workaround to this is to drag the boss to a solid surface and do the fight there. I was doing it on the stairs using bot distance 25.

![WoWScrnShot_020221_134036](https://user-images.githubusercontent.com/1254989/106562871-886ada00-655d-11eb-9ec0-e681f9d32b00.jpg)

**Comment by Mr-Deadbeat** [comment]
yeah i tried kiting him to other areas as well but had no luck hence the "stars align" comment ;) i'll try that position you showed in the screenshot next time thanks for the tip
