### ISSUE TITLE
Summon worldwide

### ISSUE THREAD

**Issue by Project-Onslaught** [trickerer/Trinity-Bots#740]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Got a question. Can they be summoned all over the world, fighting with creatures ?

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

2022

### Operating system

Win server 2019

**Comment by trickerer** [comment]
Yes, there is a 'wandeing bots' feature. Open readme and scroll down to `NPCBot Wander System` section
