### ISSUE TITLE
[AC] [Question] Bots with higher Maxlevel

### ISSUE THREAD

**Issue by Flashaholic88** [trickerer/Trinity-Bots#741]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Hello,

i edited the Maxlevel on my Server to 100 and if i run the Server it gives me the following warnings:

> >> Loaded 60 disabled wandering bots gear items
No items for class 1 slot 0 at levels 85-89!
No items for class 1 slot 0 at levels 90-94!
No items for class 1 slot 0 at levels 95-99!
No items for class 1 slot 0 at levels 100-104!
.
.
.
No items for class 20 slot 17 at levels 100-104!
>> Sorted wandering bots gear in 741 ms

How i can fix that ?

Thanks in advance

### TrinityCore or AzerothCore

AzerothCore

AzerothCore rev. 46062dd070a8+

**Comment by trickerer** [comment]
Sorry for late answer.

When you set player maximum level higher than default so does change max level of generated NPCBots.
These errors just mean that there is no gear for level 85-100 bots. Algorithm tries to pick items for generated bot from its level bracket (5 levels step). If there is no gear for given bot level, class and slot the error is generated and no item is generated. If there is no gear for levels 85-100 at all then every generated bot of this level range will be naked.

**Comment by trickerer** [comment]
Now after skeeming through the code I see that I've already added a mechanism for selecting highest non-empty level bracket if bot's level bracket is empty.
Lowered log level for that warning to debug. Update and you won't see those messages anymore.

**Comment by Flashaholic88** [comment]
Where I can add equipment for level 80+ ?

**Comment by trickerer** [comment]
Bots' equipment is just equippable items, `item_template` table. Level is required character level, not item level.
