### ISSUE TITLE
[TC] [AC] [Feature] [Group/Spell/Core] The idea of configuring the correlation between the number of NPCBOTs and employer levels.

### ISSUE THREAD

**Issue by moncat2005** [trickerer/Trinity-Bots#742]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

I have found that the number of NPCBOTS in the game is always insufficient. 
I have noticed that many players send coins to low-level characters through high-level characters, and then hire a certain number of robots for low-level characters. 
If the number of hired NPCBots is limited based on character level, it may help improve gameplay and alleviate the shortage of employment resources.

For example, NPCBOTS can only be hired at level 10 or above, with a limit of 1. At level 20 or above, there is a limit of 2, and so on. After level 60, the maximum number of roles allowed in the employment configuration file is allowed.

Can this feature optimization be achieved? 
Thank you!

### TrinityCore or AzerothCore

Both

### Core rev. hash/commit

AzerothCore rev. 595a4c5+ 2024-02-20

### Operating system

Ubuntu 18.04

**Comment by trickerer** [comment]
Good idea. Still need to think of the best way of doing this. It will mess with bot cost so maybe change that also to increase per 10 levels.
This would replace maximum bots config.

**Comment by moncat2005** [comment]
maybe is bad idea.

Idea 1: Add a hill qualification starting level {start hill level} to control the ability to hire NPCBOTS only after reaching the set level.

Idea 2: Continue to retain the maximum number of hires configuration parameter,  and then evenly divide the number of hires that can be hired for every 10 levels up to the highest level (divide and round).

Thank you very much for handling a large number of issues this week, it's great!

**Comment by trickerer** [comment]
Clang build fails so wait for a fix if you build with it.

**Comment by moncat2005** [comment]
An error occurred during the compile process
![0319](https://github.com/trickerer/Trinity-Bots/assets/34859687/cec422e4-5701-4d17-bbe3-9f9f0b2d45fd)

**Comment by moncat2005** [comment]
Thank you! Compiled successfully, now feels good to use!
