### ISSUE TITLE
[TC] [Feature] [Spell] Request for rogues to disable traps in BWL

### ISSUE THREAD

**Issue by TQPS** [trickerer/Trinity-Bots#743]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

In BWL if you are super quick between spawns you have just enough time to right click and select the pick lock option on a Rogue. If you are near a suppression or frost trap, the option comes up for them to disable the trap.

However, once you select it - nothing happens. I suspect they do not have this ability at this time.

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

TrinityCore rev. 5cf4aa70fc3a 2024-02-25 08:03:54 +1100 (npcbots_3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

### Operating system

Win 10

**Comment by trickerer** [comment]
https://github.com/trickerer/TrinityCore-3.3.5-with-NPCBots/commit/aca56bf09f2def8615618024ea9416aa78a1148c

No need for manual labor. You'll need a dedicated Rogue bot **without** DPS role though.


https://github.com/trickerer/Trinity-Bots/assets/1254989/0b025a5c-b199-4c37-8395-cb557e858123
