### ISSUE TITLE
[AC] [Patch Related] Patch can not be reversed due to git-subrepo being created and it refuses to reverse the patch

### ISSUE THREAD

**Issue by Mr-Deadbeat** [trickerer/Trinity-Bots#745]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

patching works but reversing the patch does not i tried to use the patch version to keep the patching procedure fresh so i would not forget how to do it and encountered this issue

### Expected behaviour

should be possible to reverse patch

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

git log commit cd415a1302ee9b9f6e9406b63a8f4ad8fb3c0872

### Operating system

Ubuntu 20.04

**Comment by trickerer** [comment]
So what happens if you use `patch -R -i NPCBots.patch` or `git apply -R NPCBots.patch`?
Why not use `git reset --hard <commit>`?

**Comment by Mr-Deadbeat** [comment]
when using first option it asks me for file to patch when using git apply -R NPCBots.patch i got error NPCBots.patch:374: trailing whitespace.

normally i have always reversed by using patch -p1 -R < NPCBots.patch and it has worked but not anymore
when using above i get

"File deps/git-subrepo is not a regular file -- refusing to patch
File deps/git-subrepo is read-only; trying to patch anyway
1 out of 1 hunk ignored -- saving rejects to file deps/git-subrepo.rej"

i guess i could do a hard reset didn't think about that will try it

not patched the core for a very long time so got a bit surprised that it didn't work as intended ;)

**Comment by trickerer** [comment]
`git apply --help`

What you want is an additional argument to suppress whitespace error:
- `git apply -R NPCBots.patch --whitespace=warn`
