### ISSUE TITLE
[TC] [AC] [Question/Feature]Suggestions on using icon commands for secondary tanks.

### ISSUE THREAD

**Issue by moncat2005** [trickerer/Trinity-Bots#748]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

At present, icon commands mainly assist players in scheduling the main tank and DPS of npcbots.
Please consider adding an indicator icon parameter configuration for the secondary tank when you have time.
This will be very useful in dungeon battles with multiple BOSS objects.
After completing this secondary tank, the icon commands are basically perfect.

Thank you！

### TrinityCore or AzerothCore

Both

### Core rev. hash/commit

AzerothCore NPCBots 2024-02-20 

### Operating system

Ubuntu 18.04

**Comment by moncat2005** [comment]
About This configuration parameter ：NpcBot.OffTankTargetIconMask   
I mistakenly thought this was an icon command that required the main tank not to confront a target.
I see,offtank = secondary tank
Thank you！

**Comment by trickerer** [comment]
> About This configuration parameter ：NpcBot.OffTankTargetIconMask I mistakenly thought this was an icon command that required the main tank not to confront a target. I see,offtank = secondary tank
> 

You could just search the Readme. Off-tank for secondary tank the same way as off-hand weapon for weapon in left hand.

> Perhaps it is possible to consider adding a priority attack icon for all NPCBOTS in the final stage of the replica boss for concentrated have priority firepower attacks.
> 
> Thank you！

It's easily done by resetting all other dps icons and attacking your priority target. It's a single macro, which in the end is no different from what you propose.
