### ISSUE TITLE
[TC] [Bug] [Autobalance] Dead princes attacking player

### ISSUE THREAD

**Issue by DykeRz** [trickerer/Trinity-Bots#749]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

at ICC if you kill princess, they will continue attack you without HP
![image-4](https://github.com/trickerer/Trinity-Bots/assets/35741241/8e4e69f0-7120-4fcc-8bdf-106af52a5758)

### Expected behaviour

Installed patch "autobalance for npc bots" Your patch and set inflection points to 0.7

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

Latest your commit

### Operating system

Debian 11

**Comment by trickerer** [comment]
https://github.com/trickerer/Autobalance_for_NPCBots/commit/f8f96b0469dc3cefa090044578d268d59d919f70
