### ISSUE TITLE
[TC] [Bug] [Core] Latest Worldserver.exe build being incorrectly quarantined

### ISSUE THREAD

**Issue by TQPS** [trickerer/Trinity-Bots#750]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Microsoft Virus & Threat protection is quarantining the latest build from the dadcd2178ddd33ebe7b856cfa6c985e89016b03f commit.

<details>

![image](https://github.com/trickerer/Trinity-Bots/assets/66294837/391e8fec-8aef-440a-9d62-86faf8f15780)

</details>

I trust this is a false positive and am raising it for your situational awareness.

### Expected behaviour

Not expecting the build to be flagged as malware albeit likely false positive.

### Crashlog

N/A

### Steps to reproduce the problem

1) Built commit dadcd2178ddd33ebe7b856cfa6c985e89016b03f  from the recent 3.3.5 w/ bots repo.
2) Applied SQL update.
3) Server wouldn't start - missing Worldserver.exe
4) Noticed Microsoft popped a notification when I copied it across again

Have made some adjustments to prevent this from happening again.

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

TrinityCore rev. c7775b0040f0 2024-03-12 15:45:03 +1100 (npcbots_3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

### Operating system

Windows 10

**Comment by trickerer** [comment]
Well... thanks, I guess. I'm not even sure what to do with this information but I'm sure no TC core recent changes, nor NPCBots recent changes couldn't introduce anything even remotely or vaguely malicious. There weren't even any dependency updates. Maybe some pattern recognition false positive, or maybe it's partially related to continued SSL 1.1 support which has reached EOL in 2023. Blame the big corporation, at least they are used to it.
