### ISSUE TITLE
[TC] [Bug] [Core] SQL Error 1067 Invalid default value for 'hire_time'

### ISSUE THREAD

**Issue by TQPS** [trickerer/Trinity-Bots#752]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

When applying this line from latest commit:
```sql
ALTER TABLE `characters_npcbot` ADD `hire_time` timestamp NULL DEFAULT '1970-01-01 07:00:01' AFTER `faction`;
```

The following error appears:
`/* SQL Error (1067): Invalid default value for 'hire_time' */`

I noted you already applied a fix potentially addressing any NO_ZERO_DATE, but tried it anyway.

<details>

![image](https://github.com/trickerer/Trinity-Bots/assets/66294837/6495dfd6-2551-4845-9c52-e0c2026d838c)

</details>

### Expected behaviour

Table should create new colum `hire_time` after `faction` with a default timestamp of '1970-01-01 07:00:01'.

### Crashlog

N/A

### Steps to reproduce the problem

1) Run 2024_03_12_00_characters_npcbot.sql
2) Error appears in console

Notes:
sql file executed in HeidiSQL 12.6.0
SQL version 8.0.32.0

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

TrinityCore rev. a97043371edf 2024-03-12 21:11:08 +1100 (npcbots_3.3.5 branch) (Win64, RelWithDebInfo, Static) (authserver)

### Operating system

Win 10

**Comment by trickerer** [comment]
Strange. It works in both 5.7 and 8.1, but not 8.0?
Try setting default value to `CURRENT_TIMESTAMP`. Also try removing default altogether

**Comment by TQPS** [comment]
I took some time (and precaution) to migrate SQL to 8.1.0.

Same error with running the bot sql file.

Saw someone suggested to change 1970 to 1990 in the AC thread so tried that here and it worked.

<details>

![image](https://github.com/trickerer/Trinity-Bots/assets/66294837/78c89273-f9e9-421c-a32a-734ed39d9207)

</details>

Just an FYI if someone else is having a similar issue.

**Comment by trickerer** [comment]
Okay. Could you please post an output of console command `SELECT FROM_UNIXTIME(1);`? In theory it should produce minimum valid generated `timestamp` field value.

**Comment by TQPS** [comment]
Returns what you expected. Only difference is the time - this might be timezone. The query specifies 7, mine's returning 11 which reflects my timezone I take it? 

<details>

![image](https://github.com/trickerer/Trinity-Bots/assets/66294837/a194fb10-5434-46a1-8a8d-9e7be881f75a)

</details>

**Comment by trickerer** [comment]
Thanks.
This means I don't need to adjust anything in code, only the SQL file - set universal default value and make it re-executable.
