### ISSUE TITLE
[TC] Last TC update not compatible, but works as a patch but you can't compile

### ISSUE THREAD

**Issue by Krutok** [trickerer/Trinity-Bots#753]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

I have installed all new updates via autoupdate and always check TC to see if there is a patch.

And I saw that there was still a very large patch from TC ready, but unfortunately it couldn't be added to my repo with a pull request. Then I created it as a patch file and patched it manually and it worked without errors or a *.rej file.

Unfortunately, an fatal error occurs when compiling the new files. It doesn't stop compiling, but I think there is an incompatibility here.

```
/var/www/vhosts/xxx/TrinityCore-3.3.5-with-NPCBots/src/server/game/AI/NpcBots/botdatamgr.cpp:1383:37: fatal error: no viable conversion from 'const Trinity::unique_trackable_ptr<Battleground>' to 'const Battleground *'
                Battleground const* real_bg = real_bg_pair.second;
                                    ^         ~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [src/server/game/CMakeFiles/game.dir/build.make:608: src/server/game/CMakeFiles/game.dir/AI/NpcBots/botdatamgr.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 23%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Commands/cs_list.cpp.o
[ 23%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Commands/cs_lookup.cpp.o
[ 23%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Commands/cs_message.cpp.o
[ 23%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Commands/cs_misc.cpp.o
[ 23%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Commands/cs_mmaps.cpp.o
[ 24%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Commands/cs_modify.cpp.o
make[1]: *** [CMakeFiles/Makefile2:1089: src/server/game/CMakeFiles/game.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

[.....later]
[ 76%] Linking CXX static library libscripts.a
[ 76%] Built target scripts
make: *** [Makefile:149: all] Error 2

```

I found it very strange, so I'm making the patch available here so that you can insert it and then have it installed via an update and with it the error message when compiling

[release...TrinityCore TrinityCore 3.3.5.patch.txt](https://github.com/trickerer/Trinity-Bots/files/14613275/release.TrinityCore.TrinityCore.3.3.5.patch.txt)

### Steps to reproduce the problem

Install the patch and compile, then the core you will then see the error message.

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/93daeaea26ea0f317c328568058b04b30f84c8ad

### Operating system

Debian 11

**Comment by trickerer** [comment]
It was a routine merge. I'm tired of answering questions about updates so I've added this info to readme header
