### ISSUE TITLE
[TC] Mysql update error / Unknown column 'hire_time' in 'field list'

### ISSUE THREAD

**Issue by Krutok** [trickerer/Trinity-Bots#754]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

I have all the SQL updates in there, but there is an error here
```

>> World database is up-to-date! Containing 57 new and 6396 archived updates.
In mysql_stmt_prepare() id: 447, sql: "UPDATE characters_npcbot SET owner = ?, hire_time = FROM_UNIXTIME(?) WHERE entry = ?"
Unknown column 'hire_time' in 'field list'
In mysql_stmt_prepare() id: 448, sql: "UPDATE characters_npcbot SET owner = ?, hire_time = FROM_UNIXTIME(?) WHERE owner = ?"
Unknown column 'hire_time' in 'field list'
```
Server no longer starts because there is this MYSQL error message and you cannot fix it.
Now I have to import a server backup so that it works again -.-

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

TrinityCore rev. a5eee8869166+

### Operating system

Debian 11

**Comment by trickerer** [comment]
You are missing `sql/Bots/updates/characters/2024_03_12_00_characters_npcbot.sql` update. NPCBots sql updates aren't applied automatically.

It's harder to integrate existing sqls into TC autoupdates system than into AC so this comes later.
