### ISSUE TITLE
[AC] [Crash] Some specific wandering bot causes a crash on spawn

### ISSUE THREAD

**Issue by SuzumiK** [trickerer/Trinity-Bots#755]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

After the latest update, I have experienced very puzzling crashes. I now think that one specific bot being spawned as a wandering bot causes the server to crash.

I observed that after the update, the world server would crash after some time without discernible cause. This usually happened after a few minutes, but not always.

I also observed that wandering bots are spawned in one by one.

I have 24 bots hired. That leaves a pool of 258 for wanderers. My wanderer count was configured to be 100.

When I set that wanderer count to 258 (to guarantee spawns of the whole pool), the server always crashed in all of my tests.

When I set the wanderer count to 0, I did not (yet) experience any more crashes.

Therefore, I think that spawning a specific bot as a wanderer causes a server crash. However, I do not know which bot, and I also do not know how to find out.

**UPDATE**:
I may have been wrong about the spawning in causing the crash. In at least one instance, all bots were spawned and the server did not crash immediately. It did crash maybe a minute later. So it seems to be related to wandering bots, but not to the spawn.

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

452ca39

### Operating system

Win10

**Comment by Day36512** [comment]
I'm pretty sure this issue is related to the new Sunder Armor mechanic for nontanks as that's where my crashlogs are pointing to. I'd share my logs but they point to different lines. Essentially it's getting hung up on botspec retreival during updateai. I'm trying with a simplified version of code to see if this improves anything.

**Comment by Day36512** [comment]
So this is what I came up with. It has different checks though. All I check for is  roles and dps specs. I think it was originally just getting hung up on GetBotMgr()->HasBotWithSpec with regards to wandering bots.


```
            //SUNDER ARMOR 
            if (IsSpellReady(SUNDER_ARMOR_1, diff) && can_do_normal && dist < 5 && rage >= rcost(SUNDER_ARMOR_1))
            {
                bool shouldCastSunder = false;

                if (IsTank() && mytar->GetHealth() > me->GetMaxHealth() && Rand() < 55)
                {
                    shouldCastSunder = true;
                }
                else if ((!IsTank() && (isFury || isArms)) && (!CanBlock() || !GetSpell(DEVASTATE_1)) && Rand() < 30)
                {
                    shouldCastSunder = true;
                }

                if (shouldCastSunder)
                {
                    AuraEffect const* sunder = mytar->GetAuraEffect(SUNDER_ARMOR_DEBUFF, 0);
                    if ((!sunder || sunder->GetBase()->GetStackAmount() < 5 || sunder->GetBase()->GetDuration() < 20000) &&
                        doCast(mytar, GetSpell(SUNDER_ARMOR_1)))
                    {
                        return;
                    }
                }
            }
            ```
