### ISSUE TITLE
[AC] [Bug] [Core] Druid fly form , bot not fly

### ISSUE THREAD

**Issue by Tilenozz** [trickerer/Trinity-Bots#756]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

When druid use Fly form , bot stay on ground and aggro all and die

![image](https://github.com/trickerer/Trinity-Bots/assets/54805850/166cdd5c-9ff1-48eb-b74b-77cc147b6e2d)

### Expected behaviour

Pop fly mount , and follow

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. a15d71433b32 2024-03-17

### Operating system

Ubuntu 22.04

**Comment by trickerer** [comment]
Of course they don't fly, Fly Form isn't implemented. That's why Druids don't use it automaticaly.

**Comment by trickerer** [comment]
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/53c02094cde0497678186ed4d454a833738dfbb5
