### ISSUE TITLE
[TC] [AC] [Question/Feature] [Group/Spell/Core] .npcbot attack?

### ISSUE THREAD

**Issue by nugsforthugs** [trickerer/Trinity-Bots#757]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Was wondering if it was something that could be implemented to send the bots to attack or if you whispered the tank and it attacks your current target and triggers others to attack also. It's not a super huge deal but sometimes with spell caster only mobs the bots don't notice until I'm close to dead and healing kicks in or there's an AOE that damages the group.

Thanks so much!

### TrinityCore or AzerothCore

Both

### Core rev. hash/commit

AzerothCore rev. a15d71433b32 2024-03-17 12:53:45 +0700 (npcbots_3.3.5 branch) (Win64, Release, Static) (worldserver-daemon)

### Operating system

Win10

**Comment by trickerer** [comment]
There is `.npcbot sendto` command for that as well as different target priorities set via raid icons. And other options. Use search next time. Check Readme.

#254
#516
#599
#274
Also #506
