### ISSUE TITLE
[TC] [AC] [Feature] [Boss Mechanics] Shirrak the dead watcher (18371): Improve bots for this boss

### ISSUE THREAD

**Issue by Boxhead78** [trickerer/Trinity-Bots#758]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Hello, first I want to thank you for your ongoing work on the NPCBots and I love following each commit you make 💯 

Caster Bots (especially healers) are having a difficult time against the boss "Shirrak the dead watcher" because that boss gives a cast time debuff which stacks the closer you are to the boss.

1. I would like to ask if it's possible to make caster bots keep max distance to the boss in order to improve their performance against that boss. Spell should be "Inhibit Magic. ID: 32264"
2. The boss also uses an ability I think it's named "Focus Cast" or "Fiery Blast" where it targets the player and does a big amount of damage on the ground as an aoe spell. The bots should avoid that if possible.
This spell also only targets the player. It would be a nice to have if this spell can target npcbots as well but I think this would require a core edit.

### TrinityCore or AzerothCore

Both

**Comment by trickerer** [comment]
Attack distance you set manually through gossip menu or using `.npcbot distance attack` command
