### ISSUE TITLE
[AC] [Question] [Core] Updates/Changelog

### ISSUE THREAD

**Issue by Conan1996-2** [trickerer/Trinity-Bots#759]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Is there a current changelog? I would like to see this so I know whether or not I wish to spend time recompiling everything.

the current Guide Changelog only shows:

Version 0.25 (14 Jun 2023)
Added .npcbot useonbot ... commands

Thank you, and thank you for all the hard work you have put into this.

### TrinityCore or AzerothCore

AzerothCore

**Comment by trickerer** [comment]
No, there is no changelog.

The only thing kind of resembling a changelog is a commit history of this repository. Each commit here contains links to every included commit in both TC and AC patched repos, github provides popups with actual commit messages.
