### ISSUE TITLE
npcbot dump load

### ISSUE THREAD

**Issue by zaicopx** [trickerer/Trinity-Bots#76]
Hello, why every time I use the .npcbot dump load command there is an error like this?

> Starting NpcBot system...
>> Bot appearance data loaded
>> Bot race data loaded
>> Loaded 2 bot data entries
Cannot spawn npcbot Evencane (id: 70032), not found in `creature` table!
Cannot spawn npcbot Lariia (id: 70217), not found in `creature` table!
>> Spawned 0 npcbot(s) within 0 grid(s) in 7 ms

Sometimes npcbot works, sometimes it doesn't.

**Comment by trickerer** [comment]
Post your dump file so I can test it. For now use this to uninstall bots and try again
[npcbots_uninstall.zip](https://github.com/trickerer/Trinity-Bots/files/5936170/npcbots_uninstall.zip)

**Comment by zaicopx** [comment]
This is my npcbot dump
[bots.zip](https://github.com/trickerer/Trinity-Bots/files/5936447/bots.zip)
