### ISSUE TITLE
AC Bug Core Bots can't enter raids (but can enter dungeons)

### ISSUE THREAD

**Issue by jmoeIP** [trickerer/Trinity-Bots#760]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Hello. 
Thank you for your work.

Bots will not enter/ teleport to any raid I've tested (Naxxramas, Molten Core, Icecrown Citadel), but can enter/teleport to dungeons (dungeon finder/ running through the portal/ teleporting)

I've used (Azeroth core :  .tele Nax and .tele .naxxramas, and ran through the portal). The player character can enter, but the bots can't.

Using Azeroth core at commit b69df485cf87e1a3ff838302e5b3295e78370407 , due to the newest version of Azeroth Core has modified files which is incompatible with the current patch file (commit d261588c895973a465bd244f6879ed31cd839675)

#Outside Naxxramas (world map)
![image](https://github.com/trickerer/Trinity-Bots/assets/133774342/b8f266d0-827a-4a17-af86-2c8264485b31)

#Inside Naxxramas (bots will not enter )
![image](https://github.com/trickerer/Trinity-Bots/assets/133774342/3f799947-5718-4ab3-8d67-29183fbbb143)

#Inside Naxxramas (bots will not enter )
![image](https://github.com/trickerer/Trinity-Bots/assets/133774342/3efd9c43-7d21-485d-a27a-fe3227524826)

#Deadmines (Working as I expect. After teleporting to the deadmines, the bot will teleport to me)
![image](https://github.com/trickerer/Trinity-Bots/assets/133774342/b233210c-c3f8-4ffe-a838-d39b705884f9)

### Expected behaviour

I assume it is expected behavior that bots can enter raids like seen in videos like https://youtu.be/riTgGx9ELW0 (though its TrinityCore  and not Azeroth Core)

### Steps to reproduce the problem

- Enter world with a character at level 80.
- .npcbot spawn 70137 
- Right click the bot and click: Create group
- Press the 'o' key and click on the raid tab (in the bottom) and click Convert To Raid
- Teleport to a raid: .tele nax

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. b69df485cf87+ 2024-03-18 22:31:05 +0100 (HEAD branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

### Operating system

Windows 11

**Comment by trickerer** [comment]
Can't confirm. Bots can enter Naxxramas normally.
![naxx](https://github.com/trickerer/Trinity-Bots/assets/1254989/05cf2c14-b850-4d2f-b911-e47f009a0cc4)

Check your config parameters
- `NpcBot.Enable.Raid`
- `NpcBot.DisableInstances`

**Comment by jmoeIP** [comment]
Thank you!
I'm sorry I wasted your time. 
I've looked for config settings, but I missed the NpcBot.Enable.Raid setting.
![image](https://github.com/trickerer/Trinity-Bots/assets/133774342/d3d5c302-2e35-4551-be6e-728525633aac)

**Comment by jmoeIP** [comment]
Thank you so much for your work!

![image](https://github.com/trickerer/Trinity-Bots/assets/133774342/61f47512-3af1-4a75-b058-2017e14a54e4)
