### ISSUE TITLE
[AC] [Bug] [Core] When the NpcBot.HealTargetIconMask is set, it will not be treated when the BOSS is treated to 90% blood.

### ISSUE THREAD

**Issue by saliven1970** [trickerer/Trinity-Bots#762]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

When the NpcBot.HealTargetIconMask is set, it will not be treated when the BOSS is treated to 90% blood.It is normal to treat 100% before March 2024.

### Expected behaviour

It is normal to treat 100% before March 2024.

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. 87b74c1c2dc3 2024-03-23 08:32:45 +0700 (master branch) (Unix, Release, Static) (worldserver-daemon) ready

### Operating system

OpenEuler22.03

**Comment by trickerer** [comment]
It's probably caused by https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/2bfdad05cc957a2b1cd5ab5643adf6860c41fc3f. You need to set this threshold to 99 thorugh gossip menu for bots to heal their targets to 100% hp.

**Comment by saliven1970** [comment]
> It's probably caused by [trickerer/AzerothCore-wotlk-with-NPCBots@2bfdad0](https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/2bfdad05cc957a2b1cd5ab5643adf6860c41fc3f). You need to set this threshold to 99 thorugh gossip menu for bots to heal their targets to 100% hp.

Thank you, this operation has solved the problem.
