### ISSUE TITLE
[TC] [Crash] [Core] Server starup crash

### ISSUE THREAD

**Issue by leelf00** [trickerer/Trinity-Bots#763]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

TrinityCore rev. c4912e0380d9 2024-03-22 21:20:58 +0000 (npcbots_3.3.5 branch) (Unix, Release, Static) (worldserver-daemon)
<Ctrl-C> to stop.

 ______                       __
/\__  _\       __          __/\ \__
\/_/\ \/ _ __ /\_\    ___ /\_\ \, _\  __  __
   \ \ \/\`'__\/\ \ /' _ `\/\ \ \ \/ /\ \/\ \
    \ \ \ \ \/ \ \ \/\ \/\ \ \ \ \ \_\ \ \_\ \
     \ \_\ \_\  \ \_\ \_\ \_\ \_\ \__\\/`____ \
      \/_/\/_/   \/_/\/_/\/_/\/_/\/__/ `/___/> \
                                 C O R E  /\___/
http://TrinityCore.org                    \/__/

Using configuration file conf/worldserver.conf.
Using SSL version: OpenSSL 3.0.2 15 Mar 2022 (library: OpenSSL 3.0.2 15 Mar 2022)
Using Boost version: 1.74.0
Daemon PID: 80579

Updating Auth database...
>> Auth database is up-to-date! Containing 1 new and 113 archived updates.
Updating Character database...
>> Character database is up-to-date! Containing 2 new and 83 archived updates.
Updating World database...
>> World database is up-to-date! Containing 73 new and 6396 archived updates.
In mysql_stmt_prepare() id: 447, sql: "UPDATE characters_npcbot SET owner = ?, hire_time = FROM_UNIXTIME(?) WHERE entry = ?"
Unknown column 'hire_time' in 'field list'
In mysql_stmt_prepare() id: 448, sql: "UPDATE characters_npcbot SET owner = ?, hire_time = FROM_UNIXTIME(?) WHERE owner = ?"
Unknown column 'hire_time' in 'field list'
Could not prepare statements of the Character database, see log for details.

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

TrinityCore rev. c4912e0380d9 2024-03-22 21:20:58 +0000 (npcbots_3.3.5 branch) (Unix, Release, Static) (worldserver-daemon)

### Operating system

Ubuntu 22.04

**Comment by trickerer** [comment]
You miss a sql update, #754. It's a TC only problem.

**Comment by leelf00** [comment]
Thanks.It works.
