### ISSUE TITLE
[TC] [AC] [Bug/Crash] [Core]  the worldserver service was no response in Blackwing Lair

### ISSUE THREAD

**Issue by moncat2005** [trickerer/Trinity-Bots#764]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

I cannot determine whether the issue is caused by AC code or NPCBOTS code.
The server console appears to have no abnormalities or crashes.
But the world service no longer responds to clients, and logging in again cannot access the world service.

### Steps to reproduce the problem

1. The raid entering the Blackwing Lair

2. goto confronting Nefarian

3. The player was hit by Nefarian's breathing skill and flew up, causing the client to disconnect.

4. The server is deadlocked, and after client account authentication, it shows no response in the connection.

5. The worldserver console appears to be displaying normally.

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit
AzerothCore rev. 87b74c1c2dc3 2024-03-23 10:10:50 +0800 (npcbots_3.3.5 branch) 
  
### Operating system

Ubuntu 18.04

**Comment by trickerer** [comment]
Can't confirm after 20 minutes (2 fights). No Nefarian's abilities cause players to disconnect / get kicked so I can't tell what happens. Maybe you should give it a bit more time, it sometimes takes a while to generate a crashlog.

**Comment by moncat2005** [comment]
I suspect that the issue is caused by the MOD component: anticheat.

When a player is knocked away by a boss, it is easy to be misjudged as a cheat.

If the BAN account action is triggered at this time, the client will be disconnected.

If the BAN operation of this MOD component causes an error in the connection between Worldserver and MySQL database, it may exhibit a phenomenon similar to downtime without further logging.
![error](https://github.com/trickerer/Trinity-Bots/assets/34859687/fc40da07-3fb7-463c-8f4e-88fe6280c25d)

**Comment by trickerer** [comment]
From my experience lost connection during a query error means that some mysql buffer is too small.
Try to run this query manually, if it errors then try to gradually increase buffer sizes listed in `my.ini` config file, starting with `max_packet_size` or whatever it's called exactly.

**Comment by moncat2005** [comment]
Confirm that this issue is related to the execution character of anticheat modules:  being kicked out of the world after being hit and flying during combat.
Not related to NPCBOTS and azcore source code.

**Comment by moncat2005** [comment]
close this issuse
