### ISSUE TITLE
[TC] [Bug/Crash] [Group] Currently we cannot record bots' damage in team/group

### ISSUE THREAD

**Issue by FerdinandLBS** [trickerer/Trinity-Bots#765]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Addons cannot record bots' damage.
In previous version, when bots are considered as pets/guardians, Addon can successfully record the damage.
But in some rare cases, some bots can be recorded. Not stable.

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

ca1abfef71

### Operating system

Windows 11

**Comment by trickerer** [comment]
Have you looked for an alternative? Like [Skada](https://www.curseforge.com/wow/addons/skadarev), it does work with bots

**Comment by noisiver** [comment]
I use and recommend this version: https://github.com/bkader/Skada-WoTLK

It's a complete rewrite of Skada for 3.3.5a, and it works fine with bots.

**Comment by FerdinandLBS** [comment]
OK, thank both of you. I will try.
