### ISSUE TITLE
[TC] [AC] [Feature] [Core] Can we add some interfaces/callbacks so that I can do customization with NPCBot?

### ISSUE THREAD

**Issue by FerdinandLBS** [trickerer/Trinity-Bots#766]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

I played with NPCBot for a long time. And I also trying to add some other customized feature to TC.
Like more race talent skills or integrating ChatGPT.
Can we add some interfaces or callbacks so that I can easily do customization?
Thank you.

### TrinityCore or AzerothCore

TrinityCore

**Comment by trickerer** [comment]
Eluna Lua engine exist just for that, as well as its TC port (from AC).
But I don't intend to integrate it into any version. If you need it you'll have to merge it yourself, only then you may start thinking about what is to expose to Eluna with an API callback (create new hooks).

**Comment by FerdinandLBS** [comment]
OK, thanks for your reply.
