### ISSUE TITLE
[AC] Краш сервера

### ISSUE THREAD

**Issue by xBarselonx** [trickerer/Trinity-Bots#767]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

После запуска worldserver приложение закрывается.

### Crashlog

[<script src="https://gist.github.com/xBarselonx/981cfd9370f2ca954dc6e233087e7f89.js"></script>
](https://gist.github.com/xBarselonx/981cfd9370f2ca954dc6e233087e7f89)

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. 87b74c1c2dc3 2024-03-23 08:32:45 +0700 (npcbots_3.3.5 branch) (Win64, Debug, Static) (worldserver-daemon)

### Operating system

Windows 10 x64

**Comment by trickerer** [comment]
Ты пропустил обновление конфига от https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/70533058

**Comment by xBarselonx** [comment]
Спасибо!
