### ISSUE TITLE
 [AC] [Bug] [Core] Consultation on abnormal features of Acore's built-in warden function

### ISSUE THREAD

**Issue by moncat2005** [trickerer/Trinity-Bots#768]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

I don't know how others set up the configuration for warden, and I have always been very confused about the actual performance of this feature.

Since 2020, I have been in contact with Azcore. As long as the warden function is enabled in the worldserver configuration, the following exceptions will occur.
1. The character creation and selection interface has become sluggish.
2. If you keep Warden's default configuration and enter the world, the client will crash and pop up an error message.
3. I turned off the checks related parameters and only kept warden enable=1 to enter the world, but the entire client screen became stuck every 3 seconds, making it impossible to play normally.

Based on the above reasons, I can only disable the native warden feature of azcore and use the anticheat module instead.
However, the anticheat module may misjudge the use of fly cheating when players are hit by skills in the game.

I once searched for relevant issues on Azerothcore, but couldn't get any useful information.
I really want to understand the correct usage of the warden function and hope to receive guidance from all the experts.
Thank you.

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore-wotlk-with-NPCBots 238dbd6  2024-3-30

### Operating system

Ubuntu 18.04

**Comment by trickerer** [comment]
This issue is not related to NPCBots and stayed open long enough, but looks like noone is able to elaborate.
Closing now.
