### ISSUE TITLE
[AC] [Bug] [Core] The Protection Paladin has random equipment and no defensive equipment.

### ISSUE THREAD

**Issue by leewheel** [trickerer/Trinity-Bots#769]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

       I added a menu to the robot that can randomly refresh the equipment, using the following code, but I found that the Paladin with the defensive talent, even if the duty is defined as TANK, no matter how I refresh it, there will be no defensive equipment, only magic damage equipment.

### Expected behaviour

case GOSSIP_SENDER_REEQUIP_ALL:
        {
            bool suc = true;
            UnEquipAll(master->GetGUID()); // 

            if (suc)
                me->HandleEmoteCommand(EMOTE_ONESHOT_SHY);
            ApplyBotRandomEquip(); // 

            break;
        }

### Steps to reproduce the problem

Just refresh it

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. 9ca9f695998c+ 2024-03-25 07:46:25 -0600 (npcbots_3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

### Operating system

Windows 11

**Comment by trickerer** [comment]
Hell if I know. Why do you even make an issue about your own custom code here?

**Comment by leewheel** [comment]
Sory!
