### ISSUE TITLE
Improvement - follow patch NPCBots v4.9.38a make raid with bot nearly impossible..

### ISSUE THREAD

**Issue by Ryu1254** [trickerer/Trinity-Bots#77]
we raid alot ICC and TOC (normal and heroic)
With this new feature of spell target also BOT, make some fight impossible without a fully functional of the Implement AoE detection and avoidance within combat positioning.
is it possible, to add a condition if BOT can avoid within combat positioning, then we use the spell that are explicite target bot or use by script will be activate..
if bot cannot avoid, then dont cast that spell on BOT.
for example: Putricide Mutated Slime, fire bomb in Gormok the Impaler, those skill bot cannot avoid at all. just sitting there and die.

I dont mean to completely do a roll back. but add some condition when it's avoidable by bot, then we cast it on bot..
otherwise, it's nearly impossible to do those raid only with bot, as oppose we can do those fight before the patch v4.9.38a.

**Comment by trickerer** [comment]
4.9.38a is likely to be partially reverted. This whole 'player-only spells target bots too' thing needs a deeper rework including reviewing 700+ cases of target selection across all scripts.
