### ISSUE TITLE
[TC] [Crash] [Core] Сбой при нажатии на "Роли" в боте и трансмог

### ISSUE THREAD

**Issue by DykeRz** [trickerer/Trinity-Bots#770]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Привет, при применении трансмога в ядро от Rochet2 версии катаклизм (https://github.com/Rochet2/TrinityCore/tree/transmog_3.3.5/src/server/scripts/Custom/Transmog) version 6.1

и при применении исправлений из #101

Сервер закрывается при нажатии в боте на "Роли"

[log2024-04-04-06-06-32.log](https://github.com/trickerer/Trinity-Bots/files/14860927/log2024-04-04-06-06-32.log)

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

1a1ba98

### Operating system

debian 11

**Comment by trickerer** [comment]
Возможно никак не связано с кодом трансмога, а просто отсутствует локализация. Попробуй добавить условие `ntl->Text_0[0].size() > size_t(loc)`:
```diff
- if (loc != DEFAULT_LOCALE && ntl && !ntl->Text_0[0][loc].empty() && Utf8FitTo(ntl->Text_0[0][loc], wnamepart))
+ if (loc != DEFAULT_LOCALE && ntl && ntl->Text_0[0].size() > size_t(loc) && !ntl->Text_0[0][loc].empty() && Utf8FitTo(ntl->Text_0[0][loc], wnamepart))
```

**Comment by DykeRz** [comment]
> Возможно никак не связано с кодом трансмога, а просто отсутствует локализация. Попробуй добавить условие в строке bot_ai.cpp 331 `ntl->Text_0[0].size() > size_t(loc)`:
> 
> ```diff
> - if (loc != DEFAULT_LOCALE && ntl && !ntl->Text_0[0][loc].empty() && Utf8FitTo(ntl->Text_0[0][loc], wnamepart))
> + if (loc != DEFAULT_LOCALE && ntl && ntl->Text_0[0].size() > size_t(loc) && !ntl->Text_0[0][loc].empty() && Utf8FitTo(ntl->Text_0[0][loc], wnamepart))
> ```

Понял, получается это тебе надо будет исправить в основном коде?

**Comment by DykeRz** [comment]
Кстати, а где эта локализация хранится в БД? Просто на винде работает нормально, а на дебиане крашит, БД одинаковые (вроде)

**Comment by trickerer** [comment]
> > Возможно никак не связано с кодом трансмога, а просто отсутствует локализация. Попробуй добавить условие в строке bot_ai.cpp 331 `ntl->Text_0[0].size() > size_t(loc)`:
> > ```diff
> > - if (loc != DEFAULT_LOCALE && ntl && !ntl->Text_0[0][loc].empty() && Utf8FitTo(ntl->Text_0[0][loc], wnamepart))
> > + if (loc != DEFAULT_LOCALE && ntl && ntl->Text_0[0].size() > size_t(loc) && !ntl->Text_0[0][loc].empty() && Utf8FitTo(ntl->Text_0[0][loc], wnamepart))
> > ```
> 
> Понял, получается это тебе надо будет исправить в основном коде?

Да. Но если это изменение пофиксит краш то мне не придётся устанавливать этот мод и искать проблему в другом месте.

> Кстати, а где эта локализация хранится в БД? Просто на винде работает нормально, а на дебиане крашит, БД одинаковые (вроде)
>
> Может я что-то не добавил в БД на дебиане и нужно добавить какую-то локализацию

`npc_text_locale`. Файлы локализации находятся в `sql/Bots/locales/` в репозитории форка или `SQL/locales` в репозитории патча

**Comment by DykeRz** [comment]
Фикс решил проблему, странно ещё то, что локализация ботов и этого меню у меня установлено на русский, и вроде бы как должно было же работать (локализация же есть на русский) но почему то крашило, щас всё ок, спасибо за помощь)
