### ISSUE TITLE
[TC] [Crash] [Core] Worldserver fails on startup "Loading NPCBot group members"

### ISSUE THREAD

**Issue by TQPS** [trickerer/Trinity-Bots#771]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Worldserver crashes during startup at this point:
```
...
>> Loaded 60 disabled wandering bots gear items
>> Sorted wandering bots gear in 12 ms
Loading NPCBot group members...
```

### Expected behaviour

Startup completes.

### Crashlog

N/A

### Steps to reproduce the problem

1) Build commit d99a35fa9cc0ccd4a705e4ffa73a7e4dc5130f47 from npcbots_3.3.5
2) Worldserver closes unexpectedly; "A problem caused the program to stop working etc"

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

TrinityCore rev. c5ac3094e93f 2024-04-06 14:43:56 +1100 (npcbots_3.3.5 branch) (Win64, RelWithDebInfo, Static) (authserver)

### Operating system

Win10

**Comment by trickerer** [comment]
Post a crashlog

**Comment by TQPS** [comment]
https://gist.github.com/TQPS/34fc1b2d81dca26c052b41eddbf4d576

**Comment by trickerer** [comment]
Did you get error in the console about not being able to spawn bot beacuse he is not in `creature` table?

**Comment by TQPS** [comment]
Console is showing:
```
>> Loaded 60 disabled wandering bots gear items
>> Sorted wandering bots gear in 13 ms
Loading NPCBot group members...

C:\Projects\3.3.5a - Bots\Source\src\common\Debugging\Errors.h:80 in ASSERT_NOTNULL_IMPL ASSERTION FAILED:
  pointer
BotDataMgr::FindBot(creature_id)
```

I can try a rebuild or just drop the build back a few commits if you cant replicate it.

**Comment by trickerer** [comment]
Ok, seems like bots could've been deleted by `2024_03_30_05_world.sql` and other sqls messing with most recent creature guids.

Here is a script that will spawn missing bots at the bottom of Lordamere Lake, you will be able to `.npcbot move` them as normal, hope you rememeber where they were because for me it seems like **all** bot spawns got deleted.

```SQL
SET @MAXGUID = (SELECT MAX(`guid`) FROM `creature`) + 100000;
INSERT INTO `creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `wander_distance`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `VerifiedBuild`) VALUES
(@MAXGUID, 70000, 0, 0, 0, 1, 1, 0, 0, 1172.51, 52.322, 5.93566, 0.99, 300, 0, 0, 66937, 0, 0, 0, 0, 0, 0);
INSERT INTO `creature` (`id`) (SELECT `entry` FROM `characters`.`characters_npcbot` WHERE `entry` NOT IN (SELECT `id` FROM `creature` WHERE `id` > 70000));
UPDATE `creature` SET `map`=0, `zoneId`=0, `areaId`=0, `spawnMask`=1, `phaseMask`=1, `modelid`=0, `equipment_id`=0, `position_x`=1172.51, `position_y`=52.322, `position_z`=5.93566, `orientation`=0.99,`spawntimesecs`=300, `wander_distance`=0, `currentwaypoint`=0, `curhealth`=1, `curmana`=0, `MovementType`=0, `npcflag`=0, `unit_flags`=0, `dynamicflags`=0, `VerifiedBuild`=0 WHERE `guid` > @MAXGUID;
```
Use on `world` DB. Make sure to execute all this as a single file.

**Comment by TQPS** [comment]
Thank you - all bots restored to their original locations.
