### ISSUE TITLE
[TC] [AC] [Question/Feature] [Core] Автоэкипировка ботов нормальным шмотом на 80 уровне

### ISSUE THREAD

**Issue by Bogir** [trickerer/Trinity-Bots#772]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Есть идея реализовать одевание ботов 80 уровня по бис-листу. Автоматически при вызове, а не вручную из своего инвентаря. И при увольнении бота - удалять из массива предметов этого бота весь БИС-шмот, а не передавать игроку.
У игрока, зачастую, на себя не хватает нормальных вещей, а тут еще боту где-то доставать надо шмот. А так - бот будет полностью готов к использованию. 
Шаблон для бис-шмоток у меня готов от Player-бота если будет нужен.

P.S. чур помидорами не кидаться!

### TrinityCore or AzerothCore

AzerothCore

**Comment by trickerer** [comment]
Автоэкипировка нанимаемых ботов в любом виде, тем более бис, полностью обнуляет всякий смысл заботиться об экипировке своих ботов, а это одна из ключевых фич.
Так что ответ, такой же отрицательный, как и на все предыдущие предложения такого рода.

Что касается баланса шмота. Данная проблема, если она есть (у игроков, я имею ввиду), решается несколькими путями: либо увеличением дропа, либо замедлением кача, чтобы игрок получал больше лута на уровень. Если игрок качается настолько быстро, что у него не образовывается лишнего шмота даже чтобы одеть одного-двух ботов, то зачем они вообще нужны.

**Comment by Bogir** [comment]
Anв what about to make it as option (on/off) and put it in worldserver.conf ?
А что если сделать это как опцию и вывести в конфиг сервера?

Я попробовал. Всё отлично работает, но не соображу как обновить внешний вид для оружия правой/левой руки. Дефолтный меч отображается при любом оружии.
