### ISSUE TITLE
[TC] [Bug] [Core] Garr adds despawn at 11% if you take Garr down first

### ISSUE THREAD

**Issue by TQPS** [trickerer/Trinity-Bots#776]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Some time ago, I created an [issue](https://github.com/trickerer/Trinity-Bots/issues/209) regarding the server crash if you killed Garr before his adds.

This got fixed (Thank you) but noticed since then, when bots switch to the adds AFTER Garr is down, they'll despawn at 11%.

If you exit and re-enter instance (ie go sell loot), the adds that despawned will reappear.

Note: If adds are taken down BEFORE Garr, they behave properly and explode - killing 1-2 bots in the process.

Note: There are no crashes or workarounds required, just a bug.

### Expected behaviour

Adds should be taken down to 0 health and explode if killed before or after, Garr.

### Crashlog

N/A

### Steps to reproduce the problem

1) Put skull on 1 add, bots DPS it, goes to 0 and explodes
2) Put skull on Garr, bots DPS him until he dies
3) Kill next add, it despawns at 11% health
4) Kill next add, it despawns at 11% health
5) etc for each remaining add

Caveat: All bots are capped at 60 and most have decent MC gear drops with some in BWL gear. Also, damage, heals, etc all reduced by 25% to mimic a more realistic raid experience.

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

TrinityCore rev. c5ac3094e93f 2024-04-06 14:43:56 +1100 (npcbots_3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

### Operating system

Win10

**Comment by trickerer** [comment]
Can't reproduce.
All adds despawn at 10% even if hit with damage exceeding their health, by either player or bot, regardless of boss state. This behavior is handled by `npc_firesworn` creature script in `boss_garr.cpp` (`void DamageTaken(...)`)
