### ISSUE TITLE
[AC] [Question/Feature] [Core] Primary DPS target Icon mask not work during soul phase of Kalecgos & Sathrovarr

### ISSUE THREAD

**Issue by Shiradan** [trickerer/Trinity-Bots#777]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

I was trying to solo raid with bots in Sunwell, in the first boss, when I entered the soul phase and summon some bots  (as they were not able to enter themselves), the bots won't attack Sathrovarr(the dread lord) even though I put a primary dps target on it, I guess it is because in this phase, my character don't have any threat, so the bots assume I am not in combat, and then they stopped. Is there any way to bypass the issue, like some command to force the bot to attack my target?

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

the latest version of your build

### Operating system

Ubuntu

**Comment by moncat2005** [comment]
There is indeed this problem.
After identifying the DPS object for Sathrovarr, the NPCBOTS that followed the player character into the gap did not exhibit any attack behavior.
Finally, all Sathrovarr needs to be killed by the player's character's DPS output, and the player must wait for a delay in the entry and exit gap, going through several times before it can be executed.
