### ISSUE TITLE
[AC] [Bug] [Core] NPCbots Name Appearing Twice in Tooltip Instead of Race/Class

### ISSUE THREAD

**Issue by RedMageofRed** [trickerer/Trinity-Bots#778]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Bots display their name instead of their race/class on the HUD when grouped up. Also, I'm not sure if this is related or not, but Recount doesn't seem to be capturing the bots' damage like it did in the past.

![image](https://github.com/trickerer/Trinity-Bots/assets/50994703/52e8136b-e07b-43b3-a258-a762e6b94f5f)

### Expected behaviour

Bots should display their race and class instead of their name when grouped up, i. e. "Level 1 Undead Warrior"

### Steps to reproduce the problem

1) Build, create account, log in, create character
2) type .npcbot spawn 70003 (or any npcbot)
3) Hire NPCbot
4) Group with NPCbot
5) Mouseover the bot and check the HUD pop-up

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. 44cd1525faba 2024-04-13 08:13:04 +0700 (npcbots_3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

### Operating system

Win10

**Comment by trickerer** [comment]
Client doesn't query server for this info, probably because it identifies bots as creatures locally.
Sorry but I think this will never be fixed without client modification.
