### ISSUE TITLE
[TC] [Crash] [Group] Worldserver crashes when logging out from instance 

### ISSUE THREAD

**Issue by kruchor** [trickerer/Trinity-Bots#779]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Playing with bots in instance leads to crash when logging out from instance. Logging out outside is OK.

Please note I use the solocraft branch but the crash happens also when it is disabled.

(I will recompile with standard branch to test further)

(also thank you for you work !)

### Expected behaviour

No crash is supposed to happen when logging out.

### Crashlog

https://gist.github.com/kruchor/1b9dee2d6b106898cf36c5aca5fad10e

### Steps to reproduce the problem

1) Enter instance with a group of bots
2) Log out

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

TrinityCore rev. 4330923bb424+ 2024-03-04 01:14:44 +0000 (3.3.5-solocraft branch) 
NPCBots v5.4.129a. Merge. Bugfix

### Operating system

Debian 12

**Comment by trickerer** [comment]
Can't reproduce. I am able to log out normally from an instance with 4 bots in group, also tested when bots didn't finish their teleport to player, with dead bots and in combat.
Either it's solocraft which makes some sensitive changes in code or maybe there is some important details I'm not aware of. Do make a latest build and confirm the crash. Make sure to include a crashlog for that one, too.

**Comment by kruchor** [comment]
Following is crashing :

TrinityCore rev. ee88aadc4788+ 2024-04-13 23:19:36 +0000 (3.3.5-solocraft branch)
NPCBots v5.4.176a. Merge

This one too : 

TrinityCore rev. 12bb3efea6af+ 2024-04-15 21:12:55 +0200 (3.3.5 branch)
NPCBots v5.4.176a. Merge

=> see https://gist.github.com/kruchor/a9cef0001bd059568a7f1edb74dfc8d7

So it's not related to Solocraft.

(I compile by patching Trinitycore tree with NPCBots.patch file)

I'll try the following : 

1) compile with https://github.com/trickerer/TrinityCore-3.3.5-with-NPCBots.git instead ;

and/or

2) use a fresh database

**Comment by kruchor** [comment]
1. compile with https://github.com/trickerer/TrinityCore-3.3.5-with-NPCBots.git instead => same issue / crashlog
2. use a fresh database => same issue / crashlog

Tested with multiple accounts / characters ...

Maybe something fancy on my worldserver.conf ... I'll guess I'll have to perform some more tests !

**Comment by trickerer** [comment]
4 months without update. Please confirm that the issue is reproducible on last version of https://github.com/trickerer/TrinityCore-3.3.5-with-NPCBots
