### ISSUE TITLE
[TC] [Question] [Core] Не видно шмот т10 для кастом ботов

### ISSUE THREAD

**Issue by DykeRz** [trickerer/Trinity-Bots#781]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

для Повелителя ужаса и темной охотницы например, как их в т10 одеть?

### TrinityCore or AzerothCore

TrinityCore

**Comment by Parkan1986** [comment]
А разве эти нпс боты не имеют уникальные модели которые ну никак не будут вилять на внешний вид нпсбота?вроде только стандартные классы подвержены изменениямю
