### ISSUE TITLE
[TC] [Question/Feature] [Group/Spell/Core] БГ и арена

### ISSUE THREAD

**Issue by DykeRz** [trickerer/Trinity-Bots#786]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Планируются ли остальные БГ для ботов и арена? Или как это всё активировать? 

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

1

**Comment by trickerer** [comment]
Планируются. Пока никак не активировать.
Копия #643
