### ISSUE TITLE
[AC] [Question] [mod-autobalance] Missing property AutoBalance.CountNpcBots in config file

### ISSUE THREAD

**Issue by azcguy** [trickerer/Trinity-Bots#789]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

How i arrived here:
1. I had azcore clean, all works and compiles.
2. Installed default (not Trickerers) mod-autobalance.
3. It turned out bugged with npc-bots
4. Replaced it with autobalance-npcbots
5. cleared cache in cmake, reconfigured, rebuilt, replaced config file

Issue:
Upon wserver start, i get the following messages:

```
Loading Modules Configuration...
> Config::LoadFile: Found incorrect option 'AutoBalance.CountNpcBots' in config file 'configs/modules/AutoBalance.conf'. Skip
> Config::LoadFile: Found incorrect option 'AutoBalance.Enable.World' in config file 'configs/modules/AutoBalance.conf'. Skip
```

and later

```

> Version DB world:     ACDB 335.11-dev
> Config: Missing property AutoBalance.CountNpcBots in config file configs/worldserver.conf, add "AutoBalance.CountNpcBots = 1" to this file or define 'AC_AUTO_BALANCE_COUNT_NPC_BOTS' as an environment variable.
> Config: Missing property AutoBalance.Enable.World in config file configs/worldserver.conf, add "AutoBalance.Enable.World = 0" to this file or define 'AC_AUTO_BALANCE_ENABLE_WORLD' as an environment variable.

```

It seems the server is confused about where to look for those parameters.
What should i do?

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. 61863ebd61cb+ 2024-04-28 19:20:20 +0700 (npcbots_3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

### Operating system

Win10

**Comment by trickerer** [comment]
The only idea I have is maybe it checks both `.conf` and `.conf.dist` files
