### ISSUE TITLE
[AC] [Bug] [Core] NPCBots stopped recognizing available equipment in my bags.

### ISSUE THREAD

**Issue by JasonDayspring** [trickerer/Trinity-Bots#790]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

In the deadmines, and I have loot turned up to not have to grind to find good gear, I noticed my bag was full, so in a hurry, I went through and clicked through the autoequip menus giving my bots anything they would take.  Sold everything left, and moved on.  After that point, none of the bots would recognize that I had gear to offer.  I thought it might have just been that they had better gear (No idea how that works.) and didn't want downgrades, but I noticed they also weren't accepting rings when they had empty slots.

I'll add more info if the problem clears up.

### Expected behaviour

Items in bag did show in the autoequip menu before.

### Crashlog

N/A

### Steps to reproduce the problem

Unsure how to reproduce, as issue is still ongoing. 
Edit: Leaving the Deadmines seems to have cleared the issue, I will add in if problem occurs again.

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. fb70058eb425 2024-04-18 09:30:13 -0600 <npcbots branch> <Win64, RelWithDebinfo, Static> <authserver>

### Operating system

Win 7

**Comment by trickerer** [comment]
No way to reproduce in 3 months, closing
