### ISSUE TITLE
 [AC] [Bug] [Core]The returned equipment after NPCBOTS's automatic dismissal cannot be obtained from the mailbox.

### ISSUE THREAD

**Issue by moncat2005** [trickerer/Trinity-Bots#792]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

A problem was found that the returned equipment after NPCBOTS automatic dismissal could not be obtained from the mailbox.
When you open the email to pick up the equipment, some of the equipment will indicate that it is not yours and cannot be obtained.
My guess is that when you equip the NPCBOTS, the equipment is not tied to the player itself.
As a result, there is an obstacle to picking up through the mailbox.

At the same time, I will also find that if I rehire the original npcbots, I will find that his equipment is still there.

### Expected behaviour

I hope this issue can be fixed. After dismissal, NPCBOTS will automatically clear and restore default equipment, and players can also obtain returned equipment normally.
thank you！

### Steps to reproduce the problem

1. After obtaining the equipment, do not bind it and send it directly to NPCBOTS.
2. The offline time of the player exceeds the npcbots firing cycle.
3. Confirm that npcbots has been automatically fired.
4. Go to the mailbox to pick up the returned equipment interface and find that it cannot be obtained, indicating that it is not the player's equipment.
5. According to the return reminder of the mailbox, the player re-hired the NPCBOTS with the original name and found that the original equipment was still on him.

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. 461f11ec09bc 2024-04-13 22:05:21 +0800 (npcbots_3.3.5 branch)

### Operating system

Ubuntu 18.04

**Comment by trickerer** [comment]
Damn

**Comment by trickerer** [comment]
Should be fixed in https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/f758b14b482903b8dc4ee13b0321a8f8e7605381
