### ISSUE TITLE
[AC] [Bug] [Core] NPC Bot Item Stay Equiped on expire

### ISSUE THREAD

**Issue by jacatinelord** [trickerer/Trinity-Bots#794]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

NPC Bot's item stay within the NPC Bot's Data after expiring. When you re-hire, the npc bot's equipment remain there and you also got email that the item has been sended due to bot expiring.

### Expected behaviour

This should not happening, the bot's equipment should be disappear

### Steps to reproduce the problem

- Set the expiration time to 5 second
- hire a bot and give it equipment
- logout character
- restart server
- login
- hire the expired bot (the name can be checked via mail)
- the item is still equiped by the bot

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. 88622e5efdf5+ 2024-05-07

### Operating system

Win Server 2019

**Comment by trickerer** [comment]
This issue was already fixed in https://github.com/trickerer/Trinity-Bots/commit/fb45aef94f49a884d214e385c9bc3a7b0644f94f (AC https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/f758b14b48)
Update your core

**Comment by jacatinelord** [comment]
Thank you, i remember i was merging lastest version a day before posting the isse. I dont know why it does not included.
It was fixed at some point.
