### ISSUE TITLE
 [AC] [Bug] [Core] NPCBots Cant: Follow, Fight, Equip(?)

### ISSUE THREAD

**Issue by lachyjp** [trickerer/Trinity-Bots#797]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

**CONTEXT:**
I've tried recompiling twice and don't seem to get any obvious errors in my console.

I'm running on a Debian 12 Linux VM and everything else except NPCBots runs smootly. I had it working maybe for about a week at the beginning, then it stopped working, possibly as I was doing more configurations and adding the FactionFree module, but I can't confirm that's the issue.

**ISSUES**: 
Basically, when I hire a NPCBot, they will 'follow' up to the side of me, then stop completely. Using the Netherbot Addon, I can use RECALL for the bot to walk to me, but if I use STAND or STOP it goes back to its spawn point.

I also am not sure if this is expected behaviour but when trying to equip armour or weapons, it doesn't seem to update the model visually.

https://github.com/trickerer/Trinity-Bots/assets/87349643/f164d5b3-8dd7-420f-b1dc-51f8e0242b03

lls

**CONSOLE STARTUP NPCBOT INFO:**

```
Starting Map System
Starting NpcBot system...
>> Bot spellInfo overrides generated for 53 spe
>> Bot appearance data loaded
>> Bot race data loaded
>> Bots transmog data is not loaded. Table `characters_npcbot_transmog` is empty!
>> Loaded 0 npcbots. Table `characters_npcbot` is empty!
Setting up wander map...
No valid Neutral spawn node for at least level 60 on non-continent map 30.
No valid Neutral spawn node for at least level 60 on non-continent map 489.
No valid Neutral spawn node for at least level 60 on non-continent map 529.
>> Loaded 5039 bot wander nodes (0 disabled) on 7 maps (total 474 tops) in 202 ms
Sorting wandering bot's gear...
>> Loaded 60 disabled wandering bots gear items
>> Sorted wandering bots gear in 6 ms
Loading NPCBot group members...
>> Loaded 0 NPCBot group members. DB table `characters_npcbot_group_member` is empty!
Loading NPCBot items storage...
>> Loaded 0 NPCBot stored gear items. DB table `characters_npcbot_gear_storage` is empty!
Starting Game Event system...
```

### Expected behaviour

Work as intended, follow, fight back against mobs, and be able to equip armour.

### Steps to reproduce the problem

I believe it may be a install or config issue, steps to reproduce is just using the mod as normal.

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. 01bd645beb48+ 2024-05-10 21:26:30 +0000 (npcbots_3.3.5 branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon)  

### Operating system

Debian 12

**Comment by trickerer** [comment]
Try spawning a bot, then restarting the server, maybe there is a problem with that again. If it doesn't help set logging level for NPCBots in worldserver.conf to debug and see if you get any useful output in console (`Logger.npcbots`)

**Comment by lachyjp** [comment]
Thanks for the quick reply, I tried restarting and it didn't work (Done this a few times over couple weeks)

In worldconfig I've added
Appender.NpcBots=1,5,0
Logger.npcbots=5,NpcBots Server

Im looking at my worldserver terminal and nothing new is appearing at startup or when interacting with the NPCBot?

**Comment by lachyjp** [comment]
Just had another look at the Faction Free mod I'm using and it instructed me to change these lines in my database, could it be related? I ran a SQL check provided by the author to see if it clashed with anything but maybe I didn't do it correctly. https://github.com/gitdalisar/mod-Faction-Free

<html><body>

Location (table) | Column (attribute) | Values Used
-- | -- | --
creature_template | entry | 500,000-500,001
gameobject_template | entry | 500,000-500,004
broadcast_text | ID | 500,000-500,001 and 500,003
npc_text | ID | 500,000-500,001 and 500,003
creature | GUID | 5,000,000-5,000,019
gameobject | GUID | 5,000,000-5,000,049


</body>
</html>

Could it be related maybe?

**Comment by trickerer** [comment]
No this isn't it. It's the file replacement that does it, `PlayerUpdates.cpp`. If you want to make both mods work together you'll have to go through bots version of `PlayerUpdates.cpp` looking for 'npcbot' and manually patch FactionFree's file accordingly. Or apply FactionFree's replacement to clean AC first and then try to patch it with npcbots.

**Comment by lachyjp** [comment]
Ah got it, that will put me on the right path then. Thanks I'll have a look at it!

**Comment by lachyjp** [comment]
Finally got the time to have a crack, it worked like a charm by patching NPCBots into Faction Free, was very easy since it was only a few lines. Thank you!
