### ISSUE TITLE
"What happened to me" filter in combat log does not exclude log from bots

### ISSUE THREAD

**Issue by jiayuandeng** [trickerer/Trinity-Bots#80]
Sometimes when I die, I look into the "What happened to me" tab in combat log to find the cause of death, but the tab is not filtering out log from bots, and the bots are generating logs so quickly that it is almost impossible to find any useful information about myself. I think this is so because bots are considered player's minions. Is it possible to change the behavior and only show player's log in "What happened to me"?

**Comment by trickerer** [comment]
It's not possible as far as I know, and even if it were - not worth it to change a fundamental concept to fix some logging functionality.

There is a workaround though. All you need to do is go to your combat log filter settings and adjust your filter by disabling all message sources but 'Me' in both columns.
