### ISSUE TITLE
[AC] [Bug] Mage portal misspelling and missing portals

### ISSUE THREAD

**Issue by jasongdove** [trickerer/Trinity-Bots#802]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

1. `Exodar` is misspelled as `Exordar` https://github.com/trickerer/Trinity-Bots/blob/56be2b4a677bcc322dfc2c7e03d3255ae096516c/AC/SQL/updates/world/2024_03_19_00_npc_text.sql#L11

2. `Theramore` and `Stonard` portals are missing from mage bots

### Expected behaviour

1. `Exodar` should be spelled correctly
2. Mages should offer portals to `Theramore` and `Stonard` as appropriate

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. 2031358c01a4+ 2024-05-18 14:09:35 +0700 (npcbots_3.3.5 branch) (Unix, RelWithDebInfo, Static) (authserver)

### Operating system

Docker on Ubuntu 22.04.3 LTS

**Comment by trickerer** [comment]
- Roger on the typo
- Bots don't get portals to `Theramore` and `Stonard`, that's intended
