### ISSUE TITLE
[TC] [AC] [Question/Feature] [Group/Spell/Core] ISSUE_TITLE

### ISSUE THREAD

**Issue by Machalote** [trickerer/Trinity-Bots#803]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

I installed the mod and everything went great but when I try to start worldserver this error shows up:  Applying update "2023_05_26_00_characters_npcbot_transmog.sql" '3304DE8'...
ERROR 1146 (42S02) at line 2 in file: 'C:\Overworld2\Azerothcore_build\data\sql\custom\db_characters\2023_05_26_00_characters_npcbot_transmog.sql': Table 'acore_characters.characters_npcbot_transmog' doesn't exist♪◙
Applying of file 'C:/Overworld2/Azerothcore_build/data/sql/custom/db_characters/2023_05_26_00_characters_npcbot_transmog.sql' to database 'acore_characters' failed! If you are a user, please pull the latest revision from the repository. Also make sure you have not applied any of the databases with your sql client. You cannot use auto-update system and import sql files from AzerothCore repository with your sql client. If you are a developer, please fix your sql query.

(I installed the last version of the repository)
Any ideas of how can be resolve? Than you so much for the mod is really fun.

### TrinityCore or AzerothCore

AzerothCore

### Operating system

Win 10

**Comment by Machalote** [comment]
Hmm then one way to fix this is reinstalling this the server from 0?

I would do that if needed

**Comment by trickerer** [comment]
Yes. All you need to do is delete all three `acore_...` DBs

**Comment by Machalote** [comment]
Okeeey thank you so much for the help
