### ISSUE TITLE
[AC] [Question/Feature] NPCBots after entering to the dungeon/raid losing Mana

### ISSUE THREAD

**Issue by aelblade** [trickerer/Trinity-Bots#804]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

NPCBots after entering to the dungeon/raid losing Mana and bcs of that not using spells/heal/dmg, also they're level changing to the "skull", I don't understand what the problem and how to resolve the issue, installed via instruction and looked upon config, have no idea how to fix that, any solution about that please?
![wow_PQaKlokuX3](https://github.com/tric
![wow_fFBEVpYEHk](https://github.com/trickerer/Trinity-Bots/assets/48015861/78d4979f-2de7-4551-a19e-bc7f09d2c516)
kerer/Trinity-Bots/assets/48015861/519c762b-b0b0-4f37-b109-b04dc6232045)

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. 79b975d9c91a 2024-05-20 19:24:45 +0700 (npcbots_3.3.5 branch)

### Operating system

Win11

**Comment by trickerer** [comment]
Do you use autobalance? https://github.com/trickerer/Trinity-Bots/issues/735

**Comment by aelblade** [comment]
> Do you use autobalance? #735

ty so much for the answer, I'll try, sorry for bothering you, didn't see that post before, i'm blind ;(
