### ISSUE TITLE
[TC] [Bug] [Core] Команда боту на сбор кожи (шкуры) с мобов

### ISSUE THREAD

**Issue by DykeRz** [trickerer/Trinity-Bots#809]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Если дать боту команду на сбор кожи с мобов, периодически с одного и того же моба бот снимает кожу несколько раз (доходило до 15 раз)

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

TrinityCore rev. b0aa08fd3081 2024-05-24 12:57:24 +0300 (main branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon)

### Operating system

debian 12

**Comment by trickerer** [comment]
Нужно больше деталей. О каких именно мобах речь? Как часто происходит (1 раз на сколько мобов)? Я попробовал на 20 мобах и ничего такого не вижу

**Comment by trickerer** [comment]
Возможно связано с #793

**Comment by DykeRz** [comment]
Чаще всего на нордскольских люторогах было, точное количество мобов сказать не могу, но примерно раз в 30 мобов или около того
В Гундраке такое было на мобах перед ластом, если не ошибаюсь, там 4 люторога с наездниками

Ещё этот баг заметил на медведях в драконьем погосте возле входа в подземелья с нерубами

**Comment by trickerer** [comment]
Так и не обнаружил подобной проблемы нигде.
Нет такой ревизии https://github.com/trickerer/TrinityCore-3.3.5-with-NPCBots/commit/b0aa08fd3081
Вынужден списать на кастомный код
Закрыто
