### ISSUE TITLE
[TC] [Bug] [Core] Регистрация БГ несколькими игроками

### ISSUE THREAD

**Issue by DykeRz** [trickerer/Trinity-Bots#810]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Если игрок зарегестрировал и пошёл на БГ против ботов, то следующий игрок и далее уже не могут попасть на БГ с ботами, их регестрирует как в обычном чистом ТК, т.е. как одного игрока в очереди, без ботов.
Т.е. для следующих игроков ядро не добавляет ботов в БГ, и тем самым только один игрок может играть на БГ против ботов, остальным приходится ждать когда он закончит БГ

У меня установлено 11к ботов, с кол-вом проблем нет

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

TrinityCore rev. b0aa08fd3081 2024-05-24 12:57:24 +0300 (main branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon)

### Operating system

debian 12

**Comment by trickerer** [comment]
Это конечно можно поправить, но только если существующие БГ этого типа и уровня полность заполнены (или если игрок или его группа могут присоединиться), иначе дополнительно сгенерированные боты пойдут сначала туда, а не на новый матч.

Всё потому что сгенерированные боты подаются на очередь как обычные игроки, а уже существующий алгоритм выбирает кого куда приглашать. Проблема в том что сам алгоритм выбора участников математически не тривиален, так что вмешиваться в него я не спешу.

В общем чтобы точно была польза от фикса лучше поставить максимальное заполнение БГ ботами, так как иначе подобная ситуация будет повторяться, хоть и реже.

**Comment by trickerer** [comment]
https://github.com/trickerer/TrinityCore-3.3.5-with-NPCBots/commit/86c6c26bba6725336c3742e7ba2285e782b32a4d проверял только на ТС
