### ISSUE TITLE
[AC][Bug][Core] NPCBOTS have weird face and clothing bug

### ISSUE THREAD

**Issue by lbcomposer** [trickerer/Trinity-Bots#811]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

NPCBOTS, particularly Human and Night elves so far, have distorted face textures and clothing textures.  The draenei and custom classes look great.  I've tried 10 different NPCBOTS of different classes, all either night elf or human, male or female, same face bug.  They perform fine, it's just the textures that are off.  

Repack TrinityCore NPCBots + Eluna + Extras [335a Solo/LAN] 2022 is what I am using.

### Expected behaviour

The textures should be normal like other NPCs.

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

TrinityCore rev. 504fcfb2fdd0+ 2022-09-23 09:42:26 -0500 (3.3.5 branch) (Win64, Release, Static) (worldserver-daemon)

### Operating system

Windows 10

**Comment by DykeRz** [comment]
Seems it's because of custom client patch for character's/NPCs

**Comment by lbcomposer** [comment]
What patch?   Do you know?

**Comment by Day36512** [comment]
How would they know since you're the one who added it?

**Comment by lbcomposer** [comment]
I found the offending patch and changed clients and it worked.  @Day36512 stay friendly ok.
