### ISSUE TITLE
 [AC] [Bug] [Core] NPcbots experienced equipment loss issues

### ISSUE THREAD

**Issue by moncat2005** [trickerer/Trinity-Bots#812]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Received player feedback:
This week, there have been two incidents of NPCBOTS equipment loss.
A certain player hired 9 NPC bots, and the equipment of 5 robots was lost together.
When it is discovered that equipment is lost, players must re-enter the game and only have 2 pieces of equipment left on the npcbots who have lost their equipment.

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore-wotlk-with-NPCBots 68261d1  2024-05-21

### Operating system

Ubuntu 18.04

**Comment by trickerer** [comment]
This is the first time I hear about bot items disappearing. Bot items are updated immediately in DB upon equipping. Bot AI never deletes items from DB, only updates item owner. So item was either deleted from item_instance table or bot's corresponding column in characters_npcbot was nullified. Another possiblity is that item wasn't loaded properly since some of them did resurface for some reason. Theoretically item could get deleted when sent back by freed bot and not picked up in 30 days since there is nowhere to send it back when mail expires but I don't think this is the case here.

I have some bots with very old equipment and never had issues besides items return bugs where item could've been received twice if wasn't properly removed from bot when sent by mail.

All I can do right now is add some debug code for you to track possible errors with equipment load if it's missing in item_instance but is assigned to bot's inventory slots

**Comment by trickerer** [comment]
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/4ecbc6fe8977aacdf8030d529696884cec989ea1 Should report an error if you player actually has given those items to the bot which then disappeared.

After https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/31de56c5d3c5e570e3d8fa2569b792f530319c9e all bot equip / unequip actions will be automatically logged to DB. You can include the logs table dump if you get such a report again, I'll also need bot id and owner player guid.

**Comment by moncat2005** [comment]
I am planning to test it with the 5/29 update.
In addition, there is another feature about lost equipment:
This issue mainly occurs after I restart or shut down WorldServer to update the WorldServer version and enable it to run.

**Comment by moncat2005** [comment]
Once again, NPC equipment is lost, along with the player character itself.
It's still the player who was lost before, other players have no problem.
[characters_npcbot_logs.xls](https://github.com/user-attachments/files/15582558/characters_npcbot_logs.xls)

**Comment by moncat2005** [comment]
Once again, NPC equipment is lost, along with the player character itself.
It's still the player who was lost before, other players have no problem.
[characters_npcbot_logs.xls](https://github.com/user-attachments/files/15582558/characters_npcbot_logs.xls)

**Comment by moncat2005** [comment]
Once again, NPC equipment is lost, along with the player character itself.
It's still the player who was lost before, other players have no problem.
[characters_npcbot_logs.xls](https://github.com/user-attachments/files/15582558/characters_npcbot_logs.xls)

**Comment by trickerer** [comment]
So the issue is caused by deleted character then?
What error(s) exactly did you get? What is the bot id in question?

**Comment by moncat2005** [comment]
I now suspect that the player has used a hacked client, which has a destructive function of automatically deleting character related equipment when offline, because at the same time, this guy also reported that his character equipment is also gone.

**Comment by trickerer** [comment]
Try after https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/fa643558745912620ccd1e6edc1b48e9afb0aa37

**Comment by moncat2005** [comment]
New situation: The employment intermediary NPC shows that the available NPCBOTS is already 0.
After restarting WorldServer, the employment intermediary interface will resume displaying the number of NPCBOTS to be hired normally.

**Comment by moncat2005** [comment]
Do you need to add an NPCBOTS termination date/former employer information in the log?
If someone hires npcbots at the hiring agency and then fires them, it seems that these npcbots will not return to the hiring agency list until the server restarts?

**Comment by trickerer** [comment]
No, I can investigate without that info. It's probably because of EnrageOnDismiss config since the buff will never fade.

**Comment by trickerer** [comment]
I assume the original issue has disappeared?

**Comment by moncat2005** [comment]
The player has not provided any further feedback on this issue.
