### ISSUE TITLE
[AC] Every time I rehire a robot, it's very troublesome to configure its equipment, so I hope there can be a more convenient feature.

### ISSUE THREAD

**Issue by 1825679767** [trickerer/Trinity-Bots#813]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Every time I rehire a robot, it's very troublesome to configure its equipment, so I hope there can be a more convenient feature.
I hope to add a new equipment library NPC for pre-configuring the equipment of robots. The main functions are implemented as follows: After talking with the NPC, a dialog box pops up, allowing you to choose a profession. After choosing a profession, the corresponding submenu allows you to configure multiple equipment (Set 1, Set 2, Set 3......). After the player hires the robot, the robot can directly wear from the configured equipment. After being dismissed, the robot's equipment is directly returned to the weapon library.

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. 306434e81139+ 2024-05-20

### Operating system

win11

**Comment by Badgermilk0** [comment]
@1825679767 
While Trickerer evaluates if this should be implemented, you could test this: 
https://github.com/Day36512/Npcbot_Extended_Commands
(Requires: https://github.com/azerothcore/mod-eluna)

**Comment by trickerer** [comment]
Keeping equipment sets for the bots as WoW client does for players is possible but honestly sounds like a pretty big feature. It also could be clunky since it has to use the same gossip menu. And of course I'm not implementing anything involving creating items for the bots out of thin air in any way.
Re-hiring a bot isn't really something that is intended to happen frequently, unless you use ownership expiration timer, that's why this feature isn't a priority at the moment (said moment being last 5 months actually).

**Comment by 1825679767** [comment]
This does not create equipment out of thin air; instead, it transfers equipment from your own inventory to the equipment storage NPC for safekeeping. After hiring a robot, you can equip yourself with a single click based on the preset configurations.

**Comment by trickerer** [comment]
> This does not create equipment out of thin air; instead, it transfers equipment from your own inventory to the equipment storage NPC for safekeeping. After hiring a robot, you can equip yourself with a single click based on the preset configurations.

Good, because it wasn't 100% obvious from the OP translation.

**Comment by trickerer** [comment]
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/6985a722288bee6313c91e94d1c6a42d50ac806d

**Comment by 1825679767** [comment]
thanks
