### ISSUE TITLE
[AC] [Crash] [Core] Server Crashes on ReputationMgr

### ISSUE THREAD

**Issue by jacatinelord** [trickerer/Trinity-Bots#816]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Greetings, this crash is occured by unknown behaviour because i was not the one causing this crash. But one thing that i know of is, the crash happened 2-5x a week with the same cause: the ReputationMgr.

At first i thought it was not related to the NPC Bot core, and i saw the entire error code and see a NPC Bot's name "Taktungtuang" there and it make me think that this was related to NPC Bot too.

I tried to reproduce the crash by changing reputation point, even doing the at war thing still not causing it.

If you have the time to check, can you check and see what the real problem is? thank you

### Crashlog

https://gist.github.com/jacatinelord/8ad98da14feb79084bf19aa4127c5ccb

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. 4ce85edf0e21+ 2024-05-14 08:44:20 +0800

### Operating system

Win Server 2019

**Comment by trickerer** [comment]
Post a debug crashlog please

**Comment by jacatinelord** [comment]
i did provide a RelWithDeb crashlog, is that not good? because if i compile on debug the server response time is high

**Comment by trickerer** [comment]
> i did provide a RelWithDeb crashlog, is that not good?

No.
Issue template clearly states what kind of crashlog is needed. Some issues can be resolved with only call stack info but not this one.

**Comment by jacatinelord** [comment]
i have been setting it do debug mode and still not receiving same or simmilar reports about this. maybe ill inform once it were occured again. Since debug mode also increase the server input or increase lag

**Comment by Evilanemesis** [comment]
[38fc22da375a_worldserver.exe_[19-6_15-44-56].txt](https://github.com/user-attachments/files/15905733/38fc22da375a_worldserver.exe_.19-6_15-44-56.txt)

Would this one work? I'm also getting this

**Comment by trickerer** [comment]
No, this is RelWithDebInfo

**Comment by jacatinelord** [comment]
I got this fix (maybe), becase it is not happening again for a week. Because of the Grid and map related i check on the log, i decided to increase the map update interval to 1 ms and also increasing the map update threads to 4.
