### ISSUE TITLE
[AC] [wotlk-npcbots] bots not populating 

### ISSUE THREAD

**Issue by PaulRotzien** [trickerer/Trinity-Bots#817]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

I've compiled the server a couple different times, and every time the world doesn't populate with bots and and none are on the list from the NPC. The characters_npcbots table isn't populated. But I can summons them into the world individually. What am I doing wrong?

### TrinityCore or AzerothCore

AzerothCore

### Operating system

Windows 10/11

**Comment by trickerer** [comment]
Nothing is wrong here, you have to spawn bots in order to make them available to players. If you mean wandering bots you have to enable them in config.

**Comment by PaulRotzien** [comment]
The botgivers list shows all zero's for hireable bots. I can spawn them manually, is there a way to make them all hireable through the botgivers?

**Comment by PaulRotzien** [comment]
> The botgivers list shows all zero's for hireable bots. I can spawn them manually, is there a way to make them all hireable through the botgivers?



> Nothing is wrong here, you have to spawn bots in order to make them available to players. If you mean wandering bots you have to enable them in config.

**Comment by PaulRotzien** [comment]
> Nothing is wrong here, you have to spawn bots in order to make them available to players. If you mean wandering bots you have to enable them in config.

The botgivers list shows all zero's for hireable bots. I can spawn them manually, is there a way to make them all hireable through the botgivers?

**Comment by trickerer** [comment]
Botgiver lists spawned bots.
You can spawn bots wherever you want and even hide them altogether using config but they still have to be spawned before they can be hired.

**Comment by PaulRotzien** [comment]
Ah, okay. I've only used them on the dinklepack prior.
