### ISSUE TITLE
Patching fails

### ISSUE THREAD

**Issue by Mr-Deadbeat** [trickerer/Trinity-Bots#82]
TC: 21eb48d87f30885e61a85bca29a2f587f6e6aa80
Bots: 81098e249debe442162e1a9a5b139365dd450bd1

´´´patching file sql/Bots/1_world_bot_appearance.sql
patching file sql/Bots/2_world_bot_extras.sql
patching file sql/Bots/3_world_bots.sql
patching file sql/Bots/4_world_generate_bot_equips.sql
patching file sql/Bots/5_world_botgiver.sql
patching file sql/Bots/characters_bots.sql
patching file sql/Bots/locales/zhCN/npc_text_locale.sql
patching file sql/Bots/updates/characters/2020_05_15_characters_npcbot_NPCBots_4.7.8a-4.7.27a.sql
patching file sql/Bots/updates/characters/2020_06_21_characters_npcbot_43fceb98.sql
patching file sql/Bots/updates/characters/2020_10_08_characters_npcbot_NPCBots_4.7.34a-4.7.39a.sql
patching file sql/Bots/updates/characters/2021_01_04_characters_npcbot.sql
patching file sql/Bots/updates/characters/2021_01_24_characters_npcbot_stats.sql
patching file sql/Bots/updates/world/2020_07_08_creature_template_npcbot_extras.sql
patching file sql/Bots/updates/world/2020_09_25_creature_template.sql
patching file sql/Bots/updates/world/2020_10_14_creature_classlevelstats.sql
patching file sql/Bots/updates/world/2020_10_14_creature_template.sql
patching file sql/Bots/updates/world/2020_10_15_creature_template_npcbot_extras.sql
patching file sql/Bots/updates/world/2020_11_07_npc_text.sql
patching file sql/Bots/updates/world/2020_12_11_npc_text.sql
patching file sql/Bots/updates/world/2021_01_04_npc_text.sql
patching file sql/Bots/updates/world/2021_01_05_npc_text.sql
patching file sql/Bots/updates/world/2021_01_08_npc_text.sql
patching file sql/Bots/updates/world/2021_02_01_npc_text.sql
patching file src/common/Utilities/EventProcessor.h
patching file src/server/database/Database/Implementation/CharacterDatabase.cpp
patching file src/server/database/Database/Implementation/CharacterDatabase.h
patching file src/server/game/AI/CoreAI/UnitAI.cpp
patching file src/server/game/AI/NpcBots/bot_Events.h
patching file src/server/game/AI/NpcBots/bot_GridNotifiers.h
patching file src/server/game/AI/NpcBots/bot_ai.cpp
patching file src/server/game/AI/NpcBots/bot_ai.h
patching file src/server/game/AI/NpcBots/bot_archmage_ai.cpp
patching file src/server/game/AI/NpcBots/bot_bm_ai.cpp
patching file src/server/game/AI/NpcBots/bot_dark_ranger_ai.cpp
patching file src/server/game/AI/NpcBots/bot_death_knight_ai.cpp
patching file src/server/game/AI/NpcBots/bot_dreadlord_ai.cpp
patching file src/server/game/AI/NpcBots/bot_druid_ai.cpp
patching file src/server/game/AI/NpcBots/bot_hunter_ai.cpp
patching file src/server/game/AI/NpcBots/bot_mage_ai.cpp
patching file src/server/game/AI/NpcBots/bot_paladin_ai.cpp
patching file src/server/game/AI/NpcBots/bot_priest_ai.cpp
patching file src/server/game/AI/NpcBots/bot_rogue_ai.cpp
patching file src/server/game/AI/NpcBots/bot_shaman_ai.cpp
patching file src/server/game/AI/NpcBots/bot_spellbreaker_ai.cpp
patching file src/server/game/AI/NpcBots/bot_sphynx_ai.cpp
patching file src/server/game/AI/NpcBots/bot_warlock_ai.cpp
patching file src/server/game/AI/NpcBots/bot_warrior_ai.cpp
patching file src/server/game/AI/NpcBots/botcommands.cpp
patching file src/server/game/AI/NpcBots/botcommon.h
patching file src/server/game/AI/NpcBots/botdatamgr.cpp
patching file src/server/game/AI/NpcBots/botdatamgr.h
patching file src/server/game/AI/NpcBots/botdpstracker.cpp
patching file src/server/game/AI/NpcBots/botdpstracker.h
patching file src/server/game/AI/NpcBots/botdump.cpp
patching file src/server/game/AI/NpcBots/botdump.h
patching file src/server/game/AI/NpcBots/botgiver.cpp
patching file src/server/game/AI/NpcBots/botmgr.cpp
patching file src/server/game/AI/NpcBots/botmgr.h
patching file src/server/game/AI/NpcBots/bpet_ai.cpp
patching file src/server/game/AI/NpcBots/bpet_ai.h
patching file src/server/game/AI/NpcBots/bpet_archmage.cpp
patching file src/server/game/AI/NpcBots/bpet_dark_ranger.cpp
patching file src/server/game/AI/NpcBots/bpet_death_knight.cpp
patching file src/server/game/AI/NpcBots/bpet_dreadlord.cpp
patching file src/server/game/AI/NpcBots/bpet_druid.cpp
patching file src/server/game/AI/NpcBots/bpet_hunter.cpp
patching file src/server/game/AI/NpcBots/bpet_mage.cpp
patching file src/server/game/AI/NpcBots/bpet_priest.cpp
patching file src/server/game/AI/NpcBots/bpet_shaman.cpp
patching file src/server/game/AI/NpcBots/bpet_warlock.cpp
patching file src/server/game/Combat/CombatManager.cpp
patching file src/server/game/Combat/ThreatManager.cpp
patching file src/server/game/Conditions/ConditionMgr.cpp
patching file src/server/game/DataStores/DBCStores.cpp
patching file src/server/game/DataStores/DBCStores.h
patching file src/server/game/DungeonFinding/LFGMgr.cpp
patching file src/server/game/DungeonFinding/LFGScripts.cpp
patching file src/server/game/Entities/Creature/Creature.cpp
Hunk #1 succeeded at 56 with fuzz 2 (offset 3 lines).
Hunk #2 succeeded at 274 (offset 4 lines).
Hunk #3 succeeded at 667 (offset 4 lines).
Hunk #4 succeeded at 712 (offset 4 lines).
Hunk #5 succeeded at 768 (offset 4 lines).
Hunk #6 succeeded at 792 (offset 4 lines).
Hunk #7 succeeded at 807 (offset 4 lines).
Hunk #8 succeeded at 861 (offset 4 lines).
Hunk #9 succeeded at 1058 (offset 4 lines).
Hunk #10 succeeded at 1335 (offset 4 lines).
Hunk #11 succeeded at 1718 (offset 4 lines).
Hunk #12 succeeded at 1767 (offset 4 lines).
Hunk #13 succeeded at 1798 (offset 4 lines).
Hunk #14 succeeded at 1949 (offset 4 lines).
Hunk #15 succeeded at 2067 (offset 4 lines).
Hunk #16 succeeded at 2544 (offset 4 lines).
Hunk #17 succeeded at 2721 (offset 4 lines).
Hunk #18 succeeded at 3353 (offset 5 lines).
Hunk #19 succeeded at 3523 (offset 5 lines).
patching file src/server/game/Entities/Creature/Creature.h
Hunk #2 succeeded at 375 (offset 5 lines).
Hunk #3 succeeded at 498 (offset 6 lines).
patching file src/server/game/Entities/Creature/CreatureData.h
patching file src/server/game/Entities/Creature/TemporarySummon.cpp
patching file src/server/game/Entities/Creature/enuminfo_CreatureData.cpp
patching file src/server/game/Entities/Object/Object.cpp
patching file src/server/game/Entities/Player/KillRewarder.cpp
patching file src/server/game/Entities/Player/Player.cpp
patching file src/server/game/Entities/Player/Player.h
patching file src/server/game/Entities/Totem/Totem.cpp
patching file src/server/game/Entities/Unit/StatSystem.cpp
patching file src/server/game/Entities/Unit/Unit.cpp
Hunk #8 succeeded at 1557 (offset 8 lines).
Hunk #9 succeeded at 1687 (offset 8 lines).
Hunk #10 succeeded at 1798 (offset 8 lines).
Hunk #11 succeeded at 2216 (offset 8 lines).
Hunk #12 succeeded at 2239 (offset 8 lines).
Hunk #13 FAILED at 2272.
Hunk #14 succeeded at 2652 (offset 8 lines).
Hunk #15 succeeded at 2678 (offset 8 lines).
Hunk #16 succeeded at 2738 (offset 8 lines).
Hunk #17 succeeded at 2772 (offset 8 lines).
Hunk #18 succeeded at 2805 (offset 8 lines).
Hunk #19 succeeded at 2849 (offset 8 lines).
Hunk #20 succeeded at 3960 (offset 8 lines).
Hunk #21 succeeded at 5733 (offset 8 lines).
Hunk #22 succeeded at 5837 (offset 8 lines).
Hunk #23 succeeded at 6435 (offset 8 lines).
Hunk #24 succeeded at 6472 (offset 8 lines).
Hunk #25 succeeded at 6758 (offset 8 lines).
Hunk #26 succeeded at 7096 (offset 8 lines).
Hunk #27 succeeded at 7137 (offset 8 lines).
Hunk #28 succeeded at 7170 (offset 8 lines).
Hunk #29 succeeded at 7401 (offset 8 lines).
Hunk #30 succeeded at 7625 (offset 8 lines).
Hunk #31 succeeded at 7770 (offset 8 lines).
Hunk #32 succeeded at 8177 (offset 8 lines).
Hunk #33 succeeded at 8316 (offset 8 lines).
Hunk #34 succeeded at 8405 (offset 8 lines).
Hunk #35 succeeded at 8662 (offset 8 lines).
Hunk #36 succeeded at 9087 (offset 8 lines).
Hunk #37 succeeded at 9169 (offset 8 lines).
Hunk #38 succeeded at 10351 (offset 8 lines).
Hunk #39 succeeded at 10373 (offset 8 lines).
Hunk #40 succeeded at 10762 (offset 8 lines).
Hunk #41 succeeded at 10917 (offset 8 lines).
Hunk #42 succeeded at 11198 (offset 8 lines).
Hunk #43 succeeded at 11387 (offset 8 lines).
Hunk #44 succeeded at 12186 (offset 8 lines).
Hunk #45 succeeded at 12215 (offset 8 lines).
Hunk #46 succeeded at 12253 (offset 8 lines).
Hunk #47 succeeded at 12276 (offset 8 lines).
Hunk #48 succeeded at 12458 (offset 8 lines).
Hunk #49 succeeded at 12524 (offset 8 lines).
Hunk #50 succeeded at 12794 (offset 8 lines).
Hunk #51 succeeded at 13568 (offset 14 lines).
1 out of 51 hunks FAILED -- saving rejects to file src/server/game/Entities/Unit/Unit.cpp.rej
patching file src/server/game/Entities/Unit/Unit.h
patching file src/server/game/Entities/Vehicle/Vehicle.cpp
patching file src/server/game/Globals/ObjectMgr.cpp
Hunk #1 succeeded at 1191 (offset 5 lines).
Hunk #2 succeeded at 8941 (offset 25 lines).
patching file src/server/game/Globals/ObjectMgr.h
Hunk #2 succeeded at 1240 (offset -6 lines).
Hunk #3 succeeded at 1503 (offset -6 lines).
Hunk #4 succeeded at 1668 (offset -6 lines).
patching file src/server/game/Groups/Group.cpp
patching file src/server/game/Groups/Group.h
patching file src/server/game/Handlers/ItemHandler.cpp
Hunk #2 succeeded at 655 (offset 1 line).
patching file src/server/game/Handlers/SpellHandler.cpp
patching file src/server/game/Maps/Map.cpp
patching file src/server/game/Maps/MapManager.cpp
patching file src/server/game/Movement/MotionMaster.cpp
patching file src/server/game/OutdoorPvP/OutdoorPvP.cpp
patching file src/server/game/Scripting/ScriptMgr.cpp
patching file src/server/game/Scripting/ScriptMgr.h
patching file src/server/game/Server/WorldSession.cpp
patching file src/server/game/Spells/Auras/SpellAuraEffects.cpp
patching file src/server/game/Spells/Auras/SpellAuras.cpp
patching file src/server/game/Spells/Spell.cpp
patching file src/server/game/Spells/Spell.h
patching file src/server/game/Spells/SpellEffects.cpp
Hunk #7 succeeded at 3219 (offset -4 lines).
patching file src/server/game/Spells/SpellInfo.cpp
patching file src/server/scripts/Commands/cs_npc.cpp
patching file src/server/scripts/Northrend/Naxxramas/boss_four_horsemen.cpp
patching file src/server/scripts/Spells/spell_dk.cpp
patching file src/server/scripts/Spells/spell_druid.cpp
patching file src/server/scripts/Spells/spell_generic.cpp
patching file src/server/scripts/Spells/spell_hunter.cpp
patching file src/server/scripts/Spells/spell_mage.cpp
patching file src/server/scripts/Spells/spell_paladin.cpp
patching file src/server/scripts/Spells/spell_priest.cpp
patching file src/server/scripts/Spells/spell_rogue.cpp
patching file src/server/scripts/Spells/spell_shaman.cpp
patching file src/server/scripts/Spells/spell_warrior.cpp
patching file src/server/shared/DataStores/DBCStructure.h
patching file src/server/shared/DataStores/DBCfmt.h
patching file src/server/shared/SharedDefines.h
Hunk #1 succeeded at 194 (offset 1 line).
patching file src/server/worldserver/worldserver.conf.dist´´´

compiling works no errors but noticed ingame that i could not access warriors menus at all seemed to work for the other bots i had in party

**Comment by Ryu1254** [comment]
I am not sure, but i use the latest TC commit ed5ec45ed2c023e47f4b32a4c3afb728c83b65ad
with the latest NPCbot Patch for quit a while, I dont have any issues with bot menu.

I already had some weird issues in the past, what I do to fix them is to reset your TC branch and re-apply NPCbot Patch. 

hope this work for you.

**Comment by Mr-Deadbeat** [comment]
> I am not sure, but i use the latest TC commit ed5ec45ed2c023e47f4b32a4c3afb728c83b65ad
> with the latest NPCbot Patch for quit a while, I dont have any issues with bot menu.
> 
> I already had some weird issues in the past, what I do to fix them is to reset your TC branch and re-apply NPCbot Patch.
> 
> hope this work for you.

i reset the build every time i apply the bot patch and the commit you refered to i could not find it ?

anyway only way to fix it was to revert and go back to the previous commit and everything works again but missing the latest fixes to the core code gruul's lair among others :(

**Comment by Ryu1254** [comment]
my bad, i copy the wrong hash. 
i use this one:
https://github.com/TrinityCore/TrinityCore/commit/e2ba73e9a35deeb3fa36b1972b6b53c12c530100

**Comment by Mr-Deadbeat** [comment]
> my bad, i copy the wrong hash.
> i use this one:
> [TrinityCore/TrinityCore@e2ba73e](https://github.com/TrinityCore/TrinityCore/commit/e2ba73e9a35deeb3fa36b1972b6b53c12c530100)

np anyway issue is sorted so closing this added the rejected patch part to the Unit.cpp file and all is well
running on the latest TC commit atm no issues so far :) "knock on wood"
