### ISSUE TITLE
[AC] [Bug] [Spell/Core] Spell Penetration not being recognized by bots with some items

### ISSUE THREAD

**Issue by Day36512** [trickerer/Trinity-Bots#821]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

![image](https://github.com/trickerer/Trinity-Bots/assets/118951051/248d7972-ab4d-4abc-877b-2ae5e99716ac)

Bonked my warlock to see if spell penetration was being considered from an item upgrade. It did not get considered. Item in question uses spellids for stats, so i switched the item to raw stat values and spell pen was picked up then. 

### Steps to reproduce the problem

1} Test on a bot using an item that has spell pen baked in as a spellid rather than raw stat

### TrinityCore or AzerothCore

Azerothcore

### Core rev. hash/commit

AzerothCore rev. 3752ad5da884+ 2024-06-06 14:08:58 -0600 (npcbots_3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

### Operating system

Win10

**Comment by trickerer** [comment]
From testing results: spell penetration stat applies from both spells and item stats, spell auras just aren't taken into account when using /bonk - just a visual bug

**Comment by trickerer** [comment]
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/88bb14dc9a0b970ac139afc35e7737b52f66977c

**Comment by trickerer** [comment]
https://github.com/trickerer/Trinity-Bots/commit/bbc4e92810f7bb9db391a6746b1374b5473e8a11
