### ISSUE TITLE
Spell Text Issue On Web Page

### ISSUE THREAD

**Issue by Jankey7** [trickerer/Trinity-Bots#824]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Your page --->   https://github.com/trickerer/Trinity-Bots?tab=readme-ov-file

It says the below, yet has an error:

NpcBot.OffTankTargetIconsMask

    This parameter is similar to NpcBot.TankTargetIconsMask**, but this one marks targets for your NPCBot off-tanks
    Your off-tanks will not stop attacking pointed target until it's dead or icon is unset

NpcBot.DPSTargetIconsMask

**THE BELOW IS THE INCORRECT PORTION - I believe it should read as the above for obvious reasons and was mistyped.**

    Same as **NpcBot.TankTargetIconsMask**, but this one affects your damage dealers, and (off-)tanks with DPS role enabled without pointed tanking target, with the same rules

### Expected behaviour

N/A

### Crashlog

N/A

### Steps to reproduce the problem

N/A

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

N/A

### Operating system

N/A

**Comment by trickerer** [comment]
English isn't my native language so for me this description makes perfect sense since it was I who wrote this. Each next icon mask description is gradually simplified.

Maybe you could explain your findings in more detail.

If you mean the `(off-)tank` portion of the `DPSTargetIconsMask` description then it just means that besides main DPSers the only bots that also (usually) have DPS role enabled are main tanks and off-tanks. All bots having DPS role enabled check DPS target icon(s), but for tanks their respective tanking icons take priority if present.

**Comment by Jankey7** [comment]
I am sorry, I was tired when I was reading your page, and thought I was looking at headings (the topic with the gray background), and then the syntax below in the description (which didn't match).  I am lost in the NpcBot .xxx syntax stuff, and can't figure out how to get these commands to work based on the descriptions (like in a macro for example, so that I don't have to type out everything when I walk into a room and want to roll through pulls), so I guess I am misunderstanding something (syntax examples are so huge for me).

I will try and check the syntax again to see how to set tanktarget, offtanktarget again, and especially that dang nodpstarget (in BRD these idiots kill the princes no matter if I put a skull on the boss or not, which is so annoying, so trying to finish that quest was complete hell).

One thing I didn't see was a tanking "priority" anywhere.  If skull, X, circle, star, square, triangle, and diamond are used, what order do they kill in?  Can you add that to your page so we understand their kill order?  Do they by any chance follow these rules on this link? https://wowwiki-archive.fandom.com/wiki/Target_markers (example diamond = banish)?

**Comment by trickerer** [comment]
> One thing I didn't see was a tanking "priority" anywhere. If skull, X, circle, star, square, triangle, and diamond are used, what order do they kill in? Can you add that to your page so we understand their kill order? Do they by any chance follow these rules on this link? https://wowwiki-archive.fandom.com/wiki/Target_markers (example diamond = banish)?

No they don't follow the priority listed at that wiki page.
The order is mentioned below icon targeting types, after `NoDPSTargetIconMask`:

"""
- `Heal / Tank / DPS _TargetIconsMask` priorities
    - For every pointed target type priority goes from _Skull_ (highest) to _Star_ (lowest)

"""
i.e. priority goes in reverse order from how icons are listed in right-click dropdown menu

**Comment by Jankey7** [comment]
THANK YOU!!!  You stated Skull to Star, and I had read that, but it left
out everything between.  I didn't realize it was a backward version of the
drop down list, which now makes sense.  In all honesty, some of us really
appreciate having more explicit info to make sure we know exactly what to
expect.

Have a great week,

Jared
