### ISSUE TITLE
[AC] [Question/Feature] [Core] Would be cool to be able to select what classes to allow to be wandering bots

### ISSUE THREAD

**Issue by Purple-23** [trickerer/Trinity-Bots#825]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

You can already split number of wandering bots (total) by percentage in level bracket, but it would be cool to break down by classes.  Say, I don't want any DKs at all, it would be cool to remove them from the wandering table entirely.  Or if at the early 0-10 levels, only see a couple warriors.

Best I can think of, now, is manipulating the SQL tables which is a lot of work.

### TrinityCore or AzerothCore

AzerothCore

### Operating system

Win11

**Comment by trickerer** [comment]
Another half-assed solution is to disable the class altogether. Disabled classes will not get selected for wandering bot generation.

I don't think I'll do this per level bracket.

**Comment by Purple-23** [comment]
Yeah I was hoping to still have them for hiring at the vendor bot. 

I wrote a script in SQL I thought would work in clearing the wandering table of premade bots and then I could manually add in like 5 but it didn't work. 

DELETE FROM creature_template WHERE name LIKE '%Death Knight Bot%';
UPDATE creature_template SET ScriptName = '' WHERE ScriptName = 'death_knight_bot';

**Comment by Parkan1986** [comment]
> ### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE
> * [x]  I understand that my issue may get **closed without notice** if I _intentionally_ remove or skip any mandatory* field
> * [x]  This is NOT a bug/crash report
> * [x]  I've searched the bugtracker for similar questions/requests **including closed ones**
> 
> ### Description
> You can already split number of wandering bots (total) by percentage in level bracket, but it would be cool to break down by classes. Say, I don't want any DKs at all, it would be cool to remove them from the wandering table entirely. Or if at the early 0-10 levels, only see a couple warriors.
> 
> Best I can think of, now, is manipulating the SQL tables which is a lot of work.
> 
> ### TrinityCore or AzerothCore
> AzerothCore
> 
> ### Core rev. hash/commit
> _No response_
> 
> ### Operating system
> Win11

Does this is not enought for you?
NpcBot.Classes.<Class>.Enable
#        Description: Allow players to hire bots of certain classes.
#        Note:        Some non-standard class abilities may be unbalanced or game breaking.

There is already settings present where turn on/off class

**Comment by trickerer** [comment]
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/90d3602c6fd11033ee8f723845e7c0644986ba9b

**Comment by trickerer** [comment]
https://github.com/trickerer/Trinity-Bots/commit/93e6655356ae8d9e614fa17c48feb3998163133c
