### ISSUE TITLE
[TC] [Bug] [Spell] Некоторые спеллы игрока увеличивают слишком мало ХП и АП ботам

### ISSUE THREAD

**Issue by DykeRz** [trickerer/Trinity-Bots#826]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Спелл от предмета https://base.opiums.eu/?item=49633

не даёт боту 8% как заявлено, ощущение что оно даёт ему всего 1%

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

9e0b579

### Operating system

debian 12

**Comment by DykeRz** [comment]
Так же плохо работает крик вара на бота и паладиновское благословение королей, прибавляет всего лишь 110 хп

**Comment by trickerer** [comment]
На https://github.com/trickerer/TrinityCore-3.3.5-with-NPCBots/commit/dd332040918a21a57a5d5fa460527ba4a9b8e60c:
- Варотанк 80 уровня без шмота
- Крик варотанка даёт около 2800 хп
- Барабаны на 8% статов дают 146 хп (стамина 183 -> 197)
- Крик на АП даёт около 700 АП

Похоже проблема где-то на твоей стороне
![s1](https://github.com/trickerer/Trinity-Bots/assets/1254989/a498b888-bd64-4a55-a7f6-6f48c47ce1ca)
![s2](https://github.com/trickerer/Trinity-Bots/assets/1254989/824f177f-9174-42f1-911b-a4bd3d236998)
![s3](https://github.com/trickerer/Trinity-Bots/assets/1254989/651768e8-fa3e-4c52-af94-03304d6e186d)

**Comment by DykeRz** [comment]
Из-за твоего автобаланса может быть?

**Comment by trickerer** [comment]
Не знаю. Пиши весь список используемого дополнительного кода.

**Comment by DykeRz** [comment]
> Не знаю. Пиши весь список используемого дополнительного кода.

Твой автобаланс для ботов, арена 1 на 1, самописный код для подарков с лвлапом игрокам, код на кастом баф игрока при лвлапе,всё

а ты попробуй не ботом бафы кидать, а именно ты крик на него заюзай

**Comment by trickerer** [comment]
> а ты попробуй не ботом бафы кидать, а именно ты крик на него заюзай

Пробовал оба

**Comment by trickerer** [comment]
Руки дошли, проверил с автобалансом.
![AB_shout](https://github.com/user-attachments/assets/c7d26711-9653-4d6f-91c0-e975a08fadf2)

Как видишь такой же голый вар получает нормальное количество ХП.
Закрыто.
