### ISSUE TITLE
[CMANGOS] [NPCBots] NPCBots implementation to CMaNGOS TBC

### ISSUE THREAD

**Issue by d3athbl0w** [trickerer/Trinity-Bots#827]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

The implementation of NPCBots to CMaNGOS TBC or Vanilla would be great. Currently CMaNGOS has a playerbot system but personally the NPC Bots help a lot in both PvE and PvP

### TrinityCore or AzerothCore

Both

### Core rev. hash/commit

CMaNGOS LastRev

### Operating system

All Operation System

**Comment by trickerer** [comment]
There is no plans for that currently
