### ISSUE TITLE
Suggestion for improvement for Tanking

### ISSUE THREAD

**Issue by Mr-Deadbeat** [trickerer/Trinity-Bots#83]
built in or config option for engagement timers DPS and Healing
this would give more time for Tank to build aggro before bots engage

2 timers one for DPS and the other one for healing
sometimes Healing is needed instantly so individual timers is the best option

**Comment by trickerer** [comment]
There is already a check if tank has enough threat on the boss which supposed to prevent other bots to engage right away. It only works in raid dungeons though. And it doesn't work for unusual cases where boss is pure caster and doesn't target anything.

Do you have problems with some particular boss or situation?

**Comment by Mr-Deadbeat** [comment]
hence it might be a good idea to have a configurable switch / switches for when they are allowed to engage the situation i ended up in was that the second i pulled trash mobs or out in the world running about the bots engage directly so never give me any time to build up threat with a configuration option you can fine tune it for the response time you need only time i have had issues tanking is with warrior since they need to build threat by sundering each and every mob combined with heroic strikes and shield slams using challenging shout only to gather large groups where they might sneak off before i can grab them

have not had a chance to raid with the Warrior as of yet he is only level 49 atm just thought i should mention that
tanking with paladin or DK is a walk in the park compared to warrior since they use AOE to grab threat lol

timer would make it easier for normal dungeons as well we are talking about response times of 5 to 20 seconds tweaking it if necessary 20 being absolute max this is just a suggestion so your call in the end :) as always

**Comment by trickerer** [comment]
Ok I get it. I don't remember if it works in non-raid groups, but try to use /mt on yourself, so bots will see you as a tank and not try to defend you at all costs

**Comment by Mr-Deadbeat** [comment]
> Ok I get it. I don't remember if it works in non-raid groups, but try to use /mt on yourself, so bots will see you as a tank and not try to defend you at all costs

i tested it while doing Zul'Farrak and it made no difference sadly might be that /mt does not work outside of raids i don't remember either lol

although once i got vigilance life improved slightly i can maintain threat a little bit easier but at times they still run all over the place Warrior is not at his full potential yet either so might be things improve even more the higher he gets
