### ISSUE TITLE
[TC] [AC] [Bug/Crash] [Group/Spell/Core] Сервер крашиться при попытке создать нового нпсбота

### ISSUE THREAD

**Issue by Parkan1986** [trickerer/Trinity-Bots#832]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

при поптыке создать нового нпс бота сервак крашиться с такой ошибкой:
[1054] Unknown column 'modelid1' in 'field list'
Your database structure is not up to date. Please make sure you've executed all queries in the sql/updates folders.

Похоже создание нового нпс бота лезет в creature_template и не может найти эти столбы т.к их перенесли в другую таблицу.

### Expected behaviour

Не должно крашиться при создании нпс бота

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

863b172cf69e 2024-06-23

### Operating system

Win10

**Comment by DykeRz** [comment]
создай эту колонку где оно требует)

**Comment by trickerer** [comment]
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/056526c74bf4bcc1f05b84231108c8ab755a42fd
