### ISSUE TITLE
[TC] [Crash] [Core] Fix crash

### ISSUE THREAD

**Issue by DykeRz** [trickerer/Trinity-Bots#833]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Фикс краша

[log2024-06-23-14-58-59.log](https://github.com/user-attachments/files/15945495/log2024-06-23-14-58-59.log)

Заменить в Unit.cpp

ASSERT(!m_aiLocked, "Tried to change current AI during UpdateAI()");

на

if (m_aiLocked)
    {
        TC_LOG_ERROR("unit.ai","Tried to change current AI during UpdateAI()");
        return;
    }

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

last

### Operating system

debian 12

**Comment by trickerer** [comment]
Что это за краш? Чем вызван? Просто при запуске сервера и спавна бота всё нормально.

**Comment by DykeRz** [comment]
Я вот и не пойму чем его вызвать, рандомно получается

**Comment by dimakpro** [comment]
Краш вызывается когда регаешь бг и включены боты ,регаешь варсонг и вылетает ядро

**Comment by trickerer** [comment]
1) Не воспроизводится
2) Нет такой ревизии https://github.com/trickerer/TrinityCore-3.3.5-with-NPCBots/commit/5b0fd3079aa2
3) Согласно существующему коду переменная `m_aiLocked`, на которой сработал ассерт, изменяется на true только перед вызовом `UpdateAI()` и изменяется обратно сразу после. То есть ассерт мог сработать только в результате работы какого-то кастомного кода, либо в результате коррупции памяти (на это не похоже). В любом случае в крашлоге отладочной информации почти нет.

Не думаю что смогу здесь помочь
