### ISSUE TITLE
[TC] [Crash] [Core] Краш сервера при телепортировании на игрока из БГ

### ISSUE THREAD

**Issue by DykeRz** [trickerer/Trinity-Bots#836]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Телепортация к игроку через .app на БГ происходит удачно, а вот из БГ .app на игрока который вне БГ (на простой локации) вызывает краш сервера
[log2024-06-26-17-39-25.log](https://github.com/user-attachments/files/16008170/log2024-06-26-17-39-25.log)

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

last

### Operating system

debian 12

**Comment by trickerer** [comment]
1) Нет такой ревизии [`c77810507beb`](https://github.com/trickerer/TrinityCore-3.3.5-with-NPCBots/commit/c77810507beb)
2) Не воспроизводится с 4 ботами у телепортирующегося игрока на игрока онлайн/оффлайн на карте 0 (Eastern Kingdoms, 6 попыток)

Попробуй без дополнительных модов на последней версии. Если всё равно будет крашиться - тогда будет фикс

**Comment by DykeRz** [comment]
> 1. Нет такой ревизии [`c77810507beb`](https://github.com/trickerer/TrinityCore-3.3.5-with-NPCBots/commit/c77810507beb)
> 2. Не воспроизводится с 4 ботами у телепортирующегося игрока на игрока онлайн/оффлайн на карте 0 (Eastern Kingdoms, 6 попыток)
> 
> Попробуй без дополнительных модов на последней версии. Если всё равно будет крашиться - тогда будет фикс

подскажи ещё один вопрос, как активировать мастера клинков бота?

**Comment by trickerer** [comment]
Похоже что нет. Закрыто
