### ISSUE TITLE
[AC] [Feature]I have a note about the 1v1 arena

### ISSUE THREAD

**Issue by Blandyoung** [trickerer/Trinity-Bots#837]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Would it be better to combine the wandering robot with the [mod-1v1-arena].
There is no need to consider the coordination problem of complex robots, and the current strategy can be directly used.
I will try to do it：）

### TrinityCore or AzerothCore

AzerothCore

**Comment by trickerer** [comment]
Looks like there was no progress on that at all. Oh well
