### ISSUE TITLE
 [AC] [Feature] [Core] An idea of establishing and hiring npcbots based on account

### ISSUE THREAD

**Issue by moncat2005** [trickerer/Trinity-Bots#838]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

I have spawned 300 npcbots in the gaming world, with an average of 30 per class, but this still seems to be insufficient.
I have analyzed the current actual situation and the main issues are as follows:
1. At present, hiring NPCBOTS is designed as a role association method, and characters with the same account must hire their own Npcbots separately.
2. In fact, it is impossible for hired NPCBots with the same account and role to be called and used at the same time.
3. Players will create multiple professional characters together with their accounts, which will occupy the number of hires, resulting in a shortage of NPCBOTS.

If the association between hiring NPCBOTS is extended to account validity, then the above issues will be greatly improved.

1. Retain the current configuration of the number of NPCBOTs hired by characters and increase the number of account hires. The total number of character hires cannot exceed the value of the number of accounts.
2. Extend the employment relationship to account validity, allowing the same account role to call NPCBOTS that already have an employment relationship.
3. Implement the principle of whoever calls is responsible for providing equipment. Once called by the current same account character, NPCBOT automatically unloads equipment from non current characters.
4. Create equipment information tables for each character that have been assigned when calling NPCBots, to avoid repeatedly reconfiguring equipment for NPCBots after calling back and forth.

It seems to be very complex to implement, do you think this idea itself is still reasonable?
Wait until you have free time to evaluate whether it's worth making such modifications.
thank you very much!

### TrinityCore or AzerothCore

Both

### Core rev. hash/commit

AzerothCore rev. c643b28 2024-05-29 16:24:18 +0800 (npcbots_3.3.5 branch) 

### Operating system

ubuntu 18.04

**Comment by trickerer** [comment]
Well, it is complex and it doesn't solve everything - nothing stops players from making separate accounts and occupy your bots that way.

In terms of complexity to effeciency ratio the best approach seems to be just limiting the number of bots per account.
But if I were you I would really consider lowering the number of bots available per character. I suppose you've balanced `NpcBot.MaxBots` values for your own purposes. If you have enough players to make a 5-man group then there is no point to allow 24+ bots to any character. Then for any given player it will be pointless to try to preserve that many bots since you can't form a proper raid alone anyway. Because it looks to me like you have enough players to make raid groups without any bots at all.

**Comment by moncat2005** [comment]
At present, the daily online here does not exceed 10 players, so the maximum number of NPCBots I can hire for each character is 9.
By selecting this value, players can at least lead NPCBOTS through a 10 player dungeon of ICC when playing alone.
When facing a 25 player dungeon, at least two players need to lead their respective 9 NPCBOTS groups in order to have a chance of clearing.
﻿
The time cost of role maintenance based on multiple accounts is greater than the idea of multiple roles per account, which is why there is an optimization idea of increasing the maximum employment value per account and combining it with the existing maximum employment value per role.
In addition, the time limit function for each character to hire NPCBOTS will trigger a timeout and release the available number of NPCBOTS hires if there is no time to attend to it.
My current employment period is 14 days, with a slightly longer retention period in case players are unable to continue playing after returning from travel or business trips.
﻿
There are indeed many factors to consider when it comes to sharing and hiring NPCBots with the same account, and the logic behind conceptualizing this reuse feature is very complex
The recall of different player characters after entering the game will involve a series of data switches such as equipment, responsibilities, assistance, talents, skills, levels, squads, teams, etc.
How to choose to recall these reusable NPCBots objects under the same account also requires an implementation approach, such as adding a list of existing NPCBots objects as alternatives in the employment intermediary menu.

**Comment by moncat2005** [comment]
Just now, there was another aspect to address the idea of NPCBOTS being arbitrarily employed, which revolves around the gold coin expenses for hiring and maintaining NPCBOTS on the job.

In addition to hiring NPCBOTs through employment agencies, NPCBOTs that have already been hired also have the function of paying salaries based on the validity period of their employment.
The original employment validity period is automatically extended based on the role's online time, and this feature requires a switch configuration. Once turned off, the periodic salary mode will automatically take effect.

The periodic salary payment function can be implemented on the existing NPCbots dialogue menu, extending the employment validity period once per payment cycle.
The amount of gold coins paid can refer to the current amount of the intermediary's employment office, or a multiplier of this employment amount can be added to the configuration variables.

On the day when the cycle is approaching, it is possible to consider adding salary negotiation language for NPCBOTS and default it to FULL STOP status.
Once there is no conversation with NPCBOTS for renewal extension after the deadline, the original automatic termination function will be triggered.
This idea avoids the disadvantage of player characters being able to continuously occupy NPCBOTS resources without cost through online recording once they hire NPCBOTS.

Overall, this approach is much simpler than previous ideas.
At the same time, this plan is more in line with the employment principles of the real world.
Without actual gaming activities, there is no source of gold coin income, and naturally, the demand for hiring NPCBots cannot be sustained.

**Comment by trickerer** [comment]
Actually, what is the problem with just creating more bots? I mean you aren't supposed to have to manage bots accesibility this closely. With hidden spawns CPU cycles isn't a problem anymore.
I was even considering the ability to keep bots completely out of world until hired (check through botgiver) or owner logged in (check through botmgr) since I don't really like teleport event re-scheduling every 5 seconds for each free bot.

**Comment by moncat2005** [comment]
Yes, since optimizing the npcbots of spawn to be invisible, the CPU usage improvement effect has been very good. Well done!
Therefore, I have increased the number of spawn for NPCBOTS to 390.

At present, there is a significant difference in DPS scores between ranged professions and melee professions in the game, so warrior, paladin, and death knight professions are always the top priority for employment, and employment resources are more scarce.
This week, in order to balance this difference, I even increased the damage multiplier of the ranged profession to test the effect.

If there are 50 game players coming in the future, but not playing online at the same time, considering the preferences of game factions and the bias of online time slots, it is still necessary to maintain the current configuration of hiring 9 players per person.
If there is no optimization of the employment release mechanism of NPCBOTS (optional online log extension of lease term or periodic salary extension of lease term), it may still face the problem of insufficient employment resources.

**Comment by trickerer** [comment]
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/c48cad436ef8b66728942b9683b9a98e7f7c43ab
Not gonna lie, I can't promise more than that

**Comment by trickerer** [comment]
Bots above account-based limit will not be removed automatically, there is a new command for this
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/f019bf9d4c990d2872029b5fcd0275255f773ac2
Unfortunatelly you still have to do it manually, you decide which bots to remove from those characters whose player tries to cheat.
I lack the skill to make this query more compact but this is how you find your cheaters:
```sql
SET @MAXBOTS = 1;
SELECT c.account,cn.owner,c.name,cn.entry FROM characters_npcbot cn JOIN characters c ON c.guid = owner WHERE (SELECT COUNT(entry) FROM characters_npcbot WHERE owner IN (SELECT guid FROM characters WHERE account = c.account)) > @MAXBOTS ORDER BY c.account,cn.owner,cn.entry;
```
Good luck I guess

**Comment by moncat2005** [comment]
Great, thank you very much!
I have been very busy lately and need to wait until I have free time to verify this feature.

**Comment by trickerer** [comment]
https://github.com/trickerer/Trinity-Bots/commit/dd5e5cf59b39d8254edbf1417a5166251eaa9547
