### ISSUE TITLE
Make bots join the 2v2 arena team and go to the arena

### ISSUE THREAD

**Issue by douglasgneves** [trickerer/Trinity-Bots#840]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

I found the pack very interesting and I'm loving being able to play with it, but if the bots could enter the 2v2 arena it would be even more interesting for all players to be able to play with them.

The question I ask is, how could you do this? If possible, help us

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

azeroth core

### Operating system

win 10

**Comment by trickerer** [comment]
Currenly bots can only join arenas with their owner, bots only arena teams are pending after BGs. Arenas are BGs technically, you may want to look into it or find a repack where arenas with bots are implemented already, I heard they exist.
https://github.com/trickerer/Trinity-Bots/issues/588
https://github.com/trickerer/Trinity-Bots/discussions/780
