### ISSUE TITLE
[AC] [Crash] [Group/Spell/Core] Краш сервера когда боты вступают в бой

### ISSUE THREAD

**Issue by Remakbna** [trickerer/Trinity-Bots#841]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

При вступлении ботов в Бой, происходит краш сервера.

### Expected behaviour

Краш сервера не должен происходить

### Crashlog

<script src="https://gist.github.com/Remakbna/de89bde4eead46b9f60a60ff7b5808b8.js"></script>

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. 47ad691c92ac+ 2024-07-01 23:28:03 +0200 (master branch) (Win64, Release, Static) (worldserver-daemon)

### Operating system

Win 11

**Comment by trickerer** [comment]
Post a Debug crashlog, Release one is useless

**Comment by Remakbna** [comment]
[47ad691c92ac+_worldserver.exe_[2-7_13-38-30].dmp](https://github.com/user-attachments/files/16067054/47ad691c92ac%2B_worldserver.exe_.2-7_13-38-30.dmp)

**Comment by Remakbna** [comment]
[47ad691c92ac+_worldserver.exe_[2-7_13-38-30].txt](https://github.com/user-attachments/files/16067078/47ad691c92ac%2B_worldserver.exe_.2-7_13-38-30.txt)

**Comment by trickerer** [comment]
> [47ad691c92ac+_worldserver.exe_[2-7_13-38-30].txt](https://github.com/user-attachments/files/16067078/47ad691c92ac%2B_worldserver.exe_.2-7_13-38-30.txt)

This is just another Release crashlog, which doesn't help

**Comment by Remakbna** [comment]
Прошу прощения. Собирал релиз, а не debug. Позже соберу дебаг и попробою отправить.

**Comment by trickerer** [comment]
Нет ответа уже месяц. Как / если будет крашлог - переоткрой
