### ISSUE TITLE
[TC] [AC] [Question] [Core]Questions about model modification in NPCBOTS.

### ISSUE THREAD

**Issue by moncat2005** [trickerer/Trinity-Bots#842]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Questions about model modification in NPCBOTS.

The model of npcbots can be modified except for the displaymodel in creatue_template_model.

There is also a data table: gender definition in creature_template_npcbot_appearance,
There are also character feature extensions, such as skin, face，hair，haircolor，features.

Recently, some players suggested that I modify some of the newly added characters in the original copy to be female.
After trying to modify the model ID of the reference female NPC in creatue_template_model
Also modified the gender field in the creature_template_npcbot_appearance table
I am not sure about the parameter definitions for skin, face, hair, haircolor, and features.
But after trying to modify it, I found that the skin color and facial shape of female characters of the Draenei race were very strange.

Where does the data reference for these extended parameters come from?

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. 4bdf5b7 2024-07-01 11:24:18 +0800 (npcbots_3.3.5 branch) 

### Operating system

ubuntu 18.04

**Comment by trickerer** [comment]
There are several potential reasons for model screw-up:
- Model has to match bot gender and race
- Model has to support displaying character parts (most models of playable races do)
- After changing bot's gender you may get an overflow in skin, face, hair, haircolor, or features field(s)

As far as I remember client's cache doesn't affect this.

Ranges for model details (skin, face, etc.) come from DBCs. There are some quirks though, like some hairstyles and colors are only available through barbershop and although they can be assigned almost all bots use standard ranges
I didn't use DBCs since the values are not condensed within a single table, I had to make my own chart giving a name to every skin tone (per race), face type (per gender per race), hair style and everything else - was kinda fun but not very readable as it's intentionally in engrish. Also enumerated model presets my voice type but that data is outdated now.

**Comment by moncat2005** [comment]
What I'm saying is strange: for example, the expression on the face is very strange, the complexion turns black and the skin tone is not consistent, and the hair color is pure green.

Yes, it should be the manifestation of parameter overflow that you explained.

Which DBC data files are the specific configurations of these parameters in?

**Comment by trickerer** [comment]
Ranges can be picked up from CharSections.dbc: column 5 (index 4) usually states the name of a texture which contains race, gender and appearance detail, like `HumanMaleSkinXX_YY.blp` and column 10 stores variation index. The maximum value is `14` for this race/gender/type combination so there are 15 different human male skin tones. Note however that only first 10 are used for playable characters, the rest are usually different zombified skins. And so on.

Specific values used per creature are listed in CreatureDisplayInfoExtra.dbc which is referenced by CreatureDisplayInfo.dbc, semi-useful.

As I said, I had to find those base max values experimentally. Essentially I made a command which spawns a temporary mirror image creature with wanted values assigned and matches it against existing creatures in world repeatedly as well as character creation screen.

**Comment by icedcolor** [comment]
@trickerer 
[AC] Error after compiling in the new update

![7](https://github.com/trickerer/Trinity-Bots/assets/19793341/58979e77-4cd2-488c-9d05-9efb88e812fd)

**Comment by trickerer** [comment]
> @trickerer [AC] Error after compiling in the new update
> 
> ![7](https://private-user-images.githubusercontent.com/19793341/346042394-58979e77-4cd2-488c-9d05-9efb88e812fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNzEwNzgsIm5iZiI6MTcyMDE3MDc3OCwicGF0aCI6Ii8xOTc5MzM0MS8zNDYwNDIzOTQtNTg5NzllNzctNGNkMi00ODhjLTlkMDUtOWVmYjg4ZTgxMmZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDA5MTI1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhMjY0YWNjNGE0Yzk2YWQyZGZlNGE3ODcyMGYwYWFkMDE5OWRjN2NjMzBhNmM4MWVmNDgwZDMxMDM4ODc1NmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CV8hvvUzmRSJPhfuCPIdWjaLeHMhopymtbxfx8SeZd4)

It's an AC update not Trinity-Bots, you don't need to report this. Bots update schedule can be found in the very beginning of the Readme.
