### ISSUE TITLE
[TC] [AC] [Feature] [Spell] Balance Druid missing Improved Faerie Fire talent

### ISSUE THREAD

**Issue by khs-kks** [trickerer/Trinity-Bots#843]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Please implement Improved Faerie Fire talent for Druids with Balance spec. Looked for it in bot_druid_ai.cpp and didn't find it.

### TrinityCore or AzerothCore

AzerothCore

**Comment by trickerer** [comment]
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/9eda2d7d008bb14c9e5372291f33373277e16097
