### ISSUE TITLE
 [AC] [Bug] [Group/Spell/Core] Нужно запретить игрокам воскрешать вражеских ботов

### ISSUE THREAD

**Issue by Parkan1986** [trickerer/Trinity-Bots#845]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Игроки могут воскрешать ботов как дружественных так и враждебных.Враждебных надо запретить иначе это будет абьюз.

### Expected behaviour

Игроки не должны воскрешать враждебных ботов

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. 238a2cb79cf6 2024-07-06 08:00:50 +0300 (npcbots_3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

**Comment by trickerer** [comment]
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/196106a268aa85b73010f416e0b7ce5c6dc2a211
