### ISSUE TITLE
Proper Feral Cat Priority System and Talents.

### ISSUE THREAD

**Issue by primus1002** [trickerer/Trinity-Bots#847]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### 10 Minute Dummy Exhibition

**Buffs:**
- Tiger's Fury missed some opportunities maybe because of Berserk, which is okayish.
- Savage Roar is currently 0% uptime, should be close to 100%
- Berserk got used at the start, which is wrong.
- Omen of Clarity procs should be used on Shred.

**Debuffs:**
- Mangle got used way too often, even if there's enough time remaining (avoid if someone else can apply it).
- Rip has 71% uptime; it should be as close to 100% as possible, ideally around 95% or more on a 10-minute dummy fight.
- Rip doesn't crit, which means Primal Gore isn't skilled (likely prioritizing bear).
- Rake has 8.6% uptime instead of 100% on a dummy.
- Faerie Fire has 100% uptime.

**General:**
- Ferocious Bite was used way too often; it should only be used in very limited situations, such as during Berserk.

---

### Priority List

1. If you have less than 40 Energy and Tiger's Fury is off cooldown, then cast **Tiger's Fury**.
2. If Berserk is available and Tiger's Fury is on cooldown for at least 15 seconds, then cast **Berserk**.
3. If you have at least 1 Combo Point and the Savage Roar buff has expired, then cast **Savage Roar** (pooling Energy first if needed).
4. If your last auto-attack generated a Clearcasting proc (from Omen of Clarity), then spend the proc on **Shred**.
5. If you have 5 Combo Points and the Rip debuff has expired, then cast **Rip** (pooling Energy first if needed).
6. If the Rake debuff has expired, then cast **Rake** (pooling Energy first if needed).
7. If the Mangle (Cat) debuff has expired, then cast **Mangle (Cat)** (pooling Energy first if needed).
8. If you have enough Energy in reserve to reapply Savage Roar, Rip, Rake, and Mangle (Cat) as soon as they expire (taking into account future Energy regeneration), then cast **Shred**.
9. Otherwise, pool Energy in preparation for Savage Roar, Rip, Rake, or Mangle (Cat) falling off.

### TrinityCore or AzerothCore

AzerothCore

**Comment by khs-kks** [comment]
None of the rotations are optimized, as far as I can tell. For example, Arms Warrior doesn't use Execute in a raid environment. If you have access to the files and the server is managed by you, edit the skills' logic in their corresponding files in src/server/game/AI/NpcBots/.

**Comment by trickerer** [comment]
> - Rip doesn't crit, which means Primal Gore isn't skilled (likely prioritizing bear).

Well that's a lie. Rip crits just as fine as Rake does

![feral_crit](https://github.com/user-attachments/assets/8d8183cf-c5c5-4f19-b889-88f2f14ca29f)

**Comment by trickerer** [comment]
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/cf5301a8afa093df2d58da6883d3a6288ab85616

Thanks for the info @primus1002. Note that I'm not going to try to improve it any further.
Here are the results, Skada session was recorded with Windfury Totem active at all times, bot GS is 6k, only +hit and +haste gems:

![feral_dps](https://github.com/user-attachments/assets/5deeeec0-b6cb-4d05-8214-b4289755f309)
