### ISSUE TITLE
[AC] [Crash] [Spell] order cast macro crashes worldserver

### ISSUE THREAD

**Issue by ThoorAdam** [trickerer/Trinity-Bots#848]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

If the following macro is used ".npcbot order cast Druid78338 wrath skull" the world server crashes. No crash happens when using "mytarget" as target option, the two "marks" I've tried as targets are diamond and skull, both crashes the server.

### Expected behaviour

Hopefully not a server crash.

### Steps to reproduce the problem

Run macro ".npcbot order cast Druid78338 wrath skull"

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. 303032ca2bce+ 2024-07-04 21:55:21 +0200 (npcbots_3.3.5 branch) (Unix, RelWithDebInfo, Static)

### Operating system

Win11 and Ubuntu 22.04

**Comment by trickerer** [comment]
I've no idea what custom code you're using on your repo. Can't reproduce on https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/91ef74b276e2303ee75374c0ac232eced5650b0d

Post a Debug crashlog and maybe I'll be able to help you

**Comment by ThoorAdam** [comment]
[303032ca2bce+_worldserver.exe_[11-7_9-59-4].txt](https://github.com/user-attachments/files/16173388/303032ca2bce%2B_worldserver.exe_.11-7_9-59-4.txt)

Here is the crashlog. We don't really have any modified code except for some damage calculation changes for the bots in PvP.

**Comment by trickerer** [comment]
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/7d15ea557eb1b76fae1bf682bc171dae5e2ee49b

**Comment by ThoorAdam** [comment]
Thanks a lot! Works like a charm!

**Comment by trickerer** [comment]
Issue should stay open until the main repository receives this update
