### ISSUE TITLE
[AC] [Bug] [Spell] Flasks are stucks and do not replace each other

### ISSUE THREAD

**Issue by Bogir** [trickerer/Trinity-Bots#849]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

In case of giving some flasks, eat or dring (with buff) to bots, the spell-effects are combined with each other and do not replace if spell-effects are the same.

Если ботам давать всякие зелья, еду или написки с эффектами бафа - эффекты заклинаний стакаютсяя, даже если они однотипные, хотя должны замещать свои аналоги с более слабым действием.
![Screenshot_2](https://github.com/user-attachments/assets/0796f5fb-6e3f-4cff-94d5-e0f383158a1b)

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

7d15ea557eb1b76fae1bf682bc171dae5e2ee49b

### Operating system

Windows

**Comment by Day36512** [comment]
same if you're a paladin casting blessings on a bot. seems they ignore spell_group_stack_rules

**Comment by trickerer** [comment]
There is a hack which disables stacking rules for npcbot passive AoE auras since the calculation consumes so much CPU but looks like its application is unexpectingly broad. Also with the implementation of hidden spawns it's no longer needed.

**Comment by trickerer** [comment]
https://github.com/trickerer/Trinity-Bots/commit/986e776ad41e85ded1bdba03c6124dd3021e450e
