### ISSUE TITLE
[Question]  The definition of the data table related fields of characters_npcbot for npcbots.

### ISSUE THREAD

**Issue by moncat2005** [trickerer/Trinity-Bots#850]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Could you please parse the definitions and numerical meanings of the<roles>and<spec>fields in the data table characters_npcbot?
thank you!

### TrinityCore or AzerothCore

Both

### Core rev. hash/commit

AzerothCore rev. 4bdf5b7 2024-07-01 11:24:18 +0800 (npcbots_3.3.5 branch) 

### Operating system

ubuntu 18.04

**Comment by trickerer** [comment]
- entry <- creature_template.entry
- owner <- characters.guid
- roles <- sum of bot roles (see botcommon.h BotRoles enum)
- spec <- talent tree number 1-31 (see botcommon.h BotTalentSpecs enum)
- faction <- FactionTemplate.dbc entry, ex. 1802 refers to 469 = Alliance (Faction.dbc)
- hire_time <- hire event timestamp, only used by hired bots to determine when to set free
- equipNAME <- item_instance.guid

**Comment by moncat2005** [comment]
Thank you, this way I can correct the NPCbots data added to the data table.
