### ISSUE TITLE
[AC] [Feature] [Core] Fix spam to console by MoveSpline validator

### ISSUE THREAD

**Issue by Bogir** [trickerer/Trinity-Bots#853]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

We need to add an exception for bots to the function `bool MoveSplineInitArgs::Validate(Unit* unit) const` (MoveSpline.cpp).

Always triggers if bots cannot move. For example: in "Trial of the Crusader" the Boss freezes everyone to the floor for a few seconds. During this time, an error is displayed in the server console (see screenshot)
![изображение](https://github.com/user-attachments/assets/ffcc7fa8-7ea9-4d75-934c-134ccca9f917)

Не знаю как по-аглицки будет "Консоль засрана" (((

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

7d15ea557eb1b76fae1bf682bc171dae5e2ee49b

### Operating system

Windows

**Comment by trickerer** [comment]
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/872c62d3efe134a229e1e693d555006df863bff8

**Comment by trickerer** [comment]
https://github.com/trickerer/Trinity-Bots/commit/dd5e5cf59b39d8254edbf1417a5166251eaa9547

**Comment by Bogir** [comment]
Всё-таки фикс не работает
Каждый день такой спам:
https://gist.github.com/Bogir/deb9b442e898d41d98b69d5e5cd674ed

**Comment by trickerer** [comment]
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/85ee7aeb1be238323a9bfe6835c568d95211218a
