### ISSUE TITLE
[AC] [Question] [Spell/Core] non handled item enchantment

### ISSUE THREAD

**Issue by Bogir** [trickerer/Trinity-Bots#854]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Is this very bad, or is it nothing to worry about?
![изображение](https://github.com/user-attachments/assets/bb92b61f-9628-485a-a90a-9e9909d933c1)

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

7d15ea557eb1b76fae1bf682bc171dae5e2ee49b

### Operating system

Windows

**Comment by trickerer** [comment]
Duplicate of https://github.com/trickerer/Trinity-Bots/issues/775

Isn't critical, your custom or custom-casted windfury on bot won't work
<details><summary>Details</summary>
<p>
If you're NOT using a repack then describe the way this spell is applied as best as you can.

</p>
</details>

**Comment by Bogir** [comment]
> If you're NOT using a repack then describe the way this spell is applied as best as you can.

I'm not a player at all, so I don't know what it was and what could call this Error.
Players told me, what does this spell do - it is breaking current cast of Shaman's target. 
But i've noticed - it appears 4 times at 1 second. Player's spell have a cooldown. May be bot tried to use this spell too fast without cooldown?
Причем тут энчант предмета - я вообще не понимаю

**Comment by trickerer** [comment]
Хэндлер прока ругается не на кулдаун а на невозможность определить источник прока.
Спелл 33757 это пассивный спелл, временно накладываемый на юнита при надевании зачарованного (или зачаровании надетого) предмета. Если он всё ещё активен но зачарования на оружии нет вылезет такая ошибка. Хэндлер ищет зачарованный предмет чтобы определить какой уровень спелла использовался и оттуда посчитать бонус атаки - он его не находит. Так как никакого спелла не кастуется то и прервать никакого каста он не может. В прошлый раз я уже пытался воспроизвести подобную ситуацию, не смог - тогда я предположил что спелл от енчанта был наложен либо на юнита напрямую, либо через пассивный спелл предмета там его хэндлер прока тоже не найдёт.

**Comment by trickerer** [comment]
В принципе такое возможно если предмет был каким-то образом некорректно снят с бота. Состояние бота должно исправиться при сбросе аур - релог игрока или рестарт сервера.

**Comment by LannyE** [comment]
This has been happening since April for me.  I think Azerothcore made some changes to Windfury around that time if my memory serves.  My installation is using the default NPCBots bots SQL.  I don't use NPCBots as companions.  I just have them on my server for Battleground bots and wandering bots.  If I disable the wandering bots the errors stop.

**Comment by trickerer** [comment]
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/0b5a7fa91739a17972dbc3bb7dfaf95ad7d69c95

**Comment by trickerer** [comment]
https://github.com/trickerer/Trinity-Bots/commit/986e776ad41e85ded1bdba03c6124dd3021e450e
