### ISSUE TITLE
 [AC] [Bug/Crash] Боты отказываются хилить Валитрию

### ISSUE THREAD

**Issue by xBarselonx** [trickerer/Trinity-Bots#855]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Во время боя с  боссом Валитрия, боты не хилят ее  либо до какого-то значения или процента скрин ниже. В итоге мне(ДД) пришлось захилить Валитрию и на это все ушло 30 мин.
![WoWScrnShot_080324_031054](https://github.com/user-attachments/assets/eee62d46-9215-4abf-bdfc-5ee500b41fca)
![WoWScrnShot_080324_033206](https://github.com/user-attachments/assets/4158239f-5a52-4fdb-9c61-fc71c87a1e62)

### Expected behaviour

Раньше боты хилили Валитрию 

### Steps to reproduce the problem

Войти в рейд к бассу Валитрия Сноходица

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. 7c2fc587eab0 2024-07-27 07:30:49 +0700 (npcbots_3.3.5 branch) (Win64, Release, Static) (worldserver-daemon)

### Operating system

Win11

**Comment by trickerer** [comment]
Before you engage you have to set heal threshold for your healers.
- Select a healer
- `Engage behavior`
- `Heal target health threshold`
- `Set to 100%`
