### ISSUE TITLE
[AC] [Feature Request] NPCBots ignore questgivers/flight masters

### ISSUE THREAD

**Issue by StraysFromPath** [trickerer/Trinity-Bots#856]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Optional toggle for npcbots to stop killing questgivers/flight masters would be nice.

Common feedback on my server is that flight masters being killed is very problematic and even lvl 30 elite dark ranger bots can solo flightmasters or any lvl 40 normal class bot can.

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

latest

### Operating system

win10

**Comment by trickerer** [comment]
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/81f390ea2376189fd78671a78291600ccb6085e7
