### ISSUE TITLE
[AC] [Bug/Crash] No NPC Bots?

### ISSUE THREAD

**Issue by Dranos-Nupper** [trickerer/Trinity-Bots#857]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

I look up NPC bots there in the world Database  but not the character database. 
When i search them i only get random names
![image](https://github.com/user-attachments/assets/8b468a35-88b6-43a5-8271-1cda45554eb8)

### Expected behaviour

List ID/Name/ Class

### Steps to reproduce the problem

1. Fresh install with Azerothcore via Patch.
2. Database updated.
3. Go Ingame and look up bots.

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. fcdc50306ff8+ 2024-08-03 12:02:49 -0300 (master branch) (Win64, Release, Static) (worldserver-daemon)

### Operating system

Win10

**Comment by Dranos-Nupper** [comment]
![image](https://github.com/user-attachments/assets/f0754b78-e386-419a-b858-e442934b4be4)

**Comment by trickerer** [comment]
Looks like being caused by https://github.com/azerothcore/azerothcore-wotlk/commit/3fbded8f6bdaae1ec6897dae34afdab36b124899

**Comment by trickerer** [comment]
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/ceeba694710bd54a5de7a5b3653c55aca78761e0

**Comment by apple-pies** [comment]
Edit the botcommands.cpp file and replace all instances of %u, %s, and %d with {}

**Comment by trickerer** [comment]
https://github.com/trickerer/Trinity-Bots/commit/986e776ad41e85ded1bdba03c6124dd3021e450e
