### ISSUE TITLE
[AC] [Crash] [Core] World Server crash when logging out with a hidden bot with a pet/minion

### ISSUE THREAD

**Issue by Zerkenn** [trickerer/Trinity-Bots#859]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

The world server crashes with a segfault/Assertion Failed when you logout while having a hired bot with a pet and then using the command '.npcbot hide' command.

![image](https://github.com/user-attachments/assets/17b1c502-a393-4ce0-a7b6-f59ab77ba58e)

### Steps to reproduce the problem

1) Hire a hunter bot or warlock bot and wait for it to summon a pet
2) Hide the bot using .npcbot hide
3) Logout and server will segfault/crash

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. 3d00d05f4972+ 2024-08-09 21:27:36 +0000

### Operating system

Debian 12

**Comment by Zerkenn** [comment]
I  was able to figure out the issue exist within this function. It seems this gets called on pets/minions when you hide the bots and again on logout.

For a temporary fix on my server I just made it so save is creature->ToTempSummon())->UnSummon() is always called. This stops the segfault on logout.

![image](https://github.com/user-attachments/assets/ddc3f9d3-3718-49ca-a911-409a22d06a70)

Thanks for all the work on NPCbots. I hope these details help.

**Comment by trickerer** [comment]
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/b252afc60354319271993a1620e13dcc06011202

**Comment by trickerer** [comment]
The issue must stay open until main repo receives the changes

**Comment by trickerer** [comment]
https://github.com/trickerer/Trinity-Bots/commit/dd5e5cf59b39d8254edbf1417a5166251eaa9547
