### ISSUE TITLE
Bug - Bots fall into the ground in ICC lich King Fight

### ISSUE THREAD

**Issue by Ryu1254** [trickerer/Trinity-Bots#86]
when fighting Lich King near the edge of the platform.. often when Lich king summon minions, minions falls of the platform and bring Bots with them.. when all adds are death.. lich king follow the Bot tank into the ground make the fight impossible to completed..

**Comment by trickerer** [comment]
The solution here obviously is to make summoned minions not fall down, which has nothing to do with NPCBots.

I don't see a clean workaround for that either.

**Comment by Ryu1254** [comment]
yeah.. this one is pretty nasty.. I just recompiled TC without any mod.. the bug does exist on the vanilla TC..

**Comment by Saiska** [comment]
'minions falls of the platform and bring bots with them

remove the dps sign. they won't follow them. i got the problem only if i let the dps sign on a minion which fall. If i put a sign on the lich king, the bots will ignore the minion and the minion will fall alone.

**Comment by Ryu1254** [comment]
ok.. i'll try the trick with .npcb dist 0. usually, i dont really change the distance during fight. 
but if that do the trick.. I can try that.
thx

**Comment by Jinnaix** [comment]
This is a TC issue and not fixable:
https://github.com/TrinityCore/TrinityCore/issues/22151

More details for ICC:
https://github.com/TrinityCore/TrinityCore/issues/26493

**Comment by Ryu1254** [comment]
if it's a TC issues, then i'll close this issues. since the problem is not relate to bot.
Thanks for the finding.
