### ISSUE TITLE
[AC] [Crash] [Spell/Core] Teleport

### ISSUE THREAD

**Issue by Bogir** [trickerer/Trinity-Bots#861]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

HandleDelayedTeleports 
BotMgr::_teleportBot

I don't know what it was. I've got only crash-log

### Crashlog

https://gist.github.com/Bogir/a95f6df3d303244effa6c3bdc4412af2

### Steps to reproduce the problem

I don't know what it was. I've got only crash-log

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

Trickerer rev. b252afc60354319271993a1620e13dcc06011202

### Operating system

Win7

**Comment by trickerer** [comment]
Не могу воспроизвести
Нет такой ревизии 0ae8a2a1df69

Обновись до последней версии. Если не будет крашлога на версии https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/b252afc60354319271993a1620e13dcc06011202 (11.08.2024) или выше то буду считать это дубликатом https://github.com/trickerer/Trinity-Bots/issues/859

**Comment by Bogir** [comment]
> Не могу воспроизвести Нет такой ревизии 0ae8a2a1df69
![изображение](https://github.com/user-attachments/assets/48ba15d0-4482-4047-9ee8-1d2bc93c441e)

ревизия АС - это в краш-логе из моего репо. Основа - Ваша последняя ревизия

вот ревизия от АС - 7b102f53f2b155abf80dbae4cff2f4d2213f0c44
![изображение](https://github.com/user-attachments/assets/65fd60b4-0b1d-4c90-8200-125c3256528d)

**Comment by Bogir** [comment]
Прошел месяц, и ошибка повторилась. Игрок с ботами портанулся в Залы Отражений. Снова те же шаги в краш-логе:
BotMgr::HandleDelayedTeleports
BotMgr::_teleportBot
bot_ai::SetTeleportFinishEvent

>> ASSERTION FAILED

# Location: D:\!REPO\WOW\src\server\game\AI\NpcBots\bot_ai.h:214
# Function: bot_ai::SetTeleportFinishEvent
# Condition: !teleFinishEvent

# Debug info: Me: MapID: 0 X: 3753.37 Y: -3985.47 Z: 128.97 O: 1.59691
GUID Full: 0xf13001125f0000ed Type: Creature Entry: 70239  Low: 237 Entry 70239
Name: Izmir
AliveState: false UnitMovementFlags: 0 ExtraUnitMovementFlags: 0 Class: 5
AIName:  ScriptName: priest_bot WaypointPath: 0 SpawnId: 4128308

**Comment by trickerer** [comment]
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/86eab6c66e3c03a2a72ac6b685e2d98240f17a0d
