### ISSUE TITLE
[AC] [Question] [Core] WorldObject::AddObjectToRemoveList() error

### ISSUE THREAD

**Issue by Bogir** [trickerer/Trinity-Bots#862]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Today I've noticed new error on bots entering to instance map. It never happened before.

12-08-2024 10:23:26 Object GUID Full: 0xf13001138a003453 Type: Creature Entry: 70538  Low: 13395 at attempt add to move list not have valid map (Id: 574).

12-08-2024 11:52:39 Object GUID Full: 0xf13001138a0049ea Type: Creature Entry: 70538  Low: 18922 at attempt add to move list not have valid map (Id: 599).

12-08-2024 12:40:01 Object GUID Full: 0xf13001138a002889 Type: Creature Entry: 70538  Low: 10377 at attempt add to move list not have valid map (Id: 599).
12-08-2024 12:40:01 Object GUID Full: 0xf13001138a002887 Type: Creature Entry: 70538  Low: 10375 at attempt add to move list not have valid map (Id: 599).

12-08-2024 14:58:25 Object GUID Full: 0xf1300113750000af Type: Creature Entry: 70517  Low: 175 at attempt add to move list not have valid map (Id: 603).

12-08-2024 14:59:45 Object GUID Full: 0xf130011375002fd7 Type: Creature Entry: 70517  Low: 12247 at attempt add to move list not have valid map (Id: 533).
12-08-2024 14:59:47 Object GUID Full: 0xf13001136800029b Type: Creature Entry: 70504  Low: 667 at attempt add to move list not have valid map (Id: 533).

12-08-2024 15:11:13 Object GUID Full: 0xf130011375000653 Type: Creature Entry: 70517  Low: 1619 at attempt add to move list not have valid map (Id: 603).
12-08-2024 15:11:13 Object GUID Full: 0xf130011375000652 Type: Creature Entry: 70517  Low: 1618 at attempt add to move list not have valid map (Id: 603).
12-08-2024 15:11:13 Object GUID Full: 0xf130011375000644 Type: Creature Entry: 70517  Low: 1604 at attempt add to move list not have valid map (Id: 603).

12-08-2024 15:48:58 Object GUID Full: 0xf13001138a00053b Type: Creature Entry: 70538  Low: 1339 at attempt add to move list not have valid map (Id: 533).
12-08-2024 15:49:06 Object GUID Full: 0xf130011368000539 Type: Creature Entry: 70504  Low: 1337 at attempt add to move list not have valid map (Id: 533).
12-08-2024 15:49:22 Object GUID Full: 0xf13001138e0005b4 Type: Creature Entry: 70542  Low: 1460 at attempt add to move list not have valid map (Id: 533).
12-08-2024 15:49:38 Object GUID Full: 0xf1300113750005b7 Type: Creature Entry: 70517  Low: 1463 at attempt add to move list not have valid map (Id: 533).
12-08-2024 15:56:35 Object GUID Full: 0xf1300113680005cf Type: Creature Entry: 70504  Low: 1487 at attempt add to move list not have valid map (Id: 533).

And so on. All about bot-pets.
What it means?

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

Trickerer rev. b252afc60354319271993a1620e13dcc06011202

### Operating system

Win7

**Comment by trickerer** [comment]
It means that the bot pet in question wasn't in map when it was removed, this ultimately leads to memory leak.

https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/56c353b488ac9128dd80793660de8edde9e42063

**Comment by Bogir** [comment]
> [trickerer/AzerothCore-wotlk-with-NPCBots@56c353b](https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/56c353b488ac9128dd80793660de8edde9e42063)

Big thanks!

**Comment by trickerer** [comment]
https://github.com/trickerer/Trinity-Bots/commit/dd5e5cf59b39d8254edbf1417a5166251eaa9547
