### ISSUE TITLE
[AC] [Crash] [Group/Core] Bot out of Raid-group hangs server while waiting out of ICC

### ISSUE THREAD

**Issue by Bogir** [trickerer/Trinity-Bots#863]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Бот (видимо паладин) подвесил сервер, находясь вне рейдовой группы, которую игрок завёл в ЦЛК. Боту стало скучно и он обиделся? Но он там остался в компании таких же ботов вне группы...

Прикрепляю начало краш-лога. Полный лог - 2,5 Мб. Прикреплять весь?
(Я номера строк поправил, чтоб совпадали, с Вашими, у меня они смещены из-за дебагов и комментов.)

И еще момент: 
Номер ревизии предусмотрен только  для АС или ТС, но я теперь использую только Ваш репо и номер ревизии указал из него. Можно добавить в выпадающий список пункт "Trickerer" чтоб не путаться?

### Expected behaviour

Возможно, нужно проверить чем занимаются боты вне группы, пока остальные находятся в инсте

### Crashlog

https://gist.github.com/Bogir/906ee8f97b6efb6784f8196ab6dafd61

### Steps to reproduce the problem

Go to ICC entrance with bots
Make a Raid-group with some of them
Enter to instance

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

1f850c2259d3b9f38d3253152155c43cb0b02271

### Operating system

Win7

**Comment by trickerer** [comment]
> Прикрепляю начало краш-лога. Полный лог - 2,5 Мб. Прикреплять весь?
(Я номера строк поправил, чтоб совпадали, с Вашими, у меня они смещены из-за дебагов и комментов.)

Вообще нужно весь, но в данном конкетном случае не обязательно, так как причина очевидна. https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/c54569da87b0431172bf8f629dce23f209db1ecd. Была пара фиксов в https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/57a98e1b6aa33641f2282e33fd755d43c4d295c3 но кое-что осталось неучтённым.

> И еще момент:
Номер ревизии предусмотрен только для АС или ТС, но я теперь использую только Ваш репо и номер ревизии указал из него. Можно добавить в выпадающий список пункт "Trickerer" чтоб не путаться?

Чтобы не путаться ревизия внутри крашлога должна быть существующей, соответствовать указанной и не иметь никаких допонительных добавлений
Что я вижу в крашлоге (чисто как разработчик, принимающий репорт)?
`Revision: AzerothCore rev. 1f850c2259d3+ 2024-08-15 03:37:42 +0500 (master branch) (Win64, RelWithDebInfo, Static)`
1) Почему `master` а не `npcbots_3.3.5`? Это всегда сбивает с толку. В https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots нет ветки `master`, только `3.3.5` и в ней нет ботов. Обычно такое бывает когда на мастере https://github.com/azerothcore/azerothcore-wotlk используют патч без фиксации изменений
2) 1f850c2259d3 **+** - сразу говорит что в ядре есть кастомный код. Я не могу знать что это за код, сколько его и что он делает. Я могу лишь спросить и поверить наслово
3) RelWithDebInfo - в шаблоне для репорта прямо сказано что нужен крашлог в Debug. RelWithDebInfo это оптимизированный билд и отладочная информация в нём по большей части бесполезна

**Comment by Bogir** [comment]
Чуть позже оптяь такой же краш 
Изменился лишь номер одной сроки в bot_ai
```
Revision: AzerothCore rev. 1f850c2259d3+ 2024-08-15 03:37:42 +0500 (master branch) (Win64, RelWithDebInfo, Static)
Date 16:8:2024. Time 10:20 
//=====================================================
*** Hardware ***
Processor: AMD FX(tm)-8120 Eight-Core Processor           
Number Of Processors: 8
Physical Memory: 33535540 KB (Available: 23612708 KB)
Commit Charge Limit: 67069180 KB

*** Operation System ***
Windows 7 Professional Service Pack 1 (Version 6.1, Build 7601)

//=====================================================
Exception code: C0000420 Произошла ошибка подтверждения.

Assertion message: #----------------------------------------------------------------------#
 
>> ASSERTION FAILED

# Location: D:\!REPO\!!WOW\!Anda_WoW_Git\WoW\WOW\src\server\game\Entities\Object\Object.h:546
# Function: WorldObject::GetMap
# Condition: m_currMap

# Debug info: MapID: 571 X: 5487.94 Y: 2840.15 Z: 421.065 O: -0.287446
GUID Full: 0xf130024e18000302 Type: Creature Entry: 70064  Low: 770 Entry 70064
Name: Betin
AliveState: true UnitMovementFlags: 0 ExtraUnitMovementFlags: 0 Class: 2
AIName:  ScriptName: paladin_bot WaypointPath: 0 SpawnId: 4140477
 
#----------------------------------------------------------------------#

Fault address:  000000013F438B54 01:0000000000067B54 C:\!!!SERVER\bin\RelWithDebInfo\worldserver.exe

Registers:
RAX:00000000E5E3FE20
RBX:0000000042A05D30
RCX:000000000332E370
RDX:0000000000000110
RSI:000000008AC7B130
RDI:0000000042A05D30
R8: 0000000000000000
R9: 0000000000000D50
R10:000000000332E9C0
R11:000000008947C498
R12:000000008947C3F0
R13:00000000430ED8C0
R14:0000000000000000
R15:0000000000000001
CS:RIP:0033:000007FEFD16B87D
SS:RSP:002B:000000000332E980  RBP:0332EAE9
DS:002B  ES:002B  FS:0053  GS:002B
Flags:00000202

Call stack:
Address   Frame     Function      SourceFile
000007FEFD16B87D  000000000332EA40  RaiseException+3D
00000001404E908D  000000000332EB30  Acore::Assert+15D  D:\!REPO\!!WOW\!Anda_WoW_Git\WoW\WOW\src\common\Debugging\Errors.cpp line 112
000000013F438B54  000000000332EC40  WorldObject::GetMap+124  D:\!REPO\!!WOW\!Anda_WoW_Git\WoW\WOW\src\server\game\Entities\Object\Object.h line 546
000000013FAAE151  000000000332ECC0  WorldObject::MovePositionToFirstCollision+71  D:\!REPO\!!WOW\!Anda_WoW_Git\WoW\WOW\src\server\game\Entities\Object\Object.cpp line 2931
000000013FAAA97A  000000000332ECF0  WorldObject::GetFirstCollisionPosition+3A  D:\!REPO\!!WOW\!Anda_WoW_Git\WoW\WOW\src\server\game\Entities\Object\Object.cpp line 2920
000000013FE4F528  000000000332EF40  bot_ai::CalculateAttackPos+10E8  D:\!REPO\!!WOW\!Anda_WoW_Git\WoW\WOW\src\server\game\AI\NpcBots\bot_ai.cpp line 5473
000000013FE6093E  000000000332EFB0  bot_ai::GetInPosition+3CE  D:\!REPO\!!WOW\!Anda_WoW_Git\WoW\WOW\src\server\game\AI\NpcBots\bot_ai.cpp line 5530
00000001403196B1  000000000332F010  hunter_bot::hunter_botAI::UpdateAI+4B1  D:\!REPO\!!WOW\!Anda_WoW_Git\WoW\WOW\src\server\game\AI\NpcBots\bot_hunter_ai.cpp line 735
000000013FBD22B8  000000000332F1B0  Creature::Update+FB8  D:\!REPO\!!WOW\!Anda_WoW_Git\WoW\WOW\src\server\game\Entities\Creature\Creature.cpp line 880
000000013FEEB0E4  000000000332F330  BotMgr::Update+394  D:\!REPO\!!WOW\!Anda_WoW_Git\WoW\WOW\src\server\game\AI\NpcBots\botmgr.cpp line 1128
000000013FF87E4F  000000000332F580  Player::Update+15AF  D:\!REPO\!!WOW\!Anda_WoW_Git\WoW\WOW\src\server\game\Entities\Player\PlayerUpdates.cpp line 433
000000013FD42F3D  000000000332F850  Map::Update+19D  D:\!REPO\!!WOW\!Anda_WoW_Git\WoW\WOW\src\server\game\Maps\Map.cpp line 765
000000013FD42D77  000000000332F880  InstanceMap::Update+17  D:\!REPO\!!WOW\!Anda_WoW_Git\WoW\WOW\src\server\game\Maps\Map.cpp line 3074
000000014023DAC2  000000000332F8C0  MapUpdateRequest::call+32  D:\!REPO\!!WOW\!Anda_WoW_Git\WoW\WOW\src\server\game\Maps\MapUpdater.cpp line 45
000000014023D5BC  000000000332F8F0  MapUpdater::WorkerThread+DC  D:\!REPO\!!WOW\!Anda_WoW_Git\WoW\WOW\src\server\game\Maps\MapUpdater.cpp line 158
000000014023CFBF  000000000332F920  std::thread::_Invoke<std::tuple<void (__cdecl MapUpdater::*)(void),MapUpdater *>,0,1>+F  d:\Program Files\Microsoft Visual Studio\2022\Community1763\VC\Tools\MSVC\14.36.32532\include\thread line 56
000007FEF862F4A0  000000000332F950  _o__realloc_base+60
000000007711556D  000000000332F980  BaseThreadInitThunk+D
000000007737372D  000000000332F9D0  RtlUserThreadStart+1D
```

**Comment by Bogir** [comment]
> 3\. RelWithDebInfo - в шаблоне для репорта прямо сказано что нужен крашлог в Debug. RelWithDebInfo это оптимизированный билд и отладочная информация в нём по большей части бесполезна

В таком случае, лучше собирать в Debug?

> Что я вижу в крашлоге
Номер ревизии я вношу вручную, т.к. не работаю напрямую с веткой или форком Вашего репо. Мой репо на assembla и там всё в SVN. Привычнее и проще ориентироваться там, "apply patch" не вызывает конфликтов с номерами GIT-ревизий и прочее. Работает assemba в разы быстрее, чем github, и откатиться на какую-то ревизию - секундное дело. Особенно это актуально при поиске непонятной ошибки, когда приходится откатывать 10-15 ревизий подряд


Только что сервер опять упал
`# Debug info: MapID: 571 X: 5780.13 Y: 2064.75 Z: 636.064 O: -2.67893
GUID Full: 0xf130025d8d0005e9 Type: Creature Entry: 70471  Low: 1513 Entry 70471
Name: Alcaeos
AliveState: true UnitMovementFlags: 0 ExtraUnitMovementFlags: 0 Class: 6
AIName:  ScriptName: death_knight_bot WaypointPath: 0 SpawnId: 4141434
`

Крашлог как в первом сообщении

**Comment by trickerer** [comment]
> В таком случае, лучше собирать в Debug?

Для сервера с активным онлайном? Сомнительно, ведь отладочный билд потребляет гораздо больше ресурсов. Впрочем лично для меня выбор очевиден, так как отладка это просто повседневная работа. Если вдруг нужно собрать релизный билд, то это обычно MinSizeRel.

> Номер ревизии я вношу вручную, т.к. не работаю напрямую с веткой или форком Вашего репо. Мой репо на assembla и там всё в SVN. Привычнее и проще ориентироваться там, "apply patch" не вызывает конфликтов с номерами GIT-ревизий и прочее. Работает assemba в разы быстрее, чем github, и откатиться на какую-то ревизию - секундное дело. Особенно это актуально при поиске непонятной ошибки, когда приходится откатывать 10-15 ревизий подряд

Это всё конечно очень хорошо и я не берусь давать советов как кому организовывать свою работу, но те расхождения и непонятки, на которые я указал выше, потенциально снижают вероятность благополучного разрешения проблемы, особенно если проблема серьёзная - было бы наивно полагать что это вообще никак не влияет. Именно поэтому я предпочёл указать на них с точки зрения абстрактного участника разработки, которому на анализ попадает багрепорт.

А вот и фикс
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/f3444970c27577718e113ca350d9aa61dd782d8e

**Comment by Bogir** [comment]
> отладочный билд потребляет гораздо больше ресурсов

Если цель - доработать сервер до стабильного состояния, то правильнее будет пожертвовать ресурсами )

**Comment by trickerer** [comment]
https://github.com/trickerer/Trinity-Bots/commit/dd5e5cf59b39d8254edbf1417a5166251eaa9547
