### ISSUE TITLE
[AC] [Question] [Group] Как начать атаку? 

### ISSUE THREAD

**Issue by Bogir** [trickerer/Trinity-Bots#866]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Настроил в конфиге круг = метка для танка, для ДД и для РДД.
Нанял 2 ДД - фурика и кота. Настроил им роль - ДД. Создал с ними группу.
Нашел кролика. Поставил метку Круг и жду.
Пробовал ставить метку на манекен - тоже не реагируют.

Как заставить ботов начать атаковать цель?
Нужно выполнить еще какие-то условия?

![изображение](https://github.com/user-attachments/assets/d9f0d65c-d41d-4c81-b997-4aec7f328429)

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

f93a683962811dcf29109ed7bc5f3f1627856d7f

### Operating system

Win7

**Comment by trickerer** [comment]
Метки дд и танкования задают приоритет в битве, а не заставляют ботов немедленно атаковать.
Как только и бот, и цель оказываются в режиме боя, тут приоритет и вступает в силу. Если на конкретного бота он распространяется, то из всех целей он будет выбирать помеченую.
В бою с одним врагом эти метки всего лишь снимают ограничение по дальности преследования (для соответствующих ботов).

**Comment by Bogir** [comment]
Спасибо за пояснение.
А как же начать саму битву? Как заставить бота атаковать выделенную цель, не трогая цель персонажем?

**Comment by Bogir** [comment]
А можно сделать более простое решение? 
Что-то типа `.npcbot attack` на основе того же `.npcbot order cast` или `OnOwnerDamagedBy(target)`, чтоб забиндить макрос безусловной атаки?

**Comment by trickerer** [comment]
Можно, хоть и не на основе указанного. Инструменты для подобного уже есть и опробованы.

**Comment by Bogir** [comment]
Сори за оффтопик
но тут фикс спама не сработал:  https://github.com/trickerer/Trinity-Bots/issues/853#issuecomment-2322029998, а тема уже закрыта.
Я сделал "костыль", сменив LOG_INFO на LOG_DEBUG чтоб остановить флуд в консоль,, но это только временное решение.

**Comment by trickerer** [comment]
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/ee76ff6128b56559cf5ff519ff69ee3190dc2178
