### ISSUE TITLE
[AC] [Bug] Modelid1 error injecting SQL 5_world_botgiver.sql 

### ISSUE THREAD

**Issue by Wimmetje1** [trickerer/Trinity-Bots#867]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

When Injecting the SQL file https://github.com/trickerer/Trinity-Bots/blob/master/AC/SQL/5_world_botgiver.sql in th SQL database it is creating errors on modelid1. This due to changes in the Azerothcore. 

### Expected behaviour

Injecting SQL without errors, i think it is related to modelid1,2,3,4 that was removed from the table?

### Crashlog

na

### Steps to reproduce the problem

Injecting https://github.com/trickerer/Trinity-Bots/blob/master/AC/SQL/5_world_botgiver.sql into SQL database

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

Azerothcore rev. fdb6fedc0050 2024-08-26

### Operating system

Debian 12

**Comment by trickerer** [comment]
Looks like that was an error on my part and this file was never updated. Oops
Still, you may want too read through this: https://github.com/trickerer/Trinity-Bots/issues/858
