### ISSUE TITLE
[AC] [Question] [Core] Question about bot rental timer / Вопрос по таймеру аренды ботов

### ISSUE THREAD

**Issue by Bogir** [trickerer/Trinity-Bots#868]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

в `bot_ai::GlobalUpdate` есть 2 проверки:
```cpp
if (IAmFree())        - если я свободен
{
    if (npcBotData->owner != 0)       - если я не свободен
       CheckOwnerExpiry(); 
   ...
}
```

Не могу понять логику IAmFree(). Логично предположить по коду, что бот свободен. Но тут же проверка есть ли у свободного бота хозяин, чего быть не может.
Или я неправильно понимаю логику IAmFree() ?

Просто таймер не срабатывает. Просто не попадаем в CheckOwnerExpiry();
По дебагу таймер, заданный в конфиге, считает интервал гораздо быстрее. Там, возможно, не секунды нужно указывать, а миллисекунды?

https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/blob/ee76ff6128b56559cf5ff519ff69ee3190dc2178/src/server/game/AI/NpcBots/bot_ai.cpp#L17303

### TrinityCore or AzerothCore

AzerothCore

**Comment by Bogir** [comment]
Может, Вы какой-то канал в Дискорде заведёте для таких вопросов? Им не место тут)

**Comment by trickerer** [comment]
> Может, Вы какой-то канал в Дискорде заведёте для таких вопросов? Им не место тут)

Своего сервера не имею ибо на это нет времени, а так меня можно найти на серверах Wor Repacks Community и Wow Modding Community. Если нужны ссылки напишу отдельно.

Условия в приведённом куске кода разные, очевидно и проверяют они разное.
- IAmFree() - свободен ли бот в данный момент времени (владельца нет либо вышел из игры)
- npcBotData->owner - собственно владелец

Из конфига: `NPCBot ownership may only expire after player goes offline`
Это и есть проверка что у бота есть владелец, но он оффлайн.
Что касается самого таймера, то его длительность выбирается, конечно, не оптимально - проверка хотя бы раз в час, лучше тогда я ничего не придумал.

Таймер в конфиге указывается в секундах. Возможно возникла путаница из-за `_checkOwnershipTimer` - так вот это другой таймер, время владения ботом проверяется только внутри `CheckOwnerExpiry()`

**Comment by trickerer** [comment]
> Ситуация патовая. NpcBot.OwnershipExpireMode = 1 _- timer never resets_ NpcBot.OwnershipExpireTime = 60 _-Time (in seconds)_
> 
> Нанял бота. Время прошло, бот не освобождается Бот исчез только когда я перезашел в игру
> 
> upd: если перезаходить в течение установленного времени OwnershipExpireTime, бот появляется снова. Перезашел через 70 сек - бот уже не появился.
> 
> Если в конфиге поменять режим 1 на 0 NpcBot.OwnershipExpireMode = 0 то таймер начинает считать время, проведенное в оффлайне, как и задумано. Если оставаться в оффлайне дольше заданного интервала - бот исчезает.

Так и должно быть. В режиме 1, если игрок успеет перезайти до того как таймер выйдет, бот останется при нём. Владение ботом может быть окончено только после логаута.
Например: таймер 1 минута - если выйти из игры через 55 секунд, то через 5 секунд бот освободится

P.S. похоже в вычислении таймера межде проверками есть мелкая ошибка (таймер почти всегда минимален) но это на вышеописанный алгоритм не влияет

**Comment by trickerer** [comment]
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/e58d6a2eb28b51fa45ed531a3b0e53a1768e9f4a
