### ISSUE TITLE
[TC] [AC] [Question/Feature] [Group/Spell/Core] How do I update the database without losing my bots?

### ISSUE THREAD

**Issue by OtavioProfeta** [trickerer/Trinity-Bots#870]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Hello, I would like to update my database with the current one available in the repository without losing my bots. I tried to do the procedure suggested in the documentation with the 'dump' command but after loading the .sql file my bots do not appear.

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

TrinityCore rev. 06a3daddfbac 2024-08-23 21:22:44 +0000 (npcbots_3.3.5 branch) (Win64, RelWithDebInfo, Static) (authserver)

### Operating system

Win10

**Comment by trickerer** [comment]
Did it say that it was imported successfully though?

**Comment by OtavioProfeta** [comment]
> Did it say that it was imported successfully though?

Yes

**Comment by trickerer** [comment]
Can't reproduce. Tried using https://github.com/trickerer/TrinityCore-3.3.5-with-NPCBots/commit/f33c6a6fe6b7102be023134ae7212d4decff8721 (there were no changes in dump / load algorithm in a long time)

- npcbot dump write 1
- delete bots from `creature` table and `characters_npcbot` table + restart worldserver OR use clean db with bot tables created
- npcbot dump load 1
- restart worldserver
