### ISSUE TITLE
[AC] [Crash] [Core] Server randomly crashing

### ISSUE THREAD

**Issue by imetators** [trickerer/Trinity-Bots#871]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Worldserver.exe is randomly crashing. Could be 10 seconds, can be over 5h but typically really quick in under 5mins. Do not even need to login. 

### Expected behaviour

Not crash I guess

### Crashlog

https://gist.github.com/imetators/a754104fe8da490a54468efcf0638e13

### Steps to reproduce the problem

1. Run worldserver.exe
2. wait...
3. recieve crash

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. c3be0fa2a8b4+ 2024-08-05 01:22:16 +0800 (Playerbot branch) (Win64, Release, Static) (worldserver-daemon)

### Operating system

Win11 Home 23H2

**Comment by Bogir** [comment]
Your core is compiled in the "Release" mode. This crash-log says almost nothing. For development, it is recommended to build in RelVindevInfo or Debug mode.

Then you'll be able to read the stack yourself. For example:
```
Call stack:
Address   Frame     Function      SourceFile
000000013FDFD5B2  000000000D77E5E0  bot_ai::ResetBotAI+72  D:\WOW\src\server\game\AI\NpcBots\bot_ai.cpp line 745
000000013FDBB605  000000000D77E620  bot_ai::bot_ai+4F5  D:\WOW\src\server\game\AI\NpcBots\bot_ai.cpp line 292
0000000140313A0E  000000000D77E660  blademaster_bot::GetAI+3E  D:\WOW\src\server\game\AI\NpcBots\bot_bm_ai.cpp line 55
000000013FB6C33D  000000000D77E7C0  ScriptMgr::GetCreatureAI+1AD  D:\WOW\src\server\game\Scripting\ScriptDefines\CreatureScript.cpp line 171
```

**Comment by trickerer** [comment]
Is this what you're using? https://github.com/liyunfan1223/azerothcore-wotlk

**Comment by imetators** [comment]
> Is this what you're using? https://github.com/liyunfan1223/azerothcore-wotlk

Not exactly. I got server files off a reputable torrent tracker. It is an all-in-one package unzip-and-run style. No compliling required. 

How do I recompile it in Release mode? Or should I compile it from the ground up?

**Comment by trickerer** [comment]
To compile you need source code, butt you seem to have no idea where it is located (maybe it isn't even public?). Thus there is no way to get a Debug build - no way to tell what the issue is.

<details><summary>spoiler</summary>
<p>

Your server isn't even a fork of main AC NPCBots repo https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots
</p>
</details>

**Comment by DykeRz** [comment]
> > Is this what you're using? https://github.com/liyunfan1223/azerothcore-wotlk
> 
> Not exactly. I got server files off a reputable torrent tracker. It is an all-in-one package unzip-and-run style. No compliling required.
> 
> How do I recompile it in Release mode? Or should I compile it from the ground up?

you cant recompile repacks
