### ISSUE TITLE
[AC] [Question] [Core] Are NPC Bots counts as player in ObjectAccessor?

### ISSUE THREAD

**Issue by jacatinelord** [trickerer/Trinity-Bots#872]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Hello, just wondering if NPC Bots counts as player?
i tried to fix something on the code that related to the ObjectAccessor that affect something in Item and Guild thing. Crashing sometimes because of invalid provided guid.
I do a console logging, and the ObjectAccessor constantly giving update, and i assume it is from the NPC Bots because the wandering NPC Bot is enabled and spawned many Free NPC Bot too, is that true?

Just wondering and asking, thank you for your time.

### TrinityCore or AzerothCore

AzerothCore

**Comment by trickerer** [comment]
NPCBots don't count as players.
NPCBots are creatures and thus have creature guids (always starting with `0xF130`). This 'high part' of a guid ensures that guids of different types do not intesect

The main implication regarding ObjectAccessor is: just like with any other creature, passing bot's guid to ObjectAccessor::FindPlayer type methods will always return nullptr

**Comment by jacatinelord** [comment]
I see, got it! Thank you for your explanation
