### ISSUE TITLE
BUG? - Bots are all gone

### ISSUE THREAD

**Issue by Jankey7** [trickerer/Trinity-Bots#873]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

When I enter the azerothcore based server, all my bots have completely vanished, can't be recalled, can't be found, they just don't exist for me any longer.

### Expected behaviour

I normally log in, and my entire raid group of bots is with me for raiding.

### Steps to reproduce the problem

I am unsure the exact cause since I logged out fine, then went back in the next day and they vanished, but I believe it might be connected to an error in game I sometimes get.

1.  Sometimes when trying to set focus (I am hunter trying to focus a tank), the game with give an error with two options, one is "ignore", and the other is "disable".  I can't remember the wording of the error unfortunately, and can't replicate since it is random, and now I have no bots to create the scenario.
2. I have done both in the past without issues, but after a while I just learned to use "/reloadui" to fix the issue, at which time I can easily use the set focus function without the error.
3. Last night I accidentally hit disable, which reloaded my interface, and I honestly don't know what that error is disabling, but today logging in, I now have no bots (might be related, might not, but that was the last and only issue I had during game play yesterday, so it seems related).

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. d4d758b13502+ 2024-06-16 22:53:36 -0600 (npcbots_3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

### Operating system

Win 10 Pro build 19045

**Comment by Jankey7** [comment]
Oh, FYI, I am looking for an idea on how to debug, check logs, troubleshoot where they went, and what could cause such behavior in case that wasn't obvious.

Thank you

**Comment by trickerer** [comment]
Did you make any changes to the config?
Did you update recently?

Try:
1) Check server startup for bot-related errors
2) `.npcbot list spawned`
3) Check your `creature` table (sort by creature id) vs `characters_npcbot` table and try to see if any bots in second table are missing from the first

**Comment by trickerer** [comment]
> I am unsure the exact cause since I logged out fine, then went back in the next day and they vanished, but I believe it might be connected to an error in game I sometimes get.
> 
>     1. Sometimes when trying to set focus (I am hunter trying to focus a tank), the game with give an error with two options, one is "ignore", and the other is "disable".  I can't remember the wording of the error unfortunately, and can't replicate since it is random, and now I have no bots to create the scenario.
> 
>     2. I have done both in the past without issues, but after a while I just learned to use "/reloadui" to fix the issue, at which time I can easily use the set focus function without the error.
> 
>     3. Last night I accidentally hit disable, which reloaded my interface, and I honestly don't know what that error is disabling, but today logging in, I now have no bots (might be related, might not, but that was the last and only issue I had during game play yesterday, so it seems related).

Sounds like an UI error, 'an addon trying to use a function reserverd for Blizard API' type of thing you may get sometimes with some addons when trying to set focus. That is completely unrelated.

**Comment by Jankey7** [comment]
Sorry about the delay.  I had started to write you about everything I had
tested, and then some of the guys from Dinkle's team jumped on Discord, and
one in particular was available.  I talked with him about it midstream
writing you back (tested everything you said to, and found nothing).

Ultimately, and you are going to find this stupid I suppose, but it was due
to me being attacked over and over and over and was so pissed, I finally
threw the dang game into GM mode (done it many times to get through a
farming run), and was so tired, I forgot to turn it off.  Well, oddly
enough, if you turn it on, everything is the same, but you don't get
attacked (normal behavior).  IF, you log out and in, NO BOTS WILL EVER
APPEAR!?!?  Worse, I had dropped my raid so that they wouldn't drag me into
any more fights with the stupid guards, so I didn't even have my group
frames to show that they were possibly there somewhere.  During my test log
off and log back on to learn the behavior after I got them to come back
with GM mode off and a "recall", I happened to be in raid that time, and I
had them in group, but otherwise invisible, so at least that time it gave
me a hint as to where they were.  Unfortunately, there isn't much to let
you know you are in GM mode (like game goes a diff color, or displays GM
mode somewhere obvious or on login, etc.), so you are at the mercy of your
memory, or some troubleshooting (if I had something to go do solo, I would
have easily spotted it, but I didn't, so again, very hard to spot being I
was only in IF or Light's Hope, and no horde showed in the less than 1
minute I tele'd there to see if my bots were standing around.

I am so thankful for the help, and sorry about the GM thing, but no one had
a clue, so I guess it isn't very common?  One guys said, maybe check GM
after we checked all sorts of other stuff, and it was turned on, at which
time, he was like, "I sometimes through out a lame idea, and it pans out
half the time, I can't believe it!"  Hahaha.



<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by trickerer** [comment]
Yeah, I guess I could document this but bots won't try to re-join you after log in while in GM mode until you disable it - this is intended behavior.
GM mode is shown in chracter name. Since I mostly do dev things while in game I keep 'show own name' option enabled at all times. There is also 'GM badge in chat' config param IIRC.

**Comment by Jankey7** [comment]
Thank you for that information, I will check for those settings to see if
they help me spot the mode I am in better.

The start of the cause is really to do with the bad setup at lights hope.
In Everlook, put bots on slack, they get attacked, guards demolish the
attackers, and I don't get drug into fights, but for some stupid reason at
light's hope, they can attack me or my bots and not deal with guard
retribution. If I am getting their gear for them and trying to outfit them,
I can't because they are in battle, so I have to kill horde or let them
kill horde, and then we are all flagged. The mechanic in that specific area
just sucks. I am moving along with their Naxx gear, so I shouldn't be stuck
there much longer, but still, that's annoying in a very non-fun,
non-functional way when outfitting bots. The only saving grace was
remembering that GM mode stops attacks or takes me out of agro with guards
when it goes sideways. I am very curious why those guards act differently.

You have a great week
