### ISSUE TITLE
[AC] [Bug] [Spell/Core] The buff Blessing of Kings affects the wrong bot stats / Благословение королей действует не на те статы боту

### ISSUE THREAD

**Issue by Bogir** [trickerer/Trinity-Bots#874]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Вхожу в мир персонажем Воин 80 уровня, одет в т9 за триумф +/-.
Нанял бота Воин и одел в точно такой же шмот. Показатели здоровья у меня и у бота отличаются. Ну, это и ожидаемо, всё-таки бот - это НПС и статы заданы Вами вручную.

Вопрос:
Баф каски от другого бота-паладина мне поднял здоровье почти на 2000 (и прочие статы), а боту только на 393
Является ли это багом? Может, баф каски действует не на те статы ботов?

Вопрос 2:
Можно в ядре добавить исключение для бафа игроком НПС, если этот НПС является ботом? Чтоб игрок мог бафать ботов.

### Expected behaviour

Ожидаемо, что баф каски поднимет статы бота так же, как поднимает на простом персонаже. 

### Steps to reproduce the problem

- войти в мир и запомнить свои статы (размер ХП) без бафа
- нанять бота не паладина, взять его в группу и запомнить его статы (ХП) без бафа
- нанять паладина, взять в группу и после раздачи им бафа Благословение королей сравнить на сколько увеличились статы персонажа (ХП) и бота.

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

f93a683962811dcf29109ed7bc5f3f1627856d7f

**Comment by trickerer** [comment]
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/38c114881e61a0175b4e7e76e376e4d223f8a282

**Comment by Bogir** [comment]
Вроде стало гораздо лучше. Спасибо!
