### ISSUE TITLE
[TC] [Question] How do I get the creature list back?

### ISSUE THREAD

**Issue by Codewow** [trickerer/Trinity-Bots#875]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

I think I am frustrating myself. Was there not a SQL script to pre-populate some creatures into the world tables for the bots? Where can I find that. I swear it was a provided file, but I may be going insane as my brain is mush from work this week...

### TrinityCore or AzerothCore

TrinityCore

**Comment by trickerer** [comment]
No, there is no sqls for that, only macros: https://github.com/trickerer/Trinity-Bots/issues/279#issuecomment-1340923970

**Comment by Codewow** [comment]
So I am getting "Creature X does not exist" as the error when trying to spawn any. Those creature IDs aren't in the creature table at all and I am extremely confused as to why.

**Comment by trickerer** [comment]
If you cannot spawn a bot with this message then bot entries are missing from `creature_template` (not `creature`) table, meaning your server setup wasn't completed. Unlike AC, TrinityCore setup requires manual SQLs execution (from sql/Bots/).

**Comment by Codewow** [comment]
When starting the world server this is what it is saying.

I used the ALL_world.sql file to populate the tables, but still getting this:

Cannot spawn npcbot Thran (id: 70002), not found in `creature` table!
Cannot spawn npcbot Lyria (id: 70003), not found in `creature` table!
Cannot spawn npcbot Ander (id: 70004), not found in `creature` table!
Cannot spawn npcbot Malosh (id: 70005), not found in `creature` table!
[...]

**Comment by Codewow** [comment]
I didn't figure out how to fix it, luckily I had a backup of the server that I pulled the creature table from. Very strange that the All_world file wasn't repopulating the Ids though..
