### ISSUE TITLE
[AC] [Bug] Battleground bot generation breaks if player group size matches minimum amount of players

### ISSUE THREAD

**Issue by EllieSca** [trickerer/Trinity-Bots#878]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

When joining battleground queue with equal or larger number of players than MinPlayersPerTeam defined in battleground_template database table bot generation breaks.

### Steps to reproduce the problem

1. Set MinPlayersPerTeam in battleground_template for WSG to 1
2. Attempt to queue for WSG with 2 players in group

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. 409d2f138e37+ 2024-09-08 07:23:42 +0700

**Comment by Codewow** [comment]
I think we encountered this on TrinityCore as well. Me and 3 others + 1 bot joined WG to meet the 5 minimum, 1 player + 4 bots joined on the opposing side and no bots were generated. 

We also tried it with a full 4 player + 6 bot group and and 1 player 4 bot group and no bots generated on the opposing side to fill the remaining slots.

**Comment by trickerer** [comment]
Thats because BG queue manager count such rounded group as premade and doesn't try to match it with normal groups. Any group having members count >= minimum team members per team for that BG counts a premade

**Comment by trickerer** [comment]
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/80e1dbe736cbb6c4b501e9cade12228991717b1b
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/0091b43f3d40c6114ae8fa55f851999b11cf9c9d

**Comment by trickerer** [comment]
The issue must be closed only when these changes get added to the patches, you don't need to bother
