### ISSUE TITLE
npcbot dump load

### ISSUE THREAD

**Issue by zaicopx** [trickerer/Trinity-Bots#88]
Every time I use the .npcbot dump load command, an error appears like that and NPCBot is not on my server. I am using the latest npcbots patch.
```
[1264] Out of range value for column 'randomPropertyId' at row 6
Unhandled MySQL errno 1264. Unexpected behaviour possible.
```

**Comment by trickerer** [comment]
Quickfix (if you can re-extract old data):
botdump.cpp:L867
```
                }
                case 7:  //randomPropertyId
+                    AppendEscapedValue(ss,     int32(fields[i].GetInt16()),   end);
+                    break;
                case 8:  //durability
                    AppendEscapedValue(ss,     uint32(fields[i].GetUInt16()),  end);
                    break;
```

Otherwise you'll need to manually find faulty values in your dump and convert them to negative (they overflow int16) or just set them to zero

**Comment by zaicopx** [comment]
Ok, I'll try to add line on botdump.cpp

**Comment by zaicopx** [comment]
Thx now i can load npcbot
