### ISSUE TITLE
[TC] [AC] [Bug/Crash] Set Wandering Bot to 290 - Game freezes from lag

### ISSUE THREAD

**Issue by RobertoHendo** [trickerer/Trinity-Bots#883]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

I have set my wandering bots to 290 and about 5-10 minutes in game my game freezes and no longer lets me interact with anything, it then crashes. In the Error Logs it says SmartScript::ProcessAction: Entry 18945 SourceType 0, Event 3, Link Event 4 not found or invalid, skipped. which if im not mistaken may be attached to NPCBots, any help would be appreciated, thank you.

### Expected behaviour

Bots should load 

### Crashlog

SmartScript::ProcessAction: Entry 18945 SourceType 0, Event 3, Link Event 4 not found or invalid, skipped. repeated over and over

### Steps to reproduce the problem

enter worldserver.conf
change bot count from 0 to 290
play game as normal
crash

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. 64c9e4a0a4d5+ 2024-09-15 21:16:14 +0000 (master branch) (Win64, RelWithDebInfo, Static) (authserver)

### Operating system

Win10

**Comment by trickerer** [comment]
Attach a Debug crashlog please. The smart script error you mention has nothing to do with bots

**Comment by RobertoHendo** [comment]
I hope this is what you need, i'm not very tech savvy yet. I apologize if this still isnt what you need.
[Worldserver_debug_output.txt](https://github.com/user-attachments/files/17070581/Worldserver_debug_output.txt)

**Comment by trickerer** [comment]
This isn't a crashlog.
But even from this output I can tell it's probably same as https://github.com/trickerer/Trinity-Bots/issues/876 and you'll have to just wait for next update where the fix will be included

**Comment by RobertoHendo** [comment]
Awesome, thank you for your quick response time and assistance. it is appreciated
