### ISSUE TITLE
[AC] [Bug] [DB/Core] Player Remains on Transport after leaving it.

### ISSUE THREAD

**Issue by Dranos-Nupper** [trickerer/Trinity-Bots#884]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

https://www.youtube.com/watch?v=ZlFWcgzGykQ (Video of the Transport Bug)
![image](https://github.com/user-attachments/assets/896ec63b-2576-47d9-94ac-594331bad546)
![image1](https://github.com/user-attachments/assets/8d0b5b45-00f9-4ffe-8f50-55ebf0f0916c)
![image2](https://github.com/user-attachments/assets/4a7c30ac-dbe7-41de-b4bd-c2894f0273f7)

Can Confirm that ALL Ships and Zepplins and Turtles have this issue. 

### Expected behaviour

The Transport does not take you with it when it leaves.

### Steps to reproduce the problem

1) Step on Transport. 
2) Leave transport or Leave at Next Destination.
3) Wait for Transport to leave outside Transport.
4) Transport takes you with it regardless where you are.

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. ceeba694710b+ 2024-08-06 11:38:27 +0700 (npcbots_3.3.5 branch) (Win64, Release, Static) (worldserver-daemon)

### Operating system

Win10

**Comment by trickerer** [comment]
Unable to reproduce using https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/edc0b1dd4e02562637e0401c5abd2ae452687bd4. Checked Ratchet ship, also tries to follow exact steps shown in video but nothing.
I mean that looks pretty severe and I honestly don't see how bots code could break transport interaction with player.

Try without whatever custom code you got there. Try updating your core, I see it a month old. Try to reproduce on clean AC.

**Comment by Dranos-Nupper** [comment]
I've Updated the Core and the Only changes i made is 
![image](https://github.com/user-attachments/assets/4fec71dc-1a20-4a93-9181-99791fb48ad8)
It also has Mod-Eluna thats all. 

Unless it can be a DBC issue i am not sure.

**Comment by Dranos-Nupper** [comment]
This issue was with the WMO File itself. Due to Modding Newer Expansion to 3.3.5a i apologize for the waste of time.
