### ISSUE TITLE
Npcbot and equipment

### ISSUE THREAD

**Issue by German0Mike** [trickerer/Trinity-Bots#885]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Hello everyone. Is there a setting where you can set what kind of equipment an NPCbot has equipped? As an example, an NPCbot has a Tier 1 set as its own armor?

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

409d2f138e37+ 2024-09-08 07:23:42 +0700 (npcbots_3.3.5 branch)

### Operating system

windows 10

**Comment by Bogir** [comment]
Bot on create is dressed on starting items as regullar character. Then hired, player MUST to give items to bot manually

**Comment by trickerer** [comment]
Only wandering bots have 'their own' items.
Hired bot's equipment is managed by player owner only. Since bot's main purpose is to help during leveling and they can be hired at level 1 there is no point to have any initial gear

**Comment by Badgermilk0** [comment]
How does this work in practice - I can recruit 4 "fresh" bots, not give them any items, do a random dungeon and feel that they do very good damage, tanking, healing.

Do they have some base level stats that scale regardless of equipment?

They have previously acted as wanderbots if that makes a difference.

**Comment by trickerer** [comment]
I do get what you want and you're not the first one to propose this.
I'm not doing any kind of automatically created gear for owned bots, automatic stat scaling or short-term / single-use bots created for the players. Players have either commit to their bot management or not use them at all.
