### ISSUE TITLE
[TC] [Bug] [Core] Autobalancefornpcbots проблема с лутом

### ISSUE THREAD

**Issue by DykeRz** [trickerer/Trinity-Bots#887]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Некоторые боссы не дропают лут с включённым автобалансом, например как Бальнвззар в Стратхольме

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

Last

### Operating system

Debian 12

**Comment by trickerer** [comment]
https://github.com/trickerer/Autobalance_for_NPCBots/commit/a22c2608dc538b1d9a00f479c1e2607b38bb16a9
