### ISSUE TITLE
[TC] [Question] [Core] Объясни подробнее о NpcBot.Premade.Enable

### ISSUE THREAD

**Issue by DykeRz** [trickerer/Trinity-Bots#888]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Что и в каком случае оно делает?

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

last

### Operating system

debian 12

**Comment by trickerer** [comment]
В случае если группа, регающаяся на БГ, имеет ботов, и при этом может быть квалиицирована как premade (размер группы >= минимальное кол-во игроков в БГ для каждой стороны):
- `1` - регать как premade (матч только с другой такой же группой, не создавать ботов для БГ)
- `0` - регать как обычную группу (с созданием ботов для БГ)

По дефолту `0`

**Comment by DykeRz** [comment]
спасибо
