### ISSUE TITLE
[TC] [AC] [Question/Feature] [Group/Spell/Core] Gossip Window

### ISSUE THREAD

**Issue by FlailingGiraffe** [trickerer/Trinity-Bots#889]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Hi there, im interested in changing the text in the gossipwindow for the npcbots, i was wondering what files id check under to get that changed. Thanks

### TrinityCore or AzerothCore

AzerothCore

### Operating system

WIN10

**Comment by trickerer** [comment]
Gossip menu text is contained in `npc_text` table, `npc_text_locale` for non-EN locales.
Main (non-clickable) text id is hardcoded and is set in core within `OnGossipHello()` method by `gossipTextId` variable (`bot_ai.cpp`). Its value is 70001 with some options for non-standard classes.
Gossip menu option (clickable) color for items/spells/etc. is handled by `_AddXYZLink()` (`bot_ai.cpp`).
Whatever changes you make, clear client's cache before testing it.

**Comment by trickerer** [comment]
Only NPCs having bot ai script initialized get added to botgiver hiring list. Did you copy an NPC from bot creature or something? Clear its scriptname field then.
