### ISSUE TITLE
New Feature Request - Make 'em jump

### ISSUE THREAD

**Issue by skipperheart** [trickerer/Trinity-Bots#89]
Would it be possible to have a command that makes you group of bots jump? The last boss in the Nexus is not possible unless the group jump to remove the DOT.

**Comment by trickerer** [comment]
Last time I did Nexus just moving around was enough. Did it change?

**Comment by skipperheart** [comment]
I tried a couple of days ago. Need to jump and there's no option to do it. If i get a chance tonight, i will try hide and unhide as that might do it, but jump would be the way to fix it.

**Comment by trickerer** [comment]
Tested it today. You don't need to jump, only move.
Reduce your bot follow distance and after #78 fix moving bots around the boss won't be a problem.
