### ISSUE TITLE
[AC] [Question] [Core] Specific commit for Hide NPC Bots Spawn

### ISSUE THREAD

**Issue by jacatinelord** [trickerer/Trinity-Bots#890]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Hello, i am searching for commits about the feature hiding the spawn of npc bot.
I just wanted to try to update my core with that feature only not by all.
Can you help me with providing any specific commits? I tried search for it cant find a thing.

Thank you ❤️

### TrinityCore or AzerothCore

AzerothCore

**Comment by trickerer** [comment]
These are the related commits I found, you'll need to apply them in this exact order. Still, it's not impossible that you'll be left with some compile errors, in that case please fix them yourself - don't ask here
- https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/0b5b5b36f4aac1ee3c2819e8a4f1fcaeead9e9ed
- https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/84a806cae5067a5819a4500820ebf14f868f937d
- https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/d42c384a71d33205ab62cf77e84401c9dff07992
- https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/0289fd97dccb689e750c0780bbdd7e4c539667e9
- https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/2d0d09c2996654e5b00a03c00c9e60687aa4adf5
- https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/d03fa111123fccb47c6faa6335c511663fe36130
- https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/d36a1c038a994b308aeb2dd0bffb6d48fd06e143

**Comment by jacatinelord** [comment]
i understand that, thank you so much
