### ISSUE TITLE
[TC] [Bug] [Core] Lich King chasing bots that fall through the floor.

### ISSUE THREAD

**Issue by Codewow** [trickerer/Trinity-Bots#891]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Since bots don't die from falling when the floor collapses during the LK fight, it is causing LK to follow them under the floor and get stuck. 

I don't know what a great workaround for this would be other than hardcoding them dying or teleporting faster when they get below a certain Y axis level on that specific map.

It really breaks the fight.

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

f7f1c8f1e3e3 2024-09-14 07:51:23 +0700 (npcbots_3.3.5 branch)

**Comment by trickerer** [comment]
https://github.com/trickerer/TrinityCore-3.3.5-with-NPCBots/commit/9b47545100cb8207893d697a598ff844147d0a46
