### ISSUE TITLE
[TC] [Crash] Sindragosa Crash and Bots lose AI

### ISSUE THREAD

**Issue by Codewow** [trickerer/Trinity-Bots#892]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

When doing the Sindragosa encounter, the worldserver will crash moments after the party wipe attack occurs. 
The bots will also lose AI during the fight when the player gets encased in ice. The ones that don't die during the ice portion will just stand there and do nothing afterwards.

### Expected behaviour

Bots will remain fighting and the server doesn't crash. :)

### Steps to reproduce the problem

Engage the boss until the phases begin. Notice that ice block begins to cause the AI to lock up. And eventually, the server crashes during the fight.

I'll try to grab a crash log the next time it happens. It is nearly every time at the moment though.

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

f7f1c8f1e3e3 2024-09-14 07:51:23 +0700 (npcbots_3.3.5 branch)

**Comment by trickerer** [comment]
https://github.com/trickerer/TrinityCore-3.3.5-with-NPCBots/commit/03def08976ec940fe3034694dd9df36347259331

Couldn't reproduce the crash though

**Comment by Codewow** [comment]
I’m also still waiting for them to break it. They’re using so many bots now that they kill Sindy before it enters the flying phase which is where the crash typically happens and the AI of bots freezes.On Oct 25, 2024, at 12:30 AM, trickerer ***@***.***> wrote:﻿
***@***.***
Couldn't reproduce the crash though

**Comment by trickerer** [comment]
Once you get a crashlog, please open a new issue
