### ISSUE TITLE
[TC] [Bug] [ICC] Bots stop healing Valithria Dreamwalker at 99% health in the healing fight in ICC

### ISSUE THREAD

**Issue by Codewow** [trickerer/Trinity-Bots#893]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

The bots will not completely heal Valithria Dreamwalker and stop at 99%

### Expected behaviour

The bots should continue to heal Valithria until the encounter is complete and Valithria is untargetable.

### Steps to reproduce the problem

Start the Valithria Dreamwalker encounter in ICC
Have bots heal Valithria.
Notice bots stop healing at 99%

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

TrinityCore rev. f7f1c8f1e3e3 2024-09-14 07:51:23 +0700 (npcbots_3.3.5 branch)

**Comment by Bogir** [comment]
![изображение](https://github.com/user-attachments/assets/b7eabe91-1024-4c09-a304-ad4a19c2f099)

**Comment by Codewow** [comment]
> ![изображение](https://github.com/user-attachments/assets/b7eabe91-1024-4c09-a304-ad4a19c2f099)
> 
> 

Bots have a setting to heal up to a threshold? 😮

**Comment by Codewow** [comment]
Appreciate it! None of us noticed that option when setting up our bots! 😆
