### ISSUE TITLE
[AC] [Bug] [Spell] Magisters Terrace: NPCBots don't evade Phoenix and arcane sphere AoE damage

### ISSUE THREAD

**Issue by Boxhead78** [trickerer/Trinity-Bots#894]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Magisters Terrace, boss_felblood_kaelthas
Bots do not evade aoe damage of either the phoenix or arcane sphere if nearby.

### Expected behaviour

Bots should move away from those two creatures in order to avoid the AoE damage.

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. b3b361750288+ 2024-10-10 15:29:33 +0200 (npcbots_3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

**Comment by trickerer** [comment]
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/dfb282d17b11d52c47440b7928471aa8b0b13586
