### ISSUE TITLE
Worldserver crashes when Mind control Is casted on me 

### ISSUE THREAD

**Issue by Machalote** [trickerer/Trinity-Bots#896]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Worldserver crashes If any boss cast Mind Control on me. This happens on every boss for example Hakkar when he cast Mind Control on me and I start to attack bots (or bots starts to stun/root me) the server starts to lag and worldserver suddenly crash no matter what I do it keep crashing.

I tried with Nefarian which also casts Mind control and it crashes on the same way

### Expected behaviour

What should happen is bots should polymorf me or even root me and I should be back to the fight once Mind control has ended.

### Steps to reproduce the problem

Any boss who uses Mind control is engaged
For example Hakkar uses Mind Control
Server starts to lag and 10 seconds later crashes
Need to reopen Worldserver 

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. 79b975d9c91a 2024-05-20 19:24:45 +0700 (npcbots_3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

### Operating system

Win 10

**Comment by trickerer** [comment]
Post a Debug crashlog please

**Comment by Machalote** [comment]
Where can I find Debug crashlog?

**Comment by Bogir** [comment]
> Where can I find Debug crashlog?

![изображение](https://github.com/user-attachments/assets/f0a74af3-a474-453e-8ba9-1d175e4760ff)

**Comment by trickerer** [comment]
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/79b975d9c91a is super old.
Can't confirm on https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/a126f721fadb093e8cf0fcc300310a309e78df3d. Try updating your core

**Comment by trickerer** [comment]
Please re-open once you have the crashlog
