### ISSUE TITLE
[TC] [Feature] [Core] Save individual bot settings

### ISSUE THREAD

**Issue by Codewow** [trickerer/Trinity-Bots#897]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Configuring bots to be at specific follow distances, combat settings, etc all reset when you log out. Being able to have these save automatically would be great and reduce the amount of time spent reconfiguring them when you log back in.

### TrinityCore or AzerothCore

TrinityCore

**Comment by trickerer** [comment]
https://github.com/trickerer/TrinityCore-3.3.5-with-NPCBots/commit/509097f52d09568d78935f7e49361cd1e80e194d
Don't forget to execute that new SQL file

**Comment by trickerer** [comment]
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/eb66e77900bc7142ed70ed61117a07737d4f4fd9
