### ISSUE TITLE
[AC] [Question] How are the BOT stats calculated

### ISSUE THREAD

**Issue by Badgermilk0** [trickerer/Trinity-Bots#898]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

How are the NPCBot Stats calculated?

It seems they are granted HUGE bonues, example:
My lv 44 TANK BOT has over 170 in all resistances, 36% dodge, 52% block, 62%(!) crit etc.

He is in practice immortal in any current level dungeons.

Is it supposed to work like this or is something wrong with my compilation?

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. 0091b43f3d40 2024-10-06 14:11:50 +0700 (npcbots_3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

### Operating system

Win 11

**Comment by trickerer** [comment]
Looks like a regression from https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/38c114881e61a0175b4e7e76e376e4d223f8a282

https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/a126f721fadb093e8cf0fcc300310a309e78df3d

**Comment by Badgermilk0** [comment]
Thank you trickerer - I'll make a new build and check if it looks "better". :)

**Comment by Badgermilk0** [comment]
It seems to be much more reasonable now, my lv 44 tank now has 12.5% crit instead of 62.
15% dodge and 10% block etc.

Seems like you fixed it, thank you!

**Comment by trickerer** [comment]
Issue should only be closed when the fix is added to the patch. You don't need to bother.

**Comment by Badgermilk0** [comment]
sorry - also as a continuation if this is expected behavior:

lv 8 tauren with a lv 8 bot - "naked" stat comparison.

![image](https://github.com/user-attachments/assets/cc721eef-2cc7-458a-8e4a-2c8f0fb74b80)

**Comment by trickerer** [comment]
Yes, bots differ from player in stats a little at low levels since creatures have to have some base damage and different races have different base stats and racial passives. Also crit and block/dodge/parry chances depend on weapon skill level and defense skill level respectively which are always max for creatures for their level, bots included
