### ISSUE TITLE
[TC] [Bug] [Core] Minimum Requirements still exist for BGs that are implemented for bots except Warsong

### ISSUE THREAD

**Issue by Codewow** [trickerer/Trinity-Bots#899]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

With bots enabled for BGs in the config and bot generation set for minimum thresholds, the minimum player requirement still exists for every BG other than WG.

### Expected behaviour

Joining each enabled BG (that is implemented) should allow joining with 1 player and generate bots for it if enough are available.

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

TrinityCore rev. 9876fd754efc 2024-10-12 08:08:52 +0700 (npcbots_3.3.5 branch)

**Comment by Codewow** [comment]
Workaround: Edit the battleground_template table in the world database, setting minimum player requirement to 1 or 0 if you want to enable solo player queues to start a bg.

**Comment by trickerer** [comment]
> bot generation set for minimum thresholds

Please provide an example (i.e. steps to reproduce) as I don't entirely understand what you mean by this

**Comment by trickerer** [comment]
NPCBots system isn't supposed to change Battleground minimum participants requirement. Hope steps to reproduce are provided before next merge, otherwise the issue will be closed as invalid

**Comment by trickerer** [comment]
Could be related.
https://github.com/trickerer/TrinityCore-3.3.5-with-NPCBots/commit/28ea7375e3e1a53374fe265af576e0836e0c1a06
