### ISSUE TITLE
[TC] [Feature] [Core] Боты на БГ для всех

### ISSUE THREAD

**Issue by DykeRz** [trickerer/Trinity-Bots#900]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Хотелось бы реализации что бы боты присоединялись ко всем игрокам, на данный момент только один игрок может играть на БГ с ботами против ботов, но если второй игрок зарегистрирует это же БГ, он окажется в очереди как один игрок и ему не дают ботов

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

last

### Operating system

debian 12

**Comment by Bogir** [comment]
Если второй игрок пожелает присоединиться к тому БГ, о котором сервер объявил в анонсе, то у него есть время 2 минуты чтоб войти вместе с ботами (или вместо одного из них, он будет выкинут) в одну из команд этой битвы. Вероятнее всего - в противоположную первому игроку, создавшему очередь. У меня постоянно первый попадает за орду, второй - за альянс.

@trickerer 
тут возможен слив хонора на публичном сервере. Для домашнего это некритично...

**Comment by DykeRz** [comment]
> Если второй игрок пожелает присоединиться к тому БГ, о котором сервер объявил в анонсе, то у него есть время 2 минуты чтоб войти вместе с ботами (или вместо одного из них, он будет выкинут) в одну из команд этой битвы. Вероятнее всего - в противоположную первому игроку, создавшему очередь. У меня постоянно первый попадает за орду, второй - за альянс.
> 
> @trickerer тут возможен слив хонора на публичном сервере. Для домашнего это некритично...

да, вообще должно быть что бы если это время присоединения прошло, то следующая регистрация регестрировала бы новое БГ с ботами

**Comment by trickerer** [comment]
Не получится.
Проблема в менеджере очереди БГ, при регистрации второй группы, если на БГ есть свободное место, то из очереди боты попадут сначала туда. В работу очереди я вмешиваться не хочу.

Если на БГ есть свободный слот, то зарегистрировавшийся игрок может попасть туда на протяжении всего БГ, если `Battleground.InvitationType = 0`. Если все БГ заполнены полностью, боты генерируются как обычно.

Достаточно просто поставить `NpcBot.WanderingBots.BG.TargetTeamPlayersCount.XX` на максимум для этого БГ. Например `NpcBot.WanderingBots.BG.TargetTeamPlayersCount.WS = 10`
