### ISSUE TITLE
[AC] [Bug] [Core] Wintergrasp Demolishers Bug

### ISSUE THREAD

**Issue by cesuogui** [trickerer/Trinity-Bots#901]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

![WoWScrnShot_100924_210232](https://github.com/user-attachments/assets/2f96d79c-57a4-4216-9cce-8c5c2c52f8db)
![WoWScrnShot_100924_210321](https://github.com/user-attachments/assets/36346e20-3dda-457e-a50e-1cfe722a773d)

### Expected behaviour

in Wintergrasp Demolishers the bots can‘t became barbette

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. e07426e251e45febd301ac09d1f10924ca4802d6+ 2024-07-17 08:51:25 +0700 (npcbots_3.3.5 branch) (Unix, RelWithDebInfo, Static)

### Operating system

Debian 12

**Comment by trickerer** [comment]
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/2bd32cbfd3b5d096406726cef558c2c8b11809f6

**Comment by trickerer** [comment]
The issue shall only be closed when relevant code changes are merged into  patches
