### ISSUE TITLE
[AC] [Feature] [Group/Spell/Core] Additional level based configuration

### ISSUE THREAD

**Issue by Badgermilk0** [trickerer/Trinity-Bots#903]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Would it be possible/appropriate to add additional configurations based on the level for damage, health etc.

An extension of the following parameter:

    NpcBot.Mult.Damage.Levels
        Description: Multipliers for bots' damage by level: 0-9, 10-19, 20,29, ... , 70-79, 80+.
                     At least 9 values required.
        Default:     1.0
        Minimum:     0.1
        Maximum:    10.0
NpcBot.Mult.Damage.Levels = 0.5,0.5,0.5,0.6,0.6,0.6,0.6,0.7,1.0

To support Individual Progression, could we also get level based:
HP
Healing

Also, is it possible to make lv 60 and 70 their own brackets, or able to manipulate in config?

### TrinityCore or AzerothCore

AzerothCore

**Comment by trickerer** [comment]
I only support mods I develop so it doesn't really matter what you want that feature for as long as you don't use this tracker to file bugs caused by something other than bots.

https://github.com/trickerer/Trinity-Bots/issues/444. Well if I did that for damage it must be possible to do the same for HP and healing as well.
> Also, is it possible to make lv 60 and 70 their own brackets, or able to manipulate in config?

I'm not doing that, sorry

**Comment by Badgermilk0** [comment]
Thank you for your response.
Consider if it is appropriate for you to add as additional configuration. :)

**Comment by trickerer** [comment]
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/953c84a658efd778525cc651a0906b6fb9d887ef

**Comment by Badgermilk0** [comment]
wow, amazing as always!!
Thank you for the feature!
