### ISSUE TITLE
[AC] [Bug] [Core] Expertise not applying to Bots

### ISSUE THREAD

**Issue by Wowzers01** [trickerer/Trinity-Bots#904]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Expertise does not seem to be applying to bots.
Ongoing dodge and parries despite experitse cap (Bot @ 57) against boss level mob.

Prot Warrior bot.

~2000 swings
parry ~11%
dodge  ~4.5%

These numbers seem to be inline with the inate expertise, but not expertise from gear.

### Expected behaviour

expertise cap 56+ should eliminate dodges and parries while attacking.

### Steps to reproduce the problem

Engage boss.
Review Combat log.

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. d4d758b13502+ 2024-06-16 22:53:36 -0600 (npcbots_3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

### Operating system

win10

**Comment by trickerer** [comment]
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/0458d25163e3c5bb9657a04a2d18db707e4ce1c8

Looks like expertise was only applied to white hits for some stupid reason.
Also fixed expertise from auras not being listed

Here's result after the fix:
200 Maul hits
1. expertise: 0 (Primal Precision removed). Dodge doesn't show up but it's 5%
2. expertise: 56 (rating from items & auras, plain expertise from auras)

![expertise](https://github.com/user-attachments/assets/9f425eca-07f2-4610-8893-01bf07e739df)
