### ISSUE TITLE
[AC] [Bug] [Core] Боты не воспринимаются в качестве противника для ачивок на поле боя

### ISSUE THREAD

**Issue by Bogir** [trickerer/Trinity-Bots#906]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

![изображение](https://github.com/user-attachments/assets/bcfe5f32-8fb1-495f-978b-2a3d022446b8)

Было бы здорово, если Почетные победы над ботами засчитывались бы в зачет ачивок.
Пробовал сам убивать - победы добавляются в статистике поля боя, но в ачивку и в общий счетчик персонажа - нет.
![изображение](https://github.com/user-attachments/assets/307b27b0-4209-4e11-8c8d-67c9ee08b48f)

Пробовал бафать свою группу, чтоб их киллы тоже мне в победы засчитывались, но и они не идут в зачет ачивок.

### Expected behaviour

Пробовал найти условие в ядре, в котором убитый засчитывается или не засчитывается, но чёт не нашел )

### Steps to reproduce the problem

1. Запустить БГ. Напр. Ущелье песни войны и дождаться начала боя.
2. Использовать Г.Л.А.Д.О.С.Т.И (влияет только на доп.  ачивку по Тыквовину)
3. убить противника и убедиться по Alt+H, что убийство не засчитано, но в сводке текущего боя (значек под миникартой) в таблице будет +1 почетная победа

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

a126f721fadb093e8cf0fcc300310a309e78df3d

### Operating system

Win7

**Comment by trickerer** [comment]
Попробуй с https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/2c3b32c2bf7acaf09877721091e4326b05937968
Там есть ещё баг с требованием по дамагу но само убийство засчитывается и прогресс ачивки тоже

**Comment by Bogir** [comment]
Спасибо, попробовал.
По-прежнему убийства не засчитываются...

**Comment by trickerer** [comment]
Возможно только первое убийство не засчитывается (для каджого бота в отдельности)

**Comment by trickerer** [comment]
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/5105b65808c8e3f8fd79f7287c8b588c29c84f01

Проверил на БГ. Любой урон засчитывает убийство при смерти бота, после респавна бота флаг сбрасывается. То же самое сделал для нанятых ботов. Прогресс ачивки есть (сама ачивка багнутой не была, только ХК)

**Comment by Bogir** [comment]
Срочно проверяю )

**Comment by trickerer** [comment]
Нет тут ничего срочного :stuck_out_tongue:

**Comment by Bogir** [comment]
> Нет тут ничего срочного 😛

Тыквовин подходит к концу, а выполнить его ачивку без этого счетчика не получится...

**Comment by trickerer** [comment]
Проверь ещё раз что смерджил изменения


https://github.com/user-attachments/assets/bf398337-0233-450a-8d8f-5f8d794534ab


https://github.com/user-attachments/assets/beea112c-9d7a-4ec3-ab27-db5d249e97b0

**Comment by Bogir** [comment]
GameType = 16    // FFA_PVP, Free for all PvP mode

NpcBot.HK.Enable = 1
NpcBot.HK.Message.Enable = 1
NpcBot.HK.Achievements.Enable = 1
NpcBot.HK.Rate.Honor = 1.0

Может, еще какие-то параметры нужно включить?

**Comment by Bogir** [comment]
Почему у меня боты на БГ 70 уровня, а персонаж, создавший очередь, 80-го?
Выброс был на
```
            if (v_level <= k_grey)
                return false;
```
Это я опять где-то опцию в конфиге проморгал?

**Comment by trickerer** [comment]
`NpcBot.WanderingBots.BG.CapLevel` проверь, а с ним заодно `Expansion` и `MaxPlayerLevel`

**Comment by Bogir** [comment]
Правки смерджены. Благодарю и закрываю

**Comment by trickerer** [comment]
Закрыто будет только после обновления патчей

**Comment by Bogir** [comment]
Еще и патчи... Какой, всё-таки, это титанический труд )

**Comment by trickerer** [comment]
Я уж давно написал скрипты и для генерации патчей, и для генерации сообщений коммита со списком включённых коммитов из репозиториев АС и ТС, и даже для обновления Readme. Так что это не проблема
