### ISSUE TITLE
AC UNIT.H FIX

### ISSUE THREAD

**Issue by leewheel** [trickerer/Trinity-Bots#908]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Since AZ updated unit.h, if I use patch -p1 < NPCBots.patch command to patch, the final unit.h is a mess. I hope to update this part as soon as possible. Thank you

### TrinityCore or AzerothCore

AzerothCore

**Comment by trickerer** [comment]
https://github.com/trickerer/Trinity-Bots/commit/3b717fbc0efb70e5d805322bfa60f42a25529edb
