### ISSUE TITLE
[TC] [AC] [Question/Feature] [Group/Spell/Core] Бот ДК

### ISSUE THREAD

**Issue by DykeRz** [trickerer/Trinity-Bots#909]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Бот дк в специализации нечестивость, не использует "удар плети", призыв гаргульи. К тому же бот дк не использует "хватку смерти"

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

last

### Operating system

debian 12

**Comment by trickerer** [comment]
Хватку бот не использует по тем же причинам, по которым у друида выключен отброс от Typhoon и от Blast Wave у мага. Эффекты перемещения по параболе, вызываемые со стороны сервера, имеют нехорошую тенденцию выкидывать юнитов за пределы бытия. Кроме того, из-за несовершенства нахождения пути бот может оказаться (слегка) под текстурами и каст чего-то наподобие Хватки может притянуть игрока туда же, с обидными последствиями.

**Comment by trickerer** [comment]
https://github.com/trickerer/TrinityCore-3.3.5-with-NPCBots/commit/039ae30ffd92cdc1fe51dc13e6feccbef0d25be9
Не проверял и не помню почему выключил
С гаргульей придётся погодить немного

**Comment by trickerer** [comment]
https://github.com/trickerer/TrinityCore-3.3.5-with-NPCBots/commit/acc260a4865a16dc00b12c7843a0d32e8fb9b7a5
