### ISSUE TITLE
[AC] [Bug] Felguard Damage

### ISSUE THREAD

**Issue by Day36512** [trickerer/Trinity-Bots#911]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Warlock bot felguard damage is much lower than what it should be doing.

### Expected behaviour

Same damage as player felguard under proper conditions.

### Steps to reproduce the problem

Tested at level 60

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. 60320b97ab0a+ 2024-10-27 21:19:15 -0600 (npcbots_3.3.5 branch) (Win64, RelWithDebInfo, Static) (authserver)

### Operating system

Win10

**Comment by trickerer** [comment]
Try after https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/84b19dc02bd8347a0505140bfd169b4232fbe463
Damage for non-Guardians is calculated differently so it will never be 100% precise. I tried to balance it for level 80 of course
