### ISSUE TITLE
[AC] [Bug] Bots hardcast certain spells on weapons

### ISSUE THREAD

**Issue by Day36512** [trickerer/Trinity-Bots#912]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Bots are hardcasting spells on weapon items, such as shadow oil.

### Expected behaviour

These spells should be triggered

### Steps to reproduce the problem

1) apply shadow oil to weapon
2) give to bot
3) watch them hardcast it

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. 60320b97ab0a+ 2024-10-27 21:19:15 -0600 (npcbots_3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

### Operating system

Win10

**Comment by trickerer** [comment]
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/ffa8136f94cd7b5f6ba1b5498ec3a6fa281d0e1f
