### ISSUE TITLE
[TC] [AC] [Question/Feature] [Core] Option To Set Wandering Bots Gear Max Item Level

### ISSUE THREAD

**Issue by Zerkenn** [trickerer/Trinity-Bots#914]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

I am creating a server where there are progressive level brackets and want the ability to control the max item level wandering bots spawn with. In the level 60 bracket I want to make it so wandering bots cant spawn with item levels higher than tier 1 (Item level 66) as that will be the max item level obtainable by real players so pvp will be balanced.

Is there a way / can a feature be implemented to the logic that controls gearing wandering bots to set a max item level they can spawn with?

### TrinityCore or AzerothCore

Both

**Comment by trickerer** [comment]
This can be done, but if max item level is set too low bot may end up without most / any gear. I think instead of hardcoding a minimum item level for every bracket item selection algorithm should just fall back to a default selector in case no items were found because of maximum item level setting. That's because minimum item level may differ per item slot.
The only question is: should it affect world maps wandering bots only or BG bots as well? Probably both

**Comment by Zerkenn** [comment]
> This can be done, but if max item level is set too low bot may end up without most / any gear. I think instead of hardcoding a minimum item level for every bracket item selection algorithm should just fall back to a default selector in case no items were found because of maximum item level setting. That's because minimum item level may differ per item slot. The only question is: should it affect world maps wandering bots only or BG bots as well? Probably both

I would want it to affect all wandering bots. Thanks

**Comment by trickerer** [comment]
https://github.com/trickerer/TrinityCore-3.3.5-with-NPCBots/commit/1e1130d4799c56be2433f0f9c66a163e72ccaccd
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/8181aac9ef3d06c719cf4665e2f62aacdf728aec

**Comment by Zerkenn** [comment]
> [trickerer/TrinityCore-3.3.5-with-NPCBots@1e1130d](https://github.com/trickerer/TrinityCore-3.3.5-with-NPCBots/commit/1e1130d4799c56be2433f0f9c66a163e72ccaccd) [trickerer/AzerothCore-wotlk-with-NPCBots@8181aac](https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/8181aac9ef3d06c719cf4665e2f62aacdf728aec)

Thank you very much. This is perfect.
