### ISSUE TITLE
[TC] [Bug] [Core] Bots cant swim

### ISSUE THREAD

**Issue by DykeRz** [trickerer/Trinity-Bots#916]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Боты разучились плавать с последними коммитами и боты танки бегают вокруг цели, не адекватное поведение, так же бот танк иногда не танкует, а со стороны кидает таунт и стоит смотрит

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

last

### Operating system

debian 12

**Comment by trickerer** [comment]
Никаких изменений в позиционировании ботов в бою не было уже давно.
Чтобы проверить мне нужны настройки бота, а также общие настройки для ботов игрока. Роли, спек, расстояние до цели, при котором это наблюдается. Настройки дистанций, активные иконки и остальное что влияет на поведение ботов в бою.

Нет такого коммита `last`, завтра будут новые изменения и это `last` не будет озачать ничего.

**Comment by DykeRz** [comment]
Кажется перевключение всех настроек бота помогло, вообще все пункты, от роли, до скилов и позиционирования

Но возможно ли это сделать админу массово у всех игроков сразу?

**Comment by trickerer** [comment]
Фикс плавания: https://github.com/trickerer/TrinityCore-3.3.5-with-NPCBots/commit/27d985e03d3ebc8d4edee087f508891356faf04c

Что касается "кручения" так это очень редкий случай и скорее связанный с нестабильностью ориентации мобов в бою и это баг ядра (обоих), заметил такое лишь пару раз - первый примерно 5 месяцев назад, может больше.

> Кажется перевключение всех настроек бота помогло, вообще все пункты, от роли, до скилов и позиционирования
>
> Но возможно ли это сделать админу массово у всех игроков сразу?

Такое решение меня точно не устроит и помогать в его поиске я не стану. Потому что решение должно быть общим, а не для конкретного сервера.

**Comment by trickerer** [comment]
Теперь по поводе оформления.

Во-первых: три проблемы в одном. Это неправильно, потому что:

Во-вторых: нет способа воспроизведения. Если проблема не очевидна, то у меня нет времени производить случайные действия, надеясь на воспроизведение указанной проблемы. А здесь все три проблемы - разные и друг с другом никак не связаны. Всё что здесь представлено это **кратчайшее описание трёх проблем в двух строках**, даже без скринов. Это не багрепорт - это жалоба, жалобы я принимаю только в дискорде и по почте, а здесь - багтрекер. Про ревизию написал выше.

В-третьих: это уже далеко не первый случай столь феерического оформленния и это ~~злостное~~ игнорирование правил оформления, чесслово, уже начинает по-немногу раздражать.

Итого: независимо от причины, а просто потому что с подобными "багрепортами" **тяжело работать** (и раздражаться я не люблю), предупреждаю, что в будущем, вероятно, подобные жалобы рассматриваться будут лишь в первом приближении, и, если проблема не очевидна, закрываться как инвалидные без дальнейших рассуждений. Надеюсь на понимание.

**Comment by DykeRz** [comment]
понял

**Comment by trickerer** [comment]
Репорт должен оставаться открытым до тех пор, пока связанные изменения не будут добавлены в патч(и).
