### ISSUE TITLE
[AC] [Bug] [NPCBOTS] Minor Mistake

### ISSUE THREAD

**Issue by Boxhead78** [trickerer/Trinity-Bots#917]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Hello, I just saw that randomly. I do believe there is a minor mistake in botdatamgr.cpp line 326 max_expansion_level of WotLK. It should be 80 instead of 70 or I'm interpreting the code incorrectly.

![grafik](https://github.com/user-attachments/assets/56858836-f6f9-40e0-aa2c-c5165cc2e643)

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

262a8ed703a0298d09acd523579b242db3bfdef3

**Comment by trickerer** [comment]
Good catch, thanks.
Copypaste errors. Bane of my existence

**Comment by Parkan1986** [comment]
That's why if NpcBot.WanderingBots.BG.CapLevel = 1 was set to 1 and player level is beyond 70 the bots on bg generated level 70 max

**Comment by trickerer** [comment]
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/9289fb8c539c2efdb51027cdacb025cd26c1fb48

**Comment by trickerer** [comment]
The issue should only be closed when related code is merged into patch(es). You don't need to worry about it
