### ISSUE TITLE
Undefined String Locale Text

### ISSUE THREAD

**Issue by JamesHoffer** [trickerer/Trinity-Bots#92]
Been awhile, but I compiled the latest version, when I speak to an NPC Bot in game, all the text is saying "undefined string"
In the world window, I'm getting "NPCBots: bot text string #70445 is not localized, at least for enUS" 
Never had this issue before, did you remove the EnUs text? or is there a setting on my end that I'm missing? 
Also, is there a way to ask a question without opening up an issue? a direct email, or question area?

**Comment by Parkan1986** [comment]
I think you forgot to add sqls to db to use npcbots. Look to sql/update  folder

**Comment by trickerer** [comment]
You need to apply SQL files from `sql/Bots/updates/world/` to your world DB

**Comment by JamesHoffer** [comment]
Seems like when I merge the files into one, it's not working properly. I individually imported each file from updates/world, and it works now. Do you know a better merge script then "copy *.sql merged.sql" ? Thanks for the help.

**Comment by trickerer** [comment]
Make sure the merge scripts file is in `sql/Bots/` folder when you run it. If it didn't work then I'd like to see the contents of a resulting file.

> Do you know a better merge script then "copy *.sql merged.sql" ? 

Not really. There *was* a `type` command also up to Vista, but since Win7 it doesn't exist anymore.
