### ISSUE TITLE
[TC] [Question] [Core] Бот обсидиановый разрушитель

### ISSUE THREAD

**Issue by DykeRz** [trickerer/Trinity-Bots#920]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Привет, почему боту Обсидиановому разрушителю (sphynx) запрещено носить шеи, серьги и кольца?

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

TrinityCore rev. cb1ad2958701 2024-11-09 16:15:26 +0300 (main branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon)

### Operating system

debian 12

**Comment by trickerer** [comment]
Потому что ему их некуда надеть, он же каменный :smile:
Это чисто ролевой элемент, конечно же, как и то, что он подчиняется игроку по причинам, не вполне понятным. Баланс урона с ним соблюсти почти невозможно, но его система конвертации статов в урон компенсирует отсутствие некотых элементов обвеса.

Все дополнительные классы созданы на основе юнитов 3 Варкрафта.

**Comment by DykeRz** [comment]
понятно)
