### ISSUE TITLE
[TC] [Bug] [Spell/Core] Buffs for bots

### ISSUE THREAD

**Issue by DykeRz** [trickerer/Trinity-Bots#921]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Некоторые бафы не срабатывают на ботов, а конкретнее: перенаправление бота охотника не работает на бота паладина, и каска с кулаком не стакаются, если попросить двух паладинов ботов повесить на игрока эти два бафа, они заменятся друг на друга

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

TrinityCore rev. cb1ad2958701 2024-11-09 16:15:26 +0300 (main branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon)

### Operating system

debian 12

**Comment by trickerer** [comment]
Нет такой ревизии https://github.com/trickerer/TrinityCore-3.3.5-with-NPCBots/commit/cb1ad2958701

Специально сделал свежую базу данных для этого теста.

1)
![buff1](https://github.com/user-attachments/assets/05575461-e813-4d1b-b640-b56372fc14e4)
![buff2](https://github.com/user-attachments/assets/21381814-54d1-477b-96fd-ff2132a2cd0f)

2)
https://github.com/user-attachments/assets/4dc5aa1c-9e90-4858-b935-761560a4f294

Вывод: брехня + брехня.

Игрок не может использовать спеллы, предназначенные для игроков, на ботов. Для этого есть команда `.npcbot useonbot` (`.npcb use`)
