### ISSUE TITLE
[AC] [Bug] Mob traps triggered by bots spawn lv 80 mobs regardless of current player level

### ISSUE THREAD

**Issue by Badgermilk0** [trickerer/Trinity-Bots#922]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

When bots trigger traps that spawns mobs, the enemies are created according to the Bot level regardless of the current level of the player and scaled bot level.

Example, "Warpwood Pod" in Diremaul West sometime spawns "Whip Lashers".
When NPCbot triggers the trap, the Whip Lasher will be ?? (due to player being about level 55-60 in this instance.

The same issue exists in Stratholme if the Bots trigger the Rat traps.

In the following image, the player is lv 57, the NPCbot triggered the Warpwood Pod and the enemies are level "??".
![Screenshot 2024-11-11 215657](https://github.com/user-attachments/assets/a1aad2dc-f990-4391-9cdf-6ba0e9cee906)

Same instance and player, but the player (lv57) triggered the trap:
![Screenshot 2024-11-11 215738](https://github.com/user-attachments/assets/82da455e-793e-4460-b042-b3f17dc4627c)

The following Module is also installed, no level scaling is active in the config for it.:
https://github.com/trickerer/mod-autobalance

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. 03bdf64d03a2 2024-11-09 15:23:34 +0700 (npcbots_3.3.5 branch)

### Operating system

Win 11

**Comment by trickerer** [comment]
https://github.com/trickerer/mod-autobalance/commit/807809e0f4ca966d8041c3ec09bd5fd9cd2d0f6e
