### ISSUE TITLE
[Feature] Configurable Penalties depending on NPCBot Usage

### ISSUE THREAD

**Issue by Badgermilk0** [trickerer/Trinity-Bots#924]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Feature Dialog / Request

Ability to impose additional _optional_ restrictions and penalties depending on NPCBot usage.
The goal would be to give some additional balance when using bots in various settings.

Penalties should be configurable separately depending on setting:
World
Dungeon
Raid

**A number of penalty questions / suggestions**

- Activate Percentage reduction of gold in relation to amount of NPCbots.
Example
1 player + 1 bot = 50% money recieved by player
1 player + 2 bots = 33% money recieved by player
1 player + 3 bots = 25% money recieved by player

- Trash Mob Loot Reductions
Configurable loot penalties per rarity for:
Grey, white, green, blue, purple, orange
Options could include:
Bot owner gets all, Group Split, % reduction (ex. every 3 mob gets removed)

- Boss Mob Loot Reductions
Same as Trash Mob

- Changes (or new parameter) to XP penalty to mimic BlizzLike behaviour
Modifiers:
1 person group = 1.0
2 person group = 1.0
3 person group = 1.166
4 person group = 1.3
5 person group = 1.4
Example: XP = MonsterXP/numberOfMembers * modifier.
1 player + 1 bot = 50% XP recieved by player
1 player + 2 bots = ~39% XP recieved by player
1 player + 3 bots = ~33% XP recieved by player
1 player + 4 bots = ~28% XP recieved by player

### TrinityCore or AzerothCore

AzerothCore

**Comment by trickerer** [comment]
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/09cc3efe47b942ba331a6843e37c1513ea3b5f94
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/a88b9b55dbb33fdc146d564f25ee1a6129022013

Loot penalties won't happen. Same for per map type filter.
