### ISSUE TITLE
[TC] [Question] [Core] Боты удалённых персонажей

### ISSUE THREAD

**Issue by DykeRz** [trickerer/Trinity-Bots#925]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Как освободить ботов от удалённых персонажей массово или по одному или у старых персонажей, которые долго не входили в игру?

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

TrinityCore rev. f2e12b8e4ba3 2024-11-15 20:58:49 +0300 (main branch) (Win64, Debug, Static) (authserver)

### Operating system

debian 12

**Comment by trickerer** [comment]
При удалении персонажа (в клиенте) боты отвязываются автоматически. Если возникла необходимость отвязать бота через БД то это делается в таблице `characters_npcbot`, достаточно поставить `owner=0` и перезапустить сервер. Также можно отвязать владельца в игре у бота на спавне через `.npcbot set owner 0` или через дебаг меню в режиме ГМа

**Comment by trickerer** [comment]
Предметы останутся на боте.
Снять предметы с занятого бота можно в игре командой `.npcbot free` - она вернёт предметы либо владельцу (если найдётся), либо ГМу (кто использовал команду) и освободит бота от владения
