### ISSUE TITLE
[Feature] Configurable reward for WanderBots in the world

### ISSUE THREAD

**Issue by Badgermilk0** [trickerer/Trinity-Bots#926]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Possible to get an option to manipulate the reward from Wanderbots in the world - currently they can drop very powerful items.

Suggestion is to add a config parameter to enable/disable item drops from wanderbots in the world.

### TrinityCore or AzerothCore

AzerothCore

**Comment by trickerer** [comment]
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/5a57c291f4004d8ec75d93552cd8878a3a260ea2
