### ISSUE TITLE
[AC] [Bug] [Bot gear bank] Bot fails to equip Equipment Set

### ISSUE THREAD

**Issue by Badgermilk0** [trickerer/Trinity-Bots#927]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Items existing in Bot gear bank with Eruipment set created and tied cannot be equipped by bot.

I can withdraw all items from Bot gearbank, and then re-equip them "manually".

Config:

- NpcBot.GearBank.Enable = 1
- NpcBot.GearBank.Capacity = 40
- NpcBot.GearBank.EquipmentSets = 10

### Steps to reproduce the problem

1) Create Equipment set from Bot Equipped Items
2) Use "Unequip all (gear bank)
3) Open your created Gear set and click <Equip>
4) Bot whispers "Failed(11)" - no items are equipped

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. d719c662fc80 2024-11-16 06:49:57 +0700 (npcbots_3.3.5 branch)

### Operating system

Win 11

**Comment by trickerer** [comment]
Error code `11` means bot can't combine set items in main hand and off-hand slots.
What does bot have in its MH / OH slots when you're trying to equip the set?
What does the set have for MH / OH slots?

**Comment by Badgermilk0** [comment]
See screenshots for MH, OH and Ranged:
![image](https://github.com/user-attachments/assets/7b2d22a4-484a-4628-a86c-b54b11a76f54)
![image](https://github.com/user-attachments/assets/940c5272-c631-4100-a7cb-c6e08e141942)
![image](https://github.com/user-attachments/assets/afa8685a-282a-4205-8702-dae0f0fc31c4)

**Comment by trickerer** [comment]
Good, that's the answer to my second question. But.
> What does bot have in its MH / OH slots when you're trying to equip the set?

**Comment by Badgermilk0** [comment]
Sorry, missed that one.
He as Default (no gear):
![image](https://github.com/user-attachments/assets/ca1849d0-0714-4e59-88bd-1d40954bfac2)

**Comment by trickerer** [comment]
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/603e2b530072de3f89b24cb7e472e19507443a0a
