### ISSUE TITLE
AC Build guide incomplete

### ISSUE THREAD

**Issue by joshjoshajosh** [trickerer/Trinity-Bots#928]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [x] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

I don't see the scripts for AzerothCore for installation step 7, I tried the sql scripts from Trinitycore but the tables are laid out differently so they don't import. As a result, worldserver.exe does not start.

### Expected behaviour

The install guide says there should be bot scripts to complete the build, or it should work without them.

### Steps to reproduce the problem

Download AzerothCore+NPCbots
Build

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. unknown 1970-01-01 00:00:00 +0000

### Operating system

Win10

**Comment by joshjoshajosh** [comment]
Ok I found them in the AC folder of this git, I thought it was all in the npcbots core

**Comment by joshjoshajosh** [comment]
Urgh now there's no 'creature_template' table in 'acore_world'

**Comment by joshjoshajosh** [comment]
Ok I wiped the database with the files in the create folder, and then it worked on the next build. I've also applied the scripts in the AC folder, not sure if they were actually necessary as the server started first time this time.

**Comment by trickerer** [comment]
https://github.com/trickerer/Trinity-Bots/commit/82e98403edcdcf7b2e0da50ddd039cb2a4b91b68

<details><summary>P.S.</summary>
<p>


![fine](https://github.com/user-attachments/assets/1aceea24-dd98-403c-bc3a-04a1ba85caf5)

</p>
</details>
