### ISSUE TITLE
[AC] [Enhancement] Wanderbots in Free-for-all PVP ruleset attacks player that is not PVP flagged

### ISSUE THREAD

**Issue by Badgermilk0** [trickerer/Trinity-Bots#929]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Currently, using a FFA ruleset causes Wanderbots of "your" faction to attack you in non-pvp zones, such as the lv 1-10 zone with no option to retaliate.

You as a player cannot attack the wanderbot in the sanctuary zones but they can attack you.

gametype = 16 in worldserver.conf
"16 - (FFA_PVP, Free for all PvP mode like arena PvP in all zones except rest
                         activated places and sanctuaries)"

Is it possible to make it so the NPCbots cannot attack players in sanctuary zones if you use a FFA pvp mode?

### Steps to reproduce the problem

1) set gametype = 16 in worldserver.conf
2) spawn wanderbots in low-level brackets
3) encounter a wanderbot

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. d719c662fc80 2024-11-16 06:49:57 +0700 (npcbots_3.3.5 branch)

### Operating system

Win 11

**Comment by trickerer** [comment]
In sactuary zones (like Dalaran) bots and players cannot attack each other.
In FFAPvP mode level 1-10 zones aren't sanctuary zones and players of the same faction can attack each other so what you propose wouldn't be the right thing exactly. But players should be able to retaliate to bots' attacks of course.

https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/b44d931d9e3c812211c3e43e42cf74306a0e66e3
