### ISSUE TITLE
[AC] NPCBots do not attack targets "friendly" to Possessed Players

### ISSUE THREAD

**Issue by Badgermilk0** [trickerer/Trinity-Bots#930]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

NPCBots currently do not attack Enemies that are temporary Friendly to the PC due to possession of the Player Character.

Example:
The Boss Baroness Anastari (npc=10436) casts the spell Posession (spell=17244) .

This causes Baroness Anastari to becom temporarily friendly to the PC, NPCbots now treats Anastari as a Friendly target and will not attack.

The PC will kill off all the bots since he is under possession spell.

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. d719c662fc80 2024-11-16 06:49:57 +0700 (npcbots_3.3.5 branch)

### Operating system

Win 11

**Comment by Badgermilk0** [comment]
This might be even more complicated as the spell "Possession requires the party to attack the mind controlled player to 50% health for the possesion to break and bots does not attack the mind controlled player (usually desired state).

It also seems the NPCbots will continue to attack the temporary friendly MOB if they were already attacking when the possesion spell went of, but the enemy is now immune to damage.

**Comment by trickerer** [comment]
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/ecd530dcd84c6b660a16f321e4cd531327aacee4
