### ISSUE TITLE
[TC] [Crash] [Core] Segmentation fault in worldserver when using WanderingBots

### ISSUE THREAD

**Issue by TixanSin** [trickerer/Trinity-Bots#931]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

After updating to the newest TC + NPC Bots version from 2024-11-15 21:21:48, worldserver crashes ( Segmentation fault ) seconds after it begings to spawn wandering bots. If I disable the wandering bots, the server seems to run stable.

I am getting this error during startup, but I believe that this was also the case with the last version. Sounds like that error may be related with the crash...

Setting up wander map...
No valid Neutral spawn node for at least level 60 on non-continent map 30.
No valid Neutral spawn node for at least level 60 on non-continent map 489.
No valid Neutral spawn node for at least level 60 on non-continent map 529.
No valid Neutral spawn node for at least level 60 on non-continent map 566.

### Expected behaviour

No crash

### Crashlog

https://gist.github.com/TixanSin/7e582630418de89bdeef4cb99b654772

### Steps to reproduce the problem

Use Wandering Bots and run server.
NpcBot.WanderingBots.Continents.Count = 200
worldserver crashes after a few bots were created.

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

TrinityCore rev. 53a2ee4587d7 2024-11-15 21:21:48 +0000 (npcbots_3.3.5 branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon) ready...

### Operating system

Debian 12

**Comment by DykeRz** [comment]
give us your Server.log

**Comment by trickerer** [comment]
> I am getting this error during startup, but I believe that this was also the case with the last version. Sounds like that error may be related with the crash...
>
> Setting up wander map...
No valid Neutral spawn node for at least level 60 on non-continent map 30.
No valid Neutral spawn node for at least level 60 on non-continent map 489.
No valid Neutral spawn node for at least level 60 on non-continent map 529.
No valid Neutral spawn node for at least level 60 on non-continent map 566.

This isn't an error and isn't related to the crash.
Crashlog indicates tha bot data was not found for some reason during a chained spawn of a bot triggered by a wandering bot spawning and loading the grid.

**Comment by TixanSin** [comment]
[Server.log](https://github.com/user-attachments/files/17791742/Server.log)
Here is the Server.log

**Comment by trickerer** [comment]
This is probably not related to wandering bots.

Try teleporting to Gadgetzan (or `.npcb wp go 2146`) and check the bots you have spawned within the grid (533 yd) - see if you get the same crash.

**Comment by TixanSin** [comment]
Interesting.. So going to Gadgetzan with WanderingBots enabled is impossible since the server crashes pretty much after startup.

So I
- set NpcBot.WanderingBots.Continents.Count to 0
- started worldserver
- teleportet to Gadgetzan
... No Crash, and no bots to be seen. I had manually placed some bots there though. (in other places as well)

So I reimported the previously exported sql files for my manually placed bots. 
(Entries in world -> creature & characters -> characters_npcbots)
Restarted, and now everything is back to normal...

When I enable WanderingBots now, I get no crash, so problem seems to be solved. That is great. Thank you. :-)

I dont quite understand why my missing bots would have caused a crash with the WanderingBots enabled. Those entries arent there by default. Why did those entries positively affect the WanderingBots?

**Comment by trickerer** [comment]
NULL bot data at spawn means bot was spawned but then its record was removed from `characters_npcbot` table while bot still exists in `creature` table. Such bots won't spawn at server startup and it's strange you had no crash loading the grid at their location.
In any event, I'll have to add an assertion at bot initialization and that should solve most such cases. Currently it's checked at a different point of execution.

**Comment by TixanSin** [comment]
Yes, your characters_bots.sql in updates folder droped my characters_npcbot, so only the entries in the creature table remained. I simply forgot to add my bots after the update.

A message to the log would be helpful if there was a world/creature that matches the ID of the npcbots creature_template and if no corresponding characters_npcbot entry exists. Because that table gets wiped with every update while the world/creature database remains.

Thanks for your assistance. Case closed. :-)
