### ISSUE TITLE
[TC] [AC] [Question] [Spell] How to operate the soul binding of NPCBOTS warlocks

### ISSUE THREAD

**Issue by moncat2005** [trickerer/Trinity-Bots#933]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

The player carries several warlocks in the dungeon, but discovers that the warlocks in NPCBOT have not executed the employer's soul stone binding.
How to operate and implement the resurrection skill soul stone binding for warlocks?

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. 862376f 2024-11-18 12:59:29 +0800 (npcbots_3.35 branch) 

### Operating system

ubuntu 22.04

**Comment by Badgermilk0** [comment]
I'm not sure how it works, but my warlock threw a soulstone on me when I am in a party with it, see image below:
(I can't force it however, it is not available in the Manage abilities section)

![image](https://github.com/user-attachments/assets/183eb1f5-0f9d-45a9-8a40-2dc962b9432c)

**Comment by trickerer** [comment]
Currently players can't regulate warlock bot's soulstone usage policy, neither can they order a bot to use a soulstone on someone. So it's all automatic.
Dungeon or not, the rules are the same and are very simple:
1. Any player in group of class capable of resurrecting others i.e. healers
2. Same as (1) but checking bots this time
3. Any group member

There is also a core bug (tested only on TC) where targets below level 20 cannot be targeted by Soulstone Resurrection spell (even if cast by player) despite its rank 1 being level 18 spell (should allow targeting level 8 in theory). But I guess I'm not 100% sure, maybe that's just me being silly. I any case, no soulstone below level 20.
Bots also won't use soulstone on other bots in BG.

**Comment by DEV7163** [comment]
> Currently players can't regulate warlock bot's soulstone usage policy, nor can they order a bot to use a soulstone on someone. So it's all automatic. Dungeon or not, the rules are the same and are very simple:
> 
>     1. Any player in group of class capable of resurrecting others i.e. healers
> 
>     2. Same as (1) but checking bots this time
> 
>     3. Any group member


It doesn't seem to be working this way for me.
Currently I have the warlock randomly using the soulstone on itself, when I have 2 other players able to ress, lvl 70 druid and paladin.
