### ISSUE TITLE
[Feature] Configurable rent cost over time for NPCBots that is bound

### ISSUE THREAD

**Issue by Badgermilk0** [trickerer/Trinity-Bots#940]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Are there any other ways to associate cost with time usage?

Perhaps a "rent per hour" cost that can be configured?
example:
X Money per started TIME per bot gets removed from your coins when player is online AND the bot is BOUND, using the same scaling you have for the lease cost (so it varies depending on the player level).

Failure to "pay" causes the bot(s) to get forcefully removed from your ownership.

I think with this addition, there are plenty of different ways to configure and balance usage on the server.

### TrinityCore or AzerothCore

TrinityCore

**Comment by trickerer** [comment]
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/8ccb8f49a3cb6855ff4782ad21bbf68e1bab8d5e
Never liked this crap in games. Disabled by default
