### ISSUE TITLE
[AC] [Question] [Group/Core] Bot disappears during BG if queued from party

### ISSUE THREAD

**Issue by Shadowcoldzx** [trickerer/Trinity-Bots#943]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Hi,

Brand new guy here - just got to install this a few days ago so don't really know the background/history. Could be a new thing, could be a known thing, this is just a question to figure this out (might be a potential bug report if confirmed..)

# Problem description
Queueing battlegrounds with NPCBots in group seems broken
* The bot will not buff other wanderer-generated bots, but it will get buffed by them
* The bot will follow you until the first engagement, shortly after that (and sometimes during) it will "disappear"
* The bot continues to remain in the BG, it just simply occupies a slot but is otherwise out of existence

What does "disappear" mean
* It shows alive and owned via .npcbot info
* It appears on the minimap
* It can be selected via raid frame, but seems as if it was not in the instance
* It's MP does not regenerate (as if it was out of existence..)
* It does not respond to `.npcbot recall teleport` instead you get "You can't do this in combat" error, despite being out of combat myself and even having `.gm on`

After leaving the battleground, the bot will teleport to my position, it still has buffs/debuffs from when it disappeared (such as mid-duration power infusion), and it's MP starts to regenerate.

# Notes
* I have tested this with 1 bot in a party at a time, once with a pre-existing "standard" bot, and again with a custom made one using `.npcbot createnew`
* I have only tested this at 10-49 brackets, not at 80
* sure I modified the code a bit, but NOTHING that tinkers with what I'm observing - I just did a bug fix to even get BGs to start (which was later already committed as far as I can see), changed some AI behaviour, added a min level to wanderer generator (sets bots at <5 levels below capped at '0 to prevent grays)

# Steps to reproduce
* Fresh install at https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/dc9d4972c3fb799b5cf4a1be29f18f96e4f53c7f
* Include this commit on top, otherwise BGs will crash on enter: https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/f588a094d40fd0e08c911e8b8fc3216cd10f5d77
* Mods used: ah-bot, random-enchants, autobalance, solo-lfg
* Ensure that wanderers are enabled and can join bgs
* Make a character, set it to higher level such as `.character level 49`
* Hire an NPCBot, any should do
* Queue for a BG as party (such as Arathi Basin)
* Start the game, get into an engagement (does not matter if you survive or not)
* The bot should disappear during or shortly after the first engagement

As there are no logs for this (other than trying to enable and dig through them blindly..), this is just a question for now to confirm that what I'm seeing is a common problem.
Though I cannot tell where that problem is yet. As I'm new, I don't know if this was always the case (can't see any report!?).

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. dc9d4972c3fb+ 2024-11-30 00:50:58 +0000 (npcbots_3.3.5 branch) (Win64, RelWithDebInfo, Static)

### Operating system

Win10

**Comment by Shadowcoldzx** [comment]
[worldserver.conf.txt](https://github.com/user-attachments/files/17987191/worldserver.conf.txt)
[core_changes_diff.txt](https://github.com/user-attachments/files/17987192/core_changes_diff.txt)

also here's worldserver conf, and since I mentioned to have done some changes, also a diff to dispel any doubt (not many, and as you can see, nothing that can interfere)

**Comment by trickerer** [comment]
Using https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/f588a094d40fd0e08c911e8b8fc3216cd10f5d77
Here I'm in Arathi Basin at level 45 with 29 bots of which 1 is mine and he did not disappear anywhere despite multiple combat encounters

![dis](https://github.com/user-attachments/assets/a7ddb394-b96a-4141-9b5e-fdaeef945685)

This is just a regression from https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/9caa91924c0efc6cffe36dea346d7e82de652e4a, was fixed already in https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/cde40813c0fae7ce8541a8a680db1959cce75ab6

Just update your core

**Comment by Shadowcoldzx** [comment]
Nice thanks, I'll give that a try.

**Comment by Shadowcoldzx** [comment]
Yup, latest updates fixes this, now my pocket healer stays in the game.
