### ISSUE TITLE
[TC] [AC] [Bug/Crash] [Group/Spell/Core] BG Crash world.exe on startup

### ISSUE THREAD

**Issue by darkness3285** [trickerer/Trinity-Bots#947]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

[00eeb0051a2a+_worldserver.exe_[6-12_13-33-36].txt](https://github.com/user-attachments/files/18052665/00eeb0051a2a%2B_worldserver.exe_.6-12_13-33-36.txt)

### Steps to reproduce the problem

When starting a bg, at the time of creating the bots, 10/15 seconds pass and the world.exe crashes

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. 00eeb0051a2a+ 2024-12-06 12:19:03 +0100 (master branch) (Win64, Release, Static) (worldserver-daemon)

### Operating system

Win 10

**Comment by trickerer** [comment]
Post a Debug crashlog

**Comment by darkness3285** [comment]
> Post a Debug crashlog

Sorry but the crashlog file is empty. The only crash file is the one I uploaded. And one thing I'm only using ahbot as a module.

**Comment by trickerer** [comment]
It doesn't crash for me and Release crashlog is useless.
Just make a Debug build and crashlog will contain all the required info.

**Comment by davvvve1** [comment]
I had a crash too (segment fault ) .  It was latest mod-ah   that did it.
