### ISSUE TITLE
[TC] [AC] [Feature] [Core] Wintergrasp

### ISSUE THREAD

**Issue by Conan1996-2** [trickerer/Trinity-Bots#948]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Is it possible to add Wintergrasp to the list of BGs in your config files? I have started playing with mapping it out but I'm unable to have bots spawn/despawn without the config files set.

### TrinityCore or AzerothCore

TrinityCore

**Comment by trickerer** [comment]
It's rather funny how this description assumes that all that is needed to enable bots in Wintergrasp is a config option.

No, Wintergrasp is not a BG, it's a Battefield - a region within a **world map** with a PvP event taking place on a timer. There is no support for that in bot code. Also the problems I've described in https://github.com/trickerer/Trinity-Bots/issues/937 apply here as well. Honestly I doubt it will ever be implemented.

**Comment by Conan1996-2** [comment]
Good to know, thanks
