### ISSUE TITLE
 [AC] [Question] [Core] NPCBOT is unable to pick up loot above green.

### ISSUE THREAD

**Issue by moncat2005** [trickerer/Trinity-Bots#949]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Player feedback this week: In the latest version, NPCBOT is unable to pick up loot above green.
Only white and gray can be picked up.

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. a32b7ba 2024-12-07 13:25:27 +0800 (npcbots_3.35 branch) 

### Operating system

ubuntu 22.04

**Comment by trickerer** [comment]
It's because loot method is no longer forced for bot groups. Player has to select loot quality threshold, bots will only autoloot items of quality below group loot quality threshold.
Just gotta change the logic a bit and make bots ignore the threshold in case there is only one player in group

**Comment by trickerer** [comment]
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/3044f42c77ff5da922c49c2426125bc987347b20

**Comment by moncat2005** [comment]
The loot of NPCBOT is normal.
thank you!

**Comment by trickerer** [comment]
https://github.com/trickerer/Trinity-Bots/commit/b2f417d32bec73e86f58906b9d183ec677bf5dec
