### ISSUE TITLE
updates

### ISSUE THREAD

**Issue by iceyman** [trickerer/Trinity-Bots#95]
just wondering how often will this get updated ? to like the latest TrinityCore?

only asking due to installed Trinitycore [#26494
](https://github.com/TrinityCore/TrinityCore/commit/cd853118b6cc215676cd7a4661c0b91575e5650a)  and NPCbots dont install

OS windows server 2019

**Comment by trickerer** [comment]
Since I don't really play anymore and have little free time in general, I mostly update on demand, or if I get build errors in [patched repo](https://github.com/trickerer/TrinityCore-3.3.5-with-NPCBots).

https://github.com/trickerer/Trinity-Bots/commit/99a01833aee1be80a409039668fa4982b541c967

**Comment by iceyman** [comment]
OK Thanks for updating :D i'll have to learn how to if it myself one day soon :D i haven't played in year but a few mates and i wanted to play again :D
