### ISSUE TITLE
[AC] [Bug] [Core] In the latest version, NPCBOT often cannot escape combat mode after battles.

### ISSUE THREAD

**Issue by moncat2005** [trickerer/Trinity-Bots#950]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Player feedback this week: In the latest version, NPCBOT often cannot escape combat mode after battles.
The player tried to test it with a hunter, and even when the hunter confirmed their withdrawal from the battle by feigning death, NPCBOT remained in combat.
In the latest version, it is no longer allowed to call back to the current position during combat, so the performance is particularly evident when controlling NPCBOT.

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. a32b7ba 2024-12-07 15:39:27 +0800 (npcbots_3.35 branch) 

### Operating system

ubuntu 22.04

**Comment by trickerer** [comment]
Combat bug **IS** a thing, there is nothing new about that. Man, combat bug happens even of retail.
Usually happens in dungeon, from my exeperience it's a critter most of the time affected by AoE non-damaging ability. Players can either teleport to another map (re-enter dungeon) or use `.npcbot kill` command in combination with combat stopping ability (feign death, invisibility), or just find the offending critter and kill it ~~with fire~~.

If you're sure it's nothing of the like and actually is a bug on bots' behalf, then I need a location and bots selection to test it myself. `.debug threat` and `.debug hostil` output could also help.

**Comment by trickerer** [comment]
Found it. There is actually a mechanism players have which cancels combat with enemies outside of visibility range in non-dungeon maps. Now bots will have this too.

https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/0355ccfe41c16d2813bd7243316f7cbc1bab454c

**Comment by moncat2005** [comment]
That's great！
I have compiled and updated the worldserver, waiting for further feedback from players.
