### ISSUE TITLE
[AC] [Bug] [Core] Blizzlike EXP Reduction Not Working As Expected

### ISSUE THREAD

**Issue by Zerkenn** [trickerer/Trinity-Bots#952]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

```
NpcBot.XpReduction.Amount              = 0
NpcBot.XpReduction.StartingNumber      = 2
NpcBot.XpReduction.Blizzlike.Enable    = 1
NpcBot.XpReduction.Blizzlike.GroupOnly = 1
```

With the above config bots in groups are increasing xp gained instead of lowering xp gained.

### Expected behaviour

Xp reduction per bot invited to the group should be blizzlike as if they were real players.

Apologies if I am misunderstanding this config. But with the config above I assume this would mean xp calculations in groups should be blizzlike with any combinations of bots and players?

### Steps to reproduce the problem

1) Kill a level 1 enemy at level 1 = 50 exp gained
2) Hire and add a bot to the group and kill a level 1 enemy = 50 exp gained
3) Hire another bot, add to the group and kill a level 1 enemy = 58 exp gained

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. 505113dfcd24+ 2024-12-14 09:36:13 +0700 (npcbots_3.3.5 branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon)

### Operating system

Debian 12

**Comment by trickerer** [comment]
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/5aab2aea73b689686a5b6c300a74d5b160c53c48
