### ISSUE TITLE
[AC] [Bug] [Core] Rare Bots on Battlegrounds

### ISSUE THREAD

**Issue by Ramvaris** [trickerer/Trinity-Bots#953]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

Rare Bots like the Nerubian are appearing on battlegrounds like Arathi since the last update cycle.
They didn't appear before. At least I have never seen them.

The battleground (Arathi) had 8 vs 16 - which was also odd - but the side with the rare bots (The 8 player side) won without any chance for the enemy.

### Expected behaviour

Rare Bots should not be on battlegrounds since they are borderline overpowered.
If they are nerfed and this is an intended behaviour, then sorry for opening this issue.

### Steps to reproduce the problem

1) Join a random battleground

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

AzerothCore rev. 505113dfcd24 2024-12-14 09:36:13 +0700 (npcbots_3.3.5 branch)

### Operating system

Ubuntu 24.04.1 LTS

**Comment by trickerer** [comment]
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/f669eb84cabdd986a5bcc230494a331564728ba1

> The battleground (Arathi) had 8 vs 16 - which was also odd - but the side with the rare bots (The 8 player side) won without any chance for the enemy.

What you've seen is how client determines team for the race. It's 12v12. Most extra classes use non-player races and the team they join is undefined (probably default to Alliance). Same thing with player's bots - player can hire bots of any race by default, but in BG their team displayed on a scoreboard is calculated by the client.

Currently extra classes should not join BGs (undefined behaviour). I noticed Obsidian Destroyer not having any gear besides weapons, some other problems surely exist. I'm not even talking about balance

**Comment by Ramvaris** [comment]
Hmm. That really seems to be an unwanted behaviour then. I also had no Bots with me since I disabled hiring Bots because I just want them for random world meetings on a 3 people private server and battlegrounds. Dungeons are scaled to the player amount so no bots needed here.

I have seen that you changed some code here - so did you try to fix this behaviour? I would test it then if you have and see if the Nerub shows up again over the next days.

**Comment by trickerer** [comment]
> I have seen that you changed some code here - so did you try to fix this behaviour? I would test it then if you have and see if the Nerub shows up again over the next days.

Yes, should be fixed now
