### ISSUE TITLE
[TC] [AC] [Question/Feature] [Group/Spell/Core] Avoid logging to TC console

### ISSUE THREAD

**Issue by RM6SS62** [trickerer/Trinity-Bots#955]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
- [X] This is NOT a bug/crash report
- [X] I've searched the bugtracker for similar questions/requests **including closed ones**

### Description

Would it be possible to suppress bots info from the TC console?
I'm being constantly spammed there about their activity, ie:

`Spawning wandering bot: Yarel (82761) class 9 race 7 fac 115, location: mapId 1 WP 60 'Nijels Point', 1 link(s) (avg weight 0), Map 1, Zone 405, Area 608, minLvl 28, maxLvl 40 (X: 164.43 Y: 1335.57 Z: 197.47), flags: 0x00000003 (Nijels Point)
Wandering bot Ansel id 82832 class 3 level 16 KILLED wandering bot Quorin id 82907 class 9 level 20 on their way to LochS!
Wandering bot Quorin id 82907 class 9 level 20 WAS KILLED BY wandering bot Ansel id 82832 class 3 level 16 on their way to LochS!`

### TrinityCore or AzerothCore

TrinityCore

### Core rev. hash/commit

TrinityCore rev. 21a4acfb283f+ 2024-12-06 19:58:33 +0100 (3.3.5 branch) (Unix, RelWithDebInfo, Static) (authserver)

### Operating system

Debian sid

**Comment by trickerer** [comment]
It's basic logging settings management. Go to your worldserver.conf and set `Logger.npcbots` to 3 (Info) of even 4 (Warn)
