### ISSUE TITLE
[TC] [AC] [Bug/Crash] [Group/Spell/Core] Textures Off

### ISSUE THREAD

**Issue by will5435** [trickerer/Trinity-Bots#956]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

![image](https://github.com/user-attachments/assets/28af19df-85d1-4cf0-889b-c90490dc643c)

Leg textures and face textures are being swapped

### TrinityCore or AzerothCore

Both

### Core rev. hash/commit

AzerothCore 3.3.5a  -  www.azerothcore.org

**Comment by trickerer** [comment]
The problem is in your client HD textures mod, not NPCBots code

**Comment by trickerer** [comment]
#409
#713
#811

**Comment by will5435** [comment]
Yes, I used a different Repack and it worked thank you!
