### ISSUE TITLE
Enchants not visual on bots

### ISSUE THREAD

**Issue by beet3** [trickerer/Trinity-Bots#97]
The sword is enchanted with Mongoose, it procs for the bots but is not visual. As you can see when I inspect the sword that the bot is using, it is visual but on the bot it's not.

![WoWScrnShot_050521_013638](https://user-images.githubusercontent.com/83679106/117083090-254b3800-ad44-11eb-8244-e286e74efaea.jpg)
![WoWScrnShot_050521_014045](https://user-images.githubusercontent.com/83679106/117083091-267c6500-ad44-11eb-9d07-1ff3164db774.jpg)
![WoWScrnShot_050521_014225](https://user-images.githubusercontent.com/83679106/117083093-2714fb80-ad44-11eb-9607-cdf6b592076c.jpg)

**Comment by trickerer** [comment]
Weapon enchant visuals are stored in player fields and bots don't have them.
