### ISSUE TITLE
Bots not compiling

### ISSUE THREAD

**Issue by Mr-Deadbeat** [trickerer/Trinity-Bots#99]
OS: Ubuntu 20.04.2 Server
TC Commit: b1242c38cc8f7e0da2343e0e1062db1e3f414d49
Bots: 99a01833aee1be80a409039668fa4982b541c967

lots of changes lately on Player.cpp among others so code won't compile at the moment

**Comment by trickerer** [comment]
I'm currently waiting on stability updates after movement system changes:
https://github.com/TrinityCore/TrinityCore/issues/26531
https://github.com/TrinityCore/TrinityCore/pull/26538
